### ISSUE TITLE
Generate stricter DKIM keys

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#112]
###### Original Redmine Issue: [112](https://dev.yunohost.org/issues/112)

Author Name: **julienmalik**

---

From man opendkim-genkeys :

~~~
       -S     (--[no]subdomains) Disallows subdomain signing by this key.  By default the key record will be generated such that verifiers are told subdomain signing is permitted.  Note that for backward compatibility
              reasons, -S means the same as --nosubdomains.

       -r     (--restricted) Restricts the key for use in e-mail signing only.  The default is to allow the key to be used for any service.

~~~

Should we use -S and -r ?
We are generating one key per yunohost domain (so including subdomain), so I guess we should enforce -S
We use "mail" as the selector, so why not restricting it to mail signing with -r ? (I don't know what else DKIM can be used for, but I guess at least we don't use it for anything else in yunohost yet).

**Comment by alexAubin** [comment]
#wontfix, the current DKIM keys are fine I guess
