### ISSUE TITLE
Allow ynh_setup_source to download non archive files

### ISSUE THREAD

**Issue by Jibec** [YunoHost/issues#1132]
for some packages, the download of binary/debian/config file is needed

But `ynh_setup_source` only accepts archive format and even assume it should be tar.gz:
https://github.com/YunoHost/yunohost/blob/unstable/data/helpers.d/utils#L164

Here is one of the many use-cases:
https://github.com/YunoHost-Apps/jenkins_ynh/blob/e2a561f4aa1ea572830ea7e9b982bf8ba351fe1f/scripts/restore#L89

**Comment by JimboJoe** [comment]
Already done here: https://github.com/YunoHost/yunohost/pull/460

**Comment by alexAubin** [comment]
Closing then ?

**Comment by JimboJoe** [comment]
I would have closed it if I had rights for that :innocent:
