### ISSUE TITLE
"service list" is broken when mariadb is installed, do we need an alias system?

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1134]
As described here https://forum.yunohost.org/t/beta-testing-phase-for-yunohost-3-0-on-debian-stretch/4798/102

```
Action
GET /services
{"locale":"en"}
Traceback
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 406, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 498, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/service.py", line 228, in service_status
    status = _get_service_information_from_systemd(name)
  File "/usr/lib/moulinette/yunohost/service.py", line 265, in _get_service_information_from_systemd
    service_path = manager.GetUnit(service + ".service")
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.systemd1.NoSuchUnit: Unit mysql.service not loaded.
```

And

```
$ systemctl status mysql
● mariadb.service - MariaDB database server
   Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-05-28 12:07:02 GMT; 25min ago
 Main PID: 832 (mysqld)
   Status: "Taking your SQL requests now..."
    Tasks: 26 (limit: 4915)
   CGroup: /system.slice/mariadb.service
           └─832 /usr/sbin/mysqld
```

Things to do : 

* fix that bugs
* doesn't crash on exception on unknown services
* we can do a quick hack for mysql/mariadb but that sucks, should we have an alias systemd instead?

**Comment by alexAubin** [comment]
Yea I guess we could add a key in services.yml for services that need to point to a different "true service name" or something like this ?

What I dont understand though is why we didnt encountered this bug earlier in tests ... I mean, isn't mariadb everywhere now ? Or maybe that's an issue happening only on stretch for some reason ?

**Comment by Psycojoker** [comment]
> Yea I guess we could add a key in services.yml for services that need to point to a different "true service name" or something like this ?

Won't work because I'm pretty sure that it's either mysql OR mariadb but that systemctl handle both situations.

I think that we have a shitty situations for migrated distribution where it's still mysql but it's mariadb for fresh installations :/
