### ISSUE TITLE
Document the new SSH feature

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1137]
The new ssh feature thing (`yunohost user ssh`) should be documented somewhere like near the end of : https://yunohost.org/#/ssh_fr

**Comment by jershon** [comment]
Check out PR https://github.com/YunoHost/doc/pull/765 for French and PR https://github.com/YunoHost/doc/pull/766 for English.

**Comment by alexAubin** [comment]
Thanks ! :astonished:

**Comment by Psycojoker** [comment]
Super cool, thanks a lot @jershon :) :heart:
