### ISSUE TITLE
Stretch: Restore a jessie backup of a php app could not work

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1140]
During restoration process we replace php5 by php7, but it breaks some restore scripts:
https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/app.py#L2195

On this nextcloud example, the restore will fail because there is no php7 path in the backup.csv
https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/restore#L79

See the nextcloud issue:
https://github.com/YunoHost-Apps/nextcloud_ynh/issues/122

**Comment by zamentur** [comment]
To fix it manually, the user could do
```
apt install archivemount
archivemount XXXX.tar.gz /mnt
cd /mnt
sed -e 's@backup/etc/php5@backup/etc/php6@g' -e 's@"/etc/php5@"/etc/php/7.0@g' -e 's@backup/var/run/php5-fpm@backup/var/run/php/php6-fpm@g' -e 's@"/var/run/php5-fpm@"/var/run/php/php7.0-fpm@g' -e 's@php5@php7.0@1' -e 's@php6@php5@1' backup.csv > backup2.csv
rm backup.csv
mv backup2.csv backup.csv
cd
umount /mnt
apt remove archivemount # important if it's on the yunohost
```

**Comment by zamentur** [comment]
I will code a fix

**Comment by zamentur** [comment]
https://github.com/YunoHost/yunohost/pull/489

**Comment by Psycojoker** [comment]
PR has been merged.
