### ISSUE TITLE
Metronome miscompiled for raspberrypi 2

### ISSUE THREAD

**Issue by hferee** [YunoHost/issues#1143]
Last version of metronome (`3.9.4+yunohost-2`) fails to install as the service does not start and fails on `Illegal instruction`.
gdb on metronomectl gives "0xb69d1ac0 in ?? () from /usr/lib/metronome/util/encodings.so" 

I rebuilt the package from source using apt-build, and it is now working fine.

Additional details: 
uname -a: `Linux _____ 4.14.50+ #1122 Tue Jun 19 12:21:21 BST 2018 armv6l GNU/Linux`

yunohost: `3.0.0.1`

**Comment by hferee** [comment]
Update: this is still the case for me on 3.9.10+yunohost-1.
Is anyone else affected by this?

**Comment by alexAubin** [comment]
Thanks for bumping the issue :wink: 

I had a look on my server (also a RPi2) and after an upgrade it's working fine.

I noticed that you are running `armv6l` but I am running `armv7l` ? Full `uname -a` : 

```
Linux _______ 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux
```

Not sure how you ended up with `armv6l` ? Can you clarify how you installed your RPi ?

**Comment by hferee** [comment]
I can't say for sure, that was quite some time ago (thanks debian/yunohost stability ;-)), but I'm pretty sure I installed it with yunohost official image for raspberry pi.
It's either that or an official raspbian install with yunohost installed on top.

So this is definitely "my fault", although I don't know how this happened.

**Comment by hferee** [comment]
Did I install the image for the wrong (still compatible) architecture?  cpuinfo seems to tell me that armv6l is the right one, but debian says that armhf will work for Rpi 2.

More info: 
`cat /proc/device-tree/model`: `Raspberry Pi Model B Rev 2`

`cat /proc/cpuinfo`:

```processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 000f
Serial		: 0000000098c256eb
```

**Comment by alexAubin** [comment]
Hmmm that's interesting ? I seem to have a different version of the board : 

```
 > cat /proc/device-tree/model 
Raspberry Pi 2 Model B Rev 1.1
```

```
 > cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 44.80
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5
[...same stuff for the 3 others procs ?...]
```

Note the `v7l` in model name ...

The fact that verrsion 1.1 would be a  `v7l` and version 2 would be a `v6l ` is a bit conterinuitive :/ ...

**Comment by hferee** [comment]
Well, I don't get it anymore: according to the wikipedia page, BCM2835 only corresponds to model A, compute module or zero, but none of the model B (and I clearly have a model B, that's for sure :D).
I guess they made quite a lot of intermediate models without naming them explicitly. I'm quite sure it was an early model 2 when I bought it though...

**Comment by hferee** [comment]
I'll close the issue then. Thanks for the help anyway!

I've run yunohost almost without issue for maybe 2 years before having this architecture clash, so it's not that bad ;-)
I guess I can't install the new version though. This might be a good excuse to buy a rpi 3 ;-)

**Comment by alexAubin** [comment]
Okay ! Thanks for the feedback anyway. Not sure what happened exactly and it's still a bit sad to have hardware that last less than 10 years I guess, but you should surely be happy with a RPi3 ;)
