### ISSUE TITLE
when creating a user from CLI (and admin too?) suggest a default email "$user@$maindomain"

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1147]
Everything is in the title.

**Comment by Psycojoker** [comment]
This is not an easy pick actually, it's related to the moulinette magic "ask_$arg-name" in the manifest :(

**Comment by alexAubin** [comment]
I would even go one step further and try to like, forbid the admin to use something else than the username as the left-part of the address ... 'cause that later creates a lot of confusion and silly issues when people try to configure email client and the email adress is not `username@domain.tld` but something like `shortname@domain.tld` ...

**Comment by cyxae** [comment]
Should be closed, it has been fixed !
