### ISSUE TITLE
"./ynh-dev kill" is a confusing command name since it DESTROY EVERYTHING

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1150]
Everything is in the title, that should be "destroy" or something like that.

Also the possibility to pick a specific vm.

**Comment by frju365** [comment]
cf. PR inprogress : https://github.com/YunoHost/ynh-dev/pull/43

**Comment by alexAubin** [comment]
~Fixed by https://github.com/YunoHost/ynh-dev/pull/43
