### ISSUE TITLE
[ynh-dev] When redoing "./ynh-dev DOMAIN VERSION" but with a different version, the previous VERISON is still used

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1151]
Due to the weird cod that modifies the VagrantFile using perl, when launching "run" for the first time the VagrantFile is modified and the name of the vm is then bind forever to the initial used box even if you used "./ynh-dev kill".

This has lead to a super confusing bug to a new contributor :x 

Also we should probably modify the VagrantFile to read a customfile (csv like?) in ruby since it's full ruby instead of doing weird file modification in perl x(

**Comment by alexAubin** [comment]
ynh-dev CLI changed quite a lot since then so that doesnt sound relevant anymore
