### ISSUE TITLE
Nginx configuration incorrectly deleted

### ISSUE THREAD

**Issue by etchevef** [YunoHost/issues#1156]
I installed yunohost on a freshly installed debian in a test environement. 

During post install, I incorrectly configured domain name as yyy.zzz instead of xxx.yyy.zzz
I corrected this from gui (create new domain xxx.yyy.zzz, set it as default, delete yyy.zzz). 

That is breaking nginx : 
$sudo nginx -t
 nginx: [emerg] BIO_new_file("/etc/yunohost/certs/test.org/crt.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/yunohost/certs/test.org/crt.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed

After looking a bit arround, I deleted /etc/nginx/conf.d/yyy.zzz.conf ; That solves the problem. I don't know why that file was not correctly deleted in the first place though.

**Comment by alexAubin** [comment]
I think that got fixed by the thing about "force deleting/clearing nginx conf from the regen-conf when deleting a domain"
