### ISSUE TITLE
[core] on CLI arguments for app installation, on bad input don't fail, reask for a new value

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1160]
Right now if you provide a bad value for an input in CLI during app installation, the whole process will stupidely crash, that sucks.

We should reask for another value instead.

**Comment by siliconninja** [comment]
Could you give an example of an app or command that has bad input? Are you using `yunohost app install [input]` or `yunohost app update [input]`?

Also, just for reference, which version of Debian is your server running (stretch or jessie)? Run `lsb_release -a` in your terminal to find it. The latest stable version of Yunohost on 3.0, which runs on Debian Stretch.

Other things to try (the above are more important):

Could you post your /etc/yunohost/appslists.json? It might be improperly formatted but the library might not catch it (Be sure to redact personal information)

Use https://jsonlint.com/ (copy your appslists.json there) and post the result. (see Other possible causes for more detail on why)

# To contributors: here's some code I found relating to app installs on the jessie-stable branch:

## Primary causes

https://github.com/YunoHost/yunohost/blob/stretch-stable/src/yunohost/app.py#L665 (the app_install function)

https://github.com/YunoHost/yunohost/blob/stretch-stable/src/yunohost/app.py#L692 (how apps in the terminal are checked)

On line 692, basically the [app list fetched from the server](https://yunohost.org/#/apps) is being checked.
The syntax for the second, third, and fourth arguments seems valid:
https://thispointer.com/python-how-to-check-if-an-item-exists-in-list-search-by-value-or-condition/

Do you need parentheses around `app in app_list(raw=True)` before `('@' in app)`? It might be that only one condition is being checked, where the app is in the app list, and the others are being ignored.
(possible short circuit evaluation)

See here for some detail on what I mean:
https://www.djm.org.uk/posts/python-multiple-line-conditions-and-all-builtin/

https://github.com/YunoHost/yunohost/blob/stretch-stable/src/yunohost/app.py#L701

This checks the app id when the app has been downloaded. Did you get to this stage where an invalid app error happened, or did it install properly?

## Other possible causes:

It might also be a bash error with escape codes or something. Here's a good reference on how input is checked and read in bash: https://stackoverflow.com/questions/4273074/sanitize-user-input-in-bash-for-security-purposes

(if nothing else works)
https://github.com/YunoHost/yunohost/blob/03f52bdd69294318dc74005480b55a10cba6230b/src/yunohost/app.py#L2303

Line 2303: It may also be something weird with how json is handled or read from the server. Specifically the json.loads function. Could you post your `/etc/yunohost/appslists.json`? It might be improperly formatted but the library might not catch it (Be sure to redact personal information)

**Comment by alexAubin** [comment]
Closing because fixed in 4.3
