### ISSUE TITLE
"systemctl didn't recognize this service ('NoSuchUnit')." in remove script when following example_ynh

### ISSUE THREAD

**Issue by Jibec** [YunoHost/issues#1162]
When following https://github.com/YunoHost/example_ynh/blob/master/scripts/remove we have this error:

> Error: yunohost.service service_status - [1177.1] Failed to get status information via dbus for service mumbleserver, systemctl didn't recognize this service ('NoSuchUnit').

This comes from `STOP AND REMOVE SERVICE` before `REMOVE SERVICE FROM ADMIN PANEL`

is it a change in Ynh 3.0 and a bug in Ynh or a bug in example_ynh?

**Comment by alexAubin** [comment]
I believe I fixed this somewhere like 2 months ago ...
