### ISSUE TITLE
Better support needed for non-web apps

### ISSUE THREAD

**Issue by julienmalik** [YunoHost/issues#1163]
See this issue : https://github.com/YunoHost-Apps/mumbleserver_ynh/issues/19
where simply introducing a "domain" setting has changed the SSO behavior.

As described in the linked issue, the root cause is here :
https://github.com/YunoHost/yunohost/blob/stretch-stable/src/yunohost/app.py#L399
where the rule for an app to appear in the portal is "having a domain setting"

Wouldn't it be better, for those kind of non-web apps, to be able to explicitely state "i don't want to appear on the portal and interfere with SSO" ? By a specific setting like "disable-sso" or "noportal" or something along those lines.

**Comment by Psycojoker** [comment]
Yeah, just defining a new variable seems to be the easiest way to do that.

**Comment by Psycojoker** [comment]
Related PR https://github.com/YunoHost/yunohost/pull/507

**Comment by Psycojoker** [comment]
Fixed.
