### ISSUE TITLE
sudo: ldap_sasl_bind_s(): Can't contact LDAP server

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1165]
Since stretch, for some reason this error shows up from time to time ... Not sure what is causing this, but an explanation might be that the slapd process/daemon gets killed for some reason.

Slapd actually shows as status "active (exited)" instead of "active (running)" which in fact looks normal (green color) if you are not paying attention carefully to the "exited" part. My understanding is that systemctl reports "exited" because the process it launched isnt running anymore.

One possible dirty fix could be to add a cron job that checks that if slapd is "active (exited)" and if so, try to restart slapd...

**Comment by Psycojoker** [comment]
Do you have a copy/pasta from this systemctl status?

I'm suspecting slapd to exit with the return code "0" which systemctl consider to be normal and won't restart the program, I already had this situation with mattermost.

If that's the case, we'll simply need to modify the system config file to consider "0" to be a failure.

**Comment by alexAubin** [comment]
I think we got rid of this at some point ... not sure exactly, might reopen later if needed.
