### ISSUE TITLE
Pre-installed images for Single-board computers with minor flaws

### ISSUE THREAD

**Issue by amuuza** [YunoHost/issues#1172]
A suggestion.

It'd be nice to have pre-installed images for boards based on the FreeScale i.MX6 platform [0], as they are almost entirely functional in freedom [1].

[0] https://en.wikipedia.org/wiki/Comparison_of_single-board_computers#CPU,_GPU,_memory
[1] https://www.fsf.org/resources/hw/single-board-computers

**Comment by alexAubin** [comment]
Closing because 4 years old, we are already struggling with maintaining other images, and we don't have any "FreeScale i.MX6" ...

**Comment by amuuza** [comment]
Yes, I understand, thanks.
