### ISSUE TITLE
Clicking "Update system" on the home page of the webadmin shouldn't trigger the update already

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1174]
Right now when you click on "Users" on the webadmin, you go to a page listing user and stuff. Same for domains, apps and etc.

But the button "Update system" triggers the update directly. This is a bit counterintuitive and launches a command that might take several minutes (even though it's an update and not the full upgrade or stuff)

Ideally we should have a dedicated screen, ideally showing the last update time - but at least a button to explicitely trigger the update.

**Comment by cyxae** [comment]
Should be closed, it has been fixed
