### ISSUE TITLE
Add posibility to hide / not display tiles in the sso

### ISSUE THREAD

**Issue by Josue-T** [YunoHost/issues#1175]
Actually when the set the path and the domain in the app settings a button is automatically created in the sso.
By example in the synapse app the url is fixed its : `domain.tld/_matrix`. But this url is just for the client to be able to connect to the server so a button in the sso is not useful.

Adding a feature (like the actuall `no_sso` feature) but which also add the path in the `app_map` could be useful.

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost/pull/507

**Comment by Josue-T** [comment]
Are you sure that issue is fixed by YunoHost/yunohost#507 ? I made this issue specifically because a had this following discussion with Bram about that

> Josué
Bonsoir,
Mais genre pour le "no_sso" ca serait aussi intéressant de pouvoir donner un path. Ca serait juste l'idée que il affiche pas la tuille. Parsque par example pour synapse le path fixé c'est domain.tld/_matrix .

> Bram (IRC)
Josu[m]: le "no_sso" ça fait juste que l'app apparait pas dans app_map
tu peux rajouter un path si tu veux
ah oui non ok je crois que je comprend
Josu[m]: synapse utilise quand même le sso ?
là c'est se faire sortir totalement du sso

> Josué
En fait l'idée qu'est que l'url domain.tld/_matrix ne soit totalement pas géré par le sso (donc pas aussi de bouton/lien dans le pannel des apps. Par contre ca réserve quand même l'url si une autre app tenterais cette url. Notament une autre instance de synapse.

> Bram (IRC)
je vois
ça fait pas ça là :/

> Josué
Mais bon déjà la avec le "no_sso" ca me paraît mieux que maintenant.

> Bram (IRC)
tu as le courage d'ouvrir un ticket sur yunohost/issues ?
bon sinon c'est chiant de montrer quel app entre en conflict

> Josué
Parce que en fait actuellement pour éviter qu'une instance soie installé sur le même domaine qu'une autre je check la config nginx mais c'est un peut crade. Ici https://github.com/YunoHost-Apps/synapse_ynh/blob/master/scripts/install#L42-L43

> Bram (IRC)
je vois :/
y avait l'idée qu'une app soit capable de réserver une valeur unique dans yunohost
pour ce genre de cas
(ça a jamais été codé)
aussi pour tout ce qui est de réserver les .well-known
ou alors les calendriers qui chopent un path spécial pour ical
on avait un conflict entre caldav (ou baikal ou agendav) et l'app calendrier de nextcloud pour ça

> Josué
Oui et il y a horde, et peut être aussi sogo qui sont dans ce cas...

**Comment by alexAubin** [comment]
Uh okay sorry /o\ Thanks for the clarification

**Comment by alexAubin** [comment]
Fixed by the new permission system in 4.1
