### ISSUE TITLE
yunohost user ssh allow <username> doesn't work

### ISSUE THREAD

**Issue by Bobcadence** [YunoHost/issues#1176]
## `yunohost user ssh allow <username>` doesn't work as expected

After a fresh install on Olinuxino LIME 2 with the v3.0, the ssh acces work only for root. 

## Actual Behaviour:
Connection failed every time. 
(No try too much, Fail2ban watching you) 

## Expected behaviour:
Allow ssh to new user like root 

## Sept to reproduce:
- Fresh install + post install
- create a user with the webUI
- On shell `yunohost user ssh allow <username> 
systemctl restart ssh`
- try a ssh connection with your user

By the way your [instruction](https://yunohost.org/#/ssh_fr) isn't very clear.

Which ssh user is stetup by default ?(root or admin)

-------------------------------------------------
I fix it by create a new local user + ssh_config:

`addgroup sshusers 
adduser alice
usermod -a -G sshusers alice`

Add on sshd_config :

`vim /etc/ssh/sshd_config`
`AllowGroups sshusers`
`service ssh restart`

**Comment by alexAubin** [comment]
Hm I'm gonna guess that this was because of the issue related to https://github.com/YunoHost/yunohost/pull/587 and assume this is fixed (in 3.4) ... Sorry about that

**Comment by alexAubin** [comment]
(Feel free to complain if this still doesn't work after 3.4 :sweat_smile: )
