### ISSUE TITLE
Add application id in `yunohost app map`

### ISSUE THREAD

**Issue by Jibec** [YunoHost/issues#1177]
when listing apps, it would be great to have the **id** when listing them (at least when having two times the same app), so we can remove it in an easier manner.

Here is an example with three weblate installed in the same server, it's difficult to know what is to remove:

```jb@jb9:~$ sudo yunohost app map
ff.jb9.fr/: Kresus
jb9.fr/baikal: Baikal
jb9.fr/date: OpenSondage
jb9.fr/ffsync: Firefox Sync Server
jb9.fr/kanboard/: Redirect
jb9.fr/merde: Weblate
jb9.fr/webi: Weblate
jb9.fr/weblate: Weblate
p.jb9.fr/: PeerTube
```

**Comment by alexAubin** [comment]
Agreed :+1: I was expecting to find the idea a few times via this command and got disappointed it wasn't there :s 

We should be careful though, as the output of this command / function is in fact used by some others commands

**Comment by Psycojoker** [comment]
FYI it appears in "--raw", not especially good UX

```
root@ynh:/vagrant/lektor_ynh# yunohost app map --raw
lektor.ynh.local: 
  /: 
    id: lektor
    label: Lektor
ynh.local: 
  /wallabag: 
    id: wallabag2
    label: Wallabag
  /zerobin: 
    id: zerobin
    label: Zerobin

**Comment by alexAubin** [comment]
Closing because meh, `yunohost app list` returns the list of installed apps nowadays ... and anyway we should focus on the webadmin, people using the CLI are usually able to dig other commands / options to find the right stuff
