### ISSUE TITLE
can't install a app using a path starting the same than an existing one

### ISSUE THREAD

**Issue by Jibec** [YunoHost/issues#1178]
When installing an application using a path that start the same an existing path, it fails.

How to reproduce:
* install a app using domain/path/
* try to install an app using domain/path1/ ==> it fails
* try to install the same app utising domain/pat => it works

Tested with yunohost 3.0.1

I'm unsure this is a feature or not, but it looks like to be related comments: https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/domain.py#L254

If this is a feature, we may wish to improve the error message.

**Comment by Psycojoker** [comment]
That's the expected behaviour as stated in the comment:

```python
# We also don't want conflicts with other apps starting with
# same name
```

I don't know which kind of conflict you could get, I wasn't in the discussion.

What's weird is that `try to install the same app utising domain/pat` works, it probably shouldn't?

That's @alexAubin decision I think, maybe he can details that.

**Comment by alexAubin** [comment]
Hmmm as far as I remember, I think when I implemented `domain_url_available`, based on the behavior of `app_checkurl` : https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/app.py#L1220

The relevant half seems to come from https://github.com/YunoHost/yunohost/commit/da7728fe7458ca04d8df9095ab903aa68efdfe68

So my guess is that it hasnt been thoroughly analyzed and we could probably adapt the behavior ?

**Comment by alexAubin** [comment]
Re-reading this, from what Jibec describe, it is weird and inconsistent that : 

- installing on /foo then /foobar is refused
- but installing on /foobar then on /foo is allowed ...

We should either refuse both of neither

**Comment by alexAubin** [comment]
Finally made a PR for this because this behavior is just stupid
