### ISSUE TITLE
php-fpm not starting on boot due to "VPN client" pool on debian custom install and x64 image

### ISSUE THREAD

**Issue by jeremy54** [YunoHost/issues#1179]
Hi,

I've only produced this on stretch but I'm pretty sure older version will have the same issue... Also not sure where to classify it so set install, but it's also a vpn client app problem, feel free to change the category.

The service php7.0-fpm is not starting on boot with this error:

# journalctl -u php7.0-fpm
Jul 25 12:01:38 test.codewreck.org php-fpm7.0[735]: [25-Jul-2018 12:01:38] ERROR: [pool vpnadmin] cannot get uid for user 'admin'
Jul 25 12:01:38 test.codewreck.org php-fpm7.0[735]: [25-Jul-2018 12:01:38] ERROR: FPM initialization failed

Because /etc/php/7.0/fpm/pool.d/vpnadmin.conf contains these two lines:

user = admin
group = admins

While I think it's a bad idea to start php processes as admin user, the reason this fails is that the admin user is defined in the ldap but not on the base system; looking at the rest of the logs slapd did start just before php7.0-fpm but probably not long enough for nslcd to realize that the user is now available.

I think the yunohost install script should create the admin:admins user on the system like it probably is in the base yunohost install (fwiw I didn't use it because the link to "yunohost iso images" https://yunohost.org/images/ is a 403 forbidden error from the only place where I could find a link to the iso that is https://yunohost.org/install_on_virtualbox )

fwiw the ldap 'admins' acount has gid 1007 which does not exist on my system so this looks weird:

# id admin
uid=1007(admin) gid=1007 groups=1007,4001(admins),4002(sftpusers)

A group 'admin' with gid 1007 ought to be created there as well, probably...

This is actually somewhat difficult to work around for normal users, as debian user management scripts won't let one adduser/useradd admin to the files as it properly notices it already exists in the ldap and will refuse to create them.
Manually editing /etc/group and /etc/passwd works as expected.While it is a bad idea

**Comment by alexAubin** [comment]
Closing because we can't do much on yunohost's side .. Imho this is an issue related to the design of vpnclient_ynh which should be integrated as a "module" rather than a webapp. (Maybe pitchum has a different point of view or a clever workaround for this)
