### ISSUE TITLE
[i18n] Linguistic plenitude

### ISSUE THREAD

**Issue by Quenty31** [YunoHost/issues#1180]
Hello!
I'm opening this issue so as to get a full experience in other languages but English :)
I have two ideas I'd like to share.
1) Let the users set a favourite language for the interface. At the moment the UI is shown in the language the browser indicates the user understand. Which is good, but for people who don't know about this setting or cannot modify their configuration, it would be useful to be able to override this mechanism.
2) Show the dates in the current language. Using moment.js to show dates and time information can help to get the linguistic plenitude. I noticed two places where there are dates in the administration panel.
You might know that I translate in Occitan, at the moment, the people from moment.js haven't merged my Pull Request so Occitan isn't available yet. So if you accept to i18n the date format with moment.js, could you import my Pull Request from here: https://github.com/moment/moment/pull/4624 ?

Il ne me reste plus qu'à vous souhaiter un bon Brique Camp :)
Amistats

**Comment by ghost** [comment]
Hi @Quenty31,
Nice one ! Yep a lot of users depend on their browser user-agent lang. May be they don't know that they can use or switch language of the UI at any time they want to :)
So +1

**Comment by Axolotle** [comment]
Web-admin users will be able to set a primary and a fallback language directly in the new web-admin settings with https://github.com/YunoHost/yunohost-admin/pull/316.

Concerning dates formatting, the web-admin will now use [date-fns](https://github.com/date-fns/date-fns) in which Occitan is not yet integrated but [someone was planing to do so](https://github.com/date-fns/date-fns/issues/2061) few months ago.
