### ISSUE TITLE
Website's packaging instructions are gone

### ISSUE THREAD

**Issue by sagaciouszu** [YunoHost/issues#1181]
Instead of posting it on twitter, I'll post it here too. I'm trying to create a package for ZNC but there's nothing being scraped for the page here

https://yunohost.org/#/packaging_apps_scripts_en

![screenshot_2018-08-21 go host yourself](https://user-images.githubusercontent.com/19918354/44419117-4b0a6180-a548-11e8-8179-2f6bc8476049.png)

It's the same across Firefox, Chrome and Edge, on my VPN or naked.

**Comment by maniackcrudelis** [comment]
It works perfectly for me with Firefox.

**Comment by sagaciouszu** [comment]
After doing some more digging, it's definitely something on my end.

I guess you can close or delete this. Sorry. :(
