### ISSUE TITLE
Raspberry Pie installable image is a .sig file

### ISSUE THREAD

**Issue by JustFishing** [YunoHost/issues#1183]
Installation direction for installing YunoHost on a Raspberry Pi does not mention how to handle a .sig file.  The YunoHost image available for download is yunohost-stretch-3.1.0-rpi-stable.iso.sig.  Installation instructions refer to etcher-electron-1.4.4-i386.AppImage, but that program only recognizes .iso images.  While it is possible to verify the .sig file, there is no procedure listed (and none readily found on the Internet) to convert the .sig file into an .iso file, or to install YunoHost directly from the .sig file.

**Comment by JustFishing** [comment]
Alexandre,

Thank you for your response!

I attempted installation of the file by renaming it without the .sig at the end.  Etcher complained that the image didn’t have a directory structure and would likely not boot.  I proceeded anyway and attempted to boot with a Raspberry PI B+, but perhaps I was too impatient, however, it looked like it immediately locked up.

Without a file structure, how it is possible to modify the installed image on a micro SD card to permit access by SSH?

Also, sorry to file a bug, but have not been able to access chat.

Sincerely,

Bill

Hbco2@hbco2.com

 

 

 

  _____

**Comment by alexAubin** [comment]
This was kind of a bug so it's fine to submit a bug over here :wink: 

Hmmm I'm not sure why Etcher would not be happy with the file o.O Are you sure that you took the `.iso.sig` file and not the `.sig.sig` file ? Anyway if that helps, you should be able to redownload the file from [this url](https://build.yunohost.org/yunohost-stretch-3.1.0-rpi-stable.iso) now, dunno if that helps ...

**Comment by alexAubin** [comment]
Uh nevermind ...I realized I made a huge mistake and was probably doing at least 5 others things while doing this >.> The file is indeed not a .iso but a .zip. You can rename the file to `anything.zip` and it should be fine for Etcher.

I will fix that on our side and that should do it. Sorry for the head in the cloud !
