### ISSUE TITLE
setfacl: command not found on debian from ynh-dev

### ISSUE THREAD

**Issue by guigot** [YunoHost/issues#1184]
Hello,

Last time I wanted to test an application which uses yunohost.multimedia and its directories, it didn't work. Looking at logs, the installation of yunohost.multimedia goes right to the end without indicating the fail of setfacl ("command not found").
Installating the package _acl_ solved the problem.

**Comment by alexAubin** [comment]
Hmmm so do you suggest that we should install acl as a core dependency ? The alternative is to install it in each app that needs it. I don't have a strong opinion on this topic.

**Comment by guigot** [comment]
Maybe we can add a dependency only for yunohost.multimedia and let the scripts (ynh_media_addfolder and ynh_media_build) installing this package if necessary ?

**Comment by maniackcrudelis** [comment]
Fixed by https://github.com/YunoHost-Apps/Experimental_helpers/commit/612d958bacd0d3dbb7e6ff3a317bbf41ad8ab3c1

**Comment by guigot** [comment]
Thanks ! The helpers ynh_multimedia_addfolder and ynh_multimedia_movefolder need it too, isn't it ? They use setfacl as well.

**Comment by maniackcrudelis** [comment]
ynh_multimedia_build_main_dir is used to install or update the main directory yunohost.multimedia. So this helper is used in install and upgrade scripts.
It would be enough to patch only this script since it will used to build the main directory before any other command.

**Comment by alexAubin** [comment]
Closing assuming this is fixed ..?
