### ISSUE TITLE
Remove those damn useless errno from MoulinetteErrors

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1185]
Having to put an errno in MoulinetteError is quite useless and just a waste of time. If only we could take some time to get rid of those once for all ¯\\\_(ツ)\_/¯

**Comment by Psycojoker** [comment]
Theoretically is changes the return code when YunoHost crash which can be useful when writing scripts that wraps YunoHost.

But I've never encountered someone who did that and uses them (they aren't documented after all).

**Comment by alexAubin** [comment]
Fixed via https://github.com/YunoHost/yunohost/pull/574 and https://github.com/YunoHost/moulinette/pull/180
