### ISSUE TITLE
Mise a jour vers 3.1 depuis l'interface web impossible / Update to 3.1 doesn't work in the web interface

### ISSUE THREAD

**Issue by LaBaude32** [YunoHost/issues#1187]
La mise à jour de 3.0 à 3.1 ne fonctionne pas par l'interface web. Les paquets ne veulent pas se mettre à jour. Soit ça ne fonctionne pas soit ils indiquent mise à jour différé (1h) mais 5 jours après ce n'est pas fait.
Cependant la mise à jour fonctionne en ssh.

**Comment by Psycojoker** [comment]
I hope this is fixed now :/ don't hesitate to complain if not (sorry for the lack of reaction)
