### ISSUE TITLE
Add a link to an app's repository on install page

### ISSUE THREAD

**Issue by nicofrand** [YunoHost/issues#1189]
Hi,

this would be great if in the apps list (https://domaintld/yunohost/admin/#/apps/install/) or on the app's view (https://domain.tld/yunohost/admin/#/apps/install/APP) the URL of the app's repository was added.

This would allow the user to check the source but also to see if additional steps are needed (for example the synapse app requires to modify the DNS).

**Comment by alexAubin** [comment]
I'm gonna assume that this is fixed by https://github.com/YunoHost/yunohost-admin/pull/205 which was released in 3.3 and includes a link to the app repository and readme.
