### ISSUE TITLE
Add option '--need-lock' to 'yunohost service add'

### ISSUE THREAD

**Issue by pitchum** [YunoHost/issues#1190]
yunohost CLI uses a lock mechanism to prevent two yunohost CLI from running at the same time, except when those two CLI share a common process tree.

This is safe in most cases except when a systemd service is involved because it creates a distinct process tree to execute. Such cases cause deadlocks.

A solution is already implemented in the core for the *firewall* service (cf. commit [9903c48f](https://github.com/YunoHost/yunohost/commit/9903c48f)).
That solution is currently hard-coded. We need to be able to set the *need_lock* property using `yunhohost service add xxxxxxxx --need-lock`.

**Comment by irina11y** [comment]
What help message should i write?

**Comment by pitchum** [comment]
I suggest this help message: "Use this option to prevent deadlocks if the service does invoke yunohost commands."

**Comment by alexAubin** [comment]
Closed via YunoHost/YunoHost#530
