### ISSUE TITLE
Consider restic as a backup tool

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1194]
Apparently it's like borg but better (it supports way more backend), in Go (faster?) and also in debian. Dunno if it's worth it.

https://github.com/restic/restic

**Comment by decentral1se** [comment]
I found https://stickleback.dk/borg-or-restic/ a useful read.

**Comment by Psycojoker** [comment]
> Restic’s memory requirements makes it unsuitable for backing up a small VPS with limited RAM, and the slow backup verification process makes it impractical on larger servers.

I guess this sort it out for us, we already have quite RAM problems on small boards so we can't have that in addition :/

Thx for this article!
