### ISSUE TITLE
Admin pacman hangs indefinitely

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1196]
It has been reported several times that sometimes the webadmin pacman runs forever. The root cause is still to be understood, but this is a bit of a critical UX problem right now...

**Comment by tituspijean** [comment]
I consistently have this bug when I click on a "Install with YunoHost" button. The page loads, but installation never starts.

**Comment by tulsileathers** [comment]
I'm having this issue with a postinstall failing with an infinite pacman as well

**Comment by alexAubin** [comment]
@tituspijean @tulsileathers or anyone encountering this issue : if you encounter it again, what would greatly help is to check in the Javascript Console (F12 on Firefox, then Console) if there's anything suspicious that might be related to this. Thanks for the feedback already given tho ! :heart:

**Comment by tituspijean** [comment]
Yep, there is an error associated to this issue: 
```
TypeError: p[a.params.app] is undefined
```
![image](https://user-images.githubusercontent.com/8769166/50020989-e59b1e80-ffd7-11e8-9622-6fcdf2b60f6d.png)

Edit: Chrome is a bit more verbose about it:

```
script.min.js?version=3.3.1:32 Uncaught TypeError: Cannot read property 'manifest' of undefined
    at script.min.js?version=3.3.1:32
    at Object.<anonymous> (script.min.js?version=3.3.1:29)
    at l (script.min.js?version=3.3.1:2)
    at Object.fireWith [as resolveWith] (script.min.js?version=3.3.1:2)
    at r (script.min.js?version=3.3.1:3)
    at XMLHttpRequest.<anonymous> (script.min.js?version=3.3.1:3)
```

YNH 3.3.3

**Comment by alexAubin** [comment]
```
TypeError: p[a.params.app] is undefined
```

@tituspijean : that's interesting, can you explain how you triggered this ?

**Comment by tituspijean** [comment]
I had the audacity to use the button "Install with YunoHost" the way it is advertised. :)

1. Go to Flarum's Github page
2. Click on the button / open the page https://install-app.yunohost.org/?app=flarum
3. Input my server's address
4. Click on "install Flarum (community).
5. Click on "Reach the serveur" button
6. Input my password (or not if already connected) in the webadmin
7. BAM. Bug. F12 to see the aforementioned error.

**Comment by alexAubin** [comment]
I can reproduce the issue and will work on a fix. Many thanks ! :tada: :+1:

**Comment by alexAubin** [comment]
Hmokay turns out that it was an issue in the install-app page and not in the webadmin itself. It should be fixed now, though the UX is not really cool, in the sense that it just tells you to go to the install page and copy/paste the link manually basically. 

Could be improved (i.e. behave directly as if you entered the URL) but that's beyond the scope of this issue. At least now there shouldnt be any infinite pacman for this very specific issue.

**Comment by alexAubin** [comment]
About this in chrome : 

>script.min.js?version=3.3.1:32 Uncaught TypeError: Cannot read property 'manifest' of undefined

Was it the same issue ?

**Comment by tituspijean** [comment]
To me it looked like the same issue. Actually the `manifest` part has also been mentioned on Firefox, but only once.

**Comment by alexAubin** [comment]
Ah yes nevermind, reading the code and re-reading the error carefully, it makes sense :wink: Thanks again !

**Comment by alexAubin** [comment]
Didn't re-read everything but I think we can close this issue, also some parts of the webadmin internals have been reworked (namely the custom app install)
