### ISSUE TITLE
on failed installation/(other operation) of NON official applications, we should provide specific information to the user

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1204]
The main reason people say that YunoHost doesn't work is because they try to work on non official applications and sometime things failed because they aren't good enough and people concluded that YunoHost sucks because of that (I had the case several times).

To improve this situation here is a list of ideas:

- on installation, warn way better (and also in CLI) that this is a non-official application and that this can breaks the system and that the users need to be aware of that and make the user agree with that (like a button "I understand what I'm doing" or a cli prompt)
- on installation failure, say something among the line of "this is a non official application, those aren't stable and not maintained by the YunoHost team, you need to reach the maintainers of this application that you can find here $URL, provide them with the installation log bellow [display installation log bellow]. Remember that the YunoHost team is not responsible for this application".

Do something similar for remove/upgrade failure.

**Comment by alexAubin** [comment]
Closing because I guess it was somehow improved at some point (at least for installation) and it's also reported in the diagnosis
