### ISSUE TITLE
EOFError on postinstall

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [YunoHost/issues#1206]
I have an orangepipc. I downloaded the image for orangepipcplus and flashed on the SD card. The board boots and I can SSH into the machine with default username and password.

I am getting API is not responding error when I visit the webpage, but then that is also because I haven't started the postinstall steps yet, so I invoked `yunohost tools postinstall` to only immediately receive a error from the script saying it failed to load the pickle file.

![yunohost_error](https://user-images.githubusercontent.com/788244/45861027-0ad91180-bd88-11e8-8370-c0b5b0e11244.png)

`actionsmap.py` is expecting the file to be present in `/usr/share/moulinette/actionsmap/`. There is only one YAML file in that path called `yunohost.yml`

1. What file is the script expecting to be present in that path?
2. Is it auto-generated or has to be compiled manually?

**Comment by Psycojoker** [comment]
Hello,

This `yunohost.yml` file is not autogenerated, but the cached pickle version is, which is the one that this code is trying to load.

You should be able to fix your problem by deleting the `.pkl` file in `/var/cache/moulinette/actionmaps/`, there was probably a bug during its generation. I'm going to had code to handle that.

Thanks for taking the time to do this bug report :)

**Comment by Psycojoker** [comment]
Wait, what version of YunoHost are you using? I see that this `EOFError` is supposed to be handle :o https://github.com/YunoHost/moulinette/blob/stretch-unstable/moulinette/actionsmap.py#L394

**Comment by alexAubin** [comment]
Bump for feedback :s ...

**Comment by Psycojoker** [comment]
Well, I'm going to close it for now :/ 

Don't hesitate to complain/reopen if you want :)
