### ISSUE TITLE
Add a "select/deselect all" button on webadmin backup creation page

### ISSUE THREAD

**Issue by SiM** [YunoHost/issues#1207]
Hi,

When do you want to create a new backup within the webadmin interface (/yunohost/admin/#/backup/local/create), by default everything is selected.
But if you want to create a backup for one app and if you have a lot of apps installed, it can be annoying to deselect all others items.

A small improvement with a big effect could be to have a button (or text) on the top and on the bottom of the list to select/deselect all items.

I'm not a regular user of webadmin, but maybe this could be useful on other webadmin pages

**Comment by eauchat** [comment]
I can work on this.

**Comment by eauchat** [comment]
It's done! I'll create the pull request in the coming days.

This covers select all/none buttons in the "new backup" page, and in the "restore" view as well.
If anyone think of a section of the admin panels that could benefit this functionality tell me and I'll add it in them too :)
