### ISSUE TITLE
Delayed upgrades in webadmin are a UX disaster

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1209]
Currently when upgrading yunohost packages (core, webadmin, ssowat and moulinette) from the webadmin, the upgrade is delayed / differed for various technical reason.

This is pretty much a UX disaster because : 
- the user initially expect to run the upgrade and be done with it, and have access to new features, not having to come back in 1 hour ...
- it is not clear when exactly the actual upgrade will happen
- in fact : it happens at the next 'hour', so e.g. 13:00, which might be in 1 minute or in 59 minutes... If it happens in the next minute, it might have weird consequences such as the user being disconnected because of the yunohost-api restart (which is what is supposed to be avoided)
- user can't see logs and investigate issues if the upgrade is broken for some reasons
- we end up recommending people to run `apt-get update && apt-get dist-upgrade` because at least it doesn't have all the previous inconvenience ... but that still require people to connect through SSH, whereas one of the goal of YunoHost is to be able to do 99% of common tasks through the webadmin.

During the stretch migration, another method was used which was to trigger the upgrade as a background command : https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/data_migrations/0003_migrate_to_stretch.py#L205-L236

This didn't solve the issue that "user can't see logs and investigate issues if the upgrade is broken for some reasons" but at least the upgrade happened right away ... We might be able to implement some trickery using the new `yunohost log` feature to save the corresponding log somewhere and make it accessible from the webadmin ?

**Comment by alexAubin** [comment]
Adding a rant here that we should really rework the whole update/upgrade and make this a priority because these days we regularly have people coming with the `FetchedFailedException` because of nasty stuff in sources.list ... and that's just one issue among other about the upgrade mechanism >.>

**Comment by alexAubin** [comment]
So should be okay since 3.6

**Comment by lightnin** [comment]
This is true. Having installed the recommended Raspberry pi version, I have clicked upgrade, got the waiting message, waited several hours, but some selected packages were still not upgraded. Now I selected upgrade all packages, and now I'm in eternal pacman. Looks like this might be the second failed attempt at clean install. 
Is there no way to upgrade the download image for rPI to 3.6 so this madness doesn't stop users who are interested from successfully installing? Note that most app packages seem to require 3.6, so the upgrade at this point is crucial for even trying the software out.

**Comment by alexAubin** [comment]
yes, hopefully we'll upgrade the images soon™ ... but in the meantime the most reliable way to upgrade is to run manually `sudo apt update && sudo apt dist-upgrade` (though once you upgrade the recommended way is to use the webadmin or `yunohost tools upgrade --system`)
