### ISSUE TITLE
Can't close port 22 with yunohost firewall

### ISSUE THREAD

**Issue by Najrim** [YunoHost/issues#1210]
I'm following the steps at <https://yunohost.org/#/security> to close port 22 but it's reported as open even after the command to disallow it. I also don't need to use the `-p` option to log in to the server with ssh so it seems the port actually still is open. I found someone [on the forum](https://forum.yunohost.org/t/port-closed-or-not/691/3) who was having the same problem a couple of years ago and it doesn't seem like it was resolved. Am I just doing it wrong, misunderstanding it or might there be a bug?

**Comment by Psycojoker** [comment]
Thanks for taking the time to report this bug :heart:

**Comment by zamentur** [comment]
"It's not a bug, it's a feature" ...

Historically, it's not possible to deactivate SSH port to avoid user cut off the branch on which he is sitting

**Comment by Najrim** [comment]
That makes sense. But perhaps the user should be notified of why the port won't close.

**Comment by alexAubin** [comment]
(turns out there's finally a PR for this (to allow SSH port being closed), if you have an opinion to share on the matter : https://github.com/YunoHost/yunohost/pull/556 )
