### ISSUE TITLE
decentralized backup - long terme exploration

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1212]
I'm just opening this issue to gather some related projects that we might end up using one day for that since they have been discussing this on the freedombox mailing list.

- tahoe-lafs, the old one we nearly used long time ago
- https://sia.tech/ apparently this is some kind of bakcup economy based on blockchain thingy, looks way to hypish for me (also: blockchain -_-) but that data isn't stored in the blockchain, just people have credit for storing stuff etc...
- https://maidsafe.net/ apparently this stuff too could be used for that but it look meh from here
- https://filecoin.io/ another blockchain stuff, meh
- https://storj.io/ and another one
- https://darkcrystal.pw/ this one is to split password between friends (much like pgp I guess), could be used for backup key because people sucks at keeping that

Anyway, nothing that great in scope but at least we have some place to store those links.

**Comment by alexAubin** [comment]
Closing because idk, this is not really going to transform into anything concrete i suppose
