### ISSUE TITLE
Old php5 files are not removed during the migration

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/issues#1213]
According to this issue, https://github.com/YunoHost-Apps/multi_webapp_ynh/issues/18

Apparently (didn't check it...), the old php5 configuration isn't remove during the migration.
Don't know exactly how this part of the migration works, but I expect that any direct fix we would add into the helper will match the script, or whatever it is, and turn to a remove of php7.

So, how could we manage that ?

I though about add a silent ynh_secure_remove on php5 files, but I don't think it would work after a migration.

**Comment by julienmalik** [comment]
On my side, after one day of a stretch migration, crond is spaming me with this :
```
/usr/lib/php5/sessionclean: 34: /usr/lib/php5/sessionclean: php5: not found
```

and this comes from the following file :
```
/etc/cron.d/php5
```
which I guess, should have disappeared, but somehow did not.

**Comment by Psycojoker** [comment]
PR is merged, closing then.
