### ISSUE TITLE
Encourage people to go read the Yunohost's release note during major version upgrade (e.g. x.2 -> x.3)

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1214]
That could prove itself useful for users (more advanced users), we already have them on the forum but having them in yunohost could be better, especially in case of doubt.

**Comment by zamentur** [comment]
This link could be used, and it could be good enough to put it somewhere in webadmin
https://forum.yunohost.org/tag/ynh_release

**Comment by alexAubin** [comment]
Done recently in the webadmin (minor release on 11.0)
