### ISSUE TITLE
Error: yunohost.app 'app checkurl' is deprecated !

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/issues#1217]
Anytime someone is using app_change_url, there's an error message about `app checkurl` that should be replace by `ynh_webpath_register`.
But, actually, it looks like app checkurl is in the core, not in the app packages.
https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/app.py#L471

And, if you have a look to a log during a change-url, you can see that the error is just after `INFO     moulinette.actionsmap process - processing action [6205.1]: yunohost.app.change-url with args={'path': '/', 'app': 'shaarli', 'auth': <moulinette.authenticators.ldap.Authenticator object at 0x7f2db4e35290>, 'domain': 'domain.tld'}` and before the starting of the code from the app script.

**Comment by alexAubin** [comment]
Meh, yeah that's a remaining TODO / FIXME waiting to be implemented, since at that time all we had was checkurl :/ :

https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/app.py#L468-L471

Related : https://github.com/YunoHost/yunohost/pull/376
