### ISSUE TITLE
apt autoremove breaks YunoHost

### ISSUE THREAD

**Issue by rushsteve1** [YunoHost/issues#1219]
Packages are not marked as manually installed when installing on top of a Debian base.
Because of that running `apt autoremove` removes everything necessary for YunoHost to function properly.

They either need to be marked as manually installed or marked as direct dependencies of the YunoHost package. Preferable a mixture of both for core/apps.

**Comment by alexAubin** [comment]
Uuuh, thanks for the report but could you elaborate what packages you are talking about ? Are you talking about app dependencies ? Or Yunohost dependencies ? Or apps themselves ? Or something else ?

**Comment by rushsteve1** [comment]
Sorry if I was unclear. I mean Devian package dependencies. As far as I could tell these were all things required by the YunoHost core and not apps, but there were > 100 items so I likely missed some.

This included things such as `mariadb`, `dnsmasq`, `fail2ban`, etc. which are required for YunoHost to function.

**Comment by alexAubin** [comment]
Uuuuh I don't see how those could have been removed ? `yunohost` is a debian package requiring all these ... If you demand to uninstall `dnsmasq` on any yunohost instance, it will certainly ask to remove yunohost. So are you sure that the `yunohost` package is still installed on your system ...?

**Comment by rushsteve1** [comment]
Huh... you are completely right. I must have had some configuration issue at the time because the issue is now gone.
I will close this issue, this was just user error. Thank you for your time.
