### ISSUE TITLE
Documentation about mysql

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#122]
###### Original Redmine Issue: [122](https://dev.yunohost.org/issues/122)

Author Name: **cassou**

---

I wanted to backup my cube's databases so I was looking for mysql administation information on yunohost documentation. I didn't find anything. I was at least expecting to know the user/password to use to login to mysql server.

**Comment by alexAubin** [comment]
Not sure it's really meaningful to keep this issue opened ... We have the backup mechanism now
