### ISSUE TITLE
Metronome configuration template is outdated also the package should be updated to 3.11.0.

### ISSUE THREAD

**Issue by maranda** [YunoHost/issues#1221]
https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/templates/metronome/metronome.cfg.lua is rather outdated, it has features like bidi and stream management disabled.

Please have a look for the default config file to get ahold of the default features for 3.11, https://github.com/maranda/metronome/blob/master/metronome.cfg.lua.dist

**Comment by alexAubin** [comment]
Thanks for the feedback

(Unfortunately there aren't many people with XMPP expertise in the current team so if you have time, it would help if you could propose a PR to update the default conf :s)

Also do you understand why some people reported that MAM is disabled despite our config apparently including it ?

**Comment by maranda** [comment]
@alexAubin Metronome by default doesn't enable logging despite the module being enabled clients need to explicitly configure prefs to enable logging (that also better conforms to GDPR).

**Comment by maranda** [comment]
@alexAubin done https://github.com/YunoHost/yunohost/pull/559 also the Metronome package should be update to v3.11 since it has been released

**Comment by alexAubin** [comment]
Merged, thanks !
