### ISSUE TITLE
Switch main domain should switch autosign certificate authority ?

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1224]
If we do a new installation with a domain "toto.fr" that later we add the domain "tata.fr" which is deleted "toto.fr", to make "tata.fr" the default domain and the only one, then self-signed certificates will systematically be generated with the first domain name used during the installation, namely "toto.fr", even if this domain has been deleted from the server.

**Comment by alexAubin** [comment]
Should be fixed nowadays, cf the `regen_local_ca` function in ssl's regen conf hook
