### ISSUE TITLE
Glances seems to start but not really

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1225]
It seems it appears on SSD setup only 
https://forum.yunohost.org/t/certificat-autosigne-qui-revient-avec-nom-de-domaine-supprime/5971/7?u=ljf

https://forum.yunohost.org/t/erreur-avec-le-service-glances-errno-1/5719

**Comment by alexAubin** [comment]
Burn Glances :fire: :fire: :fire:

**Comment by alexAubin** [comment]
Removed glances in https://github.com/YunoHost/yunohost/pull/821
