### ISSUE TITLE
"Last name" attribute does not accept a compounded name

### ISSUE THREAD

**Issue by Dark-Fenix** [YunoHost/issues#1226]
Hi,

I have just set up a fresh installation of Yunohost, so I'm running an up-to-date version.

I tried (through the WebGUI and the CLI) to add a new user with a compounded name (with a "-" between the two names), and it is not accepted : 
"Invalid argument 'lastname': Must be a valid last name".

I can't find any issue reporting this, so here it is, but feel free to blame me if I'm wrong :)

**Comment by Psycojoker** [comment]
It looks like something pretty easy to fix https://github.com/YunoHost/yunohost/blob/cedaaa908744c372941b9092be713bc3670e9774/data/actionsmap/yunohost.yml#L108

Thx for taking the time to report this bug :heart:

**Comment by alexAubin** [comment]
https://github.com/YunoHost/yunohost/pull/565 should fix it
