### ISSUE TITLE
Cant update fresh installation

### ISSUE THREAD

**Issue by JimFrostig** [YunoHost/issues#1227]
I make a fresh sd card from the online image of yunohost.
I made the postintall in the browser but it´s dont run throu :/

Here is the pastebin from the log.

https://paste.yunohost.org/lariciweqe

I try reinstall, check the hash of the image  etc. but everything is ok.

**Comment by alexAubin** [comment]
Looks related to https://github.com/YunoHost/issues/issues/1209 :/

**Comment by JimFrostig** [comment]
@alexAubin  Oh i fixed it know it runs perfectly! 

i fixed it like that ->

1. fresh flash on a micro sd with [Etcher](https://etcher.io/) 
2. then i made the postinall in my browser ( for me firefox) > i get the same error
3. i logged me in the terminal on the root and run "yunohost tools update" and  "yunohost tools upgrade" -> this runs perfectly

after that i logged in on my yunohost raspberry with the browser and tadaaa... it runs ! 
maybe that helps u too!

**Comment by Psycojoker** [comment]
The PR has been merged, I think this is good now :)

Don't hesitate to complain if it's not the case.
