### ISSUE TITLE
Nextcloud deleted after failed upgrade

### ISSUE THREAD

**Issue by xaloc33** [YunoHost/issues#1230]
I tried to upgrade nextcloud with yunohost app upgrade, but after the upgrade failed yunohost removed nextcloud. No files where deleted just the app.
Here are the logs of the failed upgrade, the remove of nextcloud and the failed restore of nextcloud.

logs failed upgrade:
https://paste.yunohost.org/raw/ugisewucov

logs remove nextcloud:
https://paste.yunohost.org/raw/debaxanika

logs restore nextcloud:
https://paste.yunohost.org/raw/izotewuwir

After manually removing the nextcloud group I was able to reinstall nextcloud

**Comment by Psycojoker** [comment]
> 2018-10-16 09:41:21,264: DEBUG - + sudo yunohost app remove nextcloud
> ...
> 2018-10-16 09:41:41,946: DEBUG - + sudo yunohost backup restore nextcloud-pre-upgrade1 --apps nextcloud --force
> 2018-10-16 09:43:20,270: WARNING - useradd: group nextcloud exists - if you want to add this user to that group, use -g.
> 2018-10-16 09:43:20,273: WARNING - Unable to create nextcloud system account
> ...
> 2018-10-16 09:43:20,477: DEBUG - The operation 'Restore 'nextcloud' from a backup archive' has failed ! To get help, please share the full log of this operation using the command 'yunohost log display 20181016-094244-backup_restore_app-nextcloud --share'

That's linked to a failed backup/restore strategy from the upgrade script :/ (and not directly linked to the core but for the apps upgrade strategies) cc @maniackcrudelis

**Comment by maniackcrudelis** [comment]
Actually it looks like it's more about an error with the remove script
```
userdel: group nextcloud not removed because it has other members.
```

Also, the main error was with dpkg, because another process was using the database. We hadn't encountered that error before a recent update.
Anyway, I was thinking about adding a check on the lock file before trying to use apt or dpkg. Probably with a small helper.

**Comment by maniackcrudelis** [comment]
Here a helper to fix that issue about apt.
https://github.com/YunoHost/yunohost/pull/571

**Comment by alexAubin** [comment]
Related fix : https://github.com/YunoHost/yunohost/pull/680

**Comment by alexAubin** [comment]
Fix got merged
