### ISSUE TITLE
Three differents names for each app ...

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1233]
Currently the community.json is a mess because there are three way to name apps, and sometimes those names are different : 
- the name of the key in the community.json
- the name of the repo, without the `_ynh`, so for instance `wordpress` in `https://github.com/yunohost-apps/wordpress_ynh`
- the "id" in the manifest of the apps.

For instance, 
- `apticron` has in fact `ynapticron` in the manifest (c.f. https://github.com/ldidry/apticron_ynh/blob/master/manifest.json#L3 ) 
- `dockerregistry`'s repo is `https://github.com/plopoyop/docker-registry_ynh`
- `dockerrstudio`'s repo is `https://github.com/scith/docker_rstudio_ynh`
- people regularly put/remove caps in keys of community.json whereas the name of the repo don't have one..

It is a silly issue but it creates bugs / confusion in many places which assume all three names are supposed to be the same. This is for instance the case of the list builder ... It would be nice to have a long-term fix for this though I don't know what's the right thing to do ...

**Comment by alexAubin** [comment]
This week I got mad about this again and added a warning in our list builder to help investigate this : https://github.com/YunoHost/apps/commit/2e4eaacf3acc7e338302520426572fc73ea89d55

**Comment by Psycojoker** [comment]
Maybe we can had a script in our travis-yaml to block bad PR for that? That's not very hard to write, I can do it if you want.

**Comment by alexAubin** [comment]
Hm yes if you want :wink: Though I'm not 100% sure it's trivial to fetch the info about the app id in the manifest given that's in the git repo itself. But anything that could help limit those inconsistencies is welcome !

**Comment by Psycojoker** [comment]
We do it like that right now so it's basically "remove 80% of list_build.py, add a bit of logic" and that ~should~ be fine https://github.com/YunoHost/apps/blob/master/list_builder.py#L224

**Comment by alexAubin** [comment]
:+1: 

![serveimage](https://user-images.githubusercontent.com/4533074/50257059-d3671900-03f9-11e9-959d-5ca1389efee3.gif)

**Comment by Psycojoker** [comment]
I've made a script for that https://github.com/YunoHost/apps/blob/master/check_id_unicity.py

Here is the result of its first run:


> [scm] github repo name is not coherent with app id: 'scm' vs 'scm-manager_ynh' (https://github.com/drfred1981/scm-manager_ynh)
> [scm] manifest id is different from github repo name : 'scm' vs 'scm-manager_ynh' (https://github.com/drfred1981/scm-manager_ynh)
> [bicbucstriim] github repo name is not coherent with app id: 'bicbucstriim' vs 'BicBucStriim_ynh' (https://github.com/YunoHost-Apps/BicBucStriim_ynh)
> [bicbucstriim] manifest id is different from github repo name : 'bicbucstriim' vs 'BicBucStriim_ynh' (https://github.com/YunoHost-Apps/BicBucStriim_ynh)
> -> Error: unable to request https://raw.githubusercontent.com/ljf/wifiwithme_ynh/14e01a3981bde7192e100b1f9cfa50e95d6cb89b/manifest.json, 404 Client Error: Not Found
> [ftp_webapp] github repo name is not coherent with app id: 'ftp_webapp' vs 'ftp_support_webapp_ynh' (https://github.com/YunoHost-Apps/ftp_support_webapp_ynh)
> [ftp_webapp] manifest id is different from github repo name : 'ftp_webapp' vs 'ftp_support_webapp_ynh' (https://github.com/YunoHost-Apps/ftp_support_webapp_ynh)
> [emby] manifest id is different from app id: 'emby' vs 'embyserver' (manifest_id
> [emby] manifest id is different from github repo name : 'embyserver' vs 'emby_ynh' (https://github.com/YunoHost-Apps/emby_ynh)
> [telegram_chatbot_ynh] github repo name is not coherent with app id: 'telegram_chatbot_ynh' vs 'telegram_chatbot_ynh' (https://github.com/YunoHost-Apps/telegram_chatbot_ynh)
> [telegram_chatbot_ynh] manifest id is different from app id: 'telegram_chatbot_ynh' vs 'telegram_chatbot' (manifest_id
> [firefly-iii] github repo name is not coherent with app id: 'firefly-iii' vs 'Firefly-III_ynh' (https://github.com/YunoHost-Apps/Firefly-III_ynh)
> [firefly-iii] manifest id is different from github repo name : 'firefly-iii' vs 'Firefly-III_ynh' (https://github.com/YunoHost-Apps/Firefly-III_ynh)
> [zabbix] manifest id is different from app id: 'zabbix' vs 'ynhzabbix' (manifest_id
> [zabbix] manifest id is different from github repo name : 'ynhzabbix' vs 'zabbix_ynh' (https://framagit.org/Mickael-Martin/zabbix_ynh)
> [dockerrstudio] github repo name is not coherent with app id: 'dockerrstudio' vs 'docker_rstudio_ynh' (https://github.com/scith/docker_rstudio_ynh)
> [dockerrstudio] manifest id is different from github repo name : 'dockerrstudio' vs 'docker_rstudio_ynh' (https://github.com/scith/docker_rstudio_ynh)
> [webtrees] github repo name is not coherent with app id: 'webtrees' vs 'Webtrees_ynh' (https://github.com/YunoHost-Apps/Webtrees_ynh)
> [webtrees] manifest id is different from github repo name : 'webtrees' vs 'Webtrees_ynh' (https://github.com/YunoHost-Apps/Webtrees_ynh)
> [opennote] github repo name is not coherent with app id: 'opennote' vs 'OpenNote_ynh' (https://github.com/YunoHost-Apps/OpenNote_ynh)
> [opennote] manifest id is different from github repo name : 'opennote' vs 'OpenNote_ynh' (https://github.com/YunoHost-Apps/OpenNote_ynh)
> [gitrepositories] manifest id is different from app id: 'gitrepositories' vs 'git-repositories' (manifest_id
> [gitrepositories] manifest id is different from github repo name : 'git-repositories' vs 'gitrepositories_ynh' (https://github.com/YunoHost-Apps/gitrepositories_ynh)
> -> Error: unable to request https://raw.githubusercontent.com/ljf/covoiturage_ynh/613412a74efebca52a8c4e213abf56443056f610/manifest.json, 404 Client Error: Not Found
> [cubiks-2048] github repo name is not coherent with app id: 'cubiks-2048' vs 'Cubiks-2048_ynh' (https://github.com/YunoHost-Apps/Cubiks-2048_ynh)
> [cubiks-2048] manifest id is different from app id: 'cubiks-2048' vs 'cubiks2048' (manifest_id
> [cubiks-2048] manifest id is different from github repo name : 'cubiks2048' vs 'Cubiks-2048_ynh' (https://github.com/YunoHost-Apps/Cubiks-2048_ynh)
> [calibreweb] github repo name is not coherent with app id: 'calibreweb' vs 'calibre_ynh' (https://github.com/YunoHost-Apps/calibre_ynh)
> [calibreweb] manifest id is different from github repo name : 'calibreweb' vs 'calibre_ynh' (https://github.com/YunoHost-Apps/calibre_ynh)
> [turtl] github repo name is not coherent with app id: 'turtl' vs 'Turtl_ynh' (https://github.com/YunoHost-Apps/Turtl_ynh)
> [turtl] manifest id is different from github repo name : 'turtl' vs 'Turtl_ynh' (https://github.com/YunoHost-Apps/Turtl_ynh)
> [remotestorage] github repo name is not coherent with app id: 'remotestorage' vs 'RemoteStorage_ynh' (https://github.com/YunoHost-Apps/RemoteStorage_ynh)
> [remotestorage] manifest id is different from app id: 'remotestorage' vs 'Remotestorage' (manifest_id
> [remotestorage] manifest id is different from github repo name : 'Remotestorage' vs 'RemoteStorage_ynh' (https://github.com/YunoHost-Apps/RemoteStorage_ynh)
> [joomla] github repo name is not coherent with app id: 'joomla' vs 'Joomla_ynh' (https://github.com/YunoHost-Apps/Joomla_ynh)
> [joomla] manifest id is different from github repo name : 'joomla' vs 'Joomla_ynh' (https://github.com/YunoHost-Apps/Joomla_ynh)
> [collabora online with docker] github repo name is not coherent with app id: 'collabora online with docker' vs 'collaboradocker_ynh' (https://github.com/aymhce/collaboradocker_ynh)
> [collabora online with docker] manifest id is different from app id: 'collabora online with docker' vs 'collaboradocker' (manifest_id
> [emailpoubelle] github repo name is not coherent with app id: 'emailpoubelle' vs 'poubelle_ynh' (https://github.com/YunoHost-Apps/poubelle_ynh)
> [emailpoubelle] manifest id is different from github repo name : 'emailpoubelle' vs 'poubelle_ynh' (https://github.com/YunoHost-Apps/poubelle_ynh)
> [collabora_online] github repo name is not coherent with app id: 'collabora_online' vs 'collaboraonline_ynh' (https://github.com/YunoHost-Apps/collaboraonline_ynh)
> [collabora_online] manifest id is different from app id: 'collabora_online' vs 'collabora' (manifest_id
> [collabora_online] manifest id is different from github repo name : 'collabora' vs 'collaboraonline_ynh' (https://github.com/YunoHost-Apps/collaboraonline_ynh)
> [webapp_multi_inst] github repo name is not coherent with app id: 'webapp_multi_inst' vs 'webapp_multi_ynh' (https://github.com/polytan02/webapp_multi_ynh)
> [webapp_multi_inst] manifest id is different from github repo name : 'webapp_multi_inst' vs 'webapp_multi_ynh' (https://github.com/polytan02/webapp_multi_ynh)
> [dockerregistry] github repo name is not coherent with app id: 'dockerregistry' vs 'docker-registry_ynh' (https://github.com/plopoyop/docker-registry_ynh)
> [dockerregistry] manifest id is different from app id: 'dockerregistry' vs 'docker-registry' (manifest_id
> [youtube-dl-webui] github repo name is not coherent with app id: 'youtube-dl-webui' vs 'Youtube-dl-WebUI_ynh' (https://github.com/YunoHost-Apps/Youtube-dl-WebUI_ynh)
> [youtube-dl-webui] manifest id is different from github repo name : 'youtube-dl-webui' vs 'Youtube-dl-WebUI_ynh' (https://github.com/YunoHost-Apps/Youtube-dl-WebUI_ynh)
> [framaforms] github repo name is not coherent with app id: 'framaforms' vs 'Framaforms_ynh' (https://github.com/YunoHost-Apps/Framaforms_ynh)
> [framaforms] manifest id is different from github repo name : 'framaforms' vs 'Framaforms_ynh' (https://github.com/YunoHost-Apps/Framaforms_ynh)
> [lbcalerte] github repo name is not coherent with app id: 'lbcalerte' vs 'LBCAlerte_ynh' (https://github.com/YunoHost-Apps/LBCAlerte_ynh)
> [lbcalerte] manifest id is different from app id: 'lbcalerte' vs 'LBCAlerte' (manifest_id
> [htmltool] github repo name is not coherent with app id: 'htmltool' vs 'htmltools_ynh' (https://github.com/isserterrus/htmltools_ynh)
> [htmltool] manifest id is different from github repo name : 'htmltool' vs 'htmltools_ynh' (https://github.com/isserterrus/htmltools_ynh)
> [dockercontainer] github repo name is not coherent with app id: 'dockercontainer' vs 'docker_container_ynh' (https://github.com/scith/docker_container_ynh)
> [dockercontainer] manifest id is different from github repo name : 'dockercontainer' vs 'docker_container_ynh' (https://github.com/scith/docker_container_ynh)
> [glowingbear] github repo name is not coherent with app id: 'glowingbear' vs 'glowing_bear_ynh' (https://github.com/YunoHost-Apps/glowing_bear_ynh)
> [glowingbear] manifest id is different from github repo name : 'glowingbear' vs 'glowing_bear_ynh' (https://github.com/YunoHost-Apps/glowing_bear_ynh)
> [ghostblog] github repo name is not coherent with app id: 'ghostblog' vs 'ghost_ynh' (https://github.com/YunoHost-Apps/ghost_ynh)
> [ghostblog] manifest id is different from app id: 'ghostblog' vs 'ghost' (manifest_id
> [freeboard.io] github repo name is not coherent with app id: 'freeboard.io' vs 'freeboard_ynh' (https://github.com/YunoHost-Apps/freeboard_ynh)
> [freeboard.io] manifest id is different from app id: 'freeboard.io' vs 'freeboard' (manifest_id
> [apticron] manifest id is different from app id: 'apticron' vs 'ynapticron' (manifest_id
> [apticron] manifest id is different from github repo name : 'ynapticron' vs 'apticron_ynh' (https://github.com/ldidry/apticron_ynh)
> [openidsimplesamlphp] github repo name is not coherent with app id: 'openidsimplesamlphp' vs 'openid-simplesamlphp_ynh' (https://github.com/julienmalik/openid-simplesamlphp_ynh)
> [openidsimplesamlphp] manifest id is different from github repo name : 'openidsimplesamlphp' vs 'openid-simplesamlphp_ynh' (https://github.com/julienmalik/openid-simplesamlphp_ynh)
>

**Comment by alexAubin** [comment]
Closing because it's mostly fixed nowadays
