### ISSUE TITLE
ISO install fails to properly partition disk (?)

### ISSUE THREAD

**Issue by galuel** [YunoHost/issues#1234]
I want to make a return of installation on a Lenovo G50 + SSD.
I stayed blocked at the step "partionnement", he failed to create file system and partitions...
Long time to find why and a solution was from the menu : 

From shell command I succeeded wth fdisk to delete all partitions on the PC disk and created only one sda1...

When launching again :

- Shell command
- umount /dev/sda1
- exit
- Start again from menu "partitionner les disques"

So for an unknown reason PC disk was mounted... Perhaps it should be automocatically unmounted first ?

**Comment by alexAubin** [comment]
Uh thanks for the report (and sorry for the lack of feedback) Though I'm not sure to understand exactly what happens :/ Sounds to me like it's related to the way debian-installer works and we don't really have control over this ...
