### ISSUE TITLE
No SMTPUTF8 support

### ISSUE THREAD

**Issue by buzuck** [YunoHost/issues#1236]
Hi,

Yunohost doesn't seem to allow [SMTPUTF8](https://en.wikipedia.org/wiki/Extended_SMTP#SMTPUTF8)[1] addresses, with unusual characters, such as `{` or `"`. [Postfix](http://www.postfix.org/SMTPUTF8_README.html)[2] supports it, it should be feasible :)

[1] : https://en.wikipedia.org/wiki/Extended_SMTP#SMTPUTF8
[2] : http://www.postfix.org/SMTPUTF8_README.html

**Comment by alexAubin** [comment]
That just sounds like a super-nerdy request that is likely to create bugs all over the place (mail adresses are not just handled by postfix, sometimes you gotta write them in CLI etc.) ... I'd like to know real-life example of why you would really need this ...

**Comment by alexAubin** [comment]
That just sounds like a super-nerdy request that is likely to create bugs all over the place (mail adresses are not just handled by postfix, sometimes you gotta write them in CLI etc.) ... I'd like to know real-life example of why you would really need this ...
