### ISSUE TITLE
Fail2ban for Metronome

### ISSUE THREAD

**Issue by anmol26s** [YunoHost/issues#1237]
Hi
Metronome is not using Fail2ban because of this its open for attacks which is dangerous.
Implementing mod_gate_guard for metronome and SCRAM with channel binding should be done. If someone have experience with metronome please help Yunohost implement it.

Otherwise at least c2s fail2ban should be implemented for now.

**Comment by alexAubin** [comment]
Closing because it's 5 years old and the orientation is more about making Metronome optional / turning it into an app
