### ISSUE TITLE
doc - use a single location for helpers information

### ISSUE THREAD

**Issue by Gofannon** [YunoHost/issues#1239]
# Issue

Packagers can find information on helpers on multiple locations. Proposal is to keep only one location

# Proposal

The location to use is https://yunohost.org/#/packaging_apps_helpers_en so I propose to forward the old page http://helpers.yunohost.org/ to new one or to remove it silently if no other option can be found.

I don't know where this web page is hosted and cannot find it in the "doc" repository https://github.com/YunoHost/doc

See discussion here if needed : https://forum.yunohost.org/t/difference-between-skipped-urls-and-unprotected-urls/6308/7

**Comment by alexAubin** [comment]
I implemented the forward / redirection from helpers.yunohost.org to the page in the "true" doc. That should solve the issue, thanks for reporting it ! :+1:
