### ISSUE TITLE
Properly remove a user and it's data

### ISSUE THREAD

**Issue by eauchat** [YunoHost/issues#1245]
I can't believe this issue hasn't been posted yet, but I searched and didn't find anything about this problem. If it's a duplicate, please excuse me.

When you remove a user, from the admin panel, it's home directory isn't removed.
Is that normal? I would expect the users data to also be removed (or maybe to be asked if I want to remove the users data as well on removal)?  
This is true for other directories like the spool/mail user directory, and is probably true about other settings for this user that I don't know.  

To me, if a user is removed, everything stored about it should as well be.

**Comment by alexAubin** [comment]
>To me, if a user is removed, everything stored about it should as well be.

Well it's not that obvious ... if a user is removed by mistake, you don't want to loose its data ... But agreed that there should be an option to tell that user's data should also be removed. But that requires more UI/UX work and that's probably the reason it hasnt been done yet :/

**Comment by eauchat** [comment]
Yep it's not obvious, that's why I was wondering if it's a bug or a design choice. But I still think it's super important that it's both possible and easy to remove a user, and everything that belongs to them.
So what is exactly all the user's data that should be removed manually?  

```bash
rm -R /home/username
rm -R /var/spool/username
# are there any other things created for a user that also should be removed?
```

I imagine that `userdel -r username` deletes those directories, and maybe also more things.  
But it's not possible to run this command since the user is already removed.  
Is it possible to simply use `userdel -r username` to remove user instead of using the admin ui. Or is it not a good practice?

**Comment by eauchat** [comment]
I will look if I can setup a developing environment to edit the UI and propose a fix, because I think it would be cool that what's happening is transparent for the administrator that uses it.  
But I've never done it, so I hope I can figure it out.

**Comment by alexAubin** [comment]
I don't think userdel can be used as Yunohost users are actually LDAP users, so that's not as simple as that.

Anyway, I just think it has been historically implemented like this because quite a lot of things were just bootstraped in a few days, and it just has never been discussed in particular (and there's so many things to do). Most of the work related to this issue relates to designing and implementing the UI/UX process behind this. It's not huge but it just takes time.

**Comment by eauchat** [comment]
Yep, I understand.  
I'll look a bit into it and try to see if I can do something about it, or if I don't have the competences.  
Still if anyone has an idea of all the things that should be removed that's good to know.

**Comment by alexAubin** [comment]
I guess the home directory and mail would be a good start ;) If you want to dig deeper then it quickly gets complicated. E.g. if a user has article on a wordpress blog, should they also be removed or not, and how to properly handle the removal of these ? Or what about nextcloud files ? 

So let's ignore that first and just consider mail and home directory ;P

If you want to have a look at the implementation, don't hesitate to contact us on #yunohost-dev on freenode (or equivalent through XMPP or Matrix) to ask questions :stuck_out_tongue_winking_eye:

**Comment by eauchat** [comment]
So after further investigation, I discovered that the function is already implemented with the command line, simply specifying `--purge` option. But it only removes the home directory. But that's a good start, and it's quite easy to add the rest I think.   
I understood how it connects to yunohost-admin so I can implement it in it. I just need to take a bit of time to think of the best way to present it to the user and then I can make a proposal on how I think it would be best, and code the implementation.  

To my view, the existing code is quite cool, easy to understand, to work, use and add improvements. That's super cool :)  

One thing I didn't really understand is what are the files in `yunohost/data/helpers.d/` meant for.  
In `yunohost/data/helpers.d/user` there is a function `ynh_system_user_delete` that implements `userdel`, but I don't know if that's in any way related to the rest.

**Comment by alexAubin** [comment]
Cool ! :+1: 

>One thing I didn't really understand is what are the files in `yunohost/data/helpers.d/` meant for.
In `yunohost/data/helpers.d/user` there is a function `ynh_system_user_delete` that implements userdel, but I don't know if that's in any way related to the rest.

I think that's in fact unrelated to the current issue discussed here. Those are helpers meant for apps script which requires to create a system/unix user (e.g. a `wordpress` user) for some reason, and that has nothing to do with YunoHost users (e.g. `johndoe`, in the LDAP and everything).

**Comment by eauchat** [comment]
Here are the pull requests corresponding to the proposed patch for this issue:  
  * yunohost/yunohost#602,
  * yunohost/yunohost-admin#221.
