### ISSUE TITLE
Successfull login loops over login page

### ISSUE THREAD

**Issue by eauchat** [YunoHost/issues#1246]
In this [forum thread](https://forum.yunohost.org/t/cant-login-as-yunohost-user/3257) an issue is mentioned about looping over login page.  
I encountered this issue quite a few times a bit randomly without really understanding why it occurs, but I think I got an idea why it's happening.  

So here is how I can reproduce the issue:
  - I registered two domain names in yunohost: `mydomain.tld` and `yunohost.mydomain.tld`
  - Yunohost's sso is available at `yunohost.mydomain.tld/yunohost/sso/`
  - I have some apps set on each domain, and the problem will occur if I use an app setup to use `mydomain.tld`.

To solve it, I need to clear browser's data for `mydomain.tld` (restarting the browser doesn't solve the issue).

It's not hard to solve, but it's annoying, and also there's no way for a random user to know about that.

**Comment by eauchat** [comment]
For the reference, I think the same problem and ideas for solutions, are discussed [here](https://forum.yunohost.org/t/conflicting-ssowat-with-two-instances-on-same-domain/4608/4).

**Comment by alexAubin** [comment]
Closing because old issue and not clear when / how to reproduce it, and the SSO/portal got rewritten for Bookworm so maybe that solves it idk
