### ISSUE TITLE
Removal of default app on a domain does not remove domain redirection

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#125]
###### Original Redmine Issue: [125](https://dev.yunohost.org/issues/125)

Author Name: **Anonymous**

---

Removing an app marked as a default app on a domain does not remove the redirection placed on the domain at /etc/ssowat/conf.json.persistent. This can have unintended side effects when later installing an app as root under that domain. This happens in both the web and command line interfaces.

To reproduce:
1. Add a new domain to the Yunohost instance using the web or command line interface.
2. Add a new app under this domain, using the default directory.
3. After installation, go to the app page in the web interface and click "Make Default" to redirect the domain root to the application directory.
4. Uninstall the app.
5. Install an app -- it can be the same app -- in the same domain, using the root directory as the app directory.
6. After installation, navigate to the domain the app is in.

Expected behavior: The root app is displayed in the browser.
Current behavior: The browser is redirected to the old app directory, producing an error.

This can probably be mitigated by doing one of the following:
* On the removal of an app, checking to see if that app is default on the domain and deleting the corresponding redirection line in /etc/ssowat/conf.json.persistent.
* Moving the redirections to the non-persistent ssowat configuration file, and regenerating the default redirections with app changes.

**Comment by Ibrahim-AbouElseoud** [comment]
I still have this issue, it was not fixed, what's the way to fix it manually? Because I tried deleting the domain but face the same problem when creating the domain again.

**Comment by Ibrahim-AbouElseoud** [comment]
This is causing me great issue because I am installing an app on the root of the domain but when you open the domain it redirects to the old app /_matrix which was default, which is trash for the new app. How can I reset it ? Deleting the domain didn't work.

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost/pull/1406 <3
