### ISSUE TITLE
Backup size shown in admin panel is very different than in file system

### ISSUE THREAD

**Issue by eauchat** [YunoHost/issues#1250]
I noticed that in the backup panel of yunohost-admin, the size given for the backups is extremely different than if I run `du -sh` on the file itself, or if I `rsync` them to my laptop and ask the properties of the file.  
I can imagine that different ways of calculation are invoked in each three options, but the size is said to be around 500MB in the admin panel, while with `du` and the utility that uses nautilus to calculate, it's around 80MB.  
Is this a calculation problem? Or  is there something I don't understand?

**Comment by nqb** [comment]
On YunoHost 3.3.3, I got same behavior.

* Size in Web Admin: 137 MB
* Size in CLI (`ls -l --si`): 32 M

**Comment by nqb** [comment]
If I extract my backup, I got size of 211M (powers of 1000)

**Comment by Psycojoker** [comment]
@zamentur have you seen that?

**Comment by zamentur** [comment]
I think somethings has been fixed this year about that cc @Aleks

Anyway, there are several sizes: the size when you restore, the size of the backuped files, the size on the repo (could be different due to deduplication/compression).

**Comment by alexAubin** [comment]
Hmpf yeah it's a mess and never clear if we're talking about the size displayed by Yunohost, the .tar.gz, or the .tar, or the untar archived, or something else ... or something else ... not to mention MB versus MiB ... 

Anyway this is 2~3 years old, not a huge deal, let's close this ...
