### ISSUE TITLE
Disabling API prevent using admin interface

### ISSUE THREAD

**Issue by nqb** [YunoHost/issues#1252]
YunoHost 3.3.2

Steps to reproduce:
- `systemctl disable yunohost-api; systemctl stop yunohost-api`
- Try to go on https://mydomain.lan/yunohost/admin/

Actual results: API not responding message

Expected results: Admin password field

**Comment by alexAubin** [comment]
Uh well, yes, the yunohost-api is required for the yunohost webadmin to works, that is by construction : the API is precisely the way the javascript of the webadmin interacts with the server...
