### ISSUE TITLE
Helper `ynh_system_user_create` should check that no corresponding yunohost user exists

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1253]
There's a small edge case in `ynh_system_user_create` which happens if the user exists as yunohost user (and not as a system user)

As discussed in https://github.com/YunoHost/issues/issues/1249, someone was trying to install nextcloud with a yunohost user called nextcloud.

Hence `ynh_system_user_create` did not create any new `nextcloud` user ... which would have been fine if the group `nextcloud` wasn't also needed for the php-fpm pool to work properly.

Dunno what's the right fix for this (ideally I'd avoid doing a `yunohost user list` just to check this because meh)

**Comment by alexAubin** [comment]
Today there was a similar / related issue where a nextcloud upgrade failed and the backup couldn't be restored. Traced back the reason to : 
- upgrade failed (that can happen, okay)
- deleted the app before restore, which include deleting the user - *BUT* turns out that the nextcloud *group* had several user in it (nextcloud + admin ... dunno why). So the user was deleted, but *not the group* ...
- attempted to restore
- during the restore, the scripts wants to create the nextcloud user and it complains that the nextcloud group already exists, and fails somehow ...

Corresponding check with `getent group` : 
```bash
$ getent group nextcloud
nextcloud:x:991:admin
```

Sooo, dunno what to do exactly to cover the original case + this one but I would say : 
- check if the user already exists. If it does, throw an error about it. If we can identify that this is a ldap user, complain about it specifically ?
- if only the group already exists, maybe we can delete it ... idunno :| 
- oooor when the user gets deleted, force the deletion of the group ?

I know that both of these are touchy though é_è

**Comment by maniackcrudelis** [comment]
https://github.com/YunoHost/yunohost/pull/680 should have fixed that issue
