### ISSUE TITLE
Still vulnerable to meltown  after updates and reboot  on domain.nohost.me ? 

### ISSUE THREAD

**Issue by masurak** [YunoHost/issues#1254]
Hi , 

I'm totally new to the yunohost thing and the server i just configured with a nohost.me domain name is saying being still vulnerable to meltdown attack after updates and reboot ... what can I do to fix and diagnose this ? is it a big deal to be vulnerable ?

**Comment by alexAubin** [comment]
What kind of hardware are you using (RPi, VPS, old laptop, ...) ?

**Comment by masurak** [comment]
its and old toshiba laptop with 32bits kernel ... :(

**Comment by alexAubin** [comment]
Sooo just to confirm, you are running stretch and did a full dist-upgrade and rebooted ?

Maybe looking at `uname -a` (to get the kernel version) would give a clearer idea of the context, but yea, that's a bit troublesome (though not a *huge* deal i guess, but would be nice to understand better..)

**Comment by masurak** [comment]
ok, 
yes, i did full dist-upgrade and reboot but on the admin interface its keep sayin im vulnerable, although trough the admin graphic interface there is no more upgrades to run. 

the uname -a : Linux Mydomain.nohost.me 4.9.0-8-686 #1 SMP Debian 4.9.130-2 201801027 i686 GNU/linux

**Comment by masurak** [comment]
please ask if you need more info from command line i will be happy to understand and fix this but don't know where to start after those first steps..

**Comment by alexAubin** [comment]
Hmyea I don't know much either about reliable ways to fix that :/ I've seen several mystic cases like this where it's not clear at all what would be required to fix it ... Naively i'd say this is related to the fact that you're running 32 bit but that's really like a random guess. I'm just quite surprised that a dist-upgrade + reboot isn't a straightforward fix 1 year after the meltdown thing was discoreved...

Or maybe the dist-upgrade thing does not switch to the newest kernel or something like that ... The bottom-line is, it's not really a yunohost-specific issue so I'm no expert about that :/ ...

**Comment by masurak** [comment]
ok , thank you so much for your time and guesses, i will continue to make upgrades regularly and to search around more info about the meltdown  attack and 32bit etc... and maybe also wait for someone who knows more to answer this thread :) 
And also i'm wondering if reinstall the whole server would be an idea ... are maybe try with some 64bit architecture.. 
what i don't know its how risky is it to use the server with this issue not fix ...

**Comment by alexAubin** [comment]
Any update on this ? :S

**Comment by alexAubin** [comment]
Closing due to lack of feedback and we can't do much on Yunohost's side ...
