### ISSUE TITLE
Feature : check if IP is blacklisted

### ISSUE THREAD

**Issue by frju365** [YunoHost/issues#1256]
Everything is in the title : In "Monitoring" menu for example : one option to check if ip is blacklisted in a list of RBL and another to have a precise list/logs where the IP is blacklisted.

@alexAubin : Could you assign me this issue. I'm working on it (it's just I hadn't time to totally finish it and I 'm afraid I will forget it :-) )

**Comment by alexAubin** [comment]
Related to https://github.com/YunoHost/yunohost/pull/534/commits/2df6e97e003fa770a0cf40914ddffd77ee2ce53c#diff-a7790a192e1f356589c17659a4bbb74aR18

**Comment by alexAubin** [comment]
Fixed by the diagnosis
