### ISSUE TITLE
Feature : Check Port is opened ot not directly in Admin interface

### ISSUE THREAD

**Issue by frju365** [YunoHost/issues#1257]
Everything is in the title. 
@alexAubin : Assign me this issue if you can. I'm working on it (with the blacklist feature issue)

**Comment by alexAubin** [comment]
Not sure to understand what's the purpose / use case behind this ...

**Comment by alexAubin** [comment]
Implemented in https://github.com/YunoHost/yunohost/pull/534

**Comment by alexAubin** [comment]
Done in the diagnosis
