### ISSUE TITLE
[enh] doc: how to upgrade from command line ?

### ISSUE THREAD

**Issue by nqb** [YunoHost/issues#1258]
Missing section in https://yunohost.org/#/update.

I saw two ways to do that:
```
$ apt-get update
$ apt-get dist-upgrade

```
or
```
$ yunohost tools update 
$ yunohost tools upgrade --ignore-apps

```
Is there is a recommend way ?

**Comment by Psycojoker** [comment]
Both will do nearly the same thing. We generally recommend the second way but there is nearly no differences.

**Comment by nqb** [comment]
Hello @Psycojoker,

The second way will upgrade the OS too ?

**Comment by nqb** [comment]
See https://github.com/YunoHost/doc/pull/881

**Comment by Psycojoker** [comment]
> The second way will upgrade the OS too ?

None of those command upgrade the OS contrary to what "dist-upgrade" sound like, it just ALSO install packages that have new dependencies which "upgrade" won't do (thanks debian for this confusion).

Like if we have "openvpn" as a new dependency for YunoHost, "apt-get upgrade" won't install the new YunoHost package, but "dist-upgrade" will.

**Comment by nqb** [comment]
I agree but what I would like to point out is that with first way you will not update **only** YunoHost packages.

What `yunohost tools upgrade --ignore-apps` command will exactly run ?

**Comment by Psycojoker** [comment]
As I've told you, the equivalent of `dist-upgrade` using the apt python API https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/tools.py#L518
