### ISSUE TITLE
"use --shallow-submodules option" in app.py with git?

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1260]
Just stumbled upon this comment: https://github.com/YunoHost/yunohost/blob/1c80e7242b2be0df8d7d5660990ff3397e929fe1/src/yunohost/app.py#L1899-R1902

```python
# We use currently git 2.1 so we can't use --shallow-submodules
# option. When git will be in 2.9 (with the new debian version)
# we will be able to use it. Without this option all the history
# of the submodules repo is downloaded.
```

According to git documentation:
```
--[no-]shallow-submodules

    All submodules which are cloned will be shallow with a depth of 1.
```

I have not idea if we should do that, I don't think we use submodules at all.

**Comment by alexAubin** [comment]
I don't think we do ... we have no apps using submodules
