### ISSUE TITLE
Impossible to leave empty password

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/issues#1261]
https://github.com/YunoHost-Apps/jirafeau_ynh/issues/52

Since you CAN'T use a weak password... Apps with optional password don't work anymore.
The password is here optional, https://github.com/YunoHost-Apps/jirafeau_ynh/blob/master/manifest.json#L57, this value should be considered during app installation.

**Comment by maniackcrudelis** [comment]
Do we have anything new about that issue ?

**Comment by alexAubin** [comment]
Soooo I was about to make a yolofix for this and realize that it should already be handled correctly ...

Running in the debugger I finally found the issue which is : 

```json
optional: "true"
```

...

since this is a boolean it should be : 

```json
optional: true
```

to be interpreted correctly :/

**Comment by alexAubin** [comment]
Hm my bad, there's still another issue :wink:

**Comment by alexAubin** [comment]
So I fixed the other issue in https://github.com/YunoHost/yunohost/commit/0bd781be4735169685473f7e3969c6a45f6c0b3e

Though I'm not sure to understand why the original code was like this ... in fact here's the commit that introduced the issue back in 2.4.1 : https://github.com/YunoHost/yunohost/commit/f7add32acbca053f8ff8bcf035bee5f272f6180a

But I don't understand why if the arg is optional *and* the arg is empty string, then the behavior should be different that if it's None ...

Maybe it's important, maybe it's not ¯\\\_(ツ)\_/¯ But to me it sounds more logical with the new code..

**Comment by alexAubin** [comment]
Closing the issue because it's basically fixed (c.f. follow-up https://github.com/YunoHost-Apps/jirafeau_ynh/pull/54 )
