### ISSUE TITLE
in some case, dyndns update couldn't get the ipv4 AND the ipv6 of the server and that seems to break everything

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1262]
In some weird situation, it happens that yunohost could not get the ipv4 and the ipv6 of the server, BOTH of them (and so no ip) but still push a configuration to bind but WITHOUT A/AAAA records thus making it unresolvable.

I don't know how this situation could happen but our code don't handle it and that's probably the cause of the situation where a domain is registered but unresolvable.

Some partial logs:

> 2019-01-03 12:34:02,957: DEBUG - Building zone update file ...
> 2019-01-03 12:34:03,080: DEBUG - Could not get public IPv4 : [Errno 52] Invalid url https://ip.yunohost.org (does this site exists ?)
> 2019-01-03 12:34:03,180: DEBUG - Could not get public IPv6 : [Errno 52] Invalid url https://ip6.yunohost.org (does this site exists ?)
> 2019-01-03 12:34:03,182: DEBUG - Now pushing new conf to DynDNS host...
> 2019-01-03 12:34:03,564: SUCCESS - Your IP address has been updated on DynDNS

**Comment by MrControl** [comment]
I've had a similar problem, but in my case just the ipv6 was missing.  Any advice?

**Comment by ChildishGiant** [comment]
My diagnosis is complaining about the DNS for a noho.st domain and asked me to run `yunohost dyndns update --force` but that gives this output:
<details>

```
args:
  domain: null
  dry_run: false
  force: true
ended_at: 2023-07-13 21:07:17.698166
error: Could not update IP address to DynDNS
interface: cli
operation: dyndns_update
parent: null
related_to:
- - domain
  - domain2.tld
started_at: 2023-07-13 21:07:17.430226
success: false
yunohost_version: 11.1.22

============

2023-07-13 22:07:17,436: INFO - Updated needed, going on...
2023-07-13 22:07:17,437: DEBUG - Reusing IPv4 from cache: xx.xx.xx.xx
2023-07-13 22:07:17,437: DEBUG - Reusing IPv6 from cache: None
2023-07-13 22:07:17,679: DEBUG - initializing ldap interface
2023-07-13 22:07:17,684: DEBUG - Formating result in 'export' mode
2023-07-13 22:07:17,694: DEBUG - Now pushing new conf to DynDNS host...
2023-07-13 22:07:17,694: DEBUG - id 20133
opcode UPDATE
rcode NOERROR
flags 
;ZONE
noho.st. IN SOA
;PREREQ
;UPDATE
domain2.tld. ANY ANY
domain2.tld. ANY ANY
domain2.tld. ANY ANY
mail._domainkey.domain2.tld. ANY ANY
_dmarc.domain2.tld. ANY ANY
*.domain2.tld. ANY ANY
domain2.tld. ANY ANY
domain2.tld. 3600 IN A xx.xx.xx.xx
domain2.tld. 3600 IN MX 10 petal
domain2.tld. 3600 IN TXT "v=spf1 a mx -all"
mail._domainkey.domain2.tld. 3600 IN TXT "v=DKIM1; h=sha256; k=rsa; p=longkeygoeshere"
_dmarc.domain2.tld. 3600 IN TXT "v=DMARC1; p=none"
*.domain2.tld. 3600 IN A xx.xx.xx.xx
domain2.tld. 3600 IN CAA 0 issue "letsencrypt.org"
;ADDITIONAL
2023-07-13 22:07:17,697: ERROR - id 20133
opcode UPDATE
rcode NOTIMP
flags QR
;ZONE
;PREREQ
;UPDATE
;ADDITIONAL
```
</details>

**Comment by alexAubin** [comment]
This is not the same issue, the original issue is specifically about YunoHost not resolving IPv4 nor IPv6 ...

In fact I don't know how this could happen beyond "there's an outage on our infrastructure" ...

**Comment by alexAubin** [comment]
Closing because havent seen this issue reported in a while, this seem super funky that the code ain't able to fetch its IP but is able to push it on the dynette ...
