### ISSUE TITLE
the current logging strategy in "yunohost dyndns update" remove important information

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1264]
Right now we only start the logger if we need to update: https://github.com/YunoHost/yunohost/blob/1c80e7242b2be0df8d7d5660990ff3397e929fe1/src/yunohost/dyndns.py#L249 in consequence we miss important information for debugging like the ip we had before. We need to switch a strategy where we can get those previous information (like for example starting logging and abandoning if we don't need it).

We also don't get the output of "nsupdate" at the end that shows the generated zone, that would be very very VERY useful for debugging.

**Comment by alexAubin** [comment]
I guess it's been fixed since then though anyway nsupdate error messages are completely stupid and don't really explain why things fail usually...
