### ISSUE TITLE
Invalid error message on moulinette.network.download_text

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1265]
Here: https://github.com/YunoHost/moulinette/blob/b7ea1c4cf75f9d9aae50a70428e55d4c1c550c8d/moulinette/utils/network.py#L26 if yunohost doesn't managed to reach a server it will say "invalid url" but it can be a lot of other reasons.

For example here:

> 2019-01-03 12:34:03,080: DEBUG - Could not get public IPv4 : [Errno 52] Invalid url https://ip.yunohost.org (does this site exists ?)

It's very possibly either a rooting problem or a DNS problem. This error message is confusing and hide the reality, it needs to be changed.

**Comment by Psycojoker** [comment]
test

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/moulinette/commit/b68e046ad0c7047b42a637992ca878a3714865e3
