### ISSUE TITLE
Backups cannot be download by user "admin", only by "root"

### ISSUE THREAD

**Issue by Gofannon** [YunoHost/issues#1266]
# problem

Since the `root` user cannot connect by ssh easily anymore, the user `admin` does not have enough rights to access to the backup folder on the server.

It is not possible anymore to get back the backup easily on a computer by `scp` or `filezilla`

**admin user**
```bash
admin@yunohost:~$ ls -al /home/yunohost.backup/archives/
ls: impossible d'ouvrir le répertoire '/home/yunohost.backup/archives/': Permission non accordée
admin@yunohost:~$ 
```

**root user**
```bash
root@yunohost:~# ls -al /home/yunohost.backup/
total 16
drwxr-xr-x  4 root  root 4096 oct.   1  2016 .
drwxr-xr-x 18 root  root 4096 nov.   5 01:10 ..
drwxr-x---  2 root  root 4096 déc.  31 01:07 archives
drwxr-x---  2 admin root 4096 déc.  31 01:07 tmp
```
**Filezilla with admin user**
![filezilla_7 fuck you](https://user-images.githubusercontent.com/17145502/50738981-da53a100-11d9-11e9-9132-1a40766e4f26.png)

# Proposals

1. `chown -R admin /home/yunohost.backup/archives` (didn't test it)
2. have a "feature" in core to handle backups by CLI or GUI
3. have a dedicated user for managing backups

> IMO, this behavior is not complicated to handle for a technician but can be tricky for the people targeted by Yunohost (you have to do a `cp` as root before to be able to get your backups)

**Comment by Gofannon** [comment]
Because of this, the page https://yunohost.org/#/backup and command `scp admin@your.domain.tld:/home/yunohost.backup/archives/<archivename>.tar.gz ./` does not work

**Comment by Gofannon** [comment]
Made a proposal in the documentation to show a temporary solution : https://github.com/YunoHost/doc/pull/899

**Comment by alexAubin** [comment]
Closing, fixed by https://github.com/YunoHost/yunohost/pull/613
