### ISSUE TITLE
Display admin emails inside the webadmin ?

### ISSUE THREAD

**Issue by frju365** [YunoHost/issues#1272]
Il faudrait un moyen pour lire ses mail directement dans l'interface administrateur/utilisateur (envoi de d'id/mdp par exemple) qqch de stable avec les adresses locales.

**Comment by alexAubin** [comment]
Quelle est la motivation pour faire ça sachant qu'il y a déjà des apps qui s'occupent de ça ? 

Perso ça me parraît super relou à implémenter parce que le mail est un enfer :/ ...

**Comment by frju365** [comment]
la motivation, c'est qu'il n'y a pas besoin d'ajouter une app justement... car pour lire juste des message (sans forcément en envoyer), il n'y a peut-être pas besoin de sortir l'"artillerie lourde". :D Sinon, c'est pour l'envoi, et autre. Il serait bien donc d'avoir qqch en natif dans le logiciel directement.

Ça ne me paraît pas très difficile, du moins pour lire des mail qui sont très certainement retranscrit sous la forme de fichier dans /var/mail qqch, non ?

Après ce n'est qu'une idée de fonctionnalité, qui serait selon moi très intéressante.

**Comment by alexAubin** [comment]
Same as "let's have the chat inside the webadmin" and "let's have a file browser in the webadmin", this feels like a pandora box and it's not clear why it'd be so great investing time/energy in this
