### ISSUE TITLE
backup missing dyndns keys

### ISSUE THREAD

**Issue by tbhi** [YunoHost/issues#1275]
I can't see the dyndns keys for the noho.st I'm using in the backup created by `yunohost backup create`.

```
# tar tf /home/yunohost.backup/archives/*.tar.gz | grep dyndns 
conf/cron/yunohost-dyndns
#
```

**Comment by Psycojoker** [comment]
@zamentur ^

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost/pull/1101
