### ISSUE TITLE
Add an input/output option to firewall rules

### ISSUE THREAD

**Issue by Dark-Fenix** [YunoHost/issues#1279]
Hi Yunohost team !

As you know, or as you can see in this screenshot, you can't specify if the iptables rules you want to create is for "in" ou "out" flows.

It could be very interesting to allow users to do so, don't you think ? :)

![screenshot from 2019-01-23 19-00-14](https://user-images.githubusercontent.com/4449399/51627377-304a7780-1f42-11e9-96db-5926a420c292.png)

Of course, this screenshot is from the latest version of Yunohost.

Regards, greetings, etc.

**Comment by Psycojoker** [comment]
Thx for taking the time to suggest this feature :)

**Comment by alexAubin** [comment]
Closing because I don't know why this would be useful to create rules for outgoing traffic...
