### ISSUE TITLE
Do not log migration into /tmp

### ISSUE THREAD

**Issue by opi** [YunoHost/issues#1280]
https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/data_migrations/0003_migrate_to_stretch.py#L38

Sadly, my migration get stuck and I have to reboot, and the `/tmp` folder was empty...

I suggest to use the `/var/log/yunohost` folder. I can make a pull request if needed.

kisses

**Comment by alexAubin** [comment]
> I can make a pull request if needed.

Yes please :+1:

**Comment by opi** [comment]
merged
