### ISSUE TITLE
Remove old SMTP port (465) from Fail2ban jail.conf

### ISSUE THREAD

**Issue by opi** [YunoHost/issues#1283]
The `jail.conf`file still use the 465 instead of the 587 use by starttls 
https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/templates/fail2ban/jail.conf#L565

I someone confirm it's a bug, I can create a pull-request.

**Comment by alexAubin** [comment]
Uh that is weird that this "465" is hard coded. But otherwise I thought it was the "submission" port which corresponds to 587 ? There's a file in debian listing the correspondance between those name and actual port numbers

**Comment by opi** [comment]
indeed "submission" seems to be an alias to 587 (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=714632), but I can't find the listing of correspondance.

**Comment by alexAubin** [comment]
`/etc/services` :wink:

**Comment by opi** [comment]
damn right. 
`submission      587/tcp                         # Submission [RFC4409]`.

Should we clean the jail.conf template to remove hardcoded 465 port now ?

**Comment by alexAubin** [comment]
Why not yep :+1: That'd look cleaner

**Comment by opi** [comment]
Here you go https://github.com/YunoHost/yunohost/pull/637

**Comment by alexAubin** [comment]
Merged
