### ISSUE TITLE
Check that apt is not "dans les choux" before trying to install app dependencies

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1284]
In some cases, some shit happened with apt and it won't work until something like a `dpkg --configure -a` thing is ran and the issue behind it is solved.

Meanwhile, user might ignore this and try to install apps ... It would be nice if the `ynh_install_app_dependencies` (or whatever the helper is called) would fail nicely by detecting this situation instead of making it look like the app itself is broken :s. We could even integrate this in the core as a check prior to any app install.

**Comment by maniackcrudelis** [comment]
Is it sure in any case to run `dpkg --configure -a` ?

**Comment by alexAubin** [comment]
I'm not sure it covers 100% of the cases, and sometimes the `dpkg --configure -a` might fail I think ... (I don't have any clear example in mind though). I don't think we can just automatically solve this ourselves, but anyway just detecting this situation and not failing miserably would already be awesome :wink:

**Comment by maniackcrudelis** [comment]
I guess we could parse the output log to detect that error. and try to run this command before retrying.
Was that what you had in mind ?

**Comment by alexAubin** [comment]
Nah I was more thinking about trying to see if there's some `apt is-dans-les-choux` or some file flagging that apt (or dpkg) still has some pending action, before we try to run `apt install`. I don't know exactly what, but we might be able to find a trick (similarly to the dpkg lock thing :wink: )

**Comment by maniackcrudelis** [comment]
I see...
Difficult to implement though, unless you know a way to break apt.
But, I guess we could add such a test into the same helper that check dpkg lock.

If you have any idea about how to break apt, I can work on that this afternoon.

**Comment by alexAubin** [comment]
The most obvious example I can think of is the whole metronome update stuff triggering an interactive thing where you need to choose between keeping the old conf or the new one. I think you can try to : 
- start with a fresh yunohost
- enable the testing repo for force.yunohost.org in sources.list
- apt dist-upgrade should propose a new metronome version
- if you keep going in non-interactive mode (or kill apt or Ctrl+C when the question is asked ?) that should break apt :wink:

**Comment by maniackcrudelis** [comment]
I'll try that :)
Love to break my apt :D

**Comment by maniackcrudelis** [comment]
So, I see 2 different ways to do that
- Either we try to run an apt command to induce this error. But which command would it be ?
- Or we can implement the way apt is detecting that this command should be used. Which is here: https://sources.debian.org/src/apt/1.4.9/apt-pkg/deb/debsystem.cc/#L141-L174
Which is simply
    - Have a look to the directory `/var/lib/dpkg/updates/`
    - Detect if there's any files with a name made of 4 numbers (maybe more ?)
    - Ask to an admin to run this command. (Or any other action)

**Comment by alexAubin** [comment]
```
dpkg-query -f '${status} ${package}\n' -W | awk '$3 == "half-configured" {print $4}'
```

and

```
dpkg --audit
```

look like nice and clean solutions :+1:

**Comment by maniackcrudelis** [comment]
Ok, I rebroke my apt \o/

The first command shows me nothing, and return 0.
The second one tells me:
```
Les paquets suivants ont été dépaquetés mais ne sont pas configurés. Ils
doivent être configurés en utilisant dpkg --configure ou l'option configure
du menu de dselect pour pouvoir fonctionner :
 metronome            Lightweight XMPP server with advanced microblogging featu
 yunohost             manageable and configured self-hosting server
```
And return 0...
Not enough in both case to put it in a script. I'll have a look to an option maybe to have something else than 0

**Comment by alexAubin** [comment]
Meh .. I guess we need to parse the output somehow to check it's not empty ?

Or anyway, I guess using what `apt` does (as you pointed out https://sources.debian.org/src/apt/1.4.9/apt-pkg/deb/debsystem.cc/#L141-L174) is enough and maybe more consistent then

**Comment by maniackcrudelis** [comment]
I found indeed a script that check if the output is empty or not, and indeed, trying on a VM with a still working apt, the output is empty.
Not so fond though of simply checking if the output is empty or not...
Rather prefer to do the same check than apt, especially since that a very easy check.

**Comment by alexAubin** [comment]
>Rather prefer to do the same check than apt, especially since that a very easy check.

Agreed :+1:

**Comment by maniackcrudelis** [comment]
About the first command, with dpkg-query, metronome is `unpacked`, instead of `half-configured`. That's why the command return nothing.
Not sure also that would work will all locales.

**Comment by maniackcrudelis** [comment]
So the code is done and working on my VM.
Not tested the code as it is now though.
Let's discuss about what to do with it before.

https://github.com/YunoHost/yunohost/pull/638
