### ISSUE TITLE
Password appears in /var/log/yunohost/yunohost-api.log

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1289]
People using yunohost-api discovered that password appears in /var/log/yunohost/yunohost-api.log

https://forum.yunohost.org/t/ssh-root-remplace-par-admin-precisions/6961/31

```
2019-02-01 20:55:41,151 DEBUG gnupg _read_response - [GNUPG:] PLAINTEXT_LENGTH 17
2019-02-01 20:55:41,152 DEBUG gnupg _read_data - chunk: ‘XXXXXXXXXXXXX’
2019-02-01 20:55:41,152 DEBUG gnupg _read_response - [GNUPG:] 
```

Here is the line which send this debug message
https://github.com/YunoHost/moulinette/blob/1e90dd4bb1dc5f774a4a81b57c99800529100ab9/moulinette/authenticators/__init__.py#L142

And here the pr that made debug messages appears in this log
https://github.com/YunoHost/yunohost/pull/603

For the moment, i have communicate to run this command to avoid that:
```
sed -i "s/LOGGERS_LEVEL = 'DEBUG'/LOGGERS_LEVEL = 'INFO'/" /usr/bin/yunohost-api
```

The good way to fix this issue could be to avoid gnupg python library to send debug message.
It seems it should be the case (the doc says verbose=False by default)
https://pythonhosted.org/python-gnupg/index.html#getting-started

Here is an untested code that might disable gnupg logger (untested)
https://github.com/YunoHost/yunohost/tree/password-in-log

**Comment by alexAubin** [comment]
Fixed in 3.4.2.3
