### ISSUE TITLE
Progress bar in the admin interface for longtime install app

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#129]
###### Original Redmine Issue: [129](https://dev.yunohost.org/issues/129)

Author Name: **Anonymous**

---

For app having a longtime running install process, display a progress bar in the admin.

Probably needed in command line too.

API to be defined.

**Comment by alexAubin** [comment]
Related : https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_script_progression/ynh_script_progression

**Comment by alexAubin** [comment]
Closing this following the work on ynh_script_progression + https://github.com/YunoHost/yunohost-admin/pull/244
