### ISSUE TITLE
On user deletation, some app (nextcloud) won't remove the user data.

### ISSUE THREAD

**Issue by ghost** [YunoHost/issues#1290]
On a Yunohost 3.3.4 I have deleted my user account.

A few weeks later, I have recreated the user account with the same user name and the same password.

All the emails and the Nextcloud content was still there.  It was useful for me, but I do not think that it should still working that way.

**Comment by eauchat** [comment]
Since last yunohost release (3.4 if I'm not mistaken), when you chose to remove a user, there is a tickbox that let you chose if you want to also remove the user's data (at the moment, this deletes emails and home directory).
See precious issue #1245.

**Comment by eauchat** [comment]
So now if you tick this box when removing a user it's emails will be deleted. However it won't (if I'm not mistaken) remove Nextcloud or other apps data.
Maybe it would be useful to implement that as well, but I'm not so sure how to make it so it supports all apps.

**Comment by Psycojoker** [comment]
> However it won't (if I'm not mistaken) remove Nextcloud or other apps data.

I think so, it looks like a problem with app packaging and ldap integration.

**Comment by alexAubin** [comment]
I suppose these apps should handle this via the post_user_deletion hook (using the hook system that isn't documented lulz)

**Comment by AkselRocks** [comment]
Can confirm that bug also for app "hubzilla".

**Comment by alexAubin** [comment]
Closing because 5 years old, and cf previous comment, that should be handled on Nextcloud's side with a `post_user_delete` hook
