### ISSUE TITLE
The yunopaste CLI tool is broken

### ISSUE THREAD

**Issue by anto1ne** [YunoHost/issues#1291]
Hi try to use yunopaste and I think I have found some bug ...

Here are some example 

as admin 
`journalctl -xe | yunopaste` returns an url
`sudo journalctl -xe | yunopaste` return an error : "Invalid usage: No input is provided."

as root 
`yunohost app upgrade lstu -u https://github.com/YunoHost-Apps/lstu_ynh/tree/testing --debug | yunopaste` fails

**Comment by alexAubin** [comment]
(Personally I basically stopped using it entirely because it was *always* failing ... would be nice to resurect it at some point)

**Comment by tituspijean** [comment]
Fixed by https://github.com/YunoHost/yunohost/pull/1558
