### ISSUE TITLE
Apps page: add more details on date

### ISSUE THREAD

**Issue by nqb** [YunoHost/issues#1293]
Hello,

When you're on a ynh instance or in https://yunohost.org/#/apps, there is a date mentioned for each app but we don't know what it mean:
![screenshot from 2019-02-06 23-27-14](https://user-images.githubusercontent.com/10830260/52378088-0e371600-2a67-11e9-92c5-0a3376456799.png)

I saw the icon when you're on https://yunohost.org/#/apps but you don't get it on a ynh instance (3.4 here). I supposed the icon mean that the app has been upgraded as this date.

It would be nice to be more explicit, especially for neophyte users.

**Comment by Axolotle** [comment]
There's no more dates in the web-admin app catalog, is this still relevant ?

**Comment by nqb** [comment]
Still presents on https://yunohost.org/#/apps @Axolotle

**Comment by zamentur** [comment]
It has been fixed on doc too
