### ISSUE TITLE
DMARC none could be interpreted as DMARC reject by some mail hosters

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1297]
I get this message on FFDN mailing liste:

> Les services de mails de plus en plus facho sur le respect de DMARC/DKIM/SPF, au point de considérer l'action DMARC 'none' comme 'reject', et du coup dégrader la notoriété de serveurs de liste de diffusions, au point d'être qualifiés de spammeurs, et que freedesktop envisage d'arrêter les mails et passer sur des discussions web...

More info on: https://pad.pirateparty.be/p/r.8ce7c1c63961bca270c8dd042793c04a

We might change our recomendations for more accurate rules ?

https://github.com/YunoHost/yunohost/blob/e293cdcd77a02c863cff7e7c79a307f3ad0ffd43/src/yunohost/domain.py#L336

**Comment by alexAubin** [comment]
Bump ... what should be done ? :/

**Comment by alexAubin** [comment]
... bumpity bump ...
