### ISSUE TITLE
Repository - Move application to right location

### ISSUE THREAD

**Issue by Gofannon** [YunoHost/issues#1298]
Hello,

While transferring a application to the community, I moved it to the wrong repository. I don't have right to move it to the right location.

Could you, please, move the application Airsonic from https://github.com/YunoHost/airsonic_ynh to the repository https://github.com/YunoHost-Apps

See https://github.com/YunoHost/apps/pull/685#issuecomment-461319938

**Comment by Psycojoker** [comment]
> Could you, please, move the application Airsonic from https://github.com/YunoHost/airsonic_ynh to the repository https://github.com/YunoHost-Apps

Done.

I'll let you close this issue if everything is fine :)
