### ISSUE TITLE
Shouldn't we optimize `ynh_app_setting_{get,set}` ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1299]
Opening this question but I have been wondering if we shouldn't optimize `ynh_app_setting_{get,set}` : https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/helpers.d/setting

Currently they trigger a yunohost call and this is kinda overkill considering that it's essentially just reading/writing a yaml file 
- it's not a big deal to call `yunohost` directly **once** and ideally that'd be preferrable to keep everything consistent and in a single place...
- but the fact is that many apps will call it 5\~10 times at the beginning of each scripts and it just basically take about 5\~10 seconds for nothing, especially on slow hardware
- the vpnclient / hotspot app heavily rely on this helper (which I think is bad design because they store settings which strictly-speaking are unrelated to yunohost ...) but anyway ...

So I dunno, but could be nice to win those 5~10 seconds by just using a small yaml-manipulating command line somehow.

**Comment by Psycojoker** [comment]
I always though we needed a lower layer between moulinette and yunohost (like git as "plumbering") for this kind of operations and calling it directly from YunoHost.

Something like a yunohost-lib on which we could build needed cli tools.

That would solve the problem even if it's a bit overkill here ^^'

**Comment by maniackcrudelis** [comment]
Should we do that with Python ?
Considering what's really in a settings.yml, I can rewrite those 3 commands really quickly in bash

**Comment by alexAubin** [comment]
Naively I'd say yes, let's do it in Python :P ... To really be sure that the output (when writing) will be valid YAML 

Maybe quick bash commands are good enough for this, I don't know YAML well-enough to know about edge-cases that would be "hard" to handle.

**Comment by Psycojoker** [comment]
YAML is a shitty very complex format, it may looks easy here because we don't use a lot of features, but you really *don't* want to do that in bash with sed or something like that.

Also format/api might change, we want that layer of abstraction.

**Comment by Josue-T** [comment]
I think too, that's easy to use python or other thing like that which already implement a clean way to manage the YAML syntax. Maybe something like jq for YAML...

**Comment by alexAubin** [comment]
PR got merged
