### ISSUE TITLE
Client mail configuration and SSL certificates in multi-domain context

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1301]
Today a user came with an interesting use case : 
- main domain is `maindomain.tld`
- there's a secondary domain, let's say `other.tld` (or can be `sub.maindomain.tld`) 
- mail address is in `username@other.tld`
- thunderbird will get a somewhat appropriate config *BUT* the ssl certificate provided by postfix will be the one of the main domain ... 

This is kinda expected from https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/templates/postfix/main.cf#L31 but the real issue is that the user reports that Thunderbird ask for a confirmation for the certificate *each time* an email is sent for example. I expect that this is related to the mismatch between the domain and the certificate.

So I'm wondering if, in the IMAP/SMTP configuration provided by https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/templates/nginx/autoconfig.tpl.xml we shouldn't point to the main domain everytime.

This does leak what the main domain is ... but turns out that we can't do otherwise right now (except if somehow we manage to have several certificates in postfix ... [random idea]maybe using nginx as reverse proxy ? dunno if that can work[/random idea])

**Comment by nqb** [comment]
https://forum.yunohost.org/t/multi-domaine-en-pratique-viable-ou-pas/6327/10

**Comment by nqb** [comment]
> This is kinda expected from https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/templates/postfix/main.cf#L31 but the real issue is that the user reports that Thunderbird ask for a confirmation for the certificate _each time_ an email is sent for example. I expect that this is related to the mismatch between the domain and the certificate.

I can confirm this. I have the same setup.

**Comment by alexAubin** [comment]
Note this discussion on serverfault : https://serverfault.com/questions/344038/virtual-domains-with-postfix-and-ssl 

>If you want each domain to use a valid SSL certificate, you have 2 solutions: use a multi-domain certificate, or set up each domain on a unique IP. 

So I don't think there's any solution to avoid leaking the main domain name ultimately ...

**Comment by nqb** [comment]
Ok.

I tried to hack my DNS config few days ago without success:
```
;; ANSWER SECTION:
imap.other.tld                3600 IN CNAME    imap.maindomain.tld.
imap.maindomain.tld.    3599 IN A     PUBLIC_IP
```
but at the end, Thunderbird is configured with `imap.other.tld` and get a certificate for `imap.maindomain.tld` so I got a warning.

**Comment by alexAubin** [comment]
Somewhat related, though I don't think it adresses the SSL certificate thing (because there's no SNI mechanism anyway ?)

Still could be useful to clarify some bits of configuration in multidomain context ? 

https://www.sysnove.fr/blog/2019/07/decouverte-multi-instances-postfix.html

**Comment by Jojo144** [comment]
I have the same problem :-)

**Comment by alexAubin** [comment]
For some reason I was trying to read a bit more about this today and apparently Postfix >= 3.4 (available in Buster) supports SNI handling, which means this could be fixed

Here are some details: https://serverfault.com/questions/928926/postfix-multi-domains-and-multi-certs-on-one-ip/1000977#1000977

**Comment by alexAubin** [comment]
We also probably need to tweak the dovecot conf with similar SNI stuff as postfix is just the SMTP part.

This wiki documents the syntax : https://wiki.dovecot.org/SSL/DovecotConfiguration

It was about not all clients supporting SNI but that's from 2017 and already then most recent client did support it ?

**Comment by julienhel** [comment]
Bonjour,

La même chose chez moi via Outlook mon domaine secondaire pour mon association utilise le certificat du domaine principale de mon site perso , ce qui crée des erreurs de certificats régulières sur les clients de messagerie.

Une solution est-il envisageable avec les MAJ de postfix et de dovecot ?

Merci encore pour le travail effectué sur cette outils merveilleux :)

**Comment by alexAubin** [comment]
>Une solution est-il envisageable avec les MAJ de postfix et de dovecot ?

Oui, mais ce n'est pas le simple fait de mettre à jour, il faut aussi qu'on adapte la configuration ...

**Comment by Neustradamus** [comment]
@alexAubin: Have you looked this problem?

**Comment by tutle** [comment]
Bonjour, j’ai migré un deuxième site sur mon serveur yunohost sur lequel j’ai déjà un autre site.
Je voudrais remettre en service les listes de diffusion mais je ne sais pas comment on peut configurer mailman pour 2 domaines, j’ai vu ça
https://www.gnu.org/software/mailman/mailman-install/postfix-virtual.html
mais n’y comprend pas grand chose.
Toute aide est la bienvenue.

**Comment by alexAubin** [comment]
Ce n'est pas le sujet du ticket ...

**Comment by tutle** [comment]
Je pensais que ça entrait dans la config mail en multi domaine, pardon

**Comment by Neustradamus** [comment]
Oui c'est lié au multi-domaine.

**Comment by isAAAc** [comment]
ping @alexAubin , 
in irc: `23:04:15         Aleks[m] | besoin d'un volontaire pour se pencher sur le problème de comment utiliser le machin de SNI de postfix`
dis moi comment je peux aider, 
je suis confonté au problème avec deux ndd différents

**Comment by alexAubin** [comment]
What I was meaning was somebody to have a deeper look at https://serverfault.com/questions/928926/postfix-multi-domains-and-multi-certs-on-one-ip/1000977#1000977 and maybe https://doc.dovecot.org/configuration_manual/dovecot_ssl_configuration/ and validating that tweaking the conf (especially postfix) does fix the issue
