### ISSUE TITLE
Main domain: Error: Argument 'domain' is required

### ISSUE THREAD

**Issue by Qwertie-** [YunoHost/issues#1303]
I just copied the yunohost image to an sd card and booted the raspberry pi 3 B+
I got a prompt asking to go the post installation. After pressing `y` I got the error `Main domain: Error: Argument 'domain' is required`

**Comment by alexAubin** [comment]
Hmyea I think this image is starting to be quite old and the bootprompt was kinda broken at this point ... I think the best option right now is to just open a new tty (ctrl+alt+f2 or f3 or f4 ...) and log in as root (password should be yunohost) and start the postinstall with `yunohost tools postinstall`.

Or do the postinstall from the webadmin (via the local IP)

I'll work in the coming days on updating the RPi image and validating that the UX is not broken :wink:

**Comment by alexAubin** [comment]
Hellow @Qwertie- ,

the new RPi image has been published and should hopefully fix this issue ... though I was not able to validate it myself because I lack an HDMI screen. (But install through SSH works, at least)

So in case you happen to have time to test this, it would be useful to have feedback on this ! :wink:

**Comment by Qwertie-** [comment]
I can test this probably in the next few days. I'll let you know how it goes

**Comment by Qwertie-** [comment]
I tested it and I didn't get the domain is required error but it failed after entering the admin password

**Comment by alexAubin** [comment]
Uh but how dit it failed ...

**Comment by Qwertie-** [comment]
Sorry I didn't get to see how. It told me to run a command to see the output and I quit to run the command but then it dropped me back on the login screen and removed the message about what command to run

**Comment by decentral1se** [comment]
I think this can be closed, no? Original reported issue is solved :+1:
