### ISSUE TITLE
There's no operation log created during backup_create

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1305]
Today a user came with a backup issue (email backup not working for some reason) but we couldn't investigate it easily, because no log was created :/ 

Not sure how complicated it is to implement this. I understand that it can't easily be split into Backup "app1" then "app2" then "system part 1" then "system part 2" because of the way it happen, but I'm not sure such a granularity is necessary. Just having a general log "Backing up [many stuff]" would be enough.

**Comment by zamentur** [comment]
There is no log on backup cause it doesn't change anything on the system. 
But we could implement it, may be on each part of the backup.

**Comment by zamentur** [comment]
Note if i implement it , there will be a lot of log for people using daily backup... 1 per application per day

**Comment by Psycojoker** [comment]
I think the "real" problem here is that we don't have logrotate like feature for operational logs, I ended up on an instance with a failing renew-cert and hundred and hundred of operational logs :/

So we probably have some kind of strategy like "keeping x operational log with the same signature and a total of max y operational logs" and maybe put the rest compressed in some kind of compressed archive with search capabilities on it.

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost/commit/fe9f0731e81af43a2bffa0ea619d128b2a328b99
