### ISSUE TITLE
upgrading with ynh_setup_source - improvement

### ISSUE THREAD

**Issue by anto1ne** [YunoHost/issues#1306]
Hi,

When upgrading an application, *ynh_setup_source* unpacks source in the directory and __overwrites__ all existing files, including conf files (which contains local setting) and data.

It would be nice if it was possible to specify files and directory in app.src to not overwrite during this process.

Antoine

**Comment by maniackcrudelis** [comment]
We hardly have any apps that store config in a file which is already into the archive.
Which means that overwriting files shouldn't overwrite a config file. Otherwise that's an error from the dev upstream.

On which app do you have this issue ? And on which files ?

**Comment by anto1ne** [comment]
well, I am looking at PluXml documentation and they recommend not to overwrite some directory when upgrading. https://wiki.pluxml.org/installer/installation/#mise-a-jour

I also think that their archive is not going to overwrite some file during upgrade ... but I can not check that

**Comment by maniackcrudelis** [comment]
If data, plugins and themes doesn't contains any files that would be modified on a already install instances, there will be no problems.
I guess those directories will contains new files, as the user creates content, so those files are not going to be overwrite.

**Comment by anto1ne** [comment]
data stores all new articles, commentaries and also config file (users)
plugins stores additional features added by users.

Those directory contain an index.html that already exist in the source (but it seems to be and stay an an empty file?).

themes contains several files for the default theme, it can be modified by an user who wants his own theme. 

to summarize, it seems that overwriting files won't affect data and plugins but may affect theme

nevertheless, it should be better that the default theme is overwritten in order to have a complete upgrade

@maniackcrudelis : do you think that we can close this bug and assume that the upgrade will work ?

**Comment by maniackcrudelis** [comment]
About the theme, if an user wants to modify it, it would probably be better to copy it, them to modify it as he wants.

I think we can assume that the upgrade will works fine, as it works for all other apps so far.
