### ISSUE TITLE
Postinstall through webadmin fails miserably if password is less than 8 characters

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1307]
That's the second time a user come on the support with this issue : if you put e.g. 8 characters during the web postinstall, it will fail miserably just saying "An error occured" with no clue why :/

Probably an issue with the way errors are handled in that special case ?

**Comment by decentral1se** [comment]
Aha, this cannot happen anymore :)

We merged https://github.com/YunoHost/yunohost-admin/pull/245 to fix it.

This also answers the question in https://github.com/YunoHost/yunohost-admin/pull/245#pullrequestreview-242787325 further!

**Comment by alexAubin** [comment]
Indeed, cheers !
