### ISSUE TITLE
`ynh_print_warn` and `ynh_print_err` causing buggy message in the webadmin

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1309]
Eylo,

`ynh_print_warn` and `ynh_print_err` use the "shell color" thing, e.g.

```bash
ynh_print_log "\e[93m\e[1m[WARN]\e[0m ${message}" >&2
```

but in the webadmin, those are not interpreted correctly and this yield : 

```text
[91m[1m[ERR][0m E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.
```

Dunno what to do with this ...

**Comment by maniackcrudelis** [comment]
Arg...
I'll make some test, especially about how the web admin is identified by bash. As we're not running in a terminal, we could maybe detect that and not print colors.
I'll make some test this afternoon

**Comment by maniackcrudelis** [comment]
Fixed here https://github.com/YunoHost/yunohost/pull/659

**Comment by alexAubin** [comment]
Yolofixed the other day in stretch-unstable directly...
