### ISSUE TITLE
nodejs on aarch64

### ISSUE THREAD

**Issue by yalh76** [YunoHost/issues#1311]
ynh_install_nodejs helper use the [N - Node.js version management](https://github.com/tj/n).

But there is a issue in N, https://github.com/tj/n/issues/521, arm64 and aarch64 are not detected correctly, they are detected as amd64.

N maintainer doesn't seem to accept the Pull Request to correct that issue.
So for now, the only way to fix that is to provide N the argument -a/--arch arm64 : https://github.com/tj/n/pull/448
but ynh_install_nodejs doesn't provide the --arch argument... 

Is it possible to add the --arch argument to ynh_install_nodejs helper and use it on https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/helpers.d/nodejs#L101?

**Comment by maniackcrudelis** [comment]
Yep, why not.
If you can, create a pull request on this helper to add that argument.

**Comment by yalh76** [comment]
I will try, but really not sure I can handle that, I let you know ^^

**Comment by yalh76** [comment]
Ready, to which branch of https://github.com/YunoHost/yunohost I must to my PR ?
By default, it proposes stretch-unstable

**Comment by alexAubin** [comment]
Yup :+1: Stretch-unstable is the branch to work with

**Comment by yalh76** [comment]
Perfect, PR done : https://github.com/YunoHost/yunohost/pull/660
