### ISSUE TITLE
Fix gzip compression in nginx

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1315]
In some cases, compressing the HTTP body can allow an attacker to
decrypt the secrets in the HTTP body (BREACH vulnerability) [1].

Debian has gzip compression enabled by default in nginx
(nginx.conf). This default is kept in YunoHost.

AFAIU, only a few YunoHost apps disable gzip compression explicitely:

    $ rgrep -E "gzip *off"
    YunoHost-Apps/owncloud_ynh/conf/nginx.conf:  gzip off;
    YunoHost-Apps/owncloud_ynh-old/conf/nginx.conf:    gzip off;
    YunoHost-Apps/sympa_ynh/conf/nginx.conf:    gzip off;
    YunoHost-Apps/nextcloud_ynh/conf/nginx.conf:  gzip off;
    YunoHost-Apps/huginn_ynh/conf/nginx.conf:    gzip off;
    YunoHost-Apps/bozon_ynh/conf/nginx.conf:	gzip off;
    YunoHost-Apps/gnusocial_ynh/conf/nginx.conf:          gzip off;
    yunohost/lal/nginx-vhost.sample:    gzip off;

I guess at least a few of the applications where gzip is not disabled
are vulnerable to BREACH. It would probably be safer to disable
compression for dynamic content in most applications and mabye include
this in the ginx configuration guide guide [3].

[1] http://breachattack.com/
[2] https://httpd.apache.org/docs/2.4/en/mod/mod_deflate.html
[3] https://yunohost.org/#/packaging_apps_nginx_conf_en

-----

what about https://github.com/YunoHost/yunohost/pull/356/files though ?

We discussed this in the corresponding PR and concluded that it was okay to enable gzip compression only for those file types which are supposed to be "static" files ?

-----

Sadly, I don't think it works 

The reason is that, currently, text/html is always included in the
gzipped MIME types whatever you do [1, 2]:

> Syntax: 	gzip_types mime-type ...;
> [...]
> Enables gzipping of responses for the specified MIME types
> in addition to “text/html”.

Example:

GET /yunohost/sso/?r=aHR0cHM6Ly9kZW1vLnl1bm9ob3N0Lm9yZy8= HTTP/1.1
Host: demo.yunohost.org
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101
Firefox/67.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: ynhSecurityViewedItems=[]; SSOwAuthUser=demo;
SSOwAuthHash=2db9e2a7466c21630668aad4fde4d86b2da5e50b5fcf415fe2ae4bbbb4e3f8590d0426f7e61d53eee8886b75657b51af0d96a1a2444762e6a46af32ee867e23e;
SSOwAuthExpire=1550266560.305
Upgrade-Insecure-Requests: 1
Pragma: no-cache
Cache-Control: no-cache

HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Fri, 08 Feb 2019 22:53:05 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
X-SSO-WAT: You've just been SSOed
Cache-Control: no-cache
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
Content-Security-Policy: upgrade-insecure-requests
Content-Security-Policy-Report-Only: default-src https: data:
'unsafe-inline' 'unsafe-eval'
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
X-Frame-Options: SAMEORIGIN
Content-Encoding: gzip

[1] https://trac.nginx.org/nginx/ticket/1083
[2] http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_types

**Comment by alexAubin** [comment]
PR got merged
