### ISSUE TITLE
Error: failed to get information for this service, it doesn't exists for systemd

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/issues#1316]
When using [`_get_service_information_from_systemd`](https://github.com/YunoHost/yunohost/blob/stretch-stable/src/yunohost/service.py#L343-L365) in the admin JS, it fails to get the status of one of my service.
The code says "this is the equivalent of 'systemctl status $service", but it's not. The service exist, I can start or stop it from CLI, with systemctl. As well as I can get the status without error.
This happens only when the service is stopped. If I start the service it works as expected.

The main issue here is that I can't start the service from the admin JS because it fails to load the page for this service, arguing that the service doesn't exist.

As this service is my personal video surveillance, the purpose was to control it remotely.

**Comment by Psycojoker** [comment]
You need to provide more detailed information like the service file and status and other things otherwise it's totally not possible to fix this issue.

**Comment by alexAubin** [comment]
I think I had a similar issue once I disabled a service ... I think I was trying to stop fail2ban - from the webadmin, and instead of Stop I clicked on Disable. Then it started to complain that the service did not exist just like Maniack reports...

**Comment by maniackcrudelis** [comment]
The service is 'motion', that's not link to a application.
There's not so much to say about it.

But I thought about it this morning, and as I remember, it's a sysvinit service.
The main problem is that it works perfectly with systemd, even if the service is stopped

**Comment by Psycojoker** [comment]
Ah, it probably need an "enable" step or something like that on the communication with systemd.

**Comment by alexAubin** [comment]
The PR is merged and should have fixed it
