### ISSUE TITLE
etckeeper killed my root

### ISSUE THREAD

**Issue by Jibec** [YunoHost/issues#1317]
hello,

I had an issue with space on **/** :

```
# df -h
Sys. de fichiers Taille Utilisé Dispo Uti% Monté sur
/dev/sda1          8,2G    7,5G  205M  98% /
```

Note: /var , /home and /home/yunohost.backup uses different partitions.

after deleting temporary files created by scripts (like `rm -rf /root/.[pip,cache,cpanm,composer,npm]`), I figured out I had to go deeper. Note on this temporary files, we should probably find a way to prevent npm/pip/composer running as root, but that's another story.

I have 4 Gigagbyte for /etc/

It sounds like too much, and most of it is taken from a ".git" repository:

```
# du --max-depth=1 -h /etc/.git/
8,0K	/etc/.git/info
340K	/etc/.git/logs
3,8G	/etc/.git/objects
16K	/etc/.git/refs
48K	/etc/.git/hooks
4,0K	/etc/.git/branches
3,8G	/etc/.git/
```

It looks like it's related to etckeeper.

Do we really make use of this tool? Would it be safe to simply remove it?

While following the YesWeHost project for quite some time, I can't recall using it.

After running `git gc`, here is the result:

```
# du --max-depth=1 -h /etc/.git/
12K	/etc/.git/info
52K	/etc/.git/logs
390M	/etc/.git/objects
12K	/etc/.git/refs
48K	/etc/.git/hooks
4,0K	/etc/.git/branches
391M	/etc/.git/
```

Thanks a lot for your help,

**Comment by alexAubin** [comment]
What is really strange is why you would end up with 4 Gig of stuff in etckeeper... Etckeeper just keep some versionning of the files in etc so that you can go backward in conf if needed some day. But having 4 Gig looks like you have heavy files in /etc/ that change a lot, also called "data" which shouldn't be there ?

**Comment by alexAubin** [comment]
c.f. https://github.com/YunoHost/yunohost/pull/803

**Comment by Jibec** [comment]
as YunoHost/yunohost#803 is merged, let's close this, thank you Alex
