### ISSUE TITLE
Application passwords can not contain { } ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1319]
I saw a least two users encountering this in the last month : 

```
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/app.py", line 836, in app_install
    args=args_list, env=env_dict
  File "/usr/lib/moulinette/yunohost/hook.py", line 358, in hook_exec
    command.append(cmd.format(script=cmd_script, args=cmd_args))
ValueError: Single '}' encountered in format string
```

I suspect there's also something similar if there's a `+`, c.f. https://github.com/YunoHost-Apps/borgserver_ynh/issues/8 (maybe not related to the same technical thing tho, idk)

**Comment by maniackcrudelis** [comment]
Not sure there's any way to fix such errors.
{} are highly integrated in bash script.
Maybe we could escape all characters like that, but not sure it will be a good solution all along the script.

We could also check if there's such characters and print a warning.

My opinion on that is that an user should never use that kind of characters in a password. If not bash, the app itself could break down as well because of characters used in its language.

**Comment by alexAubin** [comment]
Well then maybe we can validate that password-type values do not contain { } before launching the install

**Comment by maniackcrudelis** [comment]
That's probably not only with {}...

Anyway, I guess I could make a small helper to check or escape characters in passwords...

**Comment by Psycojoker** [comment]
I remember that we already had this discussion on an application... it was in nextcloud no?

**Comment by maniackcrudelis** [comment]
It could be any application

**Comment by Psycojoker** [comment]
Yes I know, it's just that we discussed there potential ways to fix that.

**Comment by nqb** [comment]
It's was here: https://github.com/YunoHost-Apps/etherpad_mypads_ynh/issues/61

**Comment by alexAubin** [comment]
Proposing a fix in https://github.com/YunoHost/yunohost/pull/671

**Comment by maniackcrudelis** [comment]
> [...] there's probably nothing I want to do.

And still I'm doing it...

Maybe it could be tried as a helper:
```
ynh_check_password () {
	ynh_print_OFF
	local password="$1"
	local fixed_pwd=""

	local i
	for i in $(seq 0 ${#password})
	do
		local real_char="${password:$i:1}"
		local octal_char="0$(printf "%o\n" "'$real_char")"
		fixed_pwd+="\\$octal_char"
	done

	echo "$fixed_pwd"
	ynh_print_ON
}
```
Used that way:
```
ynh_print_OFF; password="$(ynh_check_password "$password")"
echo "password=$password"
echo -e "password-e=$password"
```

The first echo will show a octal version of the string, the second one, with `-e` will show the real string.
Tried with the password gave in the issue: "bu\?a{:Q[*dWM-\7+MA-/"

```
echo "password=$password"
password=\0142\0165\0134\077\0141\0173\072\0121\0133\052\0144\0127\0115\055\0134\067\053\0115\0101\055\057\00
echo -e "password-e=$password"
password-e=bu\?a{:Q[*dWM-\7+MA-/
```

**Comment by alexAubin** [comment]
PR got merged

**Comment by randomstuff** [comment]
Looks to me your problem is that this is relying on `["sh", "-c", some_thing_with_possible_injections]`:

```python
# Construct command to execute
if user == "root":
    command = ['sh', '-c']
else:
    command = ['sudo', '-n', '-u', user, '-H', 'sh', '-c']

if no_trace:
    cmd = '/bin/bash "{script}" {args}'
else:
    # use xtrace on fd 7 which is redirected to stdout
    cmd = 'BASH_XTRACEFD=7 /bin/bash -x "{script}" {args} 7>&1'

# prepend environment variables
cmd = '{0} {1}'.format(
    ' '.join(['{0}={1}'.format(k, shell_quote(v))
              for k, v in env.items()]), cmd)
command.append(cmd.format(script=cmd_script, args=cmd_args))
```

This is `exec`-ing something similar to:

```python
["sudo", "-n", "-u", user, "-H",
  "sh", "-c",
  '/bin/bash "{script}" {args}'.format(script=cmd_script, args=cmd_args))]
```

Instead, it should probably be done somewhat like this:

```python
(["sudo", "-n", "-u", user, "-H", "/usr/bin/env"] +
 ['{0}={1}'.format(k, shell_quote(v)) for k, v in env.items()] +
 ["/bin/bash", script] + args)  
```

This way, the arguments (`args`) are not processed by the shell (`sh`) and are immune to shell command injection.

*Edit: the arguments looks like they are properly quoted before that snippet.*

**Comment by randomstuff** [comment]
>  If not bash, the app itself could break down as well because of characters used in its language.

Well any sane language should be able to correctly deal with `{}` regardless of whether it is used in the language. You may have to to some proper escaping if you extrapolate the value in a template and then you should be fine.

**Comment by alexAubin** [comment]
To me the original issue sounded more like an issue in python related to `format`, but yes, we should probably address the issue in a more general way to avoid shell-stuff as well like quotes :+1: 

What you suggest : 

```python
(["sudo", "-n", "-u", user, "-H", "/usr/bin/env"] +
 ['{0}={1}'.format(k, shell_quote(v)) for k, v in env.items()] +
 ["/bin/bash", script] + args)  
```

looks good to me on the principle :+1: 

Edit: ah but we did already have the `shell_quote(v)` :sweat_smile: Well anyway getting rid of the `format` make things better I guess

**Comment by randomstuff** [comment]
Yeah, I don't think the `.format()` is related to the problem in this case.

**Comment by Psycojoker** [comment]
The problem is how apps scripts in general handles variables escaping, not really a problem in the python code itself.

**Comment by randomstuff** [comment]
Indeed, the args seems property quoted (before that snippet).
