### ISSUE TITLE
What do with setups with Install-Recommends set to 'false' ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1320]
An user came today with an interesting situation. While trying to install ttrss, php7.0-xml and php7.0-mbstring were missing. Quite funny that nobody noticed it so far ... So let's see why it's usually installed ? 

```
# aptitude why php7.0-xml
i   yunohost        Recommends php-gettext    
i A php-gettext     Depends    php-php-gettext
i A php-php-gettext Depends    php-pear       
i A php-pear        Depends    php-xml        
i A php-xml         Depends    php7.0-xml 
```

So, `yunohost` as a debian package *recommends* `php-gettext` which in turn depends on `php7.0-xml`

And in fact yes, this user did not have `php-gettext` ... yet he used the install script which does not uses `--no-install-recommends`.

The reason is that some VPS provider include this in the apt conf (`/etc/apt/apt.conf.d/`): 

```
APT::Install-Recommends "false";
```

which disable recommended packages ...

That's kinda worrying because all app packagers will typically test their apps on system with install-recommends to true (the default value) and many dependencies will be installed because of this.

So, I see two possibilities which do not exclude one-another : 

1. During the install script, detect if this setting is set to false, and disable it if that's the case ... That's a bit intrusive, but at least it guarantees that you don't end up in that kind of situation where a kinda well-known app ain't working because of missing dependencies. Also, not that this has a not-insignificant cost for the size of the system (so, depends of the target we set in terms of lightweight-ness of YunoHost)

2. We should change the app CI to work with `APT::Install-Recommends "false";` (to be set *before* the install of yunohost itself). But you can expect a lot of app to break because of this ;P

**Comment by maniackcrudelis** [comment]
> We should change the app CI to work with APT::Install-Recommends "false"; (to be set before the install of yunohost itself). But you can expect a lot of app to break because of this ;P

Even though it would be possible to do that, it wouldn't highlight all missing packages. Because that's often when you really use the package that you notice that it's not working.

Isn't there an apt option when installing package to force installation of recommended packages ?

**Comment by alexAubin** [comment]
>Isn't there an apt option when installing package to force installation of recommended packages ?

Hmmm, maybe there's one, but if you're thinking about adding it to the app helper : that wouldn't cover that case I believe (the case where the missing packages were implicit on other yunohost instance, because of the yunohost package dependency). We could also add it to the install script I guess but I dunno, that does sound like an easy "general" solution

**Comment by maniackcrudelis** [comment]
Indeed that was my idea :D

Well, that depends on what really is the problem. If that's only a problem about missing dependencies for apps, yes in that case that should be handled somewhere in apps side.
But, in the first place, why yunohost deb has recommended packages, and what's going on if they're missing ? Should we worry about not having those ?

**Comment by alexAubin** [comment]
Weeell I dunno ... For instance for `php-gettext`, it seems to date back from the very early days of YunoHost : https://github.com/YunoHost/yunohost/blob/8668ffa2ff62ed3bc1ec9a40e1d0160aef863f94/debian/control#L38

So the reason why this is there as been lost in time I guess. But the thing is just that if you remove it, then you also remove its dependencies (such as `php-xml` and others) which happens to be used by many php apps ... all of this chain reaction being only there because of a random recommended package :/

**Comment by maniackcrudelis** [comment]
Do we have a lot of recommended packages that we don't know why we do have them ?

**Comment by alexAubin** [comment]
Weeell here they are : https://github.com/YunoHost/yunohost/blob/stretch-unstable/debian/control#L30-L36

- **yunohost-admin** : that's not mandatory, this allows people to uninstall it if they don't want it
- **openssh-server** : okay I guess ... not sure yunohost works without it but why not ... anyway that's probably installed on every server even in minimalist mode
- **ntp** : not so much needed but why not
- **inetutils-ping | iputils-ping** : that's probably `ping` ? Same as remark as openssh
- **bash-completion** : nice to have, but not mandatory
- **rsyslog** : dunno what this is
- **etckeeper** : why not, but not mandatory
- **php-gd, php-curl, php-gettext, php-mcrypt** : i have no idea why those are there
- **python-pip** : dunno why that's recommended either ... we do not use it explicitly anywhere i believe
- **unattended-upgrades** : nice to have, but not mandatory
- **libdbd-ldap-perl, libnet-dns-perl** : I think that's related to weird locale stuff, not sure

So to me, essentially those php deps + python-pip are weird to have as recommended

**Comment by maniackcrudelis** [comment]
Does that mean that this user didn't have `yunohost-admin` !!!?
Well for me, to decide whether or not those packages should be installed is not up to the VPS your using but to the admin himself.
 I don't think we should let such config prevent of installing those packages. But still I understand that having those as 'recommended' allow to remove them if wanted, without removing YunoHost.

**Comment by alexAubin** [comment]
>Does that mean that this user didn't have yunohost-admin !!!?

I thought about that too, but turns out that the install script explicitly install yunohost-admin too, so he did have it ;)

**Comment by alexAubin** [comment]
So, https://github.com/YunoHost/install_script/commit/f4839a7e712a6b67cd398f6da2494987040cfa69 should fix it for newer install ... Gonna say fuck it for existing instances because I'm kinda lazy to implement a migration for the minor case of instances installed without the recommended php packages

Note that a quick and easy fix for the remaining existing problematic setup should be to run 

```
apt install php-gd php-curl php-gettext php-mcrypt
```
