### ISSUE TITLE
[Rouncube 1.3.6~ynh1] tinymce_4.5.8.zip archive corrupted

### ISSUE THREAD

**Issue by indelog** [YunoHost/issues#1321]
After fresh installation of Roundcube app, i don't able to send email, when i show js console in my web browser, i see `TypeError: this.editor is undefined`.

After verification of my roundcube files, i see tinymce is missing in `/var/www/roundcube/program/js` and `/var/www/roundcube/temp/js_cache/tinymce-4.5.8.zip` is present.

I've try to extract it but : 
```
# unzip -l ./temp/js_cache/tinymce-4.5.8.zip                                      
Archive:  ./temp/js_cache/tinymce-4.5.8.zip                                      
  End-of-central-directory signature not found.  Either this file is not         
  a zipfile, or it constitutes one disk of a multi-part archive.  In the         
  latter case the central directory and zipfile comment will be found on         
  the last disk(s) of this archive.                                              
  unzip:  cannot find zipfile directory in one of ./temp/js_cache/tinymce-4.5.8.zip or
}>        ./temp/js_cache/tinymce-4.5.8.zip.zip, and cannot find ./temp/js_cache/tinymce-4.5.8.zip.ZIP, period.
```

I solved this problem by installing tinymce manualy in /var/www/roundcube/program/js from this URL : <http://download.tiny.cloud/tinymce/community/tinymce_4.5.8.zip>.

**Comment by Psycojoker** [comment]
Hello,

Thx for taking the time to report this issue :) 

There is already an open ticket on this app repository (issue for apps should be on their repository) there https://github.com/YunoHost-Apps/roundcube_ynh/issues/58 so I'm closing this one as duplicated.

Have a nice day,
