### ISSUE TITLE
Demoinstance torrent problem

### ISSUE THREAD

**Issue by bugfindcert** [YunoHost/issues#1325]
Hi guys.
Your demo installation is open for everyone. Bad people could download warez and share them ... 

Look, a lovely debian image ;)
https://demo.yunohost.org/torrent/downloads/debian-9.8.0-amd64-netinst.iso

I don't know the filesystem permissions your instance has, but i can download a torrent file to /etc ... I think that is a big security issue.

**Comment by maniackcrudelis** [comment]
Our demo has a lifespan of 30 minutes only.
Your link isn't available anymore.

We probably could enforce the security of transmission to not allow people to download anything. I Don't know though if it worth it, considering the short lifespan of anything downloaded with it.
Also, it would be a patch applied after each upgrade of transmission package, which is automatic.

Don't understand how you can download a file to /etc. Is it with transmission ?

However, whatever you would do with the demo server, even compromising it, won't last more than 30 minutes.
