### ISSUE TITLE
Italian translation for reboot screen incorrect

### ISSUE THREAD

**Issue by noccio** [YunoHost/issues#1327]
In the reboot screen for the italian translation the phrase 

> Puoi controllare questo aggiornado questa pagina (F5).

is not really correct.

I think something like

> Puoi controllare lo stato del riavvio aggiornando questa pagina (F5)

would be better

**Comment by ghost** [comment]
Cc @sylkevicious

**Comment by silkevicious** [comment]
I'm going to check the translation of that string. Thanks for the report! If you see something else wrong, i'm happy to fix it! ;-)

**Comment by silkevicious** [comment]
The string is now translated correctly like you suggested, i fixed it in weblate. I'm sure it will be availabe in the next updates. 

@admins you can close this issue ;-)

**Comment by ghost** [comment]
Thank you @silkevicious

**Comment by Psycojoker** [comment]
Thx for all your contributions :) 

I'm closing this issue.
