### ISSUE TITLE
E-Mail forward address impossible with "+" character

### ISSUE THREAD

**Issue by cl-parsons** [YunoHost/issues#1333]
I got an error when changing the mail forward value in the user interface, if I put a "+" in the address. In my case the forwarding address is located on another server that allows receiving nickname+whatever@serv.er e-mails. 

This error is then not relevant.

`Invalid argument 'add_mailforward': Must be a valid email address (e.g. someone@domain.org)`

I just installed the last version of yunohost, manually with the curl|bash command, on the last debian iso, in a VM of my own server.

**Comment by Psycojoker** [comment]
That's probably related to the email regex that we uses (it's not
really the best available)

https://github.com/YunoHost/yunohost/blob/3b5b7a9ae6edfb3c9142f825de9fa2989bb71ebe/data/actionsmap/yunohost.yml#L117
