### ISSUE TITLE
yunohost-stretch-3.4.2: phpMyAdmin & custom WebApp & hotSpot  OK

### ISSUE THREAD

**Issue by gitLHNduthel** [YunoHost/issues#1334]

**Comment by gitLHNduthel** [comment]
En installant les applications dans cet ordre et en redémarrant le serveur Yunohost après chaque étape, les 3 applications fonctionnent enfin ensemble (sans bug à l'installation) :
1)  via URL yunohost=> application :  hotspot  
2)   via SSH => sudo apt-get install php7.0-cli php7.0-common php7.0-intl php7.0-json php7.0-mcrypt php-pear php-auth-sasl php-mail-mime php-patchwork-utf8 php-net-smtp php-net-socket php-net-ldap2 php-net-ldap3 php-zip
3)   via SSH => sudo apt-get install php7.0-gd php7.0-mbstring
sudo apt-get install php-curl
3)   via URL yunohost => application phpMyAdmin 
4)   via URL yunohost=> application wustomWebapp

**Comment by Psycojoker** [comment]
@YunoHost/apps I guess this is an issue for you? ^

**Comment by gitLHN** [comment]
yes by following these 5 steps the installation got  positive issue

**Comment by maniackcrudelis** [comment]
Should we suppose it wasn't in a different order ?
If so, issues in corresponding repo would be great.

To know it works it always a good news, but we're not going to do anything then.

**Comment by alexAubin** [comment]
(I too am confused by this issue ... I don't understand what doesn't work or what is expected ?)

**Comment by gitLHNduthel** [comment]
I do not understand all those messages, ?
@alexAubin : je tente en français
Je voulais par mon message d'origine simplement signaler que j'avais eu du mal à installer les 3 applications sans obtenir d'erreur - J'indiquais une solution pour que l'installation se déroule sans bug .
N'hésitez pas à supprimer ces posts si vous pensez qu'ils n'ont pas d'intérêt

**Comment by alexAubin** [comment]
Uuuuh mais du coup ce qui serait intéressant d'avoir comme info, c'est pourquoi tu avais eu des erreurs "avant", et les messages / logs associées ...

**Comment by alexAubin** [comment]
Closing because can't understand what's the actual issue is / lack of feedback ...
