### ISSUE TITLE
Portal button doesn't work for subdomain (v3.5.2)

### ISSUE THREAD

**Issue by gnouts** [YunoHost/issues#1335]
Hello,

I recently upgraded to Yunohost 3.5.2 and took advantage of the customizable overlay portal button. I only changed the logo like [in the example](https://yunohost.org/#/theming_en) and nothing else. (custom images display fine and it's really cool btw).

But now, on any of my subdomains, the button trigger this address : 
https://sub.domain.tld/yunohost/sso/portal.html
which returns a 404.

The correct address should be without the subdomain :
https://domain.tld/yunohost/sso/portal.html

**Comment by alexAubin** [comment]
Yes indeed ... there are a few tricky things related to the SSO in multidomain context, it's not straightforward to fix those but eventually we'll do something :s 

Thanks for the feedback !

**Comment by opi** [comment]
Here's a dirty way to fix this issue : 

1. Edit `/usr/share/ssowat/portal/assets/js/ynh_portal.js` and replace the 2 occurences of `/yunohost/sso/` with `https://domain.tld/yunohost/sso/` : 

```
portalOverlay.src = "https://domain.tld/yunohost/sso/portal.html";
```
and
```
portalButton.setAttribute('href', 'https://domain.tld/yunohost/sso/');
```

2. Allow domain.tld to be served in iframe, edit `/etc/nginx/conf.d/domain.tld.conf` and change the following line : 
```
more_set_headers "X-Frame-Options : SAMEORIGIN
```
by
```
more_set_headers "X-Frame-Options : ALLOWALL";";
```

3. Don't forget to reload the Nginx web server : `systemctl reload nginx.service`.

*domain.tld should be replaced with your main domain*

**Comment by opi** [comment]
Note that the proper fix should be to serve `anydomain.tld/yunohost/sso/` as `domain.tld/yunohost/sso/`. There is probably a nginx config trick.

**Comment by Josue-T** [comment]
Looking interesting

Thinking about that:
```
more_set_headers "X-Frame-Options : ALLOWALL";";
```
But does it don't it bring a security issue ?

**Comment by gnouts** [comment]
Maybe a specific redirect is less risky than allowing all domain in header ?
Something like :  
```
rewrite ^(/yunohost/sso/)(.*)$ http://domain.tld/yunohost/sso/$2 permanent;
```
(I don't know if it's possible to write this once or if we have to write it in every subdomain conf file)

Also a server block is usually considered safer but I don't know how/where to write it.

**Comment by opi** [comment]
> But does it don't it bring a security issue ?

It does ; It means that the content of your main domain website (and/or login page) can be included within an iframe on another website. I was aware of that and assume the (little) risk, but thanks for bringing it

**Comment by alexAubin** [comment]
I too am afraid about this X-Frame-Options : ALLOWALL which sounds pretty scary ...

Last time I was working on trying to find a proper solution for this issue, I just came to the conclusion that some architectural stuff in SSOwat must be reworked ...

c.f. also this discussion https://forum.yunohost.org/t/call-for-feedback-sso-portal-in-multi-domain-context-how-should-it-work/7491 (though that does not cover 100% of the issues)

**Comment by alexAubin** [comment]
Ah I didnt see the message from opi :  

>Note that the proper fix should be to serve anydomain.tld/yunohost/sso/ as domain.tld/yunohost/sso/. There is probably a nginx config trick.

But the tricky part is to handle/check the authentication also ? Currently it only works on the portal domain using a cookie ... You could imagine that all domains would be a portal domain ... but then with the current code, you would need to authenticate on each domain separately.

My opinion about this is that : if you are authenticated on foo.tld, you should not have to reauth on sub.foo.tld (technically I think that should be doable because cookie from a parent domain can be accessed from the subdomain?). But you would need to reauth on bar.tld, even though that's just a domain of the same instance. (c.f. the topic in previous message)

Dunno if that makes sense.

**Comment by Josue-T** [comment]
The other question that I don't understand is why does is work a little bit (not completly) with the version <3.5. So why we have a regestion about that in the version 3.5 ?

**Comment by alexAubin** [comment]
Because during the work on theming, we refactorized several parts (which were previously a complete mess) and introduced this thing where the small portal button relates to an iframe. But we didn't anticipate the issue about iframes in a multidomain context...

**Comment by Josue-T** [comment]
So it's because of the iframes as I understand.

**Comment by Josue-T** [comment]
I did some test and as I understand there are probably something which is is broken in SSOwat probably since the version 3.5 or maybe before, but I didn't found what exactly is broken. I need to investigate more. But from what I see it's not the Iframe which break this. It's probably  something else.

**Comment by Josue-T** [comment]
Found maybe a solution here : https://github.com/YunoHost/SSOwat/pull/136

**Comment by Psycojoker** [comment]
The PR is merged, can we closed this issue now then?

**Comment by alexAubin** [comment]
Well uh my understanding is that it's only a partial fix (c.f. https://github.com/YunoHost/SSOwat/pull/136#issuecomment-493696771 ) but maybe I'm mistaking, that this is subtle as hell

**Comment by alexAubin** [comment]
Closing, SSO/portal completely reworked for Bookworm
