### ISSUE TITLE
the need to do a "--dyndns" in CLI on "yunohost add domain" is bad UX

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1338]
I don't know what should be the best alternative?

Right now I'm for:

- detect if it's a domain we offer in dyndns
- if yes, print a warning saying it's detected, say that we can do "--ignore-dyndns" if we don't want this behavior
- treat it like a dyndns

That should be way more intuitive than the current behavior that even doesn't tell you it won't thread it as a dyndns.

**Comment by alexAubin** [comment]
(In fact that would also simplify the postinstall code because in the postinstall we precisely handle it automatically but for some reason not in domain_add ...)

**Comment by alexAubin** [comment]
Fixed in https://github.com/YunoHost/yunohost/pull/1475
