### ISSUE TITLE
Problème for phpmyadmin app installation

### ISSUE THREAD

**Issue by prism-ux** [YunoHost/issues#1344]
Bonjour à vous, 
Quand je veux installer l'application PHP MySQL admin je reçois un rapport d'erreur. Je colle les log plus bas.
Hello.
I have an error message when i want to install the PHP Myadmin app. I paste the log :

https://paste.yunohost.org/raw/hutexoziru

**Comment by maniackcrudelis** [comment]
Fixed by https://github.com/YunoHost-Apps/phpmyadmin_ynh/pull/86
