### ISSUE TITLE
Support DNS-based challenge for Lets Encrypt ?

### ISSUE THREAD

**Issue by marius** [YunoHost/issues#1346]
Hi,

when trying to get a let's encrypt certificate via the CLI on my
IPv6-only, HTTPS-only yunohost I get:

root@yuno:~# yunohost domain cert-install funk.[REDACTED].org --no-checks
Info: Now attempting install of certificate for domain funk.[REDACTED].org!
Success! The SSOwat configuration has been generated
Success! The configuration has been updated for service 'dnsmasq'
Info: Parsing account key...
Info: Parsing CSR...
Info: Registering account...
Info: Already registered!
Info: Verifying funk.[REDACTED].org...
Error: funk.[REDACTED].org challenge did not pass: {u'status': u'invalid', u'validationRecord': [{u'url': u'http://funk.[REDACTED].org/.well-known/acme-challenge/h4c4w02-z69gfI3ZpPEg3KpAXQpck_V6L3G98q8nM', u'hostname': u'funk.REDACTED.org', u'addressUsed': u'REDACTED', u'port': u'80', u'addressesResolved': [u'REDACTED']}], u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/goDo9jGljsd8Bsw6UrzxxPBsEiU1sVNBBXIYPqnw/15290566682', u'token': u'h4c4w02-fI3ZpPEg3KpAXQpck_V6LNZ3G98q8nM', u'error': {u'status': 400, u'type': u'urn:acme:error:connection', u'detail': u'Fetching http://funk.REDACTED.org/.well-known/acme-challenge/h4c4w02-z69gfI3ZpPEXQpck_V6L3G98q8nM: Timeout during connect (likely firewall problem)'}, u'type': u'http-01'}
Error: No DNS 'A' record found for funk.REDACTED.org. You need to make your domain name point to your machine to be able to install a Let's Encrypt certificate! (If you know what you are doing, use --no-checks to disable those checks.)
Info: The operation 'Install Let's encrypt certificate on 'funk.REDACTED.org' domain' has failed! To get help, please share the full log of this operation using the command 'yunohost log display 20190429-601-letsencrypt_cert_install-funk.REDACTED.org --share'

When I temporarily open port 80 in my firewall it works fine.

**Comment by zamentur** [comment]
IPv6 only is not a current feature of yunohost. Things could break, like here.

Thanks for the report, feel free to make other bug report about ipv6 only support :)

**Comment by alexAubin** [comment]
Uh wait, there's confusion in there, it's not about IPv6 but about HTTP vs HTTPS ?

The ACME challenge only works with HTTP from what I know ... so there's no way to make it work through HTTP (except if LetsEncrypt builds and provide another challenge, HTTPS-based)

**Comment by decentral1se** [comment]
> The ACME challenge only works with HTTP from what I know

Yep, same here. There is some discussion over this:

> https://letsencrypt.org/docs/allow-port-80/

From what I understand, DNS validation is an option if you have your own domain and it seems that some DynDNS providers give this too (see https://community.letsencrypt.org/t/renew-certificate-using-https-port-443-or-alternative-port-eg-8000/66981/17).

For more, see "DNS-01 challenge" in:

> https://letsencrypt.org/docs/challenge-types/

As far as I can tell, this won't be added to `acme-tiny` due to various issues, please see https://github.com/diafygi/acme-tiny/issues/161#issuecomment-373957662.

**Comment by Psycojoker** [comment]
> From what I understand, DNS validation is an option if you have your own domain and it seems that some DynDNS providers give this too (see https://community.letsencrypt.org/t/renew-certificate-using-https-port-443-or-alternative-port-eg-8000/66981/17).

I haven't dig into the details but that mean that we can do that for our own dyndns service (while I'm not sure it hads a real benefit) but we won't be able for other domains until we added registars api support inside YunoHost (it's there somewhere in another issue '-')

**Comment by alexAubin** [comment]
Closing because wontfix / DNS challenge to be discussed in https://github.com/YunoHost/issues/issues/1292
