### ISSUE TITLE
Searching applications on yunohost website

### ISSUE THREAD

**Issue by ChristopheVuillot** [YunoHost/issues#1347]
When searching an application on https://yunohost.org/#/apps, the search string is only matched against the very beginning of application names.

For example searching 'box' will not find the application 'shell in a box'.

**Comment by decentral1se** [comment]
Hi @ChristopheVuillot, I've taken a look at this. 

From what I see, this is not an issue on Yunohost `3.5.2.2`:

![shellinabox](https://user-images.githubusercontent.com/1991377/58352988-8afecc00-7e6d-11e9-8216-ebef1c95162d.png)

**Comment by ChristopheVuillot** [comment]
Hi @decentral1se, thanks for having a look.
You are right the problem doesn't appear in the admin panel of a yunohost instance which is good.
Where it appears is on the yunohost website: https://yunohost.org/#/apps.

**Comment by decentral1se** [comment]
Right, apologies, you did already mention that :point_up: 

If I'm not mistaken, I think the issue is somewhere lurking in the JS blob in:

> https://github.com/YunoHost/doc/blob/master/apps.md

**Comment by decentral1se** [comment]
OK, here comes a fix then https://github.com/YunoHost/doc/pull/996 :bomb:
