### ISSUE TITLE
Interface to easily configure SMTP relay

### ISSUE THREAD

**Issue by Dr-Wily** [YunoHost/issues#1348]
Hello,

I notice there is no option to setup an authentication for SMTP relay. Most of major SMTP servers refuse to accept direct mail from a newly created SMTP server (like Yunohost).

One of the solutions is to relay through ISP's SMTP. To make this relaying works we need to setup an authentication with ISP account. This actually works in Yunohost but only through SSH and editing manualy main.cf postfix configuration file.

Why not add a web UI for SMTP configuration in admin part of Yunohost (like domain configuration for example) ?

**Comment by alexAubin** [comment]
Indeed that could be a nice feature to have, never really thought about that. Need someone to take the energy and time to implement this though :s

**Comment by ImaCrea** [comment]
Sounds cool and useful but what about security? Isn't it a bit against the idea of self-hosting as sending email become then dependant of an external service?

**Comment by decentral1se** [comment]
Nice idea!

> Isn't it a bit against the idea of self-hosting as sending email become then dependant of an external service?

To some degree yes. OTOH, for the purposes of a "soft entry" into self-hosting, it can be very useful for a less overwhelming start. And sometimes you know a friendly SMTP relay from a nice hosting collective or something that can let you send mails through. Later, you get your own DNS and start to configure everything as understanding increases.

I could potentially have time to take this on if someone could lay out a plan of what needs to be done.

Also see:
* https://forum.yunohost.org/t/external-smtp-relay-server-for-the-domain/5731

**Comment by zamentur** [comment]
I have code a small solution to avoid admin to reapply update of postfix main.cf update 
See : https://github.com/YunoHost/yunohost/pull/773

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost/pull/773
