### ISSUE TITLE
LDAP cn=config backend cannot be edited

### ISSUE THREAD

**Issue by MCMic** [YunoHost/issues#1350]
Hello,

I asked about it on the yunohost forums but never got an answer: https://forum.yunohost.org/t/ldap-setup-and-access-to-cn-config/5691/2

It seems that yunohost is using a slapd.conf which is then converted to cn=config format, which removes the default Debian ACL allowing to edit cn=config with root account.

This makes editing LDAP configuration pretty hard, for instance adding indexes to solve all the warnings in the log about missing indexes.

**Comment by alexAubin** [comment]
Not sure I understand that thing about cn=config, but uh yeah I was wondering about fixing the missing index warning the other day ... Can't we just improve the slapd.conf ?

**Comment by MCMic** [comment]
@alexAubin slapd.conf is not used anymore by slapd, it’s the legacy way.

Configuration is now stored in cn=config LDAP tree, which you can access through LDAP protocol, allowing to edit configuration without restarting slapd.
https://www.openldap.org/doc/admin24/slapdconf2.html
«An existing slapd.conf(5) file can be converted to the new format using slaptest(8) or any of the slap tools:
        slaptest -f /usr/local/etc/openldap/slapd.conf -F /usr/local/etc/openldap/slapd.d»
If I remember correctly from last time I looked into it yunohost uses this to fill the configuration, but this is supposed to be used for migration to the new system, not for configuration.

Regarding indexes: http://www.zytrax.com/books/ldap/apa/indeces.html
«In OLC (cn=config) the attribute used is olcDbIndex which can only appear in an olcDatabase={0}config entry. Additionally re-indexing is done in real time so any change to an attribute immediately triggers and indexing change (slapindex is not required).»

**Comment by alexAubin** [comment]
Hmokay, it's still sketchy in my mind, I really have troubles understanding the whole LDAP thing (and databases in general anyway lol)

But could it be that https://github.com/YunoHost/yunohost/pull/721 would fix this issue ? In particular the changes in slapd.conf which (re?)add the mysterious uidNumber=0 incantation) : https://github.com/YunoHost/yunohost/pull/721/files#diff-151221293d0eb23387831125ded6416c

**Comment by MCMic** [comment]
From what I see in the diff it still uses slapd.conf and only changes ACLs on the main tree. This does not fix the problem about not having access to cn=config tree.
But I’m not sure about that.

The LDAP server stores two trees, one is rooted as dc=yunohost,dc=org, the other one is rooted as cn=config and stores the configuration and schemas.

Could you try to dump /etc/ldap/slapd.d/cn=config/olcDatabase={0}config.ldif from a freshly installed yunohost to see if it’s different from mine?

**Comment by Josue-T** [comment]
> Could you try to dump /etc/ldap/slapd.d/cn=config/olcDatabase={0}config.ldif from a freshly installed yunohost to see if it’s different from mine?

As I remember it still this.

> From what I see in the diff it still uses slapd.conf and only changes ACLs on the main tree. This does not fix the problem about not having access to cn=config tree.
But I’m not sure about that.

Yes it's that.

Actually there are no plan to change this configuration. And I don't know if it's really a good idea to change this because, yes could give the possibility to the user to customize the LDAP config, but on the yunohost side using the actual technique is probably easier when we need to update the LDAP config by example in theses PR [721](https://github.com/YunoHost/yunohost/pull/721) and [585](https://github.com/YunoHost/yunohost/pull/585).

Anyway if we really want to migrate to this concept the main work is probably on [this script](https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/hooks/conf_regen/06-slapd).

**Comment by MCMic** [comment]
But how do you update the configuration on yunohost update? From what I understand once setup slapd uses cn=config and ignores the slapd.conf, so any changes in there would not be effective.

**Comment by Josue-T** [comment]
Well, you can see in the [regen-conf script](https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/hooks/conf_regen/06-slapd) that each time that run the regen-conf the config is rebuild from scratch from the slapd.conf file.

**Comment by MCMic** [comment]
Then would it be possible to add some indexes to the slapd.conf used, to avoid seeing the warning in the logs?
```
 <= mdb_equality_candidates: (cn) not indexed
 <= mdb_equality_candidates: (gidNumber) not indexed
 <= mdb_equality_candidates: (mail) not indexed
 <= mdb_equality_candidates: (member) not indexed
 <= mdb_equality_candidates: (memberUid) not indexed
 <= mdb_equality_candidates: (sudoUser) not indexed
 <= mdb_equality_candidates: (uidNumber) not indexed
 <= mdb_equality_candidates: (uniqueMember) not indexed
 <= mdb_equality_candidates: (virtualdomain) not indexed
 <= mdb_substring_candidates: (sudoUser) not indexed
```

So something like:
```
 # Indexing options for database #1
 index  objectClass         eq
-index  uid                 eq,sub
+index  uid,sudoUser     eq,sub
 index  entryCSN,entryUUID  eq
+index cn,mail eq
+index  gidNumber,uidNumber eq
+index member,memberUid,uniqueMember eq
+index virtualdomain eq
```

**Comment by Josue-T** [comment]
Good idea,

You can create a PR [here](https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/templates/slapd/slapd.conf#L66-L68) for that.

**Comment by MCMic** [comment]
Done.

**Comment by Josue-T** [comment]
> Done.

Thanks

**Comment by alexAubin** [comment]
Closing the issue because apparently the real motivation was really about removing the index warning thingies...

**Comment by Josue-T** [comment]
Hello,

Now, we have a problem with buster because the `slaptest` command is probably broken. So for me it's maybe the time to refactor this part.

I could do this work, as long as we have defined how will work this part.

**Comment by Josue-T** [comment]
Maybe we can look on this side to refactor the regen-conf for slapd.

https://serverfault.com/questions/863274/modify-openldap-cn-config-without-slapd-running

**Comment by MCMic** [comment]
The whole point of cn=config is to edit the configuration with ldap operations, this defeats the purpose.

**Comment by Josue-T** [comment]
> The whole point of cn=config is to edit the configuration with ldap operations, this defeats the purpose.

For this it's easy we can just allow the user `gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth` to write in the `config` database. It should be only one entry to add in the config database.

**Comment by MCMic** [comment]
While working on a tool to edit cn=config configuration I noticed openldap refuses most deletion in cn=config, even on attributes, making it hard to fix a broken configuration (as far as I know you cannot remove an index, or a module, or a schema, or a attributeoption definition).

**Comment by alexAubin** [comment]
Closing because supposedly https://github.com/YunoHost/yunohost/pull/984 fixed the issue (the PR was actually cherry-picked)
