### ISSUE TITLE
Broken nginx redirect after an update of the couchpotato app

### ISSUE THREAD

**Issue by MCMic** [YunoHost/issues#1351]
Hello,

I clicked the update link in the couch potato app and it broke it.

I tried to restore the configuration to a working state but I am failing so far.

I can access couchpotato from local network by going to its own port, but going to /couchpotato only gives me the SSO menu. Clicking couchpotato link on it does nothing.

The nginx config file for couchpotato does not seem different from what I can find for other apps, so I do not understand why this redirect fails:

```
# cat /etc/nginx/conf.d/<domain>.d/couchpotato.conf 
location /couchpotato {
    proxy_http_version 1.1;
    proxy_pass_header Server;
    proxy_pass http://127.0.0.1:5050;
    proxy_redirect off;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    # Include SSOWAT user panel.
    include conf.d/yunohost_panel.conf.inc;
    more_clear_input_headers 'Accept-Encoding';
}
```

Doing “wget -O - http://127.0.0.1:5050” on the server shows that couchpotato is indeed running correctly at that address. Why does /couchpotato not show this?

￼￼
￼

**Comment by frju365** [comment]
Did you use it for CouchPotato App ? Does it work at root `location / { ... }` ?

**Comment by MCMic** [comment]
I do not understand the first question.

No, changing /couchpotato for / does not seem to change anything. But I guess there is already a config for / elsewhere since this is the main menu.

**Comment by Psycojoker** [comment]
This might be a configuration problem in `/etc/sso/conf.json` (which is generated by yunohost based on app information).

Sadly couchpotato app isn't maintained anymore :/

**Comment by MCMic** [comment]
Ok in the end I just removed and installed again the application, this worked.
I do not see the difference in the nginx conf so I do not know what was happenning.
