### ISSUE TITLE
[ynh-dev] Docs: point to /dev/ not /dev_fr/ on description

### ISSUE THREAD

**Issue by decentral1se** [YunoHost/issues#1352]
Tiny one - on https://github.com/YunoHost/ynh-dev. The repository description says:

> Dev environement wrapper, based on Vagrant and LXC, to develop on YunoHost https://yunohost.org/dev_fr

However, given that there are multiple languages supported, should it be:

> Dev environement wrapper, based on Vagrant and LXC, to develop on YunoHost **https://yunohost.org/dev**

EDIT: I can also send a small patch for https://github.com/YunoHost/ynh-dev#more-info.

:see_no_evil:

**Comment by frju365** [comment]
Thanks. Yes, you can. It's indeed not a good thing to force user to use french translation, I think the explanation is that there wasn't English version (surely written at the beginning in french and then in English)

**Comment by decentral1se** [comment]
OK cool, I've opened up a tiny one on https://github.com/YunoHost/ynh-dev/pull/49.

**Comment by frju365** [comment]
Ok. Thanks. I merged it.
