### ISSUE TITLE
Do not insert YNH portal button within app iframe

### ISSUE THREAD

**Issue by opi** [YunoHost/issues#1354]
Sometimes app use iframe for their own need, for example roundcube for the visualisation panel, or nextcloud. This leads to duplicate YNH button, see screenshot

![Capture d'écran de 2019-05-23 10-59-44](https://user-images.githubusercontent.com/159548/58240010-547c6080-7d4a-11e9-9bf0-f878150bb17b.png)

I'll create a PR with a proposal fix

**Comment by decentral1se** [comment]
> I'll create a PR with a proposal fix

:clap:

**Comment by opi** [comment]
There you go https://github.com/YunoHost/SSOwat/pull/137

**Comment by alexAubin** [comment]
PR got merged
