### ISSUE TITLE
sort domains alphabetically on domain list page of the admin

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1355]
If you have a lot of domains it's quite a mess.

One interesting addition would be to regroup domain by "top" domains (if you uses a lot of subdomains).

**Comment by Aeris1One** [comment]
Best ordering would be to have them sorted in alphabetical order but first domain in list would be the default one (the one with a 🌟)

Ex:
1.    defaultdomain.com (🌟)
2.    alphabeticalfirst.com
3.    endofalphabet.org

**Comment by alexAubin** [comment]
Closing / done in 11.1, went for a tree structure instead
