### ISSUE TITLE
Add a Docker image as app

### ISSUE THREAD

**Issue by HyperCriSiS** [YunoHost/issues#1358]
Hi,

would awesome to see this as builtin feature.
Is there any possibility to install this Docker image on Yunohost?
https://github.com/tomav/docker-mailserver

Thanks,
Hyper

**Comment by decentral1se** [comment]
Hi @HyperCriSiS, Yunohost already has an email stack integrated that you can read about over at https://yunohost.org/#/email. Is there something you are missing from that stack that you found in this docker setup?

**Comment by Psycojoker** [comment]
For now we aren't planning to do any containerization integration, it might happen in a (distant) future but I wouldn't count on it :/

Focus is really more on UX and adding new user oriented features to ease the maintainability of the server and empower app developers.
