### ISSUE TITLE
can we stop ci-stretch.nohost.me?

### ISSUE THREAD

**Issue by Jibec** [YunoHost/issues#1359]
Hello, what is https://ci-stretch.nohost.me/ci/ ? Do we really need it? Isn't our CI this one: https://ci-apps.yunohost.org/ci/ ?
It continuously sends email to apps maintainer with bad links:

> Application kresus rise from level 0 to level 7 on https://ci-stretch.nohost.me/ci/job/kresus%20(Apps)/lastBuild/console

thanks for your help

**Comment by alexAubin** [comment]
(I too am confused by this)

**Comment by maniackcrudelis** [comment]
As we still have users on jessie, this CI is still in use to know which apps are still working on jessie. Not that much by the way.
As soon as the work will start on Buster, this CI will move to buster.

**Comment by Jibec** [comment]
OK, would it be possible:
* to have the correct link to CI,
* only send email if manifest's requirement aim to support Jessie (ynh<3.0)?

**Comment by maniackcrudelis** [comment]
Everything's possible...

**Comment by zamentur** [comment]
The work has started on buster. But i don't think we can adapt the ci for it now.
We might stop to run test for jessie, today all tested apps are in red and send bad email to maintainers... I have no access to the machine to stop the worker, could it be possible to do it.

**Comment by alexAubin** [comment]
Today, we have another story from @JocelynDelalande who got very confused about emails from this CI and stopped caring about all CI mail (including the real one) because of it ... :/

**Comment by alexAubin** [comment]
Yet again today the packager of tvheadend_ynh got confused by this ...

**Comment by sy6sy2** [comment]
Maybe is it possible to add something on this Jessie CI that check the minimal YNH version in the manifest? Then if the version is above 2.7 (not sure about the number) the CI silently failed without sending an email to package dev?

Edit: Hum, this idea has already been said above :-/

**Comment by alexAubin** [comment]
I think it's done now ...
