### ISSUE TITLE
Phone menu on tartiflette doesn't displayed

### ISSUE THREAD

**Issue by kay0u** [YunoHost/issues#1361]
The menu of https://dash.yunohost.org/ doesn't displayed on phone. So I can't stalk every projects when I don't have a computer with me.

**Comment by Psycojoker** [comment]
That's weird, I've tested it with firefox responsive tool and I got the "hamburger" menu button that allows to show the menu :confused: 

![2019-07-12-013758_308x484_scrot](https://user-images.githubusercontent.com/41827/61092216-b3568000-a445-11e9-83e3-6d22a47ec192.png)
![2019-07-12-013721_334x471_scrot](https://user-images.githubusercontent.com/41827/61092218-b487ad00-a445-11e9-9357-17d44fcf968a.png)

**Comment by kay0u** [comment]
Huh, I fixed it:

https://github.com/YunoHost/tartiflette/pull/6

**Comment by Psycojoker** [comment]
Oh ok x)
