### ISSUE TITLE
Can't download or update anything on raspi

### ISSUE THREAD

**Issue by zyphlar** [YunoHost/issues#1362]
For a bit I was able to try and install Firefly III, but it failed for some reason (like local config files / install scripts not completing properly). Now I can't download or install anything. I rebooted and that just seems to have generated more miscellaneous errors. I had trouble doing postinstall last night even after verifying the sha and signature of my download and formatting/imaging my SD card a few times. This raspi works pretty well with other images so I'm unsure what the issue is.

Installing anything:
```
unable to download https://github.com/YunoHost-Apps/firefly-iii_ynh/archive/e1caea57cec6efc40be33a9f561ae03acaae2671.zip
```

Even looking at the system update page:
```
Yunohost encountered an internal error:/
Action

PUT /update
{"locale":"en"}

Traceback

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 439, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 523, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/tools.py", line 476, in tools_update
    if not cache.update():
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 466, in update
    raise FetchFailedException()
FetchFailedException
```

**Comment by alexAubin** [comment]
Well, what happens if you try to `wget wikipedia.org` for example ?

**Comment by zyphlar** [comment]
Whelp, I couldn't SSH in (connection reset by peer) and when I tried to connect a monitor and keyboard again it rebooted and kernel panicked (something tried to kill init 9 seconds in) so I guess something went seriously wrong with the OS/storage. Never had this kind of issue with a Raspi before, guess we'll never know.
