### ISSUE TITLE
Operation logs should redact sensitive infos like password

### ISSUE THREAD

**Issue by decentral1se** [YunoHost/issues#1363]
I clicked "share with yunopaste" after an install of writefreely app failed on a yunohost 3.5. The full log is here (already reset passwords / user details):

> https://paste.yunohost.org/raw/penucemovi

Where "YNH_APP_ARG_PASSWORD" and mysql's "--password", argument show the passwords in clear text.

Original report is over at https://github.com/YunoHost-Apps/writefreely_ynh/issues/54.

**Comment by maniackcrudelis** [comment]
Still a work in progress, I managed to hide passwords during the execution of the script for stdin, stdout, and xtrace.
Can't continue for now, because I need to sleep before working tomorrow morning ;)

Here the code I used
```bash
hide_password () {

    rm -f {stdin,stdout,xtrace}_file_capture
    touch {stdin,stdout,xtrace}_file_capture
    # Duplicate file descriptor stdin into fd 3
    # Then redirect stdin to a file.
    exec 3>&1; exec 1>stdin_file_capture
    # Do the same for stdout
    exec 4>&2; exec 2>stdout_file_capture
    # And xtrace
    exec 8>&7; exec {BASH_XTRACEFD}>xtrace_file_capture

    rm -f {stdin,stdout,xtrace}_fifo_capture
    # Create fifo for all 3 previous files.
    mkfifo {stdin,stdout,xtrace}_fifo_capture

    # Start 3 tail in background to follow the outputs.
    # This part could probably be made easier.
    tail -F stdin_file_capture >stdin_fifo_capture &
    kill_read_capture_stdin=$!
    tail -F stdout_file_capture >stdout_fifo_capture &
    kill_read_capture_stdout=$!
    tail -F xtrace_file_capture >xtrace_fifo_capture &
    kill_read_capture_xtrace=$!

    # Read outputs from their fifo
    while read -r stdin_capture
    do
        # Replace 'password' by asterisk and redirect the result into the duplicated file descriptor
        # If the result is redirected into the same file descriptor, it would loop.
        echo ">>>>>>$stdin_capture" | sed 's/password/********/g' >&3
    done <stdin_fifo_capture &
    kill_stdin_capture=$!

    while read -r stdout_capture
    do
        echo ">>>>>>$stdout_capture" | sed 's/password/********/g' >&4
    done <stdout_fifo_capture &
    kill_stdout_capture=$!

    while read -r xtrace_capture
    do
        ynh_print_OFF; echo ">>>>>>$xtrace_capture"; ynh_print_ON | sed 's/password/********/g' >&8
    done <xtrace_fifo_capture &
    kill_xtrace_capture=$!

    ynh_clean_setup () {
ynh_debug -m "Without ynh_debug, nothing is shown... Don't know why for now..."

        # Kill the 3 tail and the 3 while loops.
        kill -s 15 $kill_read_capture_stdin
        kill -s 15 $kill_stdin_capture

        kill -s 15 $kill_read_capture_stdout
        kill -s 15 $kill_stdout_capture

        kill -s 15 $kill_read_capture_xtrace
        kill -s 15 $kill_xtrace_capture
    }
}
```

To try it, take an app, call the function `hide_password` try to echo some stuff that contains "password".
And do not forgot to call `ynh_clean_setup` later into the script. Otherwise it will hang forever.

**Comment by decentral1se** [comment]
Thanks for this work!

Question: Is there any way we can pass all this into the Python layer? Some sort of log processing function. I ask because this is all looking  complicated and difficult to understand and therefore this will make it quite possible that we find regressions in this password redaction in the future.

**Comment by maniackcrudelis** [comment]
I think the idea is anyway to do that in python.
I doubt though it would be easier in python than bash.

That's not really that difficult, it's just a redirection of each file descriptors into files to replace password and redirect back to the output.
if I find some time, probably next week, I'll finish that. But still in bash for now.

**Comment by Josue-T** [comment]
Hello,

I think that it's more easy on the python side.

[Here](https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/hook.py#L375-L376) is the default function used to process each line of the log in the Yunohost side. But we can define a specific function for the App management (the default is `logger.debug(l.rstrip()+"\r"),`). We can by example add a sed like function to hide the password. The problem that I still don't have a really good solution for, is how to know what we need to hide. We can maybe get some generic things like the root mysql password or the password given by argument (defined in the manifest). But there are many other case which is less easy to know...

I'm interested to work on that if it make everybody happy on this side :smile:

**Comment by maniackcrudelis** [comment]
To know what are the passwords will be part of what I'm working on.
Since we can't know what are passwords, I though to use a list, filled by a dedicated helper.
Each time a password would be declared or created, this helper should be called to hide the declaration itself and store the password into the list.

So the part of code dedicated to hide password could rely to this list to know what to hide.
I'm still thinking though about how to fill the list, by the password itself or the variable that will contains it. The second one's probably better as it doesn't store the password in clear.

For now, I'm going to continue working on that matter (in bash...), better to have something that work in bash than nothing at all for now.

**Comment by Josue-T** [comment]
One solution is to say (just by a echo like) the next line you will have a password. So add this to your list to hide.

In bash code it could like that:
```
echo "start password zone"
# define your password
...
echo "password defined :'YOUR_PASSWORD'"
```
By this the lines between the both echo will be completely hidden. And the last line will give the password to hide every-time with a sed-like function.

And in parallel we can implement something in the `ynh_settings_get` function "ynh_app_setting_get" to hide settings which contains the "pwd" or "password" key.

**Comment by maniackcrudelis** [comment]
Not feeling like sleeping, I worked a little on that matter.

I made some adjustment, especially using sed only when needed.
And add a simple function to add a password to the list, by adding the name of the variable that contains it.

I have issues though on using the list of passwords in sed for now.

Here the new code
```bash
passwords_list=""
add_password_to_hide () {
    if [ -z "$passwords_list" ]; then
        passwords_list="${!1}"
    else
        passwords_list="$passwords_list\|${!1}"
    fi
}

hide_password () {

    touch {stdout,stderr,xtrace}_file_capture
    # Duplicate file descriptor stdin into fd 3
    # Then redirect stdin to a file.
    exec 11>&1; exec 1>>stdout_file_capture
    # Do the same for stdout
    exec 12>&2; exec 2>>stderr_file_capture
    # And xtrace
    exec 17>&7; exec {BASH_XTRACEFD}>>xtrace_file_capture

    # Create fifo for all 3 previous files.
    mkfifo {stdout,stderr,xtrace}_fifo_capture

    # Start 3 tail in background to follow the outputs.
    # This part could probably be made easier.
    tail -F stdout_file_capture >>stdout_fifo_capture &
    kill_read_capture_stdout=$!
    tail -F stderr_file_capture >>stderr_fifo_capture &
    kill_read_capture_stderr=$!
    tail -F xtrace_file_capture >>xtrace_fifo_capture &
    kill_read_capture_xtrace=$!

    replace_password () {
        if echo "$1" | grep -E "$passwords_list" >/dev/null
        then
            echo "$1" | sed 's/password/********/g'
#             echo "$1" | sed "s@$passwords_list@********@g"
        else
            echo "$1"
        fi
    }

    # Read outputs from their fifo
    while read -r stdout_capture
    do
        # Replace 'password' by asterisk and redirect the result into the duplicated file descriptor
        # If the result is redirected into the same file descriptor, it would loop.
        replace_password "$stdout_capture" >&11
    done <stdout_fifo_capture &
    kill_stdout_capture=$!

    while read -r stderr_capture
    do
        replace_password "$stderr_capture" >&12
    done <stderr_fifo_capture &
    kill_stderr_capture=$!

    while read -r xtrace_capture
    do
        ynh_print_OFF; replace_password "$xtrace_capture"; ynh_print_ON >&17
    done <xtrace_fifo_capture &
    kill_xtrace_capture=$!

    stop_hidding_password () {
        # Remove warnings from killing tail and while loops
        exec 12>/dev/null

        # Kill the 3 tail and the 3 while loops.
        kill -s 15 $kill_read_capture_stdout
        kill -s 15 $kill_stdout_capture

        kill -s 15 $kill_read_capture_stderr
        kill -s 15 $kill_stderr_capture

        kill -s 15 $kill_read_capture_xtrace
        kill -s 15 $kill_xtrace_capture

        # Restore file descriptors
        exec 1>&11
        exec 2>&12
        exec 7>&17

        rm -f {stdout,stderr,xtrace}_file_capture
        rm -f {stdout,stderr,xtrace}_fifo_capture
    }
}
```

**Comment by maniackcrudelis** [comment]
A third version, with a working list of passwords.
Also some adjustments to make it faster and simpler.

```bash
add_password_to_hide () {
    local passwords_list=""
    # Get the previous passwords into the file
    if [ -e grep_passwords_list ]
    then
        passwords_list=$(cat grep_passwords_list)
    fi

    if [ -z "$passwords_list" ]; then
        passwords_list="${!1}"
    else
        passwords_list="$passwords_list|${!1}"
    fi

    # Store the passwords into a file, to allow the already running function to have an up to date list.
    echo "$passwords_list" > grep_passwords_list
    chmod 600 grep_passwords_list
}

hide_password () {
    # Create 3 fifo to redirect the file descriptors.
    mkfifo {stdout,stderr,xtrace}_fifo_capture

    # Duplicate file descriptor stdin into fd 11
    # Then redirect stdin to a fifo.
    exec 11>&1; exec 1<>stdout_fifo_capture
    # Do the same for stdout
    exec 12>&2; exec 2<>stderr_fifo_capture
    # And xtrace
    exec 17>&7; exec {BASH_XTRACEFD}<>xtrace_fifo_capture

    replace_password () {
        local line="$1"
        # Get the list of passwords to hide from the list
        local passwords_list="$(cat grep_passwords_list)"
        # If a password is detected in the line, hide the password.
        if echo "$line" | grep -E "$passwords_list" >/dev/null
        then
            # Escape pipes into the list
            passwords_list=${passwords_list//|/\\|}
            # Escape @, as it's used by sed
            passwords_list=${passwords_list//@/\\@}
            # Hide passwords
            echo "$line" | sed "s@$passwords_list@********@g"
        else
            echo "$line"
        fi
    }

    # Do not log the caching of each line
    exec {BASH_XTRACEFD}>/dev/null

    # Read from the fifo and send each line to replace_password to hide passwords
    local stdout_capture=""
    while read -r stdout_capture
    do
        replace_password "$stdout_capture" >&11
    done <stdout_fifo_capture &
    kill_stdout_capture=$!

    local stderr_capture=""
    while read -r stderr_capture
    do
        replace_password "$stderr_capture" >&12
    done <stderr_fifo_capture &
    kill_stderr_capture=$!

    local xtrace_capture=""
    while read -r xtrace_capture
    do
        replace_password "$xtrace_capture" >&17
    done <xtrace_fifo_capture &
    kill_xtrace_capture=$!

    # Restore logging
    exec {BASH_XTRACEFD}>&1

    stop_hidding_password () {
        # Restore file descriptors
        exec 1>&11-
        exec 2>&12-
        exec 7>&17-

        # Kill the 3 while loops to close the fifos.
        # Didn't find a way to close them otherwise so far.
        kill -s 15 $kill_stdout_capture
        kill -s 15 $kill_stderr_capture
        kill -s 15 $kill_xtrace_capture
    }
}
```

**Comment by Psycojoker** [comment]
PR has been merged so I'm closing this, don't hesitate to reopen if needed.

**Comment by Josue-T** [comment]
Well,

As explained [here](https://github.com/YunoHost/yunohost/pull/742#issuecomment-507859592) we still have the clear password in the in the cli and the api. So can we really consider this as completely fixed ?

**Comment by alexAubin** [comment]
Depends of what's the scope of the issue exactly : if that's for what's shared with yunopaste, then that's fixed because the raw cli and api are not shared this way

If that's about all logs in general, than that's not 100% fixed

**Comment by Psycojoker** [comment]
Okay then :man_shrugging:

**Comment by alexAubin** [comment]
Btw we have a new case that is uncovered nowadays, after the introduction of config panels, sometimes the raw base64 version of files is ends up in logs, such as vpnclient install logs, and contain super personal secrets like VPN certs..

**Comment by alexAubin** [comment]
Closing because meh let's assume this is done idk
