### ISSUE TITLE
on user creation, "Error: Unknown mail address domain 'protonmail.com'" can be confusing (people put their already existing email address)

### ISSUE THREAD

**Issue by bencelaszlo** [YunoHost/issues#1365]
When I try to create a YunoHost user it runs error, because:
`Error: Unknown mail address domain 'protonmail.com'`
Which is obviously not true, [Protonmail is exist as an email provider](https://protonmail.com/).

**Comment by alexAubin** [comment]
Sorry for the misunderstanding, but the email asked is not "an existing email address", it's the address to be created for your user.

So if your main domain is `yolo.test` for instance, you might want the email address created for your user `sacha` to be `sacha@yolo.test`

**Comment by bencelaszlo** [comment]
I was the wrong, sorry.

**Comment by Psycojoker** [comment]
Actually that's an UX bug, thanks for repporting :) (don't hesitate to unsubscribe if you want)

**Comment by bencelaszlo** [comment]
> Actually that's an UX bug, thanks for repporting :) (don't hesitate to unsubscribe if you want)

Oh, it's okay, then it is a bug, just not what I thought. In this case, I keep myself subscribed.

**Comment by alexAubin** [comment]
Somebody worked on this during the brique camp but still hasnt created the corresponding PR despite having a working code ... Poking him about it from time to time ...

**Comment by ketsapiwiq** [comment]
An improvement PR by @ekhae has been posted here to ask for domain then username, ans assemble the email address, if I got this well: https://github.com/YunoHost/yunohost/pull/962
and here : https://github.com/YunoHost/yunohost-admin/pull/298

**Comment by bencelaszlo** [comment]
I'm more than just happy. Thank you all!
