### ISSUE TITLE
Use Python 3

### ISSUE THREAD

**Issue by filips123** [YunoHost/issues#1367]
Currently, YunoHost uses Python 2.7 which is old, deprecated and it will be [unsupported in 2020](https://pythonclock.org/). Many Linux distributions also dropped Python 2 from default programs.

 So, please upgrade YunoHost to Python 3.

**Comment by Psycojoker** [comment]
There is currently a beginning of port on python 3 but our manpower is very low so it's not really moving forward, all help is welcome https://github.com/YunoHost/moulinette/pull/172

**Comment by alexAubin** [comment]
We should really find somebody willing to commit to that ... I guess I will probably end up working on the Buster migration, but I certainly won't be able to work on *both* those outstanding issues

**Comment by decentral1se** [comment]
I'd be willing to contribute some time to this and in fact, I've already taken a look at the situation but I'd need some serious hand holding and direction from you all to get started. How will this process even work? Will the buster migration and Python 3 happen at the same time :see_no_evil: What needs to be ported to Python 3 anyway? Moulinette, core and? Has someone already started? Questions!

**Comment by alexAubin** [comment]
Btw Debian explicitly aim to remove / deprecate further support for python2 in Bullseye, in particular drop support for many (all?) Python2 packages/libs : 

https://lists.debian.org/debian-devel-announce/2019/11/msg00000.html

**Comment by alexAubin** [comment]
Let's close it, it's done in 4.2

**Comment by decentral1se** [comment]
Congratulations :fire:
