### ISSUE TITLE
Improving the application installation workflow

### ISSUE THREAD

**Issue by wayneoutthere** [YunoHost/issues#1369]
Hello and thank you so much for this super exciting project.  I hope to be a contributor and promoter long term!

This post is a suggestion about the flow of installing apps.  

## Background
I come from a cpanel softaculous background and probably a **lot** of people will be similar once they discover Yunohost.  I feel that the YH installation flow is 'nearly' perfect but the problem is that I did not see or read the 'read  me' section of an app before I installed it and it created a negative experience.  It's true that it's my fault but I think we can avoid this from happening by adding a few more steps to the installation flow.  I have created screenshots for each step so that my idea is more clear.

### STEP 1 - SELECT APPLICATION (CURRENT WAY IS FINE)
![01_yh_app_chooser](https://user-images.githubusercontent.com/16578346/60026981-7458ba00-9651-11e9-8b88-e3888f0deb83.png)

### STEP 2 - PRE-INSTALLATION SCREEN / PRE-FLIGHT (NEW)
This screen tells you all the key points that the app needs you to know **before** you begin.  It might also (not shown in my screenshot) pre-warn you that the post-installation email will be sent (people need reminders...)

![02_yh_app_PROPOSED_PRE_INSTALL_PAGE](https://user-images.githubusercontent.com/16578346/60027020-85a1c680-9651-11e9-8c64-950f2a90655f.png)

### STEP 3 - TECHNICAL INSTALL SCREEN (CURRENT ONE IS GREAT)
![03_yh_technical_install_page](https://user-images.githubusercontent.com/16578346/60027065-96523c80-9651-11e9-8346-96935594c0cf.png)

### STEP 4 - POST-INSTALL SCREEN (NEW)
This page is self explanatory.  Main point is 'make sure they know the email is sent!"
Button at bottom also gives 'final-final' feeling of completion an then takes them to the app list (next step)

![04_yh_app_PROPOSED_POST_INSTALL_PAGE](https://user-images.githubusercontent.com/16578346/60027107-a66a1c00-9651-11e9-8892-f63a77161d1c.png)

### STEP 5 - FINAL INSTALLED APP LIST (SAME AS NOW IS GOOD)
![05_final_installed_app_list](https://user-images.githubusercontent.com/16578346/60027127-b550ce80-9651-11e9-8594-7e6e4514e280.png)

**Comment by decentral1se** [comment]
> PRE-FLIGHT (NEW)

Very. Good. Idea.

**Comment by bjarkan** [comment]
Maybe even a sum of total resources needed by the apps. Not all will be at first, just optional. Kind of 1giga of ram in total recomended for this app alone. Just add an optional values, space, logs, blah ... resources. 

It will help to decide resources-ly in very extreme low resources enviorment... i dont know... maybe seafile is less hungry resources than nextcloud just for file hold, or things like that...

But also... optional, so we dont break back compatibility

**Comment by Psycojoker** [comment]
Just to thanks you for the time you've took to put up this proposal and all your ideas :)

And also to tell you that we are all so overwhelmed with things to do that I don't know when this will be done :( (I've recently re-did my todo list for yunohost and there is like 29 items in it and not small ones x() (I'm going to add this into it but that will give you an idea :/) (and I'm happy when I managed to put 10h/week in YunoHost dev :x)

**Comment by wayneoutthere** [comment]
Understood and thanks for considering the ideas! :)  Stay healthy!

**Comment by alexAubin** [comment]
Ongoing at https://github.com/YunoHost/yunohost-admin/pull/486

**Comment by tituspijean** [comment]
Done as of v11.1.2!

**Comment by wayneoutthere** [comment]
fantastic!  so many thanks to the team!
