### ISSUE TITLE
Backup fails for Armadietto

### ISSUE THREAD

**Issue by bhdouglass** [YunoHost/issues#1371]
I'm not sure exactly if this is an issue with Armadietto, Archivist, or the YunoHost backup system, so I'm posting this bug here to see if anyone can help me track down the proper place for this.

With a fresh install of YunoHost and Armadietto backing up the whole system will fail to include Armadietto. According to the logs this is because `Source path '/etc/logrotate.d/armadietto' does not exist` (this seems like a bug in Armadietto). Creating this directory will allow backing up with the YunoHost backup.

I would also like to automate the backups so I've installed Archivist. I've manually run the backup using `yunohost app action run archivist force_backup`, but it fails to backup Armadietto with `Warning: OSError: [Errno 17] File exists: '/home/yunohost.app/archivist/backup/ynh_backup/temp/apps/armadietto/backup/opt/yunohost/armadietto'` (full log: [archivist.log](https://github.com/YunoHost/issues/files/3332950/archivist.log)).

If I comment out these two lines from the [Armadietto backup script](https://github.com/bencharp/armadietto_ynh/blob/master/scripts/backup) then I can get Archivist to successfully backup Armadietto: 
ynh_backup --src_path="$final_path"
ynh_backup --src_path="/home/yunohost.app/$app"

Is this a bug in the Armadietto backup script or something that YunoHost/Archivist should gracefully handle?

**Comment by maniackcrudelis** [comment]
Hi bhdouglass

That looks like first, an error from Armadietto, the backup tries to backup `/etc/logrotate.d/armadietto` but the install script does not set any logrotate config.

Then what looks like a common error from YunoHost, when a backup fails the temp directory isn't purge. But here that's indeed into Archivist directories, still the error is from python by YunoHost, not Archivist.
Having a look to the backup script of this app, it may comes from it. There's a lot of files backup twice...
I think you should open a ticket as well into Armadietto_ynh repository to ask the maintainer of this package to test and fix the backup script. This script isn't currently tested by our CI.

**Comment by bhdouglass** [comment]
Thanks for taking a look at this! I'll go ahead an open up an issue on the armadietto yunohost app.
