### ISSUE TITLE
PageKite integration? it's a bit like our vpns

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1373]
Dunno if it's worth it https://pagekite.net/

Looks especially easy to setup and solve the same problem than our vpns.

Maybe we can also create some PageKite network? like in the FFDN? Or ourselves and get a bit of funding like that?

**Comment by alexAubin** [comment]
Meh I'm super skeptical because this has a lot of security/privacy implication ... I mean it's essentially a man-in-the-middle controlling the domain name and all traffic :|

**Comment by alexAubin** [comment]
Closing because we're not really going to recommend people to enable a man-in-the-middle on their servers idk ... There are other ideas with SNI-based forwarding and tailscale/headscale
