### ISSUE TITLE
Doc for ynh_script_progression

### ISSUE THREAD

**Issue by kay0u** [YunoHost/issues#1374]
https://yunohost.org/#/packaging_apps_helpers_en

The documentation for ynh_script_progression is broken, look for `increment_progression' in this page.... Plus, it's no longer possible to extend the card.

For me, the problem is that the doc is followed by a few variables, but not the function itself:

https://github.com/YunoHost/yunohost/blob/ac7102a0caee9c6d2d8808ef4b345edfbdbb54e8/data/helpers.d/logging#L199

**Comment by alexAubin** [comment]
Yea sorry, gotta re-generate the page following the 3.6 release, using this script https://github.com/YunoHost/yunohost/blob/stretch-unstable/doc/generate_helper_doc.py

**Comment by kay0u** [comment]
Fixed \o/
