### ISSUE TITLE
add an dedicated page in the admin to help configuring port forwarding

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1375]
Configuring port forwarding is a tedious and complex task, especially for non very technical people and even annoying for technical people, it would be great to improve that.

One way to do that would be to create a page for that in the admin interface that would present a workflow and help detecting if things are done correctly.

Brain dump:
- check if ports are open
- check port from outside (like for the "self http get")
- display local ip of the machin
- automatically configuring static ip for the server?
- check if upnp works and use it if necessary
- display inline documentation regarding as much as possible ISP as we can get
- if possible, detect the good ISP for that (ip range for ex?)
- check if the ISP requires to open manually port in some user interface, give link to that
- does those rooter have an api? can it be used to detect if port forwarning is done correctly and even do it?
- detect if port forwarding that was working has been broken?

**Comment by Psycojoker** [comment]
Another "we really don't have time to do that" would be to write a smartphone app to test your instance from the outside (and like having this fancy QR code to send information from the instance to the app.)

**Comment by alexAubin** [comment]
Closing because the diagnosis pretty much solved this, at least we have way less questions about port fowarding than before
