### ISSUE TITLE
use translations for manpages generation

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1376]
It's a bit stupid since I've only realized that after the release, but it would be good to use the translations that we already have (we have it for the commands help, right? Not even sure) to make it translatable and generates it in all the languages we have translation for.

Looking quickly I've found this doc but haven't really read it
http://docs.translatehouse.org/projects/localization-guide/en/latest/guide/project/manpages.html

**Comment by alexAubin** [comment]
> (we have it for the commands help, right? Not even sure)

Uh I don't think we do ? It's in clear in the yml file : https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/actionsmap/yunohost.yml#L66

**Comment by Psycojoker** [comment]
Damn :(

I guess we'll need to start by that.

**Comment by Psycojoker** [comment]
Need to do that first https://github.com/YunoHost/issues/issues/758

**Comment by alexAubin** [comment]
Closing because meh, #wontfix, people using the command line and man pages are usually fluent in english ...
