### ISSUE TITLE
People are confused by the avatar thing in the SSO portal and would like to edit it

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1381]
Dunno if anything was planned initially about this in SSOwat, but I wouldn't see the point of having a user avatar ... YunoHost ain't a social network where you could see other user's avatar, so it would just be about configuring an avatar that only you can see ...

Dunno what to do about this except removing it so people stop being confused by it

**Comment by decentral1se** [comment]
My only guess: apps could use this single avatar so the user could have a single avatar across all apps and therefore be easier to identify by other users. Not sure if apps event support that though ... yunohost would have to provide it's own gravatar style service lel

**Comment by Limezy** [comment]
When managing several Yunohost instances / accounts, it would be quite useful to see "where" I am and which user I'm logged in. 
A gravatar-like service would be perfect but I guess that's very long term prospective

**Comment by ScrumpyJack** [comment]
Gravatar integration would be neat

**Comment by NathanRHD** [comment]
I wonder if Libravatar might be neat?
https://www.libravatar.org/

**Comment by tituspijean** [comment]
> YunoHost ain't a social network where you could see other user's avatar, so it would just be about configuring an avatar that only you can see ...

Use case: with Flarum or any forum software, we could get the user's avatar from the LDAP server. Maybe it could work with Synapse/Element too?

**Comment by alexAubin** [comment]
@tituspijean : yes you could probably also integrate it in Nextcloud and so on (and then people will start complaining that they defined an avatar but it's not integrate in app X) but to me that's just clearly not the priority among everything there's to do in the project ...

**Comment by alexAubin** [comment]
(That's my "old embittered dev" point of view but of course if anybody is super enthusiast about having and working on this feature, let's go ¯\\_(ツ)_/¯)

**Comment by tituspijean** [comment]
Yup, and that's actually the point of your issue. People, including me, got scared to have the feature abandoned altogether, while you only worry about it being half implemented (placeholder in the web UI, but no ways to upload and display the avatars).

**Comment by lucyferu** [comment]
> My only guess: apps could use this single avatar so the user could have a single avatar across all apps and therefore be easier to identify by other users. Not sure if apps event support that though ... yunohost would have to provide it's own gravatar style service lel

Yeah, something like that would be great.
So to automatically add, for example, an avatar to your email account and/or whatever other messaging service you do have.

**Comment by tootbrute** [comment]
I see two options with it:
- let us add our own picture to it that is only in the Yunohost SSO
- kill the feature completely

Too much work to do anything else with it. There are lots of other more important things that the devs could be doing with their time...

...unless, somebody really, really wants to work on this feature :/

**Comment by Bugsbane** [comment]
Third option:

**The avatar used in YunoHost SSO is used only for the Yunohost interface and setting the *initial* avatar for users in each app.**

It doesn't sync back avatar changes from each app to Yunohost, as that would take way more work and remove the ability to have different avatars across different apps.

Here's my usecase:
I'm setting up a number of services for my family (Nextcloud, Mastodon, Pixelfed, Element Web, Peertube). Yunohost doesn't make me set up users 35 times (5 apps x 7 users). I set up each user once in the admin and the rest happens automatically. Well, *almost*.

_After setting up the users, I still need to manually log in to different app/user combinations THIRTY FIVE times to upload the avatars. This is a pain in the butt, and I only have a handful of users and apps!_

Also, having an avatar in the Yunohost admin just makes it faster to scan for the right person (especially given that I have three people in our family with the same first name).

**Comment by axolrotflotl** [comment]
Four years later, as a new user I can attest that people (that is, me) are still confused by the non-avatar. I understand that it was intended as a feature to be implemented along the way, and that the developers have had more pressing issues to deal with.

The thing is, when end users see a default avatar on their new profile, they expect to be able to upload their own. We've just been conditioned that way by all the web 2.0 accounts we've set up over the years.

In this case that expectation becomes a futile distraction, and I'd suggest just getting rid of the avatar altogether. It doesn't serve a purpose, and it certainly isn't decorative. If anything I'd suggest just a monochrome filled circle with the user's initials in it, if that helps admins scan a user index more intuitively.

**Comment by Bugsbane** [comment]
One purpose it serves is to tell users quickly and visually what account is currently logged in. Humans neurologically recognize people by images much more quickly, easily and intuitively than by reading names.

A second purpose it serves is to let admins who are setting up accounts for others to create avatars without an unnecessary amount of account switching.

That's just a couple of uses when the avatar is only in Yunohost SSO. If, later on, that image was made available to apps, then as I mentioned as an admin it would save me, an admin of a small family server, 35 (or more) sets of logging out of one account and into another to setup default avatars.

It also wouldn't require reinventing Gravatar at all. These avatars wouldn't need to be accessible from outside Yunohost. The avatars wouldn't need to sync back from the apps to the SSO. They wouldn't require syncing from the SSO to the apps regularly. They would only be an image to show who is logged in to the SSO, and possibly later for app devs to grab via their install scripts as a default user image when the apps are set up.

A simple notification could be added, just when uploading an image: "This image will only be used in Yunohost and for setting up some apps default avatar." 

As far as I can see, all this should take is:
1. A field in the user edit screen to upload an image called {$USERNAME}.png with the warning above.
2. Use a library to crop and downscale the image to a standard size.
3. Change the current default image path to use the  instead.
4. [Optional later] make that folder accessible to apps install scripts.

I can understand people arguing that there are more important things to work on. I really can. This proposal seems to be a much, much smaller suggestion though than reinventing Gravatar.

**Comment by alexAubin** [comment]
Closing because it's been 4~5 years, this is going nowhere, the new portal will display the domain's logo (YunoHost by default, but easily customizable) instead of the "blank avatar" thing, and even if we still wanted avatar, it's not as if we'd magically integrate the avatar in apps somehow...
