### ISSUE TITLE
Support unified app helpers for Ruby / Rbenv

### ISSUE THREAD

**Issue by westonganger** [YunoHost/issues#1383]
It would be great to have unified Ruby version support similar to the NodeJS integration within https://yunohost.org/#/packaging_apps_helpers. 

This could be done fairly easily using `rbenv`

Would you be open to a PR regarding this? or is this considered an application level concern?

**Comment by Psycojoker** [comment]
Helpers ends up in the core but I know they generally have a testing period either on individual apps or in this repository https://github.com/yunohost-apps/yunohost (managed by the app team)

I'm not part of the app team (but the core team), but in the mean time I would recommend you to:

* start building those helpers for your apps (put them in a `common.sh` for eg)
* try to fit to the pattern of existing nodejs helper when possible
* once you have something working or even before, start talking with apps team members on how to integrate
* from here you should know what to do but you'll probably end up doing a PR to https://github.com/yunohost/yunohost for integration

Side note: I've seen people using rvm much more than rbenv, I don't have any opinion on that but I'm surprised about that.

**Comment by maniackcrudelis** [comment]
There's already an experimental helper for ruby https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_install_ruby/ynh_install_ruby. It uses rbenv.
To use it, copy the code into your _common.sh
If you find anything that doesn't work properly, please make a PR on this repo to explain and fix (if you can).

**Comment by alexAubin** [comment]
Idk, closing this then since we do have some even if experimental (the discussion about what should be included in yunohost core is much more general)
