### ISSUE TITLE
Error: Retrieved file for application list yunohost is not valid

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost/issues#1387]
(I think) Since last update (17.7.) when trying to update yunohost:
```
yunohost tools update
Info: Fetching available upgrades for system packages…
Info: Fetching available upgrades for applications…
Error: Retrieved file for application list yunohost is not valid
Info: Nothing to do! Everything is already up to date!
apps:
system:
``` 

not urgent, just want to tell you!

**Comment by alexAubin** [comment]
Uuuh, what do you mean though, "last update (17.7)" ? What's this version number ?

Also can you try to re-run the command with `--debug` ?

What do you get if you run `yunohost app listlists` ? And do you get some sort of error message if you run `curl https://app.yunohost/apps.json` (which should be the url you get with the previous command)

**Comment by Psycojoker** [comment]
> Uuuh, what do you mean though, "last update (17.7)" ? What's this version number ?

Maybe it's the date like 17th of July?

Also error message is really bad here, we should change it

**Comment by alexAubin** [comment]
Closing due to lack of feedback ... I don't think this was really a long-term bug since nobody else reported it ...
