### ISSUE TITLE
clean unused strings in "locales/en.json"

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1388]
With the evolution of the code base some strings to translate in `locales/en.json` (and by consequence the others translation files) end up not being used anymore in the source code, we should do some cleaning to remove them so the new translation will have less work to do.

**Comment by alexAubin** [comment]
Related to https://github.com/YunoHost/yunohost/pull/793

**Comment by alexAubin** [comment]
PR got merged
