### ISSUE TITLE
moulinette crash yunohost on unexisting untranslated string

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1391]
I thought we had hardened this part of the code, it's really weird but apparently it's still possible for yunohost to crash on unexisting translationg string, see:

```
Action

GET /logs
{"locale":"br","with_details":"","limit":"25"}

Traceback

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 439, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 523, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 109, in log_list
    logger.warning(m18n.n('log_corrupted_md_file', file=md_path))
  File "/usr/lib/python2.7/dist-packages/moulinette/core.py", line 215, in n
    return self._namespaces[self._current_namespace].translate(key, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/moulinette/core.py", line 107, in translate
    return self._translations[self.locale][key].encode('utf-8')
KeyError: 'log_corrupted_md_file'
```

**Comment by decentral1se** [comment]
Unsure if it is the case but this looks related: https://github.com/YunoHost-Apps/etherpad_mypads_ynh/issues/72.

**Comment by decentral1se** [comment]
This CI build on Moulinette just showed a lot of errors being spit out ...

https://travis-ci.org/YunoHost/moulinette/builds/563905323

**Comment by Psycojoker** [comment]
> Unsure if it is the case but this looks related: [YunoHost-Apps/etherpad_mypads_ynh#72](https://github.com/YunoHost-Apps/etherpad_mypads_ynh/issues/72).

No this is just a warning https://github.com/YunoHost/moulinette/blob/stretch-unstable/moulinette/core.py#L108

**Comment by alexAubin** [comment]
Uh, isnt this like related to missing / additional data that are missing / not used in the actual string ?

For example it sounds weird that the test report an error about "cannot_write_file" but the string exist ... And if it's a warning shouldn't we display it as such ? :s 

(Edit: ah but that's a logger.exception which is then caught later I guess :/ )

**Comment by Psycojoker** [comment]
> This CI build on Moulinette just showed a lot of errors being spit out ...
> 
> https://travis-ci.org/YunoHost/moulinette/builds/563905323

Ah, this is because of badly written strings, unrelated to here.

Like you have something like that:

`"some_error": "blablabla {variable}"`

Then: `m18n.m("some_error", another_variable_name="something")`

**Comment by Psycojoker** [comment]
Fixed by https://github.com/YunoHost/moulinette/commit/599bec33b891aca9285fc0e61f90020b74dbf564
