### ISSUE TITLE
Some LXC throw "Operation not permitted" when trying to use swapon, make some installs like gitlab crash

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1392]
A friend tried to install Gitlab in a LXC, which apparently went well ... until the install tried to run `swapon` to add swap, then the system answered "Operation not permitted"

Ideally we should add a check that we can run `swapon` at the very beginning of the script instead of running the whole thing and crashing later :s

**Comment by Psycojoker** [comment]
cc @YunoHost/apps

**Comment by kay0u** [comment]
Some logs would be great, because `swapon` is done at the beginning of the install script :

https://github.com/YunoHost-Apps/gitlab_ynh/blob/6187c4bdf0c7d9a105a73b0c23200bb012c9625f/scripts/install#L135

**Comment by alexAubin** [comment]
Closing because havent heard of this since I reported that issue
