### ISSUE TITLE
Enable pop3 with Dovecot by default

### ISSUE THREAD

**Issue by decentral1se** [YunoHost/issues#1393]
Following https://github.com/YunoHost-Apps/discourse_ynh/issues/2#issuecomment-408825728 and also https://forum.yunohost.org/t/how-to-enable-pop3-in-yunohost/1662/2, I am wondering if there are objections to enabling Pop3 by default in the default generated Dovecot configuration?

In order to get replies by email working in Discourse, I have to enable it.

Here's my diff:

```diff
root@foo:~/postfix# yunohost tools regen-conf dovecot -nd
Warning: The configuration file '/etc/dovecot/dovecot.conf' has been manually modified and will not be updated
dovecot: 
  applied: 
  pending: 
    /etc/dovecot/dovecot.conf: 
      diff: @@ -8,7 +8,7 @@
 mail_location = maildir:/var/mail/%n
 mail_uid = 500
 
-protocols = imap sieve pop3
+protocols = imap sieve
 
 mail_plugins = $mail_plugins quota
      status: modified
```

We also have to install `dovecot-pop3d` and expose the `995` port in the firewall.

It is still possible to not do this by default and use the `conf.d/*` overrides in the Dovecot configuration but I am wondering if there is some value in just having this arranged by default.

It's an open question, I suppose.

**Comment by decentral1se** [comment]
An alternative can be: document this on the official documentation and leave it at that.

Might be less scary. Email is scary.

**Comment by Josue-T** [comment]
Maybe the best solution is to add a yunohost settings to give the possibility to enable this.

We also need to think about the firewall and fail2ban. If we just add a settings we can say that it's just local and we leave the firewall closed.

**Comment by rds13** [comment]
I would rather like this to be an option as it's mainly usefull for discourse usage.

**Comment by Psycojoker** [comment]
Are there good reasons to /not/ enable pop3 by default? I can't find any.

**Comment by rds13** [comment]
We tend to remove unused service for security concern. I believe today pop3 is not a common usage above our users. In the case of this PR enabling pop3 is one step among others to build a setup for discourse. All those steps can be automated with yunohost tooling.
If pop3 is used by discourse installed on the Yunohost server, the port should only be opened on localhost.

**Comment by decentral1se** [comment]
I just saw https://github.com/YunoHost/yunohost/pull/773 arrive and it is very close to what we want to work on here when enabling pop3. It seems like a good approach, just set some settings and run the regen-conf and you have it. I'll try to get around to this soon.

**Comment by alexAubin** [comment]
pop3 setting for merge :+1:
