### ISSUE TITLE
refactoring: use app_map instead of doing things by hand in domain_remove

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1394]
Here https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/domain.py#L158

**Comment by alexAubin** [comment]
(Beware though about app_map not listing the special apps with `no_sso` enabled (among other things) :s )

**Comment by Psycojoker** [comment]
Add damn x_x

We really need this "low level lib" for YunoHost è^é/ !

**Comment by alexAubin** [comment]
Done in https://github.com/YunoHost/yunohost/commit/196a3d4d477f7cb168e2748715e06ddec74737d3
