### ISSUE TITLE
manifest.json doesn't handle spaces well in values

### ISSUE THREAD

**Issue by decentral1se** [YunoHost/issues#1400]
For example:

> https://github.com/YunoHost-Apps/foodsoft_ynh/blob/3a3ae30dda41768edebc680e7de7d78ae8bcf8e7/manifest.json#L89

The value "pops out" as: "Grune;Strasse;103" and I am not sure why.

**Comment by Psycojoker** [comment]
> The value "pops out" as: "Grune;Strasse;103" and I am not sure why.

In whish context? How can anyone reproduce this bug?

**Comment by decentral1se** [comment]
Right, I think we can agree this is not my best bug report ever :smile: 

I'll be back with a reproduction of this ...
