### ISSUE TITLE
ED25519 key doesn't work with the SSHD config

### ISSUE THREAD

**Issue by solarus0** [YunoHost/issues#1402]
Hi.

I found a problem in your sshd configuration template.
You should add this MAC umac-128-etm@openssh.com in the list, in order to get the ed25519 keys working properly.

Best regards.

**Comment by decentral1se** [comment]
> I found a problem

Explain more clearly what the problem is please.

**Comment by solarus0** [comment]
The umac-128-etm@openssh.com is already in your list.

You can close this issue, sorry for the noise.
