### ISSUE TITLE
Problems after first installing on fresh VPS

### ISSUE THREAD

**Issue by StalinEXE** [YunoHost/issues#1403]
I've decided to try YunoHost with some apps. My first experience with VPS, YunoHost and PeerTube, Pleroma and others.

So, I've bought VPS with Debian 9, bought domain.

After receiving login and password I've installed curl by YunoHost tutorial, then installed YunoHost.

After that I've received link for graphical using of this service. Logged in, added domain (it didn't ask me DNS), added password and user.

But I can't open page of Apps, can't work with domain, can't ipen Diagnosis, but have a popup with this:

```
Action

GET /diagnosis
{"locale":"ru"}

Traceback

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 439, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 523, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/tools.py", line 810, in tools_diagnosis
    applications = app_list()['apps']
  File "/usr/lib/moulinette/yunohost/app.py", line 257, in app_list
    with open(json_path) as json_list:
IOError: [Errno 2] No such file or directory: u'/var/cache/yunohost/repo/yunohost.json'
```
Again, I didn't install any unofficial applications. Fresh and updated Debian installation and first YunoHost launch.

May you help me with it, please?

**Comment by StalinEXE** [comment]
When I tried to manage my domain on domains page, I've received this.

```
Action

GET /apps
{"locale":"ru","installed":""}

Traceback

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 439, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 523, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/app.py", line 257, in app_list
    with open(json_path) as json_list:
IOError: [Errno 2] No such file or directory: u'/var/cache/yunohost/repo/yunohost.json'
```

**Comment by StalinEXE** [comment]
Reinstalling Debian helped.

**Comment by alexAubin** [comment]
Uh wokay, tried to push a small fix here : https://github.com/YunoHost/yunohost/commit/817358ade4731e9c3e4081ac103e917fb4a1449d

Would have been nice to investigate why it wasnt able to fetch the applist :/

**Comment by StalinEXE** [comment]
I don't know. Maybe the problem was in my first YunoHost installation with error (error while downloading files for installation). After that I'just run setup again and received these errors in admin panel.

Also, today I've configured domain and subdomains. Installed Wordpress and didn't find how to open admin panel (redirected to yunohost).
After installing peertube to subdomain admin panel of YunoHost is broken again.

```
Action

GET /diagnosis
{"locale":"ru"}

Traceback

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 439, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 473, in process
    arguments = vars(self.parser.parse_args(args, **kwargs))
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 653, in parse_args
    auth = msignals.authenticate(klass(), **auth_conf)
  File "/usr/lib/python2.7/dist-packages/moulinette/core.py", line 279, in authenticate
    return self._authenticate(authenticator, help)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 483, in _do_authenticate
    return authenticator(token=(s_id, s_hash))
  File "/usr/lib/python2.7/dist-packages/moulinette/authenticators/__init__.py", line 106, in __call__
    password = self._retrieve_session(s_id, s_hash)
  File "/usr/lib/python2.7/dist-packages/moulinette/authenticators/__init__.py", line 157, in _retrieve_session
    gpg = gnupg.GPG()
  File "/usr/lib/python2.7/dist-packages/gnupg.py", line 755, in __init__
    raise OSError(msg)
OSError: Unable to run gpg - it may not be available.
```

I understand that it is an unofficial app, but abillity to break YunoHost just installing app - it is amazing thing.

**Comment by StalinEXE** [comment]
Half an hour later it is working again. Fixed itself.

**Comment by Psycojoker** [comment]
> abillity to break YunoHost just installing app - it is amazing thing.

That's the joy of sysadmin, welcome to the madness world of "breaking down into working" where every little modification can destroy everything because the system is crap and has never been though to be robust.

**Comment by decentral1se** [comment]
> the system is crap

We need better marketing :smiley:

**Comment by Psycojoker** [comment]
> > the system is crap
> 
> We need better marketing smiley

More like database like transaction at the OS level, fully isolated packaging and config at every software level (like you shouldn't be able to break whatever service (nginx, fail2ban, php related stuff...) because one config file is bad), not a gigantic state where each little subtle modification could just break everything etc... The system is just a disaster. (but this discussion goes out of this ticket)

**Comment by StalinEXE** [comment]
My bad, sorry.
I really tired while trying to get my first experience with VPS, command line and others. To much personal mistakes.
You do a great and important thing. Please, keep going.

**Comment by Psycojoker** [comment]
Don't worry, it's always precious to get this kind of report of new users, they are very rare and helps us knowing what didn't work for them (which is kinda critical) :)
