### ISSUE TITLE
LDAP error management

### ISSUE THREAD

**Issue by Josue-T** [YunoHost/issues#1405]
The way to manage the LDAP error (for the `add`, `update`, `remove` operation) is really bad. Most of time we do something like that:

```python
if ldap.add(...):
    # continue the operation
else:
    raise YunohostError(...)
```

But after seeing the code in the moulinette I'saw that:
- If the LDAP operation succeed, the method return `True`
- If the there are an error, the method raise `MoulinetteError`

In the case of an error it's really bad because the `YunohostError` will be never called...

So I purpose to replace everywhere the if/else by a try/except. In the except case we can catch the `MoulinetteError` and raise the `YunohostError` which is generally more explicit. This might need some work because there are approximately 23 place where we are in this case.

**Comment by decentral1se** [comment]
Nice report! 

We have test infrastructure in place, so let's use it. 

We can test that certain exceptions are being raised when we make the change.

**Comment by alexAubin** [comment]
To be fixed in https://github.com/YunoHost/yunohost/pull/795 because I went berserk
