### ISSUE TITLE
Update to yunohost 3.6.4.6 fails

### ISSUE THREAD

**Issue by mdic** [YunoHost/issues#1406]
Updated yesterday my yunohost instance from 3.6.4.x (don't remember the exact number) to 3.6.4.5 without any problems. This morning I check my instance and there's a new update, 3.6.4.6.
After clicking on the "Update" button, I get the following error, but after reloading the web admin interface the version (bottom right corner) now shows 3.6.4.6.

```
Yunohost encountered an internal error:/
Really sorry about that.
You should look for help on the forum or the chat to fix the situation, or report the bug on the bugtracker.
The following information might be useful for the person helping you:
Action

GET /logs
{"with_details":"","limit":"25"}

Traceback

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 439, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 523, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 106, in log_list
    metadata = read_yaml(md_path)
  File "/usr/lib/python2.7/dist-packages/moulinette/utils/filesystem.py", line 73, in read_yaml
    loaded_yaml = yaml.safe_load(file_content)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 224, in fetch_more_tokens
    return self.fetch_alias()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 607, in fetch_alias
    self.tokens.append(self.scan_anchor(AliasToken))
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 926, in scan_anchor
    % ch.encode('utf-8'), self.get_mark())
ScannerError: while scanning an alias
  in "", line 11, column 25:
      YNH_APP_ARG_PASSWORD: **********
                            ^
expected alphabetic or numeric character, but found '*'
  in "", line 11, column 26:
      YNH_APP_ARG_PASSWORD: **********
                             ^ 
```

Can anyone help? Many thanks in advance

**Comment by decentral1se** [comment]
Hi @mdic, I am not exactly sure but that looks like our internal YAML parser is not able to parse redacted passwords. I am not sure why there is a redacted password in that file. This could potentially be related to the on-going work in https://github.com/YunoHost/issues/issues/1363.

**Comment by mdic** [comment]
> Hi @mdic, I am not exactly sure but that looks like our internal YAML parser is not able to parse redacted passwords. I am not sure why there is a redacted password in that file. This could potentially be related to the on-going work in #1363.

Hi @decentral1se many thanks for the quick reply, and for the details. Is there anything I can do to provide further details to help the people addressing issue #1363 ?

**Comment by decentral1se** [comment]
Hmmm, I just ran:

```bash
$ grep -iR "YNH_APP_ARG_PASSWORD" /var/log/yunohost/categories/operation/
```

And got a number of results like:

> /var/log/yunohost/categories/operation/20190726-081410-app_install-etherpad_mypads.yml:  YNH_APP_ARG_PASSWORD: **********
> /var/log/yunohost/categories/operation/20190725-174740-app_install-rainloop.yml:  YNH_APP_ARG_PASSWORD: **********
> /var/log/yunohost/categories/operation/20190726-082018-app_install-mediawiki.yml:  YNH_APP_ARG_PASSWORD: **********

Sooooo, it seems like this is fine on my system :/

**Comment by mdic** [comment]
I ran the following command as well

```
grep -iR "YNH_APP_ARG_PASSWORD" /var/log/yunohost/categories/operation/
```

and I got a number of results like yours:

```
/var/log/yunohost/categories/operation/20190712-111353-app_install-my_webapp.yml:  YNH_APP_ARG_PASSWORD: **********
```

but also a number of lines like:

```
/var/log/yunohost/categories/operation/20190611-174007-app_install-my_webapp.log:2019-06-11 19:40:07,345: DEBUG - About to run the command '['sh', '-c', 'YNH_APP_INSTANCE_NUMBER=1 YNH_CWD=/var/cache/yunohost/from_file/my_webapp_ynh-a050e55533ae7bbb63fce44fd1508ad78b8a645c/scripts YNH_APP_INSTANCE_NAME=my_webapp YNH_STDINFO=/tmp/tmpc3uoEH/stdinfo YNH_APP_ARG_PASSWORD=\'***REDACTED_PASSWORD***$\' YNH_APP_ARG_IS_PUBLIC=1 YNH_APP_ARG_WITH_MYSQL=0 YNH_STDRETURN=/tmp/tmpQ0QKcJ/stdreturn YNH_APP_ID=my_webapp YNH_APP_ARG_PATH=/site YNH_APP_ARG_DOMAIN=***REDACTED_DOMAIN*** BASH_XTRACEFD=7 /bin/bash -x "./install" ***REDACTED_DOMAIN*** /site \'***REDACTED_PASSWORD***$\' 1 0 my_webapp 7>&1']'
```

where I have redacted the plain-text password and the domain with `***REDACTED_PASSWORD***` and `***REDACTED_DOMAIN***` respectively.
Are these lines ok, or they shouldn't be there?

**Comment by Psycojoker** [comment]
I think it's this which is weird since it's supposed to be in 3.6.4.6 https://github.com/YunoHost/yunohost/commit/9d559bf42ccce773e01fafb31f8bc94b21dc56ec

**Comment by alexAubin** [comment]
>I think it's this which is weird since it's supposed to be in 3.6.4.6 YunoHost/yunohost@9d559bf

Note that this won't affect already existing logs though ... So it's unfortunately expected that some errors are remaining (but they will "spontaneously disappear" as only the last 25ish(?) operations are listed on the webadmin) but that should not be a critical error

@mdic : Does the error stops the page from loading ? If so, are you running the last moulinette version also ?

**Comment by mdic** [comment]
> 
> @mdic : Does the error stops the page from loading ? If so, are you running the last moulinette version also ?

@alexAubin after the error (the one copied in the first post) the upgrade apparently finished, as the web admin interface is now showing `Powered by YunoHost 3.6.4.6 (stable).`
Re. the other question when I upgraded yunohost 3.6.4.5 -> 3.6.4.6 `moulinette` was also upgraded from 3.6.4 to 3.6.4.1. Now the w**eb admin interface is working flawlessly, and so do all the other apps**, so I guess that - as you suggested - the error was not critical to the correct functioning of yunohost.
