### ISSUE TITLE
Raspberry Pi 2 version 3.4.2.3

### ISSUE THREAD

**Issue by kristijanPetr** [YunoHost/issues#1408]
I've downloaded Raspi image but it seems latest one is version 3.4.2.3, tried to upgrade via web app but it doesnt seem to do anything. The problem is I can't install any of the app because of unmeet Yunohost version <= 3.5.
Is there a way to upgrade via CLI or workaround to install the apps on this current version?

**Comment by alexAubin** [comment]
Eeeh can you elaborate on "It doesn't do anything" ?

I believe you might be referring to the "old" upgrade mechanism which worked in a weird way such that the actual upgrade of the yunohost package happens during the next hour ... (via a cron job)

So not sure if that's what's happening, but maybe you can recheck your server now ...

**Comment by kristijanPetr** [comment]
By "It doesn't do anything" i meant the upgrade was scheduled to be installed within next hour but have been 2 days and nothing happens. 

What is the preferred way to do so or via Command line if its possible?

**Comment by alexAubin** [comment]
Hmyea sorry about that ... so maybe you can try to : `apt dist-upgrade` from the command line

**Comment by kristijanPetr** [comment]
That didn't worked either got message `0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by alexAubin** [comment]
Closing due to lack of feedback / old issue / probably fixed by now somehow (though we gotta update our images someday...)
