### ISSUE TITLE
postinstall webadmin, "I already have a domain name… " button not responding

### ISSUE THREAD

**Issue by nrobinaubertin** [YunoHost/issues#1409]
During the postinstall (in webadmin mode), when coming back from a subsequent step, the "I already have a domain name… " button is not working anymore.

Repro:
1. fill out the domain step `/yunohost/admin/#/postinstall/domain` 
2. use the previous button on the password step `/yunohost/admin/#/postinstall/password`
3. the buttons to specify a domain are not working anymore

**Comment by alexAubin** [comment]
Fixed via https://github.com/YunoHost/yunohost-admin/commit/54739f10a526459ac22b3444196722d167a51cd7
