### ISSUE TITLE
Use the AuthorizedKeysFile parameter of the sshd_config to store authorized ssh keys

### ISSUE THREAD

**Issue by roukydesbois** [YunoHost/issues#1412]
My use case is that I have an encrypted home folder, that I mount at restart. But I need to ssh in my server in order to mount it, so I set my AuthorizedKeysFile to /etc/ssh/%u/authorized_keys
I'm 99% sure that the ynh CLI stores them in ~/.ssh today, so that wouldn't work for me.
And as you see for my settings, be careful with the replacement tokens (%u).

**Comment by decentral1se** [comment]
Hi @roukydesbois, this looks like a pretty rare case which a lot of YunoHost users won't find they need. Is it really an issue for you that you have to modify the default SSH configuration away from the default?

**Comment by roukydesbois** [comment]
Hey @decentral1se ! I don't really have an opinion on the rareness of the case, I just know it's my case ;) 
I would argue that this is a case that makes sense with the idea of getting back your data - it's a good idea to have it safe too! Also, we might not be aware of other reasons to change the location of the authorized keys file. And finally, don't you think it's cleaner and more robust to use a value that is set in a configuration file than a hardcoded one? 
I'm quite interested in this feature too, because it's a prerequisite to be able to use the SSH CLI tools in my situation, and potentially the tools in the web admin on top of these CLI tools.
I'm happy to try and do it myself if I'm pointed to the right places to look at!

**Comment by decentral1se** [comment]
You'll probably want to take a look at https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/templates/ssh/sshd_config then. You can allow to configure settings with the yunohost CLI and regenerate configurations, that might be way for you to optionally enabling configuring this. Hope that helps!

**Comment by alexAubin** [comment]
Closing because this is a super edge case ... It can be solved by creating a custom regen conf hook ...
