### ISSUE TITLE
Modification proposition on YNH for non-profit organisation page failed

### ISSUE THREAD

**Issue by jrd10** [YunoHost/issues#1414]
Hi
during the YNH camp 2019... called the Brique camp 2019 :)
I try (with Valentin (ljf), to propose a modification on the YUNOHSOT.org page by using the "edit" button and after "Send" button.
I put my email... a Google email (perhaps it is the source of the issue :) and a command.
And click on Send changes button.

It does not work and I got the following error message: “Invalid page name”.
Note ljf try to modify the page name by adding _en. Same issue.

Thank you for your time and consideration.

jrd / José

**Comment by tituspijean** [comment]
We have moved away from Simone now, there is no anonymous editor anymore.
