### ISSUE TITLE
Documentation about how to configure thunderbird should be updated

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1417]
Nowadays there's the MUA autoconfigure, .well-known thing which makes this page outdated

**Comment by eauchat** [comment]
Are you sure the page is not good anymore? I find this page great and very useful and even linked to it in the documentation for users of my server. For some reason the autoconfiguration doesn't always work (depending on the mail client) and it's quite nice resource to have such detailed explanation on how to solve the issue if it comes up.
Maybe just changing "The automatic detection tool of Thunderbird does not work yet with YunoHost. You will need to set it up manually. " to "If the automatic detection tool of Thunderbird does not work, you can set it up manually." and little things like this.

**Comment by alexAubin** [comment]
Hmmm agreed that it's indeed cool to have this page if the automatic detection doesnt work ... On the other hand, the fact that the automatic detection doesnt always work should be considered to be a bug ... :confused:

**Comment by eauchat** [comment]
Yep, it's true it's a bug, but yunohost is already doing so many great things, there are still lots of stuff to improve, and little by little one thing at a time it's getting there :)
I just rewrote a bit the page, and I'm posting the changes now.

**Comment by eauchat** [comment]
Here it is: https://github.com/YunoHost/doc/pull/1113
If it looks good to merge, I can also translate it to some other languages.

**Comment by alexAubin** [comment]
Thanks for the piece doc upgrade :+1: 

Still if you are able to provide details on the setup where autoconfiguration failed, that'd help, as I expect general non-techy users to not be 100% comfortable with configuring technical stuff like ports and encryption settings ... And it's even more troublesome if it's a seemingly "random" bug

My main guesses are: 
- users with 'username' not consistent with the email address (so different from `username@domain.tld`), e.g. `fancy.user.name@domain.tld`)
- or an nginx conf not up to date due to manual tweaks ? (c.f. `yunohost tools regen-conf nginx --dry-run`)

**Comment by eauchat** [comment]
Here are a French https://github.com/YunoHost/doc/pull/1114 and Spanish https://github.com/YunoHost/doc/pull/1115 versions as well.

**Comment by cyxae** [comment]
Can be closed ! Documentation has been updated

**Comment by alexAubin** [comment]
Cheers !
