### ISSUE TITLE
Refactore page app_nextcloud and translate it into english

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1419]
Currently it's only available in french and strangely starts directly with a huge section on adding storage space instead of properly introducing the app ..

Also if the tutorial is really long, could be worth to create a dedicated page (e.g. much later there's a section about Keeweb which people probably don't see if they scroll too fast etc0

**Comment by Plumf** [comment]
J'ai commencé à la refonte de la page de documentation mais je me pausais la questions de sous-arborescenses pour l'alleger 

https://github.com/Plumf/doc/blob/dev-doc/app_nextcloud_fr.md

**Comment by alexAubin** [comment]
Done by Plumpf I believe :+1:
