### ISSUE TITLE
Add setting for apps to disable Basic HTTP Auth header injection in some uris

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1420]
This is the cause of the issue of "Invalid Token" that is regularly reported by users of the Mastodon_ynh, Peertube_ynh, Bitwarden_ynh, and other apps.

SSOwat injects some basic HTTP auth header here : https://github.com/YunoHost/SSOwat/blob/stretch-unstable/helpers.lua#L394-L397

This conflicts with the oauth thing in peertube (dunno about other apps, we only investigated peertube with @yalh76) which will check if there's an Authorization header in the request, and if there is, assume it's a Bearer / Token auth header and won't try to check if it's a basic HTTP auth instead : 

https://github.com/oauthjs/node-oauth2-server/blob/master/lib/handlers/authenticate-handler.js#L111-L122

https://github.com/oauthjs/node-oauth2-server/blob/master/lib/handlers/authenticate-handler.js#L141-L147

So it's not clear if it's a bug in SSOwat or OAuth module ...

But anyway, I think a simple fix would be to add an option similar to `unprotected_uri` that could be called `dont_inject_auth_header_uri` to disable the Authorization header injection for these.

That of course raises the bigger question of how we're supposed to support SSO support for these app since it really is dependent on Basic HTTP auth support in the upstreams...

**Comment by yalh76** [comment]
After thinking and diving into HTTP Authentication: https://fr.wikipedia.org/wiki/Authentification_HTTP
It seems to me that it's doing its job.
If the apps is installed as private, SSOWAT injects Authorization header.
The app does its works with the header, trying to authenticate the user using login and password provided in the header.

But when LDAP authentication is not implemented in those apps, it raises an error.

So as you proposed there are two options to manage apps using HTTP Authentication but not having LDAP authentication implemented:
1. Don't allow them to be installed as private until LDAP authentication is implemented.
2. Having a way to disable SSOWAT HTTP Authentication injection with a `dont_inject_auth_header_uri` stuff

For information LDAP authentication is:
- ready for [mastodon_ynh ](https://github.com/YunoHost-Apps/mastodon_ynh/pull/165)
- available for [bitwarden_ynh](https://github.com/YunoHost-Apps/bitwarden_ynh/issues/4)
- on the way for [peertube](https://github.com/Chocobozzz/PeerTube/pull/1626)

So I don't know if it's better to add the `dont_inject_auth_header_uri` stuff, that could add complexity to SSOwat and YunoHost or wait for those apps to have LDAP implemented

**Comment by alexAubin** [comment]
Hmmm and can you confirm that you can't reproduce the issue on Mastodon's branch that add LDAP support ?

**Comment by yalh76** [comment]
> 
> 
> Hmmm and can you confirm that you can't reproduce the issue on Mastodon's branch that add LDAP support ?

My bad... 

Just tested with the LDAP support on a private instance and there is still an error: `401 Le jeton d'accés n'est pas valide`

To be sure, also tested with the LDAP support on a public instance and no error...

**Comment by zamentur** [comment]
Could be disable by adding a if here:

https://github.com/YunoHost/SSOwat/blob/12412cc6c89083b185d627e2832539e54adec25e/helpers.lua#L512

**Comment by yalh76** [comment]
well, I found it:
when removing https://github.com/YunoHost/SSOwat/blob/12412cc6c89083b185d627e2832539e54adec25e/helpers.lua#L506-L509 the errors goes away

**Comment by yalh76** [comment]
There are now two open PRs to let solve that issue :)

**Comment by jedie** [comment]
Think basic auth should be disable as default or completely removed.

Because i think it's a security problem: If a cookie hijacking is possible: the attacker gets the plain text user password. Because It's simply stored in the cookie.

Another way: A user doesn't clean the browser cache on a "shared" or "public" device... Yes, is a generic problem. The attacker can simply take over the session. But usually he can't get the clear text password and sometimes a password reset also needs additionally verification.

**Comment by alexAubin** [comment]
Thing is, that Authorization header doesn't come from (nor is stored on) the client's side ... It's only happening between SSOwat and the app

**Comment by jedie** [comment]
Whoops. That's right. Sorry.

**Comment by alexAubin** [comment]
This issue is solved in 4.1
