### ISSUE TITLE
Yunohost is broken on RPi 0 and 1 because metronome builds are not armv6 compatible

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1423]
Basically you can flash the current RPi ISO and use it on RPi 1 and 0, but `metronome` and `metronomectl` will return `Illegal instruction`

I heavily suspect this to be related to our `armhf` builds to be only `armv7` compatible (RPi 2 and 3) but not `armv6` compatible (RPi 0 or 1).

- It's not straightforward for me to know how to create `armv6`-compatible build with vinaigrette (our debian build toolchain) ... Basically the way it's done is to run in a cross-arch deboostrap thing created here https://github.com/YunoHost/vinaigrette/blob/master/images/make-images#L25 and there's stuff on the internet saying default Debian stuff are not compatible armv6 anyway.
- Or maybe we could tweak Metronome's building sequence with gcc and stuff with the right option to create an armv6-compatible binary idk ?
- Oooor another option is to build a special ISO image for 0 and 1 that would rely on armel instead of armhf (though that would likely be even slower than armhf?) (and I don't even know how to do this using [our current image build chain](https://github.com/yunohost/rpi-image))
- A dirty workaround also is to replace the `metronome` and `metronomectl` binaries to `/bin/true` so that no issue is triggered during upgrades because of metronome service failing to start

So I'm a bit stuck with this so far ¯\\\_(ツ)\_/¯

**Comment by arthurlutz** [comment]
Do you have some sources of "default Debian stuff are not compatible armv6 anyway" ? 

Maybe the armbian https://www.armbian.com/ community can be of some help for the build system, they have a forum  https://forum.armbian.com/ where we can ask for some help.

In the same category of ideas, would building against https://raspbian.org/ help ? 

Do you have some documentation about "would likely be even slower" ? 

I'm not sure I understand the hack to `/bin/true`, does this "Illegal instruction" happen only on upgrade procedure ? 

I have some hardware to help test out if needed.

**Comment by ei8fdb** [comment]
I've got a Raspi 0 I can use to test. Please provide steps tho' :)

**Comment by alexAubin** [comment]
Hmmm not sure I remember everything exactly, but I believe you can : 
- follow the usual installation procedure on your RPi
- I expect it to fail at some point during the installation of packages because it's not able to start metronome (c.f. the "Illegal instruction thing)
- At this point you might perform the following (untested!) dirty hack : 

```bash
mv /usr/bin/metronome{,.bkp}   # Move the real metronome binary to somewhere else
mv /usr/bin/metronomectl{,.bkp} # Same for metronomectl
ln -s /usr/bin/true /usr/bin/metronome # Link 'true' (a dummy program that always work) to metronome
ln -s /usr/bin/true /usr/bin/metronomectl # Same for metronomectl
```
- Relaunch the install script and it should be working (though the metronome stack will in fact not be running even though the metronome service will appear to be started)

**Comment by ei8fdb** [comment]
FWIW: For those interested in trying Yunohost on a Raspberry-Pi, you'll also need raspbian image with a kernal older than 3.12 (raspbian-2013-12-24).

You can download it from [official raspbian image mirror](downloads.raspberrypi.org/raspbian/images/raspbian-2013-12-24/).

**Comment by alexAubin** [comment]
Today a user came in with a RPi1, we also realized that unscd was failing (hence postinstall couldnt be ran) because our custom build is also not compatible with armv6 either. It threw a segmentation violation when trying to start it ...

**Comment by p3k** [comment]
This issue is now being open for almost one year – should I consider this a sign that RPis of the first generations are not fully supported by YunoHost, anymore, and thus some things just won’t work with these?

**Comment by alexAubin** [comment]
Well yes the topic explicitly says "Yunohost is broken for RPi 0 and 1" ... Though it should technically be fixable, but we need somebody who understands cross-arch builds for arm to understand why our build is compatible armv7 but not armv6 etc...

**Comment by p3k** [comment]
just for the record: i ran the buster migration on my system which was affected by both, the metronome “illegal instruction” and the nscd “segmentation fault” issues.

afterwards at least the nscd issue seems to be resolved:

```plain
# nscd -V
unscd - nscd which does not hang, v.0.53
```

**Comment by alexAubin** [comment]
Ah yes because now we take (u)nscd back from the official/vanilla debian repository ... still metronome is built by us which triggers the issue ... I guess that could be indirectly solved by making metronome/xmpp optionnal lelz

**Comment by p3k** [comment]
> Ah yes because now we take (u)nscd back from the official/vanilla debian repository ... still metronome is built by us which triggers the issue ... I guess that could be indirectly solved by making metronome/xmpp optionnal lelz

or could i try to compile it on my rpi box? (assuming it does not take forever…)

**Comment by alexAubin** [comment]
We're discussing this with some folks and got some technical clarifications. 

On Debian's wiki here : https://wiki.debian.org/RaspberryPi we find that : 

>The CPU in the Raspberry Pi 1 and Zero implements the ARMv6 ISA (with VFP2) and is thus incompatible with the Debian armhf port baseline of ARMv7+VFP3 and ARM hardware-floating-point ports for other distributions, which all have the same baseline. It is compatible with Debian armel (armv4t, soft(emulated) FP), but floating-point tasks will be slow when running the Debian armel port. (This doesn't stand for newer families) 

I'm not 100% sure why/how RPi 0/1 are not exploding at boot time due to every low-level packages being compiled for armhf compared to armel then ... though my guess is that RPi are usually configured with apt repos pointing to RPi's repo instead of official debian's ones...

That still doesn't really answer either the question of how to fix the whole situation though ...

**Comment by Linkid** [comment]
Hi !

I have a RPi 0 with YunoHost 4.0. It was working fine until I updated it to v4.1. I had an `Illegal instruction` during the debian postinstall: `/var/lib/dpkg/info/yunohost.postinst: line 6: 24630 Illegal instruction yunohost tools regen-conf --output-as none`.

@alexAubin helped me with this issue. It comes from `libminiupnpc17:armhf 2.1-1`, which is a new package, and more specially from `python-miniupnpc 2.1-1`. To find it, I executed this command: `python -c 'import miniupnpc` and got `Illegal instruction`. This python module is called by `yunohost tools`.

So, to solve this issue, I had to comment [`import miniupnpc`](https://github.com/YunoHost/yunohost/blob/debian/4.1.5/src/yunohost/firewall.py#L28), but he told me that it is a piece of tape I need to do for each upgrade:
```bash
    sed -i 's/import miniupnpc/#import miniupnpc/g' /usr/lib/moulinette/yunohost/firewall.py
```

Another solution would have been to downgrade the `python-miniupnpc` package to v1.9, but it was not available.
Thank you @alexAubin, now, it is working fine for me :).

**Comment by esijg** [comment]
I just wanted to add to this conversation that I seem to be running into this on an early Raspberry Pi 2 also. (Illegal Instruction during postinstall. Seems to be Metronome failing)

**Comment by zyphlar** [comment]
It should be obvious, but it wasn't to me: a Raspberry Pi Model B+ is apparently an "RPI 1" and thus suffers this issue. I guess I forgot that "B+" and "3 B+" were very different.

**Comment by alexAubin** [comment]
Note that because of recent changes in the way we build packages, this issue may have vanished, but to be confirmed.

**Comment by ABelliqueux** [comment]
Using 'yunohost-buster-4.1.7.2-rpi-stable.img' on a Rpi B+ with metronome 3.14.1 and 3.14.5 , I can confirm that trying to run either `metronome` or `metronomectl` results in an `Illegal instruction` message.

In order to solve the issue and build metronome (~5 min build time) on the B+, here are the steps I took via ssh: 

 * Install build dependencies : `apt-get install -y liblua5.1-0-dev libidn11-dev libssl-dev`
 * Clone metronome repo : `git clone https://github.com/maranda/metronome.git`
 * Change into repo's folder: `cd metronome`
 * Configure script : `./configure --ostype=linux --prefix=/usr --with-lua-include=/usr/include/lua5.1 --with-lua=/usr/bin/lua5.1 --with-lua-lib=/usr/lib/arm-linux-gnueabihf --lua-suffix=5.1 --sysconfdir=/etc/metronome --datadir=/var/lib/metronome`
 * Build binaries : `make`
 * Install system wide : `make install`
 * Restart metronome service : `systemctl restart metronome.service`

As for the python-miniupnpc issue, I was able to install 1.9 from pip :
  * `sudo pip install miniupnpc==1.9`
  * Restart the service using `systemctl restart yunohost-firewall.service` .
  
Should I update the wiki with these instructions ?

**Comment by maranda** [comment]
@ABelliqueux why are you using lua5.1 instead of 5.2?

**Comment by ABelliqueux** [comment]
@maranda I think this is the version shipped on that specific yunohost image with no upgrade/update ?
In any case, adapting the steps to use 5.2 or 5.3 should work too.

Same for miniupnpc, I used 1.9 because of what @Linkid said above, but maybe using the last version will do too (i.e `pip install miniupnpc` to install 2.2.3 ).

**Comment by maranda** [comment]
@ABelliqueux not 5.3 Metronome does not support that yet, but using 5.2 is desiderabile atm.

**Comment by orlammd** [comment]
Hi!
In my case, it didn't work with lua5.2 (metronome/usr/bin/env/lua5.2 doesn't exist, or something like this), got to get back to lua5.1, and it seems to work.
As far as miniupnpc is concerned, I didn't manage to get it working with 2.2.3. Tried with pip install miniupnpnc, than pip3 install miniupnpnc, and eventually with pip install miniupnpnc==1.9 'still doesn't work : https://paste.yunohost.org/uqugukedit), and in the end: pip3 install miniupnpnc==1.9 which seems to work.

**Comment by alexAubin** [comment]
Closing because supposedly this should be solved now that we refactored our build chain
