### ISSUE TITLE
Display multiple log files for a systemd service

### ISSUE THREAD

**Issue by Jibec** [YunoHost/issues#1425]
The example package includes the ynh_use_logrotate in the installation script.

The behaviour is as follow:
```
If no --logfile is provided, /var/log/${app} will be used as default.
logfile can be just a directory, or a full path to a logfile :
/parentdir/logdir
/parentdir/logdir/logfile.log
```

This is very handy in my situation, as I have two systemd services, one of them is celery how have multiple log files

Could we have the same behaviour for the command `yunohost service add `?

Thanks for your help!

**Comment by alexAubin** [comment]
As far as I know you can already specify multiple log files when using `yunohost service add`...
