### ISSUE TITLE
Error: moulinette.core translate - unable to retrieve key 'service_description_xxx' for default locale 'en'

### ISSUE THREAD

**Issue by Jibec** [YunoHost/issues#1426]
hi, when an application installs new systemd services, we get moulinette.core errors directly displayed to user:

```
Error: moulinette.core translate - unable to retrieve key 'service_description_weblate-celery' for default locale 'en'
Error: moulinette.core translate - unable to retrieve key 'service_description_weblate' for default locale 'en'
Error: moulinette.core translate - unable to retrieve key 'service_description_postgresql' for default locale 'en'
```
I checked in ci-apps, this issue with gitlab, funkwhale (which I maintain), biboumi, anfora...

While providing the description for PostgreSQL probably should be part of core, it would be really welcome to know how to feed the moulinette with the correct string. Could we have a new parameter for the ynh_add_systemd_config helper? Or eventually, could it use the description inside the systemd file?

Whatever you like, as long as the user don't see red message for something he can't do anything about ;)

thanks for your help

**Comment by alexAubin** [comment]
Is this only on DEBUG mode or also in regular mode o.O ?

**Comment by Jibec** [comment]
as far as I know, in regular mode also

**Comment by alexAubin** [comment]
I think Bram tweaked the message a few weeks ago to make it looks less scary. Also after 3.8, packagers will be advised to specify a `--description` when using `yunohost service add` (which can already be done now ...) :

https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/service.py#L82
