### ISSUE TITLE
check that port 9418 is opened for "git://" protocol for the apps needed it

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1429]
Yet another edge case, an application installation failed because of a too restrictive firewall that was blocking on OUT the port 9418 (it blocks a lot of things by default), turns out it broke "git clone git://" which was needed for some application installation.

I don't know how/when but it would be good to check or add that as a requirements for applications that needs it to run (or better: only uses "http://" "https://" for git)

The situation is this cryptic installation failure: https://github.com/YunoHost-Apps/pleroma_ynh/issues/91

**Comment by alexAubin** [comment]
Hmf closing because this is a super technical edge case :|
