### ISSUE TITLE
Storing app data on external storage

### ISSUE THREAD

**Issue by Qwertie-** [YunoHost/issues#1433]
I am running yunohost on a raspberry pi and I would like to have all app data stored on my nas. I can mount the nas using sftp or any other way but I am wondering what the best way to make sure that all app data is on the nas and not break anything.

My first thought is to copy the entire /home to the nas and have that mounted to /home on the pi. Any thoughts on this, or is there a better way?

**Comment by Plumf** [comment]
Hi @Qwertie- maybe YunoHost documentation resolve your ask ? 
https://yunohost.org/#/app_nextcloud For the moment they are juste information to add data stored.You're very lucky.

**Comment by Qwertie-** [comment]
I did look at that first but it looks like it just adds a new folder in nextcloud and doesn't make the root nextcloud folder use external storage. It also shows every user the same data rather than having it split by user. I also have other apps I want on external storage like transmission which do not have an external storage feature.

**Comment by alexAubin** [comment]
Closing in favor of https://yunohost.org/fr/external_storage
