### ISSUE TITLE
[DOC] Differences between the page isp.md and isp_fr.md problematic

### ISSUE THREAD

**Issue by jeantest-git** [YunoHost/issues#1434]
**EN**
When connecting to the isp.md page the wiki will use the isp_en.md page if it detects the system in French. As a result, it is not possible to see the page information, which is different, between the two pages.
While the two pages do not have the same information on the ISP at all.

**FR**
Alors que les deux pages n'ont pas du tout les mêmes informations sur  les F.A.I. En se connectant à la page isp.md le wiki utilisera la page isp_fr.md si elle détecte le système en français. Par conséquent, il n'est pas possible de voir les informations de page, qui sont différentes, entre les deux pages.
Bien que les deux pages ne contiennent pas du tout les mêmes renseignements sur le FSI.

**Comment by cyxae** [comment]
This has been quite fixed because there is now a help message saying we can go on the EN page from the FR one, and from the FR one to the EN one
https://yunohost.org/fr/isp

**Comment by alexAubin** [comment]
Yup let's close this issue then, thanks for the heads up @cyxae :+1:
