### ISSUE TITLE
Fail2ban failt count is way too harsh, should make it at least 10 instead of 5

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1437]
We regularly have people reporting they "mysteriously" cannot log in their server ... we should really consider making the fail2ban configuration a bit looser. Maybe make it a setting so that people can easily tight it up if they want to.

c.f. yet another report today of nicofrand : 

>wow violent le fail2ban chez moi, je tente 3-4 fois de me logger à mon nextcloud via l'app de prise de notes, bam je suis banni de mon serveur en HTTPS

**Comment by ketsapiwiq** [comment]
I totally agree, fail2ban is supposed to protect from brute-forcing issues that involve hundreds and thousands of intents. Making the threshold as high as 10 would not significantly increase risks. Being banned by fail2ban is very hostile to a beginner user that don't know fail2ban as it takes time to figure out why they totally lost access to some port.

**Comment by alexAubin** [comment]
Solved thanks to https://github.com/YunoHost/yunohost/pull/802 from @doxxfr !
