### ISSUE TITLE
Weblate: find a way to generate screenshot for translation strings

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1440]
Apparently that can be uploaded by hand by admin but we really should generate that instead.

I don't know how feasible it is to do that but that would give a lot of context to users as seen here: https://hosted.weblate.org/translate/onionshare/translations/nb_NO/?checksum=4f7f3b23bf2d8335

The ideal would be to find a way to auto generate that, we could map actionsmap and source code using redbaron or similar and find a way to execute said function and take a screenshot.

![2019-09-17-191720_918x962_scrot](https://user-images.githubusercontent.com/41827/65064025-ce7ec800-d97f-11e9-9859-132d44c4936d.png)

**Comment by alexAubin** [comment]
Closing because honestly we're not going to do that unless somebody somehow volunteers specifically for this...
