### ISSUE TITLE
[Doc] Reporter problématique connue nextcloud & shaarli

### ISSUE THREAD

**Issue by Plumf** [YunoHost/issues#1443]
Suite à ce fils de discussion du forum. Reporter ce problème connu dans la documentation.
https://forum.yunohost.org/t/resolu-mise-a-jour-de-nextcloud-impossible/9057/6

**Comment by alexAubin** [comment]
N.B. : Il ne s'agit pas specialement d'un bug entre nextcloud et shaarli mais qui est general à n'importe quelle installation où il y a shaarli ... Perso j'aimerais qu'on investisse l'énergie dans fixer le bug pour de vrai à sa source plutot que de documenter ça comme si ça allait être un truc sur le long terme ...

**Comment by Plumf** [comment]
:+1: Oui je comprend totalement, par contre la je ne peux pas aider... Je ferme l'issue
