### ISSUE TITLE
We need a CI for the core

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1444]
Now that we're starting to have quite a number of tests for the moulinette and the core. Yet it's boring and long to launch them manually just to check that unrelated stuff didnt break.

Not necessarily to be ran on each commit or each branch, but having a test running every night on unstable would already be quite nice, and then possibly requesting a test to be ran on a specific branch easily would be epic.

Items to test (in a single sequence might be easier):
- fresh install using the install script
- postinstallation
- running core and moulinette tests

**Comment by decentral1se** [comment]
Yes, very good that you bring this up.

As far as I understand, the first thing to agree on is the infrastructure to run it on.

The current running discussion seems to be how to get this working under LXC or Virtualbox/Vagrant. As the YunoHost CI already uses LXC, that seems to be a winner?

**Comment by alexAubin** [comment]
I dunno, there's no clear plan so far I believe ... To me naively it could be "straightforward" to just reproduce something similar to what's done for the CI-apps : 
- We have `ci-core` LXC inside bearnaise
- We could enable the nested option (as for ci-apps) to run sub-lxcs inside
- Maybe reusing yunorunner if it can be used for jobs different than the app CI (I don't know enough about these tools)
- The actual test would start a fresh stretch LXC, run the install script with unstable branch
- Run the postinstall
- Run code and moulinette tests inside
- Report whatever goes wrong with big red spooky messages on the chat

**Comment by alexAubin** [comment]
Solved by @kay0u \o/

Epic core CI is epic
