### ISSUE TITLE
Images are outdated

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1448]
Right now they're still in 3.4, which isn't dramatic but still a lot of things changed since then, including the upgrade mechanism and it's not obvious for first user to know how to upgrade the system

**Comment by frju365** [comment]
@alexAubin : How does the mechanism to build img and iso images work?

**Comment by alexAubin** [comment]
That's kinda complex to setup but basically if you want to dig into this you should look into https://github.com/YunoHost/arm-images and https://github.com/YunoHost/rpi-image

**Comment by alexAubin** [comment]
Closing because things are now a bit more up to date (except ARM images but meh)
