### ISSUE TITLE
Help packaging Offline Internet Archive for Yunohost 

### ISSUE THREAD

**Issue by mitra42** [YunoHost/issues#1453]
I'm now starting to package the offline Internet Archive app for Yunohost ... its somewhat tough given the lack of documentation so here are some questions that arise .... I'd edit the docs myself but I'd just be guessing the answers to the questions ...

**Comment by mitra42** [comment]
**manifest.json** as described on https://yunohost.org/#/packaging_apps_manifest_en

1. Name: What are the allowed character set, i.e.. should it be "internetarchive" "Internet Archive" or "InternetArchive" 
2. id; Same question - what are the rules for ids, the example is "ynhexample" but does that mean my id should be "ynhinternetarchive" or just "internetarchive" or are both of those too long ? 

3. version: says `version of the package built from the upstream version number and an incremental number for each change in the package without upstream change. Example "1.0.1~ynh7". Must be a string.`
Really ? Presuming by "upstream" you mean the github repo for dweb-mirror, we do a minor release every few days, surely you don't want a new yunohost manifest pushed every few days ?

4. url: Of what - the documentation site, the github repo, or what ? 
5. requirements: The current version is not in the Readme at https://github.com/YunoHost/yunohost so how to find it ? I'm presuming that is what to put here as I wont be able to test against earlier versions .

**Comment by maniackcrudelis** [comment]
1. Whatever you want, except maybe special characters I don't think there's not allowed characters. Which is why nothing is said about it.

2. https://github.com/YunoHost/doc/blob/master/packaging_apps_guidelines.md#yep-11

3. Yep really...
You're free to not update your app every day for each minor release though.

4. From https://yunohost.org/#/packaging_apps_manifest_en
`    "url": "http://roundcube.net/",`
What does it look like ?
Aside of that, you can put whatever url you want.

5. You're supposed to put the version with which you tested your app. Usually the last version indeed. But if I can tell you what is the last version, I can't tell you which one you're using for your tests.

**Comment by mitra42** [comment]
Thanks @maniackcrudelis - especially for the pointer to the guidelines, the problem is that if you follow these instructions through step by step you get to the box "Manifest" - follow that to the https://yunohost.org/#/packaging_apps_manifest_en page, which has no mention of the guidlines, since they are linked from the previous page , far further down. I'll do a PR to link them to somewhere where someone will see them BEFORE hitting the questions.  I'll go through your answers and the guidelines before asking further questions.....

**Comment by mitra42** [comment]
@maniackcrudelis  - thanks for the answers to my questions. 
#1 (name) and #2 (id) thanks

#3 - ok - so the Yunohost version is unfortuantely likely to get significantly behind the live version, and have bugs that are already fixed and released. 

On other platforms like Internet In A Box for example their scripts are always going to get the current (npm) published version.

**Comment by mitra42** [comment]
#4 - OK
#5 - Understood, I'm running on a RPI with the latest version, but how do you get the current version of yunohost, I've looked for it and can't find it.

**Comment by maniackcrudelis** [comment]
3. We're more in a debian style, we rather prefer to have a version that works for sure than the last available version that might not work but is nonetheless the last available so obviously better.
Also, using a determined version of the upstream app allow us to secure the download with a checksum. So we can be sure that the final user will get what the packager made.

5. Either on your admin panel, in the bottom of the admin page you'll find `Powered by YunoHost x.x.x.x` or by `yunohost -v` in cli.

**Comment by mitra42** [comment]
Thanks for the version info - maybe put that on the manifest docs ? 

Of course, it doesn't mean yunohost will have a version that works for sure, it means its guaranteed to have bugs that have been fixed in later minor-releases, and guaranteed to be unsupported (because it wont be up to date). 

I can understand why you would want to not move to major version changes, but not allowing a package to upgrade to minor bug fix versions seems nuts to me, but I guess that is your choice. 

Most other projects seem to have moved to semver versioning by now (e.g. the package.json files in Javascript) where the API is supposed to be stable if you are matching ^x.x.x (i.e. auto upgrades from 1.2.3 to 1.2.4 but not to 2.0.0)

**Comment by alexAubin** [comment]
Closing because apparently the app was packaged and submitted, no discussion here since 3 years
