### ISSUE TITLE
Packaging guidelines Yep 16

### ISSUE THREAD

**Issue by mitra42** [YunoHost/issues#1455]
**Yep 1.6** says to join apps@list.yunohost.org, however it doesn't say how to join ! And list.yunohost.org doesn't respond as a web page. Mailing lists have many conventions to apps@list.yunohost.org with subject line subscribe for example failed 

Yep 1.6 also said to go to  the forum's Apps category at https://forum.yunohost.org/c/apps-packaging but that link is broken and should be https://forum.yunohost.org/c/contribute-room/apps-packaging I've submitted a PR for that one but can't guess the mailing list one. (and am therefore still not subscribed to it :-(

**Comment by alexAubin** [comment]
Sorry about the mailing list thing, it should be removed as we stopped using those like 2 years ago :/

**Comment by mitra42** [comment]
Thanks - its really MUCH harder to package an app than necessary, I can see why so many are in the "notworking" stage as I guess people hit the many (documentation) issues I've hit on just the first stages and give up.  

Its not made easier by having to follow both the Yep guidelines, and https://yunohost.org/#/packaging_apps_en in parallel at the same time, both of which have incorrect information and bad links. I'd fix them, but as with this one the fixes in may cases aren't obvious to a yunohost newbie.

**Comment by decentral1se** [comment]
Yeah, fair enough poinrts @mitra42. I was very scared away in the first stages for packageing apps but once I got around these initial stumbling blocks, I realised how simple, powerful and flexible it is to package apps in YunoHost. I think this is also reflected in the amount of packages that are available (taking status/stage out of account here). Thanks for making this feedback clear on a ticket. We need to work on the documentation.

**Comment by mitra42** [comment]
Yes - we  hit so many issues, first getting yunohost to install, and then just these first few steps of app packaging (between out-of-date; out-of-order; duplicate and bad links), that I think we'll de-prioritize yunohost till the docs get fixed.   (The version lock issue is also a big detriment, as anyone using Yunohost would be using a buggy and unsupported version of our package).

**Comment by alexAubin** [comment]
Closing because the mention of apps@list.yunohost.org got removed at some point ... and the whole YEP list is obsolete as stated at the top of the page anyway ...
