### ISSUE TITLE
The documentation should not assume people will know how to start and use a terminal

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1457]
Especially on Windows. We should have a page explaining how to install MobaXterm (and not that goddamn PuTTy) and how to effectively use it to connect through SSH to a server and write basic commands. This should then be linked from the various places of the documentation where we expect people to connect to their server through SSH

**Comment by frju365** [comment]
I've begun something. I push, I think this evening or tomorrow and make a PR.

**Comment by alexAubin** [comment]
Closing because the doc got refactored since then and it's a bit better I suppose
