### ISSUE TITLE
[rspamd + clamav] add antivirus in the core!

### ISSUE THREAD

**Issue by pedro-nonfree** [YunoHost/issues#1459]
I'm surprised that there is no antivirus by default in yunohost !

I think it is very easy to configure when you follow [this FANTASTIC guide](https://workaround.org/ispmail/stretch/filtering-viruses-malware/)

I will put here steps after a fresh yunohost installation:

    sudo apt install clamav clamav-daemon

add file `/etc/rspamd/override.d/antivirus.conf` with content:

```
clamav {
  attachments_only = false;
  symbol = "CLAM_VIRUS";
  type = "clamav";
  action = "reject";
  servers = "/var/run/clamav/clamd.ctl";
}
```

reload rspamd

    service rspamd reload

(I tested and it worked!)

**Comment by decentral1se** [comment]
I'm for this. We'd also need to document how to manage it.

**Comment by HyperCriSiS** [comment]
I would prefer Yunohost switching to this mailserver solution which has everything needed:
[https://github.com/hardware/mailserver](https://github.com/hardware/mailserver)

**Comment by HugoPoi** [comment]
I don't know what to do, but there is now https://mailcow.email/ as the same approach as https://github.com/hardware/mailserver but lot of complexity to put this in the Yunohost project.
* Yunohost is not builded with docker in mind
* Mailcow and mailserver images packaged UI as well as the backend
* There is no API on Mailcow, and no LDAP support for now ...
* Meaning we depends on docker ...

**Comment by pedro-nonfree** [comment]
these days for me is no longer clear to add the antivirus I suggested above (clamav) in the yunohost core (at least, not activated by default), here's why: adding clamav service takes much more RAM (and I failed regulating it) which could let to out of memory episodes for a small VPS of 2 GB of RAM with services such as email server, roundcube (webmail) and nextcloud

**Comment by tootbrute** [comment]
Don't think antivirus is necessary. Most people will use Nextcloud, and can install an antivirus app in that. Most people are most likely going to get a virus through their personal files, not on the main system.

**Comment by Neustradamus** [comment]
Antivirus is needed to the mailserver...

**Comment by zeroheure** [comment]
Antivirus can be useful for spam detection, too.

Regarding mailserver, Caddy and Maddy could be a solution in the future. [Caddy](https://github.com/caddyserver/caddy) is an https application server, and [Maddy](https://github.com/foxcpp/maddy) an integrated MTA/MDA (imap only) using Caddy. Both written in Go and easy to setup (and supporting rspamd). But there is no hurry, Postfix is a well tested and very secure mail server.

**Comment by alexAubin** [comment]
Considering we're removing rspamd from default install (though we'll have a setting to easily add it from the webadmin), we're not gonna integrate an antivirus in the default core. Could be added to the app wishlist though I guess.
