### ISSUE TITLE
Default DNS in RPi images is 8.8.8.8

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1460]
/o\
https://forum.yunohost.org/t/probleme-dns-brique/9105/8

I have checked by mounting the image for rpi and /etc/resolv.conf contains 8.8.8.8 instead  of 127.0.0.1

**Comment by alexAubin** [comment]
I don't think it's a bug, I think it's a feature : 
- before the postinstall, dnsmasq is not yet configured
- so we can't rely on our mechanism where we have a list of 10+ friendly resolver
- instead, we are constrained to the regular /etc/resolv.conf format, which can only contain 2 resolvers at most
- surely we could choose 2 friendly resolver, but then if they happen to be down (as it happens regularly according to my monitoring) that will break the install
- and anyway is this really so much drama to have 8.8.8.8 as resolver for like the 5 first minutes until the person runs the postinstall ...
