### ISSUE TITLE
Support other domain in .local

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1464]
Some users want to create other domain using bonjour protocol like "something.local" or "wikijs.yunohost.local"

The feature could be each .local domain added could be acrtivated and announced with bonjour protocol.

See https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/templates/avahi-daemon/avahi-daemon.conf

**Comment by zamentur** [comment]
An idea: may be if we announce also "non local" domain with avahi on local network, may be it allows to bypass hairpinning issue...

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost/pull/1112
