### ISSUE TITLE
Ability to display a public app portal (to list public apps which doesn't require a user account)

### ISSUE THREAD

**Issue by kalak-sudo** [YunoHost/issues#1467]
I have searched, and I found nothing about it.

I want to everyone access my yunohost, without user account.

How do I achieve that?? 

Thanks in advanced.

**Comment by decentral1se** [comment]
@kalak-sudo, which part of your YunoHost? The apps installed in them? In that case, you can choose to make your applications public which requires no YunoHost user account to view them.

**Comment by kalak-sudo** [comment]
> @kalak-sudo, which part of your YunoHost? The apps installed in them? In that case, you can choose to make your applications public which requires no YunoHost user account to view them.

I mean the dashboard with the "cards". I am attaching a screenshot.

![Screen Shot 2019-10-14 at 00 14 37](https://user-images.githubusercontent.com/55482263/66723314-c9deef80-ee17-11e9-9b6e-41a4480aee91.png)

**Comment by decentral1se** [comment]
Oh hmmm, well, the idea behind this dashboard was to have a single log in and then be able to auto-log into these apps through this interface (I think). I know that the SSO doesn't work this way for a lot of apps and you need to log in twice.  So, my point being, this isn't really a part of the design of this YunoHost dashboard and I am not sure what kind of work is needed.

**Comment by Psycojoker** [comment]
Hello,

What you want is somehow a listing of all public available applications (some applications are only available to logged in users), this isn't something that we currently support but it can be easily built using a custom application.

**Comment by kalak-sudo** [comment]
Let's imagine I want to have a **totally public Yunohost**, like a demo for example.

That is what I want to achieve, and it would be great to have an option for this.

Until that option appears officially, how can I achieve it? (editing files, commenting config lines, etc...) @decentral1se @Psycojoker  ?

Thanks in advanced :)

**Comment by Psycojoker** [comment]
As of today I'm not aware of an easy way to do that.

The easiest is to do your own html page by copy SSOWat page html and hosting it using simple web app.

You can also write some code that talks to yunohost-api the same way that the admin do that, but it's way more complicated (but more generic/powerful)

**Comment by decentral1se** [comment]
> The easiest is to do your own html page by copy SSOWat page html and hosting it using simple web app.

True ^^^, you could use https://github.com/YunoHost-Apps/staticwebapp_ynh for that.

**Comment by kalak-sudo** [comment]
Thanks for everything :)

**Comment by alexAubin** [comment]
Eeeeh shouldn't we keep this issue opened ? The ability to display the public apps would definitely be a relevant and interesting feature to have, if anybody has time and energy to implement it ...

**Comment by kalak-sudo** [comment]
Ok, sorry! It would be a great feature, no doubt! :)

**Comment by zamentur** [comment]
On this link an example of public app portal for CHATONS sans-nuage.fr

https://sans-nuage.fr/fr/

**Comment by Aeris1One** [comment]
I'm very interested in that ^^

**Comment by alexAubin** [comment]
Related to https://github.com/YunoHost/issues/issues/1848

**Comment by alexAubin** [comment]
Done in Bookworm SSO/portal refactoring
