### ISSUE TITLE
Rollback "Redirect domain root to this application"

### ISSUE THREAD

**Issue by kalak-sudo** [YunoHost/issues#1468]
I have enabled this option for an app, and now I don't want any redirection. 

I have tried to rollback this option, but I can't. Is there a way to do it? 

Thanks in advanced,

Kalak

**Comment by alexAubin** [comment]
You mean the "default app" thing ? Unfortunately that's not possible right now from the yunohost webadmin / cli (kinda related: https://github.com/YunoHost/issues/issues/125 )

But you can manually edit `/etc/ssowat/conf.json.persistent` and you should find the corresponding rule and should be able to remove it.

**Comment by kalak-sudo** [comment]
Exactly, resolved. I erased the content of that file and now it has the default configuration.

Until it is easily done in the admin panel, I think this info should be in the README or somewhere in the GUIDE. 

Or even better: Just right next to the button where it says "Make default", so everyone can do it without asking like me.
