### ISSUE TITLE
[Web admin interface] Failed to parse route Failed to parse arguments: Error 500

### ISSUE THREAD

**Issue by sy6sy2** [YunoHost/issues#1470]
Hi,

I not really often use the web admin interface but notice today that this one is completely broken.
I can see the root menu of https://domain.fr/yunohost/admin/#/ but whenever I click on a sub menu nothing happen and I get this error:

```
Action
    Failed to parse route Failed to parse arguments

Trace
   Error: 500 Internal Server Error
    Sorry, the requested URL 'http://domain.fr/diagnosis?locale=fr'
               caused an error:           
       Internal Server Error
```

Is it a known issue?

Thank you!

**Comment by alexAubin** [comment]
Hmmm do you get the error before or after clicking the button?

**Comment by sy6sy2** [comment]
Both

Edit: No error with Outils and Sauvegarde

**Comment by sy6sy2** [comment]
After a reboot the issue seems to not appear anymore...
