### ISSUE TITLE
Question: Raspberry Pre-installed images v3.6

### ISSUE THREAD

**Issue by mcorossigo** [YunoHost/issues#1472]
Hello,
in https://yunohost.org/#/images the last Raspberry Pi image available is versioned v3.4.2

Is there any plan to update it? Is https://github.com/YunoHost/issues/issues/1423 a blocker for it?

I'm asking to be able to choose between waiting for the updated version or installing it by hand following https://yunohost.org/#/install_manually

Thanks!

**Comment by alexAubin** [comment]
As mentionned on top of the page in https://yunohost.org/#/images : 

>N.B. : Even if the image does not corresponds to the latest version of YunoHost, you can still use it and do a regular system upgrade after setting up!

There's basically no difference between doing this, or using a more recent image (though you get rid of the upgrade time), or installing it manually on top of debian

**Comment by alexAubin** [comment]
Closing because RPi image is now up to date (4.0)
