### ISSUE TITLE
Add "hairpinning mode" to Yunohost to help with common configuration issues

### ISSUE THREAD

**Issue by Bugsbane** [YunoHost/issues#1475]
My router has hairpinning issues.

Despite this, I am able to successfully host a number of domains using Yunohost. This took a lot of research online to find a few small, simple command line flags that got everything to work.

The trouble is that without this knowledge, setup fails in the web UI. There are no clear error messages or obvious solutions. Most new routers do not support hairpinning any more, so most new users with new routers are likely to hit these errors when first setting up Yunohost. Few are likely to do the necessary research before giving up.

For example, trying to set up a Lets Encrypt certificate through the web interface fails if the router isn't capable of hairpinning. I the user looks at the error bar across the top, it says there may be a misconfiguration or hairpinning issue, but no potential solutions are offered. As far as the user is concerned, it just fails.

All the installer needed to do, to bypass this, is test if hairpinning issues are present and i so, use the --no-checks flag when installing SSL certiicates using the yunohost tool.

It's a similar story with adding domains.

Or removing them.

Or... well, you get the point.

Anyway, my suggestion is to automatically test for hairpinning issues (eg. if domain is reachable from a remote server, but not from the local server - there's probably a hairpinning issue). If hairpinning issues are detected, set a "hairpinning mode" flag, which then gets the web interface to use the necessary flags for operations to succeed (eg. --no-checks when installing ssl certificates)

This would result in all users with recent routers that have common hairpinning issues to have far fewer problems using the web interface to get up and started. This in turn leads to many more first time users feeling that Yunohost "just works" and that self hosting is indeed possible. :)

**Comment by ketsapiwiq** [comment]
I have the same problem on one server (YunoHost is installed in a LXC container and I never found out which `iptables` rules would solve the hairpinning issue). As a result I always have to add a domain through CLI.

Would it be required to use an external server to test if the domain is reachable from a remote server?
Otherwise we could offer an option in the UI to pass `--no-checks` / `--force`.

**Comment by alexAubin** [comment]
>Would it be required to use an external server to test if the domain is reachable from a remote server?
Otherwise we could offer an option in the UI to pass --no-checks / --force.

That's precisely what comes with the new diagnosis system in 3.8 (we diagnose the server / domain exposure using a remote tool on our infra)

**Comment by Bugsbane** [comment]
> we diagnose the server / domain exposure using a remote tool on our infra

Awesome! So what do we do when a hairpinning issue *is* detected?

**Comment by silverhook** [comment]
To add another complication, I gave up on hairpin NAT and instead have static DNS entries on the router to point all the domains on the YunoHost server to its internal IP address.

Should we take into account that too? Currently, my set-up works, but Diagnosis throws warns me about missing hairpinning.

**Comment by alexAubin** [comment]
>Awesome! So what do we do when a hairpinning issue is detected?

Can't really "magically fix the hairpinning issue", but at least the user is informed about it

Closing because assuming this is fixed
