### ISSUE TITLE
Instalation: Can't connect to ssh 

### ISSUE THREAD

**Issue by sucrecacao** [YunoHost/issues#1478]
Yunohost version =  2019-02-18-yunohost-lite.img ( yunohost-stretch-3.4.2-rpi-stable)

After install yunohost on a raspberry pi , I can't connect with ssh on localnetwork.
Ssh is up on the rpi ( show `active` on `service ssh status ).
 On my machine I get with arp-scan:
`192.168.1.133    XX:XX..   Raspberry Pi Foundation`

and form ` nmap -Pn -p 22 192.168.1.133` I get:

```
Nmap scan report for 192.168.1.133
Host is up.

PORT   STATE    SERVICE
22/tcp filtered ssh
```

but when I try `ssh admin@192.168.1.133` or `ssh root@192.168.1.133`
It end up with a timeout error

Any idea what's going wrong ?

**Comment by alexAubin** [comment]
Possibly you got banned by fail2ban ...? What if you retry now (or 10~15ish minutes) ?

**Comment by sucrecacao** [comment]
@alexAubin still not working.
Could this come from the router ?

**Comment by alexAubin** [comment]
From nmap you get: 

```
PORT   STATE    SERVICE
22/tcp filtered ssh
```

according to the doc: 

>Filtered means that a firewall, filter, or other network obstacle is blocking the port so that Nmap cannot tell whether it is open or closed.

So from what you report, it does seems like the port is actually blocked my some sort of firewall ... (which could be anywhere between your client and the ssh server, e.g. your own machine, the router, or the server machine)

Are you able to connect to the web interfaces though ? Possibly, can you try to go in the webadmin, in Services and stop fail2ban ? (At least that would eliminate the hypothesis of fail2ban)

**Comment by sucrecacao** [comment]
When trying to ping I got 
`ping: sendmsg: Operation not permitted`

**Comment by sucrecacao** [comment]
I have the error for all the device connected to the local network.

I think the problem comes from the router

**Comment by Psycojoker** [comment]
> When trying to ping I got
> `ping: sendmsg: Operation not permitted`

That's generally an indication that your firewall is blocking network operations.

**Comment by sucrecacao** [comment]
I ubuntu firewall ufw and it is disable. 
You mean the router firewall ?

**Comment by Psycojoker** [comment]
The firewall of the computer on which you use "ping", "Operation not permitted" means something (often iptables configuration but can be something else) prevents you from doing network operations.

**Comment by alexAubin** [comment]
Closing because that sounds like it was unrelated to Yunohost ..
