### ISSUE TITLE
Firefox error SEC_ERROR_INADEQUATE_KEY_USAGE

### ISSUE THREAD

**Issue by HugoPoi** [YunoHost/issues#1479]
## To Reproduce
1. Install a fresh Yunohost
1. `sudo yunohost tools postinstall -d ynh.local -p AdminPassword`
1. `sudo yunohost domain add seafile.ynh.local`
1. Open https://seafile.ynh.local in Firefox >= 69.0.2

## What happening
* https://ynh.local => Works ok after passing the self-signed exception
* https://seafile.ynh.local => Get `SEC_ERROR_INADEQUATE_KEY_USAGE` error immediately 

## Other info
There is a probleme specific to Firefox SSL check implementation. We might hit an edge case with self-signed chain check.

Related issue on Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1590217

Annoying because firefox doesn't allow bypassing this error.

**Comment by autra** [comment]
I *think* it happens when you recreate your instance, because you change . To bypass this error, I use a fresh firefox profile, see Dana's comment in the bugzilla bug. You need to recreate this profil each time the issuer signing key (?) is reset.

Maybe a workaround would be to have a different CN name each time for self-signed certificate? I don't know if it's possible to make firefox forget about the issuer key.

**Comment by HugoPoi** [comment]
Ok so there is an issue on our side, if I understand correctly, the CA certificate as a CN containing the domain name and it's not good for Firefox.

I confirm that I have `Subject: CN = ynh.local` in the main CA certificate. But I don't know this happen because the config have `yunohost.org` as default value not `ynh.local`.

The related code
https://github.com/YunoHost/yunohost/blob/dde3a19350728c1d1a90171cbae8187e619c04df/data/hooks/conf_regen/02-ssl#L42-L48

## Edit: Additional thoughts about Firefox
I'm not an expert about PKI but there is weird implementation in Firefox, if I understand correctly Firefox take the certificate of the main domain as CA for the other in the Firefox cache (Firefox doesn't make the difference between the CA cert and the server cert I believe )

**Comment by autra** [comment]
Mmhhh I'm not yet convinced it's really a yunohost issue. It does work in chrome... For me it still looks like a bug in Firefox (we should be able to have same DN in issuer and in server certificates if we want to). 

Anyway, I guess we have an acceptable workaround.

**Comment by autra** [comment]
Actually to elaborate, Dana gave us 2 workarounds: one with the current code but with a manual action from the user, and another if we change our issuer DN.
