### ISSUE TITLE
Backup for specific user

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#148]
###### Original Redmine Issue: [148](https://dev.yunohost.org/issues/148)

Author Name: **Scith**

---

Hello,
Would it be possible to include an argument in the backup/restore moulinette to ask for a single user to be backed up?
The backup/restore scripts could then act on this argument if they wish.

This could ease the process of moving specific users from one YunoHost instance to another (freedom of portability). Otherwise the user has to backup the data in each service separately.

Thanks

**Comment by zamentur** [comment]
I close cause it's a duplicate of https://github.com/YunoHost/issues/issues/784

**Comment by zamentur** [comment]
Reopen to separate per domain and per user

**Comment by alexAubin** [comment]
Closing because realistically this is not possible or that's a topic for a 3 year PhD
