### ISSUE TITLE
Allow more formatting in apps "text" type

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1482]
Right now I think we only supports `<br>`, as show on this screenshot one app developer wanted more options:
![image](https://user-images.githubusercontent.com/41827/68266730-3f716080-0050-11ea-91b3-48d55f1b4605.png)

We still need to think about restricting the scope of supported tags to avoid bad design.

We can use the [bleach mozilla's libraby](https://github.com/mozilla/bleach) which is package into debian as I've already did in another project as show [here](https://github.com/Psycojoker/pvpads/blob/master/meetings/models.py#L76) with this [list of accepted tags here](https://github.com/Psycojoker/pvpads/blob/master/meetings/format.py#L56).

**Comment by lhp22** [comment]
Bleach seems a perfect solution. I try to perform it.

**Comment by lhp22** [comment]
I've a choice problem : which strings are allowed to be html formatted ?

In my opinion, a minimum would be that the language-prefixed strings (en: "..." or fr: "..." or others) can be html formatted but not the others, which aim at being short

**edit** : the bleach default html tags are : ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code', 'em', 'i', 'li', 'ol', 'strong', 'ul'] . We have to add 'br' at least, to agree with present usage. Do we want to add "h1" and others ? That could be dangerous for design

**Comment by lhp22** [comment]
Hi there !

- First, I'm new as contributer. If the workflow I use isn't yours, tell me, I'll do as. For the moment, I come here when new questions are triggered.
- Second, I'vn't done html/css for a while, so I've used the https://www.w3schools.com as reference, and decided to follow the HTML 5 recommandations. (by example, 'acronym' tag isn't supported in HTML 5).

- For the moment, these are the html tags and attributes that I consider to be usable by app developpers : 
```

authorized_tags = ['a','abbr', 'b', 'blockquote', 'em', 'i', 'li', 'ol', 'ul', 'strong', 'br', 'q']
    # 'acronym' tag is not supported in HTML 5 (was in the bleach default tag)

authorized_attributes = \ 
    { '*' : ['title', 'lang'],
      'a' : ['href', 'hreflang', 'rel', 'target', 'type'],
      'abbr' : [], 
      'b': [], # Must be used as LAST resort to emphasize text, according to HTML 5 specification
      'blockquote' : ['cite'],
      'q' : ['cite'], # for inline quote 
      'em' : [], 
      'i' : [], 
      'ul' : [], # 'compact' and 'type' attributes are not supported in HTML5
      'ol' : ['reversed', 'start', 'type'], # 'compact' attribute is not supported in HTML5 
      'li' : [], # 'type' attribute is not supported in HTML5
      'strong' : [], # in HTML5 it's used to indicate "important text", not "strong emphasized text" like in HTML 4.01
      'br' : [], 
      'p' : [], # 'align' attribute is not supported in HTML 5
      'h1' : [], 
      'h2' : [], 
      'h3' : [], 
      'h4' : [], 
      'h5' : [], 
      'h6' : [], 
    }   
```
And right now a problem for the 'value' attribute of 'li' tag.
**1 [ The 'value' attribute exists but can be used in ol list only. Do we
         a) authorize it and check the correctness of the HTML code ?
         b) authorize it trusting the correctness
         c) not authorize (by default choice mine)
   ]**

- I'vn't looked at the html event attributes. I think we can forget them (at least as first html format). (these : https://www.w3schools.com/tags/ref_eventattributes.asp )

- A question stays about the `style` attribute.
**2 [ Do we authorize local css-ing through the `style` attribute ? ]**
My answer would be `no`, but mostly I don't know the position of yunohost community (and if they are).

- The unauthorized tags won't be stripped, but transformed into &lt; and &gt; tag. (Choice I've to done, so I precize).


And after these choices modifications have to be done in the code (of course). And as I'm new, i prefer listing these here, to be sure not forget. (of course, I'll do tests)
- API must accept reading the html in the variables as html code.
- Sentences must be sanitized according to the html format rules (via bleach).
- Choice must be done for the strings we authorize be "html formatted". (see my previous post).

**Comment by alexAubin** [comment]
>API must accept reading the html in the variables as html code. 

Not sure if I'm understanding what you're thinking about, but I think what you're looking for here is that in the webadmin templates (in `src/views/...`) you may use `{{{ foo }}}`  instead of `{{ foo }}` to use the content of foo as "raw html" (for example [here](https://github.com/YunoHost/yunohost-admin/blob/stretch-unstable/src/views/diagnosis/diagnosis_show.ms#L44))

Otherwise, reading quickly the other things from your post, it all seems to make sense and you seem to know what you're doing xD I don't have a comprehensive views of all html tags existing and even less their attribute but I do agree that we should avoid allowing custom style. Maybe allowing `<pre>` or `<code>` could be useful ? Otherwise you seem to know what you're doing so trusting you, and we can still iterate later on the allowed tags if we come up with new relevant use cases.

**Comment by zamentur** [comment]
I close this ticket cause markdown is now supported.
