### ISSUE TITLE
Potential security risk on yunohost website

### ISSUE THREAD

**Issue by sucrecacao** [YunoHost/issues#1488]
from firefox 70, I got this error:
![dev](https://user-images.githubusercontent.com/55893070/68625737-2d714100-04da-11ea-8db4-8509676a12b2.png)

**Comment by zyphlar** [comment]
And now it seems that the website is down...

**Comment by sucrecacao** [comment]
its up for me

**Comment by zyphlar** [comment]
Yeah it was down for many people when I posted but up now.

**Comment by alexAubin** [comment]
dev.yunohost.org ain't used anymore.

Other services are back online.

**Comment by sucrecacao** [comment]
You might want to double check that because I'm pretty sure I landed on this page through a link on the the yunohost.org website. I would love to grep the website source  to find it, but it seems its not on the github.

**Comment by Psycojoker** [comment]
In fact it is on github: https://github.com/YunoHost/doc/

And indeed it seems there are still some occurrences if you want to remove them :) https://github.com/YunoHost/doc/search?q=dev.yunohost.org&unscoped_q=dev.yunohost.org
