### ISSUE TITLE
Nextcloud 15.0.12~ynh1  - rend le serveur inaccessible 

### ISSUE THREAD

**Issue by thsfo** [YunoHost/issues#1490]
Installation de yunohost     15.0.12~ynh1 sur un yuno tout frais sur VPN:

1. installation pas de soucis : https://paste.yunohost.org/raw/baginigoci
2. Accès à l'interface web.. ok
3. Mais quelques minutes plus tard: serveur inaccessible...https://paste.yunohost.org/exesesuluc.vbs
4. Si on désinstalle.. tout rentre dans l'ordre.

**Comment by Neeeflix** [comment]
I had, assuming I understood the problem correctly, the same. Besides the installation, did you also create an LDAP user named "nextcloud"?
This is probably the reason why the user settings don't seem to work properly here.

**Comment by alexAubin** [comment]
Dunno what the hell happens but the issue reported seems to have nothing to do with Nextcloud ... (or at least not nextcloud itself ..)

Closing because would need more detail and explanation to understand what happened exactly ..
