### ISSUE TITLE
Impossible to use yunohost app with the overlay from an iphone

### ISSUE THREAD

**Issue by ultibo** [YunoHost/issues#1491]
Hello guys ! First of all thank you very much for the hard work put so far in yunohost, it’s really a kick-ass solution !
Everything is almost plug&play, i’m just running into an issue when using a smartphone browser. I managed to have a workaround but I assume other people would run into the same issue.

**My YunoHost server**
Hardware: dedicated server (refurbished machine rented from Oneprovider)
YunoHost version: 3.6.5.3 (stable).
I have access to my server : Through SSH & the webadmin |
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : no

**Steps to reproduce the issue**

- install latest yunohost
- install dokuwiki on it’s own subdomain (wiki.domain.tld)
- from dokuwiki install the theme Bootstrap3 Template (https://www.dokuwiki.org/template:bootstrap3)
- install wekan on the main domain (domain.tld/wekan)
- from an iPhone connect to your domain.tld
- login normally
- select the dokuwiki app

**Expected result**

- the doku wiki app opens

**Current result**

- the dokuwiki app opens, but very quickly the yunohost overlay appears on top of it (the main page with the list of the application)
- it’s possible to make the overlay disappear and go back to dokuwiki by clicking on the overlay button, but the focus seems lost, it’s then impossible to scroll or click in dokuwiki

**Additional Information**
- the same issue occurs with another app : wekan
- tested on latest chrome for iOS / incognito mode on and off / latest Safari on iOS
- everything works as expected when using a desktop browser (Latest Chrome on a mac or pc), the problem is only reproductible on iOS
- not tested on an android phone

**workaround**
in the file /usr/share/ssowat/portal/assets/js/ynh_portal.js if you comment the call to the function init_portal_button_and_overlay() at line 234 the overlay is disabled and the bug is not reproductible on iOS anymore

Thanks for your help !

**Comment by arthurlutz** [comment]
This might be the same as an issue reported by a user on the forum https://forum.yunohost.org/t/web-ui-error-when-clicking-tile-flashes-page-then-back-to-ui/9464

**Comment by alexAubin** [comment]
Another user feedback : https://forum.yunohost.org/t/cant-seem-to-get-past-home-page-on-mobile-perhaps-home-page-hides-apps/9667

**Comment by ejheil** [comment]
Are there any negative consequences to making the change above that disables the overlay so it's usable on mobile?  I hesitate to go edit files in a third-party package, but I will if that's what it takes to make it usable.

**Comment by davidrans** [comment]
I am also running into this issue on an iPhone.

**Comment by moeenio** [comment]
Most of the time switching to private navigation seems to fix the issue

**Comment by squattertim** [comment]
Is that possible that this issue affects also the Safari browsers? Any experience?

**Comment by ultibo** [comment]
thank you very much @andretheolauret. Unfortunately I am not able to test your fix. I no longer have access to a yunohost instance

**Comment by andretheolauret** [comment]
I'm not sure but given that there is a fix, should this ticket be closed?

**Comment by ultibo** [comment]
i guess it will be closed once the pull request is merged

**Comment by KvizadSaderah** [comment]
Hi guys!
Also have this bug on iPhone with various applications. And btw for couple of times meet that on a MacBook m1.

**Comment by andretheolauret** [comment]
> Hi guys!
> Also have this bug on iPhone with various applications. And btw for couple of times meet that on a MacBook m1.

Hello, oh yes ! Ahah we search tester .. please apply the pull request in your environment and returns some comments. I guess it will really help us =)

**Comment by alexAubin** [comment]
Should be fixed by @andretheolauret 's PR (https://github.com/YunoHost/SSOwat/pull/186), please complain / reopen the issue if still experiencing the issue after upcoming release
