### ISSUE TITLE
feature request: search description when searching for apps to install!

### ISSUE THREAD

**Issue by albjeremias** [YunoHost/issues#1494]
yeah that would be great :) I was just trying to find all apps clients for caldav.. and I can't..

great work guyz, im enjoying testing yunohost, thanks! :+1:

**Comment by alexAubin** [comment]
( I don't remember if this is fixed in the new app catalog view or not, to be checked )

**Comment by tituspijean** [comment]
YunoHost 3.8.4.9 (stable): no, it does not. 😉 I also suggest to include the `tags` in the search pattern.

Example here with Flarum (disregard the pretty bad description)...
![A1](https://user-images.githubusercontent.com/8769166/88030083-17bd1c80-cb3b-11ea-8a73-60f6b3899032.JPG)
...it is not listed after searching for "forum" keyword.
![A2](https://user-images.githubusercontent.com/8769166/88030095-1a1f7680-cb3b-11ea-9f5a-78f1d282c346.JPG)

**Comment by cyxae** [comment]
Should we close it now that the PR is merged ?

**Comment by alexAubin** [comment]
Indeed, cheers ! :+1:
