### ISSUE TITLE
Improve SSOwat messages when a refferer issue occurs ?

### ISSUE THREAD

**Issue by eauchat** [YunoHost/issues#1495]
I'm having a weird bug that I didn't manage to even reproduce on any machine. I found no workaround, and I can't get to log in to sso with my usual browser.
I tried deleting cookies and site data, restarting the browser. No chance. Every time I try to login, it shows again the login page with a red box, written: "Please log in from the portal".
In any other browser, everything seem to work fine.
Maybe someone has an idea where the problem comes from.

**Comment by alexAubin** [comment]
Hmmm do you have any addon that might be interfering ?

**Comment by eauchat** [comment]
Well it's also what I thought, I'm trying to disable all addons to see if something gets better and which would create the problem. But no scripts are blocked or anything like that.

**Comment by eauchat** [comment]
Disabling all extensions and restarting the browser didn't solve the issue.

**Comment by eauchat** [comment]
No luck for now. Maybe time will solve the issue...

**Comment by eauchat** [comment]
Ok, I finally figured out where the problem was coming from. I had changed the browser's config `Network.http.sendRefererHeader` from `2` to `0`. Then, from what I understand, the sso was interpreting it as CSRF attack.
The related code is [here](https://github.com/YunoHost/SSOwat/blob/stretch-unstable/access.lua#L183-L200).
I'm not really able to judge if that's just how it should be or not and if I should close the issue or not.

**Comment by pjpmosteiro** [comment]
> Ok, I finally figured out where the problem was coming from. I had changed the browser's config `Network.http.sendRefererHeader` from `2` to `0`. Then, from what I understand, the sso was interpreting it as CSRF attack.
> The related code is [here](https://github.com/YunoHost/SSOwat/blob/stretch-unstable/access.lua#L183-L200).
> I'm not really able to judge if that's just how it should be or not and if I should close the issue or not.

That´s useful for firefox users... Maybe you don´t know the equivalent in chrome-based browsers, don´t you? Thanks.

**Comment by eauchat** [comment]
@pjpmosteiro
Maybe the chrome equivalent is: `chrome://flags/#reduced-referrer-granularity`.

Thanks for the question, it made me find out another way to "hide" the referrer in Firefox, this one doesn't seem to cause issues with logging in to yunohost. Changing `network.http.referer.spoofSource` to `true`.

**Comment by alexAubin** [comment]
Sounds like a duplicate of https://github.com/YunoHost/issues/issues/1336

**Comment by eauchat** [comment]
Yep, that's true ;)
