### ISSUE TITLE
Cannot login (SSOwat)

### ISSUE THREAD

**Issue by gilluc** [YunoHost/issues#1499]
hi all,
yunohost is in hyper-v on my win10.
Install OK
Post install OK
used xxx.ynh.fr for DNS with let's encrypt OK
I created 2 users to make some tests.

In the browser in my win10 i installed some applications : fressrss, dokuwiki, sears, roundcube.
I connected successfully to some of them using both users.
but now cannot connect anymore : login screen come back everytime and nothing else...

connection to the admin page is OK however...i can make admin tasks, ... but no user login!!!

connecting from my android mobile works ....!?

any idea?

thanks in advance 
gilles

**Comment by gilluc** [comment]
seems that ssowat does not like very much different users login on the same PC...
as no problem at all when different users log from diffrent PC or smartphones.

**Comment by gilluc** [comment]
today, **no connections to any user on any PC**, unless "admin" everywhere...
i installed yunohost 3 times now and everytime it works the day of install and nothing works the day after !!!
**who has a working yunohost?** at home in a VM (hyper-v or virtualbox) with a domain like xxxx.ynh.fr and let's encrypt certificates ???
who??

**Comment by gilluc** [comment]
i dont use yunohost anymore!

**Comment by eauchat** [comment]
It's a bit confusing the descriptions you made
The problem you had in the browser may be related to another issue described. If you had a loop over the login page. You can solve it clearing cookies in your browser.
With more precision on the exact issues, it'd be possible to help better.
