### ISSUE TITLE
change the app options, and be able to update the app

### ISSUE THREAD

**Issue by albjeremias** [YunoHost/issues#1500]
Right now, when i  install an app, the definitions i choose when installing they are unchangable... It would be great to be able to change, at least from public to private and the contrary.

I tried to backup the app, and then revive it.. and did not work.. :(

related: https://forum.yunohost.org/t/change-an-application-from-public-to-private/3352

**Comment by Psycojoker** [comment]
This is not possible right now and will be once the config-panel and apps actions are stable.

You can do that by hand but I wouldn't recommend it.

**Comment by albjeremias** [comment]
hi can you clarify a bit better about what are the constrains with the current architecture of yunohost?

**Comment by Psycojoker** [comment]
There is not possibility for an app to provide any configuration beyond installation/remove/upgrade and installation is the only ones that accept parameters.

**Comment by alexAubin** [comment]
Note that changing from public to private or viceversa is now doable thanks to the new permission system in 3.7

**Comment by zamentur** [comment]
I close this ticket cause public_private / change url and new config panel system in 4.3 should cover all the use case descrive here
