### ISSUE TITLE
SLAPD crash on some LDAP update operation

### ISSUE THREAD

**Issue by Josue-T** [YunoHost/issues#1502]
Following this issue https://github.com/YunoHost-Apps/ffsync_ynh/issues/14 I think it's probably a core side bug.

My hypothesis is that yunohost try to update the LDAP with exactly the same value that it was already in the database.

I might investigate when I've some time.

**Comment by kay0u** [comment]
fixed by https://github.com/YunoHost/moulinette/pull/231
