### ISSUE TITLE
How to fork entire Yunohost project ?

### ISSUE THREAD

**Issue by Aeris1One** [YunoHost/issues#1505]
Hi,
For testing purposes, I wan't to make, on my own server, a fork of the entire Yunohost project, but I can't found some repos like the one that power forge.yunohost.org, and some other.
So, which repos have I to fork to fork the entire project and build my own Yunohost image ?

**Comment by ketsapiwiq** [comment]
Hi!
To develop on YunoHost there's this repo: https://github.com/YunoHost/ynh-dev
You can [see here the repositories it needs to clone before running](https://github.com/YunoHost/ynh-dev/blob/master/deploy.sh): 

```
git clone https://github.com/yunohost/ynh-dev
cd ./ynh-dev
git clone https://github.com/YunoHost/moulinette
git clone https://github.com/YunoHost/yunohost
git clone https://github.com/YunoHost/yunohost-admin
git clone https://github.com/YunoHost/SSOwat ssowat
```

There might be some I miss though, you can try looking for all repos of the YunoHost org in GitHub I guess...
