### ISSUE TITLE
Use dpkg-divert

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#151]
###### Original Redmine Issue: [151](https://dev.yunohost.org/issues/151)

Author Name: **julienmalik**

---

Seems like we could make good use of dpkg-divert to fortify our package configuration setup.

See:
https://www.debian.org/doc/debian-policy/ap-pkg-diversions.html
https://wiki.debian.org/ConfigPackages

In the current situation, I imagine that if a regular package for which we override configuration (nginx, slapd, ...) provides a new configuration file, it will trigger the dpkg interactive merge tool, comparing the new package-provided version with the custom yunohost-generated version.
This should probably be avoided.

**Comment by Psycojoker** [comment]
Do we still need that?

**Comment by alexAubin** [comment]
I don't think we do ... In practice in most cases we just keep the old conf and stuff keeps working. Breaking changes only seem to happen during upgrade of the full distribution, e.g. faill2ban during the jessie->stretch transition, and we just handled it manually and I don't think dpkg-divert would have helped here.
