### ISSUE TITLE
Separate vhost config for each XMPP domain

### ISSUE THREAD

**Issue by pitchum** [YunoHost/issues#1516]
## The problem

Currently only the main yunohost domain can host a full-featured XMPP server, because there are no components defined for the other domains.
In particular only the main domain can host chatrooms. Users of secondary domains must create chatrooms on the main domain.

There are situations where such behaviour is not desirable.
For example :

- main domain: mypersonalname.net
- secondary domain: myschoolchessclub.org
- secondary domain: somenonprofit.org
- another domain
- ...

If people of my chess club want to create a new chatroom to speak about upcoming competitions they will have to create *competitions@muc.mypersonalname.net* instead of *competitions@muc.myschoolchessclub.org*.
There are at least 3 problems with that:

1. that name does not make any sense for people of the chess club
2. there can be only one chatroom named ''competitions'' across all yunohost domains
3. if some day I decide to switch my main domain all chatrooms (and other XMPP-related services) will disappear

## Solution

Metronome is already designed to allow many distinct virtualhosts, so let's to that!
Doing so will make all domains independent from the main domain.

## Work in progress

I'm ready to work on a PR for this one.

**Comment by M5oul** [comment]
You are right!

---
But what if we do not want all the XMPP features on a domain created for instance just for running an application on it?
What would be nice, is that we would have a way to say no XMPP on this domain name. Enable and disable XMPP on whatevery domain name. This is bringing much more work to the original idea.

That was already an idea to be able to enable and disable other services per domain such as the mail. But, yeah, we currently have an email server running on every domain name of the YunoHost instance.

I never tried mail boxes on different mail boxes. What if a domain name get deleted with a user having its email address based on this domain name? Same for XMPP?

---

Sorry for this §. I do not know what’s bug me, A security issue? Let’s focus on the issue of this ticket. We will fix issue when they will appear.

**Comment by Neustradamus** [comment]
It is important to have several VirtualHosts for XMPP.

For do not add all in one file, it is not possible to create subfiles with "VirtualHost" settings (all options)?
- folder
-- main-conf (main domain "first vhost" with import files section)
-- second-vhost-conf
-- third-vhost-conf
-- ...

In the webadmin, add options for each domain:
- Enable/disable XMPP server
- Enable/disable anon section
- Enable/disable MUC service
- Enable/disable PubSub service
- Enable/disable HTTP upload
- ...

If option enabled and needed a subdomain, subdomain needs to be in Let's Encrypt settings, if not: removed from.

**Comment by pitchum** [comment]
> For do not add all in one file, it is not possible to create subfiles with "VirtualHost" settings (all options)?

That's already the case. Each vhost has its dedicated config file:
```
/etc/metronome/
├── conf.d
│   ├── mypersonalname.net.cfg.lua
│   ├── myschoolchessclub.org.cfg.lua
│   └── somenonprofit.org.cfg.lua
└── metronome.cfg.lua
```


> In the webadmin, add options for each domain:

At the moment there is no webadmin UI for XMPP and it's not planned in the short term.
This (big) subject deserves a separate issue and a separate PR.
