### ISSUE TITLE
Be able to enable ssh login for specific users

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#152]
###### Original Redmine Issue: [152](https://dev.yunohost.org/issues/152)

Author Name: **Bram**

---

Hello,

Currently it's only possible for root and admin to log in ssh since all other users have their shell set to /bin/false. There is currently no way to change that using the yunohost stack (you need to write your own ldap query which nobody know how to do).

There should be a way to change that. A first way to do that would be to add a new CLI entry to the "yunohost" command before considering adding this to the admin interfac

**Comment by alexAubin** [comment]
Integrated in 2.7.12 \o/
