### ISSUE TITLE
Install via the ISO should allow proxy configuration

### ISSUE THREAD

**Issue by ceinmart** [YunoHost/issues#1524]
I'm installing the last version ISO available , 3.6.4.6 . 
The VM where I'm installing it doesn't have direct access to internet, only with proxy. 
Following the standard install steps, don't ask for a proxy configuration before try to configure the apt mirror. 
If I try to cancel the mirror configuration, get this message : 
![image](https://user-images.githubusercontent.com/7062410/75694072-b4634880-5c86-11ea-8b2a-b828d6023046.png)
I want to execute the full install using the mirror with proxy, how to do that?

**Comment by ceinmart** [comment]
After a few research, I was able to manually set the proxy during the install.
This installation appears to be too much automated without option for the user set any particular configuration in case of problems, at least for network configuration. 

What I did:

1. after the error to configure the apt mirror I click to "go back" which back to main menu of the steps. 
2. I went to the prompt on terminal 2 (SHIFT-F2) 
3. Found the /target/etc/apt/apt.conf.d , configured there a file with content similar to this : 
`Acquire::http::Proxy "http://192.168.0.1:3128";`
Using the nano editor (since vi wasn't enabled)
4. Configured the /target/etc/wgetrc 
  where I set the proxy* configurations. 
5. Copied the files /target/etc/wgetrc and /target/etc/resolv.conf to /etc/ , since the wget also need to have a proxy configured and the network configures the resolv.conf to the wrong place and wasn't resolving the names since the DNS wasn't set at the installer environment.

**Comment by alexAubin** [comment]
(Agreed .. on the other hand, most users are not in a context where they use any proxy, and asking non-technical user wether or not they want to configure a proxy usually result in confusion ... But yeah :|... )

**Comment by alexAubin** [comment]
(Btw from what I understand it should be allowed by the advanced/expert install mode)

**Comment by zamentur** [comment]
I close this ticket cause expert mode allow the use of proxy since sevferal month i think.
