### ISSUE TITLE
'yunohost app install' should refuse app name with dots right away

### ISSUE THREAD

**Issue by Gofannon** [YunoHost/issues#1525]
**Short**
YunoHost core does not handle well app package with "dot" in their names like `diagrams.net`

**Long**
While packaging [diagrams.net (old draw.io)](https://www.diagrams.net/blog/move-diagrams-net), I used the package id `diagrams.net`. Install went fine but remove failed. I guess it has something to do with https://github.com/YunoHost/yunohost/blob/master/src/yunohost/app.py#L1578

How do I correctly remove these apps from my system?

Here is the log:

```
root@yunohost:~# yunohost app list -i | grep diagra
    description: Online diagram software for making flowcharts, process diagrams, org charts, UML, ER and network diagrams
    id: diagrams.net
    description: Online diagram software for making flowcharts, process diagrams, org charts, UML, ER and network diagrams
    id: diagrams.net__2
    
    
root@yunohost:~# yunohost app remove 'diagrams.net' --debug
337  DEBUG loading actions map namespace 'yunohost'
415  DEBUG extra parameter classes loaded: ['comment', 'ask', 'password', 'required', 'pattern']
416  DEBUG initializing base actions map parser for cli
420  DEBUG registering new callback action 'yunohost.utils.packages.ynh_packages_version' to ['-v', '--version']
736  DEBUG acquiring lock...
810  DEBUG lock has been acquired
920  DEBUG loading python module yunohost.app took 0.109s
921  INFO processing action [7732.1]: yunohost.app.remove with args={'app': 'diagrams.net'}
1046 INFO Removing the app 'diagrams.net'…
1396 INFO The operation 'Remove the 'diagrams.net' app' could not be completed. Please share the full log of this operation using the command 'yunohost log display 20200303-214236-app_remove-diagrams.net --share' to get help
1404 DEBUG action [7732.1] executed in 0.482s
1405 DEBUG lock has been released
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 214, in <module>
    timeout=opts.timeout,
  File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 135, in cli
    moulinette.run(args, output_as=output_as, password=password, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 424, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 527, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 287, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/moulinette/yunohost/app.py", line 1219, in app_remove
    app_id, app_instance_nb = _parse_app_instance_name(app)
  File "/usr/lib/moulinette/yunohost/app.py", line 2991, in _parse_app_instance_name
    assert match, "Could not parse app instance name : %s" % app_instance_name
AssertionError: Could not parse app instance name : diagrams.net
root@yunohost:~# 


root@yunohost:~# yunohost -v
yunohost: 
  repo: testing
  version: 3.7.0.4
yunohost-admin: 
  repo: testing
  version: 3.7.0.1
moulinette: 
  repo: testing
  version: 3.7.0
ssowat: 
  repo: testing
  version: 3.7.0.1
root@yunohost:~# 
```

**Comment by southerntofu** [comment]
Hi, what happens when you edit the `re_app_instance_name` regex in app.py so as to accept dots? Like so:

```
re_app_instance_name = re.compile(
    r'^(?P<appid>[\w\.]+?)(__(?P<appinstancenb>[1-9][0-9]*))?$'
)
```

The weird `(?P<appid> ... ?)` means capture what matches whatever's in there and store the result as `appid`. I just added `\.` to the list of accepted characters in there. The dot is prefixed by a backslash because a simple dot in a regex means any character (wildcard), which is not what we want. 

This is a very naive patch and i have not tested it. It's simply based on your traceback mentioning `app_instance_name` has failed to match the regex. Please tell me if it works for you :)

**Comment by Gofannon** [comment]
According to https://regex101.com/, it seems to fo the trick. I will try then, thanks.

![image](https://user-images.githubusercontent.com/17145502/76530348-e721f380-6473-11ea-8045-399ff0df8f80.png)

---

In the meantime, I renamed the package to `diagramsnet_ynh`

**Comment by Gofannon** [comment]
It works nicely

![image](https://user-images.githubusercontent.com/17145502/76543052-38d37980-6486-11ea-8d4f-09f18c38b526.png)

**Comment by southerntofu** [comment]
Hi, i opened a pull-request in https://github.com/YunoHost/yunohost/pull/888

Let me know if there's something wrong with it

**Comment by alexAubin** [comment]
As Maniack said in PR 888 mentioned previously, dots should in fact not be allowed in the first place ... So running 'yunohost app install foo.bar' should trigger an expection right away

**Comment by alexAubin** [comment]
https://github.com/YunoHost/yunohost/commit/aac0146aef754315764705a8f45084ff0f9209e1
