### ISSUE TITLE
Update apps.md to be consistent with the admin panel

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/issues#1526]
The apps page into the doc isn't consistent with the one into the admin panel.
Especially the doc apps page lack the information about the `maintained` tag.

Only unmaintained apps are flagged as it, even though that's discreet.
Would be better to have the same flag as we have on the admin panel to inform users, and especially to help contributors to know which apps need love.

Also, would be great to add a filter to be able to see only apps that actually need love. So it would help to know which apps need new maintainers.

**Comment by alexAubin** [comment]
Closing, replaced by the new app catalog
