### ISSUE TITLE
Add privacy alternative to Instagram -> Bibliogram, and for Youtube -> Invidious

### ISSUE THREAD

**Issue by kalak-sudo** [YunoHost/issues#1527]
Hi! 

These 2 apps are a great tool used in the privacy world, which helps users to use this commons webs with a little more **privacy**.

So I thought: Why not include them in yunohost?? 

Here is the GitHub websites of each one: (both are actively updated)

**Bibliogram**: [https://github.com/cloudrac3r/bibliogram
](https://github.com/cloudrac3r/bibliogram
)
**Invidious**: [https://github.com/omarroth/invidious](https://github.com/omarroth/invidious)

There is an **automated script** for installing Invidious, which probably have already done a huge part of the unattended installation work:

[https://github.com/tmiland/Invidious-Updater](https://github.com/tmiland/Invidious-Updater)

Cheers!

**Comment by frju365** [comment]
You can add them to the apps wishlist. :-)

https://github.com/YunoHost/doc/blob/master/apps_wishlist.md

**Comment by Aeris1One** [comment]
@kalak-sudo, you can, if you have time and wants, add yourself these apps to Yunohost! 
The great majority of apps are maintained by the community. 
You can follow the doc to see how to do that, that's not very complicated, you'll see 😉

https://yunohost.org/#/contributordoc

PS: If you want a selfhosted alternative to YouTube, look at Peertube which is a High-quality app on Yunohost.

**Comment by alexAubin** [comment]
(To be done on the wishlist page in the doc)
