### ISSUE TITLE
Make a clean installation of nginx speed for yunohost server

### ISSUE THREAD

**Issue by arnaudbagnis** [YunoHost/issues#1528]
Hello,
I wanted to ask contributors and enthusiasts if someone would have already installed _**nginx speed**_ on **yunohost** to speed up the score on natural referencing.

The only documentation that seems clear to me ...
(https://www.modpagespeed.com/doc/build_ngx_pagespeed_from_source)
I am afraid of breaking the server by installing anything.

Thank you for reading this distress !

**Comment by alexAubin** [comment]
Dunno what the rest of the team thinks about it, but it's unlikely that we'll implement this anytime soon. It's just clearly not the priority considering all the other things that should be done, and it looks like too much magic and can't be applied on all vhosts by default. Could have a setting maybe but meh...
