### ISSUE TITLE
Unable to login on SSOwat when using it as a standalone software

### ISSUE THREAD

**Issue by miquelangeld** [YunoHost/issues#1529]
Hi, i'm trying to use ssowat. I configured all the parameters.

When I try to authenticate I always get  invalid credentials.
this is the request that I the DC receive (active directory)
![2020-03-19_14-30](https://user-images.githubusercontent.com/6650266/77072597-42149700-69ee-11ea-8ff1-8e3e04868eff.png)

All data received in the request seems to be alright, but the DC returns invalid credentials.

**Comment by alexAubin** [comment]
Sorry for the late answer ... Dunno what to say though, it's not clear if you're using YunoHost or attempting to use SSOwat as a standalone piece of software ... Guessing the second one ?

**Comment by miquelangeld** [comment]
Yes, the second one.

**Comment by alexAubin** [comment]
Closing because meh ... SSOwat is really coupled to Yunohost anyway
