### ISSUE TITLE
Use screen to handle disconnection when installing Yunohost.

### ISSUE THREAD

**Issue by Aeris1One** [YunoHost/issues#1530]
Hi,
I've a VPS and tried to install YunoHost, but my SSH client disconnected from the server due to a connection error on my side. The Yunohost installation just stopped and my server is now unusable.

Maybe you can make the install script open a screen to handle this type of error ?

**Comment by alexAubin** [comment]
Is it really unusable ? Most of what happens is apt package install so when that happens I usually re-run the script and it's fine (or maybe sometimes you need to `apt install -f` or `dpkg-reconfigure -a` or something like this)

**Comment by Aeris1One** [comment]
Nope, root account was disabled and I wasn't able to perform postinstall (nginx default webpage).
I've reinstalled the server so I can't do more tests about that :/ 
(If I remember well, root account is disabled after postinstall... So why was the root account disabled??? Idk)
