### ISSUE TITLE
Exception: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by Aeris1One** [YunoHost/issues#1531]
Hi,
I've this error on nearly all actions I do :
`Exception: 'NoneType' object has no attribute 'split'`

I tried to create a user, that error appeared (user creation failed : [errorlog]) but the user was created anyway.
I tried to install an app (etherpad-mypads), same error but the app installed correctly (except public access)
I tried to issue a LetsEncrypt certificate, same error, but this time the action was not performed.

What I did on the server : 
- installed Yunohost
- restored cachet_ynh from an old server (worked)
- created the first user (error)
- installed etherpad-mypads (error)
- tried to issue a certificate for my etherpad domain (worked)
- edited ssowat conf to make my etherpad domain public
- tried to issue a certificate for my main domain (error)

Maybe the bug is caused by the fact I created the first user after installing an app ?

 same error in #1385

**Comment by Aeris1One** [comment]
Logs : https://paste.yunohost.org/juranipedo.php

**Comment by alexAubin** [comment]
Uuuh, do you have other exampls whete this happens ?

**Comment by Aeris1One** [comment]
Tried to install "my_webapp_ynh" by the webmin : 
YunoHost a rencontré une erreur interne :/
Vraiment navré.
Vous devriez chercher de l’aide sur le forum ou le salon pour résoudre le problème, ou rapporter le bogue sur l’outil de suivi.
Les informations suivantes peuvent être utile à l’interlocuteur vous aidant :
Action

```
POST /apps
 {"app":"my_webapp","args":"domain=[redactedDomain]&path=%2Frandom&password=myreallystrengtgpass&is_public=1&with_mysql=0","label":"Webapp test"}
```

Trace

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 439, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 523, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 284, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/moulinette/yunohost/app.py", line 931, in app_install
    app_ssowatconf()
  File "/usr/lib/moulinette/yunohost/app.py", line 1498, in app_ssowatconf
    for username in user_list()['users'].keys()},
  File "/usr/lib/moulinette/yunohost/app.py", line 1498, in 
    for username in user_list()['users'].keys()},
  File "/usr/lib/moulinette/yunohost/app.py", line 427, in app_map
    and user not in app_settings['allowed_users'].split(','):
AttributeError: 'NoneType' object has no attribute 'split'
```
And the logs (nothing strange in here, look like a completed install) : https://paste.yunohost.org/ahuwuvicuw.bash

Annnndd... The app is installed correctly ! I can use it and it appears in the webmin.

**Comment by alexAubin** [comment]
hmyea idk mayb something funky happened when restoring cachet ...

Can you tell what's your Yunohost version ?

This bug should anyway be fixed in the new version (3.7 from tonight) since that part has been completely reworked

**Comment by Aeris1One** [comment]
Latest stable I guess, installed server yesterday.
![IMG_20200327_122113](https://user-images.githubusercontent.com/29739547/77773279-aae0bc80-7049-11ea-84b3-ea12a1fb6de8.jpg)
PS: Can you tell me why the repo is "now" and not "stable" ?

**Comment by Aeris1One** [comment]
I'll update to 3.7... Didn't know it was (already) released !
