### ISSUE TITLE
API does not work with some browser brecause of bad handling of CORS CSRF preflight options

### ISSUE THREAD

**Issue by bachy** [YunoHost/issues#1533]
Hi,
I think that ynh api is not capable of handling api login from browser (eg axios) due to pre-flight options request.

simple request (browser is not sending pre-flight but api is missing params)
```js
axios({
        method: 'POST',
        url: 'https://domain.net/yunohost/api/login',
        data: qs.stringify({ 'password': 'XXXXXXXXX' }),
      })
```
-> 403

request with data but without headers (browser is automaticlly sending a pre-flight)
```js
axios({
        method: 'POST',
        url: 'https://domain.net/yunohost/api/login',
        data: { password: 'xxxxxxxxxxxxxxxxx' }
      })
```
-> 405 command not allowed on preflight OPTIONS

request with data and headers (browser is automaticlly sending a pre-flight)
```js
axios({
        method: 'POST',
        url: 'https://domain.net/yunohost/api/login',
        data: qs.stringify({ 'password': 'XXXXXXXXX' }),
        headers: {
          'X-Requested-With': 'customscript',
          'Content-Type': 'application/x-www-form-urlencoded'
        }
      })
```
-> 405 command not allowed on preflight OPTIONS

api should sends a response with this header
```Access-Control-Allow-Origin: *```
https://stackoverflow.com/questions/29954037/why-is-an-options-request-sent-and-can-i-disable-it

https://forum.yunohost.org/t/ynh-api-via-axios/10644/4

**Comment by bachy** [comment]
avec request native du navigateur c'est exactement le mm résultat, le navigateur envoie automatiquement un pre-flight options pour vérifier qu'il peut faire du CORS, requete a quoi le serveur devrait répondre avec un ```Access-Control-Allow-Headers: Authorization``` dans ces headers pour que le navigateur autorise le CORS. Sauf que ynh repond un 405 method not allowed, et donc la vraie requete n'est jamais envoyée (bloquée par le navigateur)
ça ne dépend pas de la librairy mais de ynh
```
      var myHeaders = new Headers()
      myHeaders.append('Content-Type', 'application/x-www-form-urlencoded')
      myHeaders.append('X-Requested-With', 'customscript')

      const request = new Request('https://domain.tld/yunohost/api/login', { method: 'POST', body: '{"password": "xxxxxxxxxxxxxxxxxxxxx"}', headers: myHeaders })

      fetch(request)
        .then(response => {
          if (response.status === 200) {
            console.log('response', response)
            return response.json()
          } else {
            throw new Error('Something went wrong on api server!')
          }
        })
        .then(response => {
          console.debug(response)
          // ...
        }).catch(error => {
          console.error(error)
        })
```

**Comment by bachy** [comment]
avec request native du navigateur c'est exactement le mm résultat, le navigateur envoie automatiquement un pre-flight options pour vérifier qu'il peut faire du CORS, requete a quoi le serveur devrait répondre avec un ```Access-Control-Allow-Headers: Authorization``` ou ```Access-Control-Allow-Origin: *``` dans ces headers pour que le navigateur autorise le CORS. Sauf que ynh repond un 405 method not allowed, et donc la vraie requete n'est jamais envoyée (bloquée par le navigateur)
ça ne dépend pas de la librairy mais de ynh
```
      var myHeaders = new Headers()
      myHeaders.append('Content-Type', 'application/x-www-form-urlencoded')
      myHeaders.append('X-Requested-With', 'customscript')

      const request = new Request('https://domain.tld/yunohost/api/login', { method: 'POST', body: '{"password": "xxxxxxxxxxxxxxxxxxxxx"}', headers: myHeaders })

      fetch(request)
        .then(response => {
          if (response.status === 200) {
            console.log('response', response)
            return response.json()
          } else {
            throw new Error('Something went wrong on api server!')
          }
        })
        .then(response => {
          console.debug(response)
          // ...
        }).catch(error => {
          console.error(error)
        })
```

**Comment by alexAubin** [comment]
Apparently related to : https://stackoverflow.com/questions/17262170/bottle-py-enabling-cors-for-jquery-ajax-requests

**Comment by alexAubin** [comment]
It would help if you would elaborate on why you are working on this, 'cause this is the first time somebody reports this issue ... The API / webadmin works fine from Firefox / Chromium ...

**Comment by bachy** [comment]
The webmin works fine because there is no cors domain, the webclient lives in the same domain as the api.
I wanted to developpe an UI for managing undreds of ynh users. An ui giving the possibility to allow user management to my art school administration, without giving them the full ynh admin access.
As a designer and (mostly) frontend dev, i strated to code it with vuejs (and axios)

**Comment by alexAubin** [comment]
Uh okay, so that UI would be hosted on a different domain, which is why you need CORS ?

**Comment by bachy** [comment]
yes

**Comment by alexAubin** [comment]
But like is that a hard requirement ...? Can you elaborate on why you need to have this on a different domain ?

We can probably work on a fix someday, but it's like there's so many todo and this ain't the funniest thing ever to fix ... And if we do fix it, it'll probably be several week before it's available in stable ...

**Comment by bachy** [comment]
I mainly wanted to be sur that the issue was not on my side. If it's not easy to fixe, i'll try an other way, don't know how yet.

**Comment by gnouts** [comment]
I think I'm also affected by this issue...
My use case : I host photoprism in docker (not the photoprism_ynh package) and use the redirect_ynh to proxy_pass to my container. I don't know what triggers it but after a few seconds/minutes, the OPTIONS request to `/yunohost/sso` receives a 405 Method Not Allowed, the subsequent GET are denied. I need to refresh the page, I got the sso login page, I login, access photoprism, wait a few dozen of seconds and repeat.
It happens that photoprism also use Axios lib, but as shown [there](https://forum.yunohost.org/t/ynh-api-via-axios/10644/6) this bug is not limited to axios

**Comment by alexAubin** [comment]
Fixed in bookworm, cf https://github.com/YunoHost/moulinette/commit/328107c94699074cd00692451fd55589c96f16f2
