### ISSUE TITLE
Use app's label in the groups and permissions page

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#1534]
In the webadmin, groups and permissions page, if apps are multi-installed it can become difficult to tell them apart.

Example here with two Redirect apps. Which is which? I have to go to the apps list and check.

![image](https://user-images.githubusercontent.com/8769166/77823761-c73e3100-70fd-11ea-8243-827131766499.png)

Solution proposal : use app labels instead of app id, or add a mouse hover tool tip with their label?

**Comment by Josue-T** [comment]
> Solution proposal : use app labels instead of app id, or add a mouse hover tool tip with their label?

Well, thinking about that, does it really fix the issue. Probably all instance of the same app have the same label, so it might be more confusing then now...

**Comment by Aeris1One** [comment]
> add a mouse hover tool tip with their label

Maybe the mouse hover tooltip can be better.

Personally, when I install two times or more the same app, I change the label to avoid confusion in SSO tiles...

**Comment by tituspijean** [comment]
UX-wise, it would help a lot at least. I would have, for example:

- Redirect labelled "PhotoPrism" (docker container)
- Redirect__2 labelled "Lodestone" (another docker container)
- Grav labelled "Blog"
- Grav__2 labelled "Test site"

2 of them I need to be kept private, 2 of them will be public. From their app ID only, if you don't remember which is which, you have to go to another webadmin page to check.

**Comment by Aeris1One** [comment]
I agree. I've myself 4 Redirect...

**Comment by tituspijean** [comment]
Fixed in the webadmin rework of v4.2. Now the app label is used instead of its ID. ❤️
