### ISSUE TITLE
Shall we rework the way we deploy php apps to have one php-fpm service per app instead of a common one ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1536]
Currently php apps share a common php7.x-fpm service, which is somewhat easier to configure (you only have to drop the pool config and restart php-fpm) but the drawback is that if a single one of those pool file is broken, *it breaks every other php app on the system* and we see many people complain about 502 errors accross all their apps because of this.

Instead, and to decrease the whole php madness, we could imagine creating a dedicated service for each of these apps, which would prevent that catastrophic domino effect. This might even help with the cohabitation of different php versions (though that doesn't solve the dependency management issue, but maybe in another topic we can discuss if adding sury sources.list in the core would be a good thing or not)

Having one service per php app would in fact be more consistent to what happens to other apps (e.g. apps in nodejs, python, ruby, ... ) which add their very own service. Though maybe there's an overhead in doing so ? But I'm not knowledgeable enough to know about that.

The biggest question in this is of course the feasibility of doing so without having to repackage every php app ... Could try to investigate if it's doable to tweak the php-fpm bash helpers such that they would automatically create the systemd service... And see how smooth or not such a transition would be .

**Comment by maniackcrudelis** [comment]
Well to migrate wouldn't be difficult regarding the use of the helper.
But, if I understand the idea of not breaking every apps because of only one, are you sure it wouldn't end up eating a lot much ram than the current situation ?

Not sure either about the current architecture, with a global config file.
Not sure how it would work if we split into different services.
I guess the question would be investigate to better understand the current architecture and how we can migrate.

One thing sure though, to migrate wouldn't be too harder with our current helper.

**Comment by kay0u** [comment]
It would be much easier to find the php-fpm logs for a specific application in webadmin

**Comment by alexAubin** [comment]
>But, if I understand the idea of not breaking every apps because of only one, are you sure it wouldn't end up eating a lot much ram than the current situation ?

I don't know either ... we could run some tests to find out ... Having a small look on my server, my two php-fpm master processes (one for php7.0, the other for 7.3) indeed surprisingly takes 35ish MB of RAM each (in addition to pool processes). I don't know wether or not it depends from the number of child pool processes ... (could check on a server that run many more apps than mine).

**Comment by Aeris1One** [comment]
If it remove the risk of breaking all my apps because of only one install broken, I would surely spend 35MB of RAM for each app ! 
I just broke about 5 apps while trying to install phpmyadmin -_-

**Comment by maniackcrudelis** [comment]
Well, I start investigating this suggestion...

**Comment by maniackcrudelis** [comment]
And it works perfectly, though I have a overload of 30M for each new master process.
I make a pull request, so we can discuss on it.

**Comment by alexAubin** [comment]
Closing because we implemented the "standalone php" stuff but it's pretty much unused except for pihole ... Nowadays things are a bit more stable even though still a risk of an app destroying the entire php stack ...
