### ISSUE TITLE
Cannot install apps with path that look alike but are not identical

### ISSUE THREAD

**Issue by roukydesbois** [YunoHost/issues#1543]
Hello guys!

I have freshrss installed on the url /rss and I tried to install rss-bridge using these paths:

- /rss-bridge
- /rssbridge
- /bridgerss

and none worked, I had this error message:

```
Cette URL n’est pas disponible ou est en conflit avec une application existante :
* mydomain.com/rss → FreshRSS (freshrss)
```
Is this an expected behaviour? Or is it a matching that is not precise enough?

Installing it on /bridge worked.

**Comment by alexAubin** [comment]
It's an expected behavior ...

Not sure, but maybe the underlying technical reason could be that in nginx, `location /rss` would catch also `/rsswhatever` as well ? (Though I would imagine if `location /rsswhatever` is defined, it should use the longest match first ...)

**Comment by Josue-T** [comment]
Maybe due to [theses lines](https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/domain.py#L350-L353), but don't really understand for `/bridgerss`.

**Comment by roukydesbois** [comment]
Aaaaaaaaahhhhh gotcha. Thanks for the quick answer!
