### ISSUE TITLE
config-panel doesnt handle multi-instance apps

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/issues#1544]
More information here: https://github.com/YunoHost-Apps/etherpad_mypads_ynh/pull/93

It appears that the config panel feature, when validating a change, looks for the YNH_APP_ID instead of YNH_APP_INSTANCE_NAME.

I don't know what are the consequences for the config-panel behavior, but as we can see on that issue, it's already a real problem if there's no app with YNH_APP_INSTANCE_NAME as simply YNH_APP_ID.

**Comment by kay0u** [comment]
Fixed by https://github.com/YunoHost/yunohost-admin/pull/282

**Comment by kay0u** [comment]
Fixed in stable :-)
