### ISSUE TITLE
Actions feature does not work if no description is provided

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/issues#1545]
Just found out that new bug (or is that a feature ?)
Any entry into the action.toml will cause an infinite loop of the pacman if there's not a `description = "my description..."` for each entry.

On the same matter, that description doesn't appear anywhere !

**Comment by kay0u** [comment]
The "bug" is here:
https://github.com/YunoHost/yunohost-admin/blob/79301a80836d92d30a96eb62938fc8f3d341b77d/src/js/yunohost/controllers/apps.js#L305-L308

The question is: should we consider the "description" as mandatory information (like the manifest)?

**Comment by maniackcrudelis** [comment]
I feel like sometime the name of an action is self explanatory.
But first, the description should appears somewhere ;)

**Comment by kay0u** [comment]
>  But first, the description should appears somewhere ;)

Indeed, another bug: `action.description['en']` we try to retrieve the `en` value, but if it's not an array it doesn't work

**Comment by kay0u** [comment]
Should be fixed by: https://github.com/YunoHost/yunohost-admin/pull/289
