### ISSUE TITLE
Sury break pip with TLS connection

### ISSUE THREAD

**Issue by Josue-T** [YunoHost/issues#1546]
Hello,

I discovered a new issue with the sury repo here : https://github.com/YunoHost-Apps/pgadmin_ynh/issues/3

After a long time to try to discovery why in some case we wasn't able to use pip to install some package i discovered that it's sury which break pip. When we use sury, the openssl package is upgraded. This break some tools in some case.

**Comment by maniackcrudelis** [comment]
Should be added into the pin config then.

**Comment by autra** [comment]
> This break some tools in some case.

@Josue-T do you remember which tools were broken and how? I've read the issue in pgadmin, but I didn't understand what you had in mind when asking to downgrade openssl.

**Comment by Josue-T** [comment]
pip was broken when you download file from https.

**Comment by alexAubin** [comment]
From what we discussed at some point, it was due to the installation of the more recent openssl version from sury ? If that's the case the issue should now be fixed because we pin openssl/libssl such that it doesn't get installed from sury anymore...
