### ISSUE TITLE
Allow yunohost app config show-panel app to only show

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/issues#1547]
Currently, when using `yunohost app config show-panel app`, it asks for all data before showing the panel like it would do on the web admin panel.

To be able to only show the config-panel would be interesting
- For an user willing to know what are the possible configurations, without changing anything.
- To just check if the config-panel does actually work or is buggy. Especially because I'm working on a new test for package check for actions and config-panel.

**Comment by alexAubin** [comment]
Closing because the config panel CLI got reworked in 4.3
