### ISSUE TITLE
People remove the Nextcloud permission from the 'visitors' group without realizing their Nextcloud client is a "visitor"

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1550]
We should add some explanation about this ... Had a user who naively removed it thinking that "I've put my credentials in my smartphone app, so it's not anonymous"

**Comment by Josue-T** [comment]
Should be fixed by https://github.com/YunoHost/yunohost/pull/861

**Comment by alexAubin** [comment]
In the meantime I added a small comment in the webadmin : https://github.com/YunoHost/yunohost-admin/commit/c0c2f417039895f0eaed9ca3234d7433fd885dfc

**Comment by alexAubin** [comment]
Closing, fixed by 4.1
