### ISSUE TITLE
Unable to install LibreERP

### ISSUE THREAD

**Issue by Qoyyuum** [YunoHost/issues#1551]
There's a problem with installing LibreERP. Log can be found here: https://paste.yunohost.org/raw/ajodepusek

According to the log, it looks like its trying to uninstall/remove `libreerp-ynh-deps` python package but couldn't because its not allowed to. Not sure why it wants to do that (perhaps a package conflict).

**Comment by tituspijean** [comment]
You might want to post your issue on the [app's repository](https://github.com/YunoHost-Apps/libreerp_ynh/issues).
Notably, https://github.com/YunoHost-Apps/libreerp_ynh/issues/20 might match your problem.

**Comment by alexAubin** [comment]
Closing c.f. titus's comment ^
