### ISSUE TITLE
adding an url in skipped url in ssowat persistent configuration is defeated by autogenerated conf.json in version >= 3.7.0.3

### ISSUE THREAD

**Issue by plslvval** [YunoHost/issues#1552]
From https://github.com/YunoHost-Apps/peertube_ynh/issues/161
adding a skipped url in /etc/ssowat/conf.persistent.json is no more honored since unprotected url takes the advantage due to YunoHost/SSOwat@eb2872d#diff-80c7526357cd62e0d0b6d80c34850105

new ordering of conflicting requests, here skipped in persistent and unprotected in autogenerated conf.json, create this problem.

It seems ssowat code does not prioritize between persistent and autogenerated configuration when it applies to different constraints. I think user expects that persistent confiugration does overrides everything coming from autogenerated configuration. I think this existed before in facts when conflict is between protected and skipped.

**Comment by yalh76** [comment]
maybe @kay0u can look at that issue ;) after doing the million things, he's doing ^^

**Comment by Josue-T** [comment]
@plslvval can you explain exactly what is the issue with peertube and what is the actual configuration. Maybe there are an other cleaner way to fix this.

Probably https://github.com/YunoHost/SSOwat/pull/161 and https://github.com/YunoHost/yunohost/pull/861 will help to fix theses issues.

**Comment by plslvval** [comment]
@Josue-T 

- Sorry if i am too verbose -

i maintain peertube instance https://peertube.serveur.slv-valbonne.fr and upgrade it often when a new package come. peertube need its own domain and operate it fully.
This public instance does not work correctly with default configuration of yunohost package when user is logged on yunohost, sso adds authentication header colliding with oauth2 of peertube. When logged on yunohost ( ie nothing related to peertube login) it is just not possible to show any video.
To overcome this issue we created a conf.json.persistent skipped_url = [ url ] to disregard any sso for peertube. Until 3.7.0.3 this was actualy fixing the problem but since it did change, some values ( unprotected_url ) within conf.json autogenerated does create the problem.
Even workaround is now subject to change in autoconfiguration, while as a user i expected that persistent manualy configured value is taken in account first.

so problem is that autogenerated conf contains an unprotected_url entry for url :

"unprotected_urls": [
...
"peertube.serveur.slv-valbonne.fr",
...
]

If i remove it, this entry will be recreated later on during administrive tasks, just like with sudo yunohost app ssowatconf

here content of conf.json.persistent 
{
    "skipped_urls" : [
         "peertube.serveur.slv-valbonne.fr"
    ]
}

until 3.7.0.3 excluded this was working because only protected_url could override skipped_url but now unprotected_url are taken in account, then defeating purpose of persistent configuration.
By chance autoconfiguration did not generate protected_url, else this problem would have been seen earlier.

This for sure can be fixed at many places in yunohost peertube package by not using protected or unprotected url and using directly skipped.

Still it should be clarified how persistent configuration is supposed to work.

I was expecting it is first priority and the has the final word on any configuration, but this is not the case, constraints are mixed and compared together disregarding the fact it comes from persistent or not. This persistent configuration was for me the ultimate last wall where a owner of yunohost instance can state what he wants at the end, if it is mixed with autogenerated configuration it just means that wathever can happens. Editing autogenerated configuration is not a valid option and this is the current workaround solution we have for https://github.com/YunoHost-Apps/peertube_ynh/issues/161
I may find a way to create a persistent configuration with wider url that overrides current rules of ssowat, but this is really dependent on how priorities are done, and then subject to change in further versions and really a bad hack.

Stating that persistent configuration always win over whatever else  would be a life saver for manualy tweaked configuration. Or did i misunderstood the purpose of this persistent file as a way to pin once for all sso constraint we don't want packages installation or administrative reconfiguration alter.

**Comment by alexAubin** [comment]
Closing because this sounds super specific and the permission system got reworked in 4.x if I remember correctly ...
