### ISSUE TITLE
Can't restore archive containing custom hooks

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1553]
c.f. https://forum.yunohost.org/t/attributeerror-restoremanager-instance-has-no-attribute-work-dir/10860

When the archive contains custom hooks, the code will attempt to look into the archive to find the restore hook : 

https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/backup.py#L971-L973

Yet the archive is not mounted yet and self.work_dir is nonexistent and even if you define it you gotta mount the archive first ...

Not sure how to fix this

**Comment by kay0u** [comment]
fixed by https://github.com/YunoHost/yunohost/pull/927
