### ISSUE TITLE
limit uuid mapping to less than 65536

### ISSUE THREAD

**Issue by bachy** [YunoHost/issues#1557]
in some config (eg lxc on archlinux https://wiki.archlinux.org/index.php/Linux_Containers#Enable_support_to_run_unprivileged_containers_(optional)) idmap is limited to 65536

yunohost could limit his map to 60000

https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/user.py#L173

**Comment by bachy** [comment]
https://forum.yunohost.org/t/script-import-users/10851/2?u=bachy

**Comment by alexAubin** [comment]
Fixed in 3.7.1.1 thanks to Bram
