### ISSUE TITLE
Ldap Environment mapsize limit reached

### ISSUE THREAD

**Issue by bachy** [YunoHost/issues#1558]
with 300+ users (i know it does not append so often, but it append a least once) the ldap db size reach the mapsize limit
yunhost could raise it by default
10M is ridiculously low

**Comment by bachy** [comment]
by the way, i asked on the forum but i can't figure out how to change this config
https://forum.yunohost.org/t/ldap-environment-mapsize-limit-reached/10899

**Comment by alexAubin** [comment]
Fixed in 4.3
