### ISSUE TITLE
Make cron more helpful about certificates

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost/issues#1559]
Cron asks to run the `cert-install` command if your certificate needs to be renewed :
> /etc/cron.daily/yunohost-certificate-renew:
> Certificate for the domain `synapse.domain.ltd` does not appear to be correctly installed. Please run `cert-install` for this domain first.

A helpful improvement would be to print the entire command instead :

> Certificate for the domain `synapse.domain.ltd` does not appear to be correctly installed.  Please run `sudo yunohost domain cert-install synapse.domain.ltd` for this domain first.

**Comment by alexAubin** [comment]
Eh but now I realize that the check behind this message should now be obsolete ... In fact I'm not sure to understand how you ended up in a situation where this message showed up :/ 

Did things actually improved by running the cert-install command ?

**Comment by ericgaspar** [comment]
I received two cron reports for sub-domains (synapse and bitwarden).

I also had alerts when I tried to renew manually the certificat through the admin panel / domains / domain.ltd / certificat SSL / Renouveler manuellement maintenant.

Running cert-install command worked.

**Comment by alexAubin** [comment]
Could it be that you backup/restored your server on a fresh machine before experiencing this ?

**Comment by ericgaspar** [comment]
I had no backup/restored on this server...

**Comment by alexAubin** [comment]
Hmokay .. So if I tried to summarize : 

- you added those domains at some point
- probably some time right after, you installed a Lets Encrypt certificate
- ... some time passed ...
- and suddenly one day you wanted to force-renew the certificate / or the renew cron ran, and this message shows up ?

Did any automatic renewal worked before that ?

**Comment by ericgaspar** [comment]
Yes spot on!
The server has been running for a year and a half and it's the first time I have a certificate alert.

**Comment by lhp22** [comment]
I'm new and try to help. I try to investigate this.

**Comment by alexAubin** [comment]
The logic behind this message had to be changed, c.f. https://github.com/YunoHost/yunohost/pull/950
