### ISSUE TITLE
Mitigate the mess caused by possible used of backports or other extra apt repo by adding more constrains in debian/control

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1563]
c.f. that kind of mess : https://paste.yunohost.org/raw/obewasikah

Here it's about backports but it can in fact happens with any extra apt repo. For example we see that kind of stuff with sury sometimes ...

We could prevent explosive domino effects like this by adding constrains in our debian/control, for example requiring `nginx < 1.x` and similar stuff for other critical packages... Maybe `openssl` (to be confirmed if that doesn't create huge conflicts with sury...)

Unfortunately we can't really do this in Stretch right now because that would mean people with backport packages end up stuck in Stretch, but we can do this for Buster in early stage.

**Comment by Josue-T** [comment]
Hello,

Today the issue is with libxml2 also upgraded by sury and it break synapse. cf https://github.com/YunoHost-Apps/synapse_ynh/issues/193#issuecomment-619909756

**Comment by maniackcrudelis** [comment]
libxml2 is a dependency of php-xml, if sury can't install its own libxml2, I think we may have issues with all install scripts that use php-xml

**Comment by Rafi594** [comment]
libxml2-dev is present in the repo https://packages.sury.org/php/pool/main/libx/libxml2/ but when running apt install libxml2-dev the debian version is installed and cause dependency problem because version does not match.

**Comment by maniackcrudelis** [comment]
@Rafi594 could you elaborate on what you were expecting and what did you actually do ?

If you run apt install libxml2-dev, you will have the debian version, this is expected.
Is the problem that you had libxml2 from sury and you did install separately libxml2-dev ?

**Comment by Rafi594** [comment]
@maniackcrudelis Yes it's because libxml2 is from sury

**Comment by frju365** [comment]
> libxml2-dev is present in the repo https://packages.sury.org/php/pool/main/libx/libxml2/ but when running apt install libxml2-dev the debian version is installed and cause dependency problem because version does not match.

Doesn't the problem come from Priority of/for the repository ? (PIN)

**Comment by maniackcrudelis** [comment]
> @Rafi594 could you elaborate on what you were expecting and what did you actually do ?

...

> Doesn't the problem come from Priority of/for the repository ? (PIN)

The pinning for sury especially doesn't allow to get dependencies from its repo for anything that is not directly php related.
For sure we could add some other pin.
But I feel like we're going to have endless issues of that kind...

**Comment by Rafi594** [comment]
The log when trying to install libxml2-dev with libxml2 from sury
`libxml2-dev : Depends: libxml2 (= 2.9.4+dfsg1-2.2+deb9u2) but 2.9.9+dfsg-1+0~20200226.5+debian9~1.gbp3b6674 is to be installed`

**Comment by frju365** [comment]
> The pinning for sury especially doesn't allow to get dependencies from its repo for anything that is not directly php related.
For sure we could add some other pin.

yes.

I think this issue can be related to https://github.com/YunoHost/issues/issues/1577. Don't know, if having php optional could solve the pb. My only suggestion to solve problem of synapse and php either, is to use ONLY sury repo for libxml2 and PHP, that means giving an higher PIN for Sury... :/ Not sure it's what we want.

Original Issue was about backports and extra: I think for backports, we have to make it difficult installing packages from backports, because most of them are quite unstable from my point of view.

**Comment by alexAubin** [comment]
I haven't digged all the details, but I wouldn't be surprised that we simply hit an impossibility to have two pieces of software installed at the same time.

Thing is, a distribution like Debian ain't just a bunch of .deb strapped together ready to get downloaded. The team of maintainer probably pays some attention to not create some huge inconsistency like ... imagine if firefox requires libpng < 3.5.x but vlc requires libpng > 3.6.x. Then it means you could not have both firefox and vlc installed at the same time !? You don't want this.

So not expected that we encounter this if we stay on Debian Vanilla. But as soon as you start adding extra repo that superseed some of the vanilla stuff, and if the maintainer of those repo don't pay attention to this, it's not really surprising that we end up with package A requiring DEP <= X, and package B requiring DEP > X and you can't install A and B together for some super technical back-end incompatibility ...

**Comment by maniackcrudelis** [comment]
Damn @Rafi594, context !

When reading that (small) piece of log
> libxml2-dev : Depends: libxml2 (= 2.9.4+dfsg1-2.2+deb9u2) but 2.9.9+dfsg-1+0~20200226.5+debian9~1.gbp3b6674 **is to be** installed

What I understand is that `libxml2` is going to be installed **from** sury, not that `libxml2` **is** installed from sury. Which is a completely different situation !
So, what the context of that error !?

@frju365 I don't think it will really solve any issue to not have php. Anyway, the problem can happen only if you have installed a package from sury, so you do have php anyway.

Backport packages are not unstable, and that quite the purpose of backport. Backport are packages that do not break Debian the way Aleks explained.
But, still, we still do have quite a lot of packages from extra repositories. And even if now we have helpers to prevent the mess of a repo without a pin.
It does not prevent an user of adding manually a repo, it's unfortunately a so common instruction over internet...

But indeed to include completely sury is a question we should investigate, we're moving to Buster with php7.3, but php7.4 is already the last stable...
We're far from getting rid of sury...

**Comment by Rafi594** [comment]
I have the full log of the failed synapse installation https://paste.yunohost.org/ucocaribel

**Comment by Rafi594** [comment]
I can try to reproduce this in a VM

**Comment by maniackcrudelis** [comment]
I doubt you would have the same situation in a VM, you won't have sury.
Do you know from where does sury come from ?

Is your sury repo pinned ?

**Comment by Rafi594** [comment]
I think it come from nextcloud

The sury repo is pinned

``` 
 200 https://packages.sury.org/php stretch/main amd64 Packages
     release o=deb.sury.org,n=stretch,c=main,b=amd64
     origin packages.sury.org

```

**Comment by maniackcrudelis** [comment]
Can I see the pin config ?
It shouldn't request a dependency from sury.

**Comment by maniackcrudelis** [comment]
With a pin at 200
> causes a version to be installed **unless there is a version available belonging to some other distribution** or the installed version is more recent

It should take the dependency from debian repo.
It has been painfully tested...

**Comment by alexAubin** [comment]
Attempt to implement idea from initial post : https://github.com/YunoHost/yunohost/pull/967

**Comment by maniackcrudelis** [comment]
Again an issue with sury.

This time with weblate.
Webate needs libglib2.0-dev, but the dependency is taken from sury instead of debian, even though the debian version would be ok.

The pin config:
```
Package: *
Pin: origin "packages.sury.org"
Pin-Priority: 200

Package: php7.0*
Pin: origin "packages.sury.org"
Pin-Priority: 600
```
`apt install --dry-run libglib2.0-dev` gives:
```
The following packages have unmet dependencies:
 libglib2.0-dev : Depends: libpcre3-dev (>= 1:8.31) but it is not going to be installed
```
`apt-cache policy libpcre3-dev` gives:
```
libpcre3-dev:
  Installed: (none)
  Candidate: 2:8.39-3
  Version table:
     2:8.43-1+0~20190710.6+debian9~1.gbpbfc49f 200
        200 https://packages.sury.org/php stretch/main amd64 Packages
     2:8.39-3 500
        500 http://ftp.debian.org/debian stretch/main amd64 Packages
```

**Comment by maniackcrudelis** [comment]
An install of `libpcre3-dev` gives more hints:
```
The following packages have unmet dependencies:
 libpcre3-dev : Depends: libpcre3 (= 2:8.39-3) but 2:8.43-1+0~20190710.6+debian9~1.gbpbfc49f is to be installed
```
And an apt-cache policy finally give something interesting:
```
libpcre3:
  Installed: 2:8.43-1+0~20190710.6+debian9~1.gbpbfc49f
  Candidate: 2:8.43-1+0~20190710.6+debian9~1.gbpbfc49f
  Version table:
 *** 2:8.43-1+0~20190710.6+debian9~1.gbpbfc49f 200
        200 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     2:8.39-3 500
        500 http://ftp.debian.org/debian stretch/main amd64 Packages
```

Reproducing the issue kay0u had, I installed snipeit first, which certainly had libpcre3 as a dependency.
So it appears that the problem is not that apt does not respect the pinning priority. The problem is indeed about dependencies.
`libpcre3-dev` want an exact version of `libpcre3`. But another version is already installed...

**Comment by alexAubin** [comment]
This topic should really be split into a separate topic to discuss sury specifically but anyway ...

During today's meeting we discussed again the possibility to use phpenv and php-build and other similar solutions, but they sound like a dead-end because they require locally compiling php binaries and that's really a no-go for low-end devices.

Alternatively, we discussed an epic hack which could be : 

- setup a chroot with deboostrap (that part is not free though, it requires a non-neglicible amount of time even on a high-end hardware, but it only done once)
 - add sury inside the chroot and install php7.3 and all the php7.3-module you want inside it (but *not* in the host)
- in the host, create some /usr/local/bin/php7.3 and /usr/local/bin/php7.3-fpm that would launch the php7.3(-fpm) from the chroot, with the right `LD_LIBRARY_PATH` and [`extension_dir`](https://www.php.net/manual/en/ini.core.php#ini.extension-dir) and any other variables to load libs *from the chroot instead of the host*
- that way, all php7.3 libs are "containerized" in the chroot and won't create conflict on the host that can remain a "vanilla" debian...

In terms of actual commands, that yields something like : 

```bash
# Setup chroot
PHPCHROOT="/root/my_php_chroot/"
debootstrap stretch $MYCHROOT

# Add sury and install php7.3
echo "deb https://packages.sury.org/php/ stretch main" > $PHPCHROOT/etc/apt/sources.list.d/sury.list
curl https://packages.sury.org/php/apt.gpg | chroot $PHPCHROOT apt-key add
chroot $PHPCHROOT apt install apt-transport-https
chroot $PHPCHROOT apt install php7.3-fpm php7.3-curl

# Link libs and conf from chroot to host
ln -s $PHPCHROOT/etc/php/7.3 /etc/php/7.3
ln -s $PHPCHROOT/usr/lib/php/20180731 /usr/lib/php/20180731

# Launch / test php
# (this could be turned into an alias-like things in /usr/local/bin)
export LD_LIBRARY_PATH=$PHPCHROOT/usr/lib/:$PHPCHROOT/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH
$PHPCHROOT/usr/bin/php7.3  -i
$PHPCHROOT/usr/sbin/php-fpm7.3 -i
```

(Yes, this is like the ugliest hack ever)

So far I don't even know if this would actually work on the battlefield ... Kay0u had trouble running this (may or may not be related to running this in an unprivileged container)

ljf really wonders if the same kind of things couldn't already be achieved with composer ... (Or *nix)  ... But we're lacking expertise about PHP :|

**Comment by autra** [comment]
Nix could theoretically do this I think. And nixpkgs contains php 7.2, 7.3 and 7.4. As we can install nix on debian, I'm very tempted to try this actually.

The question is : how many packages will we need to create for nix if we follow this path? Can we use a mix of nix packages and debian? Ex php-foo uses libfoo, what happens if libfoo is *also* installed as a debian package?

I'll see if I can experiment some stuff.

**Comment by alexAubin** [comment]
https://github.com/YunoHost/yunohost/pull/967 got merged so let's close this
