### ISSUE TITLE
We should never restart nginx if nginx -t is not happy

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1566]
Dunno exactly but we should try to figure out all the places where we're likely to restart nginx and try to test before it that nginx -t is happy ... 

Things I can think about : 
- python code
- regen-conf
- ynh_system_helper (usually people should use reload-or-restart but in case they use restart we should check nginx -t)
- ...

Same thing could be done with other essential services that allow to test the config (e.g. php7.0-fpm)

**Comment by maniackcrudelis** [comment]
Sure a reload does not break nginx if a file is not correct ?

But for sure, it could be included into the helpers.

**Comment by alexAubin** [comment]
Yeah a reload doesn't break the service if it's already correctly running... But I'm pretty sure at least in the regen-conf we sometime brutally restart the service without checking nginx -t
