### ISSUE TITLE
Make it explicit that email address asked during user creation is a *local* address

### ISSUE THREAD

**Issue by sucrecacao** [YunoHost/issues#1567]
After installing yunohost in docker, I tried to add a new user with `yunohost user create ron` but couldn't because yunohost doesn't recognize tutanota adress. 
Unfotunatly is the only address I have. Any workaround ?

**Comment by sucrecacao** [comment]
Ok I get it. It has to finish with the domain name we set up.

If found it out by using the web interface. Maybe the CLI could be more explicit about it ?

**Comment by alexAubin** [comment]
Should be addressed by https://github.com/YunoHost/yunohost/pull/962 and https://github.com/YunoHost/yunohost-admin/pull/298

**Comment by alexAubin** [comment]
Fixed via https://github.com/YunoHost/yunohost/pull/962
