### ISSUE TITLE
No domain.conf created when adding new sub domain

### ISSUE THREAD

**Issue by klorydryk** [YunoHost/issues#1568]
YunoHost 3.7.1.1 (stable).

I added a new domain (exactly, a sub domain of a domain already managed by my Yunohost), but couldn't add let's encrypt on it. I discovered that in _/etc/nginx/conf.d/_ , no _domain.conf_ had been created, only the directory _domain.info.d_

The log file of "add domain":
https://paste.yunohost.org/raw/obosoxaguv

I did it multiple times. Fun is that when I remove the domain, this files are not removed either...

**Comment by alexAubin** [comment]
Should have been fixed by https://github.com/YunoHost/yunohost/pull/946
