### ISSUE TITLE
On the doc, clicking on a page link doesn't scroll back to the top of the page, it's a bit annoying :/ 

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1569]
For example, go to : https://yunohost.org/#/boot_and_graphical_install 
Scroll down, click on link about postinstall
You end up on https://yunohost.org/#/postinstall but at the bottom and have to scroll back to the top ...

**Comment by kay0u** [comment]
I can't reproduce :-/

**Comment by alexAubin** [comment]
Sorry for the noise, that's some ublock origin doing some funky stuff
