### ISSUE TITLE
Firefox mobile and SSOWAT user panel

### ISSUE THREAD

**Issue by farvardin** [YunoHost/issues#1571]
On Firefox mobile (android), when we touch the SSOWAT button, the screen fades away, but instead of returning to the YunoHost panel selection, we only get a blank screen.

On Chrome mobile, we can switch back to YunoHost panel without problem.

**Comment by Aeris1One** [comment]
Cannot repro, I use Fenec F-Droid (The Firefox version available on F-Droid).

**Comment by farvardin** [comment]
I've tested with Fennec, it's the same. 
I have this with (among others) Sogo, diagrams.net, netdata...

I have this on 2 differents yunohost instances, but not on an other one. I'll investigate further then... (all of them are working with chrome)

**Comment by Aeris1One** [comment]
I cannot repro this bug on SOGo and Hextris.
As I removed the user panel from my Etherpad I cannot test.
It can be a bug from your server maybe, what version are you using ?

**Comment by SilverViper** [comment]
No issues here with Fennec and IceCat mobile.

**Comment by Aeris1One** [comment]
Do you have any "exotic" config ? What is your arch and have you edited some config?

**Comment by farvardin** [comment]
I have latest version everywhere, the only difference is I have edited

`/usr/share/ssowat/portal/assets/themes/default/custom_portal.css`

et added at the end:

```
body {
	background-color: #353b43;
}

```

I've also customised the logo to replace with my own, on:

`/usr/share/ssowat/portal/assets/img/logo-ynh-white.svg`

(the original logo is still present in the overlay)

I've disabled this to go back to normal, but it's the same. The 3rd server has the SSOWAT working as expected on firefox, it's puzzling me.

All of them are 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux

I don't remember having set anything "exotic" on any of them.

**Comment by SilverViper** [comment]
Does the issue also occur when you do a private browsing session/incognito?

**Comment by Aeris1One** [comment]
If incognito browsing is working, I suggest you to clear cookies/cache from your browser.

**Comment by farvardin** [comment]
still the same in incognito browsing.

What I've tried/discovered so far:

- About my 3 YNH instances: the "mobile firefox" bug is present on only two of them. I've also tried firefox mobile on https://demo.yunohost.org/, and the SSOWAT button is working as expected. So it's probably something on the 2 YNH instances, BUT:
- the button is working fine on the 3 YNH servers with Chrome mobile
- the button is working fine on the 3 YNH servers with Firefox Desktop
- the 3 YNH servers have roughtly the same apps on them (nextcloud, only office...)
- I've changed my "custom" theme back to the "light" one in /etc/ssowat/conf.json.persistent
- I've put back the original logo, but it should change anything since the light theme is using logo-ynh.svg and not logo-ynh-white.svg
- same firefox mobile behavior on another phone
- with the light theme on chrome the screen is fading from the app to white, since the background is white. On the two servers with the bug, the screen is fading to black (regardless of the theme used). Here is a picture:

![96007754_596761974380587_3725990107598028800_n](https://user-images.githubusercontent.com/477243/81037738-19643600-8ea4-11ea-97de-734704e98cc9.jpg)

I've also made a video: https://www.youtube.com/watch?v=Vrf4OGnctFk

It's a minor bug, but it's a bit annoying...

If you can think of some files I could check or modify, I'll test them.

The ynh_overlay.css files are the same, and there is nothing in custom_overlay.css

**Comment by alexAubin** [comment]
Closing because we're removing the "ssowat button" in the SSO/portal refactoring in bookworm
