### ISSUE TITLE
Bug in "Redirect domain root to this application" - Redirection in circle

### ISSUE THREAD

**Issue by cabbie395** [YunoHost/issues#1572]
Hi there,

## The issue
The "Redirect domain root to this application" feature creates a loop in redirection, and leads to a "The page isn’t redirecting properly" issue in browsers.

## Past actions:
- fresh install on Debian 9 using curl
- finish post-install
- adding main domain
- add let's encrypt certificate
- add sub-domain www
- adding let's encrypt certificate
- install wordpress app using web interface on www (at /)
[at this step, everything works as expected]
- click on Redirect domain root to this application
[redirection issue from www]

## Resolved by:
- ssh yunohost server
- edit /etc/ssowat/conf.json.persistent

from
`{"redirected_urls": {"www.domain.tld/": "www.domain.tld/"}}`

to 
`{"redirected_urls": {"domain.tld": "www.domain.tld/"}}`

**Comment by alexAubin** [comment]
Should be fixed by https://github.com/YunoHost/yunohost/pull/953
