### ISSUE TITLE
ynh_systemd_action issue

### ISSUE THREAD

**Issue by yalh76** [YunoHost/issues#1573]
That was difficult to reproduce but at least I was able to.
Doing several manual consecutive backups using `yunohost backup create --apps wekan --debug` cause of: https://github.com/YunoHost-Apps/wekan_ynh/issues/77

Here are a backup log:
https://paste.yunohost.org/ehiyalumew.bash

We can see that for `ynh_systemd_action` the wekan service is not started...
`ynh_systemd_action` is looking at a `line_match` `Started Wekan, task board`
https://github.com/YunoHost-Apps/wekan_ynh/blob/46f4b540cb99090a3fe1d35828094dbbfb34b692/scripts/backup#L79

But in the logs, line 1982, the line_match is present and manually doing `journalctl -feu wekan` I can see that ekn service is started

In the logs we can see that `ynh_systemd_action` is looking in `/tmp/tmp.hw3d0aV18A` for the line_match.

Here is the content of `/tmp/tmp.hw3d0aV18A` catch during the backup: 
https://paste.yunohost.org/kigezunivi.bash

As we can see, `/tmp/tmp.hw3d0aV18A` is missing the first line/aka line 1982.

It's like `ynh_systemd_action` started to log systemd too late...

To move forward, I replaced `ynh_secure_remove "$templog" 2>&1` by `true` in https://github.com/YunoHost/yunohost/blob/37fd69653a13e7cd90c61df8fbb52580d143f776/data/helpers.d/systemd#L175

And I've done several additional backups. Most of them are OK but one time for `ynh_systemd_action` wekan service is not started

Content of /tmp :
https://paste.yunohost.org/gazeridica.hs

During the 8 consecutive backups `ynh_systemd_action` considered that wekan service didn't started one time, corresponding to `tmp.vQAVWTISna`

Here is the content of the failed start: https://paste.yunohost.org/toriqilefo.pl
For other backups, the content of the tmp file is still the same: 
For the first one corresponding to `/tmp/tmp.gnkolo8qMD` : https://paste.yunohost.org/lixiqogehu.css
For the last one corresponding to `/tmp/tmp.LoEcGtPIWo`: https://paste.yunohost.org/yobizobeji.css

**Comment by maniackcrudelis** [comment]
Sorry but I'm little bit too lazy to read all those logs right now.
But to recapitulate, the first line was missing but the service did start so fast that it was actually into the first line.
I thought we had fix that...

Edit: Actually reading again the helper. It follows the log before doing anything with the service...
So it shouldn't be possible that it miss anything.
Does the log exist before the helper is called ?

**Comment by yalh76** [comment]
yes exactly... First line of the temporary logs is missing

Sorry I wanted to provide as much details as possible. As I do not know how to solve that issue alone.

**Comment by maniackcrudelis** [comment]
I would say that there's never too much log to help.
It's just that right now, I'm lazy :grin:

**Comment by yalh76** [comment]
> 
> 
> Sorry but I'm little bit too lazy to read all those logs right now.
> But to recapitulate, the first line was missing but the service did start so fast that it was actually into the first line.
> I thought we had fix that...
> 
> Edit: Actually reading again the helper. It follows the log before doing anything with the service...
> So it shouldn't be possible that it miss anything.

I fully agree with you, it's why I provided as much informations as possible because it shouldn't do that

> Does the log exist before the helper is called ?

No the log file doesn't exits before the helper is called.

**Comment by yalh76** [comment]
> 
> 
> I would say that there's never too much log to help.
> It's just that right now, I'm lazy 😁

Nothing urgent. Just I remember having opened an issue few month ago about that but I wasn't able to reproduce... now I can ^^

on:
```
packages:
  yunohost:
    repo: stable
    version: 3.7.1.1
  yunohost-admin:
    repo: stable
    version: 3.7.1.1
  moulinette:
    repo: stable
    version: 3.7.1.1
  ssowat:
    repo: stable
    version: 3.7.1.1
```

**Comment by maniackcrudelis** [comment]
> No the log file doesn't exits before the helper is called.

Is it a dedicated log or syslog ?
But I was considering maybe -F with tail, although I never seen it miss a line. But you're using systemd, so journalctl...

**Comment by yalh76** [comment]
Its' dedicated log created by `ynh_systemd_action` at :

https://github.com/YunoHost/yunohost/blob/37fd69653a13e7cd90c61df8fbb52580d143f776/data/helpers.d/systemd#L104

**Comment by yalh76** [comment]
> 
> 
> > No the log file doesn't exits before the helper is called.
> 
> Is it a dedicated log or syslog ?
> But I was considering maybe -F with tail, although I never seen it miss a line. But you're using systemd, so journalctl...

I've seen that sometimes but wasn't able to reproduce or identify...

**Comment by maniackcrudelis** [comment]
Oh ok, but I was talking about the log of the app, not the temporary one.

**Comment by yalh76** [comment]
> 
> 
> Oh ok, but I was talking about the log of the app, not the temporary one.

Sorry misunderstanding... no it's systemd logs

`ynh_systemd_action --service_name=$app --action="start" --log_path=systemd --line_match="Started Wekan, task board"`

**Comment by maniackcrudelis** [comment]
Since you already duplicated the helper (if you have removed the rm line), could you try with a touch of the log ?
Here https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/helpers.d/systemd#L105

I doubt it would solve anything, but actually that situation is not possible for me. So... let's try ;)

**Comment by yalh76** [comment]
I will try that. replacing `/usr/share/yunohost/helpers.d/systemd` by the one from stretch-unstable and doing several backups

**Comment by maniackcrudelis** [comment]
Huh, I don't think we have fixed anything in unstable.

Just maybe if the file is created before the command start to write into it, who knows, maybe an I/O strange thing.

**Comment by yalh76** [comment]
Well. tests made:
with stretch-stable : 73 test and 4 KO with the wekan service doesn't start
when adding a sleep 2 in the helper: 86 test all are OK....

**Comment by maniackcrudelis** [comment]
Just thinking again about it @yalh76 
You have a message saying that the service didn't start on time.
But, it doesn't actually fail the script.

So, is it really a problem, aside of being obviously annoying.

**Comment by yalh76** [comment]
If for `ynh_systemd_action` the service fails to start, the backup script doesn't fail

But I don't know how it's managed during install or upgrade, if `ynh_systemd_action` detect that the service fails to start, did it revert the install or the upgrade ?

And when `ynh_systemd_action` fails to catch the first line, you have to wait the 300 seconds / 5 minutes of the timeout...

**Comment by maniackcrudelis** [comment]
No the behavior is to wait until the line is match or the timeout, but in any case, it won't fail.
This part of the helper is just an adaptive sleep.

It's up to the actual script that has call the helper to actually fail if there's really a reason for it.
More often, it fails later or you have a 502 at the end.

Obviously, it's only if the service didn't fail to perform the action. That's another situation.

I was wondering because, while it's clearly annoying to have to wait until the time out (is 300 really needed ?) a sleep into the helper is going to affect everyone, not only 4 out of 73.

**Comment by yalh76** [comment]
Well, as it won't fail, I close this issue and the associated PR :)
Thanks for the time took on that ^^
