### ISSUE TITLE
Making mariadb, php and metronome optional

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1578]
The aim of this issue is to track progress on removing the dependency to the Mariadb/Mysql server and only require it when it is actually needed.

**Comment by Glandos** [comment]
Is it really needed for now? Is it at least possible to stop the service to save some memory?

**Comment by alexAubin** [comment]
Yes, unless some apps you installed depends on it. Otherwise it's not used by Yunohost itself.

**Comment by alexAubin** [comment]
Copypasta some comment in another issue:

>I believe it would be indeed relevant to have some concept of "system modules" (or whatever you call this) that can be enabled / disabled. 
>
>For example, we have the opposite situation for postgresql where it would be nice to have its configuration and other things managed by the regen-conf, and it would be useful to have this defined directly in the core ... but currently it's not possible because the regen-conf will assume that the corresponding system packages is installed. So far it's handled by the bash helpers but it remains a bit hackish and not practical when you need to push changes in the conf as it happened recently. And more and more I end up adding hacky patches in the python code like "if postgresql is installed" or "if service_name == postgresql" ...
>
>Could also be a middle-ground for ljf's long-term wish to have openvpn / vpnclient installed by default (which I disagree with :sweat_smile: ) ... but would definitely make sense if this would be a module that can be enabled/disabled.

**Comment by alexAubin** [comment]
Closing because it's now one step further in bookworm
