### ISSUE TITLE
Issue with credentials on etherpad

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/issues#1579]
https://github.com/YunoHost-Apps/etherpad_mypads_ynh/issues/3#issuecomment-620144675

The address `domain.tld/pad/admin/` is behind a global skipped_uris and prompt a basic_auth pop-up to ask for credential.

On YunoHost 3.6.5.3
No problem, you can put your credentials and goes on.

On YunoHost 3.7.1.1
If you're logged into the SSO, you can't log in with your credential. The credential are refused and asked again.
If you're not logged into the SSO, you can log in without any trouble.

**Comment by alexAubin** [comment]
Not sure what happens but the content of ssowat.conf should contain some clues :s

**Comment by maniackcrudelis** [comment]
Indeed...
```
    "unprotected_urls": [
        "crudelis-test6.fr/pad"
    ],
```
It wasn't a random skipped_uris...
It doesn't work with unprotected_urls...
It was on fucking purpose !!!

Nice to see that fucking wonderful permission system has been tested before a wide release...

**Comment by maniackcrudelis** [comment]
Probably I was stupid enough to just check my `settings.yml` that actually contains a...
> **skipped_uris: /**

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost-Apps/etherpad_mypads_ynh/pull/147
