### ISSUE TITLE
Prevent Nginx from overwriting CSP headers of proxy

### ISSUE THREAD

**Issue by filips123** [YunoHost/issues#1580]
I'm trying to update [ZeroNet](https://github.com/YunoHost-Apps/zeronet_ynh) package and make it compatible with newer versions and add better integration. However, I have a problem with Nginx config which prevents ZeroNet from functioning properly.

Problem is that ZeroNet relies on `Content-Security-Policy` and `X-Frame-Options` headers to correctly support its iframe and WebSocket connection. Those headers are set by its Python server which is behind Nginx proxy.

This is proxy's config provided by ZeroNet package:

```nginx
location / {
    if ($scheme = http) {
        rewrite ^ https://$server_name$request_uri? permanent;
    }

    proxy_pass http://127.0.0.1:__UI_PORT__; # Changed to correct port in install script
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    # For long-live WebSocket connetion
    proxy_read_timeout 1h;
}
```

However, in main config file for that domain (`/etc/nginx/conf.d/domain.conf`), those headers are overwritten with:

```nginx
    more_set_headers "Content-Security-Policy : upgrade-insecure-requests";
    more_set_headers "Content-Security-Policy-Report-Only : default-src https: data: 'unsafe-inline' 'unsafe-eval'";
    more_set_headers "X-Content-Type-Options : nosniff";
    more_set_headers "X-XSS-Protection : 1; mode=block";
    more_set_headers "X-Download-Options : noopen";
    more_set_headers "X-Permitted-Cross-Domain-Policies : none";
    more_set_headers "X-Frame-Options : SAMEORIGIN";
```

This prevents ZeroNet's iframe from loading correctly and WebSocket from connecting:

```
[Report Only] Refused to connect to 'wss://domain/ZeroNet-Internal/Websocket?wrapper_key=WRAPPER_KEY' because it violates the following Content Security Policy directive: "default-src https: data: 'unsafe-inline' 'unsafe-eval'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
The Content Security Policy 'default-src https: data: 'unsafe-inline' 'unsafe-eval'' was delivered in report-only mode, but does not specify a 'report-uri'; the policy will have no effect. Please either add a 'report-uri' directive, or deliver the policy via the 'Content-Security-Policy' header.
The Content Security Policy 'default-src https: data: 'unsafe-inline' 'unsafe-eval'' was delivered in report-only mode, but does not specify a 'report-uri'; the policy will have no effect. Please either add a 'report-uri' directive, or deliver the policy via the 'Content-Security-Policy' header.
inject.js:10274 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://domain') does not match the recipient window's origin ('null').
```

Is there any way to fix this? Is it possible to force headers from ZeroNet's server instead of headers from Nginx?

Also, one other "issue" with CSP headers I noticed (that isn't related to ZeroNet app but to all YunoHost apps) is that `Content-Security-Policy-Report-Only` doesn't provide `report-uri`. This triggers browser console warning, but doesn't cause any other problems:

```
The Content Security Policy 'default-src https: data: 'unsafe-inline' 'unsafe-eval'' was delivered in report-only mode, but does not specify a 'report-uri'; the policy will have no effect. Please either add a 'report-uri' directive, or deliver the policy via the 'Content-Security-Policy' header.
```

Is this intentional or it should be fixed?

**Comment by alexAubin** [comment]
I'm a bit confused because all of these CSP and headers in general ain't 100% for me but here's an attempt: 

>Is there any way to fix this? Is it possible to force headers from ZeroNet's server instead of headers from Nginx?

If I remember correctly, you gotta also use `more_set_headers` in your sublocation and the point of using `more_set_headers` is precisely to be able to override specific headers in a consistent way (c.f. [this funny (no) thing about add_header](https://www.peterbe.com/plog/be-very-careful-with-your-add_header-in-nginx))

>Also, one other "issue" with CSP headers I noticed [...]

Yes, we don't have so much expertise about how to handle CSP correctly and so on ... overall that Report-Only policy ain't so useful anyway ... If I remember correctly at some point we tried to follow Mozilla's recommendation about it but it ended up being way too disruptive for apps. I don't know if it really matters to define a report-uri or not ... I don't even know what this really do :/ 

But anyway it sounds like your issue is more related to `X-Frame-Options`. There are a couple of apps like libreto which need to tweak that kind of stuff as well. Did you try to add some `more_set_headers` in the right location to set X-Frame-Options to a new value ?

**Comment by filips123** [comment]
> But anyway it sounds like your issue is more related to `X-Frame-Options`. 

I now checked which headers exactly are sent by ZeroNet and which by Nginx. I think that it isn't problem with `X-Frame-Options`. Nginx sets it to `SAMEORIGIN`, but ZeroNet also sets it to `SAMEORIGIN` so there aren't any differences.

Problem is probably with `Content-Security-Policy` because headers set by ZeroNet and Nginx are different.

> If I remember correctly, you gotta also use `more_set_headers` in your sublocation and the point of using `more_set_headers` is precisely to be able to override specific headers in a consistent way

ZeroNet dynamically generates `Content-Security-Policy` (because it also contains script nonce) so I can't just set a static value. Is it possible to dynamically set `more_set_headers` with value that came from ZeroNet's response?

**Comment by alexAubin** [comment]
I don't really understand how Yunohost's CSP header could break something considering we're in report only mode :/ But again, all this stuff is a bit fuzzy to me ..

Maybe you can try things using other `more_*_headers` instructions like `more_clear_headers` ?  c.f. https://github.com/openresty/headers-more-nginx-module#more_clear_headers ... but idk if that's what we're looking for ... Maybe something else in that doc ...

**Comment by filips123** [comment]
> I don't really understand how Yunohost's CSP header could break something considering we're in report only mode

I think that there are two headers, one in report only mode and one in normal mode. But CSP is weird :)

Anyways, I used

```
more_set_headers "Content-Security-Policy : $upstream_http_content_security_policy";
more_clear_headers "Content-Security-Policy-Report-Only"; 

```

to force header from ZeroNet and remove report-only header and now there are *fewer errors*. I think that those remaining errors are caused by Yunohost's SSO.

Error happens when page inside that iframe tries to load some other file (CSS or JS). Request for that file is instead redirected to request to some SSO page which fails because of CORB:

```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://yunohost.local/yunohost/sso/?r=SOMETHING with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

Here, `https://yunohost.local/yunohost/sso/?r=SOMETHING` is probably a SSO login page. When I navigate directly to it, it is correctly redirected to script URL (`https://zeronet.yunohost.local/1FZ37zSqKfmLvKPBdT6BUpsJBQhSc3Ncri/js/ZeroFrame.js`). However, because SSO page is on different domain than the app and uses MIME type `text/html`, it is blocked.

I think I know what causes this error. SSO login is done with cookies, right? However, because iframe is sandboxed, it won't be able to access cookies. So request to script won't contain SSO cookies, so Yunohost will think user isn't authenticated and redirect display login page.

Solution for this is to somehow include SSO cookies in request made by page in iframe. But I don't know how exactly should this be done...

**Comment by alexAubin** [comment]
I'm a bit lost regarding wether the issue is related to CSP, X-Frame, or SSO cookies ...

**Comment by alexAubin** [comment]
Related to https://github.com/YunoHost/yunohost/pull/1432

**Comment by alexAubin** [comment]
Closing in favor of https://github.com/YunoHost/moulinette/commit/328107c94699074cd00692451fd55589c96f16f2
