### ISSUE TITLE
Remaining ~small items for 3.8

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1582]
Trying to write this list somewhere because I keep forgetting about stuff that I think remain before declaring 3.8 complete on my side

- [ ] gather moar feedback and fix any outstanding issue found
- [ ] implement a `yunohost service update` - there are a few options that got added to `service add`, some related to diagnosis. But packagers should be able to tweak options of their app's service without being force to delete/re-add the service with new options.
- [ ] ~~implement a CLI action to add swap - since the diagnosis complains about lack of swap, and adding swap ain't trivial, we should have a `yunohost tools swap --add 1G` that does everything it should (including tweaking /etc/fstab)~~
- [ ] ~~add a check that swapiness is low if swap on sd card (you don't want swap to burn SD cards super fast .. that should be pretty easy to implement)~~
- [ ] remove the swap check for now ? (or see what we do with it)
- [ ] tweak messages (just messages, not code logic) about not being able to install certificate to point to diagnosis so they can have more accurate info and tips
- [ ] improve ux / messages from diagnosis cron job ? Dunno about this, maybe it's fine already, gotta think about ti
- [ ] do something about that 'Security' category in diagnosis .. there's only 1 security check (meltdown) which yields a message like 'No security issue at all!' if you're not vulnerable to meltdown .. that message is too broad and gives a false sense of security  .. I think it should be moved to "Base system" for now until we have more security checks (c.f. other issue out there about having security.json to easily push security notifications / checks...)
- [ ] ...?

Maybe that's already too much @.@

Then there's a bunch of PR that could make it to the 3.8 but there's already so much and that's gonna again delay everything ... at the same time these are cool important PR (e.g. mail relay, upgrade_only_if_version_changes, and others), dunno what do >.> Should probably discuss this during next meeting

**Comment by SohKa** [comment]
> implement a CLI action to add swap - since the diagnosis complains about lack of swap, and adding swap ain't trivial, we should have a yunohost tools swap --add 1G that does everything it should (including tweaking /etc/fstab)

It is maybe obvious, but I think if the main storage device is an SD card the user should be prevented from creating a swap area on it. If he does, it will probably kill the SD's performance.

Anyway, there is already optimizations for some SBC like the Lime 1 and 2 (probably all Armbian images, I don't know about the RPi's). By default, there is a swap area in a zram volume and the swappiness is set to 100 (aggressive swapping).

**Comment by alexAubin** [comment]
>It is maybe obvious, but I think if the main storage device is an SD card the user should be prevented from creating a swap area on it. If he does, it will probably kill the SD's performance.

What about setting the swapiness to 1 ..?

**Comment by SohKa** [comment]
That would be ok for device like the RPi's I guess.

But for Armbian-based system, I think it will negate the advantage of the swap in the zram volume. If you setup the swappiness to 1, it won't swap to the zram before the memory is almost full. And when it will be the case, there will be not enough memory left for the zram volume (since it is located in memory). Thus it will probably swap directly to the swap volume on the SD card.

But we may have an alternative. By default, the system first swaps to volumes with a higher priority (you can see the priority of a swap volume with `swapon -s`). The system will swap to volumes with a lesser priority once the volumes with higher priority are completely filled. So we can avoid touching to the swappiness by creating a swap volume on the SD card with a lesser priority than the one on the zram volume (by default, the swap on the zram volume has a priority of 5). This way the swap area on the SD card won't be used before the one on the zram volume is filled.

I hope my explanations are understandable...

**Edit**: I tried to improve a bit my explanations

**Comment by alexAubin** [comment]
Uuuuh wokay not sure to understand 100% xD What I understand naively is that setting swapiness to 1 should work but we should be careful to check that zram volumes (if any) have a higher priority (which I naively expect they will by default ..?)

**Comment by SohKa** [comment]
> Uuuuh wokay not sure to understand 100% xD

Sorry about this crappy explanation :/

> What I understand naively is that setting swapiness to 1 should work

It would, but again, it means the swap in the zram volume won't be used before there is almost no memory left.

Armbian takes advantage of zram (which is seen as a device by the system) because it compress the data moved to the swap (located on the zram device). And by setting the swappiness to 100, it will compress these data early enough to optimize the amount of free memory.

> but we should be careful to check that zram volumes (if any) have a higher priority

Yes, we should

> (which I naively expect they will by default ..?)

Yes, they will. By default the priority number of a swap volume is less than 0. The one created by Armbian on the zram is 5.

**Comment by alexAubin** [comment]
>It would, but again, it means the swap in the zram volume won't be used before there is almost no memory left.

Uh but this part I don't understand ... Is `1` a higher priority than `5` ?

My understanding is that what we're trying to achieve is to tell the system : 
- use zram as you normally would (well i guess there's no "normal" but uh)
- use swap but only if you really need it (which to me means swapiness=1 ?)

**Comment by SohKa** [comment]
Ok, I see the issue. [Here is](https://www.systutorials.com/how-to-set-swap-priority-in-linux/) what I meant by swap priority. This is different than swappiness.

One more detail : swappiness is global for all swap volumes. We can't change it only for one volume (like the one on the SD card and not for the one into the zram).

**Comment by alexAubin** [comment]
Oh ... But it just feels weird that zram is managed "as-swap-but-not-really-swap" ?

Anyway if I understand correctly now : 
- if there's no zram it's okay to set swappiness to 1
- if there's zram it's not okay to set swappiness to 1 and we should instead play with priorities ?

In fact there are other complex cases for that kind of cases like : 
- you have a swap file on  the SD card
- and another one on a hard drive

So what we really want it seems is a way to tell the system that "swapfile X stored on the SD card should only be used as a last resort" ?

Edit: or maybe in that case we want to tell the user that swap on sd card should be removed entirely ? But it's not clear to me if there's an interest having swap on the SD card if there's zram on the system ...

**Comment by SohKa** [comment]
> Oh ... But it just feels weird that zram is managed "as-swap-but-not-really-swap" ?

That's the way it is used by Armbian :/ I suppose they have their reason to do that. I couldn't find any good documentation about this (with actual tests).

> So what we really want it seems is a way to tell the system that "swapfile X stored on the SD card should only be used as a last resort" ?
>
> Edit: or maybe in that case we want to tell the user that swap on sd card should be removed entirely ? But it's not clear to me if there's an interest having swap on the SD card if there's zram on the system ...

Well, swap on zram is only meant to optimize a bit the amount of available memory for the system (by compressing the data). Adding a swap area on the SD card will extend the total amount of memory. So I would say, if it is certain that the SD card's performance won't completely drop when the system will start swapping, it could be worth creating a swap area on the SD card.

Basically, we have two parameters with which we can play : 
  * the swappiness : global for all swap volumes, it defines when the system will start swapping
  * the swap priority : specific for each swap volume, it allows the user to define in which order the swap volumes will be filled.

**Comment by alexAubin** [comment]
Following today's meeting, it sounds like this swapiness thing is far from trivial and we're going to drop/rework the swap check and postpone that warning about "you should add swap" + swapiness check etc for now (it you confirm that makes sense) to be able to move on with 3.8

**Comment by SohKa** [comment]
Ok, no prob. It's a good idea to avoid rushing.

**Comment by alexAubin** [comment]
Alright I implemented everything I was thinking about ... Remaining PR is https://github.com/YunoHost/yunohost/pull/985
