### ISSUE TITLE
Ajouter documentation SSO / LDAP

### ISSUE THREAD

**Issue by Plumf** [YunoHost/issues#1583]
> Salut,
>Je n’ai pas trouvé de docs pour le fonctionement de SSOWat ou l’intégration avec LDAP :
>Je trouve la doc pour le packaging d’application assez incomplète.
[src : forum.yunohost.org](https://forum.yunohost.org/t/application-login-by-ssowat-or-ldap/2028/5)
-------
Après relecture de la documentation je n'ai pas trouvé de document sur le LDAP.

**Comment by alexAubin** [comment]
Indeed, we should really write some doc about this at some point ...

Closing because duplicate of https://github.com/YunoHost/issues/issues/202
