### ISSUE TITLE
Nginx config folder not deleted

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost/issues#1584]
I created a sub-domain for Synapse and installed Synapse.

After a while, I decided to delete Synapse and the sub-domain.

Shouldn't Nginx configuration folder (`synapse.domain.ltd.d`) for this domain be deleted?

**Comment by alexAubin** [comment]
Hmmmyes and no, it's complicated if there are files inside it. But anyway the fact that this folder exist shouldn't hurt, it's just weird that an old stuff seems "still there"

Does the folder still contains file ?

**Comment by ericgaspar** [comment]
No it's empty.
