### ISSUE TITLE
Integrate VPNclient interface as an app config panel inside Yunohost admin

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1590]
The Internet Cube is mainly based on two applications (VPNClient and Hotspot) whose
integration with YunoHost shall be redesigned to make them more robust and less confusing in
their usage. This requires to enhance an already existing feature allowing applications to extend
the web administration GUI.

The goal of this ticket is to integrate VPNclient interface as an app config panel inside Yunohost admin and manage the upgrade of the app.

**Comment by alexAubin** [comment]
Closing because https://github.com/labriqueinternet/vpnclient_ynh/pull/80 is mainly pending due to 4.3 testing not being released as stable yet
