### ISSUE TITLE
Merge install.internetcu.be, the hypercube.sh script and the debug install interface

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1594]
Merge install.internetcu.be, the hypercube.sh script and the debug install interface to manage all aspects of configuration and installation in a single simple interface

**Comment by alexAubin** [comment]
c.f. 
- https://github.com/labriqueinternet/install
- https://github.com/YunoHost/arm-images/pull/7

Planning to work on https://github.com/YunoHost/issues/issues/1596 next, then we should be done on this milestone :tada:

**Comment by alexAubin** [comment]
Done / released
