### ISSUE TITLE
conf directory hard to find for some helpers

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/issues#1605]
Helpers using conf directory for resources have trouble in backup or restore (php helper is especially to be used in restore script) or in actions and config-panel.

Instead of using if else in each helper using the conf directory, a simple definition of a path for conf would be enough at the beginning of any helper file and then use in each helper needed it.

Could be as following:
```
if [ "$YNH_CWD" = "/var/cache/yunohost/from_file/scripts" ]
then
    conf_directory_path=../conf
elif [ "$YNH_CWD" = "/tmp/yunohost_remove/scripts" ]
then
    conf_directory_path=../conf
elif [ "$YNH_CWD" = "/etc/yunohost/apps/$YNH_APP_INSTANCE_NAME/scripts" ]
then
    conf_directory_path=../conf
elif [ "$YNH_CWD" = "/etc/yunohost/apps/$YNH_APP_INSTANCE_NAME" ]
then
    conf_directory_path=./conf
elif [[ "$YNH_CWD" =~ "/home/yunohost.backup/tmp/" ]]
then
    conf_directory_path=../settings/conf
fi
```

It is to be noted that php helpers won't work correctly in 3.8 without a proper handling of conf directory in restore script.

**Comment by kay0u** [comment]
I wonder if this conf_dir couldn't come from the core via an env var? Both work, which one would we prefer? I don't know

**Comment by alexAubin** [comment]
Closing because it's not clear to me what's the issue, but I think it's solved by the APP_BASE_DIR var (not sure about the exact name) introduced a few versions ago
