### ISSUE TITLE
Add pgp mime type in mod_http_upload of metronome

### ISSUE THREAD

**Issue by larchange** [YunoHost/issues#1608]
To be able to send over xmpp file with arbitrary extension with pgp encryption
conversations send a *.pgp file. But with default configuration it's rejected because the mime type is not allowed.

This can be solved by adding the following lines in the http_upload component configuration

```
 http_file_allowed_mime_types = {
      ["3gp"] = "video/3gpp",
      ["aac"] = "audio/aac",
      ["bmp"] = "image/bmp",
      ["gif"] = "image/gif",
      ["jpeg"] = "image/jpeg",
      ["jpg"] = "image/jpeg",
      ["m4a"] = "audio/mp4",
      ["mov"] = "video/quicktime",
      ["mp3"] = "audio/mpeg",
      ["mp4"] = "video/mp4",
      ["ogg"] = "application/ogg",
      ["png"] = "image/png",
      ["qt"] = "video/quicktime",
      ["tiff"] = "image/tiff",
      ["txt"] = "text/plain",
      ["pgp"] = "text/plain",
      ["xml"] = "text/xml",
      ["wav"] = "audio/wav",
      ["webm"] = "video/webm"
  }
````
Or should this be modified directly in metronome ?

**Comment by alexAubin** [comment]
Closing because the plan is more to go towards metronome-as-an-app rather than handling all its complexity from YunoHost core ...
