### ISSUE TITLE
Diffie-Hellman parameters regression

### ISSUE THREAD

**Issue by SohKa** [YunoHost/issues#1611]
Hello !

Since the release 3.8 (more precisely since [this PR](https://github.com/YunoHost/yunohost/pull/913/files) has been merged), the nginx config supports weak Diffie-Hellman groups (1024 bits). Thus the nginx setup is less secure in the release 3.8 than in the 3.7 (even with the "modern" nginx configuration).

By testing your server with https://www.ssllabs.com, you will notice it complains about weak DH key exchange parameters.

By removing all ciphers beginning with "DHE" (`DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384`), sslabs will stop complaining.

**Comment by lhp22** [comment]
If that can be useful : here are the recommandations from Mozilla Fundation for SSL/TLS server side configuration : https://wiki.mozilla.org/Security/Server_Side_TLS

**Comment by alexAubin** [comment]
@lhp22 : yes we already use the recommendation from Mozilla using their automatic conf generation tool ... but I believe the difference is that we rely on default DH params (c.f. [this issue](https://github.com/YunoHost/issues/issues/93)) so my guess is that that's the cause behind what @SohKa reports...

**Comment by SohKa** [comment]
You're right @alexAubin. The default DH params are the cause of this regression.

I've proposed [a solution](https://github.com/YunoHost/issues/issues/93#issuecomment-633510357) in the issue you referenced.

**Comment by SohKa** [comment]
The problem has been fixed in the version 3.8.4.8 of yunohost. [SSL Labs](https://www.ssllabs.com/) now gives a A+ rate.
