### ISSUE TITLE
Diagnostic issue : no v6 connectivity detected

### ISSUE THREAD

**Issue by taziden** [YunoHost/issues#1612]
Hi,
Diagnostic tells me there is no v6 connectivity despite the fact there is.
How is it checked?

**Comment by alexAubin** [comment]
Well uh code is here : 

https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/hooks/diagnosis/10-ip.py#L102-L140

(and it also tries to basically `curl ip6.yunohost.org` at some point)

Note that on internet cube there's some non-trivial checks because it looks for a default-ish route

**Comment by taziden** [comment]
Ok, I think I get it. I'm using Wireguard and the default route doesn't appear in the default table shown by ip -6 route.
To have the default, you have to parse the result of : `ip -6 route show table unspec`

**Comment by taziden** [comment]
Fixed by https://github.com/YunoHost/yunohost/pull/997
