### ISSUE TITLE
Diagnostic issue: missing DNS records

### ISSUE THREAD

**Issue by taziden** [YunoHost/issues#1613]
Hi,
Seems like there is an issue with AAAA records.
For all my domains, I got this message : 
"L’enregistrement DNS de type AAAA et nom @ ne correspond pas à la configuration recommandée. Valeur actuelle : <my_actual_ipv6_address> Valeur attendue : None"

**Comment by taziden** [comment]
Could it be related to #1612 ?

**Comment by alexAubin** [comment]
Yes, because the diagnosis thinks you have no IPv6 at all and therefore having an IPv6 could be troublesome (like people trying to join your server would fail, or acme challenge would fail)

**Comment by taziden** [comment]
Ok so I'm closing this issue then :-) Thanks!
