### ISSUE TITLE
yunohost: error: invalid choice: 'diagnostic'

### ISSUE THREAD

**Issue by sy6sy2** [YunoHost/issues#1616]
Hi,

During my last upgrade I get:

```
Attention : Pour voir les problèmes détectés, vous pouvez accéder à la section Diagnostic du webadmin ou exécuter « yunohost diagnostic show --issues » à partir de la ligne de commande.
```

But a `sudo yunohost diagnostic show --issues` gave me a `yunohost: error: invalid choice: 'diagnostic'`.

I guess the correct command is `sudo yunohost diagnosis show --issues`so the error message needs to be fixed 😉

**Comment by alexAubin** [comment]
Meh I thought this was fixed during the latest hotfix release but it's still pending here ... https://github.com/YunoHost/yunohost/pull/996/files

We'll make another hotfix release soon™

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost/commit/b4730751bf853c135cb96fcafea674d9d8c80501
