### ISSUE TITLE
Diagnosis raise "web" errors that don't seem appropriate

### ISSUE THREAD

**Issue by eauchat** [YunoHost/issues#1619]
Since recent yunohost update, the new diagnosis feature (which looks awesome :)) sends a warning I don't really understand.
Not sure if it's an issue or just that I don't understand it, so tell me if it's the latter.

All domains I use raise the following errors:
> Domain mydomain.tld appears unreachable through HTTP from outside the local network. 
It looks like another machine (maybe your internet router) answered instead of your server.
> Domain cloud.mydomain.tld appears unreachable through HTTP from outside the local network. 
It looks like another machine (maybe your internet router) answered instead of your server.
...

I'm in a specific setup where yunohost is in a virtual machine, so behind the reverse proxy of the main machine. But the reverse proxy is properly configured and all the domains and apps on them are accessible and working.
So it seems the diagnosis is failing on that, but I don't really understand why.

I think I can just ignore the warning, but maybe if there is another fix, or a coming fix to the diagnosis system, I can wait.

Thanks a lot :)

**Comment by alexAubin** [comment]
Hmmmyeah

Can you first make sure to run `yunohost app ssowatconf` and re-run the check ?

If that doesn't solve the issue : basically the diagnosis tries to reach (using HTTP, port 80) the uri /.well-known/ynh-dianosis/some_random_id (note that the file some_random_id is created automagically during diagnosis time)

So naively I would first check that the reverse proxy isn't interfering when doing that

**Comment by eauchat** [comment]
Ok, I think I get it.
Thanks @alexAubin for the strikingly swift reply :)

So I ran `yunohost app ssowatconf` and same issue.
But from your description, I understand that the diagnosis fails because the reverse proxy doesn't let http traffic pass, only https.
So I think my only bet in this is just to ignore the warning.
It's a pity not to be able to use the builtin yunohost tool (but I can achieve similar diagnosis with other tools as well, so not a huge deal).

Maybe I'm diverging out of the issue a bit, but just wondering of the reason behind having the diagnosis done in http (port 80) and not https (port 443), or trying both.

**Comment by alexAubin** [comment]
Diagnosis could also be done on 443 indeed, but port 80 is important because that's how letsencrypt/acmechallenge works ... So if port 80 ain't exposed, you shouldnt be able to get letsencrypt cert ... Except if you did some more tweaking of your reverse proxy, but then you're in an advanced case and know what you're doing ...

Ideally your reverse proxy should also be configure to reverse proxy port 80 I think (but reverse proxies are hard and there are many details / subtleties..)

In fact I don't even know how you reverse proxy does work without some heavy tweaking ... we have similar issues on our infrastructure were we had to manually disable the auto https redirection otherwise it would loop forever because the proxy_pass happens in http and not https.

Nowadays I think the right way to configure such "full-domain" reverse proxy should be to use a SNI-based reverse proxy which is available in nginx (though only on buster versions)

**Comment by eauchat** [comment]
You're going beyond my knowledge ;/

Since I'm using caddy as reverse proxy, allowing http traffic is actually extra work (since https is the default and automatic), and I didn't think it was useful.
But indeed for let's encrypt certificates and mail discovery, I had to forward some specific paths as http manually to have them working.
It's true that this situation is an advanced use case and I should investigate how to also forward http traffic, but I don't know all the subtleties so I need to work on that.

Thanks a lot for your time :)

**Comment by alexAubin** [comment]
> I had to forward some specific paths as http manually to have them working.

Hmmm what about forwarding /.well-known/ynh-diagnosis too then ? (if i understand correctly, you already did this for /.well-known/acme-challenge

**Comment by eauchat** [comment]
Well, when you said it, I thought, "why didn't I try it earlier". But finally it doesn't seem to be that easy.
I added `/.well-known/ynh-diagnosis` redirections, but the diagnosis still fails.

Seems like `http://mydomain.tld/.well-known/ynh-diagnosis` redirects to the https version of it. And in the browser that redirects to the sso (with curl, I get a redirection to the https version and the https responds with some text and 302 status).

Don't know if this description is understandable, but anyway, I think those issues come from the reverse proxy, not yunohost I guess.

Edit: the 302 text is:
```html
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
