### ISSUE TITLE
Diagnosis detects ghost files

### ISSUE THREAD

**Issue by Dazeilad** [YunoHost/issues#1622]
Hi,
The new diagnosis tools tells me that : 

>  Le fichier de configuration /etc/metronome/conf.d/focus.visio.domain.tld.cfg.lua semble avoir été modifié manuellement.

Problem is, this file doesn't exist ! It used to be from an old Jitsi install, but I uninstalled it and (may be the source of the problem) I manually removed this file because it wasn't auomatically removed by YnH.
How is it possible for the diagnosis tool to detect this file ???

**Comment by alexAubin** [comment]
This happens because there's still an old entry in /etc/yunohost/regenconf.yml

This should be fixed by : https://github.com/YunoHost/yunohost/pull/1009

**Comment by Dazeilad** [comment]
Great, so we wait for the PR to be merged into the stable release to close this issue ?

**Comment by alexAubin** [comment]
Yup :+1:

**Comment by alexAubin** [comment]
Should be fixed now
