### ISSUE TITLE
Diagnosis incorrectly report IPv6 as blacklisted

### ISSUE THREAD

**Issue by Dazeilad** [YunoHost/issues#1623]
Hi, 
The diagnosis tool detected that my IPv6 was on a blacklist, but actually it wasn't the case : 
![blacklist](https://user-images.githubusercontent.com/64801705/83327823-1f6ced00-a27f-11ea-99eb-b682c14c6d47.png)

The IPv6 is provided by OVH, and everything is configured according to the [YnH tutorial](https://yunohost.org/#/ipv6).

**Comment by alexAubin** [comment]
Hmmmm but if you re-run the diagnosis for mail now, is it still detected as blacklisted ?

**Comment by Dazeilad** [comment]
Yes, still there.

**Comment by benneti** [comment]
I think I have a similar issue, and I think the issue is due to automatic redirection to the admin panel for the ipv6 address.
You should get some not authorized stuff because the admin panel is restricted to my local network.
The question is why it even tries to redirect.

Edit: Nevermind it might very well be a problem with the firewall of my isp box blocking ipv6 from the outside despite it being enabled.

**Comment by AkselRocks** [comment]
Having similar issue with IPv4.

```
=================================
Email (mail)
=================================

[ERROR] Your IP or domain 37.120.176.180 is blacklisted on Invaluement
  - The blacklist reason is: "unauthorized or malfunctioned access to invaluement - using old/outdated host names - so now ALL queries get a 'listed' answer - STOP misusing invaluement - contact invaluement for a valid subscription with valid access instructions"
  - After identifying why you are listed and fixed it, feel free to ask for your IP or domaine to be removed on https://www.invaluement.com/
```

But request on https://www.invaluement.com/removal/ reports
 ```
Delist Requests

STATUS: (your submission) 37.120.176.180 is NOT currently blacklisted 
```

Re-run of yunohost diagnosis brings same result.

Is there/ Did you find already a solution @Dazeilad @benneti @alexAubin ?

**Comment by nicolas-guichard** [comment]
@AkselRocks This is probably not the same issue as they had in 2020, the fix is simply not to use Invaluement anymore, as done in commit [71489307](https://github.com/YunoHost/yunohost/commit/714893079c88dedbc9cf56829a3112df1cafda3a).

**Comment by Dazeilad** [comment]
Hi, I just got a similar issue than AlexRocks' today (with IPv4).
The last year's problem had been solved by an update I guess.

**Comment by AkselRocks** [comment]
I edited `sudo nano /usr/share/yunohost/yunohost-config/moulinette/dnsbl_list.yml`
and `sudo nano /usr/share/yunohost/other/dnsbl_list.yml`

like this:
```
#- name: Invaluement 
#  dns_server: sip.invaluement.com
#  website: https://www.invaluement.com/ 
#  ipv4: true
#  ipv6: false
#  domain: false
```
and error disappears!

---
But as it seems, that the change will be merged into master/core, I removed the changes and set error in diagnosis to "ignore".
