### ISSUE TITLE
Diagnosis tool : Cannot allocate memory

### ISSUE THREAD

**Issue by hidrarga** [YunoHost/issues#1624]
First of all, thanks for the amazing work you are doing :) I'm using Yunohost on a Olimex Lime1, with only 512Mb. So far it was working without any issue.

Since Yunohost 3.8, I'm getting these error messages whenever the diagnosis cron job is executed: 
```
=================================
Services status check (services)
=================================

[WARNING] Configuration is broken for service nginx!
  - nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
  - nginx: [alert] mmap(MAP_ANON|MAP_SHARED, 52428800) failed (12: Cannot allocate memory)
  - nginx: configuration file /etc/nginx/nginx.conf test failed

[WARNING] Configuration is broken for service php7.0-fpm!
  - [31-May-2020 07:02:34] NOTICE: PHP message: PHP Fatal error:  PHP Startup: apc_mmap: mmap failed: in Unknown on line 0
```

This is strange because when I'm doing `nginx -t` for instance I don't have any memory issue. Do you have an idea why this is happening ?

**Comment by alexAubin** [comment]
Closing because I don't think this is specifically the diagnosis being problematic ... Can't do much to prevent the system from running out of RAM except uninstalling stuff or adding RAM or swap to the system
