### ISSUE TITLE
Diagnosis tool: rDNS

### ISSUE THREAD

**Issue by biphasic** [YunoHost/issues#1626]
I get an error of an apparently misconfigured rDNS for both ip4 and ip6, even though other services such as https://dnschecker.org/reverse-dns.php or https://www.mail-tester.com/ show correct configuration (I assume ip4 only).

The reverse DNS is not correctly configured in IPv4. Some emails may fail to get delivered or may get flagged as spam.
    Current reverse DNS: kvmvps
    Expected value: _myserver.com_

**Comment by alexAubin** [comment]
Uh wokay

Can you try to run this piece of code to check if it returns the right reverse DNS to try to pinpoint the issue ?


```
python -c "import requests, os, dns.reversename; ip = requests.get('https://ip.yunohost.org').text; reverse = dns.reversename.from_address(ip); os.system('dig +short PTR %s' % reverse)"
```

**Comment by biphasic** [comment]
your snippet returns
`kvmvps.`

**Comment by alexAubin** [comment]
Hmokay ...

Let's try: 

```
python -c "import requests, os, dns.reversename; ip = requests.get('https://ip.yunohost.org').text; reverse = dns.reversename.from_address(ip); os.system('dig +short PTR %s @8.8.8.8' % reverse)"
```

(note the @8.8.8.8 at the end which is meant to use google's DNS resolver the query)

**Comment by biphasic** [comment]
that's it! last snippet returns my server name
`myserver.com.`

**Comment by ericgaspar** [comment]
I have the same problem and the same results as @biphasic

**Comment by alexAubin** [comment]
Hmmmmokay
Can you try this script then : 

```
for RESOLVER in $(cat /etc/resolv.dnsmasq.conf  | grep "\." | awk '{print $2}'); do echo "$RESOLVER -> $(python -c "import requests, os, dns.reversename; ip = requests.get('https://ip.yunohost.org').text; reverse = dns.reversename.from_address(ip); os.system('dig +short PTR %s @$RESOLVER' % reverse)")"; done
```

(it's huge but basically tries the resolution using every IPv4 resolver in /etc/resolv.dnsmasq.conf)

Do they all return the "wrong" result ? Do some return the right result ?

**Comment by ericgaspar** [comment]
all right results for me

**Comment by biphasic** [comment]
same for me!

**Comment by alexAubin** [comment]
Wokay, so to confirm my suspicion, does running this one (using 127.0.0.1 as resolver)

```
python -c "import requests, os, dns.reversename; ip = requests.get('https://ip.yunohost.org').text; reverse = dns.reversename.from_address(ip); os.system('dig +short PTR %s @127.0.0.1' % reverse)"
```

returns the wrong result ?

**Comment by ericgaspar** [comment]
Yes, wrong result.
I don't know about you @biphasic but my server was setup yesterday... Maybe a cache issue?

**Comment by alexAubin** [comment]
Should be fixed by https://github.com/YunoHost/yunohost/commit/852cd14c4bf1301e197fe2b37d077bbed386420f

**Comment by biphasic** [comment]
wrong result for me too. Mine has been up for ~3 years
