### ISSUE TITLE
Default domain name is not selected first when installing a new app

### ISSUE THREAD

**Issue by farvardin** [YunoHost/issues#1633]
When installing a new application in Yunohost, the default domain should be pre-selected first.

At the moment, only the first domain in alphabetical order is pre-selected. Several domains can be created (for redirecting emails for example), and it should be more logical to get the default domain pre-selected when installing a new app.

For example, if my default domain is mydomain.tld and I have other domains such as aaaaaa.tld, bbbbbb.tld, ccccc.tld, ddddd.tld, when installing a new application, the domain field with display:

]aaaaaa.tld[ (selected first)
bbbbbb.tld
ccccc.tld
ddddd.tld
mydomain.tld

**Comment by alexAubin** [comment]
( To elaborate : I did not reproduce the behavior you describe until I realize that you're probably talking about the webadmin )

**Comment by Salamandar** [comment]
Fixes incoming :)

**Comment by alexAubin** [comment]
Reopening because https://github.com/YunoHost/yunohost-admin/pull/306#issuecomment-756506981

**Comment by Axolotle** [comment]
Is also implemented in https://github.com/YunoHost/yunohost-admin/pull/316
