### ISSUE TITLE
Certificate generation for xmpp-upload not working in case a wildcard DNS record is set for the main domain name

### ISSUE THREAD

**Issue by M5oul** [YunoHost/issues#1635]
This [part of the code](https://github.com/YunoHost/yunohost/blob/24f8faca67eac9ac3a194bd84ea9dfac6bbc35c5/src/yunohost/certificate.py#L606-L632) (`/usr/lib/moulinette/yunohost/certificate.py`) prevents the creation of a certificate for `xmpp-upload.main-domain.tld`, in case there is a wildcard DNS record for `main-domain.tld`.

**Comment by alexAubin** [comment]
Closing because metronome is to become an app in Bookworm / YunoHost 12.x : https://github.com/YunoHost-Apps/metronome_ynh
