### ISSUE TITLE
500 Error when creating 100+ aliases from the user portal

### ISSUE THREAD

**Issue by 1Dimitri** [YunoHost/issues#1637]
When creating too many mail aliases for a single user, the following happens:
- When OK button is pressed, a HTTP/500 Error is returned using a standard nginx error page
- The new mail alias is not created
- The error mentioned above is displayed in /var/log/nginx/_domain_-error.log

The alias can be created using cmd line yunohost such as
sudo yunohost user update <username> --add-mailalias <new mail alias>
It is also correctly displayed with a list command 

When refreshed The Web interface correctly displays it, so it seems related to the POST -> LUA LDAP process.

Tested user has roughly +/- 100 aliases, each alias being +/- 20 characters long.

**Comment by Tomo59** [comment]
Just stumbled upon this issue myself. Thanks for sharing the workaround.

**Comment by asandikci** [comment]
FYI: This error still occurs and needs fix

**Comment by 1Dimitri** [comment]
Fixed in portal rewrite in Yunohost 12.x 
(at least limit has not been reached yet)
