### ISSUE TITLE
SSL certificate issue when accessing www.domain.tld

### ISSUE THREAD

**Issue by funnymataleao** [YunoHost/issues#1638]
Hey, everybody. 
I have installed Yunohost on my home server and also installed WordPress with my personal website. But I have a problem. All the videos on my site are not playing and I get the error "The media could not be loaded, either because the server or network failed or because the format is not supported." 
I'm not a programmer, but I asked my programmer friend to look at my website and see what the problem was, and he told me that it was a problem with an SSL certificate. How can I fix it, can you give me a hint, please?

**Comment by alexAubin** [comment]
Did you install the Let's Encrypt certificate as explained in https://yunohost.org/certificate ?

**Comment by funnymataleao** [comment]
> Did you install the Let's Encrypt certificate as explained in https://yunohost.org/certificate ?

Yes, for sure. It looks like it works on my website.

**Comment by alexAubin** [comment]
Meh, then we kind of need more detail to understand what happens ... is there any specific related error message in the javascript console or the network console (c.f. the debug tab with F12 in Firefox)

**Comment by funnymataleao** [comment]
> Meh, then we kind of need more detail to understand what happens ... is there any specific related error message in the javascript console or the network console (c.f. the debug tab with F12 in Firefox)
There is no error messages in Yunohost console. I just see this message in Wordpress. How to debug it in Safari, can you tell me, please?

**Comment by funnymataleao** [comment]
For example, [here](https://denisefremov.com/portfolio/portfolio/gorod-detali/) you can see it.

**Comment by alexAubin** [comment]
That's because it seems to be loading content from www.yourdomain.tld instead of yourdomain.tld. And www.yourdomain.tld is not a domain managed by your yunohost (only yourdomain.tld is)

Any idea why it would try to fetch stuff from www.yourdomain.tld instead of yourdomain.tld ?

**Comment by funnymataleao** [comment]
That's weird. I didn't add the www to my website. No idea how to fix it?

**Comment by alexAubin** [comment]
Don't remember what was happening but now the page/link you mentionned earlier seems to be working fine ?

**Comment by alexAubin** [comment]
Related to https://github.com/YunoHost/issues/issues/249

**Comment by alexAubin** [comment]
Closing as duplicated o https://github.com/YunoHost/issues/issues/249
