### ISSUE TITLE
Package with special encoding in service description will break service administration

### ISSUE THREAD

**Issue by artlog** [YunoHost/issues#1640]
While using a not yet stable dev package Trivabble i broke service administration 
'®' character in service breaks yunohost service administration  ; https://github.com/artlog/trivabble_ynh/issues/1

i did a hot patch on server to be able to proceed then i found root cause in my code :

```
/usr/lib/moulinette/yunohost# diff service.py service.py~
357,361c357,358
<     try:
<         if description.decode('utf-8') == translation_key:
<             description = str(raw_status.get("Description", ""))
<     except:
<             print('Something went wrong')
---
>     if description.decode('utf-8') == translation_key:
>         description = str(raw_status.get("Description", ""))
```
This is FYI has no correct package should have such wrong character, but if other people do wrongly use such ®  character, it is better to have an error telling more information about what service to look at, ie doing a better exception than mine...

I think this change was introduced in last month since it was not preventing service adminsitation before.

**Comment by alexAubin** [comment]
Should be fixed by https://github.com/YunoHost/yunohost/commit/6ec0e7b6af442e4c166e6e90060f234f9a7b9e03 :+1:
