### ISSUE TITLE
Backup list is heavy on CPU

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost/issues#1641]
Hello,

I noticed on my zabbix monitoring some 100% CPU spikes. It appears that `yunohost backup list` takes 2min at full CPU, even though I have ~10 backups only (from 50MB to 1.6GB in size).

Is this a known trouble ? Can I provide some context to help you guys debug this ?

Context: KVM VPS with 2G RAM, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz.

**Comment by alexAubin** [comment]
That's probably because it needs to un-gzip some stuff which in turns requires a shitload of CPU ... Possibly https://github.com/YunoHost/yunohost/pull/1020 should help a bit with this

**Comment by zamentur** [comment]
Hello @Jaxom99 could you confirm it fixes your issues ?

**Comment by Jaxom99** [comment]
Hi, I will have to upgrade everything and then get back to you ! Will do "ASAP"  :wink:

**Comment by zamentur** [comment]
have you tried ?

**Comment by alexAubin** [comment]
Let's assume this is fixed

**Comment by Jaxom99** [comment]
It is indeed, thanks for cleaning that up ! :+1:
