### ISSUE TITLE
Error: : The certificate of ‘fluxbb.org’ has expired.'

### ISSUE THREAD

**Issue by anto1ne** [YunoHost/issues#1642]
Fluxbb can not be installed because of this error "Error: : The certificate of ‘fluxbb.org’ has expired.'"

https://ci-apps.yunohost.org/ci/job/1154

When I look at fluxbb.org, the certificate has not expired.

**Comment by frju365** [comment]
And command "wget --tries 3 --no-dns-cache --timeout 900 --no-verbose --output-document=app.tar.gz https://fluxbb.org/download/releases/1.5.11/fluxbb-1.5.11.tar.gz" works for me.

**Comment by anto1ne** [comment]
Some détails about this issue on the [forum](https://forum.yunohost.org/t/issue-with-some-app-installs-wget-reporting-the-certificate-is-not-trusted/11750)

We have to wait for an update of the ca-certificates  debian package ...

**Comment by alexAubin** [comment]
Yes the upgrade was pushed on Debian like one month ago, just upgrade your system...

**Comment by anto1ne** [comment]
@alexAubin 
Could you upgrade the ci-apps system ?
the package_check for fluxbb is still failling because of this issue
https://ci-apps.yunohost.org/ci/job/1340
