### ISSUE TITLE
Wish : ajout du controle du port 51413 dans le diagnostique automatique

### ISSUE THREAD

**Issue by anto1ne** [YunoHost/issues#1643]
Bonjour,

L'installation de transmission sur yunohost nécessite l'ouverture du port 51413.
Actuellement ce port n'est pas controlé par l'auto-diagnostique.

Il serai intéressant d'ajouter le controle de ce port lorsque transmission est installé.
De même pour les autres applications/autres ports.

**Comment by alexAubin** [comment]
Oui, les applications peuvent utiliser l'option `--needs-exposed-port` de la commande `yunohost service add`. C.f. : https://github.com/YunoHost/example_ynh/blob/master/scripts/install#L304-L310

**Comment by anto1ne** [comment]
Merci pour l'info,
Je pense que l'on peut fermer cette issue,  je vais rapporter ce souhait du coté de transmission_ynh

**Comment by Josue-T** [comment]
Hello,

Tried to Implement this on Synapse and on my server it don't work, the file `/etc/yunohost/services.yml` don't have the port passed as argument.

**Comment by alexAubin** [comment]
@Josue-T : I tried to reproduce the issue and ended up with an epic stupid bug fixed here https://github.com/YunoHost/yunohost/commit/1a2f26dc34600e97c65eb0359d79b91c85a07eab

Though you can avoid triggering it by also providing --test_status ... And in that case it does work on my machine™ ... You sure if you do that it still doesnt' work ?
