### ISSUE TITLE
Certificate chain has double entry

### ISSUE THREAD

**Issue by spctrlth** [YunoHost/issues#1644]
Ahoy,

I'm running a pleroma server on ynh and someone notified me that there are federation problems from my server to theirs. They found that the problem is because the certificate chain has a double entry. I tested multiple domains on multiple ynh instances and they all have that problem, so it seems the problem is not just me or my domain.

How I view the chain

```sh
function view_cert_chain() {
  DOMAIN="$1";
    echo -n | \
      openssl s_client \
                -servername ${DOMAIN} \
                -connect ${DOMAIN}:443 2>/dev/null | \
      awk 'BEGIN{RS="---"} /Certificate chain/ {print}' | \
      awk NF;
}

view_cert_chain <domain-to-check>
```

Output for my server

```sh
Certificate chain
 0 s:CN = ilja.space
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
 2 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
```

As you can see, 1 and 2 are the same.

What's expected is for example how it is for `letsencrypt.org`

```sh
Certificate chain
 0 s:CN = letsencrypt.org
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
```

If anyone has a work-around in the meantime, that would also be greatly appreciated :)

**Comment by spctrlth** [comment]
Follow-up,

I looked for and opened the cert file `nano /etc/yunohost/certs/ilja.space/crt.pem`. There were indeed three entries, between the first and second there was a newline, between the second and the third there wasn't. This already smells like something not right to me. I removed the last entry and did an nginx reload and now federation indeed works again.

So the problem that ynh creates certs with double entries ofc remains, but at least this gives me a work-around untill the certs renew and proves that this is indeed the issue.

**Comment by alexAubin** [comment]
Hmokay I'm surprised that this doesn't trigger any issue with regular browsers ... 

Anyway this seems related to this piece of code : https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/certificate.py#L571-L576

where we concatenate the intermediate cert with the cert received from let's encrypt to get a "full chain"

Or at least that was the rationale back in the days™, without this the certificate would not be recognized as valid. But considering this was not intuitive and led to many issues and many people asking about it on forums, maybe they changed the behavior and now the cert you get from Lets Encrypt is directly the full chain ... Or maybe that's a change in acme-tiny

Anyway, maybe we can just /not/ dump the intermediate cert and that should work (which in turn simplifies some code)
