### ISSUE TITLE
Missing advanced profile for expert install in x86 ISO

### ISSUE THREAD

**Issue by christophe-redaction-developpez** [YunoHost/issues#1646]
if you select expert install, you have an error message :
"The file needed for preconfiguration could not be retrieved from file:///cdrom/simple-cdd/advanced.preseed

**Comment by alexAubin** [comment]
Turns out I savagely removed it in https://github.com/YunoHost/cd_build/commit/fd7e2bb584ddbee5c9fc4b9e04b7f583574ea97f without realizing this was the expert install ... Though I'm still wondering why exactly we need the expert install (except maybe for partitionning)

**Comment by alexAubin** [comment]
Supposedly fixed by https://github.com/YunoHost/cd_build/commit/dd528adc3951b957f5a042b4ca4e25347d5118db
