### ISSUE TITLE
3.8 : unpopulated variable in cert-install error message

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost/issues#1647]
Hello,
dunno if it's still relevant in 4.0 but I encountered a tiny error in the folowing command: the domain is not populated, and "%s" is displayed. I run 3.8.4.9 ynh with 3.8.1.2 moulinette.

```
root@tchack:/home/yunohost.backup/archives# yunohost domain cert-install talk.tchack.xyz
Error: There is no diagnosis result for domain %s yet. Please re-run a diagnosis for categories 'DNS records' and 'Web' in the diagnosis section to check if the domain is ready for Let's Encrypt. (Or if you know what you are doing, use '--no-checks' to turn off those checks.)
```
The `--no-checks` call afterwards was a success.

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost/commit/7b1f02e01f42116a038f0bcbcb221b263fce97ee
