### ISSUE TITLE
YunoHost Web UI, create subdomain validation false negative

### ISSUE THREAD

**Issue by tomaytotomato** [YunoHost/issues#1648]
As a user I expect to be able to create subdomains successfully using the Web UI.

Input: `subdomain.domain.noho.st` 
Expected output: `Domain Created`
Actual output: `Please match the requested format`

However when using the terminal to create a subdomain it works perfectly

`yunohost domain add foo.bar.noho.st`

**Comment by Axolotle** [comment]
Should be fixed by https://github.com/YunoHost/yunohost-admin/pull/316
