### ISSUE TITLE
SOGO can't find mail after migration to Buster

### ISSUE THREAD

**Issue by corinroyal** [YunoHost/issues#1650]
After upgrading and running the migration to Buster, mail in SOGO has disappeared, though it remains in Rainloop and other mail apps. Uninstalling SOGO didn't help the problem. Not sure how to troubleshoot the issue, but I'm willing to try.

**Comment by Josue-T** [comment]
Hello,

This issue is already known here: https://github.com/YunoHost-Apps/sogo_ynh/issues/8
