### ISSUE TITLE
SSOWAT User Panel doesn't load when an app is installed on a different domain

### ISSUE THREAD

**Issue by maxthiel** [YunoHost/issues#1654]
Hello,

On a YNH instance installed on `ynhdomain.tld`, with an application installed on `myappdomain.tld`, the SSOWAT user panel will not load.
The SSOWAT is included in the nginx configuration from `/etc/nginx/conf.d/yunohost_panel.conf.inc' with this content:

```
# Insert YunoHost button + portal overlay
sub_filter </head> '<script type="text/javascript" src="/ynh_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynh_overlay.css"></link><script type="text/javascript" src="/ynhtheme/custom_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynhtheme/custom_overlay.css"></link></head>';
sub_filter_once on;
# Apply to other mime types than text/html
sub_filter_types application/xhtml+xml;
# Prevent YunoHost panel files from being blocked by specific app rules
location ~ (ynh_portal.js|ynh_overlay.css|ynh_userinfo.json|ynhtheme/custom_portal.js|ynhtheme/custom_overlay.css) {
}
```

The paths are relative, which means that when navigating to the app, the path will look like `myappdomain.tld/ynh_portal.js`.
The user panel exist only on `ynhdomain.tld/ynh_portal.js`, which will lead to a few 404 on each page view.
I've attached a screenshot of the behaviour.

![ynh_ssowat_user_panel](https://user-images.githubusercontent.com/607492/90444476-d0906000-e0d5-11ea-9438-2eec52e9636f.png)

I can think of two solutions:
* Making the path absolute to the main domain of the YNH instance
* Adding an option to the `ynh_add_nginx_config` helper.

**Comment by wadouk** [comment]
Specially when you add in fail2ban an aggressive rule on 404 and that's ban after 3 attempts

**Comment by alexAubin** [comment]
Closing because of the SSO/portal refactor in bookworm
