### ISSUE TITLE
Yunohost encountered an internal error:/

### ISSUE THREAD

**Issue by MohamedElashri** [YunoHost/issues#1656]
when I'm trying to access services tab I'm getting this error

**Action**

`GET /services
{"locale":"en"}`

**Traceback**

`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 489, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 588, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/service.py", line 302, in service_status
    output = {s: _get_and_format_service_status(s, infos) for s, infos in services.items()}
  File "/usr/lib/moulinette/yunohost/service.py", line 302, in 
    output = {s: _get_and_format_service_status(s, infos) for s, infos in services.items()}
  File "/usr/lib/moulinette/yunohost/service.py", line 357, in _get_and_format_service_status
    if description.decode('utf-8') == translation_key:
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 21: ordinal not in range(128)`

I'm not sure what is the problem.

**Comment by alexAubin** [comment]
That's most likely due to an app that installed a service with a description containing an "é" ... Though Yunohost shouldn't miserably crash just because of this

Should be fixed by https://github.com/YunoHost/yunohost/commit/6ec0e7b6af442e4c166e6e90060f234f9a7b9e03 which should be released soonish™

**Comment by MohamedElashri** [comment]
> 
> 
> That's most likely due to an app that installed a service with a description containing an "é" ... Though Yunohost shouldn't miserably crash just because of this
> 
> Should be fixed by [YunoHost/yunohost@6ec0e7b](https://github.com/YunoHost/yunohost/commit/6ec0e7b6af442e4c166e6e90060f234f9a7b9e03) which should be released soonish™

thank you
