### ISSUE TITLE
Be able to disable all SSO cookies for somes URLs for Microsoft active-sync

### ISSUE THREAD

**Issue by Josue-T** [YunoHost/issues#1657]
It looks like that Microsoft active-sync really don't like the ssowat cookies.

https://github.com/YunoHost-Apps/sogo_ynh/issues/7#issuecomment-680257907

So maybe the solution would be to disable all cookies for some url but I don't know if it's possible and what would be the effects of this...

**Comment by zamentur** [comment]
If we have a nextcloud with a logout button that logout from nextcloud and run the action logout on sso. With this new feature/bug-fix it means by logout on nextcloud you are logged out from all web app...

We probably can manage a bit by using some params on the logout url
```
https://DOMAIN/yunohost/sso/?action=logout&scope=all
https://DOMAIN/yunohost/sso/?action=logout&scope=nextcloud
```

Totally unrelated, I tried to delete nextcloud sessions server side but i was surprized that sessions files are recreated , and i am not logged out (even if the sso is logged out) !
```
rm -f /var/lib/php/sessions/*
```

**Comment by OniriCorpe** [comment]
I think it could be fixed by `active_sync.auth_header = false` in `[resources.permissions]` using packaging v2

**Comment by alexAubin** [comment]
Closing because this is Microsoft bullshit. Cookies are sent by the browser, and if the cookie is enabled on an entire domain, it will also be sent for subdomains etc. This is absolutely not trivial to fix on our side, and it doesnt need to be fixed on our side because this is a bug on Microsoft's bullshit side
