### ISSUE TITLE
Horde installation not working

### ISSUE THREAD

**Issue by utzer** [YunoHost/issues#1660]
The Horde installation did not work, I have no clue why, but I guess reporting it does not hurt. 

I used the share function above the log, so [here](https://paste.yunohost.org/raw/hufeyudina) is the log. Tried again, it worked now, this time I did not select all the options I tried before, the ticket system "Whup" (or so) was not selected.

**Comment by alexAubin** [comment]
Hey there,

It would be more relevant to post this on the horde_ynh app issue tracker (though that's probably not made obvious in our tips on the yunohost webadmin so you can't really guess it) : https://github.com/YunoHost-Apps/horde_ynh/issues

From what I can see in the log (though I don't have specific knowledge of this app) : 

```
2020-09-06 20:18:42,763: DEBUG - + /var/www/horde/pear/pear -c /var/www/horde/pear.conf config-set horde_dir /var/www/horde/horde
2020-09-06 20:18:42,864: DEBUG - ERROR: /var/www/horde/pear.conf/ is not a valid config file or is corrupted.
```

It looks like it's trying to set a setting value in pear.conf file ... and actually did so a bunch of time right before this happens ... but for some reason this time it fails ... and complains about "/var/www/horde/pear.conf/" with a trailing slash as if if was a folder ... which is pretty odd.

Maybe something related to the previous step about `init_horde_install.exp` but I really don't know much about that app..
