### ISSUE TITLE
Should /.well-known/ynh-diagnosis also be served on https?

### ISSUE THREAD

**Issue by eauchat** [YunoHost/issues#1661]
Maybe I got something wrong, but it seems to me that at the moment `/.well-known/ynh-diagnosis` is served only on http. This causes yunohost diagnosis to throw some errors if yunohost is behind a firewall that convert all http request into https ones.
From what I understood in some conversations here or on the forum, `/.well-known/acme-challenge/`, `/.well-known/autoconfig/mail/` have to be served as http, because that's part of the specifications of "mail autoconfiguration" and "let's encrypt". So I understand that yunohost implemented `/.well-known/ynh-diagnosis` in a similar way.
But some other protocols and specs do expect some `/.well-known/...` content to be served as https, like for example matrix, with the `/.well-known/matrix` that [according to the specs](https://matrix.org/docs/spec/client_server/latest#well-known-uri) should be served as https, when possible.

Would it make sense to serve `/.well-known/ynh-diagnosis` as https (or both http and https)?
That would allow to avoid diagnosis errors if domain are accessible only in https.
And isn't it better, generally, to prioritize using https over http?

**Comment by alexAubin** [comment]
>That would allow to avoid diagnosis errors if domain are accessible only in https.
>And isn't it better, generally, to prioritize using https over http?

Thing is, it's kind of feature and not a bug™

The main motivation for this route is to diagnose if Lets Encrypt certificates can be delivered using the acme protocol. But acme protocol works ... only on port 80 (at least the challenge we're using)

So "not throwing an error if it's only accessible on https" would be a mistake ...

But now that i'm thinking about it, i'm curious to know how your Lets Encrypt certificates are managed on your setup ?

**Comment by eauchat** [comment]
> Thing is, it's kind of feature and not a bug™
> ...

Ok, now I understand. I thought the point of the check was to see if the apps are up, from the outside, but if it's to check if Let's Encrypt certificates can be delivered, then it makes sense.

> But now that i'm thinking about it, i'm curious to know how your Lets Encrypt certificates are managed on your setup ?

In my setup, yunohost is in a VM. The main machine is running [caddy](https://caddyserver.com/) (instead of nginx) which takes care of making all traffic https automatically. So apart from installing caddy, I don't have to setup anything to have https traffic (but I imagine that caddy uses Lets Encrypt under the hood, never investigated it though).  
If I run services on the yunohost VM, I just have to forward the traffic of that domain to the VM, but yunohost doesn't need to deal with the certificates. Or at least it's what I understand from what I'm doing.  

So for the yunohost diagnosis to work, I can add some exception to the caddy config, to allow some http traffic to go to the VM, which is also what I did for well known mail autoconfig. For the diagnosis, it means I have to do it for all subdomains, which is a bit redundant, but since it's the way it should be for yunohost, I'll do that.

Thanks @alexAubin for the explanation.
So I close this issue then, but if you feel necessary, reopen it.
