### ISSUE TITLE
App installation : non coherent behavior for variable name in conf folder

### ISSUE THREAD

**Issue by Krakinou** [YunoHost/issues#1662]
When installing an app:
nginx.conf:
- `__FINALPATH__` will be changed by $final_path in nginx.conf
- `__PORT__` will be changed by $port in nginx.conf
- `__PATH__`  will be changed by $path in nginx.conf
- `__APP__` will NOT be changed by $app in nginx.conf

systemd.service:
- `__FINALPATH__` will be changed by $final_path in systemd.service
- `__APP__` will be changed by $app in systemd.service
- `__PORT__` will NOT be changed by $port in systemd.service
- `__PATH__` will NOT be changed by $path in systemd.service

So I have to make some dirty manual string replacement in some cases...
By the way, I couldn't find a place where the behavior is documented.

**Comment by ericgaspar** [comment]
Hello @Krakinou 
quick links to the NGINX helper
https://github.com/YunoHost/yunohost/blob/stretch-stable/data/helpers.d/nginx#L10-L15
and systemd helper...
https://github.com/YunoHost/yunohost/blob/1279755463100e6c4a0ba7d4b50f8f39658c8eac/data/helpers.d/systemd#L16-L17
I guess it could be more consistent

**Comment by alexAubin** [comment]
(This should be improved at some point by generalizing the use of the new helper ynh_add_config from Yalh )

**Comment by alexAubin** [comment]
Closing because nowadays the corresponding helpers relying on ynh_add_config which consistently replace all __FOOBAR__s
