### ISSUE TITLE
RaspberryPi install image points to qemu-lite image and stretch image 404

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost/issues#1667]
While looking into https://forum.yunohost.org/t/old-raspberry-images-not-available-any-more/12979 I found something strange.

https://yunohost.org/#/images/preview for Raspberry points to https://build.yunohost.org/image_2020-10-03-yunohost-lite-qemu.zip is that normal ? 

In build.yunohost.org there used to be a https://build.yunohost.org/yunohost-stretch-latest-rpi-stable.zip which is now a 404 (37 bytes file size - is it a symbolic link ? )

cc @alexAubin who I know is involved in the iso build part.

**Comment by esijg** [comment]
Seems like this is still a problem? although not as obvious. https://build.yunohost.org/yunohost-buster-4.1.7.2-rpi-stable.img.zip has the right filename but the img inside that zip is 2021-02-21-yunohost-lite-qemu.img

**Comment by alexAubin** [comment]
Hmpf but how much of a problem is this ... Typically if you're using etcher or usbimager, the image can be flashed without explicit unzip

**Comment by esijg** [comment]
I wouldn't say this is a breaking problem. But can cause some confusion. (even caused me to download the file again as I thought I had downloaded the wrong one). I could see this as a potential problem for people with limited internet connectivity.

**Comment by alexAubin** [comment]
Closing because might be fixed now that we build the images using a github ci
