### ISSUE TITLE
Fatal error while trying to install Mastodon on Raspberry Pi

### ISSUE THREAD

**Issue by narFnarF** [YunoHost/issues#1668]
I attempted to install Mastodon on my Yunohost and got a fatal error. I'm reporting the error here as the app suggested me to do.

Screenshot of the error:
![](https://i.imgur.com/Sde0TVs.png)

Paste of the error:
https://paste.yunohost.org/raw/yewivizido

My device:
- Raspberry Pi 4
- 4GB of Ram
- Freshly installed Yunohost last week
- Other installed apps on the same device: Bibliogram, RoundCube, Discourse

I'm very new to Yunohost but I find it very cool so far. Don't hesitate to ask for more infos. I'll help as much as I can.

This issue as been re-posted in the Mastodon repo: https://github.com/YunoHost-Apps/mastodon_ynh/issues/240

**Comment by zamentur** [comment]
I close it. Apps issue are generally to open inside app repo (as you did too)
Thanks for reporting
