### ISSUE TITLE
Global disabling overlay / general overlay problem

### ISSUE THREAD

**Issue by farvardin** [YunoHost/issues#1669]
The Yunohost overlay, while quite nice and practical, can also lead to some unexpected behavior with some yunohost applications:

With keepass/nextcloud:
https://github.com/YunoHost-Apps/nextcloud_ynh/issues/317#issuecomment-702596438

Bad Gateway error: 
https://forum.yunohost.org/t/bad-gateway-aleatoire/12814 (I can't reply to this thread to explain how to fix this)

On both I've disabled the overlay, in the /etc/nginx/conf.d/SERVER.d/APP.conf to fix the problems.

Maybe it would be nice to either disable the overlay during the installation of a new app, or when you modify it. Or even to disable it globally, for all the yunohost apps.

**Comment by alexAubin** [comment]
Yes indeed

Adding a setting to disable it globally should be kinda easy to do and could be an ~easy first contribution for a newcomer I believe ?

I think it's "just" a matter of : 
- adding a new setting here : https://github.com/YunoHost/yunohost/blob/dev/src/yunohost/settings.py#L56
- here is the place where we add the "yunohost_panel.conf.inc" file during the regen conf : https://github.com/YunoHost/yunohost/blob/dev/data/hooks/conf_regen/15-nginx#L49 (c.f. also https://github.com/YunoHost/yunohost/tree/dev/data/templates/nginx/plain where .conf.inc lives)
- we could check if the new setting is set to true/false (similar to what's done for the security/compatibility setting a few lines below) and make the .inc file empty in the corresponding case, which should disable the panel button entirely

**Comment by zamentur** [comment]
I close this sissues as a PR has been done and is closed to be merged
