### ISSUE TITLE
Sitemap, three sections indexs?

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#167]
###### Original Redmine Issue: [167](https://dev.yunohost.org/issues/167)

Author Name: **moul**

---

As we don't have automatic documentation indexor, I maintain a sitemap for both languages which is not very difficult to do.

There is also admin, user and contributor pages which lists pages. I don't maintain them.
I think many pages are admin, user and contributor related and are hard to put them in this three sections.
For instance, an app page (like transmission, ffsync) can contain information about this three parts.

This three sections which are good idea theoretically but not practically.

I would not use this three sections.
But sitemap is also growing.

Tell me what you think.

**Comment by alexAubin** [comment]
Closing because I don't think it's relevant to keep this topic opened buried in the hundred of other. Recently I went with removing the sitemap entirely and just keep the user + admin + contributor guide as indexes and it kinda solve the issue ?
