### ISSUE TITLE
Rspamd debian package is not supported

### ISSUE THREAD

**Issue by HugoPoi** [YunoHost/issues#1673]
Today I ran into issues with rspamd, all the emails sended by discord mark as hard bounce spam because of false positive with the rule `SBL_URIBL` symbol `URIBL_SBL`, I disabled the rules, but I think every instance of yunohost is concerned about this behavior.

The rspamd yunohost/debian configuration might be garbadge because

> Debian
standard
repos notes
Please DO NOT use those packages.
Please DO NOT use those packages!!
Please DO NOT use those packages!!!
Rspamd is also available in some versions of Debian and Ubuntu. Please DO NOT use those packages, as they are not supported in any way. Any issues or feature requests related to the packages from Debian provided distros will be closed with no feedback (or even rage feedback). Just don’t do it, you are warned!

As mention on the [download page of Rspamd project](https://rspamd.com/downloads.html)

**Comment by alexAubin** [comment]
Well what the fuck ... could they at least explain what the fuck is wrong with using the packages from debian ... People naturally tend to "apt search" a package when they want to install it so wtf \~_~ Also from a security point of view it's better to depend on the debian community rather than a bunch of mysterious apt repos for every project you want to install \~_~

Of course this ain't your fault and thanks for reporting this fact >_> ... In the past (jessie era if i recall correctly) we were building these packages manually so I guess we could do it again but hmpf that's just a pain in the ass

**Comment by alexAubin** [comment]
Digging a bit, sounds like version in Buster is 1.8 but in Bullseye / backports it's 2.5 which is guess is why the devs don't want to have business to do with older major versions (could be made more explicit though >_>)

**Comment by HugoPoi** [comment]
I really don't like that tooo, because it break the essence of having trusted repository and having LTS. I ask them
```irc
<muppet> Lol rspamd 1.8
<muppet> Yea... You might want to upgrade :-)
<hugopoi> muppet: do you know why these packages in Debian repository aren't supported anymore ?
<muppet> Because they're extremely old
<muppet> There's been thousands of useful changes and improvements in rspamd since then, it's a rapidly growing and improving project
<hugopoi> Ok but every package in Debian stable is extremely old lol
<muppet> Right
<muppet> But does that the author of those programs must support them?
<muppet> Some slow moving programs that's a model that works well
<muppet> rspamd is always updating and elvolving, you have to be to fight spam
<muppet> who wants to support code you wrote ~2-3 years ago, when you barely have time to support the current version and all the requests people make of you?
<muppet> The author MAKES updated versions of rspamd available for your Debian platform. The request is simple: If you WANT support, use Support packages.
<muppet> If you want to float in the ocean by yourself, by all means, use those old crappy versions.
<hugopoi> I understand, we are on the same boat here
<hugopoi> I suppose besides the old binairies, there is issues with the default configuration provided in the package
<hugopoi> "rspamd is always updating and elvolving, you have to be to fight spam" => best argument
<muppet> Exactly. Even spamassassian has that sa-update program built in. The binary stays the same, but the dataset it uses is always updating.
```

**Comment by HugoPoi** [comment]
Ok some other people have the issue so here the way to have a more usable rspamd
1. Create a file in `/etc/rspamd/local.d/surbl.conf` with this in it
```lua
rules {
  "SBL_URIBL" {
    enabled = false;
  }
}

```
2. `sudo service rspamd restart`

PS:
You can use the rspamd webui through ssh local port forward
1. `ssh admin@youryunohostaddress -L 11334:localhost:11334`
1. Then open a browser at http://localhost:11334/

**Comment by h3ndrik** [comment]
maybe yunohost should install such packages from debian testing? especially if the argument is to keep such software more up to date. this would not require third party repositories. currently we have rspamd 1.8.1 in stable. and version 2.7 available in debian testing.

**Comment by alexAubin** [comment]
Closing / wontfix, Bullseye ships 2.7
