### ISSUE TITLE
Simone does not handle unexpected variables

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#1674]
*(Per [this thread](https://forum.yunohost.org/t/partager-sur-facebook/13171) in French)*

Simone will display `Not Found` if it encounters an unexpected variable in the URL. These variables could be added by external platforms (looking at you, FB) referencing the project's website and documentation.

To test: https://yunohost.org/?fbclid=TRACKING_ID, or https://yunohost.org/?NOTaVARIABLE=BLAH

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/Simone/commit/40ceaf34ac3f74a04fd6999abf1f47086846369f ... thanks for reporting the issue :|
