### ISSUE TITLE
error: automatic diagnosis - Timed-out while trying to contact your server from outside

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost/issues#1676]
I am getting (more or less daily) emails from automatic diagnosis with error or warning, but when manual doing the diagnosis there is no error any more.

```
=================================
Web (web)
=================================

[ERROR] Domain matrix.aksel.rocks appears unreachable through HTTP from outside the local network in IPv4, though it works in IPv6.
  - Timed-out while trying to contact your server from outside. It appears to be unreachable.
    1. The most common cause for this issue is that port 80 (and 443) are not correctly forwarded to your server.
    2. You should also make sure that the service nginx is running
    3. On more complex setups: make sure that no firewall or reverse-proxy is interfering.
```
Manual diagnosis works fine and there are no problems in usage of the services.
![Bildschirmfoto_2020-11-06_20-47-25](https://user-images.githubusercontent.com/44803148/98408417-67374200-2071-11eb-82a8-6e455f8d2b85.png)
![Bildschirmfoto_2020-11-06_20-50-48](https://user-images.githubusercontent.com/44803148/98408635-c72de880-2071-11eb-8f73-e9055a166f41.png)
![Bildschirmfoto_2020-11-06_20-52-13](https://user-images.githubusercontent.com/44803148/98408742-f9d7e100-2071-11eb-8d6b-309fb85cc82b.png)
![Bildschirmfoto_2020-11-06_20-51-36](https://user-images.githubusercontent.com/44803148/98408747-fa707780-2071-11eb-925a-8a1339a70903.png)

What can I do?

**Comment by AkselRocks** [comment]
New Email/Warning:
```
=================================
Ports exposure (ports)
=================================

[WARNING] Could not diagnose if ports are reachable from outside in IPv4.
  - Error: HTTPSConnectionPool(host='diagnosis.yunohost.org', port=443): Read timed out. (read timeout=30)
```

**Comment by zamentur** [comment]
I got a similar error on several server, here are the log of nginx where i can see ipv6 is requested but not the ipv4

```
root@xxxxxx:~# grep "diagnosis" /var/log/nginx/xxxxxxx-access.log.1
80.67.172.144 - - [14/Nov/2020:07:20:01 +0100] "GET /.well-known/ynh-diagnosis/9ddcd4bce2ff7597 HTTP/1.1" 200 0 "-" "Python/3.6 aiohttp/3.6.2"
2001:910:1410::1 - - [14/Nov/2020:07:20:02 +0100] "GET /.well-known/ynh-diagnosis/9ddcd4bce2ff7597 HTTP/1.1" 200 0 "-" "Python/3.6 aiohttp/3.6.2"
2001:910:1410::1 - - [14/Nov/2020:19:08:37 +0100] "GET /.well-known/ynh-diagnosis/0f87a98978b3754b HTTP/1.1" 200 0 "-" "Python/3.6 aiohttp/3.6.2"
```

**Comment by dbuscher** [comment]
I have the same problem on one of my yunohost machines, but not the other. The server which has the problem is in the CET timezone, so I suspect that it is a problem with the diagnosis.yunohost.org server being overloaded when the CET-timezone machines (I suspect these are in the majority) all try to contact it at the same time. 

Solution - add a random time delay at the start of the cron job? I have not tried this myself.

**Comment by dbuscher** [comment]
OK, my mistake, when I looked at the cron job, it already adds a random delay of up to 20 minutes. Will try delaying by half an hour.

**Comment by AkselRocks** [comment]
@dbuscher good theory!

Changed the cron job to 30 minutes later and no timed-out error for the last 2 times. 
Just: `[WARNING] Configuration file /etc/cron.d/yunohost-diagnosis appears to have been manually modified.`

will continue to observe ...

**Comment by alexAubin** [comment]
I changed the number of workers from 8 to 16 yesterday (if i remember correctly) on the diagnosis server, which should improve the situation a bit

**Comment by AkselRocks** [comment]
Good news!
No error since @alexAubin change.
So I will close.

But the solution is just a temporary. 
Why not expand the random delay to 40 or 50 minutes? Or let decide the yunohost admin when to start the "action"?
