### ISSUE TITLE
cert-install return exit code 0 even if it fails

### ISSUE THREAD

**Issue by rthouvenin** [YunoHost/issues#1681]
When running the command `yunohost domain cert-install` on a fresh install, it fails because it demands that a diagnosis has been run before. However the exit code of the command is `0`, so if run within a script it is not possible to detect that something went wrong. I would expect that a fatal error / failure leads to a non-zero exit code.

I hope this is the right place to report the problem!
Thanks for you work

**Comment by alexAubin** [comment]
To be fixed in https://github.com/YunoHost/yunohost/commit/e4df838d
