### ISSUE TITLE
Custom themes and backup

### ISSUE THREAD

**Issue by ccclement** [YunoHost/issues#1682]
**fr:**
Quand tu fais une sauvegarde Yuno complete _(mais j'imagine que 
c'est pareil pour une sauvegarde System)_, le dossier 
/usr/share/ssowat/portal/assets/themes/ n'est pas backupé, du coup tu 
perds tous tes thèmes custom lors d'une restauration _(dans mon cas il 
n'y avait plus les petits chats sur la page d’accueil et le logo Yuno 
était de retour, en somme j'avais une version vanille)_.

Bref, faudrait inclure ce dossier dans le backup.

**en:**
When you make a complete Yuno backup _(but I guess 
it's the same for a System backup)_, the folder 
/usr/share/ssowat/ssowat/portal/assets/themes/ is not backuped, so you 
lose all your custom themes during a restoration _(in my case it's 
no more little cats on the homepage and the Yuno logo 
was back, in fact I had a vanilla version)_.

In short, this folder should be included in the backup.

**Comment by SiM** [comment]
Hi, I had created similar issue here : #1630 
May be we can close one or the other.

**Comment by alexAubin** [comment]
Indeed, let's close this one and keep the original one to keep things tidy :+1:
