### ISSUE TITLE
Consider making example_ynh a template repository

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#1683]
https://github.com/YunoHost/example_ynh/pull/137 triggered me again. 😛 As of today, 13 out of the 73 forks of the repo have been renamed with apps names, that's almost a fifth of them.

`example_ynh` is meant to be copied and altered into independent app packages. There is no need for the app repos to hold the committing history of `example_ynh`, for example, and there is no need for the app packagers to merge their alterations back into `example_ynh`.

The default behavior on GitHub when copying a repo is to actually fork it, making the new repository dependent on the original repo and allowing the user to PR their changes back into it. GitHub can now make repos into [template repos](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template) which by default makes users copy the files instead of forking them.

So, let's embrace the template. 😄

**Comment by alexAubin** [comment]
Yes that sounds pretty logical to me. If other folks from the app group agree, let's click whichever button is need to make this a template !

**Comment by tituspijean** [comment]
@YunoHost/apps, shall we make the change then?  😇

**Comment by kay0u** [comment]
I'm ok with it :-)

**Comment by yalh76** [comment]
I agree too

**Comment by kay0u** [comment]
Done \o/
