### ISSUE TITLE
Wat do with "the big YEP list"

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1685]
c.f. https://github.com/YunoHost/doc/blob/master/pages/04.contribute/04.packaging_apps/15.quality_tests/02.yep/packaging_apps_guidelines.fr.md and https://github.com/YunoHost/doc/blob/master/pages/04.contribute/04.packaging_apps/15.quality_tests/02.yep/packaging_apps_guidelines.md

It's a bit sad because it looks like an epic quantity of energy went into this, but it feels a bit abandoned ... These past years, packaging practices tend to evolve pretty organically (de-facto standards), or according to new helpers being developed and integrated or not into the core, or defined through code (c.f. example_ynh, package check, package linter) because code is law™.

I guess it would be super nice to have a well-detailed specification of what a yunohost app should look like, but we all know that it's hard to define because of the flexibility (and therefore somewhat undefinability?) of the current format and its going to keep evolving in the future.

So naively I would tend to just drop that page... Though we could do a quick walkthrough to check about stuff that not obvious or handled by code/linter nowadays. Or in terms of guidelines we could keep a bunch of general "qualitative" guidelines such as "a yunohost application is meant to work out of the box" (cf glowingbear which has been level 7 for a while but which required you to manually apt install and configure(?) weechat, which kinda defeats the whole purpose of yunohost apps...)

**Comment by nathanael-h** [comment]
Hello, just for your information, I started with this page to see how to package an app last weekend. In fact what I think that the example package and a kind of list of the helpers should be enough to start. If this helps you...

**Comment by alexAubin** [comment]
@nathanael-h : thanks for your feedback ! Can you maybe explain how you ended up on the YEP list in the first place ? (I'm guessing because it's pointed by other pages of the packaging documentation)

**Comment by nathanael-h** [comment]
Hello Alex, i read to quickly yeaterday and I confused this yep page with this one https://yunohost.org/#/packaging_apps_start sorry for the "fake news" 😔
I started with the packaging started page, and I did not get on the yep page. I don't know how i confused it.

**Comment by alexAubin** [comment]
Closing because got rid of it during the packaging doc refactoring ..
