### ISSUE TITLE
Be able to easily customize where app data are stored

### ISSUE THREAD

**Issue by sebmennetrier** [YunoHost/issues#1688]
The data path used by every application is depending of install script of each application.
This path (and probably others like backup, database, ...) should be customisable (through post-install script ?) and accessible during app installation.

The idea is to add possibility to use an external storage to store application data.
In cloud environment for exemple, it is possible to attach a storage with a "dynamic size". At the beginning, it is possible to use a storage of 10G for example then increase this size when the storage will be full without needs to buy a bigger storage (or machine), move everything inside or re-install from a backup...

If some path are customisable, it is possible to use a storage for data, an other for backup, another for ...

We can also use symbolic links but applications like NextCloud doesn't like that for security reason.

**Comment by alexAubin** [comment]
(Renaming the issue ... Naively my guess is that we should have a mechanism to move the entire /home/yunohost.app to another drive, and handle all this using mount-binds rather than symink, but gotta think calmly about this and experiment ...)

**Comment by alexAubin** [comment]
Superseded by https://github.com/YunoHost/issues/issues/2372
