### ISSUE TITLE
Clarify service requirements in manifest.json

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#1693]
[Right now](https://github.com/YunoHost/yunohost/blob/a52b7f0153a174970b63f227320d8c9ed997e87b/src/yunohost/app.py#L2842-L2873), the services requirements checks are a bit convoluted and boil down to checking that the following services are OK:

* `nginx` is always added whatever the provided list
* `php7.3-fpm`, replacing any other mention of php in the manifest
* `mysql`
* `postfix`
*  `fail2ban` is always added whatever the provided list

Other services are ignored, in opposition to the [documentation](https://yunohost.org/#/packaging_apps_manifest_en):

> **services**: services needed by the application among `nginx`, `php5-fpm`, `mysql`, `uwsgi`, `metronome`, `postfix`, `dovecot`…

I suggest we either:
* simplify the checks, acknowledge the limits of the `services` list in the documentation, and add linter warnings about custom services
* expand the checks, and specify in the documentation that these checks only test for the services being OK and will not try to install them.

**Comment by alexAubin** [comment]
Eh I was about to say "this is sort of fixed by the manifestv2" but in fact I might have dropped entirely the key and now no checks happens for v2 app ? Need to check the code ...
