### ISSUE TITLE
Thoughts on next-generation app CI

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1694]
So following the attempt to refactor package_check and some experiment with gitlab CI, I'm writing these notes to try to clarify how we would build a next-generation app CI, most probably using gitlab-ci

##  Context, constrains, wishlist

- We want to cover something like 200+ apps repo
- We want automatic periodic testing (at least once a month per app)
- We also want so way to trigger manual tests on arbitrary branches (c.f. the "dev ci" use case)
- Possibly the CI should be self-hostable (c.f. running package check manually, yalh running dozens of tests in parralel...)
- We want to cover at least 64bit, but also 32 bit, ARM architecture
- We want to cover stable yunohost, but also possibly testing/unstable yunohost, or "the-next-debian-version"
- Many test parameters are currently defined in `check_process` (though 50% of it could be automatically derived from the manifest)
- (Ideally) Some possibility to easily move/expand CI workers

##  On using Gitlab-CI

Pros:
   - Gitlab CI offers great semantic to define the tests themselves, forces to have "atomic" tests
   - Good separation between coordination & runner
   - We can have our own custom runner and handle all the test logic
   - Ability to dynamically generate gitlab-ci.yml using a script
   - Ability to use "tags" for runners to make it ~trivial to trigger tests for specific arch or ynh branches (testing/unstable/next-debian)
   - Standard tool that other people from outside the Yunohost project may already know
   - Many other powerful features that we have need

Cons:
   - Our use case / context is a bit complex and does not exactly fit ... 
      - for example because we're testing app installs which, in the general case, may affect the entire system. We want to avoid reinstalling apps during every tests *but* it's not 100% clear how to reuse previous successful installs. Gitlab strongly advise to use artefact for these but in our case, artefacts would be a ~700MB snapshot which has no purpose once the test is done. We may end up having to do some black magic for this.
       - we have 200ish app repos and want to test the same test pipeline on them, and that pipeline is defined "externally" to that repo.
   - Dynamically generating gitlab-ci.yml causes the pipeline structure to be a bit funky (c.f. the "downstream" stuff [here](https://gitlab.com/alexAubin1/helloworld_ynh/-/pipelines/229153334))
   - Gitlab CI handles the job coordination, but we may certainly end up having to write our own high-level front-end like yunorunner that's able to properly display tests results

## Custom runners, test context and images, and about "caching" the app install
   
Right now I think the best strategy is to use LXD to manage the context in which the test actually runs. We already have experience from this thanks to Kayou and the core CI. We can have a "base" image with preinstalled yunohost + default test domain and user, c.f. the "snap0" of package_check

The big related question is that we want to "reuse" a snapshot of successful install (for example, to test the backup script, or the upgrade script). *But* 
- in the gitlab test workflow, each test is independent from each other and may actually run on a different runner. So how do you make sure that snapshot is on the appropriate runner ? 
- when defining test instructions in .gitlab-ci.yml, we define instructions that are to be run *inside* the image. But you can't easily control the host to create/load/delete snapshots. I believe we'll have to do this using the prepare.sh/cleanup.sh logic of the custom runner + some home-made logic to create snapshots after the successful install, then load it before the other relevant tests (and delete it at some point... This is a bit black magic but that should work. For now I would remove the assumption that tests from the same pipeline could run on different machines

## Where to put `.gitlab-ci.yml` ? In which repo should the test run (the app itself or the "app ci" repo) ? 

We want to avoid having to duplicate and constantly update the test pipeline definition for 200+ repos ... the test pipeline should be defined in a separate repo. Gitlab-ci allows to "include" a `.gitlab-ci.yml` from an external source, which is good. But we could also imagine having no `.gitlab-ci.yml` in the apps themselves, and running all tests from the "test pipeline" repo .. (not sure if that's clear). There are pro and cons for each of these

### `.gitlab-ci.yml` in the app itself

Pros: 
- a test will be clearly identified to correspond to the app of the repo...

Cons:
- we have to commit a `.gitlab-ci.yml` to all repos (that only has to be done once, but we may not have the write access to some of the repos)
- we'll have to configure the runner + integration with gitlab(.com?) on each app which is fastidious ?

### Triggering all the tests for all apps from a single repo

Pros: 
- only one repo to configure, everything remains pretty independent from the app repo themselves, we can just define what repo to run on using a variable in `.gitlab-ci.yml` like `"APP_TO_TEST": "https://github.com/yunohost-apps/helloworld_ynh"` (c.f. gitlab : when you are in the "Pipeline" view you can "Run pipeline" manually and at this point you can inject custom vars ... of course we would like to do this automatically from our own high-level test orchestrator/frontend)

Cons:
- in the pipeline view, it won't be clear at all what app is being tested because it doesn't display the vars... (that's somewhat solved by creating our own frontend that would fetch and analyze the pipeline, but that's work ...)

## On dynamically generating the test pipeline

Some apps may have different tests to be run (for example, no need to test the change-url feature on non-webapps) ... also there's this notion of "test serie" :/ . Gitlab allows to generate the test pipeline dynamically from a script. c.f. an example [here](https://gitlab.com/alexAubin1/ci-apps-sandbox). In our case, we basically want to 
- parse check_process ... which is no easy task ... but slightly easier to understand following package_check refactoring : https://github.com/YunoHost/package_check/blob/cleanup-3/package_check.sh#L591-L645
- generate the corresponding `gitlab-ci.yml` content

Additionaly, from what I understood during the refactoring of package check, we should define the following notions for each app : 
- is it a web app ? I believe we should check the presence of `ynh_webpath_register` in the install script for this ... Later, we'll "validate the the app can be reached" only if it's a webapp (though we could define a similar test like poking the port of the corresponding service idk)
- the default install path ... i believe we should define it to `/` to all webapps (supposedly all webapps can install on the domain root ?). For non-webapps, we can set it to empty string.
- if relevant, the alternative install path (so /subpath for apps that can be installed on a subpath)
- the default installation arguments, in particular the arguments specific to the app, which should be parsed from check_process (c.f. `install_args` in the previous package_check link). By default, we shall force is_public=1.

## Test inventory 

**TODO / FIXME : how do we handle the "multiple test serie" stuff ? How important is it ? Shouldn't we just be able to define "alternative install arguments to test install with" ?**

---

### Stage 0. Package linter

Context: 
- anywhere where we can run the linter in ?

What to test:
- run the linter

Should produce
- a JSON aterfact, to be used later when computing the result/summary

---

### Stage 1. Regular install

Context: 
- basic yunohost

What to test:
- test installing the app with default install args, **on the default install path** (so `/` for webapp, or empty string for non-webapps)
- validate that the app can be reached publicly

Should produce
- (not an aterfact!)  an "internal" LXC snapshot of the app already installed

---

#### #### Reinstall after removal ####

Context: 
- reuse snapshot from stage 1

What to test:
- removing the app
- reinstalling the app with the same args
- validate that the app can be reached publicly

Should produce nothing

#### #### Install on subpath ####

Context:
- basic yunohost
- **only** for webapps that support subpath install

What to test:
- test installing the app with default install args, with path=/subpath
- validate that the app can be reached publicly

Should produce nothing

#### #### Private install ####

Context:
- basic yunohost
- **only** for webapps that support private install

What to test:
- test installing the app with default install args
- validate that the app can NOT be reached publicly

Should produce nothing

#### #### Multiinstance install ####

Context:
- reuse snapshot from stage 1

What to test:
- test installing the app a second time, with a different domain
- validate that the app 1 can still be reached publicly
- validate that the app 2 can be reached publicly

Should produce nothing

---

#### #### Upgrade from the same version ####

Context:
- reuse snapshot from stage 1

What to test:
- (force-)upgrade the app
- validate that the app can be reached publicly

Should produce nothing

#### #### for all commits defined: test the upgrade from that commit ####

Context:
- basic yunohost

What to test:
- install using the old commit, possibly with specific args defined in check_process
- upgrade to current version
- validate that the app can be reached publicly ?

Should produce nothing

---

#### ####  Backup / restore on same setup ####

Context:
- reuse snapshot from stage 1

What to test:
- backup the app
- remove the app
- restore the backup
- validate that the app can be reached publicly

Should produce 
- an aterfact corresponding to the backup archive, to be used on 'restore on fresh install'

#### #### Backup on a fresh install  ####

Context:
- basic yunohost
- with the backup archive aterfact from previous test

What to test:
- restore the backup
- validate that the app can be reached publicly

Should produce nothing

---
 
### Stage 5. "Advanced" features

... this is where we test the change url feature and actions / config panel but meh, imho these are a bit secondary so too lazy to write these

---

### Stage 6. Result / summary

Context:
- be able to run a python script ... we need all the success/failure from the tests that were ran ... + the linter json output from stage 0

What to test:
- what was successful / failed ...

Should produce
- a summary of what worked / what did not that is human friendly
- a level for the app

**Comment by kay0u** [comment]
Thank you for this huge and details explanation on what we want/need for the next-gen ci-apps.

> .gitlab-ci.yml in the app itself
>
>Pros:
>
>    - a test will be clearly identified to correspond to the app of the repo...
>
>Cons:
>
>    - we have to commit a .gitlab-ci.yml to all repos (that only has to be done once, but we may not have the write access to some of the repos)
>    - we'll have to configure the runner + integration with gitlab(.com?) on each app which is fastidious ?

We can include on each apps a default pipeline this way:
```
include:
  - remote: 'https://raw.githubusercontent.com/YunoHost/apps-ci/master/.gitlab/ci/main.gitlab-ci.yml'
```

And in this file, we can also add variables like default args...

--------

I've started something [here](https://github.com/YunoHost/apps-ci) the readme is not correct because I copy pasta the ci-core, but files in `.gitlab` folder, especially the [package_linter](https://github.com/YunoHost/apps-ci/blob/master/.gitlab/ci/package_linter.gitlab-ci.yml) is working. It will write result of the linter about level 0, 4, 6, 7, 8 in a file which is store in cache (defined in the [global file](https://github.com/YunoHost/apps-ci/blob/master/.gitlab/ci/global.gitlab-ci.yml))

--------

I have no idea how we can make this kind of runner runnable in local as we do for package_check.

**Comment by jedie** [comment]
Is there no way to put everything in docker so it's easier to run it everywhere. E.g. as github actions and on gitlab CI and at home on local machine?!?

**Comment by alexAubin** [comment]
No ... this is related to the usual question of "why ain't yunohost using docker" and/or "can i install yunohost inside a docker"

The very paradigm of Docker is based on "running one single executable", but Yunohost is *an entire ecosystem*. Docker is simply not mean to run a full Yunohost stack, and vice versa.

You can also tell it's the case from the number of hacks that people have to perform to be able to install Yunohost inside a Docker, which ultimately make the result look like a crypto-frankenstein rather than an actually sensible test bench or production server. There will be many things that we possibly do (in the general case) that you will probably not be able to perform inside a docker (for example, take vpnclient_ynh : it tweaks the iptables rules and other low-level system stuff)

**Comment by jedie** [comment]
Yes, it may be that docker is not a good idea ;)

But it would be really useful if we could run package-check as github actions, too. Because the most sources are on github, isn't it? For this, see: https://github.com/YunoHost/package_check/issues/93

I also think it would be nice if we could host our own CI server via Yunohost ;) We just need a `package_check_ynh` ... Install the App in own Yunohost instance and add own package repository via web interface...

**Comment by alexAubin** [comment]
So following the rework of CI_package_check in https://github.com/YunoHost/CI_package_check/pull/28 I pretty much changed my mind completely ... I believe we have too many aspects of the app CI that do not fit easily inside gitlab-ci (c.f. the number of different repos, reusing snapshots between tests, having a nice front end). Gitlab-CI has some pretty neat features and elegant semantic but even if we switched to it I'm pretty sure we'd have to define our own frontend + custom scheduling/orchestration logic (for example for the dev CI use case) and it would become a mess...? 

I believe the right way to go is to merge yunorunner and CI_package_check together + slap a small form to add job manually (+ ideally [reworking the format of check_process files](https://github.com/YunoHost/issues/issues/1684)...), and we'll have full control and freedom over the job scheduling / orchestration, web UI and notifications ... which is quite important ?

**Comment by jedie** [comment]
I start the idea of "package check as YunoHost App" here: https://github.com/YunoHost-Apps/ci_ynh see also: https://forum.yunohost.org/t/ci-ynh-package-check-as-yunohost-app-using-django/13894

**Comment by alexAubin** [comment]
Closing because we have the package_check v2 deployed everywhere, turns out using Gitlab is too complex / not relevant, it's much more worth and easy to progressively integrate CI_package_check in yunorunner
