### ISSUE TITLE
Add a warning/error in diagnosis if root partition (or the one hosting /var?) is less than ~15GB in total ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1697]
From time to time we see people like in https://forum.yunohost.org/t/unclear-fatal-error-no-disk-space-left-there-should-be-plenty-of-space/13765 with stupid disk space issue because their provider create a root filesystem with only 10 GB ... which will ultimately get full pretty quickly

**Comment by alexAubin** [comment]
Relevant code is around here : https://github.com/YunoHost/yunohost/blob/dev/data/hooks/diagnosis/50-systemresources.py#L66

**Comment by zamentur** [comment]
I think a warning is better, 12GB is a good value. You can have a stable server with 12GB.

**Comment by alexAubin** [comment]
Another user had this stupid situation today again : https://forum.yunohost.org/t/no-space-left-on-device-no-free-space-on-root-partition/14023

In fact we should even check this during postinstall because wtf

**Comment by alexAubin** [comment]
(Gotta think about what to do in the webadmin with respect to https://github.com/YunoHost/yunohost/pull/1145 ... (no way to add the --force-diskspace from the webadmin))

**Comment by alexAubin** [comment]
Yes, that was already discussed in some thoughts about the packaging format (in particular manifest format), in particular we need to do the same kind of thing for RAM usage during app install (and after installation) to avoid so many cases where the install script just gets killed when you try to compile / build a huge amount of stuff on a 512MB system etc...

**Comment by alexAubin** [comment]
Still not sure how to integrate this in the webadmin ...

Was thinking about a --dry-run in the webadmin that would validate this + other various things, that could return a validationerror : https://github.com/YunoHost/yunohost/blob/dev/src/yunohost/tools.py#L286-L345

but not sure how to properly catch and handle the various errors from the webadmin
