### ISSUE TITLE
YunoHost should store a report per app installation and make them available in the admin interface

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#170]
###### Original Redmine Issue: [170](https://dev.yunohost.org/issues/170)

Author Name: **Bram**

---

For now, the installation of an app is displayed on the admin interface and logged in /var/log/yunohost/yunohost-admin.log (and probably /var/log/yunohost.log). For a classical user, once the installation is done, the only way for him to access to this information is via ssh and this is a no-go for a lot of no-technically knowledgable users and this makes support very hard in those situations.

A place to display this information could be in app page in the admin interface, for example in the debugging section.

**Comment by Psycojoker** [comment]
https://github.com/YunoHost/yunohost/pull/165
