### ISSUE TITLE
404 error for some applications

### ISSUE THREAD

**Issue by madtibo** [YunoHost/issues#1702]
Bonjour,

Bonne année 2021 et longue vie à Yunohost !!!

To start the year off right, I have upgraded my yunohost. Since then, I have some 404 error for 3 applications (the sso page and the other applications are functional): jirafeau, kanboard and roundcube.

I restarted the server, nginx, I have regenerated the nginx conf (`yunohost tools regen-conf nginx`) to no avail.

```
2021/01/06 09:01:57 [error] 727#727: *383 open() "/usr/share/nginx/html/webmail" failed (2: No such file or directory), client: 192.168.0.12, server: tribu-ml.fr, request: "GET /webmail HTTP/2.0", host: "tribu-ml.fr", referrer: "https://tribu-ml.fr/yunohost/sso/portal.html"
2021/01/06 09:02:02 [error] 727#727: *383 open() "/usr/share/nginx/html/kanboard" failed (2: No such file or directory), client: 192.168.0.12, server: tribu-ml.fr, request: "GET /kanboard HTTP/2.0", host: "tribu-ml.fr", referrer: "https://tribu-ml.fr/yunohost/sso/portal.html"
2021/01/06 09:02:10 [error] 727#727: *383 open() "/usr/share/nginx/html/jirafeau" failed (2: No such file or directory), client: 192.168.0.12, server: tribu-ml.fr, request: "GET /jirafeau HTTP/2.0", host: "tribu-ml.fr", referrer: "https://tribu-ml.fr/yunohost/sso/portal.html"
```

It looks like https://forum.yunohost.org/t/404-error-on-sso-page-usr-share-nginx-yunohost-sso-failed-2-no-such-file-or-directory/10948 or https://github.com/YunoHost/issues/issues/1514... but for an application, not the sso.

Do you have an idea apart from reinstalling these applications?

bonne journée,
Thibaut

**Comment by madtibo** [comment]
I reinstalled jirafeau and got that difference in the nginx file:

```
# diff ~/save_jirafeau/nginx_jirafeau.conf /etc/nginx/conf.d/tribu-ml.fr.d/jirafeau.conf 
1c1
<  rewrite ^/jirafeau/$ /jirafeau/ permanent;
---
>  rewrite ^/jirafeau$ /jirafeau/ permanent;
```

I removed the last `/` in the regex for kanboard and it did the trick :-)  

Do you have an idea why this error happened??

Bonne journée

**Comment by zamentur** [comment]
I think it's a security fix about path traversal issue.

> To start the year off right, I have upgraded my yunohost.

In which yunohost version ?

**Comment by madtibo** [comment]
> In which yunohost version ?

I now am in 4.0.8.3 on debian 10.7.

**Comment by madtibo** [comment]
For information, my problem is solved but maybe something should be fixed in the upgrade scripts?
