### ISSUE TITLE
Cross-arch LXC in package_check

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1704]
Follow-up of discussions with Kayou to try to be able to run cross-arch LXCs

What we understood so far: 

- Had to install qemu-user-static and binfmt-support from bullseye because recent versions fix some issues

```
wget http://ftp.fr.debian.org/debian/pool/main/q/qemu/qemu-user-static_5.2+dfsg-3_amd64.deb
dpkg -i qemu-user-static_5.2+dfsg-3_amd64.deb
wget http://ftp.fr.debian.org/debian/pool/main/b/binfmt-support/binfmt-support_2.2.1-1_amd64.deb
dpkg -i binfmt-support_2.2.1-1_amd64.deb
```

- Copying `qemu-arm-static`  to the host may help ?

```
lxc file push /usr/bin/qemu-arm-static $THE_LXC/usr/bin/
```

- Stupid issues with slapd staying alive after systemctl stops it ... then slapd restart and the old process is still using the port so miserably crash ... Ugly fix consist in opening /usr/share/yunohost/hooks/conf_regen/06-slapd and replacing the service restarts with : 

```
  systemctl stop slapd
  killall slapd
  systemctl restart slapd
```

- `nft` / iptables won't work for some reason and apparently we can't tweak kernel modules. Super ugly hack to hide everything under the carpet

```
ln -sf /bin/true /usr/sbin/iptables
ln -sf /bin/true /usr/sbin/ip6tables
```

- During the postinstall, `hostnamectl` miserably timeouts but we don't really care that much anyway about changing the hostname

- Fail2ban being fail2ban is fucking stupid and miserably crashed because /var/log/mail.log doesn't exists yet

```
touch /var/log/mail.log
```

- Epic weird bug with psutil which doesn't properly find the parent of the process, resulting in deadlock in the moulinette ... Can be reproduced by running `python2 -c "import psutil; print(psutil.Process().parent())"` which displays 'None' instead of whichever shell is running the command ... Tweaked `_is_son_of` inside `/usr/lib/python2.7/dist-packages/moulinette/core.py` to use `/proc` instead of `psutil` ...

```python
    def _is_son_of(self, lock_pids):

        if lock_pids == []:
            return False

        def parse_proc(pid, info):
            info = info + ":"
            for line in open("/proc/" + str(pid) + "/status").readlines():
                if line.startswith(info):
                    return line.split()[1]

        # Start with self
        parent = int(parse_proc(pid="self", info="Pid"))
        
        # While there is a parent... (e.g. init has no parent)
        while parent not in [0, 1]:

            # If parent PID is the lock, then yes! we are a son of the process
            # with the lock...
            if parent in lock_pids:
                return True
        
            # Otherwise, try 'next' parent
            parent = int(parse_proc(pid=parent, info="PPid"))

        return False
```

**Comment by kay0u** [comment]
Thank you for all this summary.

> During the postinstall, hostnamectl miserably timeouts but we don't really care that much anyway about changing the hostname

I fixed it with that: https://github.com/kubernetes/minikube/issues/727#issuecomment-396763876
But I don't really know what it's really doing, and whether it's really important to fix this issue.

**Comment by alexAubin** [comment]
Sooo closing because I think the conclusion was it's too hard to make cross-arch LXC work
