### ISSUE TITLE
Can't change domain of first user

### ISSUE THREAD

**Issue by ghost** [YunoHost/issues#1708]
When trying to change the domain of the first/admin user from the webmaster interface or the command line, the operation fails with an error: `This e-mail address is reserved and shall be automatically allocated to the very first user`. And when attempting to do so from the user portal, the operation fails with an `invalid domain` error.

**Comment by alexAubin** [comment]
Closing because this is probably implicitly fixed by the new admins group in Yunohost 11.1

**Comment by OniriCorpe** [comment]
i confirm
