### ISSUE TITLE
Broken config-panel

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/issues#1709]
While working on a config panel here, https://github.com/YunoHost-Apps/archivist_ynh/pull/29, I notice that probably all existing config-panel using boolean are broken.

We used to set values to `true` or `false` but it doesn't accept it anymore, returning "Use one of these choices 'yes, no, y, n, 1, 0' for the argument 'YNH_CONFIG_MAIN_ENCRYPTION_ENCRYPT'"

Also, after manually fixing it, it says "Error while parsing password argument 'YNH_CONFIG_MAIN_ENCRYPTION_ENCRYPTION_PWD': password argument can't have a default value for security reason" while `main.encryption.encryption_pwd` has `optional = true`

Too bad... config-panel could be quite useful...

**Comment by kay0u** [comment]
Should be fixed [here](https://github.com/YunoHost/yunohost/pull/1134) and [here](https://github.com/YunoHost/yunohost/pull/1135)

**Comment by kay0u** [comment]
Should be fixed in the next release
