### ISSUE TITLE
--force doesn't affect ynh_check_app_version_changed

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/issues#1710]
`--force` has been added to, I quote: "Force the update, even though the app is up to date", but that's actually a layer over `ynh_check_app_version_changed`

Using `--force` does not upgrade the app as the helper `ynh_check_app_version_changed` still says "Up-to-date, nothing to do"

Now, to upgrade you need to add `YNH_FORCE_UPGRADE=1` **AND** `--force`

**Comment by kay0u** [comment]
I forgot to update this helper and the example_ynh as well.

[Here](https://github.com/YunoHost/yunohost/pull/1136) the doc updated

**Comment by kay0u** [comment]
Fixed in 4.1.5
