### ISSUE TITLE
dyndns updates with LAN IPv6

### ISSUE THREAD

**Issue by yajo** [YunoHost/issues#1714]
I noticed today that yunohost is updating wrongly my ipv6.

It's publishing the LAN ipv6 as detected in the local eth0 interface, instead of the WAN ipv6, which is totally different.

With IPv4 it's working fine and using the WAN one.

**Comment by Psycojoker** [comment]
Your ipv6 is grab by doing the equivalent of "curl ip6.yunohost.org", I guess it's a matter of your local network configuration then? I don't think we can really guess which interface should be used for that.

**Comment by yajo** [comment]
Yikes, that's weird. While being in the same LAN, with the same gateway, `curl ip6.yunohost.org` returns different results depending if I run it on my laptop or on my yunohost server. 😵

**Comment by alexAubin** [comment]
... Which makes sense because in IPv6 machines have a unique global address instead of sharing the same IP(v4) of the router/NAT ?

**Comment by yajo** [comment]
Really? So, that should be OK? Should the world be able to find my host even with no router rules? I'm confused... 😵

**Comment by zamentur** [comment]
Until you have some ipv6 firewall rules that restrict access, yes the world could ping your laptop or your server.

I am not sure that's a good idea if you isp don't put a firewall to avoid that but it's helpfull when you do self hosting.

I clause this ticket cause it's not a bug, it's just work !
