### ISSUE TITLE
set smtp settings via yunohost raise warning: 'yunohost service regen-conf' is deprecated!

### ISSUE THREAD

**Issue by jedie** [YunoHost/issues#1717]
following commands raise the warning: `Warning: 'yunohost service regen-conf' is deprecated! Please use 'yunohost tools regen-conf' instead.`

- `yunohost settings set smtp.relay.host`
- `yunohost settings set smtp.relay.user`
- `yunohost settings set smtp.relay.password`

**Comment by alexAubin** [comment]
Thank you for the bug reported :+1: 

Fixed in https://github.com/YunoHost/yunohost/commit/9c11fd58e25c9ecb8cedcd140ed6ee46b210c4ee
