### ISSUE TITLE
Setup smtp relay in web gui admin...

### ISSUE THREAD

**Issue by jedie** [YunoHost/issues#1721]
I wish there is a admin web gui to input the settings for smtp relay with a test function.

**Comment by anmol26s** [comment]
I don't know if its close to what you want achieve, but you can try this:
https://forum.yunohost.org/t/external-smtp-relay-server-for-the-domain/5731/2?u=kanhu

**Comment by tootbrute** [comment]
> I wish there is a admin web gui to input the settings for smtp relay with a test function.

YES! Great idea. Email is basically broken without an SMTP relay server, so would be great to have a more streamlined way to do it.

**Comment by alexAubin** [comment]
(Should be easy to implement in the webadmin once global settings are reworked using the new config panel mecanism)

**Comment by alexAubin** [comment]
Done in 11.1
