### ISSUE TITLE
Torrent for download last yunhost ing

### ISSUE THREAD

**Issue by manumacron** [YunoHost/issues#1722]
Lo,
Making yunhost available through torrent network shall decrease server charge, improve its availability, resilience, and –in a way– security.

### Technical question (fake one)

Creating a torrent seems to be pretty easy; bitorrent clients let your make your own through their interfaces; inluding cli with transmission-cli:
 ```
 transmission-create -t udp://9.rarbg.to:2710/announce -o 1984.torrent 1984.pdf 
 ```  
 Will create a 1984.torrent file, that allow you to seed the pdf. We could make a script to make it automatically. If there is some hook, we even could execute it to update a torrent file that is pointed out by the hyperlink on the webside
 
 ### Workflow question (true one)
 
In order to make it usable, we may promote that link, in including it in the "new yunhost version" available. Maybe it's a question for the communication team, or maybe we could make a bot to do it.

Some people pointed out that people we couldn't rely on long time work under capitalism. If it was true, we should ask ourselves if it's better to have unupdated torrent available or no torrent at all

**Comment by manumacron** [comment]
Or we could make an app th automatically seed the last version of yunhost :)

**Comment by manumacron** [comment]
To automatically post on mastodon when new version is available, we could use the python library :

```
from mastodon import Mastodon

mastodon = Mastodon(
        access_token = '__ynhost_access_token_',
        api_base_url = 'https://mastodon.social'
    )
mastodon.toot("""Hi everyone,                                      
The new version of #yunhost is available. 
You could download the installation img here : https://yunohost.org/#/images
or through the torrent :  https://yunohost.org/#/images/torrents           
""")

```

Adding the git hook would fully automated the process

**Comment by alexAubin** [comment]
Closing because meh
