### ISSUE TITLE
Password containing unicode characters, causing issues when authenticating in Metronome.

### ISSUE THREAD

**Issue by maranda** [YunoHost/issues#1729]
Just reporting this issue, as it could be caused by passwords containing unicode not being stringprepped correctly before they're stored into the LDAP database.

See: https://github.com/maranda/metronome/issues/529

If you could also check out please.

**Comment by maranda** [comment]
Closing this on Metronome's side as this is a problem on either YuNoHost management interface that doesn't prep out correctly the password when storing it into the backend, mod_auth_ldap2/lualdap2 when it passes the password to the backend, or the LDAP server backend itself not being able to store passwords containing unicode endpoints.

**Comment by zamentur** [comment]
This bug is still here in 4.2.5 ?

**Comment by alexAubin** [comment]
Closing because metronome is to become an app in Bookworm / YunoHost 12.x : https://github.com/YunoHost-Apps/metronome_ynh
