### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by tiotrom** [YunoHost/issues#1731]
After installing YunoHost I got this message:

> It seems that you have already configured MySQL. YunoHost needs to have a root access to MySQL to runs its applications, and is going to reset the MySQL root password. You can find this new password in /etc/yunohost/mysql." 

I grabbed that password but I am not sure if I should try to do anything. I am concerned I make break my ynh install. 

Installing certain apps give me this error: 

`WARNING - ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)`

**Comment by alexAubin** [comment]
Zblerg yeah

Can you try the following (should be equivalent to what the regen conf does during first initialization): 

```bash
mysql_password="$(cat /etc/yunohost/mysql)"

MYSQL_PKG="$(dpkg --list | sed -ne 's/^ii  \(mariadb-server-[[:digit:].]\+\) .*$/\1/p')"
echo "mysql package: $MYSQL_PKG"

debconf-set-selections << EOF
$MYSQL_PKG mysql-server/root_password password $mysql_password
$MYSQL_PKG mysql-server/root_password_again password $mysql_password
EOF

dpkg-reconfigure -freadline -u "$MYSQL_PKG"
mysqladmin -s -u root -pyunohost password "$mysql_password" && echo "its ok!" || echo "still not working :("
```

(I don't know how familiar you are with command line tho)

**Comment by tiotrom** [comment]
Thanks!

I am a bit familiar but since I would not want to destroy my ynh installation, can you give me step by step what to do via the command line? I would greatly appreciate it! I know that if I mess one line or some little character, I may break it and I'd rather not.

**Comment by alexAubin** [comment]
The step by step is pretty much what I wrote in the previous comment ;)

Just be sure to be logged as root (or admin, then "sudo su" or "sudo -i" to become root)

Also be careful that the `debconf-set-selections` ... `EOF` stuff is a 4-line command to be copy/pasted as a single block.

Other than this, these are just "regular" commands

**Comment by tiotrom** [comment]
Ok I get some errors. First 
```

debconf-set-selections << EOF
$MYSQL_PKG mysql-server/root_password password $mysql_password
$MYSQL_PKG mysql-server/root_password_again password $mysql_password
EOF
```
I get : 
"Warning: Unknown type (and here it displays my password), skipping line 1
Warning: Unknown type (and here it displays my password), skipping line 2 "

If I continue I get:
```
dpkg-reconfigure -freadline -u "$MYSQL_PKG"
mysqladmin -s -u root -pyunohost password "$mysql_password" && echo "its ok!" || echo "still not working :("
```
"dpkg-quary: error: --control-path needs at least one package argument"

![image](https://user-images.githubusercontent.com/34804533/106646012-6c7f2c80-658d-11eb-9806-27dd461534db.png)

**Comment by alexAubin** [comment]
Hmokay but what about

```
MYSQL_PKG="$(dpkg --list | sed -ne 's/^ii  \(mariadb-server-[[:digit:].]\+\) .*$/\1/p')"
echo "mysql package: $MYSQL_PKG"
```

(i'm interested in the echo because i'm suspecting the variable to be empty)

Or let's look at : 

```
dpkg --list | grep "maria\|sql"
```

**Comment by tiotrom** [comment]
```
root@tromsite:/home/admin# MYSQL_PKG="$(dpkg --list | sed -ne 's/^ii  \(mariadb-server-[[:digit:].]\+\) .*$/\1/p')"
root@tromsite:/home/admin# echo "mysql package: $MYSQL_PKG"
mysql package: mariadb-server-10.3
```
and

```
root@tromsite:/home/admin# dpkg --list | grep "maria\|sql"
ii  libdbd-mysql-perl:amd64               4.050-2                               amd64        Perl5 database interface to the MariaDB/MySQL database
ii  libmariadb3:amd64                     1:10.3.27-0+deb10u1                   amd64        MariaDB database client library
ii  libopendbx1-sqlite3                   1.4.6-13+b1                           amd64        SQLite3 backend for OpenDBX
ii  libsqlite3-0:amd64                    3.27.2-3+deb10u1                      amd64        SQLite 3 shared library
ii  libsqlite3-dev:amd64                  3.27.2-3+deb10u1                      amd64        SQLite 3 development files
ii  mariadb-client                        1:10.3.27-0+deb10u1                   all          MariaDB database client (metapackage depending on the latest version)
ii  mariadb-client-10.3                   1:10.3.27-0+deb10u1                   amd64        MariaDB database client binaries
ii  mariadb-client-core-10.3              1:10.3.27-0+deb10u1                   amd64        MariaDB database core client binaries
ii  mariadb-common                        1:10.3.27-0+deb10u1                   all          MariaDB common metapackage
ii  mariadb-server                        1:10.3.27-0+deb10u1                   all          MariaDB database server (metapackage depending on the latest version)
ii  mariadb-server-10.3                   1:10.3.27-0+deb10u1                   amd64        MariaDB database server binaries
ii  mariadb-server-core-10.3              1:10.3.27-0+deb10u1                   amd64        MariaDB database core server files
ii  mysql-common                          5.8+1.0.5                             all          MySQL database common files, e.g. /etc/mysql/my.cnf
ii  php-mysql                             2:7.3+69                              all          MySQL module for PHP [default]
ii  php-pgsql                             2:7.3+69                              all          PostgreSQL module for PHP [default]
ii  php-sqlite3                           2:7.3+69                              all          SQLite3 module for PHP [default]
ii  php7.3-mysql                          7.3.19-1~deb10u1                      amd64        MySQL module for PHP
ii  php7.3-pgsql                          7.3.19-1~deb10u1                      amd64        PostgreSQL module for PHP
ii  php7.3-sqlite3                        7.3.19-1~deb10u1                      amd64        SQLite3 module for PHP
ii  postgresql                            11+200+deb10u4                        all          object-relational SQL database (supported version)
ii  postgresql-11                         11.9-0+deb10u1                        amd64        object-relational SQL database, version 11 server
ii  postgresql-client-11                  11.9-0+deb10u1                        amd64        front-end programs for PostgreSQL 11
ii  postgresql-client-common              200+deb10u4                           all          manager for multiple PostgreSQL client versions
ii  postgresql-common                     200+deb10u4                           all          PostgreSQL database-cluster manager
ii  postgresql-contrib                    11+200+deb10u4                        all          additional facilities for PostgreSQL (supported version)

```

**Comment by tiotrom** [comment]
I re-did all of the instructions above via ssh. Before I was on a VNC. So I could copy paste them. I get this

```
root@tromsite:/home/admin# mysql_password="$(cat /etc/yunohost/mysql)"
root@tromsite:/home/admin# MYSQL_PKG="$(dpkg --list | sed -ne 's/^ii  \(mariadb-server-[[:digit:].]\+\) .*$/\1/p')"
root@tromsite:/home/admin# echo "mysql package: $MYSQL_PKG"
mysql package: mariadb-server-10.3
root@tromsite:/home/admin# debconf-set-selections << EOF
> $MYSQL_PKG mysql-server/root_password password $mysql_password
> $MYSQL_PKG mysql-server/root_password_again password $mysql_password
> EOF

root@tromsite:/home/admin# 
root@tromsite:/home/admin# dpkg-reconfigure -freadline -u "$MYSQL_PKG"

root@tromsite:/home/admin# mysqladmin -s -u root -pyunohost password "$mysql_password" && echo "its ok!" || echo "still not working :("
still not working :(

```

**Comment by alexAubin** [comment]
Alrighty ... then let's go deeper into the rabbit hole ... You're going to need *two* terminals (also with the root user) for this.

In the first terminal, run: 

```
systemctl stop mysql
mysqld_safe --skip-grant-tables
```

The second command should *hang* meaning it won't stop until you stop it manually with Ctrl+C. It starts mysql with authentication disabled, meaning you should be able to open a mysql shell with no authentication/password needed.

In the second terminal, run : 

```
mysql
```

(no password or any argument, yes) It should open a mysql prompt. In this prompt, type: 

```
SELECT user, authentication_string, plugin, host FROM mysql.user;
```

What do you see ?

You should see something like:

```
+------+-------------------------------------------+-----------------------+-----------+
| user | authentication_string                     | plugin                | host      |
+------+-------------------------------------------+-----------------------+-----------+
| root | *37558E6F5D07CEA0991E646FD6C4E4C9173FA46A | mysql_native_password | localhost |
+------+-------------------------------------------+-----------------------+-----------+
```

Once you're done, exit both terminal (Ctrl+C in each)

Alternatively, can we check the output of : 

```
grep localhost /etc/hosts
```

**Comment by tiotrom** [comment]
I see this:

+------+-----------------------+-----------------------+-----------+
| user | authentication_string | plugin                | host      |
+------+-----------------------+-----------------------+-----------+
| root |                       | mysql_native_password | localhost |
+------+-----------------------+-----------------------+-----------+

Also:

```
admin@tromsite:~$ grep localhost /etc/hosts
127.0.0.1	localhost
::1     localhost ip6-localhost ip6-loopback
```

**Comment by tiotrom** [comment]
Basically authentication_string is empty...

**Comment by alexAubin** [comment]
Yeah ... I realize the issue was pretty clear in the previous screenshot, after the debconf selection stuff, we see: 
"Warning: unknown type [the password], skipping line 1/2"

Which in fact seems symptomatic of the fact that the variable $MYSQL_PKG is empty, so everything appears shifted to the program (idk if i'm making sense but bear with me)

But you showed later that the variable did contain stuff ... but apparently you re-ran those command so idk, maybe something happened the first time (forgot to press enter, cosmic ray, idk). So let's just be sure and retry the procedure.

First, be sure to kill any remaining mysql program and restart the proper mysql daemon following our experiment:

```
pkill mysqld
pkill mysqld_safe
systemctl restart mysql
```

Then re-run the whole thing (and make sure to check that $MYSQL_PKG ain't empty!)

```bash
mysql_password="$(cat /etc/yunohost/mysql)"
MYSQL_PKG="$(dpkg --list | sed -ne 's/^ii  \(mariadb-server-[[:digit:].]\+\) .*$/\1/p')"
echo "mysql package: $MYSQL_PKG"



#############################################################
# HERE, really make sure that the previous echo command does show a package name !
# The package name should be 'mariadb-server-10.3' !
#############################################################



debconf-set-selections << EOF
$MYSQL_PKG mysql-server/root_password password $mysql_password
$MYSQL_PKG mysql-server/root_password_again password $mysql_password
EOF

##########
# Here if we again see the same warning then there's something funky going on ...
###########

dpkg-reconfigure -freadline -u "$MYSQL_PKG"
mysqladmin -s -u root -pyunohost password "$mysql_password" && echo "its ok!" || echo "still not working :("

```

**Comment by tiotrom** [comment]
Hm I did them all in order....

```
admin@tromsite:~$ sudo su
root@tromsite:/home/admin# pkill mysqld
root@tromsite:/home/admin# pkill mysqld_safe
root@tromsite:/home/admin# systemctl restart mysql
root@tromsite:/home/admin# mysql_password="$(cat /etc/yunohost/mysql)"
root@tromsite:/home/admin# MYSQL_PKG="$(dpkg --list | sed -ne 's/^ii  \(mariadb-server-[[:digit:].]\+\) .*$/\1/p')"
root@tromsite:/home/admin# echo "mysql package: $MYSQL_PKG"
mysql package: mariadb-server-10.3
root@tromsite:/home/admin# debconf-set-selections << EOF
> $MYSQL_PKG mysql-server/root_password password $mysql_password
> $MYSQL_PKG mysql-server/root_password_again password $mysql_password
> EOF
root@tromsite:/home/admin# dpkg-reconfigure -freadline -u "$MYSQL_PKG"
root@tromsite:/home/admin# mysqladmin -s -u root -pyunohost password "$mysql_password" && echo "its ok!" || echo "still not working :("
still not working :(

```

**Comment by tiotrom** [comment]
I found this but is in french https://forum.yunohost.org/t/error-1045-28000-access-denied-for-user-root-localhost-using-password-no/5151/2

From what I understand the solution is to edit /etc/mysql/debian.cnfc and add the password manually?

....maybe is for a different kind of issue tho..

**Comment by alexAubin** [comment]
Zzzzzzblerg it's kind of the same issue I suppose, maybe, but I believe that user "debian-sys-maint" doesn't seem to be configured, otherwise I believe we should have seen a corresponding line in the previous SELECT stuff

BUuuuuut if we really want to have a shell and inject a password manually I guess we can re-do the whole thing of "starting mysqld_safe --skip-grant-tables" in one terminal, "mysql" to open a shell in another, then yeah let's try to 

```
SET PASSWORD FOR root@'localhost'=PASSWORD('the_mysql_password');
``` 

then if you run 

```
SELECT user, authentication_string, plugin, host FROM mysql.user;
```

you should see some nonempty authentication string ...

(Doesn't really tell why the automatic configuration did not work in the first place which I was hoping to figure out :/ )

**Comment by tiotrom** [comment]
You know it is weird. I have 2 servers on the same hosting. One on an SSD one on HDD. The SSD went fine, same version of ynh. On HDD I got that Mysql error...

If you want I can try more if it helps you diagnose any issue. If not what should I do more exactly? I am sorry to ask you for the exact steps but I don't want to mess up. I am fine at customizing some linux distros and doing some packaging, but when it comes to servers I am not familiar.

And thank you so much for all the help!

**Comment by alexAubin** [comment]
Hmmmmmmwell hold on I'm thinking about other hypothesis ... Now I wonder if the current Yunohost in fact does anything at all lol ...

**Comment by tiotrom** [comment]
I'm waiting :) - no rush ;)

**Comment by alexAubin** [comment]
So yeah I'm pretty sure the current code is in fact completely fucking useless. Thanksfully mariadb/mysql is an absolutely sane piece of software, there's only 71154 ways to do this simple operation of "resetting the root password when you're already root", and only 1 of these works for your setup depending on the exact version you're running, the OS you're using, which date it is, and the current state of the moon in your timezone.

Soooo let's try this. Be sure to replace 'MY_NEW_PASSWORD' with the output of `cat /etc/yunohost/mysql`

```text
systemctl stop mariadb
( mysqld_safe --skip-grant-tables --skip-networking & )
sleep 2 
mysql -u root <<< "UPDATE mysql.user SET authentication_string = PASSWORD('MY_NEW_PASSWORD') WHERE User = 'root' AND Host = 'localhost'; FLUSH PRIVILEGES;"
pkill -9 mysqld
systemctl start mariadb
```

**Comment by tiotrom** [comment]
Ok, so here's what I get:

```
root@tromsite:/home/admin# systemctl stop mariadb
root@tromsite:/home/admin# ( mysqld_safe --skip-grant-tables --skip-networking & )
root@tromsite:/home/admin# sleep 2 
210203 03:19:20 mysqld_safe Logging to '/var/lib/mysql/tromsite.tk.err'.
210203 03:19:20 mysqld_safe A mysqld process already exists
root@tromsite:/home/admin# mysql -u root <<< "UPDATE mysql.user SET authentication_string = PASSWORD('*********') WHERE User = 'root' AND Host = 'localhost'; FLUSH PRIVILEGES;
> pkill -9 mysqld
> systemctl start mariadb

```

![image](https://user-images.githubusercontent.com/34804533/106688636-c5bb8000-65ce-11eb-841b-620acd118d06.png)

Maybe I need to copy the code line by line?

**Comment by alexAubin** [comment]
Ugh my bad, I forgot a closing quote " in the middle (super-long) line at the end ... You can ctrl+c and retry the "mysql -u root ... blabhablha"

**Comment by tiotrom** [comment]
Heeey I think it worked! Thank you so much! But yah, probably would have helped to know why this happened in the first place....

**Comment by tiotrom** [comment]
Thank you so much! I really appreciate your help!

**Comment by alexAubin** [comment]
Yeah nevermind about understanding why it didnt work on your setup, at least we learned that the current existing code was probably not doing anything since ~ 1 year or more, so now the question is more **how the hell did it work for everybody else** rather than understanding why it didn't work for you ... I'm guessing this has to do with the socker auth mecanism but not sure ..

**Comment by tiotrom** [comment]
Interesting...at least you found something out.
