### ISSUE TITLE
Better backup integration

### ISSUE THREAD

**Issue by tiotrom** [YunoHost/issues#1733]
I know there are apps like Archivist or Borg, but would be fantastic if the integrated backup feature would be just a little bit more feature-full. Like scheduled backups with an "exclude/include" list of apps and settings + an sftp remote backup to simply add the backups to a remote location. 

I have a 1.4TB ynh with peertube and nextcloud among the installed apps, and I am struggling to find a simple solution to basically backup the entire yunohost + apps to a remote location incrementally.

**Comment by tiotrom** [comment]
Another question: is it possible to auto delete the local backups after X amount of time?

**Comment by zamentur** [comment]
I close it cause features describe in this ticket are available with the borg app. I am aware UX could be improve, other ticket already describe how.
