### ISSUE TITLE
application invisible in yunohost

### ISSUE THREAD

**Issue by MX10-AC2N** [YunoHost/issues#1734]
Hello,
I'm new to yunohost I have a server that works pretty well, I already have some applications installed to test the different services that it could bring me and I ended up wanting to install rainloop, the installation crashed and I had to relaunch system updates to relaunch yunohost but now when I go to the installed applications, nothing appears, but I can access my different applications via their domain names .. I have errors :
Failed to read info for spftoolbox : 'NoneType' object has no attribute 'items'

Failed to read info for rainloop__2 : Fichier JSON corrompu en lecture depuis /etc/yunohost/apps/rainloop__2/manifest.json (raison : No JSON object could be decoded)

Failed to read info for rainloop : Fichier JSON corrompu en lecture depuis /etc/yunohost/apps/rainloop/manifest.json (raison : No JSON object could be decoded)

Failed to read info for phpsysinfo : 'NoneType' object has no attribute 'items'

Failed to read info for nextcloud : 'NoneType' object has no attribute 'items'

Failed to read info for netdata : 'NoneType' object has no attribute 'items'

Failed to read info for jellyfin : 'NoneType' object has no attribute 'items'

Failed to read info for grocy : 'NoneType' object has no attribute 'items'

Failed to read info for grafana : 'NoneType' object has no attribute 'items'

Failed to read info for spftoolbox : 'NoneType' object has no attribute 'items'

Failed to read info for rainloop__2 : Fichier JSON corrompu en lecture depuis /etc/yunohost/apps/rainloop__2/manifest.json (raison : No JSON object could be decoded)

Failed to read info for rainloop : Fichier JSON corrompu en lecture depuis /etc/yunohost/apps/rainloop/manifest.json (raison : No JSON object could be decoded)

Failed to read info for phpsysinfo : 'NoneType' object has no attribute 'items'

Failed to read info for nextcloud : 'NoneType' object has no attribute 'items'

Failed to read info for netdata : 'NoneType' object has no attribute 'items'

Failed to read info for jellyfin : 'NoneType' object has no attribute 'items'

I don't know how to fix this, if someone has the solution ...
Thank you..

**Comment by alexAubin** [comment]
Wokay, can you check in Tools > Migrations that there's no pending migration (in particular migration 19)

**Comment by MX10-AC2N** [comment]
I've checked Tools > Migrations and there's no pending migration, migration 19 is under previous migration..

**Comment by alexAubin** [comment]
Hmokay then let's talk about that "rainloop install that crashed"

Are you able to go in Tools > Logs > ... the failed installed ... and share the log using "Share with Yunopaste" ?

**Comment by MX10-AC2N** [comment]
Hmm.. no way.. in my log I don't have any log between '9 hours ago and' 4 days ago '
I've error with add domain and let's encrypt in log I "Share with Yunohost".. Maybe..
https://paste.yunohost.org/raw/equfowuqij
https://paste.yunohost.org/raw/iyanuhihaq

**Comment by MX10-AC2N** [comment]
In the application catalog, the applications that I had installed previously are marked as installed and therefore I cannot do any reinstallation.
Only Rainloop is not marked installed, if I run an installation I have an error again.

Action
POST /apps
 {"app":"rainloop","args":"domain=ac2n.ynh.fr&path=%2Frainloop&is_public=1&password=Bambouleche66!&ldap=1&lang=fr","label":"Rainloop"}
Trace
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 485, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 592, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 358, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/moulinette/yunohost/app.py", line 758, in app_install
    _validate_and_normalize_webpath(manifest, args_odict, extracted_app_folder)
  File "/usr/lib/moulinette/yunohost/app.py", line 2689, in _validate_and_normalize_webpath
    _assert_no_conflicting_apps(domain, path)
  File "/usr/lib/moulinette/yunohost/app.py", line 2773, in _assert_no_conflicting_apps
    conflicts = _get_conflicting_apps(domain, path, ignore_app)
  File "/usr/lib/moulinette/yunohost/app.py", line 2752, in _get_conflicting_apps
    apps_map = app_map(raw=True)
  File "/usr/lib/moulinette/yunohost/app.py", line 270, in app_map
    permissions = user_permission_list(full=True, absolute_urls=True)["permissions"]
  File "/usr/lib/moulinette/yunohost/permission.py", line 65, in user_permission_list
    for app in apps
  File "/usr/lib/moulinette/yunohost/permission.py", line 66, in 
    if app_setting(app, 'domain') and app_setting(app, 'path')}
  File "/usr/lib/moulinette/yunohost/app.py", line 1204, in app_setting
    app_settings = _get_app_settings(app) or {}
  File "/usr/lib/moulinette/yunohost/app.py", line 1894, in _get_app_settings
    settings = {k: _encode_string(v) for k, v in settings.items()}
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by MX10-AC2N** [comment]
So, I start a new fresh install..
