### ISSUE TITLE
Helper availability function ynh_webpath_available result is inconsistent

### ISSUE THREAD

**Issue by a0kami** [YunoHost/issues#1736]
Hey, I was revamping a yunohost package and made sure to use the helpers as much as I could, I noticed a small inconsistency.

Most existence or availability helpers returns either 0 or 1, directly usable in bash conditional expressions (`if [[ $(command) ]]`) or conditionally lists of commands (`command || ynh_die`).
E.g: `ynh_user_exists`, `ynh_psql_{user,database}_exists`, `ynh_permission_exists`, and so on,

However `ynh_webpath_available` seems to just echo either `False` or `True` but always return a successful `0`.
This is the direct result of `yunohost domain url-available $domain $path_url` ([here](https://github.com/YunoHost/yunohost/blob/e1062f145777bddbe6294932f7758c557306838c/data/helpers.d/setting#L127)).
I fail to understand how it is hooked to the `yunohost` command to print the last line of `domain_url_available()` in `domain.py:384` rather than just return value (I understand python's "False"/"True" don't exist in bash but why is it printed ?).

It does seem to be widely used already in the yunohost packages mostly like this `ynh_webpath_available [args] || ynh_die`.

There further is an extra confusions, `ynh_package_is_installed` does return either 0 or 1 but it's not explicit in the doc, just hinted via the example, but that's quite a minor concern.

**Comment by alexAubin** [comment]
Hmpf yeah indeed ... I see it's mostly used in the restore script

In fact, nowadays this is properly pointless to call this helper/command because this check is performed by the core before actually running the script ... I'm not 100% sure about the case of app restoration but pretty sure it's not needed anymore here either (and as you explain, it will always return exit code 0 so ...)

We should probably remove this from example_ynh if that's the place suggesting it, and add a check in package_linter to suggest that the line ain't relevant

**Comment by a0kami** [comment]
I'm afraid it's not even in the `example-ynh`, I took the liberty to look for interesting helpers. 😥

Sorry about that, given it's just an information gathering helper and it has no consequence I labelled as "Info" instead of "Warning" and gave it a shot in [this commit](https://github.com/a0kami/package_linter/commit/59576e075ddc31117789881b58d886ac2a5f65cc) (I'm a bit clumsy with Pull Requests so I thought I'd wait for approval first).

Would this particular helper be marked as deprecated/ultimately removed at some point ?

**Comment by alexAubin** [comment]
Yes indeed it should be marked as deprecated I think :+1: 

You commit sounds good, feel free to create a PR :+1: ! (Usually don't be too afraid about creating a PR right away, the very purpose of pull requests is precisely to "propose" changes such that people can review it ;P)

**Comment by alexAubin** [comment]
Closing because the linter now complains about it
