### ISSUE TITLE
The CI do not recognize valid output for url

### ISSUE THREAD

**Issue by anmol26s** [YunoHost/issues#1738]
Hi,
The CI fails when there is valid output for the url.

It says:

```
curl: (7) Failed to connect to sub.domain.tld port 80: Connection timed out
Error: Connection error...
```

See this CI test.
https://ci-apps-dev.yunohost.org/ci/job/247

**Comment by alexAubin** [comment]
Closing because it's not clear what's the context / issue is exactly, and the job disappared (the ci-apps-dev was resetted a couple time since then)
