### ISSUE TITLE
Installed applications are not marked as installed 

### ISSUE THREAD

**Issue by sharicov** [YunoHost/issues#1750]
When going into Applications, Install some installed applications are not marked as installed (Nextcloud, Wetty).
When clicking on install, getting message that app is already installed.
Wondering if those are monitored for updates.

**Comment by alexAubin** [comment]
Well can you elaborate on when that's started to happen ... Anything about a recent upgrade to 4.1 maybe ...

**Comment by sharicov** [comment]
I didn't catch when exactly it happened.
Currently running latest version on raspberry pi4.
Did all updates as appeared available, didn't customize any apps.

**Comment by alexAubin** [comment]
But did the problem appeared maybe *after* you ran the upgrade to 4.1 ...

Also can you go in Tools > Migrations and check if there's any pending migration ...

**Comment by sharicov** [comment]
Unfortunately cannot tell, just noticed couple of day ago, I am not adding apps regularly...
No pending migrations

**Comment by alexAubin** [comment]
Closing because that looks like some confusion about currently installed apps not being displayed as installed in the catalog, because they are multi-instance-capable ...
