### ISSUE TITLE
 defective on the Yuno host server, I set everything up again. I even uploaded the backup

### ISSUE THREAD

**Issue by carrabelloy** [YunoHost/issues#1754]
Hello, after something went defective on the Yuno host server, I set everything up again. I even uploaded the backup via scp using a terminal. After everything was done, I broke up after 3 a.m.
Now I'm trying to get back to my server via the terminal which doesn't work. In addition, new errors when renewing the scripts appear. Is anyone able to help me. Here is a link for error analysis. Since maybe others still have the same problem. Excuse me. Everything is translated here with a translation tool, since my English is not exactly great. Here's the error message for letsand script https://paste.yunohost.org/raw/sucoyotehu

**Comment by tituspijean** [comment]
(cf. https://forum.yunohost.org/t/defective-on-the-yuno-host-server-i-set-everything-up-again-i-even-uploaded-the-backup/14942)

**Comment by carrabelloy** [comment]
Duplicate of #Nevertheless, there has not been also helped me. I mean a little more understanding for it to raise for it here several itself find in whole Europe those of your national language are closer. With me it is a German. Hence, I translate with a translator. Because it should be always English, nevertheless, thus please they come along please to support me before they close everything. Since, otherwise, I find no more okay. Or does one select here now? Thanks
