### ISSUE TITLE
Can't display result of port diagnosis

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1755]
# Context
In 4.2 unstable with new webadmin in lxd with ynh-dev

# Problem

I got Object of type dict_keys is not JSON serializable instead of displaying result : 

![image](https://user-images.githubusercontent.com/4080016/111086640-83665680-851d-11eb-9c37-83a57b8b7657.png)

**Comment by alexAubin** [comment]
Sounds like a python3 regressions, gotta put a `list()` somewhere

**Comment by kay0u** [comment]
fixed by https://github.com/YunoHost/yunohost/commit/dc6033c3993023162869d770029b5ee8baab1c03
