### ISSUE TITLE
[demo] Slow loading of pages

### ISSUE THREAD

**Issue by mdziczkowski** [YunoHost/issues#1757]
In theonline demo, after login, the pages content takes too long to load

**Comment by alexAubin** [comment]
Can you tell what page ? I just tried it and after login on the SSO I see the tiles directly ..?

**Comment by mdziczkowski** [comment]
I had opened the admin panel and wanted to look over the functions.

Note: I use a phone with Android 10

**Comment by zamentur** [comment]
Don't know if it was related to an abuse on our demo or if it's 4G connectivity issue or javascript performance...
Could you quantify "too long", it's the old web admin on the demo and there are some pacman a bit long indead.

**Comment by mdziczkowski** [comment]
> Don't know if it was related to an abuse on our demo or if it's 4G connectivity issue or javascript performance...

I think the most possible is the javascript performance option, but I'm not sure. Please check if the code is optimized for quick working and the scripts from exteral vendors (like for example: jQuery, etc.) are loaded from (for example): https://jquery.googleapis.com

> Could you quantify "too long", it's the old web admin on the demo and there are some pacman a bit long indead.

By "too long" I meant that sometimes several minutes were needed to get the content to become loaded or the (not critical) values get updated (for testing propouses)
