### ISSUE TITLE
mastodon install failed because mimemagic 0.3.5 is no longer available

### ISSUE THREAD

**Issue by exfrog** [YunoHost/issues#1765]
seems mimemagic 0.3.5 is no longer available and is breaking the mastodon install
see  >>  https://rubygems.org/gems/mimemagic/versions/0.3.5

log >> https://paste.yunohost.org/raw/sakeziguhe

**Comment by ericgaspar** [comment]
@exfrog please, open an issue on the mastodon_ynh repo https://github.com/YunoHost-Apps/mastodon_ynh

**Comment by yalh76** [comment]
already known issue https://github.com/tootsuite/mastodon/issues/15977

will be solved in next mastodon version
