### ISSUE TITLE
Backup/Restore doesn't accept full restore filename with filename extension

### ISSUE THREAD

**Issue by lightnin** [YunoHost/issues#1766]
Restoring backups from the command line should not require the user to know that they must not include the filename suffix (i.e.: ".tar") in the instruction.  Most users will use the terminal autofill rather than write out the filename, and the autofill will include the suffix by default. When the user then tries to execute the restore command, they receive an error message that seems to indicate that the file they have asked to be restored is not the right file. This, along with the fact that the command line backup operation outputs multiple files and directories in addition to the .tar archive, is likely to create confusion about which file is actually the backup archive file and how it must be restored.

This issue is indicated in the docs re: backup / restore, but it's difficult to find / counter intuitive / shouldn't be required.
https://yunohost.org/en/backup
"From the command line, you can run yunohost backup restore <archivename> (without the .tar.gz)" 

Many thanks to all the contributors for making such great software.

**Comment by alexAubin** [comment]
Fixed in https://github.com/YunoHost/yunohost/commit/00ec7b2fc432139cd5b8924b19b8d90e9e6dae7a for next 4.2.x
