### ISSUE TITLE
How to really skipped an url ?

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/issues#1768]
Hi

Since there's no `skipped_uris` anymore, I'm wondering how to properly skipped an url from the sso.
Currently, with a sso configured as such
```
"app.main": {
    "auth_header": false, 
    "label": "Label", 
    "public": true, 
    "show_tile": true, 
    "uris": [
        "domain.tld"
    ], 
    "users": [
        "user"
    ]
}
```
While the auth_header may, perhaps, not be sent, the url isn't skipped from the sso, as the cookie still contains
```
'SSOwAuthRedirect=; Path=/yunohost/sso/; Expires=Thu, 01 Jan 1970 00:00:00 UTC; Secure; HttpOnly; SameSite=Lax,
```
This is currently an issue since it broke the connection from a client application trying to connect to its server because the cookie isn't as expected.

So, is there a way to properly exclude an url from the sso ? As `skipped_uris`
Or to configure nginx to exclude that cookie ?

**Comment by kay0u** [comment]
Hi!

`auth_header=false` is the new `skipped_uris` and, they both work in the same way.
The cookie `SSOwAuthRedirect` is not related to `auth_header` (or `skipped_uris`), and to me it's not used anymore.

This issue should be fixed by https://github.com/YunoHost/SSOwat/pull/182

**Comment by maniackcrudelis** [comment]
Thanks for that fix, I confirm that it does fix the issue with the cookie injected into any request :+1:
