### ISSUE TITLE
[ssowat] misleading logged out message

### ISSUE THREAD

**Issue by trogeat** [YunoHost/issues#1769]
### Describe the bug

We are facing a bug on many instance of Yunohost, when logged in the main user panel, if you close it and come back later sometime a message telling you are logged out is displayed.

If you just hit the refresh key, message disappear.

Message is displayed in flash info box

### Context

- Hardware: *VPS or baremetal*
- YunoHost version:
yunohost: 
  repo: stable
  version: 4.1.7.4
yunohost-admin: 
  repo: stable
  version: 4.1.4
moulinette: 
  repo: stable
  version: 4.1.4
ssowat: 
  repo: stable
  version: 4.1.3
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

Open your browser to yunohost, login with a user.

If you close yunohost panel and come back later sometime a message telling you are logged out is displayed but in fact no.

If you just hit the refresh key, message disappear and you are still loggued in.

### Expected behavior

This message should not be displayed

### Logs

I tried to add debug log in access.lua and helpers.lua to understand the problem and found that it was linked to a previous redirect from http to https.
It looks like when you open your browser back on the yunohost panel, sso token is checked and then message is displayed :+1: https://github.com/YunoHost/SSOwat/blob/547e15157bf8d0fdffe531a0fc34c72911c92a7b/access.lua#L349
I'm not sure why it was decided to display this message after redirection.

Can you help me understand/resolve this ?

Thanks :-)

**Comment by alexAubin** [comment]
Closing because probably implicitly fixed by the sso rework in bookworm
