### ISSUE TITLE
[SSH] .ssh folder with 777 permissions for YNH users

### ISSUE THREAD

**Issue by sy6sy2** [YunoHost/issues#1770]
## Description

I just noticed that if you create a new user with `yunohost user create <username>` and if you allow this user to connect with SSH with a public key then the `.ssh` folder get 777 permission by default causing OpenSSH to refuse the connection with `Authentication refused: bad ownership or modes for directory /home/<username>/.ssh`.

## Steps to reproduce

```
# Create foo user
yunohost user create foo

# Allow SSH for foo
yunohost user ssh allow foo

# Add a pub key for foo
yunohost user ssh add-key foo <the pub key>

# Disable password authentification by editing /etc/ssh/sshd_config and add this:
# Match User test
#     PasswordAuthentication no

# Restart ssh
sudo systemctl restart sshd.service

# Try to SSH with foo account
ssh foo@server
# You can't... and you get a "Authentication refused: bad ownership or modes for directory /home/foo/.ssh" in the log
```

## How to fix?

I guess we need to add a `chmod 700` somewhere in this function

https://github.com/YunoHost/yunohost/blob/6725a7f2bfd4b184bab99ad473db3809d0d76a3f/src/yunohost/ssh.py#L95-L132

**Comment by zamentur** [comment]
Thanks for reporting. Feel free to create a PR
