### ISSUE TITLE
[SSH] YNH user still have SSH access after `ssh disallow`

### ISSUE THREAD

**Issue by sy6sy2** [YunoHost/issues#1771]
I have a YunoHost user with SSH access (follow steps describes here https://github.com/YunoHost/issues/issues/1770).

But after a `sudo yunohost user ssh disallow foo` I notice that foo user can still login with SSH on my server.

**Comment by alexAubin** [comment]
Can you elaborate : do they actually have an interactive shell opening when they log in ?

**Comment by sy6sy2** [comment]
Sorry, now I cannot connect anymore with the user. Maybe it's needed to wait some time for `sudo yunohost user ssh disallow foo` to take effect?

Anyway 😉

**Comment by alexAubin** [comment]
Ah now that you mention it it may have something to do with some caching in nsswitch yeah
