### ISSUE TITLE
Diagnosis - apt is configured to use the backports repository

### ISSUE THREAD

**Issue by HyperCriSiS** [YunoHost/issues#1778]
Hi,

the diagnosis throws an error:
 It looks like apt (the package manager) is configured to use the backports repository. Unless you really know what you are doing, we strongly discourage from installing packages from backports, because it's likely to create unstabilities or conflicts on your system. 

How can I fix this?

Thanks,
Hyper

**Comment by alexAubin** [comment]
You can run `grep -nr backport /etc/apt/sources.list*`

Then run `nano /the/corresponding/file/that/was/found` and comment or remove the corresponding line
