### ISSUE TITLE
add alerting/monitoring capacities for common issues on YunoHost

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#178]
###### Original Redmine Issue: [178](https://dev.yunohost.org/issues/178)

Author Name: **Bram**

---

YunoHost never warn the user about any common problem while it integreate glances which does **on demand** situation analysis.

It would be great if YunoHost warn the users:

* by email
* on the admin interface
* maybe on apps for the admin user if he is logged in

Things to warn about (to be extended):

* when the free disk space is low
* when the free disk space is *very* low
* critical updates need to be done

Ideally, a solution should be proposed to the user each time with a link to the admin interface.

**Comment by alexAubin** [comment]
WIP : https://github.com/YunoHost/yunohost/pull/534

**Comment by decentral1se** [comment]
Have people seen https://docs.netdata.cloud/docs/why-netdata/? It's a dedicated monitoring tool with a web API (https://docs.netdata.cloud/web/api/) and very low resource usage.

I am not so familiar with Yunohost's architecture, so perhaps it does not work to have an external application as a core dependency. But the idea of having a "back-end" for the diagnosis tool that solves existing monitoring requirements could save time.

I don't want to take away energy from the implementation in https://github.com/YunoHost/yunohost/pull/534 but also wanted to show my thoughts on this.

**Comment by alexAubin** [comment]
Closing because this is pretty much fixed by the diagnosis system
