### ISSUE TITLE
Erreur 404 : https://yunohost.org/hardware

### ISSUE THREAD

**Issue by SuShY28** [YunoHost/issues#1781]
Hello,
From the page [https://yunohost.org/#/](https://yunohost.org/#/), in the install section the link to see the prerequisites [https://yunohost.org/hardware](https://yunohost.org/hardware) is broken.

**Comment by Aeris1One** [comment]
La page Index ne peut pas être modifiée par les contributeurs, elle n'est pas disponible dans le repo https://github.com/YunoHost/doc/, c'est dommage j'étais bien parti pour corriger ça :/
