### ISSUE TITLE
4.2: loading app manifest / install view miserably fails if no user is defined and a user is needed

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1782]
Steps to reproduce:
- go to the webadmin
- make sure no user exists yet
- try to install cryptpad
- the javascript will miserably fail while trying to load the manifest because `usersAsChoices` implicity assumes that the list ain't empty / null

Not sure exactly how to handle this, it's a pretty annoying situation ... the real fix being "we should always have at least one user which should also be the admin" ...

**Comment by Axolotle** [comment]
The first user should be created at the postinstall.
I can add it in the web-admin without changes to the core but it should be on both interface.

Or for now we could check on the app install `onQueriesResponse` if users is defined, if there's no users (even for apps that doesn't need to pick one) we do not render the view but display a message, or redirect to a page that display this message if it's needed elsewhere.

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost-admin/commit/40ef5b4c269f9d85a94d1b2d6275292239280bef
