### ISSUE TITLE
Opt-Out of Google's FLoC

### ISSUE THREAD

**Issue by JoshuaRL** [YunoHost/issues#1785]
Many browsers and services are manually opting out of Google's new FLoC, and I believe it would be a good idea to default to opt-out in Yunohost with perhaps the option to disable.

Here is a blog I found that pulls together all the necessary pieces to do so:

https://paramdeo.com/blog/opting-your-website-out-of-googles-floc-network

**Comment by alexAubin** [comment]
Done in upcoming 4.2 https://github.com/YunoHost/yunohost/pull/1211
