### ISSUE TITLE
Bitwarden Install fail - BinaryLane host

### ISSUE THREAD

**Issue by rukacat** [YunoHost/issues#1786]
Hi team

Trying to install Bitwarden and I'm getting an error. Looks like it's failing when it tries to build/install the libsqlite3 package.
Full log: https://gist.github.com/rukacat/6d8c04a49d5a0cdff9c9e4d547904ae5

Debian Buster server
Hosted by BinaryLane
25GB storage, 1GB RAM

**Comment by kay0u** [comment]
Hi!

The error is more related to the [package Bitwarden](https://github.com/YunoHost-Apps/bitwarden_ynh).

But the error is:
> out of memory allocating 800 bytes after a total of 59588608 bytes

(1Go of RAM is not enough for Bitwarden)
