### ISSUE TITLE
Bitwarden

### ISSUE THREAD

**Issue by rBogen** [YunoHost/issues#1788]
Anwendung 'bitwarden' bricht immer wieder bei der Installation mit einer Fehlermeldung ab (Skript-Fehler), hier die Log-Datei: https://paste.yunohost.org/raw/holuyebege
Kann mir jemand helfen, was kann ich tun?

**Comment by alexAubin** [comment]
The script crashes at: 

```
021-04-23 20:48:23,807: WARNING - info: installing component 'rustc'
2021-04-23 20:48:37,215: WARNING - Killed
```

This tends to be symptomatic of lack of resources on the system, typically the system ran out of RAM

**Comment by rBogen** [comment]
![Bildschirmfoto 2021-04-25 um 06 53 03](https://user-images.githubusercontent.com/83093563/115993522-7f752c00-a5d3-11eb-97d9-66406ec2b1f4.png)
Thanks for the answer, the RAM on the Raspberry is of course limited. SWAP has been enlarged from 100 to 1024MB and now there is no longer a problem.
