### ISSUE TITLE
bintray does not provide an apt repository anymore

### ISSUE THREAD

**Issue by kamou** [YunoHost/issues#1792]
> May 1st, 2021 Bintray services will no longer be available. GoCenter, and ChartCenter services will no longer be available to non-Artifactory clients. (ConanCenter and JCenter are not affected).

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

I don't know exactly what for, but seems like yunohost uses bintray. (/etc/apt/sources.list.d/crystal.list)
which makes it impossible to update yunohost from the administration interface (because apt-get update fails)

commenting:

`deb https://dl.bintray.com/crystal/deb all stable`
in /etc/apt/sources.list.d/crystal.list fixes it. But I'm not sure if this is going to break something else.

**Comment by alexAubin** [comment]
Sounds like it's only related to some crystal-based app. I don't think there's many of these apart from invidious ?

**Comment by kamou** [comment]
well probably, I actually did install invidious.

**Comment by kamou** [comment]
it seems like this have already been fixed in the app repo:
https://github.com/YunoHost-Apps/invidious_ynh/commit/8f6274ae5340756f3f7ff1337ffb9c0059fb6e20#diff-6233345de4867c7ccf72bac1fc1067988d2a4c8e1ab9a746956eafccf88cfed2R69

the install script does the following:
`echo "http://download.opensuse.org/repositories/${OBS_PROJECT}/${DISTRO_REPO}/ /" | tee /etc/apt/sources.list.d/crystal.list`

**Comment by zamentur** [comment]
I close cause it's already reported on app issue trackers
https://github.com/YunoHost-Apps/invidious_ynh/issues/30
