### ISSUE TITLE
Can't save user profile form in Yunohost admin...

### ISSUE THREAD

**Issue by jedie** [YunoHost/issues#1796]
The save button on `/yunohost/admin/#/users/<USERENAME>/edit` is always disabled:

![grafik](https://user-images.githubusercontent.com/71315/117998008-c721e480-b343-11eb-911a-842389836767.png)

I see no form errors. And IMHO if the button is disabled by missing/wrong form, if should display these errors...

**Comment by zamentur** [comment]
It's due to quota question is empty.
But you are right it's a bug, quota question should not be empty in edit mode.

**Comment by jedie** [comment]
Is it fixed?!?

**Comment by alexAubin** [comment]
It's about to be released, yes
