### ISSUE TITLE
YunoHost ISO is broken

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1802]
With 4.2, installation with iso failed during installation of yunohost package:

The logs: https://paste.chapril.org/?ae7ee526a3e66cd8#9NMTRCLLMABdSxdrZ12H4GBcz7w9npQfrXUevqxJsUFY

Its due to an error with slapd can't start

**Comment by yalh76** [comment]
As indicated by @zamentur : seems that the part to be rewrite is https://github.com/YunoHost/yunohost/blob/dev/src/yunohost/tools.py#L70

**Comment by zamentur** [comment]
Fixed in 4.2.5.2
