### ISSUE TITLE
The API connection from the server to the software has not been running

### ISSUE THREAD

**Issue by carrabelloy** [YunoHost/issues#1807]
The API connection from the server to the software has not been running properly for a long time. Though, DNS set correctly. Some of the programs are still running. From the application side, not all of them and they remain, as on the next screen.
I hope it's not too much, but I'll pass on my English with a translator and pictures. With the hope that this problem will be solved.
![image](https://user-images.githubusercontent.com/1060591/118928916-25525700-b944-11eb-8303-b811b27352c1.png)
![image](https://user-images.githubusercontent.com/1060591/118928980-38652700-b944-11eb-93fd-e00035a4d8ee.png)
Die Api Verbindung vom Server zur Software läuft nicht mehr sauber schon seit längerem. Obwohl, DNS richtig gesetzt. Ein Teil an Programmen läuft noch einigen. Von Anwendungsseiten her nicht alle und sie bleiben, so wie auf dem nächsten Screen.
Ich hoffe es sind nicht zu viel, doch mein Englisch gebe ich hier noch mal mit Übersetzer und Bildern weiter. Mit der Hoffnung das dieses Problem gelöst wird.
The API connection from the server to the software has not been running properly for a long time. Though, DNS set correctly. Some of the programs are still running. From the application side, not all of them and they remain, as on the next screen.
I hope it's not too much, but I'll pass on my English with a translator and pictures. With the hope that this problem will be solved.
![image](https://user-images.githubusercontent.com/1060591/118929086-5894e600-b944-11eb-9b97-280acbe53a5f.png)

https://github.com/YunoHost/issues/discussions/1806#discussion-3373514

**Comment by tituspijean** [comment]
Possible duplicate of https://github.com/YunoHost/issues/issues/1793. Without the usual, logs, we cannot help you more.
Let's reopen *if* we establish the issue is unrelated.

**Comment by carrabelloy** [comment]
Possible duplicate of #1793. Without the usual, logs, we cannot help you more.
Let's reopen if we establish the issue is unrelated.
Wenn, man das ganze über ein Backup versucht sieht man was passiert im oberen Bild. Glück hat zeigen die sich mal. Als nächstes mastodon . 
Ich habe gedacht, wenn er auf einmal so viel DNS Probleme hat, dass ich das auch nicht hinbekommen habe,das zeigt das hierdurch die bei verschiedenen Horster liegen und hier drei IP-Adressen vorhanden sind, da hier von meinem kleinen Hoster und zwei weiteren Hostern Domains auf meinen Server laufen. Die Abstimmungsprobleme ich bin hergegangen und habe eine neue von den ganzen Domains als Haupt Domain umgeändert. Da ich mir das leisten kann, mehre Haupt und keine Sub-Domain dazu machen oder benenn kann. 
Hatte jetzt geschafft Mastodon zu löschen und wollte das Backup einspielen. Was nicht geht. 
Ich kann auch auf meinem Terminal zugreifen, wenn mir jemand sagen kann was man jetzt gerne auch über Terminal, das es auch bei mir läuft, was eigentlich das Skript von Yunohost versucht hat zu unterbinden. Doch so oft wie ich das ganze hier installiert und wieder hergestellt habe und Arbeit reingesteckt habe wäre es schön bei über 160GB, wenn das System wieder lauffähig wird. Entschuldigt ich arbeite mit übersetzter

> Possible duplicate of #1793. Without the usual, logs, we cannot help you more.
> Let's reopen _if_ we establish the issue is unrelated.
If you try to make a backup you can see what happens in the picture above. Luck shows up. Next, mastodon.
I thought that if he suddenly had so many DNS problems that I couldn't manage that either, that shows that this means that they are with different Horster and that there are three IP addresses here, from my little host and two other hosts Domains run on my server. The coordination problems I went and changed a new one of the whole domains as the main domain. Since I can afford it, I can add or name several main and no sub-domains.
Had now managed to delete Mastodon and wanted to import the backup. What doesn't work.
I can also access my terminal if someone can tell me what I would like to do now via Terminal, that it is also running on me, which the Yunohost script was actually trying to prevent. But as often as I have installed and restored the whole thing and put work into it, it would be nice with over 160GB if the system could run again. Sorry, I work with a translator
