### ISSUE TITLE
Misleading DNS configuration diagnostic for subdomain

### ISSUE THREAD

**Issue by pbernery** [YunoHost/issues#1808]
Hello,

I'm playing with the Diagnostic feature of YunoHost and am trying to fix listed issues.

I believe there are misleading issues though concerning DNS configuration on subdomains.

## CAA record name

For instance, for subdomain1.example.org, YunoHost recommands to have this DNS entry:

```
Type : CAA
Nom : @
Valeur: 128 issue "letsencrypt.org"
```

However, if I am not mistaken, having a `@` name is not possible for a subdomain, I should actually declare 

```
Type : CAA
Nom : subdomain1
Valeur: 128 issue "letsencrypt.org"
```

Am I wrong?

## CAA record for "managed" subdomain

There is another issue: I am letting YunoHost managing most of my domain DNS entries. So, in this case, I believe YunoHost should have this CAA record in its DNS when Letencrypt is enabled on the domain, right?

**Comment by zamentur** [comment]
This bug will be fixed with the new DNS autoconfiguration machanism.
See https://github.com/YunoHost/yunohost/pull/1194

**Comment by alexAubin** [comment]
Closing because 4.3 is more "subdomain-aware"
