### ISSUE TITLE
disk space cleaner "à la" CCleaner

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#181]
###### Original Redmine Issue: [181](https://dev.yunohost.org/issues/181)

Author Name: **Bram**

---

I'm not very convinced by this idea, but someone may be more than me. This sound like a bad design actually.

Idea: provide an admin operation for freeing disk space on "files that can be remove".

Example:

* old logs
* apt-get autoremove
* probably other stuff

**Comment by alexAubin** [comment]
Closing, assuming it's done by `yunohost tools basic-space-cleanup`
