### ISSUE TITLE
Backup issue after 25/5/21 updates

### ISSUE THREAD

**Issue by cat7-no** [YunoHost/issues#1811]
Hi,
The server was kept current on a daily basis.
After applying updates of 25/5/21 (4 Packages for x11 and yunohost) the backup is not working correctly.
Even though all options for system and applications are selected, only two applications (xmpp-data and webmin) are in the backup.
A server reboot doesn't change the the symptoms.
Please advise how to enable the full system backup again
thank you
[update250521.txt](https://github.com/YunoHost/issues/files/6542555/update250521.txt)

**Comment by alexAubin** [comment]
Mokay, that's the log of the upgrade, but can you share the log of the backup

**Comment by cat7-no** [comment]
Thank you for picking up!
here are two log files: the last good one from yesterday and the last failing.
Both where startet in the same way -> full BU of the full system.
[good_bu.txt](https://github.com/YunoHost/issues/files/6542734/good_bu.txt)
[bad_bu.txt](https://github.com/YunoHost/issues/files/6542735/bad_bu.txt)

**Comment by cat7-no** [comment]
good one - sry
[good_bu.txt](https://github.com/YunoHost/issues/files/6542746/good_bu.txt)

**Comment by alexAubin** [comment]
hmokay but the arguments provided to the "bad one" explictly state to only backup the webmin app and the data_xmpp so "of course" only those are going to be backuped ... Are you sure you selected everything (i guess it could be a bug in the webadmin interface)

**Comment by cat7-no** [comment]
Hi,
yes - I'm sure that I have selected all options. I tried several times. Even tried to deselect all and selected all again.
Next ry was to deselect webmin and xmpp-data but keep the rest. Now two other options where picked. (Benutzerdaten and SPFtoolbox )

**Comment by cat7-no** [comment]
scanning the services I found this error message which i never had before. Thre is no option to restart the service
[Error.txt](https://github.com/YunoHost/issues/files/6542914/Error.txt)

**Comment by zamentur** [comment]
Could you send us a screen when you select all apps ?
The checkbox UX is a bit strange in new webadmin

**Comment by cat7-no** [comment]
This is what I selected a few minutes ago. 
Result was the same as before
[yunohost_bu.zip](https://github.com/YunoHost/issues/files/6544607/yunohost_bu.zip)
.

**Comment by cat7-no** [comment]
is there a way to monitor the creation of the yml files in /var/log/yunohost/categories/operation?
cat 20210526-071347-backup_create.yml
args:
  apps:
  - webmin
  description: null
  dry_run: false
  methods: null
  name: null
  output_directory: null
  system:
  - data_xmpp
ended_at: 2021-05-26 07:13:50.406699
error: null
interface: api
operation: backup_create
parent: null
related_to:
- - app
  - webmin
started_at: 2021-05-26 07:13:47.260006
success: true
yunohost_version: 4.2.5.2

**Comment by zamentur** [comment]
Could you tried to made this backup by cli with `yunohost backup create` , like that we could knows if it's a problem inside backup method or in webadmin.

**Comment by cat7-no** [comment]
great - it is working from the cli

**Comment by cat7-no** [comment]
Info: The archive will contain about 1.8GiB of data.
Success! Backup created
name: 20210527-103740
results:
  apps:
    archivist: Success
    droppy: Success
    guacamole: Success
    monitorix: Success
    my_webapp: Success
    nextcloud: Success
    phpldapadmin: Success
    phpmyadmin: Success
    rainloop: Success
    searx: Success
    spftoolbox: Success
    webmin: Success
  system:
    conf_ldap: Success
    conf_manually_modified_files: Success
    conf_ynh_certs: Success
    conf_ynh_settings: Success
    data_home: Success
    data_mail: Success
    data_xmpp: Success
size: 1942365751

**Comment by cat7-no** [comment]
After todays update nothing changed. The full backup started from the GUI contains the same two packeges and skips the majority of selected packages.
[yunohost_update.txt](https://github.com/YunoHost/issues/files/6589773/yunohost_update.txt)

**Comment by alexAubin** [comment]
Should be fixed in recent versions, be sure to force-restart yunohost-api

**Comment by cat7-no** [comment]
thank you for your effort.
It works

4. Juni 2021 22:41, "Alexandre Aubin" ***@***.*** ***@***.******@***.***>)> schrieb:
	Should be fixed in recent versions, be sure to force-restart yunohost-api
