### ISSUE TITLE
Redesign the "MoulinetteLock" to be more permissive (allow read actions)

### ISSUE THREAD

**Issue by Salamandar** [YunoHost/issues#1814]
I'm currently upgrading an app using the command line, so :
* I'm expecting every "write" actions on apps to fail (ok, that's fair)
* I'm expecting to be able to retrieve the app list, versions, permissions and such during the upgrade.

For now, those "read actions" seem locked (see screenshot), and that's not a great user experience. One would expect to retrieve the list of available upgrades and *then* to have a warning/error message when they want to *start* the app upgrades.

The same goes with the app catalog : you can't browse through it while an app is installing. 

Maybe some API endpoints could be referenced as "read only" to provide a more "responsive" UI while browsing the Admin panel.

![image](https://user-images.githubusercontent.com/6552989/119695649-afbc1e80-be4e-11eb-8214-58cb1c38fcc4.png)

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/moulinette/pull/327 though iirc it's not the end of the story, i think the API has a single worker or something...
