### ISSUE TITLE
MIGRATION 20 issue

### ISSUE THREAD

**Issue by Yeltis21** [YunoHost/issues#1815]
Hello everybody i'm facing an issue during the migration : "20. Ajouter la prise en charge des autorisations SSH et SFTP " with this log file : [here](https://paste.yunohost.org/raw/lididoyuwu) thanks in advance boyzs

**Comment by zamentur** [comment]
Could we have info about special char used in user profile ? (domain, firstname, lastname, forward email ...)

**Comment by Yeltis21** [comment]
hello thanks for your reply , in this server there is approximatively 100 users account,  the main domain name is "musicallstudio.online", i don't use emails services at all :)
about which user profil are you talking about ? i am in admin when a try to do the migration :)

**Comment by Yeltis21** [comment]
hello Any update ? any idea i'm still stuck with this migration ....

**Comment by alexAubin** [comment]
Hi Yeltis,

could it be that at least one user among your 100 user has some special char in its username, or in its first/last name.
