### ISSUE TITLE
100% CPU usage by Yunohost during app install

### ISSUE THREAD

**Issue by Jules-Bertholet** [YunoHost/issues#1817]
When installing an app, the `yunohost` Python process uses 100% of a CPU core during the entire install process, even when the `bash` app install script is doing all of the actual work and the Python process should just be waiting around for it to finish.

Running `strace` on the Python process spams the console with the following:
```
wait4(<pid of bash install script process>, 0x7fff71084c6c, WNOHANG, NULL) = 0
```

**Comment by kay0u** [comment]
Possible fix: https://github.com/YunoHost/moulinette/pull/275
