### ISSUE TITLE
Ignoring issues in diagnosis fails

### ISSUE THREAD

**Issue by datanomi** [YunoHost/issues#1818]
I have YunoHost installed both on a local server and a VPS and trying to ignore any issue fails on them both.
This is the error dialog i get:
https://7m.ee/m/k684.png
Both are fresh installs of YunoHost 4.2.5.2
I find this rather annoying since it emails me about it and is only a simple DNS mismatch that i can't fix since it is a issue with Cloudflare.

**Comment by petrukhnov** [comment]
unignore also fails

Error: "400" Bad Request
Action: "PUT" /yunohost/api/diagnosis/unignore
Error message:
category=extra is not a diagnosis category
