### ISSUE TITLE
View system logs (/var/log and maybe other logs) from yunohost command line

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#182]
###### Original Redmine Issue: [182](https://dev.yunohost.org/issues/182)

Author Name: **Bram**

---

It might be a good idea to have a log browser in the admin interface. Right now with the new admin interface (in testing) it is possible to see logs related to an application, but that's not always enough, a way to ensure that the user can read all the needed logs is to make them all available.

**Comment by Psycojoker** [comment]
Probably need some redesign.

**Comment by alexAubin** [comment]
Closing because this ain't really an issue anymore, 99% of the stuff we need in debugging context is available in Tools > Services > the_service
