### ISSUE TITLE
LibrePhotos install error

### ISSUE THREAD

**Issue by mikerjensen** [YunoHost/issues#1820]
Trying to install LIbrePhotos on a new up to date Yunohost running on RPI4, i got:
Could not find a version that satisfies the requirement torch==1.8.0+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
see full error log on:
https://paste.yunohost.org/raw/dicibocavu

**Comment by alexAubin** [comment]
Closing because it's more appropriate to discuss this directly in the app's repository : https://github.com/YunoHost-Apps/librephotos_ynh/issues

Other people already reported the issue here : https://github.com/YunoHost-Apps/librephotos_ynh/issues/6

Apparently the lib ain't available on ARM ...
