### ISSUE TITLE
Be able to reverse the default app action in webadmin

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1829]
When someone set an app as "Derfault app" it's not possible to reverse this change easily. Currently to do that you need to comment the redirect instruction in /etc/ssowat/conf.persistent.json

The suggestion is to add a mechanism in order to have a button "Stop to define this app as default app" in webadmin

**Comment by alexAubin** [comment]
Somewhat related to: https://github.com/YunoHost/issues/issues/125

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost/pull/1406 <3
