### ISSUE TITLE
We should probably add a check that there's a reasonnable quantity of free space (500 MB?) before any app install or upgrade

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1833]
c.f. https://forum.yunohost.org/t/mise-a-jour-nexcloud-using-a-lua-regex-you-should-use-a-pcre-regex/16481/2?u=aleks

**Comment by lelibreauquotidien** [comment]
This problem is resolved in !1266 PR

**Comment by frju365** [comment]
Let's close this one ?
