### ISSUE TITLE
php7.4-fpm : systemctl didn't recognize this service ('NoSuchUnit').

### ISSUE THREAD

**Issue by KvizadSaderah** [YunoHost/issues#1836]
Description
Error: failed to get information for this service, it doesn't exists for systemd
Status
Unknown since over 51 years ago
Start on boot
Unknown
Configuration
Unknown

Error: "500" Internal Server Error

Action: "PUT" /yunohost/api/services/php7.4-fpm/start

Error message:
Could not start the service 'php7.4-fpm'
Recent service logs:-- Logs begin at Thu 2021-07-08 13:16:58 UTC, end at Fri 2021-07-09 06:38:35 UTC. -- -- No entries --

While processing the action the server said:
Could not execute the command 'systemctl start php7.4-fpm'
Failed to get status information via dbus for service php7.4-fpm, systemctl didn't recognize this service ('NoSuchUnit').

logs https://paste.yunohost.org/rorizazeli

**Comment by alexAubin** [comment]
It would be nice to share more context regarding when you started to experience this issue ..

This sounds like you uninstalled some apps which did not properly remove the php7.4-fpm service from yunohost

**Comment by KvizadSaderah** [comment]
Yes, I've install/test/uninstall kinda big amount of apps that provided by yunohost. Then, later, diagnosis found that issue and start sending me emails about it. 

I really don't remember which app deletions cause this issue. 

And as the reinstall of yunohost would be painful, may be you could say way to find and fix it? Or some rtfm?

**Comment by alexAubin** [comment]
Yes the simple fix is to run `yunohost service remove php7.4-fpm`

**Comment by KvizadSaderah** [comment]
Success! Service 'php7.4-fpm' removed

Thank you. We could close this case.
