### ISSUE TITLE
Invalid HTML in yunohost_panel.conf.inc

### ISSUE THREAD

**Issue by Fazarel** [YunoHost/issues#1837]
[validator.w3.org](https://validator.w3.org) says "Error: Stray end tag link."
You should remove the two occurrences of `</link>` in `data/templates/nginx/plain/yunohost_panel.conf.inc`

**Comment by zamentur** [comment]
Fixed https://github.com/YunoHost/yunohost/commit/1c15f644f57df6deb9205d65a437eafd77c40f6e
