### ISSUE TITLE
Diagnosis email ISP port 25 relay pointing to a 404 in doc while a correct url exist

### ISSUE THREAD

**Issue by pp-r** [YunoHost/issues#1841]
### Describe the bug

In the *Detail* of the *email section* of the *Diagnosis* in the *Web Admin*, the link associated with *use a relay mail server* points to this *https://yunohost.org/smtp_relay* which gives a 404 instead of this *https://yunohost.org/en/email_configure_relay*

### Context

- Hardware: Raspberry Pi at home
- YunoHost version : 4.2.6.1 (stable)
- I have access to my server : Through SSH | through the webadmin | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain :
- Using an exotic ssh port and a 64 bits Raspberry Pi OS

### Steps to reproduce

Have an ISP blocking port 25, launch the Diagnosis and go to Email section then Detail and click on the link.

### Expected behavior

The link associated with *use a relay mail server* should pointing https://yunohost.org/en/email_configure_relay
Mind about translation fr/en/...

### Logs

![2021-07-31 17-50-35_diagnosis_email_detail_port25_relay](https://user-images.githubusercontent.com/64266134/127745471-65125ce3-e12b-447f-858d-f2c9913489ce.jpg)

![2021-07-31 17-53-18_diagnosis_email_detail_port25_relay_404](https://user-images.githubusercontent.com/64266134/127745475-4f34d255-ddd1-4f6e-99fd-233833dec27f.jpg)

**Comment by ericgaspar** [comment]
Thanks for reporting!
This PR should fix the issue: https://github.com/YunoHost/yunohost/pull/1277
