### ISSUE TITLE
After deleting default app, yunohost still redirects to old app URI when accessing domain

### ISSUE THREAD

**Issue by Ibrahim-AbouElseoud** [YunoHost/issues#1843]
I had an app installed then removed it via yunohost admin, then installed a new app on root of that domain but when you open the domain it redirects to the old app which was /_matrix which was the default and is now removed so this is trash for the new app. 

I tried deleting the domain then setting it up again in yunohost admin but it still has the same problem.

Till a fix is provided, how can I manually fix this and regain my domain from that default app or how can I reset that forwarding or redirection?

Which file causes this redirection to happen?

**Comment by Ibrahim-AbouElseoud** [comment]
So for those that might be in a similar situation I found out how to manually reset or remove it.

Just do `$ nano  /etc/ssowat/conf.json.persistent`

And delete or change the appropriate entries and that's it.

**Comment by alexAubin** [comment]
Closing because should be fixed in 11.0 now that we refactored the default app mechanism, it doesnt edit conf.json.persistent anymore
