### ISSUE TITLE
Meaningful tab titles for YunoHost Admin

### ISSUE THREAD

**Issue by KamilBaczkowski** [YunoHost/issues#1844]
Right now when doing some admin changes on YunoHost using multiple tabs leads to a lot of guesswork, since all the tabs are named _YunoHost Admin_. Good luck finding the appropriate tab:
![image](https://user-images.githubusercontent.com/41474169/128612051-d23be911-9391-4acc-926d-eedbb3ff24a2.png)
I think that the tab titles should include the name of the page in it like so:
- _Diagnosis - YunoHost Admin_
- _Applications - YunoHost Admin_
- _Gitea - Applications - YunoHost Admin_ (this one could be shortened to just _Gitea - YunoHost Admin_, although this may lead to some ambiguity if an app called _Diagnosis_ would be added, other collisions would also be possible)
- _Certificate - subdomain.example.org - YunoHost Admin_
etc.

I am willing to help out with coding this, I would just need some info about where to start.

**Comment by andretheolauret** [comment]
> Right now when doing some admin changes on YunoHost using multiple tabs leads to a lot of guesswork, since all the tabs are named _YunoHost Admin_. Good luck finding the appropriate tab:
> ![image](https://user-images.githubusercontent.com/41474169/128612051-d23be911-9391-4acc-926d-eedbb3ff24a2.png)
> I think that the tab titles should include the name of the page in it like so:
> 
> * _Diagnosis - YunoHost Admin_
> * _Applications - YunoHost Admin_
> * _Gitea - Applications - YunoHost Admin_ (this one could be shortened to just _Gitea - YunoHost Admin_, although this may lead to some ambiguity if an app called _Diagnosis_ would be added, other collisions would also be possible)
> * _Certificate - subdomain.example.org - YunoHost Admin_
>   etc.
> 
> I am willing to help out with coding this, I would just need some info about where to start.

Hello, I added support of your enhancement in my PR please take a review on and test also. Thanks
