### ISSUE TITLE
YNH Internal Server Error 500 when trying to install adguard_ynh

### ISSUE THREAD

**Issue by brimwats1** [YunoHost/issues#1845]
**/!\ If you have found a security issue, please follow https://yunohost.org/en/security_team**

**How to post a meaningful bug report**
   - *If you were performing an action from the webadmin or the CLI and encountered what you think is a bug, you are on the right place!*
   - *If you are requesting a feature for YunoHost, you are on the right place! You can overlook most of the bug report template below, but be as precise as possible in your description of the feature.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug

*A clear and concise description of what the bug is.*

### Context

Hardware: Dell R720
YunoHost version: Powered by YunoHost 4.2.6.1 (stable).
I have access to my server : SSH, direct access
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : not really. I have a RAID server.

### Steps to reproduce

Try to install https://github.com/YunoHost-Apps/adguard_ynh via "Install custom app"

### Expected behavior
app installs

### Logs
Logs I got:

```
Error message:
Unexpected server error

Traceback

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 484, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 600, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 380, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/moulinette/yunohost/app.py", line 905, in app_install
    args_odict = _parse_args_from_manifest(manifest, "install", args=args_dict)
  File "/usr/lib/moulinette/yunohost/app.py", line 2670, in _parse_args_from_manifest
    return _parse_args_in_yunohost_format(args, action_args)
  File "/usr/lib/moulinette/yunohost/app.py", line 2979, in _parse_args_in_yunohost_format
    parser = ARGUMENTS_TYPE_PARSERS[question.get("type", "string")]()
KeyError: 'ad_user'
```

**Comment by alexAubin** [comment]
Yes, the application is not part of the catalog - or rather is flagged as notworking ... Yunohost should have warned you that it's probably a bad idea to try to install it.
