### ISSUE TITLE
Thoughts on the future of user portal, etc.

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1848]
- Having a 'User portal' button in the webadmin that would allow to easily choose the theme, upload logo, tweaks app tiles
- Being able to tweak a 'description' of the app, and icons?, in addition to just the label
- Being able to heavily customize the html/css/js of the portal, including having a portal for visitors.
- Being able to add a search bar like on https://i.redd.it/gwzm171htu671.png that would allow people to use their yunohost account really as a dashboard / home page
- Being able to display the last X items of an RSS feed ? (c.f. being to display the last news of an association, or ....)

**Comment by SpencerDub** [comment]
I would *love* these changes. The portal as it stands is functional, of course, but I'd really love to see it expanded in these ways.

**Comment by alexAubin** [comment]
Closing because the new bookworm portal address this basically
