### ISSUE TITLE
Custom app hooks handling is buggy, not backuped/restored

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1849]
Custom hooks provided by apps through `hooks/` folders have many issues:
- the folder `hooks/` is not present in `/etc/yunohost/apps/$app/` after installation
- as a consequence, they are not present in backup at all and cannot be restored
- they are not restored either - and even having the proper `hooks/` folder being backuped, the code does not properly handle those

This could trigger a lot of mysterious issues such as : people migrating to another server using the backup/restore, then some post_user_create hooks won't be there

That said, the hooks will re-appear after upgrading the app

**Comment by zamentur** [comment]
Seems the merged pr fixed that
