### ISSUE TITLE
Automatic DNS configuration using registar API

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#185]
One of the biggest hassle for newcomers setting up a server is the complexity of manually
configuring dozens of DNS records on their registrars. While automatic DNS configuration is
handled for our .nohost.me domains, we wish to generalize this to “bought” domains using the
lexicon library which can interface with the API of all major registrars.

- [ ] Clarify how subdomains configuration should be handled (currently YunoHost doesn’t distinguish domain and subdomains)
- [ ] Be able to specify that a domain is only meant to be used for web, mail, xmpp, ...
- [ ] Integrate Lexicon in Yunohost’s domain and DNS configuration manager
- [ ] Integrate the mechanism in the webadmin (postinstall and domain add views)
- [ ] Add some documentation (or even create gifs) that explain users how to get token APIs from the most used registrars.

Feel free to split this ticket in several ticket in nlnet5

**Comment by Psycojoker** [comment]
Lexicon offers a cool abstraction on top of that https://github.com/AnalogJ/lexicon

That's really a worth it feature to have.

**Comment by Olm-e** [comment]
hope it's done someday someday, as imho and practical experience it's one of the main practical roadblock that impeach to deploy easely for small structure that have their domain name and would like to switch to local services ... it's also what could help a local "public writer" that helps other around to get yunohost install base at the next l
please pretty please ^^

[edit] we can probably find some funds in Ǧ1 and/or € if some can help solve this for fair wage ... 
[edit2] automatic IP chek and update (aka dyn dns) is the goal to permit home server hosting with "real" domain names

**Comment by skluthe** [comment]
I would definitely recommend getting this up asap. The only reason I went with cloudron over yunohost is because they use Digital Ocean's API to automatically configure DNS. Makes the experience much better.

**Comment by alexAubin** [comment]
Merged as part of 4.3
