### ISSUE TITLE
Add the new "upstream" infos in the app views of the webadmin

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1850]
There's a new "upstream" block in some app's manifest.json containing links to the upstream's demo, website, code repo, admin doc, etc... but these are only used in the app README's

Those infos should be displayed somewhere in the app views of the webadmin

**Comment by Agwebberley** [comment]
Created pull request: [yunohost-admin#428](https://github.com/YunoHost/yunohost-admin/pull/428)

**Comment by g1smo** [comment]
New PR here: https://github.com/YunoHost/yunohost-admin/pull/458

**Comment by Tagadda** [comment]
Closed by https://github.com/YunoHost/yunohost-admin/pull/486
