### ISSUE TITLE
Internet Cube / Armbian images outdated - Debian repos changed from stable to oldstable

### ISSUE THREAD

**Issue by hidrarga** [YunoHost/issues#1852]
### Describe the bug

When I install the latest release of the Internet Cube image for a Lime2 board, the install process fails at the very first step (System upgrade).

I am aware that this issue is not directly related to Yunohost, but it concerns the git repo https://github.com/YunoHost/arm-images and I'm not sure where I could report this kind of issues.

### Context

- Hardware: Olimex Lime2
- YunoHost version: 4.1.7
- I have access to my server: Through SSH and through direct access via serial cable
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

1. Install the internet cube following the Yunohost documentation (Lime2 board) : https://yunohost.org/fr/install/hardware:internetcube
2. Connect to the cube on the local network
3. Fill in the form and wait a few seconds
4. See following error:
  ```
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://security.debian.org buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'
Command 'DEBIAN_FRONTEND=noninteractive APT_LISTCHANGES_FRONTEND=none LC_ALL=C apt-get -o=Acquire::Retries=3 -o=Dpkg::Use-Pty=0 --quiet --assume-yes update &>> ./data/upgrade.logs' returned non-zero exit status 100.
  ```

I can solve this issue by connecting with SSH to the cube and manually run:
```bash
apt update
```
Then I answer yes to the questions about the repository changes.

Building a recent image of the internet cube solves the issue.

Note that Debian Bullseye was released yesterday, so that's probably what is causing this behaviour. I didn't get this error the yesterday morning.

### Expected behavior

The internet cube install process succeed.

### Logs

```
============================
Running: DEBIAN_FRONTEND=noninteractive APT_LISTCHANGES_FRONTEND=none LC_ALL=C apt-get -o=Acquire::Retries=3 -o=Dpkg::Use-Pty=0 --quiet --assume-yes update
Get:1 http://forge.yunohost.org/debian buster InRelease [18.2 kB]
Get:2 http://security.debian.org buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster InRelease [122 kB]
Get:4 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:5 http://mirrors.dotsrc.org/armbian-apt buster InRelease [18.3 kB]
Get:6 http://forge.yunohost.org/debian buster/stable armhf Packages [5652 B]
Get:7 http://mirrors.dotsrc.org/armbian-apt buster/buster-desktop armhf Packages [28.4 kB]
Get:8 http://mirrors.dotsrc.org/armbian-apt buster/main armhf Packages [162 kB]
Get:9 http://mirrors.dotsrc.org/armbian-apt buster/buster-utils armhf Packages [63.8 kB]
Reading package lists...
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://security.debian.org buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'
Command 'DEBIAN_FRONTEND=noninteractive APT_LISTCHANGES_FRONTEND=none LC_ALL=C apt-get -o=Acquire::Retries=3 -o=Dpkg::Use-Pty=0 --quiet --assume-yes update &>> ./data/upgrade.logs' returned non-zero exit status 100.
```

**Comment by alexAubin** [comment]
>Note that Debian Bullseye was released yesterday, so that's probably what is causing this behaviour. I didn't get this error the yesterday morning.

Yeah I noticed something similar in my dev environment when trying to `yunohost tools update` ... Didn't reproduce on my prod server so I thought it was not a huge deal ...

We should probably research what are options for `apt update` to automatically accept this change

(or maybe rebuilding the image may work, but I'm worried that this may also affect VPS providers etc)

**Comment by hidrarga** [comment]
I might try today as I'm installing some cubes for Neutrinet :)

Maybe this would help :
```
--allow-releaseinfo-change
           Allow the update command to continue downloading data from a repository which changed its information of the release contained in the repository indicating e.g a new major
           release. APT will fail at the update command for such repositories until the change is confirmed to ensure the user is prepared for the change. See also apt-secure(8) for
           details on the concept and configuration.

           Specialist options (--allow-releaseinfo-change-field) exist to allow changes only for certain fields like origin, label, codename, suite, version and defaultpin. See also
           apt_preferences(5). Configuration Item: Acquire::AllowReleaseInfoChange.
```

I found it there : http://kraaima.com/inrelease-changed-its-suite-value-from-testing-to-stable-error/

**Comment by hidrarga** [comment]
Ah, I also see this : https://linux.debian.bugs.dist.narkive.com/N7J51AmY/bug-992225-suite-value-change-for-buster-package-list-causes-apt-get-update-failures

Which basically says to upgrade the apt package.

**Comment by hidrarga** [comment]
I confirm that on a VPS I'm just getting a notice:
```
# apt --version
apt 1.8.2.3 (amd64)
# apt update
...
N: Repository 'http://security.debian.org buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Version' value from '10.9' to '10.10'
N: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'
```
It doesn't prompt anything and the exit code is 0.

**Comment by Treora** [comment]
Same issue here; blocked during installation. It looks like there has been no new Lime2 image since April 2021. Are there any plans for an update? (even if just to fix this, perhaps?)

**Comment by alexAubin** [comment]
@nathanael-h has some pending work in https://github.com/YunoHost/arm-images/pull/14

**Comment by hidrarga** [comment]
Awesome! I'm available for testing lime1 and lime2 images :)

**Comment by alexAubin** [comment]
So meh, the issue has been "fixed" by not advertising the Olinuxino, OrangePiPC+ and RPi 0/1/2 images anymore because they are outdated as hell. Unfortunately until further notice, we don't have time/energy to maintain those builds.

**Comment by hidrarga** [comment]
Hm, I think that's sad, because I've spent a lot of time building and testing a bullseye image for the lime2 board... At Neutrinet, we are going to use these images. I guess that leaves us no choice but to propose images for the lime2 ourselves :/
