### ISSUE TITLE
Add a --purge option to "yunohost app remove", meant for apps to remove data if this option is defined

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1854]
Currently when uninstall applications, user data may remain on the disk because we don't want all data to disappear during tricky situation like remove-after-failed-upgrade, etc.

However, the admin may want to entirely remove any user data or other pieces of data that may otherwise remain.

## Step 1 : add a new `--purge` option to `yunohost app remove`

This happens in the actionsmap around here : https://github.com/YunoHost/yunohost/blob/dev/data/actionsmap/yunohost.yml#L670-L676

 On a live system: this file is located in `/usr/share/moulinette/actionsmap/yunohost.yml`

The syntax to add `--purge` should be similar to what's done for example for the `--force` option for `app upgrade` a few line below)

You can already validate that this is taken into account by running `yunohost app remove --help` : this should display the new `--purge` option

## Step 2 : handle the new `--purge` option in the python code

This happens around here in function `app_remove(...)` : https://github.com/YunoHost/yunohost/blob/dev/src/yunohost/app.py#L1190

On a live system, this file is located in `/usr/lib/moulinette/yunohost/app.py`

The function `app_remove(...)` should handle a new `purge` argument (which should be False by default)

Then, if `purge` is True, a new `YNH_APP_PURGE` variable should be set to 1 or 0 (or True/False) to the `env_dict` (similar to what's done for `YNH_APP_INSTANCE_NAME`)

To validate that this works : one can clone a simple app such as hextris, and add in the remove script a bash block like: 

```bash
if [[ "$YNH_APP_PURGE" == "true ]]
then
     ynh_print_info "Purging user data !"
     ynh_secure_remove /some/file
fi
```

and try to install / remove this modified app with/without `--purge` and notice that the info message "Purging user data" is displayed

## (Bonus, optional) Step 3 - Integrate this new feature in the webadmin

This is a bit trickier because you need to have an actual dev environment to be able to re-build and test the webadmin easily ... and be familiar with html/javascript/vuejs

This happens in : https://github.com/YunoHost/yunohost-admin/blob/dev/app/src/views/app/AppInfo.vue#L285-L295

We probably want to add a checkbox in the confirmation modal like `[ ] Purge all user data` (not checked by default). If the checkbox is checked, we should add `?purge` to the API call, like this: `api.delete('apps/' + app.id + '?purge')`

**Comment by Shadaki** [comment]
@alexAubin Thanks for spending your time making this detailed description!

**Comment by alexAubin** [comment]
(Integrated in the core, still to be integrated in the webadmin at some point ... though not super trivial : as ljf mentionned in PR 1285, for an optimal UX, we need to know if the application actually does something with the purge option)
