### ISSUE TITLE
Support a doc/DESCRIPTION.md in the Auto-README mecanism

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1864]
Nowadays the app READMEs are automatically generated using this script https://github.com/YunoHost/apps/blob/master/tools/README-generator/make_readme.py and this jina template https://github.com/YunoHost/apps/blob/master/tools/README-generator/templates/README.md.j2

As discussed last week, the possibility to properly described the app is limited (only the `description` field from the manifest.json is used). Packagers may want to provide an extensive discussion of the app such as: 

```
Some long and extensive description of what the app is and does, lorem ipsum dolor sit amet, 
consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

Features:
- Ut enim ad minim veniam, quis nostrud exercitation ullamco ;
- Laboris nisi ut aliquip ex ea commodo consequat ;
- Duis aute irure dolor in reprehenderit in voluptate ;
- Velit esse cillum dolore eu fugiat nulla pariatur ;
- Excepteur sint occaecat cupidatat non proident, sunt in culpa."
```

To do this, a mecanism similar to what's done for DISCLAIMER.md shall be used: https://github.com/YunoHost/apps/blob/93da394be6a9871e6e61c225d838bfe8b7a52ed7/tools/README-generator/make_readme.py#L40-L54

And included around here in the jinja template: https://github.com/YunoHost/apps/blob/93da394be6a9871e6e61c225d838bfe8b7a52ed7/tools/README-generator/templates/README.md.j2#L37

**Comment by ericgaspar** [comment]
Is this issue good to close?

**Comment by alexAubin** [comment]
Indeed, cheers ! :+1:
