### ISSUE TITLE
Create a list of VPN providers/offers suitable for self-hosting

### ISSUE THREAD

**Issue by dhuschde** [YunoHost/issues#1866]
Hey, I host my YunoHost installation at home, but have constant issues with Mails and Ports. I wanted to use a VPN, but don't know which one I can use.
Surfshark doesn't have dedicated IPs and NordVPN doesn't allow connections from the outside.
Do they work anyway, or do I need to use another one?

And if not, which one would you recommend?

**Comment by alexAubin** [comment]
We usually recommend getting one from the FFDN using a .cube which is easy to combine with the vpnclient app

But it's currently not straigthforward to find / know the appropriate ISPs inside the FFDN ... and even with the list, may feel scary to reach french associations if you're not french speaking ...

It's not super clear for us either what commercial VPNs are suitable and can easily be used in combination with vpnclient

**Comment by alexAubin** [comment]
(some work is ongoing by ljf)

**Comment by alexAubin** [comment]
Ongoing in https://github.com/YunoHost/doc/pull/1785
