### ISSUE TITLE
The mysql/mariadb conf is outdated as hell

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1868]
Follow-up of https://github.com/YunoHost/yunohost/pull/1284

I'm copypasting the relevant bits: our `my.cnf` didn't get any thoughts since probably the jessie or wheezy era ...

Nowadays on a brand new vanilla debian system, this file contains: 

```
[client-server]

# Import all .cnf files from configuration directory
!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mariadb.conf.d/
```

then pointing to the default confs from mariadb which is probably better and up-to-date with modern practices ...

I'm trying to compare the old (=ours) and new (=default debian) config content but it's not super obvious, it looks like most of the buffer-related key name changed ... I'm seeing stuff about `default-character-set = utf8mb4` in the new conf

Naively I'd think we should just use the new stuff and not even handle this my.cnf from yunohost at all

- turns out that our my.cnf contains some important stuff that we should make sure to keep:
    - using innodb as storage : https://github.com/YunoHost/yunohost/commit/15c59e6d672023c8e3411fb83a08a667e12d8b2e#diff-5770ef80611e3cffb11d539fa517ed6d8de28db4e058a0519c96f3eed8ab4499
    - tweaking max_allowed_packet because ??? https://github.com/YunoHost/yunohost/commit/02105568f8f3daa26f5b2b77b1f1f0e1b3b5b44f#diff-5770ef80611e3cffb11d539fa517ed6d8de28db4e058a0519c96f3eed8ab4499

Also it turns out that in the past, mysql/mariadb were providing some conf examples called `my-small.cnf`, `my-medium.cnf`, `my-huge.cnf`, defining what's the tradeoff between resource available vs. expected usage. 
- our current `my.cnf` corresponds to the small version with some values voluntarily limited to fill on small hardware, we must be careful about this
- but it also means that this can be an explanation for why some mysql-based services (such as nextcloud) may appear slow even on reasonably good hardware...
- maybe it would be worth it to have some global setting or automatic mean of defining those values...
- strangely those `my-small.cnf`, `my-medium.cnf`, `my-huge.cnf` don't exist anymore, which is either a shame (because there's no clear baseline to base ourselves on), or because it's not relevant anymore ... Not clear which one it is ...
    - relevant ticket on mariadb's issue tracker: https://jira.mariadb.org/browse/MDEV-12346 and https://jira.mariadb.org/browse/MDEV-9882
    - according to the team: "the default values are quite decent" ... (but decent for what context?)

**Comment by alexAubin** [comment]
We should probably handle this change during the Buster->Bullseye transition

We will need to update all the mysql DB to use the new encoding

We should also make sure that the resources used are okay on arm boards

**Comment by alexAubin** [comment]
(Partially fixed by https://github.com/YunoHost/yunohost/compare/44c972f2dd65...144126f56a3d but still we should study if there's any tweaking we want to apply on the modern conf + automigrate the charset ideally)

**Comment by biva** [comment]
I'm not sure if it's relevant here, but my experience with Nextcloud is that there's an error message if I don't use the proper characters configuration in the DB:
> MySQL is used as database but does not support 4-byte characters. To be able to handle 4-byte characters (like emojis) without issues in filenames or comments for example it is recommended to enable the 4-byte support in MySQL. [See the doc](https://docs.nextcloud.com/server/22/admin_manual/configuration_database/mysql_4byte_support.html).

As I read here some interrogations about utf8mb4 I just wanted to highlight this.
