### ISSUE TITLE
Automatic node-update cron creates a mess eating up space, it's not clear how to clean it...

### ISSUE THREAD

**Issue by Jibec** [YunoHost/issues#1874]
### Describe the bug

/usr/local/n/versions/node/ is 2.5GB on my server, and root space is limited on my server.

### Context

- Hardware: Old laptop or computer
- YunoHost version: 4.2.8.3 (stable).
- I have access to my server: ssh
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: no
- If upgrading, current YunoHost version: n/a

### Steps to reproduce

```
admin@ynh:~$ sudo du --max-depth=1 -h /usr/local/n/versions/node/
113M	/usr/local/n/versions/node/14.17.4
80M	/usr/local/n/versions/node/10.23.2
113M	/usr/local/n/versions/node/14.17.5
88M	/usr/local/n/versions/node/12.21.0
112M	/usr/local/n/versions/node/14.17.0
88M	/usr/local/n/versions/node/12.20.1
88M	/usr/local/n/versions/node/12.22.4
88M	/usr/local/n/versions/node/12.20.2
88M	/usr/local/n/versions/node/12.22.2
88M	/usr/local/n/versions/node/12.22.5
80M	/usr/local/n/versions/node/10.23.0
80M	/usr/local/n/versions/node/10.24.1
113M	/usr/local/n/versions/node/14.17.2
112M	/usr/local/n/versions/node/14.16.0
80M	/usr/local/n/versions/node/10.24.0
88M	/usr/local/n/versions/node/12.22.6
80M	/usr/local/n/versions/node/10.23.3
112M	/usr/local/n/versions/node/14.16.1
80M	/usr/local/n/versions/node/12.22.3
88M	/usr/local/n/versions/node/12.20.0
113M	/usr/local/n/versions/node/14.17.1
88M	/usr/local/n/versions/node/12.22.1
113M	/usr/local/n/versions/node/14.17.6
80M	/usr/local/n/versions/node/10.23.1
113M	/usr/local/n/versions/node/14.17.3
88M	/usr/local/n/versions/node/12.22.0
112M	/usr/local/n/versions/node/14.15.5
2,5G	/usr/local/n/versions/node/
```

### Expected behavior

* Only the currently used node version, not the whole history of all previously installed versions
* Is there a way to find which packages uses these versions? If I rename the "node" folder and then restart, I assume some services will fail and help me to understand what uses it?
* How can I remove these in a "clean" way?

### Logs

n/a

Thanks for your help!

**Comment by Tagadda** [comment]
Old node versions are not removed at all. I think you can safely remove every version except the last one for each major version (only keep last version from 10.x.x, 12.x.x and 14.x.x).
You can list apps using nodejs with this ~~ugly~~ command : 
```
$ sudo yunohost tools shell --command "from yunohost.app import app_list; print(list(filter(lambda x: x['version'] != None, [{'id': app['id'], 'version': app['settings'].get('nodejs_version')} for app in app_list(full=True)['apps']])))"

[{'id': 'etherpad_mypads', 'version': '14'}, {'id': 'uptime-kuma', 'version': '14'}]
```

Major node versions are updated with a daily cron that run `/opt/node_n/node_update.sh`. This file is created during app installation, by the nodejs helpers.

We may need to search for unused versions after an update and remove them. We'll need to run `ynh_cron_upgrade_node` somehow to deploy the new cron.
We might need to restart services that was running an old version of nodejs before removing it ?

**Comment by tituspijean** [comment]
Additional issue uncovered by @rodinux: it looks like the versions binaries are duplicated both in `/usr/local/n/versions/node` and `/opt/node_n/n/versions/node`.

**Comment by alexAubin** [comment]
>We might need to restart services that was running an old version of nodejs before removing it ?

Yeah that's the hard / boring part of this issue : the cron job installs newer versions of nodejs, but doesn't effectively restart the relevant services (and imho it shouldnt, because you don't want a random service interruption triggered by a cron job ...) but then you don't know which nodejs versions are effectively used, and which are effectively not used ..

**Comment by tituspijean** [comment]
I have just noticed that the `$ynh_npm`/`__YNH_NPM__` paths from the helper use the full NodeJS version, not the symlink to the current major version. This breaks apps in case of cleanup. To be taken into account when we implement automated cleanup.

**Comment by Psycojoker** [comment]
Does the helper add nodejs + its version as a dependency somewhere for each application that uses it :sweat_smile: ? Same for other requirements like that

**Comment by tituspijean** [comment]
Like this?

https://github.com/YunoHost/yunohost/blob/4897f72974fff30b168a40bf55bf917395cca4cc/helpers/nodejs#L144-L145

**Comment by alexAubin** [comment]
Closing because I ended up savagely removing the cron the other day

**Comment by Jibec** [comment]
This helps, node-update will continue its mess at a slower rhythm, thank you
Jean-Baptiste

**Comment by eauchat** [comment]
Thanks all for the contributions to this thread, it's very instructive.
I stumbled upon the issue and was wondering what's a proper way to clean up presently.

Checking two servers (running yunohost 12.1.37), they both have all the following node versions installed:

```
user@host:~$ sudo du --max-depth=1 -h /usr/local/n/versions/node/
113M	/usr/local/n/versions/node/14.18.2
99M	/usr/local/n/versions/node/16.13.1
161M	/usr/local/n/versions/node/18.20.4
170M	/usr/local/n/versions/node/20.19.4
168M	/usr/local/n/versions/node/20.18.1
167M	/usr/local/n/versions/node/20.19.5
161M	/usr/local/n/versions/node/18.20.1
113M	/usr/local/n/versions/node/14.18.1
161M	/usr/local/n/versions/node/18.20.0
168M	/usr/local/n/versions/node/20.18.2
114M	/usr/local/n/versions/node/14.19.0
161M	/usr/local/n/versions/node/18.20.8
80M	/usr/local/n/versions/node/10.24.1
113M	/usr/local/n/versions/node/14.21.3
114M	/usr/local/n/versions/node/14.19.2
80M	/usr/local/n/versions/node/10.23.1
112M	/usr/local/n/versions/node/14.17.0
168M	/usr/local/n/versions/node/20.18.0
104M	/usr/local/n/versions/node/16.17.1
113M	/usr/local/n/versions/node/14.17.4
164M	/usr/local/n/versions/node/18.17.1
80M	/usr/local/n/versions/node/10.24.0
112M	/usr/local/n/versions/node/14.15.5
164M	/usr/local/n/versions/node/18.19.1
113M	/usr/local/n/versions/node/14.17.5
114M	/usr/local/n/versions/node/14.20.1
100M	/usr/local/n/versions/node/16.14.2
105M	/usr/local/n/versions/node/16.18.0
164M	/usr/local/n/versions/node/18.18.0
112M	/usr/local/n/versions/node/14.16.0
114M	/usr/local/n/versions/node/14.19.1
104M	/usr/local/n/versions/node/16.17.0
161M	/usr/local/n/versions/node/18.20.3
101M	/usr/local/n/versions/node/16.15.1
169M	/usr/local/n/versions/node/20.19.2
99M	/usr/local/n/versions/node/16.13.2
104M	/usr/local/n/versions/node/16.20.1
114M	/usr/local/n/versions/node/14.19.3
164M	/usr/local/n/versions/node/18.18.1
112M	/usr/local/n/versions/node/14.15.4
168M	/usr/local/n/versions/node/20.16.0
169M	/usr/local/n/versions/node/20.19.0
170M	/usr/local/n/versions/node/20.19.3
168M	/usr/local/n/versions/node/20.17.0
113M	/usr/local/n/versions/node/14.17.3
104M	/usr/local/n/versions/node/16.19.0
161M	/usr/local/n/versions/node/18.20.2
161M	/usr/local/n/versions/node/18.20.6
113M	/usr/local/n/versions/node/14.17.1
80M	/usr/local/n/versions/node/10.23.3
100M	/usr/local/n/versions/node/16.14.0
113M	/usr/local/n/versions/node/14.17.2
164M	/usr/local/n/versions/node/18.19.0
80M	/usr/local/n/versions/node/10.23.2
113M	/usr/local/n/versions/node/14.18.3
100M	/usr/local/n/versions/node/16.14.1
101M	/usr/local/n/versions/node/16.15.0
101M	/usr/local/n/versions/node/16.16.0
113M	/usr/local/n/versions/node/14.18.0
161M	/usr/local/n/versions/node/18.20.5
161M	/usr/local/n/versions/node/18.20.7
116M	/usr/local/n/versions/node/14.21.1
164M	/usr/local/n/versions/node/18.18.2
104M	/usr/local/n/versions/node/16.20.2
104M	/usr/local/n/versions/node/16.20.0
162M	/usr/local/n/versions/node/18.16.1
167M	/usr/local/n/versions/node/20.19.6
116M	/usr/local/n/versions/node/14.21.2
116M	/usr/local/n/versions/node/14.21.0
114M	/usr/local/n/versions/node/14.20.0
168M	/usr/local/n/versions/node/20.18.3
105M	/usr/local/n/versions/node/16.18.1
164M	/usr/local/n/versions/node/18.17.0
104M	/usr/local/n/versions/node/16.19.1
169M	/usr/local/n/versions/node/20.19.1
112M	/usr/local/n/versions/node/14.15.3
112M	/usr/local/n/versions/node/14.16.1
113M	/usr/local/n/versions/node/14.17.6
9.8G	/usr/local/n/versions/node/

user@host:~$ sudo du --max-depth=1 -h /opt/node_n/n/versions/node
113M	/opt/node_n/n/versions/node/14.18.2
99M	/opt/node_n/n/versions/node/16.13.1
113M	/opt/node_n/n/versions/node/14.18.1
113M	/opt/node_n/n/versions/node/14.21.3
80M	/opt/node_n/n/versions/node/10.23.1
104M	/opt/node_n/n/versions/node/16.17.1
113M	/opt/node_n/n/versions/node/14.17.4
112M	/opt/node_n/n/versions/node/14.15.5
114M	/opt/node_n/n/versions/node/14.20.1
105M	/opt/node_n/n/versions/node/16.18.0
112M	/opt/node_n/n/versions/node/14.16.0
114M	/opt/node_n/n/versions/node/14.19.1
113M	/opt/node_n/n/versions/node/16.20.1
168M	/opt/node_n/n/versions/node/20.16.0
113M	/opt/node_n/n/versions/node/14.17.3
161M	/opt/node_n/n/versions/node/18.20.2
80M	/opt/node_n/n/versions/node/10.23.2
113M	/opt/node_n/n/versions/node/14.18.3
113M	/opt/node_n/n/versions/node/14.18.0
116M	/opt/node_n/n/versions/node/14.21.1
104M	/opt/node_n/n/versions/node/16.20.2
162M	/opt/node_n/n/versions/node/18.16.1
114M	/opt/node_n/n/versions/node/14.20.0
114M	/opt/node_n/n/versions/node/16.19.1
112M	/opt/node_n/n/versions/node/14.15.3
112M	/opt/node_n/n/versions/node/14.16.1
113M	/opt/node_n/n/versions/node/14.17.6
3.1G	/opt/node_n/n/versions/node
```

A bit too much space taken, given that one of the servers currently doesn't even have any nodejs dependent apps.
It seems safe to remove all nodejs versions since they must be useless.
Anyone has a suggestion on the proper way to remove old nodejs on yunohost? Should I simply run `sudo rm -r /opt/node_n/n/versions/node/* && sudo rm -r /usr/local/n/versions/node/*`?

Also from what I understood `/etc/cron.daily/node_update` was supposed to be removed now. But I still have it and it contains the following:
```
#!/bin/bash

/opt/node_n/node_update.sh >> /opt/node_n/node_update.log
```
I guess I should be removing it as well, but I didn't understand why it wasn't. From what I understand [this line](https://github.com/YunoHost/yunohost/blob/cfb43f366ab34907b36cdefce52c5c2056f4dbab/hooks/conf_regen/01-yunohost#L306) is what's supposed to have it removed, though I don't understand how it works.

Well any suggestions on good ways to cleanup are very welcome. :)
