### ISSUE TITLE
Restore default settings

### ISSUE THREAD

**Issue by PxBCPG** [YunoHost/issues#1876]
### Describe the bug

I wanted to restore nginx configuration that I've previously modified (but it's not that good in fact ^^)

### Context

- Hardware: *Virtual Machine*
- YunoHost version: Latest
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...* Everything here
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: modifying nginx configuration

### Steps to reproduce

- change nginx configuration (editing the files directly)
- ..............................

### Expected behavior

The diagnostic told me I've modified the configuration, but how can I restore it ? 

Thank you very much, 
BCPG

**Comment by alexAubin** [comment]
The diagnostic also tells you how to restore it if you click on Details

**Comment by PxBCPG** [comment]
Thank you very much ! 
Didn't see that ^^
