### ISSUE TITLE
Webadmin 4.3 : choices rendered as simple string fields during app install ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1880]
- Go to webadmin, in the app install part
- Open the install form for an app with choices questions, for example Unattended upgrades
- Choices fields are rendered as regular string fields instead of dropdown

**Comment by zamentur** [comment]
Indeed that's because the type is a string and not a select...
https://github.com/YunoHost-Apps/unattended_upgrades_ynh/blob/master/manifest.json#L35

**Comment by zamentur** [comment]
Fixed with https://github.com/YunoHost/yunohost-admin/commit/64ae24facd52a91c492e2a5ca058f43a505a1ff7
