### ISSUE TITLE
Properly document config panel syntax / features

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1886]
c.f. original post in https://github.com/YunoHost/yunohost/pull/987

We should choose how / where to document this

Currently the config_app kind of acts as a documentation also : https://github.com/YunoHost/test_apps/blob/master/config_app_ynh/config_panel.toml

Maybe we should add comment to it and add it to example_ynh and/or add more details in the packaging doc, or something else ¯\\\_(ツ)_/¯

**Comment by zamentur** [comment]
https://github.com/YunoHost/example_ynh/pull/175/files

**Comment by zamentur** [comment]
A doc has been published. it could be improved, and axolotle worked on an automated config panels doc, but i guess we could close this ticket.
https://yunohost.org/en/packaging_config_panels
https://yunohost.org/en/dev/forms
