### ISSUE TITLE
Logging out from app redirect to old main domain

### ISSUE THREAD

**Issue by eauchat** [YunoHost/issues#1887]
### Context

- Hardware: *"old" computer*
- YunoHost version: 4.2.8.3
- I have access to my server: *Through SSH, through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Describe the bug

For some reason, in a server I used to have as main domain: `yunohost.mydomain.tld`, but it was inconvenient for mail and other stuff so I set `mydomain.tld` as new main domain, and I finally removed `yunohost.mydomain.tld`.
Now when I'm in nextcloud and hit the logout button, the page is redirected to `https://yunohost.mydomain.tld/yunohost/sso/?action=logout`, which shows a `Secure Connection Failed` page (yes the domain doesn't respond anymore, it's expectable since I removed it).
It seems that the logging out still worked. But I'm wondering why nextcloud is still redirecting to the old main domain, and if there is something I can do about it to fix the issue, it's not so nice for users to encounter this error page, they wonder what's going on.

I report this here because it seems to me related to yunohost core, but I can report it in nextcloud_ynh, if that seems better.

**Comment by alexAubin** [comment]
Sounds related to this patch : https://github.com/YunoHost-Apps/nextcloud_ynh/blob/testing/sources/patches_last_version/app-00-add-logout_url-conf.patch

Maybe we don't reapply this patch during change_url (can you confirm that you moved your nextcloud from `yuno.domain.tld` to `domain.tld` ?)

I'm having trouble understanding how the patch works though, what domain name it uses

**Comment by eauchat** [comment]
Not so sure to understand what this patch is doing exactly. But maybe the issue is related.
To clarify, the list of domains in the server changed from:
  - yuno.domain.tld <= main domain
  - domain.tld
  - cloud.domain.tld <= nextcloud domain
  - ... some other domains
to:
  - ~~yuno.domain.tld~~ (totally removed)
  - domain.tld <= main domain
  - cloud.domain.tld <= nextcloud domain
  - ... some other domains

Can't garantee 1000% that nextcloud was installed initially in cloud.domain.tld and never moved, because first install was a long time ago. But if my memory doesn't betray me it should never have changed domain.

**Comment by alexAubin** [comment]
(Naively maybe have a look if there's a redirect_url in /etc/ssowat/conf.json.persistent just in case at some point the app was set as default idk)

**Comment by eauchat** [comment]
Just checked `/etc/ssowat/conf.json.persistent`. The section "redirected_urls" contains only one entry about another app using another domain. Nothing mentioning nextcloud or the old main domain.
I also had a look at `/etc/ssowat/conf.json`, there are obviously some references to nextcloud and it's domain, but the old main domain doesn't appear at all. And "redirected_urls" is an empty object.

**Comment by alexAubin** [comment]
Then I guess i'd try to grep for `logout_url` in /var/www/nextcloud, maybe its config file :/

**Comment by eauchat** [comment]
Bingo!
It's in `/var/www/nextcloud/config/config.php`, 'logout_url' is set to the old main domain.
I guess I can correct it manually, but what do I have to reload and how for nextcloud to notice the changes?

**Comment by alexAubin** [comment]
Probably php7.3-fpm

**Comment by eauchat** [comment]
Yay, great, logging out experience increased drastically in the past 15 minutes :)
Thanks for the help and reactivity @alexAubin :)

I guess I can close this issue, but maybe I should open one on nextcloud_ynh which seems to be missing a `change_url` hook, or something like this?

**Comment by alexAubin** [comment]
Yes indeed, probably something to adapt on Nextcloud :+1:
