### ISSUE TITLE
process.check_output() exception output value is bytes and not string

### ISSUE THREAD

**Issue by dbuscher** [YunoHost/issues#1889]
### Describe the bug

When the check_output() function is called in moulinette and the command fails, the output member of the exception is bytes, not a string. If we try to trap the error and log the error cleanly, but assume the output to be a string (which it would be if the exception is not raised) we get a second exception .

This is likely due to a missing "encoding=" parameter in the call to subprocess.check_output(), but there may be similar problems elsewhere in the module.

### Context

- YunoHost version: 4.2.8.3
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: Trying out custom version of firewall.py which causes an exception

### Steps to reproduce

```sh
    sudo yunohost service firewall start
```

### Expected behavior

Reports the error in the logs cleanly.

### Logs

Sep 26 14:02:06 yunohost[2972]: Traceback (most recent call last):
Sep 26 14:02:06 yunohost[2972]:   File "/usr/lib/moulinette/yunohost/firewall.py", line 231, in firewall_reload
Sep 26 14:02:06 yunohost[2972]:     process.check_output("nft list ruleset -n -a")
Sep 26 14:02:06 yunohost[2972]:   File "/usr/lib/python3/dist-packages/moulinette/utils/process.py", line 29, in check_output
Sep 26 14:02:06 yunohost[2972]:     subprocess.check_output(args, stderr=stderr, shell=shell, **kwargs)
Sep 26 14:02:06 yunohost[2972]:   File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
Sep 26 14:02:06 yunohost[2972]:     **kwargs).stdout
Sep 26 14:02:06 yunohost[2972]:   File "/usr/lib/python3.7/subprocess.py", line 487, in run
Sep 26 14:02:06 yunohost[2972]:     output=stdout, stderr=stderr)
Sep 26 14:02:06 yunohost[2972]: subprocess.CalledProcessError: Command 'nft list ruleset -n -a' returned non-zero exit status 1.
Sep 26 14:02:06 yunohost[2972]: During handling of the above exception, another exception occurred:
Sep 26 14:02:06 yunohost[2972]: Traceback (most recent call last):
Sep 26 14:02:06 yunohost[2972]:   File "/usr/bin/yunohost", line 72, in <module>
Sep 26 14:02:06 yunohost[2972]:     parser=parser
Sep 26 14:02:06 yunohost[2972]:   File "/usr/lib/moulinette/yunohost/__init__.py", line 25, in cli
Sep 26 14:02:06 yunohost[2972]:     ret = moulinette.cli(args, output_as=output_as, timeout=timeout, top_parser=parser)
Sep 26 14:02:06 yunohost[2972]:   File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 120, in cli
Sep 26 14:02:06 yunohost[2972]:     args, output_as=output_as, timeout=timeout
Sep 26 14:02:06 yunohost[2972]:   File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 502, in run
Sep 26 14:02:06 yunohost[2972]:     ret = self.actionsmap.process(args, timeout=timeout)
Sep 26 14:02:06 yunohost[2972]:   File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 600, in proc
ess
Sep 26 14:02:06 yunohost[2972]:     return func(**arguments)
Sep 26 14:02:06 yunohost[2972]:   File "/usr/lib/moulinette/yunohost/firewall.py", line 235, in firewall_reload
Sep 26 14:02:06 yunohost[2972]:     prependlines(e.output.rstrip(), "> "),
Sep 26 14:02:06 yunohost[2972]:   File "/usr/lib/python3/dist-packages/moulinette/utils/text.py", line 62, in prependlines
Sep 26 14:02:06 yunohost[2972]:     return "%s%s" % (prepend, prepend.join(lines))
Sep 26 14:02:06 yunohost[2972]: TypeError: sequence item 0: expected str instance, bytes found
Sep 26 14:02:07 systemd[1]: yunohost-firewall.service: Main process exited, code=exited, status=1/FAILURE
Sep 26 14:02:07 systemd[1]: yunohost-firewall.service: Failed with result 'exit-code'.
Sep 26 14:02:07 systemd[1]: Failed to start YunoHost Firewall.

**Comment by alexAubin** [comment]
Should be fixed by https://github.com/YunoHost/yunohost/commit/85e6ddbeae1c2c2f43f2d84cda2faa52e8479917, thanks !
