### ISSUE TITLE
Many dyndns error mails, and resolv.dnsmasq.conf gets modified automatically, due to VPNclient stuff

### ISSUE THREAD

**Issue by eauchat** [YunoHost/issues#1890]
### Describe the bug

I'm currently having two issues on an internet cube, thinking they might be related.

#### The first is that I keep receiving mails with the following subject (like couple of hundreds in the last months):
```
Cron <root@magari> : YunoHost DynDNS update; sleep $((RANDOM%60)); test -e /var/run/moulinette_yunohost.lock || yunohost dyndns update >> /dev/null 
```
The content is not always the same:
```
; Communication with 2001:910:1410::1#53 failed: operation canceled
; Communication with 80.67.172.144#53 failed: operation canceled
Could not update IP address to DynDNS
```
or
```
Failed to resolve A for myInternetCubeDomain.tld
```
or
```
Failed to resolve dyndns.yunohost.org
```

#### The second issue is that the yunohost diagnosis is saying:
```
[WARNING] Configuration file /etc/resolv.dnsmasq.conf appears to have been manually modified
```
I ran `yunohost tools regen-conf dnsmasq --force`, which resolves the issue, but somehow the modification comes back automatically every time I revert it to normal, the default content of `/etc/resolv.dnsmasq.conf` keeps being replaced by:
```
nameserver 89.234.141.66
nameserver 2001:913::8
```

I imagine this may come from an installed app, but I didn't find things that seemed related in the code of installed apps.
Installed apps are `vpnclient_ynh`, `neutrinet_ynh`, `roundcube_ynh`, `borgserver_ynh`.

### Context

- Hardware: internet Cube with VPN
- YunoHost version: 4.2.8.3
- I have access to my server: Through SSH, through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Expected behavior

Not getting dyndns errors.
`/etc/resolv.dnsmasq.conf` content sticking to the yunohost default

**Comment by alexAubin** [comment]
Hmf yeah this is due to vpnclient injecting custom DNS resolvers ... combined with the fact that VPNclient injects iptable rules blocking DNS traffic to other DNS resolvers ... and then for some reason yunohost uses other DNS resolvers for dns resolution ... not sure to understand why 

Maybe the pending VPNclient testing could help with this but I'm not sure, this is always so tricky

**Comment by alexAubin** [comment]
Is this still happening with the new VPNclient version ? :neutral_face:

**Comment by eauchat** [comment]
Just updated (to 2.0.2~ynh9).
Waiting for some days to see how it goes, and I'll keep you updated with the situation.

**Comment by eauchat** [comment]
Seems improved, but can't say for sure yet, because sometimes it would not happen for a while (I'll check again and post updates).
I've received this once since the update, but maybe that's nothing special, maybe just a temporary issue with internet:
```
[Errno 110] Connection timed out
Could not update IP address to DynDNS
```

**Comment by eauchat** [comment]
Ok, well the issue hasn't shown up again, so I guess that's fully resolved :) 👍
