### ISSUE TITLE
remove metronome sec_labels

### ISSUE THREAD

**Issue by klahaha** [YunoHost/issues#1896]
security labels for top secret information? someone use this? can remove?

screenshot gajim: ![e2u](https://user-images.githubusercontent.com/91276599/135427337-54f43f02-2a57-4851-bfe3-8437cde40ef4.png) (fullscreen, with small screen it's big problem for type text)

[line in config](https://github.com/YunoHost/yunohost/blob/b942c26b293ff14969fdd38eef5713ccdbad57b9/data/templates/metronome/metronome.cfg.lua#L54)

**Comment by alexAubin** [comment]
No idea what I'm looking at
