### ISSUE TITLE
Cannot install apps from testing branch from webadmin

### ISSUE THREAD

**Issue by eauchat** [YunoHost/issues#1901]
Not sure if this is a question or an issue.

Investigating an issue of an app not installing from webadmin, I didn't know how to test my changes. I wasn't able neither to pass a local folder in the webadmin, nor did it seem to let me install an app from testing branch of a repo. I was only able to test my changes by merging them to master branch, which is not really ideal if people try to install the app at that moment.

Is this the expected behaviour?
It seem to me that it could be nice that the webadmin let you install an app from testing branch, in case someone prefers to use that branch.

- YunoHost version: 4.2.8.3
- I have access to my server: through SSH, through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

- open the webadmin
- input a custom repository, choosing the url of any app's testing branch (something like: `https://github.com/YunoHost-Apps/someapp_ynh/tree/testing`)
- webadmin doesn't let you proceed, it says: `Url must be a valid Github link to a repository`

**Comment by alexAubin** [comment]
+1, would be nice if that worked, would make testing app PR easier

**Comment by ericgaspar** [comment]
Aslo related #1653

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost-admin/pull/407
