### ISSUE TITLE
Bad documentation in slapd.ldif file

### ISSUE THREAD

**Issue by sebmennetrier** [YunoHost/issues#1902]
### Describe the bug

Bad documentation in slapd config file

### Context

When we want modify slapd config file (/etc/ldap/slapd.ldif), we have this message : 
```
# OpenLDAP server configuration for Yunohost
# ------------------------------------------
#
# Because of the Yunohost's regen-conf mechanism, it is NOT POSSIBLE to
# edit the config database using an LDAP request.
#
# If you wish to edit the config database, you should edit THIS file
# and update the config database based on this file.
#
# Config database customization:
# 1. Edit this file as you want.
# 2. Apply your modifications. For this just run this following command in a shell:
#    $ /usr/share/yunohost/hooks/conf_regen/06-slapd apply_config
```

But the command `/usr/share/yunohost/hooks/conf_regen/06-slapd apply_config` doesn't exist : 
```
hook called with unknown argument `apply_config'
```

### Steps to reproduce

```
/usr/share/yunohost/hooks/conf_regen/06-slapd apply_config
```

### Expected behavior

The documentation should provide the command line that apply the new slapd configuration

**Comment by alexAubin** [comment]
Fixed in https://github.com/YunoHost/yunohost/commit/68c6e58e9cc734a8a488c14c5aa9b56e7e0826f6
