### ISSUE TITLE
4.3: diagnosis share logs error 400

### ISSUE THREAD

**Issue by kay0u** [YunoHost/issues#1909]
### Describe the bug

*When i clic the button "share logs" in the diagnosis i have an error 400*
```
Erreur: "400" Bad Request

Action: "GET" /yunohost/api/diagnosis/show?share&locale=fr

Message d'erreur :
Les catégories suivantes sont inconnues : show
```

### Context

- Hardware: *computer*
- YunoHost version: 4.3.1.5
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: switch to testing

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost-admin/commit/804488abf05db543c2fd6488ce377516652f6974
