### ISSUE TITLE
4.3 : dnsmasq should not have records for .local domains

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#1910]
### Describe the bug

Currently YunoHost populates `dnsmasq`'s records for .local domains. It clashes with v4.3's mDNS feature, since if the YunoHost server is used as DNS server (local resolver, or PiHole, etc.) then it is the public address, not the local one, that is used by the clients.

### Context

- Hardware: any
- YunoHost version: 4.3.1.6
- I have access to my server: ssh
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - Manually edited `/etc/dnsmasq.conf` to allow connections from local network or VPN
- Using, or trying to install package version/branch: beta v4.3.x

### Steps to reproduce

1. Add .local domains
2. Either
   - Manually edit `/etc/dnsmasq.conf` to allow connections from local network or VPN
   - Install PiHole
3. Set the YunoHost server as DNS server
4. .local addresses are ignored and the domains are redirected to the network's public address

### Expected behavior

Do not generate `dnsmasq` records for .local domains.

**Comment by alexAubin** [comment]
(to be confirmed but should be fixed by https://github.com/YunoHost/yunohost/commit/df02f898ee2ee5fe9260d0875e40dc490ec72926 )

**Comment by tituspijean** [comment]
Confirmed! One has to force the regen-conf to delete the now unwanted files.
