### ISSUE TITLE
YunoHost overlay (ynh-overlay-switch) responding inconsistently

### ISSUE THREAD

**Issue by amber-ailuridae** [YunoHost/issues#1912]
### Describe the bug
YunoHost overlay (ynh-overlay-switch) responding inconsistently in Chromium-based browsers. Firefox appears to be unaffected.

### Context
- Hardware: DigitalOcean droplet / 2 GB RAM / 50 GB SSD / Debian
- YunoHost version: 4.2.8.3, just upgraded admin to Debian 4.2.5.1.
- I have access to my server: Through SSH, yunohost-admin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: I added a custom logo to ynh-overlay-switch a long time ago. I have not had problems opening the overlay previously.

### Steps to reproduce
   1. Log into the YunoHost Portal with a Chromium-based browser.
   2. Select any YunoHost app from the YunoHost Portal.
   3. Once the page loads, select the YunoHost overlay button (ynh-overlay-switch).
   4. Note that selecting the button will often not bring up the portal. Selecting it repeatedly will sometimes open the portal after a large delay. Other times, selecting the button will make it disappear completely. Logging in and out seems to bring it back.

### Expected behavior
An authenticated user selecting the overlay switch quickly opens the YunoHost Portal user interface.

### Logs
https://user-images.githubusercontent.com/25494912/138740078-df43959a-bf45-43b1-8888-e7bab2e0af26.MP4

**Comment by alexAubin** [comment]
SSOwat tile/overlay removed in SSOwat/portal rework coming in bookworm
