### ISSUE TITLE
Mail alias for distribution

### ISSUE THREAD

**Issue by sthaydn** [YunoHost/issues#1913]
Hi Yunohost,

I have read some issues for that, but couldn't find an answer to be able to set up an alias which forwards mails to a group of people internally and/or externally.

Is that kind of distribution planned? Or am I not seeing how it is working?

Regards,

Stefan

**Comment by alexAubin** [comment]
This is currently not supported, but if you are comfortable with tinkering, you can have a look at https://github.com/YunoHost/issues/issues/1537
