### ISSUE TITLE
Initial install fails on Debian 10.4 VPS

### ISSUE THREAD

**Issue by SomethingGeneric** [YunoHost/issues#1915]
### Describe the bug

The method described at https://yunohost.org/en/administrate/install/hardware:vps_debian causes the install to fail because for some reason it can't install `redis-server`?

### Context

- Hardware: DigitalOcean Basic $10/mo
- YunoHost version: 4.1.8
- I have access to my server: SSH as root or direct through console (thanks digitalocean!)
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No, brand new droplet

### Steps to reproduce

- `apt update && apt upgrade -y && apt install curl -y`
- `curl https://install.yunohost.org | bash`

### Expected behavior

(installs YunoHost)

### Logs

https://termbin.com/15do

### Note
I don't think this is DigitalOcean specific since I first tried a buster VM on atlantic.net

### Things I've tried
(repeating the `curl` command not included)
- Manually installing `redis-server` before running the script

**Comment by SomethingGeneric** [comment]
(edited because I also had forgot to set a root password 🤦‍♂️ )

**Comment by SomethingGeneric** [comment]
Install also fails on fresh Debian 10.11 install I did in a local VM. It has the same issue with being "unable" to install `redis-server`

**Comment by AlexioTROM** [comment]
The redis-server installation fails when IPv6 is disabled, so first enable IPv6 for your server.

**Comment by DrFlamingoo** [comment]
I run into the same error.

For me, I am installing on the Cubietruch Allwinner A20, for which there is no YunoHost image available.  So when I am installing Debian Buster, and try running the install script, I face the same problem.  The root seems to be dependency problems with `redis-server`, namely that the `yunohost` package has the requirement of `redis-server<=5.0.x` and the repositories only provide a later version.

Is there a reason to restrict `redis-server` to a specific version, or could you relax the requirements here?
Cheers!

**Comment by SomethingGeneric** [comment]
@AlexioTROM don't fully understand why this solved my issue, but it did. Anyway, I'll probably suggest that we check for IPV6 and fail the script if it's not enabled?

**Comment by alexAubin** [comment]
(I'm not sure either to understand either the relation to IPv6 ... imho it got fixed because we released a new version 4.3.2.1 where we fixed the redis conflict version ...)

**Comment by alexAubin** [comment]
@AlexioTROM : fyi we are wondering in https://github.com/YunoHost/install_script/pull/69 why / how you claim that "redis-server installation fails when IPv6 is disabled" ...

**Comment by AlexioTROM** [comment]
Please see https://unix.stackexchange.com/questions/351668/cannot-install-redis-server

>     You should probably alter the redis.conf file to force it to use IPv4 if it supports that mode only and then maybe you could run it without IPv6.
> 
>     nano /etc/redis/redis.conf
> 
>     Simply remove the ::1 IPv6 loopback address from the bind config option:
> 
>     - bind 127.0.0.1 ::1
>     + bind 127.0.0.1
> 
>     Now redis will not try to use the IPv6 network.
> 
>     Try to install again
> 
>     apt install redis-server

**Comment by SomethingGeneric** [comment]
Thanks!
