### ISSUE TITLE
App install auto-completion list could be smarter

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#1916]
### Context

- Hardware: VPS
- YunoHost version: 4.3.2
- I have access to my server: CLI
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

Try to install an app via CLI, first question is usually about selecting the domain. If the list is long enough, then it gets interrupted by `| ... and 1 other available options not shown]`.

In that case, the message explaining that there is one more domain in the list is longer that the hidden domain.

### Expected behavior

Smarter domain list cutoff. 😛 

### Logs

```
$ yunohost app install synapse
Choose the domain where this app should be installed [domain.tld | archive.domain.tld | board.domain.tld | cam.domain.tld | ci.domain.tld | db.domain.tld | dendrite.domain.tld | doc.domain.tld | g.domain.tld | galene.domain.tld | go.domain.
tld | irc.domain.tld | outline.domain.tld | pad.domain.tld | photo.domain.tld | photonix.domain.tld | photos.domain.tld
| synapse.domain.tld | wg.domain.tld | ynh.domain.tld | ... and 1 other available options not shown]:
```

Not shown option is `vps.local`.

**Comment by alexAubin** [comment]
I mean yeah mhf #wontfix
