### ISSUE TITLE
found wrong href

### ISSUE THREAD

**Issue by dhuschde** [YunoHost/issues#1917]
On that Screen:
![grafik](https://user-images.githubusercontent.com/85834680/140619694-9cb265d2-291b-4bf2-b70c-72cbf5dac48e.png)
The Domain to the Thread is:
// forum.yunohost.org/t/nohost-domain-recovery-suppression-de-domaine-en- entfernen nohost-me-noho-st-et-ynh-fr / 442 
But should be
https://forum.yunohost.org/t/nohost-domain-recovery-suppression-de-domaine-en-nohost-me-noho-st-et-ynh-fr/442

Only tested on German Layout

**Comment by Tagadda** [comment]
This was an error in the translation file. I fixed it [on Weblate](https://translate.yunohost.org/translate/yunohost/admin/de/?offset=1&q=+domain_add_dyndns_forbidden&sort_by=-priority%2Cposition&checksum=).
