### ISSUE TITLE
No working ipv4

### ISSUE THREAD

**Issue by dhuschde** [YunoHost/issues#1919]
Hey,
after removing Adguardhome and installing pi-hole, my server doesn't have a working ip4 anymore.
I can't get external and internal ip4, tried to ping my Routers IP with no success. But I can ping the internal ip4 address from my Server.

Because of that, it also went offline, but now back online...
https://stats.uptimerobot.com/3rD5JfXJZv/789052159

I don't know where to get logs...

**Comment by alexAubin** [comment]
Closing because dunno what we can do to help with no additional details ...
