### ISSUE TITLE
Yunohost log should not be readable except for root

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#192]
###### Original Redmine Issue: [192](https://dev.yunohost.org/issues/192)

Author Name: **mbugeia**

---

All log on /var/log/yunohost are readable by all users and they leak a lot of informations (like db password).

**Comment by Psycojoker** [comment]
We have a migration framework for that now.

**Comment by decentral1se** [comment]
Following https://github.com/YunoHost/issues/issues/1363, I've just made sure that the logs in /var/log/yunohost are not readable by non-root users and that is the case. So, I am not sure of the status of this ticket but I can confirm that the original report is not the case as of Yunohost 3.5.2.2.

**Comment by alexAubin** [comment]
Yes, also checked on an old instance from aroud 2.2 or 2.4, and this is not the case anymore ... So closing it
