### ISSUE TITLE
4.3 : access to apps on a different domain than portail is broken ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1922]
c.f. for example https://forum.yunohost.org/t/erreur-de-redirection-apres-maj-4-3-2/17745

Probably related to https://github.com/YunoHost/ssowat/pull/193

**Comment by alexAubin** [comment]
Might be fixed by https://github.com/YunoHost/SSOwat/pull/197 assuming the issue was related to domains containing special chars

**Comment by kay0u** [comment]
Should be fixed by: https://github.com/YunoHost/SSOwat/commit/981960fb50465dd43762a4fc767bea51dcbcfd7e

**Comment by Webcretaire** [comment]
Added your patch to my SSOwat manually and it seems to fix the problem described in the forum discussion perfectly, thanks a lot kay0u :)
