### ISSUE TITLE
Accents in user data fields crash the webadmin

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#1925]
YunoHost v4.3
Any server, any architecture.

cf. https://forum.yunohost.org/t/webadmin-error-500-while-creating-new-user-with-accents-in-name/17792

Accents, or special characters in user data fields (first, last name, and password) make the webadmin return an error 500. No issue via CLI.

**Comment by alexAubin** [comment]
Funnily enough that's also what's causing the infamous "Missing credential parameter" issue : 

https://forum.yunohost.org/t/logging-in-via-api-not-working-anymore-after-update-missing-credentials-parameter/17826/6

The credentials parameter **is** sent, but for some reason `request.POST.credentials` is empty anyway in https://github.com/YunoHost/moulinette/blob/dev/moulinette/interfaces/api.py#L396

**Comment by alexAubin** [comment]
Turns out these were too separate issues, should be fixed by https://github.com/YunoHost/moulinette/compare/fc4b31bdead9...c5700f1ba301
