### ISSUE TITLE
CI intermittently failing with `user block limit reached`

### ISSUE THREAD

**Issue by weex** [YunoHost/issues#1926]
(Feel free to edit this bug directly if anything is incorrect)

### Describe the bug

Dev?/App? CI is intermittently failing with error `user block limit reached`

### Context

Infrastructure for YunoHost

### Steps to reproduce

Automatically happens during CI runs

### Expected behavior

CI passes or fails solely based on the merit of the package without intermittency.

### Logs

Ghost: https://ci-apps-dev.yunohost.org/ci/job/3752
Ecko: https://ci-apps-dev.yunohost.org/ci/job/3778

**Comment by tituspijean** [comment]
I have looked into the CI server, and found:

```
# /etc/fstab
PARTUUID=XXX / ext4 rw,relatime,usrjquota=aquota.user,jqfmt=vfsv0 0 1
```

```
# repquota -s /
*** Report for user quotas on device /dev/vda1
Block grace time: 7days; Inode grace time: 7days
                        Space limits                File limits
User            used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
root      --  11610M      0K      0K           279k     0     0
www-data  --   9120K      0K      0K           1110     0     0
...
yunorunner --   2003M      0K      0K          29179     0     0
...
```

Quotas are not set for `yunorunner` though... Disabling them with `quotaoff /`.
I have restarted https://ci-apps-dev.yunohost.org/ci/job/3796, let's wait for it to run. 🤞

**Comment by tituspijean** [comment]
OK, looks like it's solved. @YunoHost/infra I do not know how important these quota were. I'll let you fine-tune them and re-enable them if needed.

**Comment by tituspijean** [comment]
Solved last tuesday. For reference:

1. LXD container file system is a `dir` in the host system. If the container sets ownership to a user id, same id is seen by the host.
2. In Debian 4.3, app user id starts at 997 (going down), which clashed with the quotas set in the host system, hence the error.

Solution was to completely disable the quotas in the CI host system.
