### ISSUE TITLE
The CSRF tokens do not match.

### ISSUE THREAD

**Issue by PxBCPG** [YunoHost/issues#1929]
### Describe the bug

Can't access to some of the services because "The CSRF tokens do not match." 

### Context

- Hardware: *Home server*
- YunoHost version: latest
- I have access to my server: *ssh/webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Logs

Console logs with a lot of 400 errors with all the browsers.

**Comment by alexAubin** [comment]
Uh wokay, can you elaborate what you mean by "some of the services" ? Do you mean the webadmin ? Or a specific app in the user portal ? Are you using a specific browser with some specific tweakings ?

**Comment by PxBCPG** [comment]
> can you elaborate what you mean by "some of the services" ?

Especially pgadmin, where everything is broken
> Do you mean the webadmin ? 

No, the webadmin is surprisingly working
> Or a specific app in the user portal ?

pgadmin
> Are you using a specific browser with some specific tweakings ?

No, I tried with several different browsers

**Comment by alexAubin** [comment]
Closing because it's unclear, looks like a pgadmin issue, not a yunohost issue
