### ISSUE TITLE
Content Security Policy renders error to web browsers

### ISSUE THREAD

**Issue by PxBCPG** [YunoHost/issues#1930]
### Describe the bug

With the default nginx configuration, I got this error in the console : `The Content Security Policy 'default-src https: data: blob: ; object-src https: data: 'unsafe-inline'; style-src https: data: 'unsafe-inline' ; script-src https: data: 'unsafe-inline' 'unsafe-eval'' was delivered in report-only mode, but does not specify a 'report-uri'; the policy will have no effect. Please either add a 'report-uri' directive, or deliver the policy via the 'Content-Security-Policy' header.` for the yunohost.local and some other of my services on safari.
On chromium, I got `Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.`
And on firefox, I got: `Content Security Policy: This site has a Report-Only policy without a report URI. CSP will not block and cannot report violations of this policy.`

**Comment by alexAubin** [comment]
This got fixed at some point, we removed the CSP-report-only entirely
