### ISSUE TITLE
YunoHost app repo URL validation disallows a tilde in repo URL

### ISSUE THREAD

**Issue by michalrudowicz** [YunoHost/issues#1931]
### Describe the bug

When trying to install a custom application for development purposes an URL containing a tilde is not accepted. That breaks, for example, SourceHut's git repos.

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 4.3.3
- I have access to my server: Through SSH + through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: https://git.sr.ht/~michalr/convos_ynh (package itself is probably not working - it's my first package - but it doesn't even go to the git pull stage)

### Steps to reproduce

- via SSH: `yunohost app install https://git.sr.ht/~michalr/convos_ynh`
- In the web admin:
   1. Go to `Install custom app` in Catalog/Applications
   2. Enter an URL containing a tilde, eg. `https://git.sr.ht/~michalr/convos_ynh`
   3. Press "Install"
   4. URL entry field is highlighted in red and the error message "YunoHost app repository URLs are expected to look like https://domain.tld/path/to/repo_ynh" appears.

### Expected behavior

URL with a tilde inside should be accepted.

**Comment by alexAubin** [comment]
(Fixed by https://github.com/YunoHost/yunohost/pull/1382 and https://github.com/YunoHost/yunohost-admin/commit/99ffd7ca720360f29b01cbbcd90a580fa0cdb7e2 )
