### ISSUE TITLE
How to allow iFrames

### ISSUE THREAD

**Issue by dhuschde** [YunoHost/issues#1932]
Hey, I wanted to include an YunoHost App in my Nextcloud installation, but I only get this message:
![grafik](https://user-images.githubusercontent.com/85834680/143438160-0b010779-6bfe-4745-947a-80b5d4b4f7e4.png)
"Server doesn't allow iFrames"

How can I fix that?

**Comment by alexAubin** [comment]
Tweaking X-Frame-Options in nginx conf: https://github.com/YunoHost/yunohost/blob/dev/conf/nginx/security.conf.inc#L37
