### ISSUE TITLE
E-Mail, SMTP, no authentication

### ISSUE THREAD

**Issue by sthaydn** [YunoHost/issues#1934]
Hi everyone,

I am not sure if this is the right place, but I'll try. I am using my yunohost smtp without authentication on some other servers, like sending mails from an external friendica instance. So I have thought that everybody could use my smtp to send mails around when knowing only smtp.domain.com:587.

What are the security measures to prevent other people to use one's smtp for spam or ad mails without breaking yunohost?

Regards,

Stefan

**Comment by alexAubin** [comment]
Eh, i'm not sure to understand : the security measure is precisely supposed to be authentication ...

Are you meaning that you are surprised to be able to send email from other servers *via* your yunohost without any authentication ? If that's the case, can you elaborate how you're achieving this exactly ?

**Comment by sthaydn** [comment]
Thanks for your reply.

I have a nextcloud server outside yunohost, let's say Yunohost server with mail is domain.com and Nextcloud is another VPS with next.domain.com. On next.domain.com I configure smtp like this:
smtp
starttls
sender: noreply@domain.com
no authentication
address: domain.com:587

Mails are sent perfectly. So I started to wonder what if someone else uses those settings.

**Comment by alexAubin** [comment]
And you confirm that mails are indeed correctly sent ?

Could it be that the nextcloud server is on the same local network that the yunohost maybe ?

**Comment by sthaydn** [comment]
Yes, the mails are sent to my inbox. I do have two different yunohosts. Y1 has domain.com, Y2 has domain.net. Y1 is a cloudserver (lets say IP 11.11.11.11, Y2 is another one with another IP, 22.22.22.22 for example. I do have two Nextclouds which run at home, external IP is 33.33.33.33 for both, a reverse proxy is routing them, cloud.domain.com has SMTP settings for Y1, cloud.domain.net has SMTP settings for Y2. Both are sending mails to an account on Y1 or Y2.

**Comment by sthaydn** [comment]
I began to investigate, as I wasn't able to write an email to a hotmail address anymore. It worked great a month ago, some days ago I got a message that IP of Y1 has been blocked and I should contact my ISP. It could be a coincidence that maybe an IP near mine does some SPAM or Adcrap (so hotmail has blocked a whole range), but then I discovered that my SMTP seems to send mails without authentication.

**Comment by sthaydn** [comment]
I just tried it with a wordpress install. It is also possible to send mails without authentication.

**Comment by sthaydn** [comment]
I did another test. When using smtp from Y1, but wanting to send to Y2, this gives me an error:
Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients "

So it seems everything runs as expected. SMTP without authentication works domain internally, but if the receiver is on another domain, I need to authenticate the SMTP.

**Comment by sthaydn** [comment]
This means, if I want to use the Yunohost SMTP to send Mails to people outside of Yunohost (EDIT: and the smtp is also externally), I need to have a "sender account", if I don't want to use my main account. So, problem solved, I guess.

**Comment by alexAubin** [comment]
Uh okay that's a bit subtle indeed :P But good to know ! Thanks for all the investigation
