### ISSUE TITLE
Can't install via script on RPI4 with RPI OS Debian 11.1

### ISSUE THREAD

**Issue by Happyclem** [YunoHost/issues#1943]
### Describe the bug

After a clean install of RPI OS on my RPI4, I tried to launch the script installation but got a error message
Flash image used :
Raspberry Pi OS lite
Release date: October 30th 2021
Kernel version: 5.10

### Context

- Hardware: *Raspberry Pi 4 8GO*
- YunoHost version: 3.4.2 stable
- I have access to my server: *Through SSH **NO** | through the webadmin **NO** | direct access via keyboard / screen **NO |
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

   1. Flash Raspberry pi OS-lite on Raspberry Pi 4
   2. Check if curl is installed
   3. apt upgrade | apt update
   4. Type and launch the script install script from Yunohost
   5. *See logs*

### Expected behavior

Yunohost should install

### Logs
From the console
- [FAIL] Yunohost is only available for the version 10 (Buster) of Debian, you are using '11.1'.

**Comment by tituspijean** [comment]
YunoHost is not released yet for Debian 11.

https://forum.yunohost.org/t/alpha-stage-testing-for-yunohost-11-0-on-debian-bullseye-and-migration-that-will-be-shipped-in-yunohost-4-4-x/18014/13

https://forum.yunohost.org/t/debian-bullseye-has-been-released-yunohost-is-not-yet-compatible/16858/4

Use a Debian 10 image then our install script, or an image provided by YunoHost, then upgrade.

**Comment by Happyclem** [comment]
Sure did and it worked, thanks !
