### ISSUE TITLE
Only display the configuration DNS button in the top parent settings.

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost/issues#1945]
In the webadmin under `domain` settings, the `Configuration DNS` button is displayed in all the sub-domain setting pages but works effectively only in the top parent domain setting page.

The `Configuration DNS` button in the sub-domain setting pages output a warning : `La fonctionnalité d'enregistrement DNS automatique est gérée dans le domaine parent`
Do we need to display this button for all the sub-domain settings?

**Comment by Aeris1One** [comment]
When not using automated DNS thing, the `Configuration DNS` button displays recommended config, unsure if it is relevant to show it on subdomain page though

**Comment by ericgaspar** [comment]
ah yes, I haven't thought about non automated DNS settings...

**Comment by alexAubin** [comment]
Closing because that's probably indirectly fixed in the domain views refactoring of 11.1
