### ISSUE TITLE
Firewall not reloaded when regen-conf ssh after changing port

### ISSUE THREAD

**Issue by Gredin67** [YunoHost/issues#1946]
### Context

- Hardware: *Old laptop or computer*
- YunoHost version: 4.3.4.2 
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### To reproduce
ssh conf previously not handled by Yunohost.
`sudo yunohost settings set security.ssh.port -v 2222`
`sudo yunohost tools regen-conf ssh --dry-run --with-diff`

Trying to connect from another CLI on 2222 the connection timed out.
I had to run
`sudo yunohost firewall reload`
from the already connected CLI to be able to connect.

**Comment by kay0u** [comment]
The `--dry-run` option makes the regen-conf do nothing, you know that, right? (however I don't have any server to try to reproduce the issue right now)

**Comment by tituspijean** [comment]
[Per this](https://github.com/YunoHost/yunohost/blob/720ccf52a6f616e70b6f6be9bf4ce5e4d75f4360/src/yunohost/settings.py#L428-L432), SSH configuration is directly followed by Fail2ban and Firewall regen. `sudo yunohost settings set security.ssh.port -v 2222` should be enough to update all configuration files and reload all services.

I did that last weekend on a VPS, and it worked out of the box.

> ssh conf previously not handled by Yunohost.

What do you mean by that?

---

Edit. I think I get it, but you should have shown the outputs of the commands.

```
# yunohost settings set security.ssh.port -v 22
Warning: The configuration file '/etc/ssh/sshd_config' has been manually modified and will not be updated
Success! Configuration updated for 'fail2ban'
Success! Firewall reloaded
```

```
# sudo yunohost tools regen-conf ssh --dry-run --with-diff
Warning: The configuration file '/etc/ssh/sshd_config' has been manually modified and will not be updated
ssh:
  applied:
  pending:
    /etc/ssh/sshd_config:
      diff: @@ -1,8 +1,8 @@
 # This configuration has been automatically generated
 # by YunoHost
-###
+
 Protocol 2
-Port XXXX
+Port 22

 ListenAddress ::
 ListenAddress 0.0.0.0
@@ -103,4 +103,4 @@
 # If the server is a VPS, it's expected that the owner of the
 # server has access to a web console through which to log in.
 Match Address 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,169.254.0.0/16,fe80::/10,fd00::/8
-    PermitRootLogin yes
+    PermitRootLogin yes
      status: modified
```

The SSH conf file was thus not updated, so the subsquent Fail2ban and firewall reload did nothing. To fix:

```
# sudo yunohost tools regen-conf ssh -f
Success! Configuration updated for 'ssh'
ssh:
  applied:
    /etc/ssh/sshd_config:
      status: force-updated
  pending:
```
Then you need to manually reload the firewall, be cause this regen conf does not do it for you.
`yunohost firewall reload`

Then it works.

--- 

My conclusion: the bug is that the command should fail if the ssh conf is not regen'd for whatever reason.

**Comment by zamentur** [comment]
In fact i think he did (i was in call conf with him, when he did):
```
sudo yunohost settings set security.ssh.port -v 2222
sudo yunohost tools regen-conf ssh --dry-run --with-diff
sudo yunohost tools regen-conf ssh --force
```
Trying to connect from another CLI on 2222 the connection timed out.
He had to run
```
sudo yunohost firewall reload
```

I think the firewall open the port specified in /etc/ssh/sshd_config and not the port designed by the setting: security.ssh.port

So to fix that we should check the firewall.py to see if we should open the port in the ssh config and the port in security.ssh.port.
Or we can add yunohost firewall reload at the end of the regen conf hook (and not only at the end of the settings command...)

**Comment by tituspijean** [comment]
> I think the firewall open the port specified in /etc/ssh/sshd_config and not the port designed by the setting: security.ssh.port
> So to fix that we should check the firewall.py to see if we should open the port in the ssh config and the port in security.ssh.port.

https://github.com/YunoHost/yunohost/blob/720ccf52a6f616e70b6f6be9bf4ce5e4d75f4360/src/yunohost/firewall.py#L229-L231

So yes, `_get_ssh_port` parses `/etc/ssh/sshd_config`, so if it was not updated by the settings command, it is not updated here neither.

What did the `--dry-run --with-diff` return?

**Comment by alexAubin** [comment]
Closing because no feedback for a year ... to me it sounds like the conf was manually modified and therefore not updated by the regenconf, as explained by Titus ...
