### ISSUE TITLE
Error deleting COPS application (but probably not related to the app)

### ISSUE THREAD

**Issue by jacen05** [YunoHost/issues#1950]
### Describe the bug

Error when trying to delete an app (COPS). The app was installed a long time ago and is no longer listed in the application list.

### Context

- Hardware: Not relevant
- YunoHost version: 4.3.4.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *?*
  - If yes, please explain: long-time user of Yunohost, probably some broken things through upgrades...
- Using, or trying to remove package version/branch: cops (stable)

### To reproduce

- *If you performed a command from the CLI, the command itself is enough.*
    ```sh
    yunohost --debug app remove cops
    ```

### Expected behavior

The application is removed

### Logs

Output:

```sh
485  DEBUG initializing base actions map parser for cli
491  DEBUG loading actions map namespace 'yunohost'
502  DEBUG building parser...
577  DEBUG building parser took 0.075s
581  DEBUG acquiring lock...
630  DEBUG lock has been acquired
682  DEBUG loading python module yunohost.app took 0.052s
683  DEBUG processing action [536.1]: yunohost.app.remove with args={'app': 'cops', 'purge': False}
784  INFO Suppression de cops...
1045 INFO L'opération 'Enlever l'application 'cops'' a échoué ! Pour obtenir de l'aide, merci de partager le journal de l'opération en utilisant la commande 'yunohost log share 20211220-224409-app_remove-cops'
1075 DEBUG action [536.1] executed in 0.391s
1076 DEBUG lock has been released
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 72, in <module>
    parser=parser
  File "/usr/lib/moulinette/yunohost/__init__.py", line 25, in cli
    ret = moulinette.cli(args, output_as=output_as, timeout=timeout, top_parser=parser)
  File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 131, in cli
    args, output_as=output_as, timeout=timeout
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 496, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 597, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 419, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/moulinette/yunohost/app.py", line 1031, in app_remove
    manifest = _get_manifest_of_app(app_setting_path)
  File "/usr/lib/moulinette/yunohost/app.py", line 1941, in _get_manifest_of_app
    manifest["arguments"] = _set_default_ask_questions(manifest.get("arguments", {}))
  File "/usr/lib/moulinette/yunohost/app.py", line 2000, in _set_default_ask_questions
    del arg["domain"]
KeyError: 'domain'
```

### Solution

Looking at the error message, I had a look at file `/usr/lib/moulinette/yunohost/app.py`.
The problem seems to be around line 2000:

```python
# Also it in fact doesn't make sense for any of those questions to have an example value nor a default value...
if arg.get("type") in ["domain", "user", "password"]:
                if "example" in arg:
                    del arg["example"]
                if "default" in arg:
                    del arg["domain"]
```

Replacing arg["domain"] with arg["default"] did the trick (uninstallation success)

So I wonder :
- If the correction was indeed the good one
- Why anyone else hasn't encountered this problem? (the source code line is still the same in the master)

**Comment by tituspijean** [comment]
Nice catch! COPS fell right into that bug because it has a `domain` type question, but only one `example` and no `default` for that question. (cf. https://github.com/YunoHost-Apps/cops_ynh/blob/ac499026a7d2cb57bf2a1bc414a6bcab170ad6ed/manifest.json)

When it processes the `password` type question, due to the typo in the code it tries to delete the non-existent `default` key from the `domain` question. Hence the error.

It may well be the first time we encounter the issue because packaging standards were to always add both `default` and `example` keys. Somehow COPS had no `default`.

**Comment by tituspijean** [comment]
If you are fluent enough in Git, you are welcome to contribute to the code and open a PR to fix the bug. 😉 I can do it for you otherwise.

**Comment by jacen05** [comment]
Quicker than me! Yes I could have done a pull request, but I was not sure in the first place if the bug was really what you described or a misconfiguration on my side.
