### ISSUE TITLE
SSO cross domain authentication fail

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1952]
### Describe the bug

The cross domain (or subdomain) seems to fails with at least several apps (like nextcloud or wordpress).

### Context

- Hardware:VPS & x86_64 machine at home
- YunoHost version: 4.3.x

### To reproduce

See here for an example:https://forum.yunohost.org/t/authentification-ldap-ne-fonctionne-pas/18232/6?u=ljf

### Expected behavior

When we click on a tile in sso we should be logged directly (and not have to relogin on the app).

### Logs

SSOwat need to be set in debug mode to get info.

**Comment by alexAubin** [comment]
Too many duplicates of this issue and we're dropping cross-domain auth with the SSO/portal rework in bookworm
