### ISSUE TITLE
Impossible de connecter Talk_Android à un Nextcloud sous yunohost

### ISSUE THREAD

**Issue by fredjoz** [YunoHost/issues#1953]
### Describe the bug

Bonjour,
Je rencontre un soucis lors de du paramétrage de l'application Talk pour Android (F-Droid):
Lorsque je donne l'adresse d'un serveur nextcloud seul (sans yunohost), l'appli fonctionne et se connecte à Talk.
Lorsque je donne l'adresse d'un nextcloud installé avec Yunohost (SSO ...) l'appli retourne cette erreur :
*Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false'....*

J'ai essayé avec plusieurs smartphones de plusieurs utilisateurs sur le nextcloud avec yunohost : même message d'erreur.

### Context

- Hardware serveur : Other ARM board : odroid N2+ avec armbian + Yunohost (script install)
- Hardware smartphone : Fairphone, Samsung, ....
- YunoHost version: stable 4.3.4.2   SSOwat : sable 4.3.2.2
- I have access to my server: Through SSH : yes | through the webadmin : yes 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Nextcloud version : 22.2.3
- Talk pour Android version : 13.0.0

### Steps to reproduce
Avec un smartphone Android, installation de Talk depuis F-Droid : installation ok
test 1)
post-install : adresse du serveur Nextcloud sous Yunohost
validation : erreur
Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false'....

Test 2)
post-install : adresse du serveur Nextcloud sans Yunohost (donc sans SSO ni LDAP)
validation : OK
Connection : OK

Un grand merci pour votre aide!

**Comment by tituspijean** [comment]
Bonjour,

Ç'aurait plutôt eu sa place dans YunoHost-Apps/nextcloud_ynh, mais puisqu'on est là... 😅

Peux-tu donner l'autorisation `Nextcloud` aux visiteurs dans ton panneau d'administration de YunoHost, et réessayer ?

**Comment by fredjoz** [comment]
Bonjour @tituspijean 

(En fait, j'avais aussi fait une issue dans Yunohost-Apps/nextcloud...)

Merci pour ta réponse. Ca fonctionne, j'ai pu me connecter.
Je vais essayer avec les autres utilisateurs.

Un grand merci et un joyeux Noël!!
