### ISSUE TITLE
Installing Let's Encrypt SSL in 11.0.1 fails via CLI

### ISSUE THREAD

**Issue by Bugsbane** [YunoHost/issues#1955]
### Describe the bug

When installing a Let's Encrypt certificate with the CLI via "sudo yunohost domain cert install MYDOMAIN.TLD" just gives an error:
`
Error: 'NoneType' object has no attribute 'get'`

### Context

- Hardware: VPS bought online
- YunoHost version: 11.0.1 alpha
- I have access to my server: *Through SSH and the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: Installed on a fresh buster with the alpha install script from the forum post

### To reproduce

`
sudo yunohost domain cert install MYDOMAIN.TLD`

### Logs

Weirdly enough, all of the logs only seem to show the successful operations. None of the logs seem to show the various times I tried to install a cert with CLI and got the error above.

**Comment by morta5** [comment]
I got this error when trying to install a cert for a domain which didn't run through diagnosis. Running diagnosis fixed this

**Comment by Bugsbane** [comment]
Haven't had the chance to re-check, but if this is indeed the cause of the issue, a workaround would be to have the cert install command run the necessary parts of diagnosis first, if it hadn't already been run.

**Comment by alexAubin** [comment]
Fixed it recently
