### ISSUE TITLE
CI: Backup/Restore fails because of missing "python3-venv" package

### ISSUE THREAD

**Issue by jedie** [YunoHost/issues#1960]
I have no idea what’s wrong on CI run: Sometimes Backup/restore and Upgrade failed:
![grafik](https://user-images.githubusercontent.com/71315/148588261-0494dbbd-709f-4484-9a75-c02d88410b2d.png)

The error is e.g.:
![grafik](https://user-images.githubusercontent.com/71315/148588171-9432785e-6216-427d-abae-b2fff0d632eb.png)

This kind of error happens on debian based systems, if **python3-venv** is not installed.
But `ynh_install_app_dependencies "$pkg_dependencies"` will install `python3-venv` and then call `python3 -m venv`. Sop i assume it can't missed. It's very similar code for install.

e.g.:

![grafik](https://user-images.githubusercontent.com/71315/148587761-657e5a22-81d5-4001-acfc-76728b2cc88c.png)
* https://ci-apps.yunohost.org/ci/job/5158 (commit 0caaf2b22c9f696e8218525a0b6e3ab3882c1e73)
* https://ci-apps.yunohost.org/ci/job/5157 (commit f28852653f60268a00f7478562bf8940147b77f3)

Nothing fundamentel changed [beween these two CI runs](https://github.com/YunoHost-Apps/pyinventory_ynh/compare/f28852653f60268a00f7478562bf8940147b77f3...0caaf2b22c9f696e8218525a0b6e3ab3882c1e73): This change was an idea to fix this:
![grafik](https://user-images.githubusercontent.com/71315/148588748-da12bc42-902e-48c4-a5b2-16080fd1b525.png)
But i think it's unrelated.

So i think there is a kind of a bug in CI ?!?

See also Forum entry: https://forum.yunohost.org/t/python-package-upgrate-restore-failes-on-ci/18360

**Comment by jedie** [comment]
Hm! Now i see:

- https://ci-apps.yunohost.org/ci/job/5174 (commit c242e42ffd7b58c22ce1ab940ef987d3cde74bef) on ynh-appci-buster-amd64-stable-test-1 is [![Test Badge](https://img.shields.io/endpoint?url=https://ci-apps.yunohost.org/ci/api/job/5174/badge)](https://ci-apps.yunohost.org/ci/job/5174)
[![](https://ci-apps.yunohost.org/ci/summary/5174.png)](https://ci-apps.yunohost.org/ci/job/5174)
- https://ci-apps-bullseye.yunohost.org/ci/job/3272 (commit c242e42ffd7b58c22ce1ab940ef987d3cde74bef) on ynh-appci-bullseye-amd64-unstable-test-1 is [![Test Badge](https://img.shields.io/endpoint?url=https://ci-apps-bullseye.yunohost.org/ci/api/job/3272/badge)](https://ci-apps-bullseye.yunohost.org/ci/job/3272)
[![](https://ci-apps-bullseye.yunohost.org/ci/summary/3272.png)](https://ci-apps-bullseye.yunohost.org/ci/job/3272)

Same "pyinventory_ynh" commit, but buster vs bullseye.
Sadly compare of https://ci-apps.yunohost.org/ci/apps/pyinventory/ vs, https://ci-apps-bullseye.yunohost.org/ci/apps/pyinventory/ is not very easy. Would be great if git commit is in the table.

**Comment by jedie** [comment]
I found a work-a-round by create venv with `--without-pip` and install pip later with `ensurepip` ... Details here: https://forum.yunohost.org/t/python-package-upgrate-restore-failes-on-ci/18360/13?u=jedie and here: https://github.com/YunoHost-Apps/pyinventory_ynh/blob/9bd542c3b66e2d4c139938301fbaddf00ce38330/scripts/install#L100-L122

But i think this is not the solution for the real problem... On the other side: Maybe this is just going away after update to bullseye ...

**Comment by alexAubin** [comment]
Closing because I'm confused x_x and it sounds like you found a fix so
