### ISSUE TITLE
service redis fails to start on fresh lxc container

### ISSUE THREAD

**Issue by oiseauroch** [YunoHost/issues#1962]
### Describe the bug

When creating new lxc container with `ynh-dev`, the `redis-server` service fails to start because of readonly file system

### Context

- Hardware: lxc container
- YunoHost version: 4.3.4.2+202112131753

### To reproduce

- create a new lxc container with `ynh-dev`
- look for the status of redis service

### Expected behavior

redis service should not fail.

### Logs
```
Jan 11 20:46:09 ynh-dev-buster-unstable systemd[1]: redis-server.service: Control process exited, code=exited, status
Jan 11 20:46:09 ynh-dev-buster-unstable systemd[1]: redis-server.service: Failed with result 'exit-code'.
Jan 11 20:46:09 ynh-dev-buster-unstable systemd[1]: Failed to start Advanced key-value store.
Jan 11 20:46:09 ynh-dev-buster-unstable systemd[1]: redis-server.service: Consumed 19ms CPU time.
Jan 11 20:46:09 ynh-dev-buster-unstable systemd[1]: redis-server.service: Service RestartSec=100ms expired, schedulin
Jan 11 20:46:09 ynh-dev-buster-unstable systemd[1]: redis-server.service: Scheduled restart job, restart counter is a
Jan 11 20:46:09 ynh-dev-buster-unstable systemd[1]: Stopped Advanced key-value store.
Jan 11 20:46:09 ynh-dev-buster-unstable systemd[1]: redis-server.service: Consumed 19ms CPU time.
Jan 11 20:46:09 ynh-dev-buster-unstable systemd[1]: Starting Advanced key-value store...
Jan 11 20:46:09 ynh-dev-buster-unstable redis-server[900]: *** FATAL CONFIG FILE ERROR ***
Jan 11 20:46:09 ynh-dev-buster-unstable redis-server[900]: Reading the configuration file, at line 171
Jan 11 20:46:09 ynh-dev-buster-unstable redis-server[900]: >>> 'logfile /var/log/redis/redis-server.log'
Jan 11 20:46:09 ynh-dev-buster-unstable redis-server[900]: Can't open the log file: Read-only file system
```

**Comment by kay0u** [comment]
It doesn't work in ynh-dev, but in CI it should because I manually applied a dirty hack to avoid this crash:
```
sed -i 's@^ReadOnlyDirectories=/@#ReadOnlyDirectories=/@g' /lib/systemd/system/redis-server.service
systemctl daemon-reload
systemctl restart redis-server
```

It's a known issue as you can see [here](https://stackoverflow.com/questions/35955853/docker-redis-cant-open-the-log-file-no-such-file-or-directory), and [here](https://stackoverflow.com/questions/44814351/failed-opening-the-rdb-file-read-only-file-system)

**Comment by oiseauroch** [comment]
Ok thanks. Effectively, it works. I'm packaging scrumblr application and trying to reproduce the error found in ci gave me this error in ynh-dev. And I jumped to fast to the wrong conclusion.
