### ISSUE TITLE
README generates github.com links and instructions for non-github apps

### ISSUE THREAD

**Issue by spctrlth** [YunoHost/issues#1963]
### Describe the bug

When I build the README for <https://git.domainepublic.net/Neutrinet/neutrinet_ynh>, the developer info says:
***
To try the testing branch, please proceed like that.
```
sudo yunohost app install https://github.com/YunoHost-Apps/neutrinet_ynh/tree/testing --debug
or
sudo yunohost app upgrade neutrinet -u https://github.com/YunoHost-Apps/neutrinet_ynh/tree/testing --debug
```
***
### Context

N/A

### To reproduce

```sh
git clone https://git.domainepublic.net/Neutrinet/neutrinet_ynh
git clone https://github.com/YunoHost/apps
cd ~/apps/tools/README-generator

# Follow setup instructions from README.md
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt

# Run the generator
./make_readme.py ../../../neutrinet_ynh/
```

### Expected behavior

I expect there to not be a wrong url/instructions :upside_down_face: 

It can't really get the correct url from the manifest or anything, and i don't think installing like that even works from the gitlab we use. So either it should be omitted or the correct instructions should be generated (but than there's the question how). For now I'll just change them manually.

### Logs

N/A

**Comment by tituspijean** [comment]
(Thought of a quick fix, which turned to be a bad idea).
We could imagine having the Python script to run `git remote -v` to extract the repository link... but it would not work with SSH links.

**Comment by tituspijean** [comment]
README-generator can be forked and tweaked to your liking if your repo is outside our current git organization. We'll reconsider the matter and open a broader issue when we have federated Git forges. Someday. :)
