### ISSUE TITLE
ynh_package_check: Consider using an Info instead of warning for packages that are not under YunoHost-Apps

### ISSUE THREAD

**Issue by spctrlth** [YunoHost/issues#1964]
When you use the [package check tool](https://github.com/YunoHost/package_check) on an app that's not under YunoHost-Apps, the linter test will give a Warning `! Consider adding your app to the YunoHost-Apps organization to allow the community to contribute more easily`. I think an Info should be enough.

**Comment by spctrlth** [comment]
Euh, I see the package check has it's own issue tracker, I'll add it there and close this one.

**Comment by tituspijean** [comment]
Nah it's fine to follow it here too.
