### ISSUE TITLE
11.0: Building fresh x86 images

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1969]
- [ ] Test building images with cd_build etc
- [ ] Validate that the new images are indeed working as expected

**Comment by zamentur** [comment]
The last one is from 29 march

**Comment by tituspijean** [comment]
@nathanael-h will work on it.

**Comment by nathanael-h** [comment]
Yes, I started to look at this a few days ago. But I won't be free enough this week to go on. I will update if I have some time and news.
