### ISSUE TITLE
11.0 : Building fresh RPi images

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1970]
- [ ] Build Bullseye images using our RPi build system : https://github.com/YunoHost/rpi-image
- [ ] Validate that the images work as intended

**Comment by alexAubin** [comment]
We might want to switch to 64 bit images ? Though we probably still have to build 32 bit images for RPi <= 2 ?

https://www.toolinux.com/?raspberry-pi-os-se-met-enfin-officiellement-aux-64-bits

**Comment by nathanael-h** [comment]
Done. Artifact is here, build by CI : https://github.com/nathanael-h/rpi-image/actions/runs/2693307645
