### ISSUE TITLE
11.0 : Building fresh Armbian images

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1971]
- [ ] Build fresh Armbian bullseye images using https://github.com/YunoHost/arm-images
- [ ] Validate that the new images work as intended

**Comment by zamentur** [comment]
I tried to trigger new image build by doing a tag with git on arm-images repo, but the ci to create those image seems broken: https://arm-build.yunohost.org/YunoHost/arm-images/68

**Comment by zamentur** [comment]
I finally succeed to do it. I have also updated the arm-images repo by replacing buster by bullseye

**Comment by tituspijean** [comment]
@nathanael-h will work on it.

**Comment by nathanael-h** [comment]
Yes, doing. Cf. https://github.com/YunoHost/arm-images/pull/14

**Comment by alexAubin** [comment]
Closing, duplicate of https://github.com/YunoHost/issues/issues/1852
