### ISSUE TITLE
Impossible to create 2 application paths that share common namebase

### ISSUE THREAD

**Issue by mrflos** [YunoHost/issues#1974]
### Describe the bug

When installing an app that allows multiple instances, for instance yeswiki
i can install for example https://www.example.com/yeswiki
now i want to create another wiki on path that is very similar, but different, https://www.example.com/yeswiki2

Because the name of the first instance is included in the second one, installation of second one raises an error saying that https://www.example.com/yeswiki is already used.

### Context

- Hardware: *any, but in my case VPS bought online *
- YunoHost version: 4.3.6.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 

### To reproduce

- from Yunohost webadmin > applications > new
- install for example yeswiki on path https://www.example.com/yeswiki
- repeat to create another wiki on path https://www.example.com/yeswiki2
- BOOM!!!

### Expected behavior

The path should be considered as valid, and the application should be install

### Logs

Nothing to log, but what about a french screenshot ? (who doesn't love french screenshot)
![image](https://user-images.githubusercontent.com/124845/150981375-5a006673-062f-4ba0-a5f6-083417895508.png)

PS: reported here first : https://github.com/YunoHost-Apps/yeswiki_ynh/issues/47

**Comment by alexAubin** [comment]
Finally made a PR for this because this behavior is just stupid
