### ISSUE TITLE
tld is removed from domain name and diagnosis of dns fails

### ISSUE THREAD

**Issue by DiesDasJenes** [YunoHost/issues#1980]
### Describe the bug

If you have a domain like “trucfrmuch.fr” the diagnosis tool will complain about not having a record for "trucmuch" if you are in France. I am located in Germany and got the same error with the domain “philippludewig” with  “de” so I can expect that there are similar problems for different countries. 

I used the official yunohost support chat and a user with the name "Aleks[m]" was able to verify the problem in an test instance. 
Our guess was that in the code somewhere the tld is removed from the a string and its not checked that the domain name stays the same. 

### Context

Hardware: cloud server from Hetzner - Debian 10
YunoHost version: 4.3.6.2 (stable)
I have access to my server : Through SSH :heavy_check_mark: | through the webadmin :heavy_check_mark:
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : no

### To reproduce
Depending on your tld of your country. Example is using France.  
   1. *Go to the yunohost admin page to the menu domain
   2. *Click on create new domain
   3. Create a new domain “trucfrmuch.fr”
   4. Run the diagnosis tool for it
   5. *See error*

The error could look like this:
<img width="1208" alt="Screenshot 2022-02-08 at 13 15 38" src="https://user-images.githubusercontent.com/25532733/152990130-13b4af10-3a7f-40ee-9e4f-797b69302a90.png">

### Expected behavior

The diagnosis tool should show no errors for the domain. 

### Logs

I added a forum post for this bug: https://forum.yunohost.org/t/diagnostic-error-dns-and-email-record-missing-de/18061/6

I am not sure what kind of logs I could provide. I am happy to add whatever is needed to get this resolved.

**Comment by DiesDasJenes** [comment]
Aloha,

I coded a possbile fix. 
https://github.com/DiesDasJenes/yunohost/tree/fix-1980-extract-correct-domain-basename

I haven't tested it yet with a yunohost instance. 

Cheers

**Comment by zamentur** [comment]
It seems their is a similar bug with the DNS suggestion mechanism:
```
yunohost domain dns suggest philippludewig.de
```

**Comment by jakobkilian** [comment]
Hi, thanks for working on the issue. Found this [commit/branch](https://github.com/YunoHost/yunohost/pull/1460) addressing the issue. 
But is there any workaround to use an affected domain? When will the commit above be released?

Bought a new domain that I would need to implement quite soon... Thx a lot in advance

**Comment by DiesDasJenes** [comment]
Aloha,
@jakobkilian you can use the domain without any problem as long as you have access to the server via a terminal. 
I just installed the certificates from Let's Encrypt manually via this command: 
```
yunohost domain cert install philippludewig.de --no-checks --force \
yunohost domain cert install blog.philippludewig.de --no-checks --force 
...
```
All my websites work again. 
I tried to find some reference to this command in the Documentation and I found it [here](https://yunohost.org/en/certificate), but It was not clear to me that I could renew the Let's Encrypt cert with this command. I will try to create a pull request in the Documentation to make this more visible in some days.

**Comment by DiesDasJenes** [comment]
Hi,

I installed the latest version 4.4.2 and the issue is still present. :(
Do I need to do the migration to Yunohost 11.x?

Thanks for the support

**Comment by alexAubin** [comment]
Closing because supposedly fixed by https://github.com/YunoHost/yunohost/pull/1460
