### ISSUE TITLE
Funky cases in ynh_multimedia_* ... The whole story about multimedia is confusing and should be reworked/clarified

### ISSUE THREAD

**Issue by autra** [YunoHost/issues#1981]
### Describe the bug

Installing transmission_ynh in yunohost breaks the backup / restore of every apps that uses `ynh_multimedia_build_main_dir`. Example of affected apps: `nextcloud_ynh` or `minidlna_ynh`.

More generally, if any application using `ynh_multimedia_addfolder` is installed, it'll prevent the restoration of any apps that uses `ynh_multimedia_build_main_dir` if the first application is not installed/restored first.  

Maybe the next section will make things clearer :-)

### To reproduce

- Have a box with transmission and nextcloud.
- make a backup of system and nextcloud
- try to restore the backup in another box or lxc image

**expected**: system and netxcloud are restored correcctly

**actual**: restoration fails with

```
2022-02-08 00:51:11,737: DEBUG - + setfacl -RnL -m g:multimedia:rwX,g::rwX,o:r-X /home/yunohost.multimedia
2022-02-08 00:51:11,745: WARNING - setfacl: /home/yunohost.multimedia/user1/Share/Torrents: No such file or directory
2022-02-08 00:51:11,746: WARNING - setfacl: /home/yunohost.multimedia/user1/Share/Torrent to download: No such file or directory
2022-02-08 00:51:11,752: WARNING - setfacl: /home/yunohost.multimedia/user2/Share/Torrents: No such file or directory
2022-02-08 00:51:11,753: WARNING - setfacl: /home/yunohost.multimedia/user2/Share/Torrent to download: No such file or directory
2022-02-08 00:51:11,758: WARNING - setfacl: /home/yunohost.multimedia/share/Torrents: No such file or directory
2022-02-08 00:51:11,759: WARNING - setfacl: /home/yunohost.multimedia/share/Torrent to download: No such file or directory
2022-02-08 00:51:11,763: DEBUG - + ynh_exit_properly
2022-02-08 00:51:13,269: ERROR - Could not restore nextcloud: An error occured inside the app restore script
```

[Full logs here](https://paste.yunohost.org/raw/powaqotevi)

### Context and explanations of the bug

When transmission installs, it [creates symlinks `Torrents` and `Torrents to download`](https://github.com/YunoHost-Apps/transmission_ynh/blob/testing/scripts/install#L152) in `/home/yunohost.multimedia/share` by calling `ynh_multimedia_addfolder`.

```
$ ls /home/yunohost.multimedia/autra/Share/ -al
total 8
drwxrwxr-x+ 1 root root 98 Jun 20  2021  .
drwxrwxr-x+ 1 root root 72 Mar  3  2021  ..
drwxrwxr-x+ 1 root root  0 Jul  7  2019  eBook
drwxrwxr-x+ 1 root root 50 Apr 16  2020  Music
drwxrwxr-x+ 1 root root  0 Jul  7  2019  Picture
lrwxrwxrwx  1 root root 37 Jun 20  2021  Torrents -> /home/yunohost.transmission/completed
lrwxrwxrwx  1 root root 35 Jun 20  2021 'Torrent to download' -> /home/yunohost.transmission/watched
drwxrwxr-x+ 1 root root  0 Nov 24 15:43  Video
```

In turns, these symlinks are included into the system backup (but not the original directories they point to in transmission home).

When restoring system, these (broken) symlinks are put back into `/home/yunohost.multimedia/share`.

When restoring any applications that uses `ynh_multimedia_build_main_dir`, the restore script calls this helper, which [tries to setfacl on these broken links, which fails](https://github.com/YunoHost/yunohost/blob/dev/helpers/multimedia#L47). 

### Proposed solution

There are several ways of fixing that, but in my opinion, the most logical is to prevent system backup to include the whole multimedia share folder. Instead, it should target only the system-installed folders, aka eBook, Music, Picture, Video.

It's the responsibility of transmission_ynh application to backup/restore/deal with the links it itself installs.

When restoring system and nextcloud for instance, I expect the torrent symlinks to be absent.

When I restore transmission, I expect it to create these symlinks accordingly.

Note that a similar bug will occur with any application that registers a multimedia folder, which is another reason why I think yunohost should limit what is included in the backup of this share folder.

If you agree with this, I can make a PR to yunohost repo in that spirit.

Thanks! I hope this was readable enough...

**Comment by alexAubin** [comment]
Pinging @zamentur who initially proposed to backup the multimedia folder, which is a complex matter ...

**Comment by autra** [comment]
> When I restore transmission, I expect it to create these symlinks accordingly.

and to be precise, that's what transmission_ynh is actually doing [in its restore script](https://github.com/YunoHost-Apps/transmission_ynh/blob/testing/scripts/restore#L113). So only backuping system created folder and not everything under yunohost.multimedia/share would fix this issue fully, I think.

**Comment by autra** [comment]
Commit [1ce606d4](https://github.com/YunoHost/yunohost/commit/1ce606d4) fixes this bug, so closing.
