### ISSUE TITLE
Missing Documentation: https://yunohost.org/registar_api_googleclouddns

### ISSUE THREAD

**Issue by adambeltz2** [YunoHost/issues#1983]
### Describe the bug

Documentation is missing within the app
https://yunohost.org/registar_api_googleclouddns
![Screen Shot 2022-02-21 at 2 06 30 PM](https://user-images.githubusercontent.com/44218686/155013993-29589ef0-eebf-47aa-bc64-c153df9afd44.png)

### Context
- Added a google hosted domain.
- Application prompted about configuring API via specific link (https://yunohost.org/registar_api_googleclouddns)
- Link resolved to 404 page/Missing

**Comment by alexAubin** [comment]
Hmf yeah this is just a generic message, this page may be created in the future (who knows..) and it's not like we're going to maintain a list-of-page-that-actually-exist inside Yunohost code ....  so closing as #wontfix
