### ISSUE TITLE
CLI install failed if url contains "#"

### ISSUE THREAD

**Issue by jedie** [YunoHost/issues#1984]
I create a pull request with the git branch name "fix#77" ... I can't test it, because the CLI didn't validate this kind of url, see:

![grafik](https://user-images.githubusercontent.com/71315/155764094-1dc88625-61f5-41f8-971c-9adbb82cf053.png)

The origin link: https://github.com/jedie/invidious_ynh/tree/fix%2377

**Comment by alexAubin** [comment]
Closing because hmpf this is a boring edge case ...
