### ISSUE TITLE
nextcloud: config-panel not supported

### ISSUE THREAD

**Issue by jedie** [YunoHost/issues#1986]
![grafik](https://user-images.githubusercontent.com/71315/156518482-bda7e989-ac0e-4d85-ab8d-ef8a65f7ae72.png)

**Comment by ericgaspar** [comment]
This should be fixed with the upcoming version. https://github.com/YunoHost-Apps/nextcloud_ynh/pull/464/commits/b5c21f0c3d981eeacaa690c01147ba9e7ad17478
