### ISSUE TITLE
Standard users are prompted to perform post-install in SSH

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#1989]
### Describe the bug

YunoHost standard users given the `main.ssh` permission may be shown a prompt asking them to perform the post-installation even though it has already been performed.

### Context

- Hardware: *any*
- YunoHost version: 4.3
- I have access to my server: *ssh*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### To reproduce

1. Give a standard user the `ssh.main` permission
2. Log in via SSH with that user
*(here I am only reporting the user's explanations, I could not replicate the issue)*
3. The following banner is shown:
```
Congratulations on setting up your YunoHost server !

 To finish the installation, you should run the postinstallation.
...
```
*(in my case, I get this if I manually run `yunoprompt`)*

### Expected behavior

The message prompting a standard user to perform the post-installation should not appear, it is meant for admins only and it is shown here only because standard users have no access to `/etc/yunohost` (cf. proposed solutions).

### Proposed solutions;

Either:

* Change https://github.com/YunoHost/yunohost/blob/dev/bin/yunoprompt#L59 so that the test also checks the user is `admin`, `root`, or belonging to the future `admins` group (https://github.com/YunoHost/yunohost/pull/1408).
* Allow standard users to list files in `/etc/yunohost`. For this, https://github.com/YunoHost/yunohost/blob/33bf3b2a3a8f87af090d9b0427c6bf230f450b2f/hooks/conf_regen/01-yunohost#L195 should be:
```
    setfacl -m g:all_users:--x /etc/yunohost
```
This ACL should be just enough to test file existence without revealing too much inside the directory.

**Comment by alexAubin** [comment]
Fixed in https://github.com/YunoHost/yunohost/commit/4aaa88968a2a09f4872a8742bc70c2b1f1fddf0a
