### ISSUE TITLE
Application for user subscribtion

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#199]
###### Original Redmine Issue: [199](https://dev.yunohost.org/issues/199)

Author Name: **moul**

---

Currently, to add new user on the YunoHost instance, the administrator must fill the form for instance for a friend or a family member.

The issue is that we have to ask him which user name, email address this person want.
We have to put a simple password, then we have to ask him to change it on user interface. (Some of my user didn't :D)

It would be great if, with this application, the administrator could be able to give a link to the user which want to create an account on the YunoHost instance by filling a form.

As email quota must be decided by the admin, it could be asked before generating the link.

ljf started a [subscribe app](https://github.com/zamentur/subscribe_ynh) which give some routes added to API to be able to offer a subscription page on the YunoHost instance.

However, currently, it's not possible to add module to the web admin, there is [an old PR (never finished)](https://github.com/YunoHost/yunohost-admin/pull/76).

**Comment by zamentur** [comment]
See here for an update of this ticket https://github.com/YunoHost/issues/issues/1677
