### ISSUE TITLE
Diagnostic shows port 25 is blocked but it's not

### ISSUE THREAD

**Issue by hjri** [YunoHost/issues#1990]
### Context

- Hardware: Hetzner VPS
- YunoHost version: 11.0.5
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: no
- If upgrading, current YunoHost version: no

### To reproduce

- Run diagnostics
- Get "port 25 is blocked!!11" error
- Try to send mail to server - mail arrives
- Try to send mail from server - mail arrives
- Ergo, port isn't blocked

### Expected behavior

Doesn't warn you about blocked port if it's not blocked

### Logs

no relevant logs in web admin

**Comment by alexAubin** [comment]
Well this check usually works for many people ... Maybe you got a false-negative/false-positive, but without further details there's no way to reproduce the issue. Maybe this was a temporary issue with our diagnosis server idk

**Comment by npalix** [comment]
I currently have the same issue with YunoHost 11.1.0.2.
A "tcpdump port 25" seems OK with successful exchanges between my SMTP server and the Yunohost one,
but the webadmin reports an error (same one but two times !) about the port 25 closed and the net neutrality message.
