### ISSUE TITLE
Typo error in YH DNS config (will make ssl auto renewal to fail)

### ISSUE THREAD

**Issue by tompatulpan** [YunoHost/issues#1994]
While setting up my DNS records using Seafile in a subdomain "seafile.domain.xyz" Iv got a response in the "Suggested DNS records for manual configuration" missing the first letters.
This is the respons, note "afile" instead of "seafile" :

; Basic ipv4/ipv6 records
afile.domain 3600 IN A 11.22.333.44
afile.domain 3600 IN AAAA 01:02:010:333::1; Extra
*.afile.domain 3600 IN A 11.22.333.44
*.afile.domain 3600 IN AAAA 01:02:010:333::1
afile.domain 3600 IN CAA 128 issue "letsencrypt.org"

This will make the letsencrypt automatic renewal to fail.

**Comment by alexAubin** [comment]
Probably same issue as https://github.com/YunoHost/issues/issues/1980, fixed since then
