### ISSUE TITLE
Allow installation of applications without a _ynh suffix again

### ISSUE THREAD

**Issue by ziima** [YunoHost/issues#1998]
### Describe the bug

Newer version of Yunohost can't install application from repository whose name doesn't have a `_ynh` suffix. It was possible before https://github.com/YunoHost/yunohost/commit/171b3b25d9d4cb7aad8b2cbbc5aeb7eee6243a1f

The change made applications without `_ynh` suffix uninstallable, despite the fact they were already installed and are used.

### Context

- Tested on yunohost 4.3.6.2
- Based on https://github.com/YunoHost/apps/pull/1069#discussion_r835955825

### To reproduce

```sh
sudo yunohost app install https://gitlab.com/ziima/yusers
```
produces
```
Error: https://gitlab.com/ziima/yusers is not a valid app url: app url are expected to look like https://domain.tld/path/to/repo_ynh
```

### Expected behavior

It should be possible to still install application regardless of their name as in older Yunohost versions.

**Comment by alexAubin** [comment]
As discussed in https://github.com/YunoHost/apps/pull/1069#discussion_r840636335, to me that's a feature and not a bug...
