### ISSUE TITLE
TLS has replaced SSL

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#1999]
### Describe the bug

*Context: got an gentle but firm earful about it during JDLL 2022.*
SSL has been superseded by TLS for quite some time. Certificates generated by Let's Encrypt are actually TLS, but the webadmin strings refer to SSL.

### Expected behavior

Fix strings and variables to refer to TLS in lieu of SSL in YunoHost's UI.

**Comment by alexAubin** [comment]
Hmf great @_@

Turns out this is kinda fixed in 11.1 ... `grep ssl` on `en.json` don't return anything ... all string refer to a generic "certificate" word
