### ISSUE TITLE
Parental control

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#2000]
Some people express the need to be able to block some website and to manage the time equipment can access to internet.

If we find a solution to cover this usecase i think we should be very careful that this tools can't be transform into a spy system.

**Comment by alexAubin** [comment]
Hmf I don't know what to do with this ... this seems really out of scope of Yunohost core ... https://en.wikipedia.org/wiki/Feature_creep

**Comment by alexAubin** [comment]
Closing as "this should be an app", probably doable using pi-hole or adguardhome ...
