### ISSUE TITLE
Config panel question 'foo_bar' should be initialized with a value during install or upgrade.

### ISSUE THREAD

**Issue by jedie** [YunoHost/issues#2015]
### Describe the bug

In https://github.com/YunoHost-Apps/django-fritzconnection_ynh/pull/18 is like to add a simple Boolean flag to Django's settings. So i added a `config_panel.toml`

I used bind, to create the file:
```
bind = "DJANGO_DEBUG:/opt/yunohost/__APP__/local_settings.py"
```
See: https://github.com/YunoHost-Apps/django-fritzconnection_ynh/blob/4ea25646c7d2606f1261bc537be5d1b1ad047ca9/config_panel.toml#L3-L20

The config panel doesn't work, i always get the error:

`Config panel question 'django_debug' should be initialized...`

But this value exists, e.g.:
```
root@testyunohost:/home/jens# cat /etc/yunohost/apps/django-fritzconnection/settings.yml 
...
django_debug: 'False'
...
```
I still the the error in shell, too:

```
root@testyunohost:/home/jens# yunohost app config get django-fritzconnection
Fehler: Config panel question 'django_debug' should be initialized with a value during install or upgrade.
```

Complete debug output is here: https://paste.yunohost.org/oqokorasuz.lua

### Context

More info, see: https://forum.yunohost.org/t/add-a-new-app-settings-via-config-panel-toml/19847

**Comment by tituspijean** [comment]
(disclaimer: I have little knowledge about the config panels, I'm only tweaking here)

### Understanding `bind`

> `bind = "DJANGO_DEBUG:/opt/yunohost/__APP__/local_settings.py"`

As far as I understood the config panels, the `bind` function will parse `local_settings.py` looking for the `DJANGO_DEBUG` variable declaration line. However, the current file only contains `DEBUG = False  # Don't turn DEBUG on in production!`

If you replace the config panel line by `bind = "DEBUG:/opt/yunohost/__APP__/local_settings.py"`, it will find the right line but output `ERROR Pick a valid value for argument 'django_debug': 'false  # don't turn debug on in production!' is not among the available choices (yes/no)`.

### Do not put comments on the same line

To avoid parsing issues, put ` # don't turn debug on in production!)` on another line in `local_settings.py`.

... 

Profit.

N.B. It seems it sets the True and False values as strings. I do not know if Django accepts that. If needed, you will need to write your own getter/setter or propose a core change to fix that.

---

Looks like a small PEBCAK and a strong "we really need proper documentation on that".
Reference: https://github.com/YunoHost/yunohost/pull/987

**Comment by jedie** [comment]
When `bind` works like this, I find it very strange, isn't it?

The source `conf/local_settings.py` contains this line:
```
DEBUG = __DJANGO_DEBUG__  # Don't turn DEBUG on in production!
```
The replacement works, fine: `/opt/yunohost/__APP__/local_settings.py` is created and the line is correct.

I thought it would always work like this when changes were made:

- update the changes values in: `/etc/yunohost/apps/django-fritzconnection/settings.yml`
- recreate the file from `conf/local_settings.py` (In the same way as it will be processed on creation)

**Comment by tituspijean** [comment]
I'll @zamentur answer on the internal mechanics and correct me, though:

- the variable handled by the setting is based on the setting's name, here `main.djfritz_config.django_debug` so the bash variable is `django_debug`.
- `bind = "DEBUG:/opt/yunohost/__APP__/local_settings.py"` reads as "the variable should be bound to the  declaration of DEBUG in the file .../local_settings.py". 
  - hence why `bind = ":/file"` defaults to the same bash variable name, I guess it would be in lower case too `django_debug`
  - It uses the helpers ynh_read_var_in_file() and ynh_write_var_in_file() if you want to better understand. Basically they read the file line by line, hence the behavior. It's not "that" smart, but works good enough to handle multiple file languages.

> recreate the file from conf/local_settings.py (In the same way as it will be processed on creation)

That may be where the actual behavior differs I think. It directly reads and writes into the file. That enables us to work with files that can not be declared in the `conf/` directory.

**Comment by zamentur** [comment]
I confirm all explanation of @tituspijean .

We don't recreate the config file (here a .py) we just change the value. It allows us to display in config panel the current value in the .py used by the app. Indeed some users could have change some values by hand in this kind of files and we don't want to break their change.

We store in /etc/yunohost/apps/APP/settings.yml the same value, cause we use the method you describe (overwrite the file by a new version from the template) during upgrade process. This part could be improved in the future and we know that apps are not consistent on this behaviour (sometimes the file is replaced, sometimes not).

I made a suggestion on your PR https://github.com/YunoHost-Apps/django-fritzconnection_ynh/pull/18#pullrequestreview-984446835

About boolean management: if you don't put quotes in your initial file around your True or False value, it should not put quotes when the config panel change the value. We have a specific unit test to check that:
https://github.com/YunoHost/yunohost/blob/dev/tests/test_helpers.d/ynhtest_config.sh#L99

About this error message
> Config panel question 'django_debug' should be initialized with a value during install or upgrade.

If my change is not enough, we probably should invest a bit to see if it's not an unknown bug.

**Comment by jedie** [comment]
I found a solution, see: https://forum.yunohost.org/t/add-a-new-app-settings-via-config-panel-toml/19847/14
