### ISSUE TITLE
Can’t install pleroma

### ISSUE THREAD

**Issue by KvizadSaderah** [YunoHost/issues#2019]
### Describe the bug

Can’t install pleroma on Debian. 
VPS at digitalocean, was created for pleroma. 

yunohost:
  repo: stable
  version: 4.3.6.3
yunohost-admin:
  repo: testing
  version: 4.3.4.1
moulinette:
  repo: stable
  version: 4.3.3.1
ssowat:
  repo: stable
  version: 4.3.3.1

Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

Linux rtnkv.cloud 4.19.0-20-cloud-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux

I have full access to server. 

### Context

Smallest digital ocean vps
1gb ram

### To reproduce

clean server
Install yunohost
Start install pleroma

### Expected behavior

Install successful

### Logs

https://paste.yunohost.org/raw/ufamajibol

**Comment by tituspijean** [comment]
Please post this over at https://github.com/YunoHost-Apps/pleroma_ynh/.
