### ISSUE TITLE
Document how apps should integrate with LDAP / SSO 

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#202]
###### Original Redmine Issue: [202](https://dev.yunohost.org/issues/202)

Author Name: **Anonymous**

---

Explain in the documentation how to use yunohost SSO/user management in apps.

I see at least two topics to discuss :
- using ssowat in web apps (PHP_AUTH_USER/REMOTE_USER, look for http basic auth plugins for your app). show use case for a number of langages (php/python/...)
- using LDAP for non-web-apps or at least non browser-based apps (baikal, owncloud, ...)

**Comment by alexAubin** [comment]
Let's say it's done, cf https://yunohost.org/packaging_sso_ldap_integration
