### ISSUE TITLE
UnboundLocalError: local variable 'available' referenced before assignment

### ISSUE THREAD

**Issue by bh-cod4r** [YunoHost/issues#2020]
### Context

- Hardware: *VPS bought online / Old laptop or computer / Raspberry Pi at home / Internet Cube with VPN / Other ARM board / ...*
- YunoHost version: x.x.x
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no / yes*
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current YunoHost version:

**Comment by bh-cod4r** [comment]
Hi,
Hardware Intel -i3 based PC
Installed using - yunohost-buster-4.1.8-amd64-stable.iso
Also tried installing using VirtualBox using same file also failed.
[YuNohost-error.txt](https://github.com/YunoHost/issues/files/8839516/YuNohost-error.txt)

Please see attached error log from browser post install
Any help very much appreciated, thank you.

**Comment by alexAubin** [comment]
Fixed in https://github.com/YunoHost/yunohost/commit/b7bea608f6dc268cc2eb6e2aeeca12e6f458ae88
