### ISSUE TITLE
New portal API to partially replace SSOwat

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#2028]
See https://github.com/YunoHost/yunohost/pull/1387

**Comment by ketsapiwiq** [comment]
![notes](https://user-images.githubusercontent.com/26697460/183137851-180dec9a-2171-4daa-bf3b-930a5489d380.png)
notes by @alexAubin

**Comment by selfhoster1312** [comment]
To try the new portal API, execute this script from a fresh Yunohost install:

```
#! /usr/bin/env bash

echo "Waiting for network to come online..."

while ! ping -c 1 google.fr ; do
    sleep 1
done

set -ex

git clone --recursive https://github.com/yunohost/ynh-dev /ynh-dev
cd /ynh-dev
for repo in yunohost moulinette ssowat; do
    git clone --recursive https://github.com/selfhoster1312/$repo
    cd $repo
    git checkout portal-api
    cd ..
    ./ynh-dev use-git $repo
done

export DEBIAN_FRONTEND=noninteractive
apt --yes update
apt --yes upgrade
apt --yes install lua-basexx lua-luaossl lua-logging python3-jwt

yunohost tools regen-conf
yunohost app ssowatconf

wget https://forge.yunohost.org/debian/pool/unstable/y/yunohost-portal/yunohost-portal_12.0+202308071445_all.deb
dpkg -i yunohost-portal_12.0+202308071445_all.deb

systemctl start yunohost-portal-api
```

Not sure about the steps to reproduce, but after installing my_webapp to the domain root, SSOWat config was broken:

```
2023/08/13 17:28:18 [error] 20272#20272: *29 lua entry thread aborted: runtime error: /usr/share/ssowat/access.lua:64: attempt to concatenate field 'cookie_name' (a nil value)
stack traceback:
coroutine 0:
        /usr/share/ssowat/access.lua: in function 'check_authentication'
        /usr/share/ssowat/access.lua:80: in function </usr/share/ssowat/access.lua:1>, client: 192.168.42.2, server: , request: "GET /yunohost/sso HTTP/2.0", host: "ynh-portal"
2023/08/13 17:29:08 [error] 20272#20272: *29 lua entry thread aborted: runtime error: /usr/share/ssowat/access.lua:64: attempt to concatenate field 'cookie_name' (a nil value)
stack traceback:
coroutine 0:
        /usr/share/ssowat/access.lua: in function 'check_authentication'
        /usr/share/ssowat/access.lua:80: in function </usr/share/ssowat/access.lua:1>, client: 192.168.42.2, server: , request: "GET /yunohost/sso HTTP/2.0", host: "ynh-portal"
2023/08/13 17:30:09 [error] 20272#20272: *29 lua entry thread aborted: runtime error: /usr/share/ssowat/config.lua:91: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'pairs'
        /usr/share/ssowat/config.lua:91: in function 'get_config'
        /usr/share/ssowat/access.lua:22: in function </usr/share/ssowat/access.lua:1>, client: 192.168.42.2, server: , request: "GET /yunohost/sso HTTP/2.0", host: "ynh-portal"
```

Running `yunohost app ssowatconf` again fixed it

**Comment by selfhoster1312** [comment]
One issue i found: when i log out the cookie isn't invalidated simply dropped from the browser. Usually upon logout cookies are denylisted so that they can't be spoofed by another client obtaining them.

This is an architectural problem with this patch as cookies are validated by SSOWat but emitted by another program (yunohost-portal-api via moulinette/interfaces/api.py) so SSOWat has no idea that a logout occurs and just validates the signature with the provided secret.

Not sure what to do with this information.

**Comment by selfhoster1312** [comment]
From a quick look at the new code, some portalapi methods are not implemented yet:

- `portal_apps()` to query which apps i have access to
- `portal_public()` to query public apps
- `portal_reset_password()` for lost passwords
- `portal_register()` for invitations or free registration

**Comment by alexAubin** [comment]
>portal_reset_password() for lost passwords
>portal_register() for invitations or free registration

These are clearly not trivial and are "major projects" in themselves and will come later

**Comment by selfhoster1312** [comment]
If some people would like to install my work in progress portal... assuming the setup domain is domain.tld:

```
yunohost app install --force -l login -a "domain=domain.tld&path=/login&with_sftp=false&password=foobar&init_main_permission=visitors&phpversion=8.2&with_mysql=false" my_webapp
yunohost app makedefault my_webapp

rm -R /var/www/my_webapp/www
git clone https://github.com/selfhoster1312/yunohost-portal-noscript /var/www/my_webapp/www
```

To update it:

```
cd /var/www/my_webapp/www
git pull
```

The design is copied from [yunohost-portal](https://github.com/yunohost/yunohost-portal), but only the login page is done for now. The main difference is it does not use JavaScript and does not load 3rd party resources. Loads in <20KB vs 460KB for yunohost-portal.

![ynh_login](https://github.com/YunoHost/issues/assets/121760708/6f5ea7ba-ce27-45ce-b835-190387d7d57d)

**Comment by alexAubin** [comment]
Closing because PR is merged, Bookworm released as alpha etc
