### ISSUE TITLE
Multiple `Hydrating config with current values` lines in log

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#2032]
### Describe the bug

Logs are being spammed with `Hydrating config with current values`

This line is the culprit: https://github.com/YunoHost/yunohost/blob/ee29d2e4760ab621db4863d42c1068f1dd904814/src/utils/config.py#L536

Moreover, cf. log below, it is weird to see that line duplicated that many times. Based off the code, we should see it only once.

### Context

- Hardware: any
- YunoHost version: 11.0.7, or earlier?
- I have access to my server: all means

### To reproduce

Install upgrade, or use the config panel of any app relying on config panels v1.

### Expected behavior

Either remove that debug line, or make is more explicit (which values are hydrating the config?).

### Logs

https://paste.yunohost.org/raw/sugujegaye

**Comment by alexAubin** [comment]
Fixed in https://github.com/YunoHost/yunohost/commit/f6cd35d94b9b4c5b322e89da0d455eaf9e5525b2
