### ISSUE TITLE
Muc XMPP use cert without muc.DOMAIN

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#2036]
### Describe the bug

XMPP room conversation seems to fail due to difficulties to authenticate server to server transmission.

It seems it's due to the fact that we don't add muc.DOMAIN to the certificate : https://github.com/YunoHost/yunohost/blob/dev/src/certificate.py#L569

See here for more info: https://forum.yunohost.org/t/probleme-de-certificat-sur-les-conversations-a-plusieurs-xmpp/20114/4

**Comment by alexAubin** [comment]
cf https://github.com/YunoHost/yunohost/pull/1163
