### ISSUE TITLE
"Please login from the portal" but we are in the portal

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#2037]
### Describe the bug

https://forum.yunohost.org/t/being-told-to-login-even-though-i-am-already/20286

![usZ8LGT](https://user-images.githubusercontent.com/4533074/202923852-ca2f91c0-cbd1-40a6-937f-c0e019db34a0.png)

**Comment by HyperCriSiS** [comment]
I also have similar issue.
I even cannot login anymore via the portal, only the admin interface.

As far as I found out it is Browser related.

It does not work in Firefox and Opera.
But it does work in Chrome.

And funny thing is the Admin Interface does not work in Chrome :D

**Comment by tituspijean** [comment]
Can you check the browers' console when triggering the errors? I suspect CORS settings.

**Comment by alexAubin** [comment]
Probably indirectly fixed in the SSO/portal rework
