### ISSUE TITLE
414 Request-URI Too Large

### ISSUE THREAD

**Issue by guedressel** [YunoHost/issues#2038]
### Describe the bug

I attempted to set-up yunohost on a vm behind a http proxy (nginx).  
After some effort I managed to bring the http proxying up but ran into the issue that during the initial SSO HTTP redirection I ended up that the proxying nginx deamon is responding with a "414 Request-URI Too Large" error message.
There was no way for me to configure this nginx deamon to let this SSO-redirection-request go.
That request is about 9k in size.

### Context

- Hardware: VM, Debian 10 based.
- YunoHost version: 4.3.6.3
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?:  yes
  - If yes, please explain: HTTP reverse proxy in front of yunohost vm.

### Expected behavior

show login screen

### Actual behavior

![image](https://user-images.githubusercontent.com/1841616/178109186-fe71057f-6d2b-408d-8921-c8b1de5ec352.png)

This is the Network activity log from Firefox:

![image](https://user-images.githubusercontent.com/1841616/178109236-27a81107-aa16-4eec-8771-806bde0c477e.png)

**Comment by guedressel** [comment]
@tituspijean noticed that the successive requests are containing the former in the base64 encoded querye parameter.
Seems like a loop building up the URL through redirects until the proxy nginx blocks the request.

**Comment by guedressel** [comment]
This seems to be a side effect: the actual http requests reaching the yunohost nginx has a different `Host` header than the public host - which is set to the nginx proxy in this scenario.
Now the SSOwat mechanism finds an "invalid" host in the request and responds with a redirect to the public host - what makes this funny loop begin..

By configuring the nginx proxy to always send the public host to the yunohost seems to please the SSOwat (and maybe other components too).

**Comment by tituspijean** [comment]
- [ ] Information to be added to the documentation

**Comment by tituspijean** [comment]
Thank you for investigating! Closing here in favor of your other issue.
