### ISSUE TITLE
Web admin: incorrect translation in backup section when there is no backup.

### ISSUE THREAD

**Issue by nicofrand** [YunoHost/issues#2040]
### Describe the bug

My YunoHost, set in French, displays « Il y a des aucune sauvegarde.  » (~ ”There are some none backup”) instead of « Il n'y a aucune sauvegarde » (~ “There is no backup”).

### Context

- YunoHost version: 4.3.6.3
- I have access to my server: *through the webadmin*

### To reproduce

   1. Set the locale to french
   2. Go to the webadmin in the backups section
   3. Delete all backups

### Expected behavior

The message should be something like « Il n'y a aucune sauvegarde ».

**Comment by Axolotle** [comment]
fixed with at least https://github.com/YunoHost/yunohost-admin/pull/530
