### ISSUE TITLE
Offer a shell into an app environment

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#2041]
## The need

As a packager, I oftentimes end up tweaking/hacking into an (partially) installed app to debug it or understand what to do next in its packaging journey.  As a user, I oftentimes want to tweak or create a file, or run a command as the app's system user.

To make these actions easier, I would like very much to have access to a shell running as the system user, with the app's PATH or environment variables already loaded. (check out the NodeJS or Python venv apps systemd config, for example).

## Implementation

1. Store app's PATH and other environment variables in the apps settings. Proposal:

```
admin: me
id: ghost
path: /blog
env_var:
    - PATH=/opt/node_n/n/versions/node/14/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - NODE_ENV=production
```

2. Offer a `yunohost app shell <app>` command that would basically do:

```
# pseudo-code
sudo -u $app bash
cd $final_path
for item in env_var:
   export $item
```

### `chroot`

Should we `chroot` the shell, or do we assume it's a dev tool and *here be dragons*?

### `motd`

What about adding some instructions or a link to the package or app documentation within a `motd`? It could be used to remind PHP apps which version of php to use, or which flags to add to the commands (e.g. `--define apc.enable_cli=1` for Nextcloud).

**Comment by fflorent** [comment]
Am I wrong to say we may simply extract the environment variables from systemd unit description?

```bash
env_var=`systemctl show peertube.service -p "Environment" --value`
[ -n "$env_var" ] && export $env_var;
# Also source EnvironmentFile values
su - $app
```

Thus extending the manifest or app settings would not be necessary.

> Should we `chroot` the shell, or do we assume it's a dev tool and here be dragons?

Hmm. What chroot could provide to the user?

**Comment by tituspijean** [comment]
> Thus extending the manifest or app settings would not be necessary.

You are definitely right, that's nice. :)

> Hmm. What chroot could provide to the user?

I had discussed it with Aleks actually, and indeed we shall not bother with that. A chroot would block us out of a separated data directory for example.
