### ISSUE TITLE
64bit PC installation iso is corrupted

### ISSUE THREAD

**Issue by yagarea** [YunoHost/issues#2046]
### Describe the bug
Installation `.iso` file for 64bit computers is corrupted.

### To reproduce
- go to [yunohost.org/en/install/hardware:regular](https://yunohost.org/en/install/hardware:regular)
- download "Regular computer 64 bits - default"
- Use etcher to flash it on USB disk
- Get this message:
![image](https://user-images.githubusercontent.com/14349169/182904408-f718eaf3-3f57-442c-a2f2-47e6f87da923.png)

When I run etcher as root it will flash the image. But the USB is not bootable.
### Expected behavior
Installation would flash so I can install yunohost.

**Comment by tituspijean** [comment]
Please calculate the ISO's SHA256 checksum and compare it with https://build.yunohost.org/yunohost-buster-4.1.8-amd64-stable.iso.sha256sum

**Comment by yagarea** [comment]
Yes, their are matching:
```
john@arch-thinkpad ~/D/iso> sha256sum yunohost-buster-4.1.8-amd64-stable.iso
0ac2997ff090a50153c25c5b2b621bd253c4fb7f4a2ae739e25796ff9c840b28  yunohost-buster-4.1.8-amd64-stable.iso
john@arch-thinkpad ~/D/iso> cat yunohost-buster-4.1.8-amd64-stable.iso.sha256sum
0ac2997ff090a50153c25c5b2b621bd253c4fb7f4a2ae739e25796ff9c840b28  yunohost-buster-4.1.8-amd64-stable.iso
```

**Comment by narFnarF** [comment]
Similar issues:
https://github.com/YunoHost/issues/issues/2080
https://github.com/YunoHost/issues/issues/1340

**Comment by alexAubin** [comment]
If the checksum matches, then it's not corrupted ... Closign in favor of https://github.com/YunoHost/issues/issues/2080
