### ISSUE TITLE
On "yunohost log display", support names `last` and `last-X` to refer to last operations

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#2047]
Using "yunohost log display" from the CLI is a pain, because you need to know the ID of the operation found in "yunohost log list"

To simplify this, we could instead support "magic" values such as "last" which would refer to the very last known operation, and for example "last-1", "last-2", "last-3", etc. which would refer to the N-1, N-2, N-3 operations (this is because sometimes, the relevant operation is the last-1 or -2, such as a failed installed followed by the app remove, or stuff like this)

**Comment by ghost** [comment]
Me and my classmate are going to work on this issue for a university course.
