### ISSUE TITLE
Have nested organization for domains and subdomains

### ISSUE THREAD

**Issue by ashworksco** [YunoHost/issues#2049]
While I am spending time getting to know Yunohost, I'm installing various applications and have to import many subdomains as a result in the web admin.

It would be nice to have something like this as a workflow to help organize them.

-> Add a Domain / Subdomain -> 
--> Opens to the domain add form

-> Manage Domains (dropdown/expanded when clicked)
--> domain1.ltd (dropdown/expanded when clicked)
---->subdomain1.domain1.ltd (links to settings)
---->subdomain2.domain1.ltd (links to settings)
-->domain2.ltd (dropdown/expanded when clicked)
---->subdomain1.domain2.ltd ( "     " )
---->subdomain2.domain2.ltd ( "    " )
-->domain3.ltd ( "        " )
... and so on.

This especially gets convoluted if I decide to host several people on this server, and they all decide they want to use their own installations of several different applications. Some ability to sort would help a great deal.

**Comment by alexAubin** [comment]
Done in 11.1
