### ISSUE TITLE
Upgrade to Debian 11 unsuccessful. Upgrade aborts

### ISSUE THREAD

**Issue by loma-one** [YunoHost/issues#2053]
### Describe the bug

Upgrade to Debian 11 unsuccessful. Upgrade aborts

### Context

- Hardware: Strato VPS bought online ( CPU vCores 4 RAM 8 GB 300GB)
- YunoHost version: 4.4.2.3
- I have access to my server: Through SSH 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: no
- If upgrading, current YunoHost version: 

### Logs

Attempt to repair via console does not lead to success
`sudo apt install --fix-broken` and / or `sudo dpkg --configure -a` 

slapd.service - LSB: OpenLDAP standalone server (Lightweight Directory Access Protocol)
     Loaded: loaded (/etc/init.d/slapd; generated)
    Drop-In: /lib/systemd/system/slapd.service.d
             └─slapd-remain-after-exit.conf
             /etc/systemd/system/slapd.service.d
             └─ynh-override.conf
     Active: activating (auto-restart) (Result: exit-code) since Sun 2022-08-14 09:36:01 CEST; 8ms ago
       Docs: man:systemd-sysv-generator(8)
    Process: 5278 ExecStart=/etc/init.d/slapd start (code=exited, status=1/FAILURE)
      Tasks: 4 (limit: 60)
     Memory: 9.4M
     CGroup: /system.slice/slapd.service
             └─29806 /usr/sbin/slapd -h ldap://127.0.0.1:389/ ldaps:/// ldapi:/// -g openldap -u openldap -F /etc/ldap/slapd.d

Aug 14 09:36:01 h2880253.stratoserver.net systemd[1]: slapd.service: Control process exited, code=exited, status=1/FAILURE
Aug 14 09:36:01 h2880253.stratoserver.net systemd[1]: slapd.service: Failed with result 'exit-code'.
Aug 14 09:36:01 h2880253.stratoserver.net systemd[1]: slapd.service: Unit process 29806 (slapd) remains running after unit stopped.
Aug 14 09:36:01 h2880253.stratoserver.net systemd[1]: Failed to start LSB: OpenLDAP standalone server (Lightweight Directory Access Protocol).
dpkg: Fehler beim Bearbeiten des Paketes slapd (--configure):
 »installiertes slapd-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 1 zurück

https://paste.yunohost.org/raw/fifehuhebe

yunohost tools migrations run --accept-disclaimer
https://paste.yunohost.org/raw/iguluzekoh

**Comment by ericgaspar** [comment]
It may be worth checking the forum for similar issues.

**Comment by alexAubin** [comment]
Closing because a shitload of things happened since 2 weeks ago, feel free to poke / reopen if needed
