### ISSUE TITLE
config_panel.toml settings type = "email"

### ISSUE THREAD

**Issue by jedie** [YunoHost/issues#2054]
Add type `email` as a `config_panel.toml` -> Just validate the input if it's a valid email. e.g.: https://github.com/django/django/blob/f3f9d03edf17ccfa17263c7efa0b1350d1ac9278/django/core/validators.py#L174-L195

**Comment by Tagadda** [comment]
If I understand the code correctly, there's already a email type.
https://github.com/YunoHost/yunohost/blob/dev/src/utils/config.py#L878-L882

**Comment by jedie** [comment]
Oh, interesting... Seems that there are many types already there:

https://github.com/YunoHost/yunohost/blob/c88af25949cb1eb33ff7ab73005ce4241b88ea66/src/utils/config.py#L1337-L1359

```python
ARGUMENTS_TYPE_PARSERS = {
    "string": StringQuestion,
    "text": StringQuestion,
    "select": StringQuestion,
    "tags": TagsQuestion,
    "email": EmailQuestion,
    "url": URLQuestion,
    "date": DateQuestion,
    "time": TimeQuestion,
    "color": ColorQuestion,
    "password": PasswordQuestion,
    "path": PathQuestion,
    "boolean": BooleanQuestion,
    "domain": DomainQuestion,
    "user": UserQuestion,
    "number": NumberQuestion,
    "range": NumberQuestion,
    "display_text": DisplayTextQuestion,
    "alert": DisplayTextQuestion,
    "markdown": DisplayTextQuestion,
    "file": FileQuestion,
    "app": AppQuestion,
}
```

@Tagadda Thanks!

**Comment by jedie** [comment]
Now i see, that the validation is very, very relax... I open a new issues for this, here: https://github.com/YunoHost/issues/issues/2058
