### ISSUE TITLE
Standard Notes failure before and after YunoHost Migration to 11

### ISSUE THREAD

**Issue by aarontrom** [YunoHost/issues#2056]
I did the upgrade to yunohost 11 and it went soo smooth. Thanks for the amazing work you're doing! 
1 app that failed for me was the upgrade and install of Standard Notes.
I tried to upgrade it before the migration to YNH 11, then it didn't work, so I did the migration, removed standard notes and tried to reinstall it which also failed. 
I have the 2 logs here: https://paste.yunohost.org/raw/ojalorukub
and https://paste.yunohost.org/raw/uregeqohoz

**Comment by FabianWilkens** [comment]
Hi,
I have the same problem on the next version. And was not able to solve the problem, yet.
I was not aware that the problem now also exists at the current version.
Unfortunatly i don't have time to work on this the next two weeks.
So it may take same time to solve this.

**Comment by aarontrom** [comment]
Ahh okay, thx for letting us know. 
I was able to restore the latest backup of standard notes server, then installed standard notes web application again and now it's working for me. I will wait for the next upgrade :)

**Comment by tituspijean** [comment]
Closing here, to keep technical issues on apps in their dedicated organization. Follow-up in the mentioned issue above.
