### ISSUE TITLE
RStudio Server

### ISSUE THREAD

**Issue by Robinlovelace** [YunoHost/issues#2061]
Simple feature request, for RStudio Server: https://www.rstudio.com/products/rstudio/download-server/

A bit of context, it's been requested by others for Cloudron but is not yet supported: https://forum.cloudron.io/topic/1258/rstudio-server-ide-for-r-lang/9

This could be a yunohost game changer for me, I've had good experience testing it so far but rely on in-browser IDE for my work. VS Code could be an alternative but RStudio is just really nice (especially for R, obviously, but also Python for data science and technical writing with Quarto).

**Comment by alexAubin** [comment]
This topic is kinda dupicate from the app wishlist which already reference what people would like to see ...

Noet that VS code server is packaged : https://github.com/YunoHost-Apps/code-server_ynh

**Comment by Robinlovelace** [comment]
Aha yes I did spot the wishlist after creating this. Many thanks, closing for now..
