### ISSUE TITLE
Clean install of 11.0.9 on Rpi 4 2nd prompt after keyboard locale asks: Which user would you like to rename?

### ISSUE THREAD

**Issue by lightnin** [YunoHost/issues#2062]
### Describe the bug
Clean install of rPi4 on 11.0.9 downloaded here:
https://yunohost.org/en/install/hardware:rpi2plus
Checksum is ok (6bb1fc339c7c84ae758f1e7bfe5a1e421f03c51e5ff4bca66bb3b404ba382f1f  yunohost-bullseye-11.0.9-rpi-stable.img.zip)

When booting first time on screen, first prompt asks for Keyboard locale. Entered US.
Second prompt asks:
"Which user would you like to rename:"
Tried entering new / unknown users, they don't work. 
You can rename admin, but after that it returns to the Configuring keyboard prompt, repeat, etc.

Flashed 2 times with etcher to rule out errors an checked checksum.
System does not appear to come up in such a way that one can access it headless.

Expected behavior: System does not prompt me to rename anything, boots such that it can be accessed headless.

### Context
Migration from 4x killed my system, so trying to reinstall fresh.

**Comment by jeremyfix** [comment]
I did have this issue as well but only when a keyboard was plugged into the RPI ; 

Unplugging the keyboard and I was not asked to either configure the keyboard nor rename any user.

**Comment by thebongmaster** [comment]
i am getting this now after a hard crash, without a keyboard plugged in
and it was working fine before that

**Comment by ghost** [comment]
Same problem, not sure which user I'm renaming.

**Comment by alexAubin** [comment]
Duplicate of https://github.com/YunoHost/issues/issues/2079
