### ISSUE TITLE
Domain settings to disable XMPP / email per domain should be taken into account during regenconf

### ISSUE THREAD

**Issue by marcxjo** [YunoHost/issues#2063]
## Problem Scenario
Several YunoHost apps require a dedicated [sub-]domain to function correctly when installed (e.g., Mastodon, UMS, Nitter, etc.).

Often when installing such an app, I don't have a need for the additional services configured for its domain.

At the very least, I don't have need for the XMPP and mail server configs for these domains, and I typically just end up deleting them after add. I suspect that this is probably the case for several users who encounter the same scenario.

While this is obviously not difficult, a cleaner solution would be to prevent creation of these configs when explicitly not needed.

### CLI Updates

I'd like to request adding command line options to `yunohost domain add` to prevent the creation of unnecessary services. I suggest two possible models below:

#### Model 1
Add options `--no-xmpp` and `--no-mail`. Both switches should be passed without an argument; if not passed, then domain creation proceeds according to the current `domain add` logic.
* If `--no-mail` is passed when creating <domain.tld>, then no mail server configs should be generated for this domain, and users associated with the domain should not be able to send messages from the address <user>@<domain.tld>.
* If `--no-xmpp` is passed when creating <domain.tld>, then no Metronome configs should be generated for this domain, and users associated with the domain should not be able to log into the local Metronome server using the JID <user>@<domain.tld>.

#### Model 2
Add option `--no-services`. The switch should be passed without an argument; if not passed, then domain creation proceeds according to the current `domain add` logic.
* If `--no-services` is passed when creating <domain.tld>, then:
  * no mail server configs should be generated for this domain, and users associated with the domain should not be able to send messages from the address <user>@<domain.tld>.
  * no Metronome configs should be generated for this domain, and users associated with the domain should not be able to log into the local Metronome server using the JID <user>@<domain.tld>.

I had also considered suggesting a similar option to prevent user creation altogether for domains (i.e., via a `--no-users` option in Model 1 and as a consequence of passing `--no-services` in Model 2), but this seems potentially problematic, as several applications also require an owning user.

### Graphical Admin App Updates

In the graphical admin flow, either of the above proposed models could be handled with corresponding checkboxes in the domain creation form.

#### Model 1
* Two checkboxes could be rendered with respective language:
  * "Do not configure email for this domain"
    * If checked, then `--no-mail` would be passed with the `domain add` command when the form's submit button is clicked
  * "Do not configure XMPP for this domain"
    * If checked, then `--no-xmpp` would be passed with the `domain add` command when the form's submit button is clicked

#### Model 2
* One checkbox could be implemented with respective language:
  * "Do not configure messaging services for this domain"
    * If checked, then `--no-services` would be passed with the `domain add` command when the form's submit button is clicked

## Additional Remarks

The above outline implementation is a suggested plan of attack that may have obvious weaknesses in terms of the suggested semantics or factoring of configuration handling.

I'm not necessarily suggesting this feature be implemented exactly as suggested, but a pattern similar to the above would be helpful to enable creating one-off domains which serve a highly specific purpose (such as a single application and no associated non-administrative users).

Apologies if something akin to this feature has already been requested or is currently in progress; after several searches involving keywords such as "add domain," "create domain", "generate config," etc.), I wasn't able to find any conclusive evidence that this has been requested.

**Comment by alexAubin** [comment]
Meh, XMPP is already disabled when creating a subdomain nowadays, it's only enabled by default on the main domain as far as I remember ... (this is from 4.3 i think ?)

And emails (at least outgoing) are in fact needed by many applications even though it may not be obvious for the admin. Eg creating a `mastodon.domain.tld`, you will clearly expect email to work. Or maybe we could restrict emails to apps only and forbid users from having aliases using these domains ...

**Comment by alexAubin** [comment]
Ah my bad, I realize that the settings only affect the recommended DNS configuration so far, not the regenconf

**Comment by alexAubin** [comment]
Done in https://github.com/YunoHost/yunohost/pull/1541

**Comment by marcxjo** [comment]
Pardon my late response to this - thanks a ton for getting this working in the conf regen!
