### ISSUE TITLE
after yunohost upgrade dovecot failed to start with conf problem

### ISSUE THREAD

**Issue by xoddark** [YunoHost/issues#2064]
### Describe the bug

After upgrade Yunohost to bullseye and server restart, dovecot failed to start.

### Context

- Hardware: *Dedicated server*
- YunoHost version: 11.0.9.14
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch:

### To reproduce

   1. *Tried to start dovecot with yunohost service restart dovecot '...'*
   2. *See error : *
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 26: ssl_dh: Can't open file /usr/share/yunohost/other/ffdhe2048.pem: No such file or directory

### Expected behavior
devocot should be able to start.

### Logs
(doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 26: ssl_dh: Can't open file /usr/share/yunohost/other/ffdhe2048.pem: No such file or directory)

**Comment by xoddark** [comment]
fixed by change :
ssl_dh = </usr/share/yunohost/other/ffdhe2048.pem
into 
ssl_dh = </usr/share/yunohost/ffdhe2048.pem

But why this value was incorrect ? I have no idea.

**Comment by alexAubin** [comment]
This value was incorrect because the file changed between 4.x and 11.x, but your probably manually edited it, hence Yunohost's regenconf did not upgrade this file
