### ISSUE TITLE
Add a description to the service

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#207]
###### Original Redmine Issue: [207](https://dev.yunohost.org/issues/207)

Author Name: **ljf**

---

Hi,
The goal of this feature is to be able to display in web admin a description of each services. Like that debutant user could learn what service are and what they could disable or not.

I think we should add a -d DESCRIPTION, --description option on the yunohost service add command/api . 

This description could be displayed by calling yunohost service status --full or --raw , I am not sure for this second argument...

An other way could be to register app description inside the web admin, but this solution doesn't work with new services added by apps.

What do you think about this feature ?

Thanks

**Comment by Psycojoker** [comment]
Actually did that without remembering this ticket.
