### ISSUE TITLE
Switch HTTP config from nginx to Caddy

### ISSUE THREAD

**Issue by Pierstoval** [YunoHost/issues#2073]
For now, as seen in [the main repo](https://github.com/YunoHost/yunohost/tree/dev/conf/nginx), the HTTP config is done mainly with Nginx.

As Caddy is beginning to become more and more popular and used by more and more big corps, I was thinking whether the YunoHost team thought about moving from Nginx to Caddy in a potential upcoming major version.

Caddy has many advantages:
* Provided as a single binary because it's built in go (instead of C for nginx)
* Performant, it can deal with at least as many requests per second as nginx but with less workers and less CPU load
* Simpler & smaller config format with easy to setup, either with their Caddyfile or their JSON syntax
* Automatically handles TLS by itself with certificates renewal and stuff without having to think about it
* Has cool default config one-liners for [php-fpm](https://caddyserver.com/docs/caddyfile/directives/php_fastcgi), [static files](https://www.google.com/search?client=firefox-b-d&q=caddy+file_server) or even as a [reverse proxy](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy)
* Highly customizable through Caddy mods and `xcaddy` to build a custom-made version of Caddy, in case one wants to use [mercure](https://caddyserver.com/docs/modules/http.handlers.mercure) for a SSE-based hub or [cloudflare DNS providers](https://caddyserver.com/docs/modules/dns.providers.cloudflare) (and a lot more you can see in [caddy's download page](https://caddyserver.com/download)
* A [Rest-like admin API](https://caddyserver.com/docs/api) you can use internally to start/stop it, customize domain names, add or remove websites, without even having to touch the config files, all based on their JSON syntax.

WDYT? 🙂

**Comment by alexAubin** [comment]
Sounds cool but that's the kind of idea that involves rewriting like a big chunck of yunohost because so many stuff are one way or another coupled to nginx, and pretty much all apps have nginx-conf snippets that would need to be rewritten ... And there's no real "killer feature" that would justify such a big change so ...

**Comment by alexAubin** [comment]
(Oh and not mentionning the fact that SSOwat is like a lua module for nginx ...)

**Comment by Pierstoval** [comment]
> (Oh and not mentionning the fact that SSOwat is like a lua module for nginx ...)

For this part, there's `caddy-security` https://github.com/greenpau/caddy-security 😁😇

For the rest, I totally agree that it would need a rewrite of many things, I was just suggesting the idea to know if someone has an idea of how "big" the task would be 😉

**Comment by alexAubin** [comment]
Closing because this is just not going to happen ...
