### ISSUE TITLE
All `display_text`s in app manifest are displayed with same style

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#2074]
### Describe the bug

Despite having a `"style": "warning"` key in a `display_text` block of an app manifest, the text is displayed like any other text in the app installation form.

### Context

- Hardware: any
- YunoHost version: 11.0.9.12 (maybe before too?)
- I have access to my server: ssh, webadmin

### Expected behavior

`display_text`s should be given styles like in config panels.

### Logs

Example with VPN Client:

https://github.com/YunoHost-Apps/vpnclient_ynh/blob/8ced8f0f1b9dd6d04d8c795df523071b2058809b/manifest.json#L26-L38

```
          {
            "name": "disclaimer1",
            "type": "display_text",
            "style": "warning",
            "ask": {
                "en": "Please note that this application only interfaces with **dedicated, public IP VPNs accepting inbound traffic**, preferably with an associated `.cube` (or `.ovpn/.conf`) configuration file. **Do not** expect that any VPN you randomly bought on the Internet can be used! Checkout the [list of known compatible providers](https://yunohost.org/providers/vpn) for more info.",
                "fr": "Notez que cette application est prévue pour fonctionner avec des **VPN dédiés et à IP publique qui acceptent le traffic entrant**, et de préférence avec un fichier de configuration `.cube` (ou `.ovpn/.conf`) associé. Un VPN acheté au hasard sur Internet ne fonctionnera sans doute pas ! Consultez [la liste des fournisseurs connus et compatibles](https://yunohost.org/providers/vpn) pour plus d'infos."
            }
        },
        {
            "name": "disclaimer2",
            "type": "display_text",
            "style": "info",
            "ask": {
                "en": "After installation, you will be able to configure the application from YunoHost's webadmin in Applications > VPNclient > Configuration.",
                "fr": "Après l'application, vous pourrez configurer l'application depuis la webadmin de YunoHost dans Applications > VPNclient > Configuration."
            }
        }
```

Renders as:

![image](https://user-images.githubusercontent.com/8769166/192637159-b933344f-d7ba-44ef-a4ee-74bf87c09639.png)

**Comment by Axolotle** [comment]
I think `display_text` is no longer used to display an alert styled text (never was? or just to display an info styled text maybe in the past). `"type": "alert"` is the new arg for this, I haven't tested it on the current branch but it should work. Are you sure `display_text` can be rendered as an alert in config panels?
Also I wonder if `display_text` is still useful as there is `"type": "markdown"` now, and `display_text` is also allowing markdown to be passed so idk.
I'm iterating on config panels (and actions) so I'll manage to update the docs with all the new arg types ljf added while working on config panels.

**Comment by zamentur** [comment]
I agree it's the role of alert type.

But display_text was used in install args, and screen shot here are from install part, so maybe it's the issues.

About markdown and display_text. Render markdown is not so quick, so i suggest to keep a way to display a text without displaying with markdown vuejs component.

**Comment by Axolotle** [comment]
fix https://github.com/YunoHost/yunohost-admin/pull/468
- `type = "display_text"` will render simple text (no HTML nor markdown)
- `type = "alert"` is the new recommended alert styled text and accept markdown

**Comment by tituspijean** [comment]
Fixed by aforementioned PR. Thanks!
