### ISSUE TITLE
ynh_find_port behaviour

### ISSUE THREAD

**Issue by oiseauroch** [YunoHost/issues#2078]
### Describe the bug

I'm trying to package an app that need several port. Trying to get them on after an other and before saving them to the conf, if found that they are not register as used during find_port process so that same port was get several times.

### To reproduce

use ynh_find_port several times with the same port : 
```
port1=$(ynh_find_port --port 2222)
port2=$(ynh_find_port --port 2222)
```
port1 and port2 have the value of 2222

### Expected behavior

ynh_find_port should (at least temporary register the port) 
The best behaviour for me should be : 
```bash
ynh_find_port --port 2222 --name port_name 
ynh_find_port() {
    while ! ynh_port_available --port=$port; do
        port=$((port + 1))
    done
   ynh_app_setting_set --app=$app --key=$port_name --value=$port
   echo $port
}
```
an other behaviour could be : 
```bash
ynh_find_port --port 2222

while ! ynh_port_available --port=$port; do
        port=$((port + 1))
    done
    __YNH_TMP_PORT__="$__YNH_TMP_PORT:$port"
    echo $port
ynh_port_available() {


    # Check if the port is free
    if ss --numeric --listening --tcp --udp | awk '{print$5}' | grep --quiet --extended-regexp ":$port$"; then
        return 1
    # This is to cover (most) case where an app is using a port yet ain't currently using it for some reason (typically service ain't up)
    elif grep -q "port: '$port'" /etc/yunohost/apps/*/settings.yml; then
        return 1
    elif $port in $__YNH_TMP_PORT__
        return 1
    else
        return 0
    fi
}
```

**Comment by alexAubin** [comment]
Zblerg yeah, but a simple workaround should be something like:

```
port1=$(ynh_find_port --port 2222)
port2=$(ynh_find_port --port $(($port1+1)))
```

**Comment by oiseauroch** [comment]
Yeah, I choose to save port to settings just after each find_port command : 
```
port1=$(ynh_find_port --port 2222)
ynh_app_setting_set --app=$app --key=$port1 --value=$port 
port1=$(ynh_find_port --port 2223)
ynh_app_setting_set --app=$app --key=$port2 --value=$port 
```

**Comment by oiseauroch** [comment]
I just noticed that it can goes to very weird bugs.

**Comment by alexAubin** [comment]
(I guess you meant `port2` on third line :thinking: )

**Comment by alexAubin** [comment]
Closing because this is not a real bug, and in manifest v2 anyway the recommended flow will be to let yunohost keep a completely random port

**Comment by alexAubin** [comment]
Closing because this is not a real bug, and in manifest v2 anyway the recommended flow will be to let yunohost keep a completely random port
