### ISSUE TITLE
RPi images are partially broken because service 'userconfig-service' hangs on dpkg forever

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#2079]
Probably the RPi install process changed recently and now wants to rename the user and that the admin choose the keyboard configuration etc ...

This creates stupid issues where the service name 'userconfig-service' (or `.service` ?) hangs forever on dpkg:

https://paste.yunohost.org/guxunisoju.sql

and then this breaks app install because dpkg/apt lock is used ...

We should probably fix the image build to disable that service or pre-configure the user / keyboard or whatever ...

**Comment by nzjames** [comment]
Temporary workaround to be able to use dpkg - from an ssh session stop the userconfig service:

```
sudo service userconfig stop
```

**Comment by alexAubin** [comment]
Should be fixed by https://github.com/YunoHost/rpi-image/commit/ea6944bb2d96f53c2451c99aab2e36eecc800940 ... Currently rebuilding

**Comment by alexAubin** [comment]
New image released :+1:
