### ISSUE TITLE
Specify the packaged app version number in the manifest.json to be able to script a "new version" detection scripts

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#208]
###### Original Redmine Issue: [208](https://dev.yunohost.org/issues/208)

Author Name: **Bram**

---

This should be quite useful to be aware on how much up to date packaged applications are, especially for security releases.

**Comment by alexAubin** [comment]
Hmmmm not sure what to do with this, but basically now it's ~done (or at least that's now the current practice for recently packaged apps...)
