### ISSUE TITLE
postfix postmap permission issue with smtp relay

### ISSUE THREAD

**Issue by bganne** [YunoHost/issues#2086]
When using a SMTP relay with `yunohost settings set smtp.relay.host` on Yunohost 11/Bullseye, there is a permission issue causing postfix regen-conf to faill with the error `Warning: postmap: fatal: open database /etc/postfix/sasl_passwd.db: Permission denied`. It looks like the issue stems from /etc/postfix not being writeable by the postfix user, preventing postmap to create the /etc/postfix/sasl_passwd.db. A workaround is to generate is manually at least once:
```
chown postfix:root /etc/postfix
postmap /etc/postfix/sasl_passwd
chown root:root /etc/postfix
```

Steps to reproduce:
 1. install Yunohost on a clean system
 2. configure a relay: `yunohost settings set smtp.relay.host -v mail.example.com`

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost/commit/5394790f9197639847ce90ebc29d5b3a423711fa
