### ISSUE TITLE
11.1: Could not change admin password through administration UI

### ISSUE THREAD

**Issue by ftoral** [YunoHost/issues#2087]
### Describe the bug

Due to the [restriction on the mail value for the admin account](https://github.com/YunoHost/yunohost/commit/6512bbf70cc76b711df910acc5d47e13208dd6ed#diff-38be6c8e70fd5a036e133eb508d8cebce29b6c76a1bf3da7f447cd8e08f296a7R115), it is impossible to change the admin account password in the administration panel.
The submit of the form ends with the error "Must be a valid e-mail address, without '+' symbol (e.g. someone@example.com)"

### Context

- YunoHost version: *11.1.0.2 (testing)*
- I have access to my server: *Through SSH or through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: *no*

### To reproduce

   1. *Go to 'Administration' then log in with any "admin" user* (thanks to v11 !)
   2. *Click on 'Users' > `admin`*
   3. *Try to change the password*
   4. *See error* : "Must be a valid e-mail address, without '+' symbol (e.g. someone@example.com)"

![image](https://user-images.githubusercontent.com/3391762/200433049-b9b3018f-1d68-41a0-b47d-e73cbedf2f69.png)

### Expected behavior

The form return with no error and a confirm that the changed was applied.

### Workaround with CLI

  1. Log into your yunohost through SSH.
  2. Change the admin password with Yunohost CLI
      1. Put your password/passphrase into a file `adminpwd.txt` because you don't want to let your password clear in the server history or you don't want to deal with escaping special char (as your super strong password have)
      2. Run the moulinette `sudo yunohost user update admin -p $(cat adminpwd.txt)`
      3. Remove the password file `rm adminpwd.txt`...

**Comment by alexAubin** [comment]
Hmf closing because the recommendation is going to be : "if you want to keep the admin user, you should delete it and recreate it", otherwise there are a bunch of things that are going to be messed up ... this legacy admin user was initially only meant for "backward compatibility" i.e. making it so that you can login using the "old" admin/password credentials on the new login form
