### ISSUE TITLE
yunohost domains dns-conf deprecation

### ISSUE THREAD

**Issue by xeruf** [YunoHost/issues#2090]
https://yunohost.org/en/dns_config mentions to use `domains dns-conf` for setting up the DNS config.
But firstly, I should be able to run this command before postinstall so I can actually set the DNS up correctly before completing the form.
Second, why is deprecated? Then there should be a proper new alternative described in the docs.
```sh
root@yuno:~# yunohost domain dns-conf DOMAIN
Error: YunoHost is not correctly installed. Please run 'yunohost tools postinstall'
root@yuno:~# yunohost domain dns-conf DOMAIN
Warning: 'yunohost domain dns-conf' is deprecated and will be removed in the future
Warning: 'yunohost domain dns-conf' is deprecated and will be removed in the future
``

**Comment by alexAubin** [comment]
Closing because it is described in the docs, cf `yunohost domain --help`
