### ISSUE TITLE
Prevent users from editing profile

### ISSUE THREAD

**Issue by GitBaer** [YunoHost/issues#2095]
Hello,

it would be good to get an option to prevent users from editing their profiles (or restrict this by default). I think users should not be able to change or add email addresses, too (only set forward address).

Thank you.

**Comment by eauchat** [comment]
I think this is related to #1295, nope?

**Comment by eauchat** [comment]
And also to #1675 maybe.

**Comment by alexAubin** [comment]
Yes closing as duplicate of existing issues
