### ISSUE TITLE
An improper SSL certificate is issued when main domain is replaced

### ISSUE THREAD

**Issue by ThomasFreedman** [YunoHost/issues#2101]
### Describe the bug
The certificate for ozarktalk.nohost.me is not a valid Letsencrypt cert so browsers report an insecure connection.
It looks self-signed to me, and the original ozcotalk.tech and ozcotalk.nohost.me domain info got mixed which confused LetsEncrypt.

### Context
I installed yunohost with hostname ozcotalk.tech to match the domain provided with the vps account. I later discovered the account didn't come with any domain, so I:
1) created a different domain (ozarktalk.nohost.me) according to the documentation (https://yunohost.org/en/dns_nohost_me)
2) made it the main domain
3) removed the original domain (ozcotalk.tech)

When I ran `yunohost diagnosis show --issues --human-readable` after the removal the old domain was still listed along with many errors. This confused me for quite awhile until I discovered it was necessary to run `yunohost diagnosis run` to update what the `show` command reports.

After running `yunohost diagnosis run` there are no issues reported at all, including for email. However, remnants of the ozarktalk.tech domain still remain, and browsers report an insecure website.

- Hardware: *VPS 50GB SSD, 2048 RAM, 1 core CPU
- Linux ozcotalk.nohost.me 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64
- I have access to my server through SSH and the webadmin 
- YunoHost version: 
   root@ozcotalk:/home/admin# yunohost --version
   yunohost:  repo: stable  version: 11.0.10.2
   yunohost-admin: repo: stable  version: 11.0.11
   moulinette: repo: stable version: 11.0.9
   ssowat: repo: stable version: 11.0.9

### To reproduce
Install yunohost with one hostname / domain, then add a new domain.nohost.me, make new one primary, remove original
Used https://yunohost.org/en/dns_nohost_me as a reference guide. Not sure why dyndns is required, but followed those
instructions.

### Expected behavior
A fully configured domain, DNS, email and LetsEncrypt certificate so browers recognize website as valid & secure

### Logs
I have entire console text besides the logs in yunohost. There are many. The failures do not reflect this issue and were resolved, such as reverse proxy not being set correctly.

root@ozcotalk:/home/admin# yunohost diagnosis run
Success! Everything looks OK for Base system!
Success! Everything looks OK for Internet connectivity! (+ 1 ignored issue: no IPv6)
Success! Everything looks OK for DNS records!
Success! Everything looks OK for Ports exposure!
Success! Everything looks OK for Web!
Success! Everything looks OK for Email!
Success! Everything looks OK for Services status check!
Success! Everything looks OK for System resources!
Success! Everything looks OK for System configurations!
Success! Everything looks OK for Applications!

root@ozcotalk:/home/admin# yunohost domain cert-status ozcotalk.nohost.me
Warning: 'yunohost domain cert-status' is deprecated and will be removed in the future
certificates: 
  ozcotalk.nohost.me: 
    CA_type: Other / Unknown
    summary: Good
    validity: 3649
root@ozcotalk:/home/admin# yunohost domain cert-install ozcotalk.nohost.me
Warning: 'yunohost domain cert-install' is deprecated and will be removed in the future
Error: The certificate for domain ozcotalk.nohost.me is not self-signed. Are you sure you want to replace it? (Use '--force' to do so.)

root@ozcotalk:/etc/nginx# yunohost domain list
domains: ozcotalk.nohost.me
main: ozcotalk.nohost.me

root@ozcotalk:/etc/nginx# yunohost domain dns push ozcotalk.nohost.me
Info: This domain is a nohost.me / nohost.st / ynh.fr and its DNS configuration is therefore automatically handled by YunoHost without any further configuration. (see the 'yunohost dyndns update' command)

```
$ openssl.exe s_client -connect ozcotalk.nohost.me:443
CONNECTED(00000004)
depth=1 CN = ozcotalk.tech, O = ozcotalk
verify error:num=19:self signed certificate in certificate chain
verify return:1
depth=1 CN = ozcotalk.tech, O = ozcotalk
verify return:1
depth=0 CN = ozcotalk.nohost.me
verify return:1
---
Certificate chain
 0 s:CN = ozcotalk.nohost.me
   i:CN = ozcotalk.tech, O = ozcotalk
 1 s:CN = ozcotalk.tech, O = ozcotalk
   i:CN = ozcotalk.tech, O = ozcotalk
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDzjCCAragAwIBAgIUANkqpSUyt825HWpZP3WzsdXQACcwDQYJKoZIhvcNAQEL
BQAwKzEWMBQGA1UEAxMNb3pjb3RhbGsudGVjaDERMA8GA1UEChMIb3pjb3RhbGsw
HhcNMjIxMjAzMDE1MjM1WhcNMzIxMTMwMDE1MjM1WjAdMRswGQYDVQQDExJvemNv
dGFsay5ub2hvc3QubWUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDZ
9rxPW1EWKVCiax6d00FbeAYwr9g2VVEmpdi4x+5C+uRM2xY6zpo/BBC9GM2X2RMV
F7hYPczw3exmK5PbrcRky/6aYi7her1RpUIhBr4uaXQG9+cob4vxO2npx8S1MuCV
mI1cBMo2A0UoGuDkyIojnpVJup5MeXelF2lyQiJ/pD4W+NMqWBDyboc0Qq8wI3Z9
wHsKNzoybRSmDOARmRb1+T9q1eiM5IKTuQ45jLtY19sdY1ERhQ8PeEuSjusZ6nK8
a6NUhGvSW6Ptu89jUkiUaAS9PGcdTuxrG5QnNffRALHvHRIp4A6lb+5+VSrZFVCK
dF22TCbDRxZZlVAWfvwxAgMBAAGjgfcwgfQwCQYDVR0TBAIwADAsBglghkgBhvhC
AQ0EHxYdT3BlblNTTCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFIqz
1jCtXj6p2op4SCDNyahNZkPOMB8GA1UdIwQYMBaAFGNU5IziIfor6qB+ytMOrrzX
PBbvMAsGA1UdDwQEAwIF4DBsBgNVHREEZTBjghJvemNvdGFsay5ub2hvc3QubWWC
Fnd3dy5vemNvdGFsay5ub2hvc3QubWWCFW5zLm96Y290YWxrLm5vaG9zdC5tZYIe
eG1wcC11cGxvYWQub3pjb3RhbGsubm9ob3N0Lm1lMA0GCSqGSIb3DQEBCwUAA4IB
AQBcn+cdw+dQdCyiLqAKdOFTHRHiButiUX093riV+aLn2trfAJPBZVVNgaNAALgW
54e+QUJGxiuV3CsUECAaztLeVlTCu2GiTK3nhrmFRis6C6TfWLWenglfb0cuWukR
wQ6tqHTOuHR9uXYsVG8/EYZ7+YFZ9SdvSsf5nGY8KdjvhiAAsf5C8R72x4Q8NMcq
cTrxkcMtxL1yYfGYrWNWWIJO0jFxBuThiHo7/Dbm77ormlqWl2UJ+Mxge4uKGbWZ
xIj5DJw4GZpvfiiMb7h8/hPuuDiHfFHAycXUUinh3S4lSRPqi93HdlcG0I+LZLkl
08qKwphfLQZYUmsh7djxQBye
-----END CERTIFICATE-----
subject=CN = ozcotalk.nohost.me

issuer=CN = ozcotalk.tech, O = ozcotalk

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2440 bytes and written 410 bytes
Verification error: self signed certificate in certificate chain
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 19 (self signed certificate in certificate chain)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 5ABF4098CE60F9504BC60C97C7DF917D3B436F478A4F352A6750E3234D36C546
    Session-ID-ctx:
    Resumption PSK: CD030839623B2676E0200046E512C4136C490123098602B48278DEC596B07D1173555F32E622F9F0D490CE089E5FD401
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 86400 (seconds)
    TLS session ticket:
    0000 - 47 c5 d6 7b f4 ae c5 6f-63 d3 a1 df 5f 32 45 a0   G..{...oc..._2E.
    0010 - 5d 8c 95 d3 09 f9 cb af-de 11 63 a8 33 9a 8e ae   ].........c.3...

    Start Time: 1670469958
    Timeout   : 7200 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 7369A1463285E9B90710C76FECA695151D92FAEEC46E75FC06FB455353536CFA
    Session-ID-ctx:
    Resumption PSK: 06FB47CC82D36EC0F9613730A159B29E68418CBD0A610D9515440B90FF879BEF9E3BFFC093F7965C83828C868F72AF45
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 86400 (seconds)
    TLS session ticket:
    0000 - 6a 70 37 65 95 c2 c6 e5-93 2a 83 53 38 13 a8 3c   jp7e.....*.S8..<
    0010 - 07 3b fb a6 fc 1e 62 e8-80 f6 f1 1c 86 72 f0 b4   .;....b......r..

Start Time: 1670469958
    Timeout   : 7200 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
closed

```

**Comment by alexAubin** [comment]
Yes that's a boring edge case, it's partially fixed in 11.1 : https://github.com/YunoHost/yunohost/commit/463d76f867ff4253882a0709a44c1a5deac01153

It has nothing to do with "Lets Encrypt", it's "just" that it's not really easy to identify that a cert is self-signed when the domain of the issuer is not registered in YunoHost anymore.

So whatever, just don't change the main domain, and/or install Lets Encrypt certs instead of sticking with the self-signed cert
