### ISSUE TITLE
Ssl certs are not renewed automaticaly

### ISSUE THREAD

**Issue by rosbeef** [YunoHost/issues#2102]
### Describe the bug
Ssl certs are not renewed **automaticaly** at the end of certs validity
i have to run the update manualy 

### Context

- Hardware: *odroid hc1/lxc*
- YunoHost version: 11.x.x.x
- I have access to my server: *Through SSH | through the webadmin*

### To reproduce

try to access your perfect app sine celong time install
fail to access
detect that it's a certificate proble
go to the admin console
see that the certificate is not valid anymore
clic manualy renew then it works.

### Expected behavior

certificates renewall should be automatic at the end of certs life.

### Logs

tellme which

**Comment by alexAubin** [comment]
Well there is already a cron job and this works perfectly for a lot of people ...

Are you able to check root's mails which should have received some cron job failures maybe ...

**Comment by rosbeef** [comment]
i have no root mailbox in my /var/mail.
So i went to cron.daily , run the command and it throw me this error.
i know  that my ip for imap.3cmr.fr is not the same as my server because i can't use my ynh mail server for my isp.
it should not block the other domain certs update isn't it ?.

```
root@home:/home/admin# cat /etc/cron.daily/yunohost-certificate-renew 
#!/bin/bash
yunohost domain cert renew --email
root@home:/home/admin# yunohost domain cert renew --email
Error: The DNS records for domain 'imap.3cmr.fr' are different to this server's IP. Please check the 'DNS records' (basic) category in the diagnosis for more info. If you recently modified your A record, please wait for it to propagate (some DNS propagation checkers are available online). (If you know what you are doing, use '--no-checks' to turn off these checks.)
Error: Sending email with details to root ...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/certificate.py", line 368, in certificate_renew
    _check_domain_is_ready_for_ACME(domain)
  File "/usr/lib/python3/dist-packages/yunohost/certificate.py", line 844, in _check_domain_is_ready_for_ACME
    raise YunohostValidationError(
yunohost.utils.error.YunohostValidationError: The DNS records for domain 'imap.3cmr.fr' are different to this server's IP. Please check the 'DNS records' (basic) category in the diagnosis for more info. If you recently modified your A record, please wait for it to propagate (some DNS propagation checkers are available online). (If you know what you are doing, use '--no-checks' to turn off these checks.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/yunohost", line 71, in <module>
    yunohost.cli(
  File "/usr/lib/python3/dist-packages/yunohost/__init__.py", line 25, in cli
    ret = moulinette.cli(
  File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 111, in cli
    Cli(
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 505, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 586, in process
    return func(**arguments)
  File "/usr/lib/python3/dist-packages/yunohost/domain.py", line 554, in domain_cert_renew
    return certificate_renew(domain_list, force, no_checks, email)
  File "/usr/lib/python3/dist-packages/yunohost/certificate.py", line 373, in certificate_renew
    _email_renewing_failed(domain, e)
  File "/usr/lib/python3/dist-packages/yunohost/certificate.py", line 447, in _email_renewing_failed
    smtp.sendmail(from_, [to_], message.encode("utf-8"))
  File "/usr/lib/python3.9/smtplib.py", line 885, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'root': (550, b'5.1.1 <root>: Recipient address rejected: User unknown in virtual mailbox table')}
```

**Comment by alexAubin** [comment]
Yes, it shouldnt block other domains, but I think YunoHost crashes because it fails to send the email ... Can you please tell if you are in 11.0 or 11.1, there are big differences between these two versions

Also can you explain why you have imap.yourdomain.tld registered on the first place if you ain't using YunoHost for mail anyway .. (and even if you were, i dunno why you'd have this domain registered in yunohost)

**Comment by rosbeef** [comment]
11.0.10.2 
i was using imap.yourdomain.tld for testing but didn't work well really, i don'tuse it on my server for now. 
maybe i should remove. it

**Comment by alexAubin** [comment]
Hm so the issue with the mail is not related to 11.1 ...

Still pretty puzzling that it can't send an email to root, which is a pretty standard operation ...

Did you tweak postfix conf maybe ..

**Comment by rosbeef** [comment]
nop, and really i could not tell yóu why i have no root mailbox but on my user i have the 
root@domain.tld alias asociated

**Comment by alexAubin** [comment]
Closing via https://github.com/YunoHost/yunohost/commit/d7ee1c23f3df74f03327b8abd3db8d3531839c05 ... code wont miserably crash when renewal fails for one domain and somehow the mail cant be sent to root
