### ISSUE TITLE
Wrong certificat see by the MUA after Let's Encrypt refresh

### ISSUE THREAD

**Issue by npalix** [YunoHost/issues#2103]
### Describe the bug

Postfix still expose an old certificat after expiration date albeit a Let's Encrypt renewed certificat
is present.

This cause the MUA to complain about expired certificat.

### Context

- Hardware: PS bought online
- YunoHost version: 11.1.0.2
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?:  yes
  - If yes, please explain: Disable PasswordAuthentication even in the local network (server bought online) 

### To reproduce

- Try to send an email after the expiration of the previous certificat.
- The MUA complains.

No change despite a reboot.

### Expected behavior

The last certificat is exposed, so the MUA can update it.

### Logs
 postfix/submission/smtpd[3090131]: connect from unknown[MUA_IP]
 postfix/submission/smtpd[3090131]: SSL_accept error from unknown[MUA_IP]: -1
 postfix/submission/smtpd[3090131]: warning: TLS library problem: error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:../ssl/record/rec_layer_s3.c:1543:SSL alert number 45:
postfix/submission/smtpd[3090131]: lost connection after STARTTLS from unknown[MUA_IP]
 postfix/submission/smtpd[3090131]: disconnect from unknown[MUA_IP] ehlo=1 starttls=0/1 commands=1/2

### Solution

Read https://superuser.com/questions/1494333/thunderbird-not-updating-certificate-keeps-using-old-one-and-saying-its-expire

Refreshing the SNI DB fixes the problem.

cd /etc/postfix && postmap -F hash:sni

**Comment by alexAubin** [comment]
Cheers!

Should be fixed by https://github.com/YunoHost/yunohost/commit/31794008c937f4ceb0d704c19a27683b74834535
