### ISSUE TITLE
Bad gateway on dyndns.yunohost.org

### ISSUE THREAD

**Issue by hidrarga** [YunoHost/issues#2106]
### Describe the bug

I'm trying to order a new domain in nohost.me for an internet cube, but it fails because the cube tries to call `https://dyndns.yunohost.org/test/<some nohost.me domain>` to check if the domain is available, which returns a 502 bad gateway error. 

### Context

- Hardware: Internet Cube on a lime2 board
- YunoHost version: 4.4.2
- I have access to my server:  SSH, web interface and serial cable
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: I didn't run the Yunohost postinstall yet, I'm still on the install web form of the internet cube

**Comment by alexAubin** [comment]
Restarted the service since then, should be working now ...
