### ISSUE TITLE
WebAdmin: No Installed Apps in list + Domains returns with error

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [YunoHost/issues#2107]
Hi,

I originally posted this issue in the [YNH Forums](https://forum.yunohost.org/t/broke-my-yunohost-system-how-to-fix-python3-dist-packages-yunohost/22642), but have not received an answer in 4 days, so repeating here.

Something happened on my YNH server and badly corrupted the Mariadb tables - I was unable to recover using traditional mysql commands from CLI. I then did a ZFS rollback of the snapshot I had taken 1 day prior (mirrored ZFS on separate HDD than yunohost /).
`mysqlcheck --auto-repair --all-databases` returns normal after rollback.

**But now I get other errors:**
1. User panel shows installed apps, but admin panel Applications gives “There are no installed apps”.  The Searx app gave internal server error, so I did `yunohost app remove searx` & re-installed from cli. The App now works, but does not show up in the admin panel (still empty)
2. Going through `/var/log` folders, I see that installed Apps work, but they register several errors, including “version mismatch” messages.
3. Web Admin -> Domains gives error below. Reinstalled python3-urllib3, openssl
```
File /usr/local/lib/python3.9/dist-packages/OpenSSL/crypto.py, line 3224, in <module>  utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument name

```
`pip install --force-reinstall pyopenssl -> ERROR: Cannot uninstall pycparser. It is a distutils installed...
`

**Solution:**
I’m hoping there’s a yunohost cli command that can softly (without resetting database entries) reinstall / upgrade to latest version for all installed apps?

If you have a partial answer, or things I can try, I'm happy to do it.

**P.S.** I did break the system while trying to do some actions with Python3 PIP, and I initially thought my problem was only due to PIP actions, but after further thought I think that there may have been more than one errors that recurred at the same time?

Thank you for your help.

**My YunoHost server**

Hardware: on-premise Old computer amd64
YunoHost version: 11.1.1.2 (Bullseye)
I have access to my server : ANY/ALL (Through SSH | through the webadmin | direct access via keyboard / screen)
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : yes
If yes, please explain:: Broke the system using Python3 PIP, but MariaDB seems to have had a separate issue.

**Comment by alexAubin** [comment]
```
File /usr/local/lib/python3.9/dist-packages/OpenSSL/crypto.py, line 3224, in <module>  utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument name
```

That one is yet another caused by a local install of openssl (as can be seen by the /usr/local/lib prefix) so no a YunoHost error ... just don't randomly install stuff globally with pip ...

**Comment by Beeblebrox-BSD** [comment]
Thanks

> That one is yet another caused by a local install of openssl (as can be seen by the /usr/local/lib prefix)

`pip uninstall openssl`  -> WARNING: Skipping openssl as it is not installed.
`ls /usr/local/lib/python3.9/dist-packages/OpenSSL` -> 8 files in the folder
So I suppose pip on the system is broken?
Is there a complete list of Python3.9 libraries for YNH? Then I could delete all Python, then reinstall from the list?


**Some debugging I tried to do:**
From the server CLI, `yunohost app list` works normally.
`yunohost app upgrade wordpress` gives error:
```
Info: Now upgrading wordpress...
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 70, in <module>
    yunohost.cli(
  File "/usr/lib/python3/dist-packages/yunohost/__init__.py", line 42, in cli
    ret = moulinette.cli(
  File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 111, in cli
    Cli(
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 505, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 586, in process
    return func(**arguments)
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 532, in app_upgrade
    app_dict = app_info(app_instance_name, full=True)
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 154, in app_info
    ret["upgradable"] = _app_upgradable({**ret, "from_catalog": from_catalog})
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 227, in _app_upgradable
    installed_version = version.parse(app_infos.get("version", "0~ynh0"))
  File "/usr/local/lib/python3.9/dist-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/usr/local/lib/python3.9/dist-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '6.1.1~ynh1'
```

**Comment by Beeblebrox-BSD** [comment]
**Update:**
Domains from WebAdmin now working, after I did `pip uninstall dbus-python`
Installed Apps serving off from the main domain also show up in the Domain detail, but still not in the Apps menu.

I fear I have to do a clean reinstall :(

**Comment by Beeblebrox-BSD** [comment]
I did a hard reinstall.
