### ISSUE TITLE
Disable password auth not working in Webadmin

### ISSUE THREAD

**Issue by Gredin67** [YunoHost/issues#2108]
### Describe the bug

Setting SSH -> Password authentication -> `false` in Webadmin does not prevent ssh password login

### Context

- Hardware: *VPS*
- YunoHost version: 11.1.1.2 (testing)
- I have access to my server: *Through SSH | through the webadmin*

**Comment by alexAubin** [comment]
Hmyeah indeed, it was a total mess because `yunohost settings get some.boolean.setting` sometimes returned 0 / 1, or True / False, randomly breaking various stuff ... should be fixed in https://github.com/YunoHost/yunohost/commit/47b9b8b5205f630c8553a184c9c27f29f67571b3
