### ISSUE TITLE
SSOwat documentation

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#211]
###### Original Redmine Issue: [211](https://dev.yunohost.org/issues/211)

Author Name: **moul**

---

Document SSOwat.

_/etc/ssowat/conf.json_ is overriden each time.

Any customization should live in _/etc/ssowat/conf.json.persistent_.

How to remove protection on a non YunoHost application.

Change cookie expiration: `"session_timeout": "60"` could added in _/etc/ssowat/conf.json.persistent_.

Reload nginx after each modification of _/etc/ssowat/conf.json.persistent_.

**Comment by alexAubin** [comment]
Closing, not clear what should be done, there's a README, not clear either who should be interested by this ...
