### ISSUE TITLE
Yunohost force-disables avahi-daemon on every conf_regen

### ISSUE THREAD

**Issue by selfhoster1312** [YunoHost/issues#2115]
### Describe the bug

For some time now, Yunohost has forced disabling avahi-daemon service every time configuration is regenerated. However, it is a useful daemon that admins may enable to provide local service discovery. I personally use it for Samba shares discovery which is not provided by another Yunohost service/daemon. 

I now have to manually `systemctl enable --now avahi-daemon` every time the configuration is regenerated, and when i forget to do it my flatmates complain that filesharing is broken.

Note: avahi-daemon works perfectly and does not break yunomdns, at least according to my own experience.

### Expected behavior

It is fine that Yunohost does not enable by default avahi-daemon, or even that a fresh install force-disables it. But it should respect my choice to enable the daemon on my instance.

**Comment by selfhoster1312** [comment]
Note: the condition checking for yunohost in avahi conf is true every time because 'yunohost' is never removed from avahi-daemon.conf... or at least it was not removed on my system

**Comment by tituspijean** [comment]
Agreed, we should reinstate it. Another usecase for Avahi is mDNS reflexion accross non-multicast VPNs (namely, WireGuard, still under investigation).

**Comment by selfhoster1312** [comment]
Thanks! Can i expect this to be in a minor release soon or should i just write a cron job to keep reenabling avahi?

**Comment by alexAubin** [comment]
Hmmm it's gonna be in a minor release (11.1.2) which should arrives in the coming days/weeks, but still probably at least 2 weeks / one month away from stable release I think

**Comment by selfhoster1312** [comment]
Thanks. It's not that long i'll live with it!
