### ISSUE TITLE
(ssowat) save settings redirect to homepage

### ISSUE THREAD

**Issue by selfhoster1312** [YunoHost/issues#2116]
I'm trying to setup custom homepage via default domain application. I have a button "user settings" to take my to /yunohost/sso/edit.html, but when i click OK on there i get redirect to /yunohost/sso/portal.html.

I think SSOWat should either:

- take a URL param for the redirection
- or redirect to the primary domain homepage

Why it's a problem: my friends are confused by the periodic table full of elements. I'm trying to make a simpler page, but allow to edit settings anyway.

Why i don't want to make a SSOWat theme: i want to add features which need backend processing, and i want the page to be 100% noscript-friendly.

Any idea best way to do it?

**Comment by alexAubin** [comment]
(That doesnt really help but there's an ongoing plan to refactor SSOwat / the portal to properly separate the SSO logic from the portal logic, and introduce a proper portal API such that people can easily build custom portals)

**Comment by selfhoster1312** [comment]
It really helps because i'm not in hurry. Would it help if i comment on #2028 (or elsewhere) to document some usecases i'd like to develop in the future? Or should i open separate issues?

**Comment by alexAubin** [comment]
Closing because bookworm support released as alpha with portal api etc
