### ISSUE TITLE
Installing app from source repo fails if branch is not master

### ISSUE THREAD

**Issue by selfhoster1312** [YunoHost/issues#2119]
### Describe the bug

The branch master is [hardcoded](https://github.com/YunoHost/yunohost/blob/dd33476fac1f26429dd27f50b93e1d2162cdcc82/src/app.py#L2307) when cloning app from source repo. Trying to install an app which does not have master branch results in "Could not fetch source files, is the URL correct?".

### Expected behavior

App source from repo URL should use default branch provided by remote repository. If not, error message should say that checking out a specific branch failed, instead of pretending clone failed.

**Comment by alexAubin** [comment]
Fixed in https://github.com/YunoHost/yunohost/commit/a6db52b7b42cb0e2286f4df29441a72557326b68
