### ISSUE TITLE
Postfix don’t update SSL certificates causing thunderbird email sending issues 

### ISSUE THREAD

**Issue by Thatoo** [YunoHost/issues#2121]
### Describe the bug

Postfix didn’t update SSL certificates causing thunderbird email sending issues .

The postfix service did not loaded the last certificates. I reloaded the service but, even if imap and http certificates are ok, thunderbird sendings (smtp) have issues. The error is about expired certificates.

sudo service postix status was saying

```
janv. 07 20:24:55 postfix/postfix-script[727866]: stopping the Postfix mail system
janv. 07 20:24:55 systemd[1]: postfix@-.service: Succeeded.
janv. 07 20:24:55 systemd[1]: Stopped Postfix Mail Transport Agent (instance -).
janv. 07 20:24:55 systemd[1]: postfix@-.service: Consumed 3min 29.366s CPU time.
janv. 07 20:24:55 systemd[1]: Starting Postfix Mail Transport Agent (instance -)...
janv. 07 20:24:56 postfix[727939]: Postfix is running with backwards-compatible default settings
janv. 07 20:24:56 postfix[727939]: See http://www.postfix.org/COMPATIBILITY_README.html for details
janv. 07 20:24:56 postfix[727939]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
janv. 07 20:24:56 postfix/postfix-script[728022]: warning: /var/spool/postfix/etc/ssl/certs/ca-certificates.crt and /etc/ssl/certs/ca-certificates.crt differ
janv. 07 20:24:56 postfix/postfix-script[728046]: starting the Postfix mail system
janv. 07 20:24:56 postfix/master[728048]: daemon started -- version 3.5.17, configuration /etc/postfix
janv. 07 20:24:56 systemd[1]: Started Postfix Mail Transport Agent (instance -).
```

The command `sudo yunohost tools regen-conf postfix --force` [as explained here](https://forum.yunohost.org/t/solved-postfix-dont-update-ssl-certificates-causing-thunderbird-email-sending-issues/19590) solved my issue.

However, I'm afraid the issue come back when the certificate Let's encrypt will renew.

### Context

- Hardware:  Old laptop or computer 
- YunoHost version: 11.0.10.2
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Expected behavior

Postfix to use last renewed let's encrypt certificate.

**Comment by alexAubin** [comment]
Fixed in https://github.com/YunoHost/yunohost/commit/31794008c937f4ceb0d704c19a27683b74834535

**Comment by Thatoo** [comment]
As always, you rock!
