### ISSUE TITLE
SSOWat should prefix auth headers

### ISSUE THREAD

**Issue by selfhoster1312** [YunoHost/issues#2123]
SSOWat defines a bunch of headers:

- auth-user
- email
- [etc](https://github.com/YunoHost/SSOwat/blob/dev/conf.json.example#L2)

I'm proposing to [clear those headers](https://github.com/YunoHost/SSOwat/pull/209) when user is not logged in so they can be used to actually authenticate users without running more LDAP queries.

However, some applications might use headers with the same names, so clearing them **might** produce new bugs. I think except for `Authorization` header which is standard, other headers should have a prefix like `ssowat-auth-user`.

**Comment by alexAubin** [comment]
Closing because i yoloremoved those in the ssowat refactoring
