### ISSUE TITLE
Replace the current app wishlist with a system where user can vote etc.

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#2127]
The current app wishlist is kind of meh because you need a github account, know how to write markdown, and then we have no idea what makes more sense between the various proposed apps because users have no way to thumb up or whatever

Instead it would be nice if maybe we could create a forum category for app wishlist, where people could Like the post, and then it's probably easy to somehow fetch the list of post + likes with the Discourse API

Also found a similar thing in a totally unrelated context:

https://blog.bluemind.net/fr/suggestion-box-le-self-service-des-nouvelles-fonctionnalites/
https://github.com/bluemind-net/suggestionbox
https://community.bluemind.net/suggestions/#

**Comment by Tagadda** [comment]
It is done! :confetti_ball: 

https://apps.yunohost.org/wishlist
