### ISSUE TITLE
Open permissions to read /etc/yunohost/apps

### ISSUE THREAD

**Issue by selfhoster1312** [YunoHost/issues#2131]
From what i understand, reading the directory /etc/yunohost/apps is the official way to list installed applications without API credentials. Currently, this directory is only readable by root, which prevents unprivileged users from simply listing applications.

Possibilities:

- give read permissions on the top-level directory to everyone (without allowing access to subdirectories containing app settings)
- give read permissions to a special group (without allowing access to subdirectories containing app settings)
- give read/write permissions to a special group (yunohost-api), including subdirectories

**Comment by selfhoster1312** [comment]
So it appears i also cannot get application domain/URL from LDAP as these are defined in the app settings.yaml.

In the meantime, a workaround suggested by @Salamandar is to set up a conf_regen hook to "export" this info and make it readable by the app, like [done here](https://github.com/YunoHost-Apps/homer_ynh/blob/testing/hooks/regen_config.py).

**Comment by alexAubin** [comment]
Tempted to close this as "wontfix" because there's no real-life use-case described and I'm guessing this is about build a custom portal or something, and this is definitely not the right way to address the issue and it should instead be addressed by having a proper portal API like design/implementation is ongoing ...

**Comment by selfhoster1312** [comment]
> Tempted to close this as "wontfix"

That's ok now that a workaround is documented.

> this is about build a custom portal

Yes that's my usecase, but i can imagine other usecases if more parts of the API are opened to apps without root, like:

- writing daemons (or eg. prosody plugins) to send notification on other channels when you receive a message on a protocol
- writing a chatbot that will publish a blog article with a hedgedoc/etherpad content if the user submitting it is in admin groups
- doesn't matter because it's being phased down, but that's also the kind of stuff that SSOWat required via [app_ssowatconf](https://github.com/YunoHost/yunohost/blob/dev/src/app.py#L1560)

Most of the building blocks is possible using LDAP without authentication, but unfortunately listing apps and their domain/URL is not supported via LDAP.

I think there's two ways that can be supported:

- a conf_regen hook that saves "yunohost FOO list --json" to disk and sets POSIX permissions to determine what gets access
- a conf_regen hook that synchronizes app list and saves their domain/URL in LDAP

Right now in my WIP panel i have a mix of both and i don't think that's good®. I also don't think giving an app admin credentials (write access) to the Yunohost admin HTTP API is a good alternative.

> a proper portal API 

I don't disagree. I have personal preference to hit the LDAP database directly or a JSON representation of the system (as explained before) rather than introducing new layers or complexity/failure (HTTP), but if we can have a solid API that exposes all useful methods that's good for me.
