### ISSUE TITLE
YUNOHOST on Lime2 can't configure

### ISSUE THREAD

**Issue by ghost** [YunoHost/issues#2132]
### Describe the bug

I installed YUNOHOST in a microSD and inserted it in my Lime2, the system boot properly, but I can't configure the installation either via the web interface or from the terminal, the system is connected to the internet but I cannot do sudo apt upgrade due to a problem with a certain 'slapd', I can't make slapd running so the system is unusable.
Here are the logs  https://paste.yunohost.org/raw/iwefeciliv

**Comment by alexAubin** [comment]
As advised by the log, you should investigate why slapd is not running with `systemctl status slapd`

**Comment by alexAubin** [comment]
Closing due to lack of feedback
