### ISSUE TITLE
Add dependency on php7.4

### ISSUE THREAD

**Issue by Salamandar** [YunoHost/issues#2137]
### Describe the bug

```
/usr/share/yunohost/helpers.d/php:readonly YNH_DEFAULT_PHP_VERSION=7.4
/usr/share/yunohost/helpers.d/apt:        update-alternatives --set php /usr/bin/php$YNH_DEFAULT_PHP_VERSION
```

Thus yunohost should have an apt dependency on php7.4.

### Context

I saw that php7.4 was unused (reported by apt), and `/etc/php/7.4/fpm/pool.d` only contained the default `www.conf`.

Sooo… I uninstalled it, because nextcloud was using php8.0.

But now yunohost is broken, I can't install or upgrade or restore a package !!

```
Info : [##########++........] > Upgrading dependencies...
Attention : update-alternatives: erreur: l'alternative /usr/bin/php7.4 pour php n'est pas enregistrée ; pas de configuration
Attention : [Error] Upgrade failed.
```

### Expected behavior

Either don't call update-alternatives, or depend on php7.4.

**Comment by alexAubin** [comment]
Ah yes, but the plan is rather to remove the dependency to PHP in Bookworm (and Mysql, and metronome)

They were in the dependencies so far, but in bullseye i switched them to only recommends

I think that line about update-alternative should just have a smarter behavior and only try to apply this is there's php 7.4 installed

**Comment by Salamandar** [comment]
> Ah yes, but the plan is rather to remove the dependency to PHP in Bookworm (and Mysql, and metronome)

OK, thanks for the info :) 

> They were in the dependencies so far, but in bullseye i switched them to only recommends

IMHO tehy should stay as hard dependencies as long as installing a non-php non-mysql app requires them.

> I think that line about update-alternative should just have a smarter behavior and only try to apply this is there's php 7.4 installed

Yes, or "the most supported currently installed php", maybe "the latest php currently installed" ?

**Comment by alexAubin** [comment]
Closing this as fixed in https://github.com/YunoHost/yunohost/commit/e24ddd299ecf935d042d56a70c729c440561abcc
