### ISSUE TITLE
ynh_secure_remove assumes that $app is defined

### ISSUE THREAD

**Issue by fflorent** [YunoHost/issues#2138]
### Describe the bug

I use ynh_secure_remove in a standalone post-migration. This script defines a `$new_app` and an `$old_app` variables.

But when I run `ynh_secure_remove`, either the command fails either I have to do this weird trick:
https://github.com/YunoHost-Apps/paheko_ynh/blob/4f424e03f4fc30a13f3a7d5fc2f1d25d75b131af/conf/garradin_post_migration.sh#L25 

The reason is that the command assumes that `$app` is defined
https://github.com/YunoHost/yunohost/blob/c2c0a66cdf43abccf83fc2bdea66f04eecd5c44e/helpers/utils#L721

### To reproduce

1. Clone Paheko: `git clone https://github.com/YunoHost-Apps/paheko_ynh/`
2. `cd paheko_ynh; `
3. Checkout the branch for migration: `git checkout 4f424e03f4fc30a13f3a7d5fc2f1d25d75b131af`
4. Remove the trick I set up : `sed -i 's,app="",,g' ./conf/garradin_post_migration.sh` 
5. `yunohost app install garradin`
6. `yunohost app upgrade garradin -f -F /path/to/paheko_ynh`
7. wait 3 minutes
8. check the post-migration logs: `cat /tmp/garradin_post_migration.sh.log` 

### Expected behavior

ynh_secure_remove should work with `$app` defined

### Logs

```
/bin/bash: BASH_XTRACEFD: 7: invalid value for trace file descriptor
+ set +o xtrace
/usr/share/yunohost/helpers.d/utils: line 721: app: unbound variable

```

**Comment by alexAubin** [comment]
PR merged, cheers !

**Comment by fflorent** [comment]
Faster than light :open_mouth:
