### ISSUE TITLE
Nit: Can't find certificates as easily with subtle tabs

### ISSUE THREAD

**Issue by weex** [YunoHost/issues#2139]
### Describe the bug

Certificates tab on Domain page is subtle and makes it hard to find the feature.

### Context

New YunoHost install on public domain.

### To reproduce

Go to page of a specific domain in _Administration -> Domains_ and at first glance the tabs down the page are much harder to see than the green Let's Encrypt button that used to be there.

### Expected behavior

This is a nitpick of course but ease of Let's Encrypt is important to me as an administrator.

**Comment by alexAubin** [comment]
Closing because it's not really a bug, this is the expected behavior, and it's not clear how you'd like it to be "fixed" ...

**Comment by weex** [comment]
Fair. It's good enough that it can be found in search.
