### ISSUE TITLE
My_webapp running but can’t be managed from my ynh account

### ISSUE THREAD

**Issue by Keepshango** [YunoHost/issues#2149]
HOST CONFIG
Machine : remote VPS
OS distro : Debian 11

Hello,

I am about one month newbie to YNH, and all of the few apps I already installed are running quiet fine, except the following : 

**MY_WEBAPP**
[https://yunohost.org/fr/app_my_webapp](url)
Despite I successfully installed **My_Webapp**, and that I can establish URL connection to website implemented from within it’s root directory (no database required), I am facing  a **issue when trying to manage the app from my YNH admin account :** 

When clicking on the relevant item in the applications liist, instead of allowing me to access the page to manage My Webapp, I am shown a notification popup containing such these informations :

**Screenshot :** [https://dochub.com/keoz/pqb0g5YRqv298nzKJ2nx67/bugmywebapp-pdf?dt=sqdAFLsyXsT_qnkQXtH4](url)
......................
[GET] /apps/my_webapp/config?full
Erreur: "500" Internal Server Error
Action: "GET" /yunohost/api/apps/my_webapp/config?full&locale=fr
Config panel question 'fpm_free_footprint' should be initialized with a value during install or upgrade.

**QUESTIONS**

1. Why that, whereas URL connection to website is ok ?
2. Should I pay or not pay attention to such this notification ?
3. What may consequences be if left as it is ?
4. What content in var/log/ may help to investigate this issue further ?

Regards,

**Comment by alexAubin** [comment]
This should have been fixed in https://github.com/YunoHost-Apps/my_webapp_ynh/pull/106 but we forgot to bump the version number

The upgrade should be available on your side during the next 4 hours and that should solve the issue
