### ISSUE TITLE
Reduce change_url script size

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#2150]
`change_url` script are often quite similar, here you can find a calc sheet that study in februar 2023 the content of change_url to try to determine usecases.

## In number
* 480 apps analyzed
* 396 apps have a change_url script
* 147 apps have a very common change_url script (nginx change, and if needed restart service and import the port settings)
* 176 apps need to restart at least an other services than nginx
* 87 apps needs to specify a line_match in order to wait the service is correctly restarted
* 75 apps use at least one ynh_add_config
* 72 apps use ynh_string_replace (in different kind of files)
* 54 apps disabled the change of the path with `new_path="/"`
* 12 apps change something in the database (typically the path in the settings table)
* 9 apps need phpversion variable (often to run a specific cli tools to change the url of the app)
* few apps need to change well-known, fail2ban rules, systemd config (but it's possible that other need too but doesn't)
* few apps are multisite or disabled the change_url mechanism

[change_url.ods](https://github.com/YunoHost/issues/files/10765916/change_url.ods)

**Comment by alexAubin** [comment]
Pretty much done in 11.1
