### ISSUE TITLE
YunoHost landing page displays 'Please log in to access to this content' and logged in content at the same time.

### ISSUE THREAD

**Issue by orhtej2** [YunoHost/issues#2152]
### Describe the bug

As on picture below:
![screenshot](https://user-images.githubusercontent.com/2871798/220095867-09b397cc-7b29-4a33-9688-70ff8aba4286.png)

 - this happens by typing URL of YunoHost host
 - no log in was required before displaying this view
 - most interestingly I even saw the `Please log in` header in some Asian script, thought my VPS got hacked.

### Context

- Hardware: VPS bought online
- YunoHost version: 11.1.8.2
- I have access to my server: Through SSH & through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### To reproduce

Go to instance TLD.

### Expected behavior

Either log in page or landing page, not a mix of both.

**Comment by Tagadda** [comment]
Duplicate #2037 ?

**Comment by orhtej2** [comment]
Indeed.
