### ISSUE TITLE
convert_app_to_packaging_v2.py does not convert updater.sh

### ISSUE THREAD

**Issue by fflorent** [YunoHost/issues#2155]
### Describe the bug

When migrating a project from manifest v1 to v2 using the [relevant script](https://github.com/YunoHost/apps/blob/master/tools/packaging_v2/convert_app_to_packaging_v2.py), the file located in `.github/workflows/updater.sh` is not converted.

And it's not an easy issue :'(

This script used to invoke `jq` to extract the relevant keys, like `upstream.code` or `version`. The equivalent tool for that would be `tomlq`, which is embedded in `yq`. However `yq` is only available in Debian starting from [bookworm](https://packages.debian.org/bookworm/yq) and in Ubuntu starting from [lunar](https://packages.ubuntu.com/lunar/yq).  

Though I have not experienced the bug myself, I am quite confident some packages will be impacted by that.

**Comment by fflorent** [comment]
Also the `example_ynh` package should be updated once the issue is solved:
https://github.com/YunoHost/example_ynh/blob/4ed2fdc956358e5a5d55f3f4172d94c90da4f171/.github/workflows/updater.sh

**Comment by alexAubin** [comment]
>This script used to invoke jq to extract the relevant keys, like upstream.code or version. The equivalent tool for that would be tomlq, which is embedded in yq. However yq is only available in Debian starting from [bookworm](https://packages.debian.org/bookworm/yq) and in Ubuntu starting from [lunar](https://packages.ubuntu.com/lunar/yq).

Hmmyeah another way is to write a small `python` one-line that converts toml to json on the fly and pipe to jq ... We could even create a small binary that does this and call it ... `pq` :stuck_out_tongue_closed_eyes: 

Or just directly a python one-liner that reads the corresponding key(s) :sweat_smile:

**Comment by fflorent** [comment]
`yq` seems to be embedded in Ubuntu image in Github action:
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

> - yq 4.30.8

That's a really good news. The fix should be quite easy.

However, I would suggest to see if we get (or have already got?) some reports first. Therefore we should have our mind relieved with this issue fixed once for all or relieved because we know we get notified when it fails.

What do you think?

**Comment by fflorent** [comment]
The fix I made for updater.sh, FWIW:
https://github.com/fflorent/healthchecks_ynh/commit/34d6ad8876989e61e6e9d9470ec7a7ac0ed85a26

**Comment by Krakinou** [comment]
@fflorent : Hi, the fix does not seems to work:
````
.github/workflows/updater.sh: line 8: tomlq: command not found
cat: write error: Broken pipe
.github/workflows/updater.sh: line 9: tomlq: command not found
cat: write error: Broken pipe
````
Tested on the [zwave-ui-js](https://github.com/YunoHost-Apps/zwave-js-ui_ynh/actions/runs/4300728823/jobs/7497206138) package

**Comment by tituspijean** [comment]
Consider creating a virtual env and install tomlq:

```
cd <path to the converter>
python3 -m venv venv
source venv/bin/activate
pip3 install tomlq
```
 And run the script again. :)

**Comment by fflorent** [comment]
@ericgaspar I see that you updated the autoupdate github workflow last week:

https://github.com/YunoHost-Apps/omeka-s_ynh/blob/master/.github/workflows/updater.sh

Is that because you anticipated the failture or because you got notified of an error when the workflow ran?

Thanks in advance for your answer!

**Comment by Krakinou** [comment]
> 



> Consider creating a virtual env and install tomlq:

[Worked](https://github.com/YunoHost-Apps/zwave-js-ui_ynh/blob/150ec279e18d34502900876db3408160077840c6/.github/workflows/updater.sh#L7)
Thanks!

**Comment by alexAubin** [comment]
Closing because wontfix, we encourage to use the new autoupdate mechanism in the `sources` resource, which should be way simpler to implement/maintain and compatible with 80~90% of apps
