### ISSUE TITLE
Demo webadmin not reachable

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#2159]
### Describe the bug

The demo password is admin / demo but webadmin want a 8 chars password...
https://demo.yunohost.org/yunohost/admin/

### Suggested solution
Change the password for: demodemo (in demo.yunohost.org and on the doc)

**Comment by antonio24073** [comment]
Please, just change the password. :weary:

**Comment by alexAubin** [comment]
Should be fixed by https://github.com/YunoHost/yunohost-admin/commit/946c3e61e6b32a00cd0b8abae507d3c51812b95c ... though these days the demo is in 502 so gotta investigate this
