### ISSUE TITLE
[manifest v2] Wrong permission on $data_dir

### ISSUE THREAD

**Issue by fflorent** [YunoHost/issues#2160]
### Describe the bug

I attempt to package an app which would require to create subdirectories in `$data_dir`.

However, with manifest v2, the rights are set to `r-x` for the owner and the group by default. It should be `rwx`.

**Comment by alexAubin** [comment]
Fixed in https://github.com/YunoHost/yunohost/commit/139e54a2e52f7a8fa38df8b1c48d52204173051e ;P
