### ISSUE TITLE
`POST_INSTALL.md` messages not showing on webadmin

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost/issues#2166]
### Describe the bug

`POST_INSTALL.md` messages not showing on webadmin only in CLI

![Capture d’écran 2023-03-02 à 10 47 05](https://user-images.githubusercontent.com/46165813/222392772-4e4d8739-c909-42f7-8b62-a2ed0e50067b.png)

**Comment by alexAubin** [comment]
:scream_cat:

**Comment by Axolotle** [comment]
Should be fixed with https://github.com/YunoHost/yunohost-admin/commit/fa580fb3e7714692ccc7c89cb88a856d7350a66b !

**Comment by ericgaspar** [comment]
Is this fix part of 11.1.13 release?

**Comment by alexAubin** [comment]
Hmmnope, I'll make another release for this (Yunohost and Yunohost-admin are two different packages)
