### ISSUE TITLE
Check at least one user exist when installing an app which need a user as argument

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#217]
###### Original Redmine Issue: [217](https://dev.yunohost.org/issues/217)

Author Name: **moul**

---

It happen that you want to install an app which need a YunoHost user when there is no user account. You can't install the app. You need to add a user, then came back installing the app.

Before installing an application, check if the app need a YunoHost user as argument.
`app.py` could check if the manifest contain `"type": "user"` is present and if there is no user account. If so, don't ask manifest questions, raise an error asking to add a user.

On web admin, if this check fail, it could ask to create a user account, create, then coming back to install the app.

**Comment by Psycojoker** [comment]
Linked to https://github.com/YunoHost/issues/issues/1110

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost/commit/62ebd68e34db8d0b00dc42aaa96668f2dd833343
