### ISSUE TITLE
Packaging v2 __PATH__ not transpose in manifest.toml / [resources.permissions]

### ISSUE THREAD

**Issue by ewilly** [YunoHost/issues#2172]
### Describe the bug

When trying using path template value in manifest toml to manage permissions __PATH__ (or even $path) are not transposed to its value.
For ex. : `api.url = "__DOMAIN____PATH__/api/"` becomes `api.url = "sub.domain.tld__PATH__/api/"`
I have the issue in [Scrutiny](https://github.com/YunoHost-Apps/scrutiny_ynh/blob/420c99b355da4fa01ca6df5476059f47aca75ca6/manifest.toml#L56)

### Context

- Hardware: Old laptop or computer
- YunoHost version: 11.1.13
- I have access to my server: yes all the way
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain:
- Using, or trying to install package version/branch: no
- If upgrading, current YunoHost version: no

### Expected behavior

__PATH__ should becomes /path

**Comment by alexAubin** [comment]
Not sure I get the issue, you don't need to prefix the whole thing with `__DOMAIN__` / `__PATH__` .. The url thing is already a "suffix" of `__DOMAIN____PATH__` (like the previous permission system)

**Comment by ewilly** [comment]
Rrrr i can't get it :-(
If I :
1) set `api.url = "__DOMAIN__/__PATH__/api/.*"` in  [resources.permissions]
2) install succefully the app in domain `mydomain.tld` and path `/mypath`
3) check `/etc/ssowat/conf.json`, I have : 
```
        "scrutiny.api": {
            "auth_header": false,
            "label": "Scrutiny (api)",
            "public": true,
            "show_tile": false,
            "uris": [
                "mydomain.tld/__PATH__/api"
            ],
```
What i am missing ?

**Comment by ewilly** [comment]
Ok i finally get you `api.url = "/api/.*"` should to the trick
Sorry for the noise

**Comment by alexAubin** [comment]
(You probably mean just `"/api"` ... i doubt it's useful to have the `.*` regex part ... But if you do really need a regex, you shall prefix the whole thing with `re:`)
