### ISSUE TITLE
Port 8095 is open but diagnostic shows it closed

### ISSUE THREAD

**Issue by biva** [YunoHost/issues#2173]
### Describe the bug

I configured the port 8095 on my ISP's router to be forwarded to my Yunohost server, for the app Wireguard. Wireguard works fine now. But the diagnostic shows it's not open:

![image](https://user-images.githubusercontent.com/9964305/224298924-ee1992c5-1777-4078-872e-0d258639b901.png)

@tituspijean reported the same issue and thinks it's a bug of Yunohost (https://forum.yunohost.org/t/wireguard-virtual-private-network/12928/65). This is not preventing Wireguard to work, but this is confusing for the admin user: is there a possibility to solve it or to clarify the message?

**Comment by tituspijean** [comment]
Duplicate of https://github.com/YunoHost/issues/issues/1914. 😇

**Comment by biva** [comment]
Oh, sorry for that, I searched for 8095 and didn't find any topic. Thanks!
