### ISSUE TITLE
Webadmin displays "Mailbox used space" wrong

### ISSUE THREAD

**Issue by ghost** [YunoHost/issues#2177]
### Describe the bug

When you go to https://domain.tld/yunohost/admin/#/users/<user>, and look at their **Mailbox used space**, you will see that it is displayed by 1000x lower (eg. K instead of M, nothing instead of K).

Here is Roundcube displaying the amount correctly:

![image](https://user-images.githubusercontent.com/42217808/226198814-6def8677-734f-48a1-8147-8f06f8345957.png)

### Context

- **Hardware**: Hetzner VPS
- **YunoHost version**: 11.1.15 (stable)
- **I have access to my server**: Through SSH | through the webadmin
- **Are you in a special context or did you perform some particular tweaking on your YunoHost instance?**: no
  - If yes, please explain:
- **Using, or trying to install package version/branch**: Webadmin
- **If upgrading, current YunoHost version**:

### To reproduce
   1. Go to https://yourdomain.tld/yunohost/admin/#/users/<anyuser>
   2. Set a mailbox quota if there isn't already one (to make it clear that the mailbox used space is incorrect)
   3. Observe that the mailbox used space is wrong

### Expected behavior

Mailbox used space is displayed by 1000x more / correctly.

### Logs

N/A

**Comment by alexAubin** [comment]
Relevant piece of code if somebody wants to dig into it : https://github.com/YunoHost/yunohost/blob/debian/11.1.15/src/user.py#L623

**Comment by eldertek** [comment]
will be fixed by https://github.com/YunoHost/yunohost/pull/1632

**Comment by eldertek** [comment]
Now fixed, should be closed
