### ISSUE TITLE
How to remove non-necessary port entry from firewall 

### ISSUE THREAD

**Issue by eldertek** [YunoHost/issues#2180]
Hello, I want to remove port entry who is non-useful because closed please. (49153:49193 ; 5353)
![image](https://user-images.githubusercontent.com/118362885/229298141-58526056-5f04-40ef-8460-af1aa719e646.png)

**Comment by the7thNightmare** [comment]
Do this on your server on root, `yunohost firewall disallow Both PORT_NUMBER` (change the port number to the one you want to remove to), then refresh your webadmin.

For your case, it is like `yunohost firewall disallow Both 49153:49193` and `yunohost firewall disallow UDP 5353`.
