### ISSUE TITLE
Create a Yunohost account from the portal

### ISSUE THREAD

**Issue by tdlf32** [YunoHost/issues#2186]
Hello, I don't know how to allow visitors to the portal to create their own accounts, is this feature available in Yunohost?

If it is not yet available, it would be nice to integrate it!

**Comment by yashodhank** [comment]
That's not possible, user accounts and their custom groups has to be manually created by Admin permission user from UI/CLI.

**Comment by alexAubin** [comment]
Closing, duplicate of https://github.com/YunoHost/issues/issues/1677
