### ISSUE TITLE
Register visitor accounts

### ISSUE THREAD

**Issue by tdlf32** [YunoHost/issues#2190]
Hello, Is it possible for a visitor to register an account on Yunohost?

If this is not a built-in feature of Yunohost, then how can I do it?

**Comment by tituspijean** [comment]
Duplicate of https://github.com/YunoHost/issues/issues/1677

The matter is highly technical and touches core features of YunoHost, you most likely cannot do it yourself.

**Comment by tdlf32** [comment]
Thank you for your answer
Is this feature planned in YunoHost?
