### ISSUE TITLE
Email spam about DynDNS being unable to update a non-existent domain

### ISSUE THREAD

**Issue by sylvesterroos** [YunoHost/issues#2192]
### Describe the bug

Every 10 minute I get an email like the following:
Title: `Cron <root@thejoyofcoding> : YunoHost DynDNS update; sleep $((RANDOM%60)); ! ping -q -W5 -c1 ip.yunohost.org >/dev/null 2>&1 || test -e /var/run/moulinette_yunohost.lock || yunohost dyndns update >> /dev/null`
Body: `Domain 'sylvester.nohost.me' unknown`

This domain does not show up in my list of domains because I deleted it a while ago:
```
# yunohost domain list
domains: 
  - thejoyofcoding.nl
  - blog.thejoyofcoding.nl
  - home-assistant.thejoyofcoding.nl
  - kuma.thejoyofcoding.nl
  - nitter.thejoyofcoding.nl
  - yabs.dev
  - blog.yabs.dev
  - kuma.yabs.dev
  - nitter.yabs.dev
main: thejoyofcoding.nl
```

### Context

- Hardware: *Raspberry Pi at home*
- YunoHost version: 11.1.17
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### To reproduce

Not applicable

### Expected behavior

I expect yunohost to not try to update a domain that no longer exists

### Logs

https://paste.yunohost.org/raw/nuxotegiso

![image](https://user-images.githubusercontent.com/39904003/233070616-1a85c614-3462-4596-9b74-035748e95f6d.png)

**Comment by alexAubin** [comment]
Closing because we're lacking info to know what this is happening, this is supposed to be already handled by https://github.com/YunoHost/yunohost/commit/cb835a2d6ba73965b26cdbf019faa6cc063c1e85 ... maybe the regen-conf was complaining that the file got manually modified (maybe to tweak the frequency?) and did not auto-remove it
