### ISSUE TITLE
Some Text is not Translatable [WebAdmin]

### ISSUE THREAD

**Issue by the7thNightmare** [YunoHost/issues#2194]
> [In language other than English]

Go to the WebAdmin, go to the Groups and Permissions, click on `add a permission` or `add an user`, it is "*** permission/user" next to the search bar, the permission/user is not translated.

It seems that this [line](https://github.com/YunoHost/yunohost-admin/blob/dev/app/src/i18n/locales/en.json#L595) that causes it. In that line, it is `Search for {items}...`, with the `items` variable are not translated too with the rest of the line. It carries on to the other languages.

**Comment by Axolotle** [comment]
fixed in https://github.com/YunoHost/yunohost-admin/pull/582
