### ISSUE TITLE
Apps documentation pages fail with server error

### ISSUE THREAD

**Issue by gadgetb0y** [YunoHost/issues#2195]
### Describe the bug

Attempting to load documentation for the Ghost application fails with a server error:

Server Error
Sorry, something went terribly wrong!

E_NOTICE - Trying to access array offset on value of type bool
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

### Context

[yunohost.org
](https://yunohost.org/en/app_ghost)

### To reproduce

Load URL.

### Expected behavior

View admin docs for app_ghost

### Logs

NA

**Comment by securegh** [comment]
This bug is happening on multiple applications doc Adguard, Grav, zabbix ... maybe more, did anyone look in to this issue?

**Comment by orhtej2** [comment]
The mystery thickens?
I've cloned https://github.com/YunoHost/doc, build Docker image and run it locally with provided `docker-compose.yaml`.

- http://localhost:8000/en/app_rainloop works as expected.
- https://yunohost.org/en/app_rainloop displays originally reported issue.

Perhaps official instance is pending some updates?

**Comment by tituspijean** [comment]
It looks like it was a bug with a Grav plugin, External Links. Since it’s only cosmetic, I have disabled it.
