### ISSUE TITLE
Jitsi: Connection refused, cause: metronome reactivated

### ISSUE THREAD

**Issue by der-bender** [YunoHost/issues#2196]
### Describe the bug

Jitsi is accessible, but it is not possible to start a video conference. The connection always gets disconnected, message "You have been disconnected", then it is offered to wait and reconnect but the problem persits - no connection possible.

### Context

- VPS at Contabo
- YunoHost version: 11.1.19
- I have access to my server: *through SSH, through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### To reproduce

Try to start a jitsi video conference. 

### Expected behavior

The video conference starts.

### Solution

Found out that an update seems to have re-enabled metronome. Metronome was running at the same time as prosody. I stopped metronome and disabled autostart, since then conferences can be started again and run normally.
I did not activate metronome manually, it must have happened as part of an update.

**Comment by alexAubin** [comment]
Closing because idk what to do about this apart from the fact that we're removing the Depends relation in our debian package as part of Bookworm (or maybe it was already in Recommends in bullseye ?)
