### ISSUE TITLE
Applications list doesn't show up in Webadmin since last system update / upgrade .

### ISSUE THREAD

**Issue by remy131** [YunoHost/issues#2199]
### Describe the bug

Applications list doesn't show up in Webadmin since last system update / upgrade .

![Capture du 2023-06-05 22-59-50](https://github.com/YunoHost/issues/assets/135656564/f039701b-55d4-4a82-a0d0-955a587e64af)

Through CLI it does hitting "yunohost apps list "

I've tried to upgrade hiting : "yunohost tools upgrade apps --debug" it return errors on versions .

![Capture du 2023-06-05 22-53-31](https://github.com/YunoHost/issues/assets/135656564/de18681d-2982-4af3-993f-0d20732757e7)

modules versions : 

![Capture du 2023-06-05 22-54-38](https://github.com/YunoHost/issues/assets/135656564/47c28e19-ec28-4465-9dda-b46d61ab2a43)

### Context

- Hardware: Old laptop or computer
- YunoHost version: 11.1.20
- I have access to my server:  Through SSH | through the webadmin | direct access via keyboard / screen | 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?:  no
- Using, or trying to install package version/branch:
- If upgrading, current YunoHost version:

**Comment by tituspijean** [comment]
Might be related to https://github.com/YunoHost/yunohost/pull/1655 ?

**Comment by alexAubin** [comment]
cf https://forum.yunohost.org/t/failed-to-read-info-for-invalid-version-ynh/25050
