### ISSUE TITLE
API is down and I can't start it

### ISSUE THREAD

**Issue by Ciechom** [YunoHost/issues#2203]
After newest yunohost update, the API is down and I get an error:

![image](https://github.com/YunoHost/issues/assets/6024778/23c2947d-1846-4169-92b5-1e193b4108a7)

In polish, the red error says: API is not responding. Maybe yunohost-api is turned off or was restarted?

this is the systemctl status yunohost-api:

![image](https://github.com/YunoHost/issues/assets/6024778/60d405d0-e051-40ad-84c1-c8b70f919359)

I can send logs, but I don't know where to look for appropriate logs.

BTW, while the admin interface is not working, the user interface is working.

**Comment by Ciechom** [comment]
There is also a problem with yunohost-firewall that I just discovered.

![image](https://github.com/YunoHost/issues/assets/6024778/370228ca-57ca-4d8f-ae87-f841a5f63c13)

Maybe they are connected somehow?

**Comment by alexAubin** [comment]
Can you share proper logs using : 

 `journalctl -u yunohost-api -n 50 --no-hostname --no-pager`

 `journalctl -u yunohost-firewall -n 50 --no-hostname --no-pager`

**Comment by Ciechom** [comment]
API:

-- Journal begins at Mon 2023-06-12 10:47:34 CEST, ends at Thu 2023-06-15 20:21:52 CEST. --
cze 15 20:21:41 yunohost-api[3681]:     dictConfigClass(config).configure()
cze 15 20:21:41 yunohost-api[3681]:   File "/usr/lib/python3.9/logging/config.py", line 571, in configure
cze 15 20:21:41 yunohost-api[3681]:     raise ValueError('Unable to configure handler '
cze 15 20:21:41 yunohost-api[3681]: ValueError: Unable to configure handler 'api'
cze 15 20:21:41 systemd[1]: yunohost-api.service: Main process exited, code=exited, status=1/FAILURE
cze 15 20:21:41 systemd[1]: yunohost-api.service: Failed with result 'exit-code'.
cze 15 20:21:46 systemd[1]: yunohost-api.service: Scheduled restart job, restart counter is at 45.
cze 15 20:21:46 systemd[1]: Stopped YunoHost API Server.
cze 15 20:21:46 systemd[1]: Started YunoHost API Server.
cze 15 20:21:47 yunohost-api[3727]: Traceback (most recent call last):
cze 15 20:21:47 yunohost-api[3727]:   File "/usr/lib/python3.9/logging/config.py", line 389, in resolve
cze 15 20:21:47 yunohost-api[3727]:     found = getattr(found, frag)
cze 15 20:21:47 yunohost-api[3727]: AttributeError: module 'moulinette.interfaces' has no attribute 'api'
cze 15 20:21:47 yunohost-api[3727]: During handling of the above exception, another exception occurred:
cze 15 20:21:47 yunohost-api[3727]: Traceback (most recent call last):
cze 15 20:21:47 yunohost-api[3727]:   File "/usr/lib/python3.9/logging/config.py", line 564, in configure
cze 15 20:21:47 yunohost-api[3727]:     handler = self.configure_handler(handlers[name])
cze 15 20:21:47 yunohost-api[3727]:   File "/usr/lib/python3.9/logging/config.py", line 722, in configure_handler
cze 15 20:21:47 yunohost-api[3727]:     klass = self.resolve(cname)
cze 15 20:21:47 yunohost-api[3727]:   File "/usr/lib/python3.9/logging/config.py", line 391, in resolve
cze 15 20:21:47 yunohost-api[3727]:     self.importer(used)
cze 15 20:21:47 yunohost-api[3727]:   File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 12, in <module>
cze 15 20:21:47 yunohost-api[3727]:     from gevent import sleep
cze 15 20:21:47 yunohost-api[3727]:   File "/usr/lib/python3/dist-packages/gevent/__init__.py", line 86, in <module>
cze 15 20:21:47 yunohost-api[3727]:     from gevent._hub_local import get_hub
cze 15 20:21:47 yunohost-api[3727]:   File "/usr/lib/python3/dist-packages/gevent/_hub_local.py", line 101, in <module>
cze 15 20:21:47 yunohost-api[3727]:     import_c_accel(globals(), 'gevent.__hub_local')
cze 15 20:21:47 yunohost-api[3727]:   File "/usr/lib/python3/dist-packages/gevent/_util.py", line 148, in import_c_accelcze 15 20:21:47 yunohost-api[3727]:     mod = importlib.import_module(cname)
cze 15 20:21:47 yunohost-api[3727]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
cze 15 20:21:47 yunohost-api[3727]:     return _bootstrap._gcd_import(name[level:], package, level)
cze 15 20:21:47 yunohost-api[3727]:   File "src/gevent/_hub_local.py", line 1, in init gevent._gevent_c_hub_local
cze 15 20:21:47 yunohost-api[3727]: ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 40 from PyObject
cze 15 20:21:47 yunohost-api[3727]: The above exception was the direct cause of the following exception:
cze 15 20:21:47 yunohost-api[3727]: Traceback (most recent call last):
cze 15 20:21:47 yunohost-api[3727]:   File "/usr/bin/yunohost-api", line 52, in <module>
cze 15 20:21:47 yunohost-api[3727]:     yunohost.api(debug=opts.debug, host=opts.host, port=opts.port)
cze 15 20:21:47 yunohost-api[3727]:   File "/usr/lib/python3/dist-packages/yunohost/__init__.py", line 53, in api
cze 15 20:21:47 yunohost-api[3727]:     init_logging(interface="api", debug=debug)
cze 15 20:21:47 yunohost-api[3727]:   File "/usr/lib/python3/dist-packages/yunohost/__init__.py", line 183, in init_logging
cze 15 20:21:47 yunohost-api[3727]:     configure_logging(logging_configuration)
cze 15 20:21:47 yunohost-api[3727]:   File "/usr/lib/python3/dist-packages/moulinette/utils/log.py", line 67, in configure_logging
cze 15 20:21:47 yunohost-api[3727]:     dictConfig(logging_config)
cze 15 20:21:47 yunohost-api[3727]:   File "/usr/lib/python3.9/logging/config.py", line 809, in dictConfig
cze 15 20:21:47 yunohost-api[3727]:     dictConfigClass(config).configure()
cze 15 20:21:47 yunohost-api[3727]:   File "/usr/lib/python3.9/logging/config.py", line 571, in configure
cze 15 20:21:47 yunohost-api[3727]:     raise ValueError('Unable to configure handler '
cze 15 20:21:47 yunohost-api[3727]: ValueError: Unable to configure handler 'api'
cze 15 20:21:47 systemd[1]: yunohost-api.service: Main process exited, code=exited, status=1/FAILURE
cze 15 20:21:47 systemd[1]: yunohost-api.service: Failed with result 'exit-code'.

Firewall:

-- Journal begins at Mon 2023-06-12 10:47:34 CEST, ends at Thu 2023-06-15 20:22:29 CEST. --
cze 15 20:17:40 yunohost[749]:     dictConfigClass(config).configure()
cze 15 20:17:40 yunohost[749]:   File "/usr/lib/python3.9/logging/config.py", line 571, in configure
cze 15 20:17:40 yunohost[749]:     raise ValueError('Unable to configure handler '
cze 15 20:17:40 yunohost[749]: ValueError: Unable to configure handler 'api'
cze 15 20:17:40 systemd[1]: yunohost-firewall.service: Main process exited, code=exited, status=1/FAILURE
cze 15 20:17:40 systemd[1]: yunohost-firewall.service: Failed with result 'exit-code'.
cze 15 20:17:40 systemd[1]: Failed to start YunoHost Firewall.
cze 15 20:18:15 systemd[1]: Starting YunoHost Firewall...
cze 15 20:18:16 yunohost[1716]: Traceback (most recent call last):
cze 15 20:18:16 yunohost[1716]:   File "/usr/lib/python3.9/logging/config.py", line 389, in resolve
cze 15 20:18:16 yunohost[1716]:     found = getattr(found, frag)
cze 15 20:18:16 yunohost[1716]: AttributeError: module 'moulinette.interfaces' has no attribute 'api'
cze 15 20:18:16 yunohost[1716]: During handling of the above exception, another exception occurred:
cze 15 20:18:16 yunohost[1716]: Traceback (most recent call last):
cze 15 20:18:16 yunohost[1716]:   File "/usr/lib/python3.9/logging/config.py", line 564, in configure
cze 15 20:18:16 yunohost[1716]:     handler = self.configure_handler(handlers[name])
cze 15 20:18:16 yunohost[1716]:   File "/usr/lib/python3.9/logging/config.py", line 722, in configure_handler
cze 15 20:18:16 yunohost[1716]:     klass = self.resolve(cname)
cze 15 20:18:16 yunohost[1716]:   File "/usr/lib/python3.9/logging/config.py", line 391, in resolve
cze 15 20:18:16 yunohost[1716]:     self.importer(used)
cze 15 20:18:16 yunohost[1716]:   File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 12, in <module>
cze 15 20:18:16 yunohost[1716]:     from gevent import sleep
cze 15 20:18:16 yunohost[1716]:   File "/usr/lib/python3/dist-packages/gevent/__init__.py", line 86, in <module>
cze 15 20:18:16 yunohost[1716]:     from gevent._hub_local import get_hub
cze 15 20:18:16 yunohost[1716]:   File "/usr/lib/python3/dist-packages/gevent/_hub_local.py", line 101, in <module>
cze 15 20:18:16 yunohost[1716]:     import_c_accel(globals(), 'gevent.__hub_local')
cze 15 20:18:16 yunohost[1716]:   File "/usr/lib/python3/dist-packages/gevent/_util.py", line 148, in import_c_accel
cze 15 20:18:16 yunohost[1716]:     mod = importlib.import_module(cname)
cze 15 20:18:16 yunohost[1716]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
cze 15 20:18:16 yunohost[1716]:     return _bootstrap._gcd_import(name[level:], package, level)
cze 15 20:18:16 yunohost[1716]:   File "src/gevent/_hub_local.py", line 1, in init gevent._gevent_c_hub_local
cze 15 20:18:16 yunohost[1716]: ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 40 from PyObject
cze 15 20:18:16 yunohost[1716]: The above exception was the direct cause of the following exception:
cze 15 20:18:16 yunohost[1716]: Traceback (most recent call last):
cze 15 20:18:16 yunohost[1716]:   File "/usr/bin/yunohost", line 77, in <module>
cze 15 20:18:16 yunohost[1716]:     yunohost.cli(
cze 15 20:18:16 yunohost[1716]:   File "/usr/lib/python3/dist-packages/yunohost/__init__.py", line 35, in cli
cze 15 20:18:16 yunohost[1716]:     init_logging(interface="cli", debug=debug, quiet=quiet)
cze 15 20:18:16 yunohost[1716]:   File "/usr/lib/python3/dist-packages/yunohost/__init__.py", line 168, in init_logging
cze 15 20:18:16 yunohost[1716]:     configure_logging(logging_configuration)
cze 15 20:18:16 yunohost[1716]:   File "/usr/lib/python3/dist-packages/moulinette/utils/log.py", line 67, in configure_logging
cze 15 20:18:16 yunohost[1716]:     dictConfig(logging_config)
cze 15 20:18:16 yunohost[1716]:   File "/usr/lib/python3.9/logging/config.py", line 809, in dictConfig
cze 15 20:18:16 yunohost[1716]:     dictConfigClass(config).configure()
cze 15 20:18:16 yunohost[1716]:   File "/usr/lib/python3.9/logging/config.py", line 571, in configure
cze 15 20:18:16 yunohost[1716]:     raise ValueError('Unable to configure handler '
cze 15 20:18:16 yunohost[1716]: ValueError: Unable to configure handler 'api'
cze 15 20:18:16 systemd[1]: yunohost-firewall.service: Main process exited, code=exited, status=1/FAILURE
cze 15 20:18:16 systemd[1]: yunohost-firewall.service: Failed with result 'exit-code'.
cze 15 20:18:16 systemd[1]: Failed to start YunoHost Firewall.

**Comment by alexAubin** [comment]
Could it be that you manually installed some stuff on your server such as a custom python version or whichever python-related thing ?

**Comment by Ciechom** [comment]
Yes, I installed platypush with command: 
pip3 install 'platypush[rss]'

**Comment by alexAubin** [comment]
Well installing stuff in global context has a tendency to fuck up stuff because this create version inconsistencies between the different python packages installed on the system between `pip` and `apt` ...

**Comment by Ciechom** [comment]
Damn, didn't know that. Is there any way to fix this?

**Comment by alexAubin** [comment]
I guess you can try to uninstall stuff, using `pip uninstall <package>`, but just `pip uninstall platypushwhatever` won't uninstall the problematic dependencies, so you gotta try to find the problematic dependency in `ls /usr/local/lib/python3.*/dist-packages/` and uninstall it ...

**Comment by Ciechom** [comment]
Is there a list of packages that I can compare the result of this command that should be there?

**Comment by Ciechom** [comment]
Ok, it looks like admin interface is working again, but it takes me to postinstall when in fact there should already be installed config.

The error I get now is:

It looks like you're trying to re-postinstall a system that was already working previously ... If you recently had some bug or issues with your installation, please first discuss with the team on how to fix the situation instead of savagely re-running the postinstall ...

**Comment by alexAubin** [comment]
Well yeah, it looks like you might have savagely uninstalled YunoHost .. so it looks like maybe you did not just install some stuff with `pip` but also triggered some apt command which warned you that you were about to unintall YunoHot and explicitly asked you to confirm "Yes, do as I say!" after some warning that it would probably break an epic amount of stuff

**Comment by Ciechom** [comment]
Well, that's true.

**Comment by Ciechom** [comment]
It happened so fast, my ADHD brain tried to fix it asap, and I didn't quite read the warning, but it seems that: 

touch /etc/yunohost/installed

"fixed" postinstall problem.
