### ISSUE TITLE
autoupdate_app_sources should support downloading releases

### ISSUE THREAD

**Issue by rndmh3ro** [YunoHost/issues#2205]
The autoupdate_app_sources script is great!
However it does not always work as intended:

The upstream app invoiceninja provides two assets:
- the sourcecode located at https://github.com/invoiceninja/invoiceninja/archive/refs/tags/v5.6.3.zip
- the prebuilt release (with all needed assets included) at https://github.com/invoiceninja/invoiceninja/releases/download/v5.6.3/invoiceninja.zip

When the autoupdater runs, it adds the first url to the manifest.toml, but it should use the second one. See an example here: https://github.com/YunoHost-Apps/invoiceninja5_ynh/pull/111/files#diff-06ac558c9cfca9e31a9a235f18d98e6d0c3bfee8bee0088108a29f2c60b318e3L58-L60

The updater should support downloading the release-artifact.

**Comment by alexAubin** [comment]
It already does :wink: 

You should add this line : 

`autoupdate.asset = "invoiceninja.zip"`

after the strategy line

(and also support regexes and multiarch, cf for example https://github.com/YunoHost-Apps/zwave-js-ui_ynh/blob/testing/manifest.toml#L54 )

**Comment by rndmh3ro** [comment]
Actually I did this already but forgot to mention.
The problem is that this artifact (https://github.com/invoiceninja/invoiceninja/archive/refs/tags/v5.6.3/invoiceninja.zip) is different from this (https://github.com/invoiceninja/invoiceninja/releases/download/v5.6.3/invoiceninja.zip).

**Comment by alexAubin** [comment]
I don't understand : with the proposed syntax, it will pick up the file in the release asset (ie the second link you mention), not just the tag's source code one

**Comment by rndmh3ro** [comment]
Okay, I will try again and report back. Thanks so far!

**Comment by alexAubin** [comment]
smol bump ?

**Comment by rndmh3ro** [comment]
I have to wait for the next release happening to check if it works. I wrongly added the setting to the main branch but it seems that the updater uses the testing branch.. https://github.com/YunoHost-Apps/invoiceninja5_ynh/blob/testing/manifest.toml

**Comment by rndmh3ro** [comment]
Okay it's working. Thank you!
