### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost/issues#2206]
### Describe the bug

System upgrading fails both in the webapp and via terminal (diagnosis tool shows no problems)

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.1.21.4
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### To reproduce

`sudo yunohost tools update`

### Expected behavior

Smooth update process

### Logs

```
Unable to update the cache of APT (Debian's package manager). Here is a dump of the sources.list lines, which might help identify problematic lines:
sources.list:deb http://asi-fs-d.contabo.net/debian bullseye main non-free contrib
sources.list:deb-src http://asi-fs-d.contabo.net/debian bullseye main non-free contrib
sources.list:deb http://security.debian.org/debian-security bullseye-security main contrib non-free
sources.list:deb-src http://security.debian.org/debian-security bullseye-security main contrib non-free
sources.list:deb http://asi-fs-d.contabo.net/debian bullseye-updates main contrib non-free
sources.list:deb-src http://asi-fs-d.contabo.net/debian bullseye-updates main contrib non-free
sources.list.d/extra_php_version.list:deb https://packages.sury.org/php/ bullseye main
sources.list.d/yunohost.list:deb [signed-by=/usr/share/keyrings/yunohost-archive-keyring.gpg] http://forge.yunohost.org/debian/ bullseye stable
```

**Comment by alexAubin** [comment]
We need the actual error log which should be somewhere in your interface ... or you can run `sudo apt update` manually from the command line

**Comment by xplosionmind** [comment]
Thanks @alexAubin! By running `sudo apt update && sudo apt upgrade -y`, actually the issue does not persist anymore.
