### ISSUE TITLE
Backup list page gives 504 error

### ISSUE THREAD

**Issue by BishopGreer** [YunoHost/issues#2209]
### Context

- Hardware: *VPS bought online /
- YunoHost version: 11.1.21.4
- I have access to my server: *Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no 
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current YunoHost version: 

### To reproduce
Go to backup.
Click local backup
Blank screen appears
Wait forever
Get 500 error message

### Expected behavior

You should get a list of backup files. 

### Logs
No log is generated.
![IMG_1037](https://github.com/YunoHost/issues/assets/121546259/5fd582bd-9c17-4078-a57c-78aee5da7658)

**Comment by alexAubin** [comment]
Can you provide more context such as : do you happen to have create any super huge backup recently, or anything loosely related to backup ?

What if you try to run `yunohost backup list` from the command line ?

**Comment by BishopGreer** [comment]
I have not created any new backups. When I run that command from the command line, I get a list of backups.

**Comment by BishopGreer** [comment]
> 

Your question got me thinking. I deleted one of the backups and now the page displays fine. Not sure why that is, but at least it works now.
