### ISSUE TITLE
Local IP address discovery

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#221]
###### Original Redmine Issue: [221](https://dev.yunohost.org/issues/221)

Author Name: **Anonymous**

---

Add a system to find the private ip.
I think it should be possible to add a script when the network goes up which "pings" an external server (maybe ping.yunohost.org).
Then, a user on his computer on the same lan goes to http://ping.yunohost.org . The server could show the ip of yunohost which come from the same wan ip.
It could be a bit of a privacy problem so maybe add this as an opt-in option.
It will be way easier for users to find the ip of their internet cube.

**Comment by Psycojoker** [comment]
I know that we already have code for that internally, I don't know if it's worth it to expose it.

I'm closing this then, reopen if needed.
