### ISSUE TITLE
Unowned /etc/resolv.dnsmasq.conf

### ISSUE THREAD

**Issue by cristianrz** [YunoHost/issues#2216]
### Describe the bug

The file /etc/resolv.dnsmasq.conf seems to be getting owned by the user with UID 644, which does not exist on my YunoHost install. I keep chowning it back to root but it goes back to 644.

### Context

- Hardware: Not relevant
- YunoHost version: 11.1.21.4
- I have access to my server: SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: N/A
- If upgrading, current YunoHost version: N/A

### To reproduce

```bash
# ls -l /etc/resolv.dnsmasq.conf 
-rw-r--r-- 1 644 root 23 Jul  1 00:00 /etc/resolv.dnsmasq.conf
# chown -v root:root /etc/resolv.dnsmasq.conf 
changed ownership of '/etc/resolv.dnsmasq.conf' from 644:root to root:root

# # [after a couple of days]

# ls -l /etc/resolv.dnsmasq.conf 
-rw-r--r-- 1 644 root 23 Jul  3 00:00 /etc/resolv.dnsmasq.conf
```

### Expected behavior

I would expect this to either be owned by root or by an existing user.

### Logs

Not sure which logs I would send

**Comment by alexAubin** [comment]
Fixed in https://github.com/YunoHost/yunohost/commit/af93524c362abf67e23b81457215157081fd964d, thanks for reporting /o\
