### ISSUE TITLE
Yunohost does not allow visitors to create accounts!

### ISSUE THREAD

**Issue by Mike6547** [YunoHost/issues#2218]
Hello, I've been trying for several days to allow visitors to manually create accounts on my YunoHost instance, but I haven't found any solution. Can you help me?

**Comment by alexAubin** [comment]
This is clearly not a bug but a feature request

Also duplicate, cf https://github.com/YunoHost/issues/issues/1677 

TL;DR : this is not an easy feature, it's in progress but requires major refactorings, cf for example https://github.com/YunoHost/yunohost/pull/1387
