### ISSUE TITLE
donate.yunohost.org does not work for recurring donations

### ISSUE THREAD

**Issue by MaxValue** [YunoHost/issues#2219]
### Describe the bug

I wanted to start donating regularly to yunohost. I never donated before. I clicked the "Donate" link on the frontpage (yunohost.org) and got to donate.yunohost.org There I specified a montly amount of 5 € and clicked "Donate". Nothing happened.

### Context

- Hardware: Not applicable
- YunoHost version: Not applicable
- I have access to my server: Not applicable
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: Not applicable
- Using, or trying to install package version/branch: Not applicable
- If upgrading, current YunoHost version: Not applicable

### To reproduce

   1. *Go to donate.yunohost.org*
   2. *Fill in the form, be sure to select "monthly"*
   3. *Click Donate*
   4. *Nothing happens*

### Expected behavior

You should be redirected to the Stripe payment screen

### Logs

The browser console shows this when selecting a recurring donation:
```json
{"error":"Request req_UK2CuWWBLCdyTv: No such price: 'price_1IN0HVE7vOmTpJBi8mjmhic4,one_time'"}
```

### Notes

- [ ] Would there be any possibility that you can have a list of donation links somewhere (like for open collective, kofi, liberapay)?

**Comment by alexAubin** [comment]
Hmmm that could be because there was some issue on our infrastructure today ... Or did you try 10 minutes ago ?

**Comment by tituspijean** [comment]
I can replicate the issue, this is not infrastructure-related.

---

Fixed, the configuration had a typo. (extra `,one_time` at the end of the recurring donation key)
