### ISSUE TITLE
Upgrade not working on webadmin

### ISSUE THREAD

**Issue by newbee2011** [YunoHost/issues#2222]
### Describe the bug

Trying to update/upgrade on the webadmin it says  error: 400 bad request, action: "PUT" /yunohost/api/upgrade/system;
Further is mentioned on detailed error message that I can't do that because of broken dpkg/apt. It is the second time that this bug/issue happened.
Last time I could do tbe update/upgrade through direct access to the server running without issues or errors.

### Context

- Hardware: *Old laptop*
- YunoHost version: 11.1.22
- I have access to my server: *Through the webadmin | direct access via keyboard / screen*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain: *Nothing*
- Using, or trying to install package version/branch:
- If upgrading, current YunoHost version: *11.1.22 and version before*

### To reproduce

- *If you used the webadmin, please perform the equivalent command from the CLI first.* - did this at the upgrade before without errors or issues
- *If the error occurs in your browser, explain what you did:*
   1. *Go to 'WebAdmin then Login as Admin'*
   2. *Click on 'system upgrade and do upgrade'*
   3. *Scroll down to 'nothing'*
   4. *See error - as describe in the first*

### Logs

No relevant Log provided

![Screenshot_20230724-234833.png](https://github.com/YunoHost/issues/assets/5055576/a38e95b7-732e-4f5f-b237-4399dd519038)

**Comment by alexAubin** [comment]
Then what do the proposed commands return ...

**Comment by newbee2011** [comment]
> Then what do the proposed commands return ...

Hello Alex

I didn't try it. The last time I tried with direct access "sudo apt update && sudo apt upgrade -y" and it worked as expected. For now I try it when I have a little spare time to do that.

**Comment by alexAubin** [comment]
Then closing because this is not an actual issue, this is the expected behavior. Something broke apt/dpkg at some point, therefore apt/dpkg commands can't be ran until this is fixed. The real question is what broke apt/dpkg in the first place. Closing until more feedback is available

**Comment by newbee2011** [comment]
> Then closing because this is not an actual issue, this is the expected behavior. Something broke apt/dpkg at some point, therefore apt/dpkg commands can't be ran until this is fixed. The real question is what broke apt/dpkg in the first place. Closing until more feedback is available

That's indeed the question. What broke apt/dpkg? I am running basic installation without additional apps and doing only updates/upgrades. Normally from webadmin I use at Ghostery browser on Android smartphone with Android 12. And before the problem was showing up at the last upgrade webadmin update was doing as expected.

**Comment by alexAubin** [comment]
We can't magically know .. Just run the proposed commands and report back ...

**Comment by newbee2011** [comment]
> We can't magically know .. Just run the proposed commands and report back ...

As I sad I do this when I have enough free time to do that. Not all people working from 9 tp 5 from monday to friday and have time at the weekend for such things. So a little more patience could be a nice thing to get more informations.
And why is APT working normal on CLI with direct access but failed from webadmin? So there must be some kind of issue, maybe with webadmin? Or is it, for what reason ever, not all the time working when used from Android phone? Same error at IPhone too? Lot's of questions to think about it....

**Comment by newbee2011** [comment]
> We can't magically know .. Just run the proposed commands and report back ...

Here they are.

![IMG_20230726_140038.jpg](https://github.com/YunoHost/issues/assets/5055576/3d71dad0-c651-4df5-a26a-af542c2f6ace)

![IMG_20230726_135854.jpg](https://github.com/YunoHost/issues/assets/5055576/04d2e575-0c99-4ec3-8060-b10c28396c8a)

**Comment by alexAubin** [comment]
You ran out of space in `/boot/` and therefore apt is unable to install new kernels. The usual workaround about this is to delete the old, unecessary kernels. For example apt is informing that 3 of them are not needed anymore, though let's keep the `-21-` just in case the `-23-` ain't properly installed yet : 

```
sudo apt remove linux-image-5.10.0-16-amd64 linux-image-5.10.0-20-amd64
```

**Comment by newbee2011** [comment]
> You ran out of space in `/boot/` and therefore apt is unable to install new kernels. The usual workaround about this is to delete the old, unecessary kernels. For example apt is informing that 3 of them are not needed anymore, though let's keep the `-21-` just in case the `-23-` ain't properly installed yet : 
> 
> ```
> sudo apt remove linux-image-5.10.0-16-amd64 linux-image-5.10.0-20-amd64
> ```

Thank you very much. I try it next time having free time.
