### ISSUE TITLE
Webapp manifest should always include `init_main_permission`

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#2223]
With the introduction of packaging v2, the common custom of giving `all_users` group access to the newly installed apps has stopped.

Now, if an app does not specifically ask for a user or group to grant them access upon installation, then administrators need to manually give themselves access to the app. This is a frustrating, confusing, and needless additional step.

Possible solution: have the linter warn about missing `init_main_permission` question if the app is a webapp.

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/package_linter/pull/115
