### ISSUE TITLE
Retrieve app information for a single app efficiently via CLI

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost/issues#2224]
Hi,
I need to retrieve app information for a single app on the yunohost server. Right now I use the following API call:
```
domain.tld/apps/code-server?full=true 
```

However, this is not efficient as I need to do authentication although I'm already on the server. So, I'd prefer to retrieve single app info via CLI. I was told that there is the following yunohost command.

```
yunohost app catalog -f
```
However, this returns the whole app catalog and I'd have to parse it. That's not efficient either as I just want to have the info for a single app.

So, what I'd imagine is something like

```
yunohost app catalog -name -f
```

**Comment by alexAubin** [comment]
Eeeh why not just use `yunohost app info <appname> --full` ? That should be equivalent to the webapi call you mention

**Comment by tituspijean** [comment]
It does not work if the app is not installed. ;)

**Comment by alexAubin** [comment]
Ah yes indeed ...

Well you can use `yunohost app catalog --full --output-as json | jq '.apps.nextcloud'` to easily parse it, dunno if that fits the original need ...

**Comment by alexAubin** [comment]
Closing because the proposed command apparently address the issue but since it's not clear "why" / what this is needed for it's not clear if there's a reason to implement something related to this or not ...
