### ISSUE TITLE
Allow hooks in any programming language

### ISSUE THREAD

**Issue by selfhoster1312** [YunoHost/issues#2228]
In #911 it was made possible to run hooks in Python which is nice. However, i may want to write hooks in other languages . Since the hook success is based on return code, and only the output is looked at, it makes sense to accept any program the machine can run and not just bash/python.

I encountered this problem when trying to write a hook in Rust :)

**Comment by alexAubin** [comment]
Closing because i don't know what would be the killer-feature of being able to write something in other than bash that would justify spending time on this ...
