### ISSUE TITLE
Add UnifiedPush module to Metronome

### ISSUE THREAD

**Issue by xmgz** [YunoHost/issues#2231]
Evaluate to add and activate this Prosody module

https://modules.prosody.im/mod_unified_push

in YNH we have [NTFY](https://github.com/YunoHost-Apps/ntfy_ynh) as [UnifiedPush](https://unifiedpush.org/) server. It is (ATM) the most complete solution but as Metronome (jabber server) is installed by default it would be very convenient to have _UnifiedPush_ available also by default as it consumes low resources and needs barely no configuration in order to work. Not as featured and configurable as NTFY-app, but convenient in most cases.

As Metronome is Prosody based, I've been trying myself to install this module and activate it, without success due my limitations in the matter.

So I want to suggest including this module at least as an option (as other modules in the config) with (optionally?) some toogle in the webinterface for those who wanted this service.

I've added _mod-unified-push_ module, but it depends on other modules and **utils** for each subdomain (vjug, muc,etc)

**Eventually** I also added _util.id_, but that was all I could do (I had no real hope to do all this myself though XD, but I wanted to try)

**Logs** (this is just an extract and example of the kind of problem I faced)

```
Aug 15 11:39:48 modulemanager   error   Unable to load module 'id': /usr/lib/metronome/modules/mod_id.lua: No such file or directory
Aug 15 11:39:48 modulemanager   error   Error initializing module 'unified_push' on 'pubsub.domain.noho.st': /usr/bin/metronome:156: module 'util.id' not found:
        no field package.preload['util.id']
        no file '/usr/lib/metronome/util/id.lua'
        no file '/usr/local/share/lua/5.3/util/id.lua'
        no file '/usr/local/share/lua/5.3/util/id/init.lua'
        no file '/usr/local/lib/lua/5.3/util/id.lua'
        no file '/usr/local/lib/lua/5.3/util/id/init.lua'
        no file '/usr/share/lua/5.3/util/id.lua'
        no file '/usr/share/lua/5.3/util/id/init.lua'
        no file '/usr/lib/metronome/util/id.so'
        no file '/usr/local/lib/lua/5.3/util/id.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.3/util/id.so'
        no file '/usr/lib/lua/5.3/util/id.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
        no file '/usr/lib/metronome/util.so'
        no file '/usr/local/lib/lua/5.3/util.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.3/util.so'
        no file '/usr/lib/lua/5.3/util.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
stack traceback:
        /usr/lib/metronome/core/modulemanager.lua:31: in function </usr/lib/metronome/core/modulemanager.lua:31>
        [C]: in upvalue '_real_require'
        /usr/bin/metronome:156: in function 'require'
        /usr/lib/metronome/modules/mod_unified_push.lua:6: in main chunk
        (...tail calls...)
        [C]: in function 'xpcall'
        /usr/lib/metronome/core/modulemanager.lua:31: in upvalue 'pcall'
        /usr/lib/metronome/core/modulemanager.lua:163: in upvalue 'do_load_module'
        /usr/lib/metronome/core/modulemanager.lua:240: in function 'core.modulemanager.load'
        /usr/lib/metronome/core/modulemanager.lua:61: in function 'core.modulemanager.load_modules_for_host'
        /usr/lib/metronome/util/events.lua:67: in field 'fire_event'
        /usr/lib/metronome/core/hostmanager.lua:120: in function 'core.hostmanager.activate'
        /usr/lib/metronome/core/hostmanager.lua:52: in field '?'
        /usr/lib/metronome/util/events.lua:67: in field 'fire_event'
        /usr/bin/metronome:290: in function 'prepare_to_start'
        /usr/bin/metronome:387: in main chunk
        [C]: in ?
```

Please just study this option. It's hard to call it _request_, I prefer _under consideration_. 

**Thank you.**

**Comment by alexAubin** [comment]
Closing because metronome is to become an app in Bookworm / YunoHost 12.x : https://github.com/YunoHost-Apps/metronome_ynh
