### ISSUE TITLE
Add details about backup task in logs list

### ISSUE THREAD

**Issue by olberger** [YunoHost/issues#2232]
When backups are enabled (here, using borg app), the logs list (/admin/#/tools/logs) lists many consecutive "Create a backup archive".

It would be great to have a bit more details about these, in case of failure, for instance, to help identify more quickly why something that used to work suddenly fails, for instance.

Hope this sounds reasonable and not to hard to implement.

Thanks in advance.

**Comment by alexAubin** [comment]
Sounds like a request for borg_ynh rather than yunohost core
