### ISSUE TITLE
admin Diagnosis: reverse DNS check should be case-insensitive

### ISSUE THREAD

**Issue by abochmann** [YunoHost/issues#2235]
### Describe the bug

The reverse DNS check in YunoHost's setup Diagnosis panel is case-sensitive and reports "_Reverse DNS is not correctly configured for IPv4. Some emails may fail to get delivered or be flagged as spam._" when forward and reverse lookup results have different capitalization.

Comparisons on DNS labels are supposed to be case-insensitive, as clarified in https://datatracker.ietf.org/doc/html/rfc4343#section-3

> Current reverse DNS: YunoHost.example.COM
> Expected value: yunohost.example,com

### Context

- YunoHost version:  11.2.3

### To reproduce

Configure forward and reverse lookup for a domain used by a YunoHost installation with different capitalization, run Diagnosis in the admin panel.

### Expected behavior

The reverse DNS check succeeds independent of case-differences in the DNS responses.

**Comment by zamentur** [comment]
This PR should fix this bug, thanks for reporting it.

**Comment by abochmann** [comment]
I quickly dropped the changed file from the PR into my YunoHost setup for a test, and it seems this selfcheck error is indeed gone.

Thanks!
