### ISSUE TITLE
portal-api: Logout doesn't work (by design)

### ISSUE THREAD

**Issue by selfhoster1312** [YunoHost/issues#2238]
**THIS IS RELATED TO THE portal-api BRANCH, NOT CURRENT DEVELOPMENT VERSION.**

Taken from here: https://github.com/YunoHost/issues/issues/2028#issuecomment-1678705852

One issue i found: when i log out the cookie isn't invalidated simply dropped from the browser. Usually upon logout cookies are denylisted so that they can't be spoofed by another client obtaining them.

This is an architectural problem with this patch as cookies are validated by SSOWat but emitted by another program (yunohost-portal-api via moulinette/interfaces/api.py) so SSOWat has no idea that a logout occurs and just validates the signature with the provided secret.

Not sure what to do with this information.

**Comment by alexAubin** [comment]
Closing because now there's proper session ids that gets invalidated upon logout i guess, cf https://github.com/YunoHost/yunohost/blob/bookworm/src/authenticators/ldap_ynhuser.py#L251
