### ISSUE TITLE
Wrong logrotate config perms

### ISSUE THREAD

**Issue by OniriCorpe** [YunoHost/issues#2242]
### Context

- YunoHost version: 11.2.4 stable
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

Some logrotate config files have wrong permissions
They’re writable by any user, so logrotate refuses using it
Maybe the logrotate helper changed its behavior, but this bug is present only on the most recent config files

Here, the first one is bad and the second one is good:
```
-rw-rw-rw- 1 root root  584  3 sept. 18:10 gotosocial__3
-rw-r--r-- 1 root root  579 21 déc.   2022 hydrogen
```

### To reproduce

```
sudo logrotate -f /etc/logrotate.d/gotosocial__3
error: Ignoring /etc/logrotate.d/gotosocial__3 because it is writable by group or others.
```

### Expected behavior

Logrotate accepts the config file and do its job

**Comment by Tagadda** [comment]
To intensify confusion, I can say that I have two apps installed between July 6th and July 28th that have similar permissions for logrotate.
And I installed gotosocial a few minutes ago and permissions was right.
