### ISSUE TITLE
letsencrypt renew fails for all domains when "metronome" isnt running

### ISSUE THREAD

**Issue by intellekta** [YunoHost/issues#2244]
Hello,
letsencrypt renew doesn't work yesterday.
But it is essential for my configured domains.

I noticed the renew for the subdomain "muc." fails.

Under Services I found that "metronome XMPP" was not started.
This always happens after a reboot, since I don't use xmpp "metronome" at all, I didn't care.

**I think it's more important to update the certificates of the user configured domains first and the "muc." domain last.**

**Comment by Tagadda** [comment]
Hi,
Can you disable XMPP feature from the domain config panel and try again ?

**Comment by intellekta** [comment]
I disable it and looking forward.

**Comment by alexAubin** [comment]
Closing because metronome is to become an app in Bookworm / YunoHost 12.x : https://github.com/YunoHost-Apps/metronome_ynh
