### ISSUE TITLE
Clean up apps documentation.

### ISSUE THREAD

**Issue by orhtej2** [YunoHost/issues#2256]
With release of new app catalogue the disparity between app documentation hosted on GitHub and displayed on yunohost.org/app_X is even more visible.

We should decide on single source of truth, and how and where to split between app overview and advanced use scenarios.

Likely we should force the apps to follow [`example_ynh`'s documentation directory structure](https://github.com/YunoHost/example_ynh/tree/master/doc) and work from there?

# Example:

## App catalogue v2: https://apps.yunohost.org/app/snappymail

![App catalogue](https://github.com/YunoHost/issues/assets/2871798/6576edf9-988a-4578-8dff-ef0ef97e1f25)

## Docs: https://yunohost.org/en/app_snappymail

![Docs](https://github.com/YunoHost/issues/assets/2871798/7f6c823d-9154-420b-97ab-ebbfd7a2632d)

## Install page: https://domain.tld/yunohost/admin/#/apps/install/snappymail

![Admin panel](https://github.com/YunoHost/issues/assets/2871798/67c3c970-6cae-4aff-9c90-8be561c27274)

## Installed overview: https://domain.tld/yunohost/admin/#/apps/snappymail/operations

![image](https://github.com/YunoHost/issues/assets/2871798/29eb4053-623e-464b-b592-15f3bd0d4117)

## GitHub README.md: https://github.com/YunoHost-Apps/snappymail_ynh/blob/master/README.md

![README](https://github.com/YunoHost/issues/assets/2871798/9a68b1a8-2db6-4f95-b041-413c1a0f99f3)

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/doc/pull/2417
