### ISSUE TITLE
Backup failure with S3 FS mounted on /home/yunohost.backup (I/O error)

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost/issues#2258]
### Describe the bug

I have a Cronjob performing a backup of my YunoHost instance every night. 

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.4
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - I am using [s3fs]() to mount the `yunohost.backup` directory on an S3 storage
 
### To reproduce

1. Run the backup via this script:

```sh
#! /bin/bash

#########################################
#                                       #
#   BACKUP SCRIPT FOR XPLOSION SERVER   #
#   https://tommi.space/scripts/backup  #
#       licensed with EUPL v. 1.2       #
#                                       #
#########################################

NAME="`date -u +%Y-%m-%d`_auto-backup";
DESCRIPTION="server.tommi.space AUTOMATED BACKUP, created on `date -u +%Y-%m-%dT%H:%M:%SZ`";
FAIL=true;
hr="――――――――――――――――――――――――――――――――――――――――――"
dhr="==========================================";

# Creating the backup
echo -e "$dhr\n`date -u +%Y-%m-%dT%H:%M:%SZ`:\tCREATING BACKUP\n$hr";
mv -vf /home/yunohost.backup/archives/* /home/yunohost.backup/tmp/;
sudo systemctl stop forgejo.service;
sudo yunohost backup create -n "$NAME" -d "$DESCRIPTION" && FAIL=false;
sudo systemctl start forgejo.service;

if [ "$FAIL" = false ] ; then
        rm -rf /home/yunohost.backup/tmp/*;
        echo -e "$hr\n`date -u +%Y-%m-%dT%H:%M:%SZ`:\tSUCCESS! — THE END\n$dhr";
else
        echo -e "$hr\n`date -u +%Y-%m-%dT%H:%M:%SZ`:\tFAILURE!";
        mv -vf /home/yunohost.backup/tmp/* /home/yunohost.backup/archives/ && \
                echo -e "the last successful backup has been restored.\n$dhr";
fi
```

### Expected behavior

The backup should succeed

### Logs

https://paste.yunohost.org/raw/mevaviruse

**Comment by zamentur** [comment]
I guess you should not mount your s3fs on `/home/yunohost.backup`
You should do it on `/home/yunohost.backup/archives`

Note that YunoHost use mount --bind and hardlink (or symbolic link) to avoid to copy data into tmp... If you put it on another disk, you won't be able to use this optimization...

In your script, i am very surpised of the management of /home/yunohost.backup/tmp.
```
mv -vf /home/yunohost.backup/archives/* /home/yunohost.backup/tmp/;
````

The `input/output error` seems coming from your S3 FS (which soft is used ? Garage, minio an external provider ?), so from my point of view the correct behaviour should be "Manage the error, clean tmp and explain the backup was not successful..." and not "The backup should succeed" How could we succeed if the S3 return an error.

I change the title of your ticket, cause it's an expert change to setup s3fs here, it's not a general bug on the backup feature for each FS in use.

**Comment by xplosionmind** [comment]
Thanks a lot for your reply, @zamentur!

I realized that mounting stuff with s3fs is quite complex, and it would be better to have a different solution. Maintaining this whould cause a great headache… closing this for the moment.

Thanks again!
