### ISSUE TITLE
Show error and warning count in administration logging panel

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#226]
###### Original Redmine Issue: [226](https://dev.yunohost.org/issues/226)

Author Name: **opi**

---

Sometimes an operation (like a backup) log a lot of sub operation, which can be warning, errors, but the main op ends by an nice "Success - everything goes well". 
For a regular user who doesn't want to read logs before going to bed, it can be misleading, and sub-errors  are not known.

We can find an elegant way to add an error/warning count to indicate that something goes wrong during the whole process.

**Comment by alexAubin** [comment]
Closing because something like this now exists in webadmin
