### ISSUE TITLE
Installation of Lets Encrypt cert fails.

### ISSUE THREAD

**Issue by mikerjensen** [YunoHost/issues#2260]
I have a running Yunohost installation already supporting https/  SSL certificate for a .com domain. I am now trying to get the same Yunohost installation to host a second domain. The new domain is up and http://suvabay.com works, but when i try installing Let's Encrypt cert for the domain it fails as per the below error message. I am not sure what it means.  I also tried by command line, with --force --no-checks, same problem - https://paste.yunohost.org/raw/upakefiwod  / https://paste.yunohost.org/raw/kofayezono

human_routes.domains.action_config
YunoHost encountered an internal error
Verifying suvabay.com...
Challenge did not pass for suvabay.com: {'identifier': {'type': 'dns', 'value': 'suvabay.com'}, 'status': 'invalid', 'expires': '2023-10-10T12:31:42Z', 'challenges': [{'type': 'http-01', 'status': 'invalid', 'error': {'type': 'urn:ietf:params:acme:error:connection', 'detail': '162.144.81.171: Fetching http://suvabay.com/.well-known/acme-challenge/xtys2oDZUnfQptOeWAFIucoEc0Jv_THSr3srbkqKmpI: Error getting validation data', 'status': 400}, 'url': 'https://acme-v02.api.letsencrypt.org/acme/chall-v3/270322090376/nsFWOw', 'token': 'xtys2oDZUnfQptOeWAFIucoEc0Jv_THSr3srbkqKmpI', 'validationRecord': [{'url': 'http://suvabay.com/.well-known/acme-challenge/xtys2oDZUnfQptOeWAFIucoEc0Jv_THSr3srbkqKmpI', 'hostname': 'suvabay.com', 'port': '80', 'addressesResolved': ['162.144.81.171', '157.230.16.223'], 'addressUsed': '162.144.81.171'}], 'validated': '2023-10-03T12:31:43Z'}]}
Error: "500" Internal Server Error

Action: "PUT" /yunohost/api/domain/suvabay.com/actions/cert.cert.cert_install

Error message:
Let's Encrypt certificate install failed for suvabay.com

**Comment by alexAubin** [comment]
Can you confirm that you are not behind a reverse proxy that would be interfering ?

Is YunoHost's diagnosis happy about that second domain ? (in the "web" section)

**Comment by mikerjensen** [comment]
The Web section of the diagnosis looks ok, although oddly, there is a warning about the original domain:

Domain oliverjensenmedia.com appears unreachable through HTTP from outside the local network.
    It looks like another machine (maybe your internet router) answered instead of your server.
    1. The most common cause for this issue is that port 80 (and 443) [are not correctly forwarded to your server](https://yunohost.org/isp_box_config).
    2. On more complex setups: make sure that no firewall or reverse-proxy is interfering.

Domain vpn.oliverjensenmedia.com is reachable through HTTP from outside the local network.

Domain suvabay.com is reachable through HTTP from outside the local network.

I'm not sure if the above error is relevant to the problem...perhaps it is due to being hosted on a DigitalOcean droplet?

-------
I See in the DNS section there is a warning about one of the IPs in the A record...not sure if this would be a problem or not:

"Some DNS records are missing or incorrect for domain suvabay.com (category basic)
   The following DNS record does not seem to follow the recommended configuration:
    Type: A
    Name: @
    Current value: ['162.144.81.171', '157.230.16.223']
    Expected value: 157.230.16.223

**Comment by alexAubin** [comment]
>I See in the DNS section there is a warning about one of the IPs in the A record...not sure if this would be a problem or not:

Yes you have 2 A records for your domain and Lets Encrypt is probably hitting the other IP ...

**Comment by mikerjensen** [comment]
Ok, good point. I removed the second IP, and the yunohost Let's Encrypt script worked, without the need for --force . 

Thanks.

**Comment by mikerjensen** [comment]
Issue resolved by removing alternate IP address in the domain record.
