### ISSUE TITLE
My_webapp: error on nginx conf with php 8.2

### ISSUE THREAD

**Issue by magostinelli** [YunoHost/issues#2262]
### Describe the bug

When choose php 8.2 for my_webapp, nginx conf (my_webapp.d/php.conf) contains:
fastcgi_pass unix:/var/run/php/php7.4-fpm-my_webapp.sock
Instead of:
fastcgi_pass unix:/var/run/php/php8.2-fpm-my_webapp.sock

### Context

- Hardware: VPS bought online 
- YunoHost version: 11.2.4
- I have access to my server: Through SSH, through the webadmin |
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### To reproduce
Install cutom webapp, and then change php engine from 7.4 to 8.2

### Expected behavior

fastcgi_pass unix:/var/run/php/php8.2-fpm-my_webapp.sock

### Logs

nginx error log:
 connect() to unix:/var/run/php/php8.2-fpm-my_webapp.sock failed (2: No such file or directory) while connecting to upstream

**Comment by ericgaspar** [comment]
Please open an issue on my_webapp app repo : https://github.com/YunoHost-Apps/my_webapp_ynh
