### ISSUE TITLE
Config panels: environment not fully populated with app settings etc like for other packagingv2 scripts

### ISSUE THREAD

**Issue by orhtej2** [YunoHost/issues#2268]
### Describe the bug

When running `config` after applying changes from `config_panel.toml` environment is not fully populated (missing data from app settings and manifest).

`ynh_php_*` helpers expect `YNH_APP_PACKAGING_FORMAT` to be populated, otherwise they default it to '0' hence reading legacy `YNH_PHP_VERSION` instead of passed `$phpversion`.

### Context

- Hardware: VPS bought online
- YunoHost version: 11.2.5.
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Expected behavior

1. Install [modified helloworld_ynh](https://github.com/orhtej2/helloworld_ynh/tree/environment)
2. Change configuration from config panel.
3. Nothing really but logs dump environment passed to `config` script.

### Logs

[Sample logs](https://github.com/orhtej2/helloworld_ynh/tree/environment).

**Comment by orhtej2** [comment]
Citing from Matrix

> Yeah env [here](https://github.com/YunoHost/yunohost/blob/2bf2956b3db29650c5c7b05072eadbda5b955e9f/src/app.py#L1950C23-L1950C23) is missing [this call](https://github.com/YunoHost/yunohost/blob/2bf2956b3db29650c5c7b05072eadbda5b955e9f/src/app.py#L1221C8-L1221C8) I guess

**Comment by Josue-T** [comment]
https://github.com/YunoHost/yunohost/pull/1772 should fix it
