### ISSUE TITLE
disable "phone home" in rspamd by default

### ISSUE THREAD

**Issue by chri2** [YunoHost/issues#2272]
This references https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=932054 . 

We should consider disabling those features by default or at least contact rspamd since ynh probably somehow falls under the [Vendor Policy of rspamd](https://rspamd.com/doc/usage_policy.html#vendors-policies).

If the features relying on connections to rspamd.com would not be disabled we'd at least need to inform users about it and maybe get consent.

**Comment by alexAubin** [comment]
Closing because rspamd is to become an app on Bookworm / Yunohost 12.x
