### ISSUE TITLE
include rspamd repository

### ISSUE THREAD

**Issue by chri2** [YunoHost/issues#2273]
To improve the upstream support for rspamd used for spam filtering in yunohost I'd propose to include the repository offered by rspamd.

On matrix the problem with x86_64 without SSSE3 and libhyperscan5 has been mentioned. I tested the rspam version from the debian repo and the rspamd in a qemu Opteron_G1 and found that they behave identically and both pull in the libhyperscan5. Both worked as a far as I tested (learned a few thousand spam messages).

I'm already running the newer rspamd repo version on an aarch64 and so far it is stable.

Any other tests that would be needed?

**Comment by alexAubin** [comment]
Closing because rspamd is to become an app on Bookworm / Yunohost 12.x, and the app will ship a more recent version than Debian's default one
