### ISSUE TITLE
Missing key for Sury repo

### ISSUE THREAD

**Issue by marcogaio** [YunoHost/issues#2277]
It is not clear if is a consequence of bug #2263 (installation failed, i was forced to complete jumping installation phase and completing GRUB install; after that i've fixed it as in bug and do an `apt dist-upgrade`).

But Sury PHP repository say me that it is not signed; i was forced to follow their instruction (https://packages.sury.org/php/README.txt) so practically downloading the repo key and adding to the repo:
```
root@hostname:~# cat /etc/apt/sources.list.d/extra_php_version.list 
deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ bullseye main
```
FYI. Thanks.

**Comment by alexAubin** [comment]
Closing because should be fixed by a "simple" `yunohost tools regen-conf apt`

**Comment by Lagunix** [comment]
> yunohost tools regen-conf apt

# sudo yunohost tools regen-conf apt

Warning: gpg: no valid OpenPGP data found.
Error: Could not run script: /usr/share/yunohost/hooks/conf_regen/10-apt

So, this is not worked..
