### ISSUE TITLE
rspamd: don't rate locally generated messages

### ISSUE THREAD

**Issue by chri2** [YunoHost/issues#2279]
As configured now rspamd rates locally generated messages also and e.g. give diagnosis messages of yunohost a high enough score to have them sorted to junk by there header.

As far as I thought about it I do not see a good reason why locally generated messages (system and user) should be rated by rspamd.

![2023-11-02_09-09-08-102399519](https://github.com/YunoHost/issues/assets/15866990/0366aede-a8f2-40e2-b569-c7d2684256af)

**Comment by alexAubin** [comment]
Closing because rspamd is to become an app on Bookworm / Yunohost 12.x
