### ISSUE TITLE
UserOption form should be a lot faster

### ISSUE THREAD

**Issue by selfhoster1312** [YunoHost/issues#2280]
Currently, UserOption performs many LDAP queries (not even in parallel) which makes it slower and slower as the user DB grows.

The first query triggered by `user_list` is fine returning all info super fast in a single query. But then we have a `user_info` query for every user, which is slow as hell.

Just commenting out the `if self.default is None` block on my system reduces app install time by about 1 minute. Additionally, it removes annoying warnings about email disabled (for every user) like in #2226 .

**Comment by eauchat** [comment]
Could this be related to #2088?

**Comment by selfhoster1312** [comment]
No it's not related. UserOption queries are now fast after #1738. #2088 is about synchronizing permissions between groups/users. UserOption only needs a simple user list which is fast.

Now that the PR has been merged we can close this :)
