### ISSUE TITLE
Setting app path to {domain}/ breaks default app redirects

### ISSUE THREAD

**Issue by Golden-Phy** [YunoHost/issues#2285]
### Describe the bug
Setting an apps path to the root of a domain breaks the configuration of nginx causing it to get stuck in a redirect loop. 

### Context
- Hardware: VM on XCPng homelab
- YunoHost version: 11.2.5 (stable)
- I have access to my server: Through SSH | through the webadmin | VNC
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### To reproduce
yunohost app change-url {app} -p / -d {domain}

Now the webadmin button to set/unset the app as default for the domain at /yunohost/admin/#/apps/{app}/operations will return a 400
Trying to open https://{domain} will redirect indefinitely until the browser aborts.

### Expected behavior
Either the app 'owns' that domain disabling redirects or a valid path should be enforced when attempting to configure the app.

### Logs
https://paste.yunohost.org/raw/axagagatac

**Comment by alexAubin** [comment]
`Unable to make 'nextcloud' the default app on the domain, 'cloud.domain2.tld'
  is already in use by 'nextcloud'`

You just tried to make the "default" app an app that was already installed on the root of the domain ... why ...

**Comment by Golden-Phy** [comment]
@alexAubin I guess I should have taken a look at that log, that's indeed inconclusive sorry for that. 
I had just done what was requested for submitting bug reports, figure out how to reproduce it with the API and add some logging data using the interface.
As far as I can still recall the app was installed under /nextcloud and I was trying to change it to the root of that domain using the webinterface maybe it was the default app for the domain at that point, but not the other way around. 
The reason I tried to change the path in the first place, was that the native nextcould client needed that /nextcloud path.
