### ISSUE TITLE
YunoHost Forum signup by e-mail fails because no verification e-mail is received

### ISSUE THREAD

**Issue by CynthiaArmstrong** [YunoHost/issues#2286]
### Describe the bug

YunoHost Forum signup by e-mail fails because no verification e-mail is received.

### Context

I tried signing up with a private domain and with @proton.me. I did this at the beginning of the month and just now.

### To reproduce

Sign up by e-mail on https://forum.yunohost.org/.

### Expected behavior

Receiving a verification e-mail is expected.

### Logs

I don't have logs.

**Comment by alexAubin** [comment]
The issue should have been fixed yesterday night, closing assuming this is fixed, feel free to complain if still experiencing the issue

**Comment by CynthiaArmstrong** [comment]
Yes, it is working again. I received e-mails on both accounts now. Thanks for the quick update. 👍
