### ISSUE TITLE
Support "outside reverse proxy http to https redirect" by supporting letsencrypt acme challenge on https

### ISSUE THREAD

**Issue by abanink** [YunoHost/issues#2291]
I have a reverse proxy redirecting http to https in front of yunohost so the http traffic never hits yunohost.
Letsencrypt bot will follow the redirect from port 80 to port 443 and allows a self-signed certificate. So, when the letsencrypt bot tries to get the acme challenge on port 443, it's exactly the same as on port 80. But the default nginx config for 80 enables the public acme-challenges directory, and the config for port 443 does not. So the the bot fails to collect the challenge on https, resulting in a failure to generate the certificate.

This can be worked around by adding the acme-challenges location to the https service on each domain.

This is the relevant diff for a sample domain if I would regenerate the default nginx config:
```
# yunohost tools regen-conf nginx --dry-run -d
      status: modified
    /etc/nginx/conf.d/****.org.conf: 
      diff: @@ -42,12 +42,20 @@
     server_name ***;
 
     include /etc/nginx/conf.d/security.conf.inc;
-    include /etc/nginx/conf.d/acme-challenge.conf.inc;

```
This can be verified by simply creating a dummy file in /var/www/.well-known/acme-challenges-public:
```
# ls /var/www/.well-known/acme-challenge-public/ | grep test
testfile2.txt

```

With default config:
```
$ wget --no-check-certificate "https://****/.well-known/acme-challenge/testfile2.txt"
--2023-11-28 10:22:57--  https://****/.well-known/acme-challenge/testfile2.txt
Resolving *** (***)... **.**.**.**
Connecting to *** (***)|**.**.**.**|:443... connected.
WARNING: cannot verify ****'s certificate, issued by ‘O=***,CN=***’:
  Self-signed certificate encountered.
HTTP request sent, awaiting response... 404 Error
2023-11-28 10:22:57 ERROR 404: Error.
```

But after adding the acme-challenges on https:
```
$ wget --no-check-certificate "https://***/.well-known/acme-challenge/testfile2.txt"
--2023-11-28 10:25:25--  https://***/.well-known/acme-challenge/testfile2.txt
Resolving *** (***)... **.**.**.**
Connecting to *** (***)|**.**.**.**|:443... connected.
WARNING: cannot verify ***'s certificate, issued by ‘O=***,CN=***’:
  Self-signed certificate encountered.
HTTP request sent, awaiting response... 200 OK
Length: 6 [text/plain]
Saving to: ‘testfile2.txt.2
```
The same goes for the letsencrypt bot retrieving the challenge text file.

Adding this would save me from the manual change in the nginx .conf file in my set-up.

**Comment by alexAubin** [comment]
Wokay but ...

>I have a reverse proxy redirecting http to https in front of yunohost so the http traffic never hits yunohost.

Why are you even doing this in the first place, and why would you encrypt some traffic on the local network (?) which was not encrypted on the outside network ?

**Comment by abanink** [comment]
> Wokay but ...
> 
> > I have a reverse proxy redirecting http to https in front of yunohost so the http traffic never hits yunohost.
> 
> Why are you even doing this in the first place, and why would you encrypt some traffic on the local network (?) which was not encrypted on the outside network ?

my reverse proxy is hosted on the internet, my yunohost is hosted at home. Besides, yunohost is not the only service I self-host. 
Http requests get a redirect response to https by the reverse proxy for all my services; https requests get reverse proxied (and tunneled) to my self-hosted services. So my self-hosted services each take care of https traffic only, including certificate challenges.
Afaik in this set-up, there is no traffic which is encrypted on the local network which was not encrypted on the outside network. The http to https redirection on the reverse proxy is like a courtesy for links still pointing to the http resource, I don't even want to handle that traffic on my self-hosted services.
Hope this clarifies. I really don't think this is extremely exotic...

**Comment by alexAubin** [comment]
Closing as [wontfix](https://yunohost.org/en/community/faq#why-won-t-you-include-fea) because yes, that sounds exotic, and it's still unclear why you'd want to reverse-proxy as https stuff that was not encrypted in the first place

You can probably achieve what you want by copy-pasting the lets encrypt snippet to some new file inside `/etc/nginx/conf.d/yourdomain.tld.d/`

**Comment by abanink** [comment]
https://letsencrypt.org/docs/allow-port-80/

_Our recommendation is that all servers meant for general web use should offer both HTTP on port 80 and HTTPS on port 443. They should also send redirects for all port 80 requests, and possibly an HSTS header (on port 443 requests)._

just my 2 cents
