### ISSUE TITLE
Ssh connection don't work with admin account after full restore (with a user created outside yunohost)

### ISSUE THREAD

**Issue by gwen-lg** [YunoHost/issues#2292]
### Describe the bug

After a full backup restore on a fresh debian server installation, the admin user password don't work on ssh.
But it work on webadmin and on the server (if ssh connection is done with other account)

### Context

- Hardware: *dedicated server*
- YunoHost version: from 11.2.5 (restaured with 11.2.5, and updated to 11.2.6 and 11.2.7)
- I have access to my server: *Through SSH | through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- If upgrading, current YunoHost version: 11.2.7

### To reproduce

- create a full backup of a yunohost installation.
    ```sh
    sudo yunohost backup create
    ```
- setup a new server with debian and install yunohost package (but don't do the post installation)
- restore the full backup created during the first step
    ```sh
    sudo yunohost backup restore <backup_name>
    ```
- tried to login with admin account on webadmin and ssh.
It's work on webadmin, but not on ssh

### Expected behavior

The admin account/password should work on ssh as on webadmin.

### Logs

The connection tried add this in sshd logs :
```log
sshd: Connection from <ip_client> port 60772 on <ip server> port 22 rdomain ""
sshd: User <admin_user> from <ip_client> not allowed because none of user's groups are listed in AllowGroups
sshd: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=<ip_client>  user=<admin_user>
sshd: pam_ldap(sshd:auth): Authentication failure; user=<admin_user>
sshd: Failed password for invalid user <admin_user> from <ip_client> port 60772 ssh2
```

**Comment by alexAubin** [comment]
>sshd: User <admin_user> from <ip_client> not allowed because none of user's groups are listed in AllowGroups

Hmmm interesting .. Can you confirm that `grep AllowGroups /etc/ssh/sshd_config` lists "admins"

and that `groups <your_admin_user>` lists "admins" as the group of this user ?

**Comment by gwen-lg** [comment]
```prompt
$ grep AllowGroups /etc/ssh/sshd_config
AllowGroups ssh.main sftp.main ssh.app sftp.app admins root
```
and 
```prompt
$ groups <admin_user>
<admin_user> : <admin_user> cdrom floppy audio dip video plugdev netdev
```
So `yes` and `no`

**Comment by alexAubin** [comment]
well then what do you mean by "admin account" / "admin user" ... do we agree that "admin user" is a yunohost user that existed on the initial yunohost and is "transferred" via the backup, right ?

Did "admin user" already exist before you restored the backup ?

**Comment by gwen-lg** [comment]
Yes I talk about a yunohost user that had admin access on the initial yunohost and is transferred via backup.
And yes, a user with same name was created on the new server before the backup restore.
Probably source of the bug.

**Comment by alexAubin** [comment]
Then closing because that's the "expected" behavior (unless maybe we want to miserably crash when restoring a user DB if some user inside the DB already exist as "classic" unix users)

**Comment by gwen-lg** [comment]
In case of restoring a full backup without post installation, I expected than actual unix user to be "overwritten".
And even, If I have an other previous user than not exist in the yunohost backup, that this one be delete.

And in any-case, how I can fix the ssh connection ?
There is a yunohost command to regen and fix some configuration parts ?

**Comment by alexAubin** [comment]
Naively you can try to `userdel <admin_user>`, i guess it should only delete the unix user but not the ldap/yunohost user which probably does exist in the LDAP db, and should take over once the unix user is deleted, but that's kind of unexplored territory, basically yunohost doesn't really cover the case of "somehow somebody created a unix user with the same username" beyond basic checks during user creation

**Comment by gwen-lg** [comment]
userdel help, but now the home folder of the user is no longer assigned to the user, but is assigned to the `old` userid (1000).
Not sure if it's safe to change the userid of the involved user to 1000. Or i I need to fix all files and folder `chown`
