### ISSUE TITLE
Unable to remove auto dns token because of mandatory input field

### ISSUE THREAD

**Issue by Dazeilad** [YunoHost/issues#2293]
### Describe the bug

I entered an API key in the token field and saved it, but now I want to remove it. So I clear the input field, but as it is mandatory, I am not able to save an empty token.

![image](https://github.com/YunoHost/issues/assets/64801705/79526680-05d5-4ea9-8225-d6016036e268)

### Context

- YunoHost version: 11.2.7

**Comment by alexAubin** [comment]
Fixed via https://github.com/YunoHost/yunohost-admin/pull/581 and https://github.com/YunoHost/yunohost/pull/1951 (in bookworm / Yunohost 12.x)
