### ISSUE TITLE
UX/UI issue : Main domain helper can't be read with dark mode on

### ISSUE THREAD

**Issue by Thatoo** [YunoHost/issues#2295]
### Describe the bug

WIthin Yunohost admin webpage with Dark mode activated, go to Domains, go to the main domain and click on the "Main domain ?" button, it is impossible to read the content of this helper :

![image](https://github.com/YunoHost/issues/assets/464782/dde58b39-313e-492c-a74a-6c13f899d64e)

**Comment by Axolotle** [comment]
fixed in https://github.com/YunoHost/yunohost-admin/pull/530
