### ISSUE TITLE
App Catalogue Unresponsive -  Max Redirects Exceeded

### ISSUE THREAD

**Issue by RaggedStaff** [YunoHost/issues#2299]
### Describe the bug

Don't know if this is the right place, apologies if not.

I'm getting an error trying to read the app catalogue this morning:
`Unable to download the default app catalog: Error when downloading data from https://app.yunohost.org/default/v3/apps.json: Exceeded 30 redirects.`

Error also shows up browsing to the link above in Firefox & from the web interface when rfreshing the System Update page ( [domain]/yunohost/admin/#/update )

### Context

- Hardware: *VPS bought online*
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current YunoHost version: 

### To reproduce

   1. *Go to https://app.yunohost.org/default/v3/apps.json:
   2. *See error*

### Expected behavior

App cataloguw should be retrieval

**Comment by alexAubin** [comment]
(Should be working now, sorry for the inconvenience)
