### ISSUE TITLE
XMPP: XEP-0156 lookup

### ISSUE THREAD

**Issue by Minecodes** [YunoHost/issues#2310]
Can you please add XEP-0156? Otherwise, Keyoxide can't loop up for a Keyoxide ASP or OpenPGP proof.
![image](https://github.com/YunoHost/issues/assets/65566012/355fd1d9-ab38-4bfc-8627-8fa131fce2ee)
![image](https://github.com/YunoHost/issues/assets/65566012/c963fa02-a4d3-48e8-8547-5f0c9efb84d4)

**Comment by alexAubin** [comment]
Closing, we rely on Metronome for XMPP, this is not Metronome's bugtracker

**Comment by Minecodes** [comment]
Thanks for this info 👍
