### ISSUE TITLE
Domain expiration date mismatch between diagnostic and domain page

### ISSUE THREAD

**Issue by sy6sy2** [YunoHost/issues#2311]
### Describe the bug

The diagnostic page says that my main domain LE certificate will expire in 33 days while the domain page says that my domain LE certificate will expire in 59 days.

Also, I receive Automatic diagnostic emails saying that my certificate will expire.

### Context

- Hardware: OVH VPS
- YunoHost version: 11.1.21.4
- I have access to my server: Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### To reproduce

Compare diagnostic and domain web admin pages.

### Expected behavior

Same information on both page.

### Logs

* Diagnostic page:
![Capture d’écran 2024-01-19 à 10 56 56](https://github.com/YunoHost/issues/assets/11562279/00ee1b0f-f8fe-4d61-92ab-b4b718b80400)

* Domain page:
![Capture d’écran 2024-01-19 à 10 57 11](https://github.com/YunoHost/issues/assets/11562279/bc540c83-1024-4dcf-b32d-73ed9b28cd3e)

**Comment by alexAubin** [comment]
This is two completely different things, there's no reason for it to be the same info ...

**Comment by alexAubin** [comment]
Or maybe the diagnosis message is not explicit enough ... when it says "The domain will expire", this is not about the certificate, this is about your domain registration on your registrar, the place where you bought the domain

**Comment by sy6sy2** [comment]
Oh! I get it now! Sorry for the issue and thanks for the details 😉
