### ISSUE TITLE
Bookworm: in the webadmin, the 'User interface' button in top right redirects to https://{ip}/yunohost/sso which doesn work

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#2314]
NB: this is when accessing the webadmin using the IP (which is what you do initially during postinstall etc)

Maybe we want to it to point to the {main_domain}/yunohost/sso ?

I'm also noticing that it's visible during postinstall, which is annoying to handle, but during postinstall there's no main domain yet so eh

And it's also visible on the login page, but here too, we probably don't want to leak the info of what's the actual domain hosted to any random folk visiting the IP :thinking:

**Comment by OniriCorpe** [comment]
> we probably don't want to leak the info of what's the actual domain hosted to any random folk visiting the IP 🤔

this info is already leaked if a reverse DNS is configured

**Comment by Axolotle** [comment]
done with https://github.com/YunoHost/yunohost-admin/pull/530/commits/613cdaf41eec1107ab03834160173b0d53e80119
