### ISSUE TITLE
Bookworm: in the new portal, the color of the border around app tiles is inconsistent with the theme

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#2316]
cf for example this in dark mode. Naively it should be using the same border color used in the rest of the UI ?

![appborder](https://github.com/YunoHost/issues/assets/4533074/b98005e7-4c98-4bac-8900-5bfd0895f470)

**Comment by Axolotle** [comment]
maybe fixed by https://github.com/YunoHost/yunohost-portal/commit/afac380095179ecbfabfad490e882d3fe8c16c31
used 'neutral' color as with cards in profile edit page

**Comment by alexAubin** [comment]
Fixed indeed 👍
