### ISSUE TITLE
make clear if CIDR notation is authorized for admin panel IP filtering

### ISSUE THREAD

**Issue by OniriCorpe** [YunoHost/issues#2320]
is the CIDR notation is authorized for admin panel IP filtering?
for example:
```text
192.168.0.0/16
fc00::/7
```
idk? we should explicit it in the corresponding "help" text

if it's not supported, i think it would be really great that's the case

**Comment by alexAubin** [comment]
It's the nginx "allow" directive https://github.com/YunoHost/yunohost/blob/dev/conf/nginx/yunohost_admin.conf.inc#L12 so yes: https://nginx.org/en/docs/http/ngx_http_access_module.html

Corresponding help string is https://github.com/YunoHost/yunohost/blob/dev/locales/en.json#L470
