### ISSUE TITLE
XMPP: Missing subdomains for certificate generation

### ISSUE THREAD

**Issue by Letterus** [YunoHost/issues#2325]
Metronome is configured to use the subdomains pubsub.*, muc.*, vjud.* and xmpp-upload.*, but the script for generating the certificate only includes xmpp-upload and muc in its list. This may lead to failing clients.

https://github.com/YunoHost/yunohost/blob/b69cbd33edf1d8d6688adf3963c40e40cb5faae6/src/certificate.py#L587

**Comment by Letterus** [comment]
Hint: addind the missing subdomains to the script does not help because the HTTP server is not setup to serve the missing subdomains to the certificate issuer. So to resolve that one an extended approach is necessary (like setting up temporary vhosts or something similar).

**Comment by alexAubin** [comment]
Closing because metronome is to become an app in Bookworm / YunoHost 12.x : https://github.com/YunoHost-Apps/metronome_ynh
