### ISSUE TITLE
XMPP: Separation of subdomains and base domains leads to failing certificate generation for XMPP

### ISSUE THREAD

**Issue by Letterus** [YunoHost/issues#2326]
I have got a `sub.domain.com`.

In it's cache JSON file yunohost saves this domain as `domain.com` having the XMPP CNAMEs `xmpp-upload.sub` f.e.. This makes the DNS test regarding certificate generation fail because it tests against `xmpp-upload` and not against `xmpp-upload.sub`:

https://github.com/YunoHost/yunohost/blob/b69cbd33edf1d8d6688adf3963c40e40cb5faae6/src/certificate.py#L589

This leads to a certificate that is generated only for `sub.domain.com`, but not for `xmpp-upload.sub.domain.com` and thus http uploads tend to fail.

**Comment by alexAubin** [comment]
This was fixed in https://github.com/YunoHost/yunohost/pull/1763 (which is precisely the code you're pointing to) but is not yet released

**Comment by Letterus** [comment]
Great, thanks a lot!
