### ISSUE TITLE
Dead link in example_ynh

### ISSUE THREAD

**Issue by silverhook** [YunoHost/issues#2344]
### How to replicate:

1. go to https://github.com/YunoHost/example_ynh?tab=readme-ov-file#packaging-an-app-starting-from-this-example
2. click on https://github.com/YunoHost/apps/tree/master/tools/README-generator
3. get error

### How to fix:

change that URL instead to:

https://github.com/YunoHost/apps/tree/master/tools/readme_generator

(I would have opened a PR, but since it says the README is generated, did not know what to edit)

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/example_ynh/pull/232
