### ISSUE TITLE
Publier les TOS dans la CLI et la webadmin

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#2349]
Sur le web:
- [x] Forum https://forum.yunohost.org/tos
- [x] https://forum.yunohost.org/admin/site_settings/category/legal ?
    - [x] we need to move the TOS on an external website for that (our documentation?)
- [x] Store https://github.com/YunoHost/apps/pull/2113
- [x] Website (footer)
- [x] Documentation https://github.com/YunoHost/doc/pull/2436

Dans le code:
- [x] Webadmin (postinstall)
- [x] Webadmin (DynDNS creation)
- [x] Webadmin (footer)
- [x] CLI (postinstall)
- [x] CLI (DynDNS creation)

Communication:
- [ ] faire une annonce (une fois que c'est dans la webadmin)

**Comment by Axolotle** [comment]
Added in https://github.com/YunoHost/yunohost-admin/pull/580 + https://github.com/YunoHost/yunohost-admin/pull/580

**Comment by alexAubin** [comment]
Let's close it as done, we'll add some announcement about it in the bookworm release i guess
