### ISSUE TITLE
Move from LXD to Incus

### ISSUE THREAD

**Issue by Salamandar** [YunoHost/issues#2355]
- [x] package_check https://github.com/YunoHost/package_check/pull/156
- [x] ynh-dev: https://github.com/YunoHost/ynh-dev/pull/71
- [x] yunorunner
- [x] yunorunner_ynh: https://github.com/YunoHost-Apps/yunorunner_ynh/pull/54
- [x] [yunohost-ci](https://github.com/YunoHost/yunohost-ci) https://github.com/YunoHost/yunohost-ci/pull/3
  - [ ] migrate ci-apps to incus
- [x] [lxd_img_builder](https://github.com/YunoHost/lxd_img_builder) (to rename) https://github.com/YunoHost/lxd_img_builder/pull/6
  - [x] migrate ci-core to incus

**Comment by kay0u** [comment]
Two repo were added (yunohost-ci and lxd_img_builder). I don't understand why you remove lxd support from ynh-dev, but not in package_check

**Comment by Salamandar** [comment]
I didn't remove support from ynh-dev :) If you think about the PR's message, that was a suggestion for the future.

**Comment by kay0u** [comment]
You've replaced all lxc by incus in https://github.com/YunoHost/ynh-dev/pull/71/files

**Comment by Salamandar** [comment]
Oh… sorry, i had another branch that kept both working… so I thought of this one.

**Comment by Psycojoker** [comment]
ci-apps-dev has been using incus since one week and it seems to be working pretty well, so other CI are going to be migrated to incus soon :tada:

**Comment by alexAubin** [comment]
Closing because hmpf this has been opened for 4ish months and the only remaining item is that at some point we'll have to upgrade ci-apps but that'll happen
