### ISSUE TITLE
Webadmin: ↓↓↑↑ to enable log copypasting doesn't work anymore

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#2368]
### Describe the bug

In log view interface we volunteraly disabled copypasting because people would bypass the Share with yunopaste button

>Text selection is disabled. If you want to share this log, please share the full log with the 'Share with Yunopaste' button.
>Or if you really really want to select text, press these keys: ↓↓↑↑.

but it doesn't work anymoar

### To reproduce

Try to ↓↓↑↑, but text selection still doesnt work

### Expected behavior

Should enable text selection

### Logs

Yes :grimacing:

**Comment by Axolotle** [comment]
fixed with https://github.com/YunoHost/yunohost-admin/commit/e1b2630138401e398143d4d7756174e05832bbe1
