### ISSUE TITLE
Webadmin : advertise that the wishlist exists

### ISSUE THREAD

**Issue by Tagadda** [YunoHost/issues#2369]
We could add a message that advertise the wishlist when there's no result when searching for an app in the catalog

**Comment by tituspijean** [comment]
Let's be careful about broken apps, they are hidden in the default "show only good quality apps" view. We might trigger some frustration we say "go add it to the wishlist!", only for the user to find out the app is actually packaged, only broken.

**Comment by kay0u** [comment]
In this case, we can also advertise the voting system on the store.

**Comment by Axolotle** [comment]
fixed in https://github.com/YunoHost/yunohost-admin/pull/583
