### ISSUE TITLE
Password reset has two fields next to each other with little divide which is confusing to users

### ISSUE THREAD

**Issue by felagund** [YunoHost/issues#2373]
Pasword reset form is governed by this file:
https://github.com/YunoHost/SSOwat/blob/dev/portal/password.html

and unmodified it seems to look like this:

![Screenshot_20240409_124351](https://github.com/YunoHost/issues/assets/1218098/0f3a8485-236e-4b19-9ecb-de962609ceed)

I just spent several minutes guiding nan 85-year-old user explaining that there are indeed two input fields to fill in the form. The border between the two fields is too small and with little contrast. I think a better design would be to increase the border between them and order both input fields and the button horizontally.

**Comment by alexAubin** [comment]
Uuuh that doesn't look anything like the user portal form to reset the password ? x_X I don't even understand where the "Please enter your new password twice so we can verify you typed it in correctly" is supposed to come from, we don't have this in the code ?

On one of my server it looks like this:

![Capture d’écran du 2024-04-09 16-00-53](https://github.com/YunoHost/issues/assets/4533074/fdc32147-f54e-4dd1-826a-359d4dee752a)

Could it be that you're referring to a specific app and not yunohost itself ..?

**Comment by alexAubin** [comment]
(Or maybe the forum ?)

**Comment by tituspijean** [comment]
(Nope, not the forum, just tested it.)
![image](https://github.com/YunoHost/issues/assets/8769166/e005f7df-4e36-459b-88cb-3c9cb715d718)

**Comment by felagund** [comment]
Ah, sorry, nevermind. I misidentified where this comes from, it comes from somewhere outside of yunohost, sorry for the noise.
