### ISSUE TITLE
Improvements on Tartiflette / dash.yunohost.org

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#2375]
we should really rework some of [dash.yunohost.org](http://dash.yunohost.org/) to have a big table of all app, with a link to the current testing (if any) + latest autoupdate PR + latest result of the dev CI for those (so we know wether we can merge those), maybe ability to filter per maintainer

ideally ci-apps-dev (or all CIs) should push the job result on commit status (https://docs.github.com/en/rest/commits/statuses) to make it easier to fetch the status of a given branch/PR

**Comment by alexAubin** [comment]
cf https://github.com/alexAubin/tartiflettev2 and dashv2.yunohost.org
