### ISSUE TITLE
Could not start the service 'dovecot'

### ISSUE THREAD

**Issue by kutsaltotem** [YunoHost/issues#2380]
My YunoHost server
Hardware: VPS bought online
YunoHost version: 11.2.11.2 (stable)
I have access to my server : Through SSH |
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : no
If yes, please explain:

Description of my issue
Error: "500"

Action: "PUT" /yunohost/api/services/dovecot/start

I have access to yunohost, but I cannot access my e-mail address. There is such a service error, I am sharing the log.

https://paste.yunohost.org/yexohavono

**Comment by alexAubin** [comment]
Don't know how this happened, but the vmail user doesn't exists. `yunohost tools regen-conf dovecot` should automatically recreate it.
