### ISSUE TITLE
ynh_use_logrotate documentation misleading/wrong

### ISSUE THREAD

**Issue by chri2** [YunoHost/issues#2383]
This documentation https://yunohost.org/en/packaging_apps_scripts_helpers#ynh-use-logrotate doesn't mention [these conditions](https://github.com/YunoHost/yunohost/blob/7d0d82ae016ae3e7cdb06423b67678d7f7a5d9ca/helpers/logrotate#L41).

**Comment by tituspijean** [comment]
To be added in the header comments of the function for automagic documentation generation: https://github.com/YunoHost/yunohost/blob/7d0d82ae016ae3e7cdb06423b67678d7f7a5d9ca/helpers/logrotate#L5-L14

**Comment by alexAubin** [comment]
Closing because I don't understand the big deal ... imho people shouldnt even have to pass arguments to this helper as the standard should be to have logs in /var/log/$app which is the default value ... if this is really a big deal, please make a PR directly
