### ISSUE TITLE
Use Custom Certificate Authority 

### ISSUE THREAD

**Issue by DariusSG** [YunoHost/issues#2385]
Instead of using Let's Encrypt, Would it be possible to include a option to define custom ACME services instead.

This would existing people to use other CA services or run their own (DogTag PKI)

**Comment by tituspijean** [comment]
Let's Encrypt is an integrated method that just works. We will most likely not prioritize integrating other automated certificate generation authorities.

For reference, a page of the documentation explains how to bring your own certificates: https://yunohost.org/en/administer/tutorials/certificate_custom

**Comment by alexAubin** [comment]
Closing as wontfix
