### ISSUE TITLE
Turning metronome into an app

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#2387]
- [x] Remove the corresponding blocks from the core
- [ ] We need a migration to remove the old `xmpp.main` permission from LDAP

The app should:
   - Be installed on a single domain (maybe multi-instance)
   - Install Metronome
   - [x] Add the corresponding module from https://github.com/YunoHost/yunohost/tree/dev/conf/metronome/modules though I don't even know if they are really meaningful / used anymore
   - [x] Add the corresponding conf equivalent to https://github.com/YunoHost/yunohost/tree/dev/conf/metronome
   - [x] Require the appropriate XMPP ports to be opened (cf the --needs-exposed-port option on yunohost service add, to be picked up by the diagnosis etc)
   - [x] We probably can use a regen-conf hook to add the appropriate nginx virtualhosts (`muc.`, `xmpp-upload.`, maybe pubsub/vjud)
   - [x] Add a custom_dns_conf hook, cf https://github.com/YunoHost/yunohost/blob/dev/src/dns.py#L288 - iirc synapse or some other app already use it
   - [x] We need to figure out a mechanism for an app to add subjectAltName to the domain certificate somehow, cf https://github.com/YunoHost/yunohost/blob/dev/src/certificate.py#L604
   - [ ] Ideally, auto-regen the installed certificate (if it's already a Lets Encrypt cert) such that it integrates the subjectAltName

**Comment by ericgaspar** [comment]
I wonder if `prosody_ynh` -> `metronome_ynh` with some adjustment works 🤔

**Comment by anubister** [comment]
If the aim is to provide a good XMPP server, Prosody would be more advisable, cf the work started here : https://github.com/anubister/prosody_ynh/ (currently blocked due to https://github.com/YunoHost-Apps/redirect_ynh/issues/55).
It should already answer some items of the list; the most difficult being probably the others items :grinning:

**Comment by alexAubin** [comment]
Follow up : https://github.com/YunoHost-Apps/metronome_ynh/pull/3

**Comment by alexAubin** [comment]
Done in https://github.com/YunoHost-Apps/metronome_ynh
