### ISSUE TITLE
Only standard, not customized antifeatures descriptions are displayed before installation

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#2397]
Example with Ghost. Ghost app has a customized arbitrary limitation in its manifest:

https://github.com/YunoHost-Apps/ghost_ynh/blob/9acf201a00617f8c86699069025b4a1b83a2034e/manifest.toml#L19-L20
```
[antifeatures]
arbitrary-limitations.en = "Ghost developers have chosen to only support MySQL. YunoHost relying on MariaDB, incompatibilities may arise. For more information: https://github.com/TryGhost/Ghost/issues/15729#issuecomment-1299297720"
```

It is correctly transcribed into its README: https://github.com/YunoHost-Apps/ghost_ynh/blob/9acf201a00617f8c86699069025b4a1b83a2034e/README.md#red_circle-antifeatures

![image](https://github.com/YunoHost/issues/assets/8769166/c38ac10c-7a14-4c4c-b608-c72dd8806f94)

However, when loading the app installation page from the webadmin, the standard antifeature description is displayed:

![image](https://github.com/YunoHost/issues/assets/8769166/b4a0cf3e-a4a6-455f-a47a-faae2be8451c)

**Comment by Axolotle** [comment]
fixed in https://github.com/YunoHost/yunohost-admin/pull/582
