### ISSUE TITLE
mysql hook should save all dbs

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#240]
###### Original Redmine Issue: [239](https://dev.yunohost.org/issues/239)

Author Name: **julienmalik**

---

For the sake of "security", the core mysql backup hook could easily be extended to simply dump&save ALL databases.

Currently we delegate this work to apps backup script, but :
- not all apps implement a backup/restore script yet, and I bet this will take a lot of time to implement all of them.
- usually a full mysqldump is still small (compared to /var/mail on a typical production installation, for example) so does not explode the backup size. it's only a few MB more.
- a lot of db-based apps can be brought back to life, after installation, just by feeding the db again...

I have not yet thought through how to properly handle the potential conflicts during restore : should the core script restore all db ? or still leave the restore operation to apps ? I'm just saying that having that somewhere in the backup archive is already a good step forward for security.
This does not cost a lot of extra space, but can provide a simple backup of VERY valuable information, so that in case things go very bad, users still have their data somewhere, and a manual restoration is possible. Losing data definitively is the sooooo frustrating !

Personally this is how I implemented my own ynh backup :
I don't want to think too much nor wait for apps being ready : I just save a full mysql dump, and the whole content of /var/www and /opt. And I'm pretty confident that if things goes really bad (server crash), I could bring back to life most stuff I had running, at least manually, even if almost no installed apps implement backup.

**Comment by alexAubin** [comment]
Closing because the issue has been opened for 6 years and I don't see a strong argument for this

Imho the current backup system is already good enough for the nominal use case, and then there's the whole question of "entire fs snapshots" or making it easier to create custom backup hooks maybe
