### ISSUE TITLE
Fix BorgBackup instructions in docs

### ISSUE THREAD

**Issue by olberger** [YunoHost/issues#2407]
In https://yunohost.org/en/backup/borgbackup, the commands in https://yunohost.org/en/backup/borgbackup#test mention plain `borg` command. However, that currently won't work.

Unless installed manually, `borg` isn't installed as a regular Debian package by borg_ynh. Instead, it is installed from upstream source in `var/www/borg/venv/bin/borg` (see https://github.com/YunoHost-Apps/borg_ynh/issues/152)

Hope this helps

**Comment by Salamandar** [comment]
Indeed you are right ! This recently changed in the borg package (we found it crappy to have a globally installed borg command from our package that would be possibly broken if multiple borg apps are installed…

**Comment by alexAubin** [comment]
Closing because the doc was moved to the borg_ynh package and should now contain the proper instruction to source the env
