### ISSUE TITLE
rspamd shipped with ynh crashes with SEGFAULT -  fix available

### ISSUE THREAD

**Issue by ndx1905-github** [YunoHost/issues#2409]
### Describe the bug

some emails going out were not signed with DKIM, but some were.
inspection of logs showed there was a SEGFAULT error that made rspamd crash

### Context

- Hardware: *VPS bought online 
- YunoHost version: 11.2.12 (stable)
- I have access to my server: *Through SSH | through the webadmin  *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no 

### To reproduce
send email from a client (not CLI) to external server and check DKIM signing : will sometimes be absent

### Expected behavior
mails should be DKIM signed 100% of the time when not sent from CLI

### Logs
not available anymore since I've applied a fix

### Solution
Problem was encountered by another user who recommended to reinstall rspamd directly from stable directory
https://forum.yunohost.org/t/rspamd-segfault-and-no-dkim-signature-on-output-mail/29514/2

It worked for me too, but fix should be applied for all

**Comment by alexAubin** [comment]
Closing because rspamd will be removed from the default install in upcoming Bookworm, we'll use opendkim instead
