### ISSUE TITLE
DNS Records diagnosis fails

### ISSUE THREAD

**Issue by kattschan** [YunoHost/issues#2416]
### Describe the bug

Trying to run the DNS Records diagnosis returns an error. I have never run it successfully on this installation, however this server was wiped about 3 months ago on accident and before the reinstallation it worked fine.

### Context

- Hardware: Hetzner Cloud Debian 11 aarch64 ARM 
- YunoHost version: 11.2.19, just updated from an older version though this didn't fix it
- I have access to my server: SSH, webadmin, and "direct keyboard and mouse" through the KVM console
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: n/a
- If upgrading, current YunoHost version: n/a

### To reproduce

1. Go to 'Diagnosis'
2. Wait for Diagnosis to complete
3. Select 'Rerun Diagnosis' on DNS Records if necessary.

### Expected behavior

I expected to be able to perform diagnosis on my DNS records without error.
### Logs

The error does not provide me with a link to share the error, and this is what it shows:
```
Diagnosis failed for category 'dnsrecords':
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/yunohost/diagnosis.py", line 183, in diagnosis_run
code, report = diagnoser.diagnose(force=force)
File "/usr/lib/python3/dist-packages/yunohost/diagnosis.py", line 430, in diagnose
items = list(self.run())
File "/usr/lib/python3/dist-packages/yunohost/diagnosers/12-dnsrecords.py", line 57, in run
for report in self.check_domain(
File "/usr/lib/python3/dist-packages/yunohost/diagnosers/12-dnsrecords.py", line 121, in check_domain
if self.current_record_match_expected(r):
File "/usr/lib/python3/dist-packages/yunohost/diagnosers/12-dnsrecords.py", line 220, in current_record_match_expected
key, value = param.split("=")
ValueError: not enough values to unpack (expected 2, got 1)
```
Note that in the diagnosis screen it says that everything is okay for DNS records with no information, and that the last time it was run was "over 54 years ago"(unix time 0/-1?)

**Comment by alexAubin** [comment]
It looks related to the fact that your DMARC record doesn't have an "=" in it ...

**Comment by kattschan** [comment]
Removing all the TXT records from all the domains and re-adding them seemed to work. Thanks! I forgot we had used a different email system for a little while, so those were probably left over from that.
