### ISSUE TITLE
Add option for apps to use their own nginx conf

### ISSUE THREAD

**Issue by lotigara** [YunoHost/issues#2427]
`please sorry for my english`

### Labels:
📦 App packaging, 🤓 helpers

### The problem:
Apps can use their own *snippets* of nginx configs, but not *full* nginx configs. I want to package [Codeberg Pages Server](https://codeberg.org/Codeberg/pages-server), which requires dedicated nginx config, because it manages certificates (by default, they're from Let's Encrypt) and domains on its own.

### The solution:
Add support for full nginx configs and add a creepy warning for users before installation, mentioning that app is using kind of *unsafe* webserver config.
They would be installed in the `/etc/nginx/sites-{available,enabled}/` directory.
And packagers would mark their *full* nginx configs with the `.site` extension instead of usual `.conf`:
```
.
[app files]
├── conf
│   └── nginx.site
[app files]
```

Helpers would act as usual:
```sh
#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=2
ynh_add_nginx_config
```

**Comment by lotigara** [comment]
[nginx helper](https://github.com/YunoHost/yunohost/blob/dev/helpers/helpers.v2.1.d/nginx) could be changed to support this feature, like this:
```
ynh_config_add_nginx() {

    if [ -f $YNH_APP_BASEDIR/conf/nginx.site ] ; then
        finalnginxconf="/etc/nginx/sites-available/$app"

        ynh_config_add --template="nginx.site" --destination="$finalnginxconf"
    else
        finalnginxconf="/etc/nginx/conf.d/$domain.d/$app.conf"

        ynh_config_add --template="nginx.conf" --destination="$finalnginxconf"
    fi

    if [ "${path:-}" != "/" ]; then
        ynh_replace --match="^#sub_path_only" --replace="" --file="$finalnginxconf"
    else
        ynh_replace --match="^#root_path_only" --replace="" --file="$finalnginxconf"
    fi

    ynh_store_file_checksum "$finalnginxconf"

    ynh_systemctl --service=nginx --action=reload

    unset finalnginxconf
}
```

**Comment by alexAubin** [comment]
>Apps can use their own snippets of nginx configs, but not full nginx configs. I want to package [Codeberg Pages Server](https://codeberg.org/Codeberg/pages-server), which requires dedicated nginx config, because it manages certificates (by default, they're from Let's Encrypt) and domains on its own.

Can you elaborate exactly what specific instruction cannot be integrate easily in the current system ? Considering that the .conf is included in the domain's conf so we're not limited to just `location` blocks ... Apart from the certificate part, which anyway imho shouldn't be handled by the app, because separation of concerns etc ...

**Comment by lotigara** [comment]
> > Apps can use their own snippets of nginx configs, but not full nginx configs. I want to package [Codeberg Pages Server](https://codeberg.org/Codeberg/pages-server), which requires dedicated nginx config, because it manages certificates (by default, they're from Let's Encrypt) and domains on its own.
> 
> Can you elaborate exactly what specific instruction cannot be integrate easily in the current system ? Considering that the .conf is included in the domain's conf so we're not limited to just `location` blocks ... Apart from the certificate part, which anyway imho shouldn't be handled by the app, because separation of concerns etc ...

Some apps may require non-standard configs (e.g., using new domains, like already mentioned Pages Server) and that configs can't be integrated into YunoHost for obvious reasons. Packagers may create no nginx configs at all, that's what I'll do in Pages Server package if this feature will not be implemented in YunoHost. But what if such a non-standard app requires nginx?

However, such apps are rare, so I'm closing this issue. But it would be cool, if somebody implemented this feature!

Offtopic: We need Pages Server because without it YunoHost users can't create their own GitHub, Codeberg, etc. for family, friends, themselves.

**Comment by alexAubin** [comment]
I understand that some apps "may" require non-standard configs, but these apps are rare, and the point of YunoHost is to try to standardize things, and there's also some attention given to not end up with [feature creep](https://en.wikipedia.org/wiki/Feature_creep) for stuff which are relevant only for a handful of apps or users, in turns ending in unmanageable complexity... Hence why I'm asking for specific details on what exactly cannot be achieved with the existing system to weight the relevance...

Right now I've seen a few apps with specific needs in terms of nginx config, last one I remember being metronome for which I used a custom regen conf hook (clearly not as straightfoward as the regular nginx conf snippet, but there are other implications behind this in terms of domain management, certficate mangement, dns, diagnosis, etc) : https://github.com/YunoHost-Apps/metronome_ynh/blob/master/conf/hook_conf_regen

**Comment by alexAubin** [comment]
(Maybe part of the answer is that wildcard domains are needed if this is similar to Gitlab pages ... I remember ka you tried to work on this back in the days)
