### ISSUE TITLE
"Regular computer" installer does not install YunoHost

### ISSUE THREAD

**Issue by x3rAx** [YunoHost/issues#2432]
### Describe the bug

YunoHost is not installed at all after using the "[Regular compyter](https://yunohost.org/en/install/hardware:regular)" install method. Only the base system is installed:

The system boots fine and I'm greeted with a typical TTY login that shows me the host name I selected during install. I can log in (on the TTY) to root and the admin user I created during install.

**However,** there is:

- No `yunohost` command (neither from the `admin` nor the `root` user)
- No `nginx` installed (package not installed, no `/etc/nginx`)
- (Obviously) no web interface displayed

### Context

**Hardware:** KVM (UEFI; CPU: i5-13600KF, 4 cores; RAM 4096 MiB; Disk: 32 GiB, on SSD; Network: virtio, NAT)
**YunoHost version:**  v.11.2
**I have access to my server :** direct access via keyboard / screen
**Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?** : no

I'm trying to install YunoHost on a KVM using the "[Regular compyter](https://yunohost.org/en/install/hardware:regular)" method. I chose the "normal" install (not "expert") and just went through the installer. Whole disk, nothing fancy.

The installer finishes without any sign of an error (I haven't retried and checked system logs yet).

When I **then** try to do the "[Remote server -> VPS or dedicated server with Debian 11](https://yunohost.org/en/install/hardware:vps_debian)" install:

```terminal
$ su root
# apt install curl
# curl https://install.yunohost.org | bash
```

I'm presented with the following output:

```
[FAIL] Your environment PATH variable must contains /sbin directory. Maybe try running 'PATH=/sbin:$PATH' to fix this.
[INFO] Installation logs are available in /var/log/yunohost-installation_XXXXXXXX_XXXXXXX.log
```

*(I removed the date from the log file name)*

So it seems like the installation is pretty broken, right? I already tried re-creating the VM and re-installing but with no success.

When I install a regular Debian 11, I can do the above without any issues.

### To reproduce

- Set up a VM using VirtManager
- Boot the YunoHost installer ISO
- Choose "normal" install"
- Follow the installer
- Reboot
- Login as `root` or as the created admin user
- Try to run the post-install command `yunohost tools postinstall`

### Expected behavior

The post-install should run.

### Logs

No logs since I don't even have a working YunoHost installation. Everything seems to be find during install, no obvious error. The only thing I can provide right now is:

```
bash: yunohost: command not found
```

**Comment by alexAubin** [comment]
Heuarg yeah i recently reworked the x86 ISO images to try to fix https://github.com/YunoHost/issues/issues/2080 but it sounds like there's more issues

It sounds like depending on hardware or software or bios / UEFI stuff (?) it doesn't go through the same sequence exactly (grub vs "isolinux" ?) ...

Anyway ... if that's doable, you could you share a screenshot or picture of on of the very first screen you see where you should be asked to chose between text install, graphical install ?

**Comment by alexAubin** [comment]
Also regarding:

>```
>$ su root
># apt install curl
># curl https://install.yunohost.org | bash
>```
>
>I'm presented with the following output:
>
>```
>[FAIL] Your environment PATH variable must contains /sbin directory. Maybe try running 'PATH=/sbin:$PATH' to fix this.
>[INFO] Installation logs are available in /var/log/yunohost-installation_XXXXXXXX_XXXXXXX.log
>```

Mayb try using try using `sudo -i` ... or maybe run the `curl | bash` command with bash prefixed by sudo like this : `curl https://install.yunohost.org | sudo bash`

**Comment by x3rAx** [comment]
Hi, sorry for the late answer.

I ran the installation again and saved the installer debug logs:

- [hardware-summary](https://paste.yunohost.org/oyixarogag#hardware-summary)
- [install-report.template](https://paste.yunohost.org/isudiqiqis#install-report.template)
- [lsb-release](https://paste.yunohost.org/cesogaqefi#lsb-release)
- [partman](https://paste.yunohost.org/xovapuxoxu#partman)
- [status](https://paste.yunohost.org/atimecixul#status)
- [syslog](https://paste.yunohost.org/oxasewikug#syslog)

As you requested, here's a screenshot from the boot menu:

![Screenshot_YunoHost-Dev_2024-08-30_00:36:52](https://github.com/user-attachments/assets/82abf223-a9da-47e5-9ca7-2ef42dfbfdee)

I should also mention that the very first thing I see (right before the boot menu) is this screen:

![Screenshot_YunoHost-Dev_2024-08-30_00:00:02](https://github.com/user-attachments/assets/0882169b-8e1e-4a66-bf0d-0d364175c49b)

During installation I did the following:

- **Language:** English
- **Location:** other -> Europe -> Germany
- **Locale:** Ireland *(IMHO best for German programmer with US keyboard layout)*
- **Keymap:** American English
- **Partitioning**: Guided - use entire disk -> Virtual disk 1 (vda) -> All files in one partition
- **Scan extra installation media:** No
- **Configure packages manager:** Germany -> deb.debian.org -> *(no proxy)*
- **Participate in usage survey:** No
- **Choose software to install:**
  - Uncheck "Debian desktop environment"
  - Uncheck "... GNOME"
  - Leave only "standard system utilities" checked

**Comment by x3rAx** [comment]
I tried reinstalling on a new VM where I selected BIOS instead of UEFI, and not only did the setup automatically start the installation after the "Keymap" step, it also automatically started asked to run the `yunohost tools postinstall` after I rebooted to the freshly installed system:

![Screenshot_YunoHost-Dev-BIOS_2024-08-30_01:33:42](https://github.com/user-attachments/assets/5c44343f-acf7-41e6-9556-526e1f6b3174)

So it looks like the setup can't handle UEFI hardware properly.

Btw. I find it a bit dangerous that the setup does simply override the whole disk without any confirmation :face_with_open_eyes_and_hand_over_mouth:

**Comment by alexAubin** [comment]
The new images should fix the issue, cheers !
