### ISSUE TITLE
Bug: Custom app label is not preserved on install

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost/issues#2434]
### Describe the bug

When I install an app with a customized app label, the custom app label is not saved. Instead the default app label is displayed in the user portal. E.g. I set a label for Phpinfo to `Phpinfo 8.2` (as I have this app for different PHP versions).

![image](https://github.com/user-attachments/assets/dbbbd89d-07fb-4acb-b1f4-e1d01b631cf6)

Then after install the app label is displayed like this.
![image](https://github.com/user-attachments/assets/e35f7326-e99a-4b70-bacd-603c57929172)

I can change it in the app settings afterwards again and then it is saved. However, it would be more convenient if it was saved during install already. This also happens for other apps (not only Phpinfo).

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.28
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### To reproduce

1. Choose any app to install
2. Change the app label to another name than the default app label
3. Install the app
4. Verify that the default app label is displayed in the user portal (instead of the custom app label)

### Expected behavior

The custom app label should be saved and be displayed in the user portal.

### Logs

None.

**Comment by tituspijean** [comment]
This seems to be fixed with YunoHost 12.
