### ISSUE TITLE
[YunoHost 12] Error when saving new DNS entries

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost/issues#2441]
### Describe the bug

Error when trying to save the DNS with new entries in the Domaines -> domaint.tld -> DNS web interface

### Context

- Hardware: *VPS bought online*
- YunoHost version: *12.0.3*
- I have access to my server: *through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch:
- If upgrading, current YunoHost version: 

### To reproduce

   1. *add a sub-domain.tld 
   2. *Go to Domaines -> domain.tld -> DNS*
   3. *Scroll down to 'sauvegarder'*
   4. *Click on 'sauvegarder'*
   5. *See error*

### Expected behavior

Save new DNS entries without error

### Logs
https://paste.yunohost.org/raw/alidorobaq

**Comment by Axolotle** [comment]
Thx ! Fixed by https://github.com/YunoHost/yunohost/commit/d5d6fb87a7a28be3451153ee1c3e8c3a56429b16
