### ISSUE TITLE
[YunoHost 12] clickable zone too wide to edit user profile

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost/issues#2442]
YunoHost 12.0.3, the upper part (in red) is clickable. only the user profile should be clickable

![Capture d’écran 2024-09-11 à 13 04 28](https://github.com/user-attachments/assets/2c35fe75-8e2e-4ebc-9a47-1f172a5039e9)

**Comment by Axolotle** [comment]
It should be only the middle part of the header (without logo), what browser do you use?

Also, while testing with users on the YunoCamp, we realized that the hidden when not focus/hovered link to edit the profile was not a good idea, we plan to make it visible so we will probably remove the clickable zone.
