### ISSUE TITLE
ynh-dev: referenced VB boxes are obselete

### ISSUE THREAD

**Issue by christophehenry** [YunoHost/issues#2443]
Setting up a development environment using Vagrant and VB [is still documented](https://github.com/YunoHost/ynh-dev/tree/virtualbox?tab=readme-ov-file#2-create-or-run-a-yunohost-vagrant-instance) but [referenced box URLS](https://github.com/YunoHost/ynh-dev/blob/virtualbox/ynh-dev#L128-L137) don't seem to exist anymore on the [YNH images repository](https://build.yunohost.org/).

**Comment by alexAubin** [comment]
Removed from the doc
