### ISSUE TITLE
[iso] selecting "web server" installs apache and prevents yunohost install

### ISSUE THREAD

**Issue by Salamandar** [YunoHost/issues#2448]
Some users have selected "web server" in the list of components.

It installs apache and, as it conflicts with yunohost, seems to just disable the installation of yunohost. Users find themselves with… just a standard debian install.

**Comment by Salamandar** [comment]
Workaround for users : follow the standard "install yunohost on top of debian" tutorial https://yunohost.org/en/administer/install/hardware:vps_debian#run-the-install-script

**Comment by alexAubin** [comment]
Closing because that seems to be related to the fact that the image when booted in "grub" instead of "isolinux" would not install yunohost ... should be fixed with the newest images
