### ISSUE TITLE
[Bookworm] 'Display more lines' is inconsistent with Bullseye and works only once

### ISSUE THREAD

**Issue by orhtej2** [YunoHost/issues#2452]
### Describe the bug

Interaction with 'Display more lines' in logs view is broken.
Defect 1: The whole page enters loading state, meaning the header starts displaying placeholder. This did not happen in Bullseye (where there would be no indication that something is happening, not ideal as well)
Defect 2: 'Display more lines' is gone, despite the fact that clearly this is not the beginning of the log (see image).

### Context

- Hardware: VPS bought online
- YunoHost version: 12.0.4.1+202409261515 (Bookworm unstable)
- I have access to my server: Through SSH/through the webadmin/direct access via keyboard
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### To reproduce

1. Go to Web Admin->Tools->Logs, any potentially long log.
2. Click on 'Display more lines'

### Expected behavior

'Display more lines' available till we scroll up to the top of the log file.

### Logs

(given this is install operation YNH header is missing with YNH version, app version etc).

![image](https://github.com/user-attachments/assets/5dfc3e1e-f29f-4e9b-800d-793582a6badc)

**Comment by Axolotle** [comment]
fixed with https://github.com/YunoHost/yunohost-admin/pull/530/commits/512efa9c071de6cf9d5c27fcff52ac7d91dfe796
