### ISSUE TITLE
[Bookworm] 'Operations' section is missing from app card

### ISSUE THREAD

**Issue by orhtej2** [YunoHost/issues#2453]
### Describe the bug

`$title` - section that allows to change url/interact with config panel is missing from YNH 12.x admin panel.

### Context

- Hardware: VPS bought online
- YunoHost version: 12.0.4.1+202409261515
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### To reproduce

Install any app, go to Admin->Applications->app

### Expected behavior

YNH 11:
![image](https://github.com/user-attachments/assets/9e7af461-6925-4c64-93c1-dcca887f5f74)

YNH 12 (wrong):
![image](https://github.com/user-attachments/assets/270948f8-b4b4-4ff6-a9eb-28e5a33230c1)

### Logs

N/A(?)

**Comment by ericgaspar** [comment]
the app Nextcloud and Rouncude don't have this issue in my server.

**Comment by orhtej2** [comment]
Related to lack of `config_panel.toml` perhaps?

**Comment by Axolotle** [comment]
fixed with https://github.com/YunoHost/yunohost-admin/pull/530/commits/66e4bfd75d6ed0f84002e972bd4bf644e706d055
