### ISSUE TITLE
[Bookworm] No save button in config panel page, only appears after refresh

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost/issues#2456]
### Describe the bug

When you go to an app config panel page, the save button doesn't load, refresh the page and the save button appears.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 12.0.4
- I have access to my server: *webadmin*
- Are you in a special context: *no*

### To reproduce

   1. *Go to 'webadmin -> app -> app with config panel -> config panel'*
   2. *no save button*
   3. *refresh page*
   4. *save button appears*

**Comment by Axolotle** [comment]
fixed with https://github.com/YunoHost/yunohost-admin/pull/530/commits/be55f7f9ac25f6da53be4d511f19522f42557db7
