### ISSUE TITLE
[Bookworm] "Custom CSS stylesheet" field cannot be emptied

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#2457]
### Describe the bug

Emptying the "Custom CSS stylesheet" field does not work, previous value appears again after saving the config panel.
Circumvented by putting something like "//none" in the field.

### Context

- YunoHost version: 12.0.4.1
- YunoHost admin version: 12.0.3.1

**Comment by Axolotle** [comment]
fixed with https://github.com/YunoHost/yunohost/pull/1657/commits/f64cc3f463a6c52212de5a68cf7f1682a5442e7e
