### ISSUE TITLE
[Bookworm] "Unsupported image type : text/plain" when uploading a portal logo

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#2462]
### Describe the bug

When saving a PNG file as a custom logo for the portal, the webadmin returns the following error: "Unsupported image type : text/plain"

![{29CB075C-9CFE-49CA-8F4A-B54297541713}](https://github.com/user-attachments/assets/c1cd26e0-f1a4-4dca-b5c1-9ee165725e31)
![{39DD1062-3FC7-4D82-B352-19A4D22A4DB5}](https://github.com/user-attachments/assets/ba2bea19-e61b-4b8c-b907-cdb6a01ecacb)

### Context

unohost version : 12.0.4.1+202409261515 (unstable)
yunohost-admin version : 12.0.3.1+202409251900 (unstable)

**Comment by sankayop** [comment]
Perhaps related, 
also on a new yunohost bookwork iso (uname -a: `Linux adoy.be 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux`)
when I try to load the .cube config file in the `vpnClient` app, I get the same error:
```
user1@domain1:~/ovpn$ sudo yunohost app config set vpnclient

========================================
>>>> Auto-configuration
========================================
Info: The VPN is not enabled
Enable VPN [yes | no]: yes
Info: VPNclient only interfaces with *dedicated, public IP VPNs accepting inbound traffic*, preferably with an associated `.cube` (or `.ovpn/.conf`) configuration file. Checkout the [list of known compatible providers](https://yunohost.org/providers/vpn) for more info.
Configuration file: /home/user1/ovpn/neutrinet.cube
Warning: unable to retrieve string to translate with key 'Unsupported image type : application/json' for default locale 'locales/en.json' file (don't panic this is just a warning)
Error: Unsupported image type : application/json
Configuration file:
```

It is also the case with a .ovpn or .conf file and both on yunohost GUI and CI.
(nothing to see in the log: https://paste.yunohost.org/ucozajivaz)
If not related, I can write another issue but probably redundant.
Thanks anyway for the follow up

**Comment by alexAubin** [comment]
So after debugging a bit, displaying the actual content, the result is suprising : 

`Unsupported file type 'text/plain', expected a type among 'image/png, image/jpeg, image/svg+xml'. Content: b'\xa1\xb8\xder\xd3\x9b\x8d\xe7-', [object Object]`

So turns out the API literally receive `[object Object]` as a raw value which, against all odd, base64 agrees to "decode" ... 

```python
>>> import base64
>>> base64.b64decode("[object Object]")
b'\xa1\xb8\xder\xd3\x9b\x8d\xe7-'
```

**Comment by alexAubin** [comment]
(smol poke @Axolotle when you have time to dig this ^)

**Comment by Axolotle** [comment]
fixed with https://github.com/YunoHost/yunohost-admin/pull/530/commits/40c0d8296d260b0e31578500f56fe746826c9e73
