### ISSUE TITLE
Impossible to add new group

### ISSUE THREAD

**Issue by orhtej2** [YunoHost/issues#2472]
### Describe the bug

1. Go to Web Admin->Users->Groups and permissions
2. Click 'Add new group'
3. Name it, click 'Save'

Expected: Group created
Actual: Error `the following arguments are required: groupname`

### Context

- Hardware:*VPS bought online
- YunoHost version:  12.0.6
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain:
- Using, or trying to install package version/branch: n/a
- If upgrading, current YunoHost version: n/a

### To reproduce

Described above

### Expected behavior

Described above

### Logs

None?

**Comment by ianalexis** [comment]
Did you install Yuno via the script?

**Comment by ianalexis** [comment]
Maybe related with: [User Permission Page Loads Forever](https://forum.yunohost.org/t/user-permission-page-loads-forever/31783) and [Job for slapd.service failed at install](https://forum.yunohost.org/t/job-for-slapd-service-failed-at-install/31809)

**Comment by orhtej2** [comment]
> Did you install Yuno via the script?

I did upgrade from YHN 11.x during beta phase, with official procedure described in the forums.
