### ISSUE TITLE
Fully support uncompressed backups

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#248]
###### Original Redmine Issue: [248](https://dev.yunohost.org/issues/248)

Author Name: **jocelyn**

---

`yunohost backup --no-compress` offers to do a backup in a directory, with no archive.

However, from my understanding/tests `yunohost backup delete` offers only to delete an archived backup. 

That's an issue, because running `rm -rf` on the backup dir is dangerous (as a backup dir is a mix of copies and mounts).

As a side note I'm big advocate of the --no-compress option working well : "flat" backups are useful when you want to use something else than archive copy for backups (e.g: attic/borg, rsync, whatever...).

**Comment by alexAubin** [comment]
Closing because meh
