### ISSUE TITLE
landingpage: English as default language

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost/issues#2485]
Hi! I can only see the landing page in French, and no language switch. Would it be possible to set English as the default language, and add a language switch? Ideally, it would be great if the language could be automatically detected from the browser’s settings.

**Comment by zamentur** [comment]
> Ideally, it would be great if the language could be automatically detected from the browser’s settings.

It should detect the language from browser settings :/

**Comment by OniriCorpe** [comment]
after some adjustments in the recent weeks/days, it should be solved now
