### ISSUE TITLE
Cannot install Nextcloud

### ISSUE THREAD

**Issue by Plumeros** [YunoHost/issues#2492]
### Describe the bug

Nextcloud cannot be installed, because the requested [nextcloud-29.0.9.tar.bz2](https://download.nextcloud.com/server/releases/nextcloud-29.0.9.tar.bz2) does not exist on theserver.

### Context

- Hardware: *Virtual machine on AMD64*
- YunoHost version: 11.3.02
- I have access to my server: *Through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch: Current version: 29.0.9~ynh1

### To reproduce

Install Nextcloud from applications catalogue

### Expected behavior

Nextcloud should be installed

### Logs

https://paste.yunohost.org/raw/anuforodag

**Comment by orhtej2** [comment]
Duplicate of YunoHost-Apps/nextcloud_ynh#756

**Comment by Plumeros** [comment]
Thanks for the link to the existing issue. I think we can close this one as  duplicate then.
