### ISSUE TITLE
Can't enable/disable Compress Backups in Tools->Yunohost settings->Other

### ISSUE THREAD

**Issue by wheeljack73** [YunoHost/issues#2496]
### Describe the bug

When trying to enable or disable the 'Compress Backups' option in the Webadmin Tools->Yunohost settings->Other screen, I get an error. 

If I use the command:
`yunohost settings set misc.backup.backup_compress_tar_archives -v 1`

This WILL enable the option without any issue.

The error simply states unexpected server error, with the following traceback (note: the error window itself looks like it may have cut some information off):

```
Traceback

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 473, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 561, in process
    return func(**arguments)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/log.py", line 483, in func_wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/settings.py", line 102, in settings_set
    return settings.set(key, value, args, args_file, operation_logger=operation_logger)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py", line 577, in set
    self.form = self._ask(
                ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py", line 855, in _ask
    ) or not section.is_visible(context):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py", line 169, in is_visible
    return evaluate_simple_js_expression(self.visible, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/form.py", line 216, in evaluate_simple_js_expression
    return evaluate_simple_ast(node, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/form.py", line 104, in evaluate_simple_ast
    return context[node.id]
           ~~~~~~~^^^^^^^^^
KeyError: 'security_experimental_enabled'

While processing the action the server said:
```

### Context

- Hardware: YunoHost installed on 2 VPS purchased from SSDNodes.  Debian 12 clean install, updated and then YunoHost installed.
- YunoHost version: 12.0.7
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No

### To reproduce

1. Log into YunoHost admin page.
2. Go to Tools.
3. Go to YunoHost settings.
4. Click 'Other' tab.
5. Enable option for 'Compress Backups'.
6. Click 'Save'.

### Expected behavior

The 'Compress Backups' option to be enabled, and not get an error.

### Logs

No log generated for it, and the error dialog itself seems to cut off, as I was  expecting to see further info after the last visible line that reads 'While processing the action the server said'.  Same error in Firefox and Edge - screenshot below.

![Screenshot 2024-12-06 at 19-43-03 YunoHost settings _ Tools YunoHost Admin](https://github.com/user-attachments/assets/01ca3ab7-357f-4784-b2ac-57707234c312)

**Comment by Axolotle** [comment]
Same as https://github.com/YunoHost/issues/issues/2476
