### ISSUE TITLE
the italian install wiki page is broken https://doc.yunohost.org/it/install (set the language to italian)

### ISSUE THREAD

**Issue by marzagheddon** [YunoHost/issues#2507]
### Describe the bug

the italian install wiki page is broken https://doc.yunohost.org/it/install (set the language to italian)

### Context

Brave Browser 1.73.104

### To reproduce

go to https://doc.yunohost.org/it/install , set the language to italian (if it is not already) and you het this error:
Server Error
Sorry, something went terribly wrong!

0 - Unexpected "else" tag (expecting closing tag for the "if" tag defined near line 562) in "@Page:/var/www/grav/user/pages/02.administer/10.install" at line 563.
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

### Expected behavior

Display the correct page

**Comment by Tagadda** [comment]
Fixed thanks to @orhtej2 ❤️
