### ISSUE TITLE
Add IPv6 DNS records

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#259]
###### Original Redmine Issue: [259](https://dev.yunohost.org/issues/259)

Author Name: **moul**

---

[All our machines excepted the Demo one handle IPv6](https://dev.yunohost.org/documents/1).

We could add IPv6 wildcards DNS records.

**Comment by Psycojoker** [comment]
I think that's done now that samourai uses ipv6

Closing this as a clean procedure, reopen if needed.
