### ISSUE TITLE
dnsmasq domain conf should match 'yunohost domain dns-conf' to ease being your own DNS authority on the domain

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#267]
###### Original Redmine Issue: [267](https://dev.yunohost.org/issues/267)

Author Name: **julienmalik**

---

spf does not specify ip addresses (v4 and v6)

there is a jabber txt record in dnsmasq, but not in dns-conf

no dkim/dmarc in dnsmasq

no muc/pubsub/vjud in dnsmasq

**Comment by Psycojoker** [comment]
> Status Changed: In Progress

@alexAubin that's done?

**Comment by alexAubin** [comment]
For dyndns yes, but not for dnsmasq https://github.com/YunoHost/yunohost/blob/unstable/data/templates/dnsmasq/domain.tpl but I don't know if that's even relevant or not ...

**Comment by alexAubin** [comment]
Ok whatever, let's say it's good enough now

**Comment by derfabianpeter** [comment]
Ping. Not really good enought now. The missing DMARC/DKIM Records [in here](https://github.com/YunoHost/yunohost/blob/unstable/data/templates/dnsmasq/domain.tpl) are the one missing piece to run Yunohost mostly stand-alone without manually configuring external DNS servers, which would be amazing.

From what I can tell, still the correct SPF, DKIM and DMARC records are missing from the dnsmasq config. Doesn't seem like a major thing to implement as all of there records are created automatically, right?

**Comment by Psycojoker** [comment]
Reopening then.

> Doesn't seem like a major thing to implement as all of there records are created automatically, right?

Should be fine but I'm absolutely not familiar with this part of the code so I can't tell.

**Comment by alexAubin** [comment]
Closing because it's been opened forever and "being your own DNS authority" sounds out of scope and imply too many risks
