### ISSUE TITLE
Automatic rollback if a regen config broke a package config (aka: service doesn't managed to reload itself)

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#271]
###### Original Redmine Issue: [271](https://dev.yunohost.org/issues/271)

Author Name: **Bram**

---

More like an idea to explore this current problem : right now regenconf simply run and doesn't do any testing or equivalent of a service behavior after it has modified its configuration, therefor it can break a working YunoHost instance.

A solution to that could be to have this workflow:

* regenconf
* test that config is valid:
   * either by reloading the service and see if the reloading works
   * pass a linter of something like that on the config file
* if the config is not valid, rollback its changes

**Comment by Psycojoker** [comment]
Not sure if that's really needed, we don't have bugs like that anymore.
