### ISSUE TITLE
Have a way to check the integrity of the YunoHost installation

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#275]
###### Original Redmine Issue: [275](https://dev.yunohost.org/issues/275)

Author Name: **Bram**

---

The idea is to have a script (maybe in the diagnostic command or called by diagnostic) that checks a series of information to determine that an installation seems to be in a correct state.

Here is a beginning of a list of information to check:

* there is the mysql password in /etc/yunohost/mysql
* mysql is running
* except is disabled the api is running
* ldap is running
* it is possible to log with the admin user of ldap
* the yunohost command can run
* email server is working
* maybe check for errors in logs?
* firewall is running
* fail2ban is running

Don't hesitate to edit the description of this ticket to add more items to the list.

**Comment by Psycojoker** [comment]
That shouldn't be that hard to do since we now have the diagnosis command.

**Comment by alexAubin** [comment]
Related to https://github.com/YunoHost/yunohost/pull/534

**Comment by alexAubin** [comment]
Closing this because I don't know what do with it, most of the stuff listed are covered by the diagnosis
