### ISSUE TITLE
[idea] auto repair/reload daemon that ensure that YunoHost is always in a desiderated state

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#277]
###### Original Redmine Issue: [277](https://dev.yunohost.org/issues/277)

Author Name: **Bram**

---

This is in the continuation of "for neutrinet there is a crontab that ensure that the vpn is running 100% of the time". This would be a generalist approach to this question probably connected to https://dev.yunohost.org/issues/275

The idea is that since we know that for a list of situation how to fix it, to actually have a daemon that fix that:

* for example, the api is not running on curl localhost:apiport/stuff return an error code know to mean "api is broken" reload it
* [service that should be running] is not running -> restart it
* php5-fpm can't reload because a file has a broken syntax -> rename file, reload
* nslcd bullcrap ...

Those are just examples but we end up collecting a lot of them during support.

The daemon should have a good logging saying what he has done and why and the possibility to be disabled easily globally or for certain rules.

For the annecdote, facebook actually got something like that for their servers farm.

**Comment by alexAubin** [comment]
Closing because too vague, nowadays things are much more stable, the diagnosis helps a lot ... I don't know what to do about savagely restarting services if they are failed ... they are usually failed for a reason and force-restarting ain't gonna help ...
