### ISSUE TITLE
UX: the "path" argument of an app installation is ambiguous

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#288]
###### Original Redmine Issue: [288](https://dev.yunohost.org/issues/288)

Author Name: **Bram**

---

I've got the case of one user thinking that "path" while installing an app is the filesystem path and not the url path and tried to used that to install an app on a HDD.

**Comment by alexAubin** [comment]
Closing because too much legacy now ... Also the question is now standardized since 4.1 or 2, and text got clarified in 4.3
