### ISSUE TITLE
Apps breaking important parts of the system effectively break the system for everybody...

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#289]
###### Original Redmine Issue: [289](https://dev.yunohost.org/issues/289)

Author Name: **Anonymous**

---

If dpkg ends up in a broken state, it will ask to be runed with "apt-get install -f" or "apt-get update -a --configure", if the user don't know how to use a shell he won't be able to install a app after that.

Tbh, I don't know how we should fix this situation. Should we run a check before installing and auto fix this situation?

**Comment by alexAubin** [comment]
This is a big issue (or "parti pris") of Yunohost as it does not uses containerization.

There is no simple answer to this issue unless we find a way to automatically log every small modification an app makes on the system, and be able to rollback all of them (assuming it's even possible, c.f. 'rm') if it broke something (assuming we're able to actually detect that something broke)

**Comment by alexAubin** [comment]
Closing because there's no real fix for this, cf previous comment
