### ISSUE TITLE
add (more) logging inside of ssowat

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#291]
###### Original Redmine Issue: [293](https://dev.yunohost.org/issues/293)

Author Name: **Bram**

---

Right now we barely have anything, this make things annoying to debug.

**Comment by Psycojoker** [comment]
WIP (but dead :() here https://github.com/YunoHost/SSOwat/pull/78

**Comment by alexAubin** [comment]
It's kind of implemented now, we can enable debugging by putting `"logging": "debug"` (or something like that) in conf.json.persistent and logs go to /var/log/nginx/ssowat.log
