### ISSUE TITLE
Respect W3C recommandation for user name.

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#296]
###### Original Redmine Issue: [296](https://dev.yunohost.org/issues/296)

Author Name: **Anonymous**

---

Personal name is a complex matter, especially if we have to deal with name from all around the world. W3C have an article[1] on the subject and there is another article[2] quite shorter with a bit of humor.

The problem is with the user creation form. Having a Fullname field split in two is no best practice. These fields require at least two letter which is plain wrong (some people have single letter name). If an erroneous value is supplied, the error message refer to firstname or lastname which isn't user friendly as theses string aren't displayed on the form.

The easiest solution would be to offer a single field named "display name". It will solve all these internationalization issue and is pretty close to the W3C recommandation.

[1] https://www.w3.org/International/questions/qa-personal-names
[2] http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by eauchat** [comment]
+1 to having only one field that could be called display name.

As mentioned in #704, many people don't want to use their real name. Often, creating a new user I stumble upon what am I gonna put in those fields and end up cutting the username in two to fill the mandatory fields.

Maybe this is a stupid suggestion, but if LDAP requires the two fields to be properly set, couldn't one of them only be used as display name, and the other filled with a dummy value.
Maybe a value not too absurd like "ynh", or simply replicating the value of the first field. I don't know what would be the best option. It's true it would be annoying to see the name written twice in apps using LDAP integration. Or if LDAP accepts custom characters, it could simply be "*" or "-".

**Comment by zamentur** [comment]
If we put dummy value, we should check LDAP bind in each apps, to be sure this dummy value is not displayed

**Comment by alexAubin** [comment]
Done in https://github.com/YunoHost/yunohost/pull/1516
