### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#303]
###### Original Redmine Issue: [303](https://dev.yunohost.org/issues/303)

Author Name: **moul**

---

## Flattr
- This a non-free service and software which take [10% fee](https://flattr.com/faq#0).
- Our [Flattr account](https://flattr.com/profile/YunoHost) was created more than a year ago.
- We must have more than 20€.
- Opi and Moul have an account on this YunoHost profile.
- We can withdraw this money to a bank account.

## Liberapay
- This is a [free software](https://github.com/liberapay/liberapay.com) which take [2.1% fee](https://liberapay.com/about/faq).
- This is a [fork](https://changaco.oy.lc/blog/goodbye-gratipay/) of [Gratipay](https://gratipay.com/).
- [YunoHost team](https://liberapay.com/YunoHost) was created the 29 April 2016.
- Each member of YunoHost team can withdraw between zero and his maximum part.
- If nothing is taken, nothing will be taken from donators.
- It is not possible to withdraw for an other entity
- Take a look at [Team management](https://liberapay.com/about/teams)

## What do we do with this money?
- We can pay servers and domain names.
- Take it for us.

**Comment by cyxae** [comment]
https://donate.yunohost.org
This issue may be closed :)

**Comment by alexAubin** [comment]
Indeed, cheers !
