### ISSUE TITLE
Lightweight web analyser

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#304]
###### Original Redmine Issue: [304](https://dev.yunohost.org/issues/304)

Author Name: **moul**

---

I am searching a lightweight web analyser.
[Piwik](https://piwik.org/) is too heavy and is [hard to maintain](https://github.com/maniackcrudelis/piwik_ynh_2).
This is the kind of app I am ready to package for YunoHost
The best one, I could find is [HummingBird](http://projects.nuttnet.net/hummingbird).
HummingBird is no more maintained and I did not succeed to install it on ARM.

**Comment by alexAubin** [comment]
Sounds like it's an old app-related issue so closing
