### ISSUE TITLE
Add a 'storage' category to manage/talk to other filesystems, protocols, ...

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#305]
###### Original Redmine Issue: [305](https://dev.yunohost.org/issues/305)

Author Name: **jerome**

---

This new **storage** category should be able to manage *places* - i.e. an SFTP access to another server - and "talk" to them - e.g. get or put a file into it.

This could be helpful at first for the backup/restore system, in order to be able to save/restore the system directly outside from the server's filesystem - and by the way improve backup/restore performances and time.

**Comment by alexAubin** [comment]
Meh i dunno if we'll ever do anything with this issue (apart from backup location which is a different topic than handling storage generally speaking)

**Comment by alexAubin** [comment]
Superseded by https://github.com/YunoHost/issues/issues/1823
