### ISSUE TITLE
Add possibility to change the status public or private on an installed app

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#306]
###### Original Redmine Issue: [306](https://dev.yunohost.org/issues/306)

Author Name: **moul**

---

This could be done by scripts inside the package or if it's generic it could be integrated to `yunohost` command.

**Comment by alexAubin** [comment]
I believe this is related to the work on config panel / app actions

**Comment by Psycojoker** [comment]
Yes, it's released but not yet out of experimental.

**Comment by alexAubin** [comment]
Might also be solved by https://github.com/YunoHost/yunohost/pull/797

**Comment by alexAubin** [comment]
Closing because this is pretty much fixed by the permission system in 3.7
