### ISSUE TITLE
Restrict access to applications

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#309]
###### Original Redmine Issue: [309](https://dev.yunohost.org/issues/309)

Author Name: **Anonymous**

---

I have installed owncloud and wordpress and want to limit access to those apps to only one user. I have set up the relevant permissions in the admin backend and the user who should not have access also cannot see the apps in the yunohost portal. But when accessing them directly (e.g. via /owncloud or /blog) the user without access permissions still can log in to those apps.

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost/pull/585 and following works
