### ISSUE TITLE
Add a mechanism to declare that an app is related to some specific log files

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#310]
###### Original Redmine Issue: [310](https://dev.yunohost.org/issues/310)

Author Name: **Bram**

---

This is a "I'm helping someone right now and I don't want to lose this information" ticket.

Task check if those log files for owncloud are displayed in logfile:

    /home/yunohost.app/owncloud/data/owncloud.log
    /var/www/owncloud/data/owncloud.log (but this one is empty)

**Comment by alexAubin** [comment]
Related to @zamentur's work on log files https://github.com/YunoHost/yunohost/pull/777 (and others)

**Comment by alexAubin** [comment]
(Maybe to be implemented in packaging v3)

**Comment by alexAubin** [comment]
Closing, cf packaging v3 wishlist
