### ISSUE TITLE
Add a "force" option on app upgrade

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#33]
###### Original Redmine Issue: [33](https://dev.yunohost.org/issues/33)

Author Name: **Anonymous**

---

When an application is already at the latest version, yunohost app upgrade is a no-op.
Implement a "-f" option to force the upgrade, whatever the version check result is.

**Comment by alexAubin** [comment]
Implemented in https://github.com/YunoHost/yunohost/pull/864
