### ISSUE TITLE
[fr] Interpréter les couleurs echo -e "\e" dans l'install avec --verbose durant l'install d'application

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#338]
###### Original Redmine Issue: [338](https://dev.yunohost.org/issues/338)

Author Name: **maniack_crudelis**

---

En 2.2, les couleurs de shell placées avec echo -e "\e..." sont correctement interprétée.
En 2.4, la nécessité d'usage de --verbose sur yunohost app install semble casser l'interprétation des couleurs.

Utiliser echo -e "\e[91m \e[1m" peut pourtant être intéressant pour signaler une erreur d'install lors de la capture de signaux avec trap.

**Comment by alexAubin** [comment]
Closing because not really important .. also that was done in the past and indeed breaking the webadmin display .. I don't think apps should send their own colored stuff ...
