### ISSUE TITLE
SSL certificate management

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#35]
###### Original Redmine Issue: [35](https://dev.yunohost.org/issues/35)

Author Name: **Anonymous**

---

Add an action to allow the update of an SSL certificate which will replace the current one on the server. It may also be useful to allow reverting to the self-signed certificate or to generate a new one.

**Comment by alexAubin** [comment]
Meh, honestly I would just close this ticket ... Not using Let's Encrypt is an advanced used case. I suppose there are legit use cases, but there's a documentation page about how to do handle non-LetsEncrypt certs.

**Comment by Psycojoker** [comment]
Agree, that's something I would accept as an external contribution but I don't find it worth it for our users that we put our time in that.
