### ISSUE TITLE
OpenVPN Security

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#353]
###### Original Redmine Issue: [353](https://dev.yunohost.org/issues/353)

Author Name: **Anonymous**

---

I am concerned about OpenVPN security. While I believe that authenticating to the web interface or ssh login is somewhat protected from brute force attacks by, for example fail2ban, I don't believe that OpenVPN is protected by fail2ban as configured. I propose that the OpenVPN application be upgraded to enable a reasonably secure fail2ban configuration (if possible).

Apologies if I have misunderstood the fail2ban config and such protection is, in fact, already enabled.

**Comment by alexAubin** [comment]
That sounds like an app-related issue since we don't include open vpn in YunoHost vanilla :s
