### ISSUE TITLE
add rsync support option for backup system

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#356]
###### Original Redmine Issue: [356](https://dev.yunohost.org/issues/356)

Author Name: **aymhce**

---

If user have huge data to save (1 or 2 To ...), I think use rsync rather than simple copy is more efficient, without tar.gz of course.
In first time, the idea is to add option, like "--rsync" to backup.py script

(for your information, in my case, I mount external HDD to rsync files)

**Comment by alexAubin** [comment]
In the meantime, one can now "easily" extend the backup system with a custom backup method...

**Comment by alexAubin** [comment]
Closing because this is 8 years old and we ain't gonna do it I suppose. The plan is to go for Borg or Restic in the core some day before the end of mankind. There's also the archivist app that does use rsync iirc
