### ISSUE TITLE
IDN support

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#36]
###### Original Redmine Issue: [36](https://dev.yunohost.org/issues/36)

Author Name: **Anonymous**

---

The domain matching pattern in the .yml is always rejecting IDNs (ex: café.com). 

I suppose yunohost is not built to support IDNs at all. Therefore at least update the web interface and tell people to use the punycode version (xn--) in case they want to use IDNs.

**Comment by alexAubin** [comment]
Fixed/improved recently by ljf
