### ISSUE TITLE
NAT-PMP support

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#37]
###### Original Redmine Issue: [37](https://dev.yunohost.org/issues/37)

Author Name: **Anonymous**

---

For those who don't have UPnP working, fall back to NAT-PMP (or vice versa). `libnatpmp` to the rescue.

**Comment by alexAubin** [comment]
Anybody has some insights about how NAT-PMP is commonly supported on regular ISP boxes ?..

**Comment by alexAubin** [comment]
Closing because probably wontfix, we already have trouble maintaining UPnP
