### ISSUE TITLE
Add a warning when trying to add another domain in noho.st or nohost.me

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#373]
###### Original Redmine Issue: [373](https://dev.yunohost.org/issues/373)

Author Name: **julpec**

---

It should be great to have a warning if the user try to add another domain in noho.st or nohost.me

For example : "you already have a subdomain in noho.st or nohost.me and you can't get another one"

**Comment by Axolotle** [comment]
same as https://github.com/YunoHost/issues/issues/1076 ?

**Comment by andretheolauret** [comment]
> same as #1076 ?

I guess too

**Comment by tituspijean** [comment]
Not quite a duplicate, but anyways contrary to https://github.com/YunoHost/issues/issues/1076#issuecomment-757506501, it seems that there is indeed a warning displayed now. Closing!
