### ISSUE TITLE
Bug in Restore function with web administration

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#378]
###### Original Redmine Issue: [378](https://dev.yunohost.org/issues/378)

Author Name: **inrepublica**

---

When I try to restore an app with web administration i have an error: "Vous devez préciser ce qui est à restaurer"
With moulinette it work properly.

How to reproduce:
- Install an app (ttrss for example)
- Make a backup (only this app)
- Try to restore this backup
- A Message appears: "Vous devez préciser ce qui est à restaurer"
![](http://i.imgur.com/Sn1xbrK.png)

**Comment by Psycojoker** [comment]
> Is it still the case today?

**Comment by alexAubin** [comment]
Closing because that sounds like a minor bug and lack of feedback :/
