### ISSUE TITLE
Specify the allowed characters / pattern for app id

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#382]
###### Original Redmine Issue: [382](https://dev.yunohost.org/issues/382)

Author Name: **jerome**

---

There is currently no specification on the *id* of an app neither documentation about the forbidden characters - such as `?`. Even if it goes without saying, it could not be the same in the `yunohost`code - i.e. - character was not considered, see commit:yunohost|6ad0083f04553c067d4bcea97a9fa8c11d0acccc.

We should agree on such specification, add it in the documentation and follow it in the source code of `yunohost` and app linter.

**Comment by Psycojoker** [comment]
I don't think that really relevant anymore, isn't it? Closing it, reopen if needed.
