### ISSUE TITLE
Add logo/icons in applications 

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#383]
###### Original Redmine Issue: [383](https://dev.yunohost.org/issues/383)

Author Name: **moul**

---

Logos of applications could be displayed on:

- user interface, on tilles
- admin interface, in app section

We could store the logo of the application in the package and specify the name of the image in the manifest.
That is how it's [handle with Firefox OS apps](https://github.com/soapdog/memos-for-firefoxos/blob/master/manifest.webapp#L15-L18).

We must specify an image format png/250×250px for instance.

**Comment by Baton4986** [comment]
Can't wait for this :+1:

**Comment by alexAubin** [comment]
Closing as pretty-much done
