### ISSUE TITLE
Diagnosis Disks does not handle string

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#386]
###### Original Redmine Issue: [386](https://dev.yunohost.org/issues/386)

Author Name: **Anonymous**

---

Bonjour,

Je ne suis pas capable de donner un meilleur nom mais le diagnosis ne fonctionne pas juste après une mise à jour vers 2.4 sur un serveur qui était déjà debian 8.
http://paste.yunohost.org/zudibotesi.txt

Pour info:

````lstronic# yunohost monitor disk -fH
simfs: not-available````

Léo

**Comment by alexAubin** [comment]
Closing because that's an old issue with lack of recent feedback or people reproducing ...
