### ISSUE TITLE
Can't consult firewall log

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#393]
###### Original Redmine Issue: [393](https://dev.yunohost.org/issues/393)

Author Name: **ljf**

---

Hi,

In the web admin, I would get log of firewall service but I couldn't.

I got a 403 on 
https://stable.local/yunohost/api/services/yunohost-firewall/log?number=50&locale=fr

I am not alone:
https://forum.yunohost.org/t/no-access-to-logs-yh-2-4-0-4/1571

**Comment by Psycojoker** [comment]
There is not logs for yunohost-firewall https://github.com/YunoHost/yunohost/blob/ebd5b33c31a5af75f9f20407873b08ef24488f0a/data/templates/yunohost/services.yml#L34

Do we need some?
