### ISSUE TITLE
 yunohost monitor update-stats day throughs xmlrpclib errors / Glances integration is randomly broken

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#395]
###### Original Redmine Issue: [395](https://dev.yunohost.org/issues/395)

Author Name: **Anonymous**

---

Crontab job /etc/cron.d/yunohost-monitor frequently throughs the following errors and posts is to the root account. 

```
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 212, in <module>
    password=opts.password, parser_kwargs={'top_parser': parser}
  File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 138, in cli
    moulinette.run(args, output_as=output_as, password=password)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 352, in run
    ret = self.actionsmap.process(args, timeout=5)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 467, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/monitor.py", line 315, in monitor_update_stats
    monitor = _monitor_all('day')
  File "/usr/lib/moulinette/yunohost/monitor.py", line 621, in _monitor_all
    result['system'] = monitor_system()
  File "/usr/lib/moulinette/yunohost/monitor.py", line 284, in monitor_system
    result[u] = json.loads(glances.getProcessCount())
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: '<class \'Exception\'>:method "getProcessCount" is not supported'>
```

This has started after a very recent upgrade to the latest software on a brique

1. yunohost -v                                                                               
yunohost: 2.4.0.6
yunohost-admin: 2.4.0.1
moulinette: 2.4.0.1
ssowat: 2.6.0

**Comment by Psycojoker** [comment]
Do we still get reports about that?

**Comment by alexAubin** [comment]
Personally I would just get rid of glances ... This part got absolutely not maintained since 2~3 years and we regularly get people confused because sometimes glances is not running and a corresponding error is displayed in the webadmin ... I'm not convinced having glances running really is useful

**Comment by alexAubin** [comment]
More stuff that make me want to get rid of glances if nobody is willing to maintain it : 
- https://github.com/YunoHost/issues/issues/1093
- https://github.com/YunoHost/issues/issues/1225
- https://forum.yunohost.org/t/erreur-avec-le-service-glances-errno-1/5719
- https://forum.yunohost.org/t/resolu-impossible-de-superviser-le-systeme-le-suivi-de-l-etat-du-serveur-n-est-pas-active/8196
- (and more similar posts on the forum)

all of this for a small bunch of technical info in the `Monitor` panel which afaik ain't so inteteresting (and all the actually revelant infos, we could get without glances)

**Comment by Psycojoker** [comment]
> the Monitor panel which afaik ain't so inteteresting 

I still get reports of people that uses it and find it useful :/

That's probably something on which we could launch a thread of the forum before making decision if we ever find one day the time to invest in that part of the code.

**Comment by alexAubin** [comment]
So today, yet another user complaining about glances ...

If nobody is willing to or have time to maintain it, I propose to just remove it. I propose to do so in 6 months if nobody commits to maintaining it ...

**Comment by Psycojoker** [comment]
> I still get reports of people that uses it and find it useful :/

I'm not really for it :/ (or at least without offering something else as an alternative like doing so with pslib)

**Comment by alexAubin** [comment]
Removed in https://github.com/YunoHost/yunohost/pull/821
