### ISSUE TITLE
Improve default app management on a domain

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#40]
###### Original Redmine Issue: [40](https://dev.yunohost.org/issues/40)

Author Name: **Anonymous**

---

The current `app_makedefault` action was done as a quick helper - i.e. it just allows to quickly redirect a domain root to an app. Considering the idea, it should be great to improve it by:

- adding/reviewing actions in order to set, remove and get the default app for a domain
- managing it in the generated SSOwat conf - and not in the persistent one as now
- remove this redirection when the default app is uninstalled

**Comment by alexAubin** [comment]
This should be much easier to achieve once the domain settings introduced in https://github.com/YunoHost/yunohost/pull/1194 are merged
