### ISSUE TITLE
Roundcube activates owncloud carddav whatever the owncloud configuration

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#401]
###### Original Redmine Issue: [401](https://dev.yunohost.org/issues/401)

Author Name: **julienmalik**

---

The owncloud carddav preset is activated when owncloud is installed, even if it does not provide a carddav service.

With owncloud 8 installed, I did not see the owncloud carddav setting in roundcube.
After installing owncloud 9, I can see the preset has been activated.
So in the roundcube address books tab, I have now 2 carddav accounts, and one of them points to /dev/null (but no error is reported in roundcube). I can add new contacts there, and it will just silently *not* synchronize anywhere.

**Comment by alexAubin** [comment]
Sounds like an old app issue so closing
