### ISSUE TITLE
Edit Button on Yunohost.org

### ISSUE THREAD

**Issue by MatheusRV** [YunoHost/issues#41]
How was the edit system implemented? This is awesome for an opensource project I'm handling, could someone explain how it works and how I get something similar? Tks a lot

**Comment by Psycojoker** [comment]
Hello,

This is an old custom development specifically made for YunoHost. You can find the code here https://github.com/YunoHost/Simone but it lacks good deployement instructions :/

It pushes everything on https://github.com/YunoHost/doc so if you dig a bit into it you can adapt it for your own needs I guess.

**Comment by alexAubin** [comment]
(Haha actually this issue repo is not meant for production yet, I wonder how you found it :stuck_out_tongue: )

Anyway, about Simone, feel free to come [chat with us](https://chat.yunohost.org/) in the devroom if you need more infos !
