### ISSUE TITLE
managing disks with yunohost interface

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#418]
###### Original Redmine Issue: [418](https://dev.yunohost.org/issues/418)

Author Name: **Anonymous**

---

Do fstab operations like for YunoHost, mounting/unmount hardrives and so on.

**Comment by alexAubin** [comment]
I'm closing this because we already had a similar PR about this from vlotho and concluded it was a really tricky idea - personally I'm not sure this is in YunoHost's scope...

**Comment by Psycojoker** [comment]
vlotho PR was really about disc partitioning and low level operation, this one is way more about doing expected things like detecting harddrives and other (pretty much like fstab).

This is something that is often done/used on internet cube when you had a new sdd or things like that and I frequently encounter people that wants this kind of things in YunoHost.

I think we should reopen that.

**Comment by alexAubin** [comment]
Hmmm okay, though to me according to the description it's " create a partition table and modify partitions (name, size, type)".

But why not if it's really about fstab-like stuff to automatically mount external drives

**Comment by Psycojoker** [comment]
Ah, we can modify it then, I know the "be a fstab-like" stuff is needed, partition seems indeed out of scope.

**Comment by Psycojoker** [comment]
Modified it.

**Comment by alexAubin** [comment]
Closing because really sounds duplicated of https://github.com/YunoHost/issues/issues/305
