### ISSUE TITLE
Special dropdown inputs sometimes are text inputs

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#43]
###### Original Redmine Issue: [43](https://dev.yunohost.org/issues/43)

Author Name: **Anonymous**

---

Hi,

On yunohost-admin/testing 2.1.5, sometimes I have a dropdown input (list of users or domains) replaced by a text input.
Maxime says that he got pages with dropdown and pages with text input with the same app, so same manifest...

Thanks for this new version.

**Comment by Psycojoker** [comment]
Do we still have this bug :/?

**Comment by alexAubin** [comment]
Yes :s

**Comment by Psycojoker** [comment]
For a totally unrelated reason I finally end up finding the cause of this bug and it's pretty annoying.

It's a race condition between those 3 AJAX GET and the form building:

- https://github.com/YunoHost/yunohost-admin/blob/df67dd6a440ce1d2bc69798a75103a1b1b79127a/src/js/yunohost/filters.js#L21
- https://github.com/YunoHost/yunohost-admin/blob/df67dd6a440ce1d2bc69798a75103a1b1b79127a/src/js/yunohost/filters.js#L28
- https://github.com/YunoHost/yunohost-admin/blob/stretch-unstable/src/js/yunohost/controllers/apps.js#L350

The result of the 2 first GET are used here:

- https://github.com/YunoHost/yunohost-admin/blob/stretch-unstable/src/js/yunohost/controllers/apps.js#L271
- https://github.com/YunoHost/yunohost-admin/blob/stretch-unstable/src/js/yunohost/controllers/apps.js#L255

If those 2 requests aren't done once we reach this part of the code, the fields will be text inputs.

To solve this we would need to make those 3 ajax requests dependents (one way would be to stop using magic filters based on regex on the url that are in a totally unrelated file which makes the code hard to grasp)

**Comment by SilverViper** [comment]
This is still a thing.

**Comment by alexAubin** [comment]
(Probably solved indirectly by https://github.com/YunoHost/yunohost-admin/pull/316 )
