### ISSUE TITLE
impossible de désactiver yunohost-api

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#431]
###### Original Redmine Issue: [431](https://dev.yunohost.org/issues/431)

Author Name: **Anonymous**

---

Pour des raisons de sécurité, il est conseillé de désactiver yunohost-api
Le problème est que même désactivé yunohost-api se relance toujours au démarrage de la machine
Pourtant dans la rubrique service de ladite api il est indiqué
(url /yunohost/admin/#/services/yunohost-api)

    Services
    yunohost-api

    Statut
           Lancer au démarrage :             
            Désactivé
            Statut :             
            En cours d'execution

Si on passe par la moulinette le résultat est le même
"yunohost service stop yunohost-api" arrête le service
mais
"yunohost service disable yunohost-api" ne le désactive pas, après reboot yunohost-api est de retour bien actif.

**Comment by Psycojoker** [comment]
Isn't this supposed to be solved by systemd?

**Comment by alexAubin** [comment]
I guess it's solved, didn't hear much more 'bout this ... I guess maybe an old issue with 'yunohost service disable"
