### ISSUE TITLE
Readd a domain name after removing it don't record it

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#436]
###### Original Redmine Issue: [436](https://dev.yunohost.org/issues/436)

Author Name: **moul**

---

I think that when you manually remove then you readd a domain name, the record don't works.

As you could see [here](https://forum.yunohost.org/t/nohost-domain-recovery/442/90?u=moul).

**Comment by Psycojoker** [comment]
Linked to that I think  https://github.com/YunoHost/issues/issues/1004 so let's close it as duplicated.
