### ISSUE TITLE
Build Yunohost for aarch64 / arm64

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#438]
###### Original Redmine Issue: [438](https://dev.yunohost.org/issues/438)

Author Name: **Anonymous**

---

There is no yh package for the arm64 architecture (also known as aarch64).
This is the Pine64 arch and while it's a low cost solution, it should be great to provide YH for this board.

**Comment by alexAubin** [comment]
This is now done for 3.0+ with vinaigrette ... the only issue being that rspamd does not compile properly right no. But since I see many issue about it on their bugtracker, it might be solved at some point :s

**Comment by alexAubin** [comment]
Closing thanks to the help of @randomstuff who found that compiling rspamd for arm64 works if you disable luajit and torch as explained in https://github.com/vstakhov/rspamd/issues/2202#issuecomment-401545304 :+1: 

Also thanks to @taziden to validate that the build worked :+1: 

I might create a repo later for yunohost/rspamd with the patch, in the same way that we do for metronome. That would also allow to have better tracking of the changelog.

**Comment by CuriousCocainist** [comment]
Question in relation to the above: 
As the issue was resolved over a year ago, is Yuno 3.6 capable to work on aarch64 / arm64 hardware (e.g. Pine boards)...? Or is it enough to be able to install ARMbian (Bionic) on it and then Yuno on top? 

I'm confused and would like to buy some SBC with SATA connector as a home to Yuno

**Comment by alexAubin** [comment]
Both should work, yes

The only thing is that building image for all the variety of boargs out there - and especially *test* them is hell of a work and require to own a board to actually test that the image makes sense. So far we only build images for "classic" boards like the RPi that people can easily test (and even then it's tricky to test all version of RPi and e.g. there's an issue with RPi1 as far as I heard)

However, we have a build chain that theoretically allows us to build images for any board supported by ARMbian - we would just need somebody available on the long term to test the corresponding image(s).

Anyway, in any case : YunoHost can be installed on top of any Debian (or Armbian / Raspbian which are just "ports" of Debian to ARM, at least as far as I understand) so you can install on top of it. Be careful though that it won't be installable on top of a Ubuntu system though ... so not Bionic, but rather the Debian flavor of ARMbian ...

**Comment by CuriousCocainist** [comment]
Thanks for the rapid answer :)
I'm starting to understand the challenges of this project...

I (got) mixed up with that "Bionic"... I was just wondering if Yunohost will work on the new Debian Buster-based ARMbian or previous version, built on Strech, has to used.

Thanks for your efforts towards de-cloudyfying solutions :+1:

**Comment by alexAubin** [comment]
>I was just wondering if Yunohost will work on the new Debian Buster-based ARMbian or previous version, built on Strech, has to used.

For now we only support Stretch ... you can follow the progress in https://github.com/YunoHost/issues/issues/1255

**Comment by searoso** [comment]
Does link to this issue from https://yunohost.org/#/install_on_arm_board is still relevant?

**Comment by alexAubin** [comment]
searoso : Indeed it's probably not relevant anymore now that the issue is fixed

**Comment by rzr** [comment]
So the webpage should be updated ? btw can you suggest any reference platform ? I have a dragonboard for testing

**Comment by alexAubin** [comment]
@rzr : Ah yes indeed, I did not realize that we had a warning in the doc ... I updated the page (maybe take ~1 hour to propagate)

I wouldn't now what to recommend in terms of arm64 board as I have little experience with those, I'm more familiar with "regular" armhf board like RPi, Olimex Lime and Orange Pi
