### ISSUE TITLE
Validate type 'path' arguments

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#444]
###### Original Redmine Issue: [444](https://dev.yunohost.org/issues/444)

Author Name: **opi**

---

Currenlty every package have to take care of path validation :

- https://github.com/maniackcrudelis/leed_ynh/blob/master/scripts/.fonctions#L46-L53
- https://github.com/YunoHost-Apps/dokuwiki_ynh/blob/master/scripts/install#L24-L27

**Comment by alexAubin** [comment]
This should now be done automatically : https://github.com/YunoHost/yunohost/blob/unstable/src/yunohost/app.py#L1915
