### ISSUE TITLE
updating system : apt blocked, waiting for input

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#449]
###### Original Redmine Issue: [449](https://dev.yunohost.org/issues/449)

Author Name: **martinkirch**

---

I wanted to update my system (debian packages), but it got stuck and yunohost-api does not answer anymore. I can't access the admin interface.

So I digged a little bit in the logs, and found the culprit in `/var/log/apt/term.log`, which ends like this:

~~~
Setting up php5-cli (5.6.22+dfsg-0+deb8u1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Modified configuration file
---------------------------

A new version (/usr/share/php5/php.ini-production.cli) of configuration file 
/etc/php5/cli/php.ini is available, but the version installed currently has been
locally modified.

  1. install the package maintainer's version
  2. keep the local version currently installed
  3. show the differences between the versions
  4. show a side-by-side difference between the versions
  5. start a new shell to examine the situation

What do you want to do about modified configuration file php.ini? 

~~~

Apparently it's still in interactive mode. System versions:

yunohost: 2.4.0.6
yunohost-admin: 2.4.0.1
moulinette: 2.4.0.1
ssowat: 2.6.0
Linux brique 3.16.0-4-armmp #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) armv7l GNU/Linux

**Comment by alexAubin** [comment]
Related to https://github.com/YunoHost/issues/issues/1232
