### ISSUE TITLE
Allow to override configuration in a local file

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#454]
###### Original Redmine Issue: [454](https://dev.yunohost.org/issues/454)

Author Name: **jerome**

---

It should be possible to override the ownCloud / Nextcloud configuration which comes with the package. A typical use case - which has been already reported, i.e. [here](https://forum.yunohost.org/t/owncloud-cron-php-tourne-en-permanence-occupant-tout-la-memoire/) - is to change the data directory location.

It could be done the same way as for Roundcube, e.g. to look for a `config/local.php` file and include it at the end of `config/config.php`. Note anyway that it should be done with care...

**Comment by Psycojoker** [comment]
I'm not sure it's relevant anymore, close it, let's reopen it if needed.
