### ISSUE TITLE
In cli, when an installation/remove/upgrade failed, display full installation logs

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#458]
###### Original Redmine Issue: [458](https://dev.yunohost.org/issues/458)

Author Name: **Bram**

---

Right now, when we doing an installable on cli and that it failed, we always end up with very useless logs exepect "it failed" which sucks. We spend a lot of time asking people that report us error "add --verbose" which makes everyone lose time.

Instead, when the installation of a similar operation failed, the full log should be displayed, this way everyone will be happy \o/

**Comment by Psycojoker** [comment]
Linked to https://github.com/YunoHost/issues/issues/971 and to https://github.com/YunoHost/yunohost/pull/165

**Comment by alexAubin** [comment]
PR got merged
