### ISSUE TITLE
Documentation directly in the different parts of the webadmin

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#46]
###### Original Redmine Issue: [46](https://dev.yunohost.org/issues/46)

Author Name: **Anonymous**

---

Add documentation to the administration UI + link the related documentation pages directly.

For example, when you add a new domain, you should have an explanation of what it is and the impacts, plus a link to an extensive documentation page.

**Comment by alexAubin** [comment]
Closing because too vague / never-ending issue, it's not clear what should be implemented ...
