### ISSUE TITLE
Having to install Baïkal before AgenDAV is confusing for the user

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#48]
###### Original Redmine Issue: [48](https://dev.yunohost.org/issues/48)

Author Name: **Anonymous**

---

Is Baïkal the server running DAV for AgenDAV to use ? => Wouldn't it be smarter to let it run as a service more than an app ?
Or are they 2 different services => Then the Baïkal app is not really user friendly (according to the demo running right now - a simple message is displayed (Baïkal is running alright) when the app is opened)

**Comment by Psycojoker** [comment]
Still the case today

```
11:56 <@Bram> pouet
11:57 <@Bram> désolé je suis totalement à la ramasse niveau apps, on doit toujours installer baikal avant agendav de nos jours ? 
11:57 <yunobridge_> <Maniack C> Agendav a pas trop bougé
11:57 <@Bram> y a ça qui traine mais je crois que c'est plus d'actualité https://github.com/YunoHost/issues/issues/48
11:57 <@Bram> donc il faut toujours baïkal avant ?
11:58 <yunobridge_> <Maniack C> Oui, il y a une PR sur agendav, mais ça marche pas
11:58 <@Bram> d'accord
11:58 <yunobridge_> <Maniack C> Et c'est resté en l'état depuis novembre
```

**Comment by alexAubin** [comment]
Hmf wontfix
