### ISSUE TITLE
Enable MAM on XMPP server

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#49]
###### Original Redmine Issue: [49](https://dev.yunohost.org/issues/49)

Author Name: **Anonymous**

---

MAM, or Message Archive Management, is used by all state-of-the-art Jabber clients. Somehow, MAM is not enabled for YunoHost (Android Jabber client Conversations indicates so).

In order to make optimal use of the XMPP protocol, please enable MAM by default.

**Comment by Psycojoker** [comment]
related PR for prosody https://github.com/YunoHost/yunohost/pull/240

**Comment by alexAubin** [comment]
To complicate things : it sounds like MAM was a lot improved in Metronome 3.8 / 3.9 (according to the changelog) which is built on the stretch repo

**Comment by alexAubin** [comment]
MAM is enabled in YunoHost - closing because I don't think it's relevant anymore.

https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/templates/metronome/metronome.cfg.lua#L84

 Feel free to reopen or complain to repoen
