### ISSUE TITLE
Get rid of os.system calls

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#5]
###### Original Redmine Issue: [5](https://dev.yunohost.org/issues/5)

Author Name: **Anonymous**

---

It's considered deprecated in favor of [subprocess module](https://docs.python.org/2/library/subprocess.html).

**Comment by decentral1se** [comment]
I've taken a look at this. There is only the remaining calls left:

```
➜  moulinette (packagefix/setuptools-packages-list-and-docs) ✔ grep -iR "os\.system" .
./moulinette/utils/tests/test_process.py:    os.system("rm -rf %s" % TMP_TEST_DIR)
./moulinette/utils/tests/test_process.py:    os.system("mkdir %s" % TMP_TEST_DIR)
./moulinette/utils/tests/test_process.py:    os.system("echo 'foo\nbar' > %s" % TMP_TEST_FILE)
./moulinette/utils/tests/test_process.py:    os.system("chmod 700 %s" % TMP_TEST_FILE)
./moulinette/utils/tests/test_process.py:    os.system("rm -rf /tmp/test_iohelpers/")
./moulinette/utils/tests/test_filesystem.py:    os.system("rm -rf %s" % TMP_TEST_DIR)
./moulinette/utils/tests/test_filesystem.py:    os.system("mkdir %s" % TMP_TEST_DIR)
./moulinette/utils/tests/test_filesystem.py:    os.system("echo 'foo\nbar' > %s" % TMP_TEST_FILE)
./moulinette/utils/tests/test_filesystem.py:    os.system("echo '{ \"foo\":\"bar\" }' > %s" % TMP_TEST_JSON)
./moulinette/utils/tests/test_filesystem.py:    os.system("chmod 700 %s" % TMP_TEST_FILE)
./moulinette/utils/tests/test_filesystem.py:    os.system("chmod 700 %s" % TMP_TEST_JSON)
./moulinette/utils/tests/test_filesystem.py:    os.system("rm -rf /tmp/test_iohelpers/")
./moulinette/utils/tests/test_filesystem.py:    os.system("echo '{ not valid json lol }' > %s" % TMP_TEST_JSON)
```

I was unable to run the tests to validate replacing these. I could use some hints and tips regarding this over at https://github.com/YunoHost/moulinette/pull/200 if anyone has time.

**Comment by decentral1se** [comment]
Well, given the result of https://github.com/YunoHost/moulinette/pull/200#issuecomment-495096393, I am not sure this is really "an issue". I leave it up to you all on what further to do here.

**Comment by alexAubin** [comment]
Uuuh idk, I think the original issue was also about `os.system` calls in yunohost code (not just moulinette). I guess using `os.system` is not so much drama, but possibly it would be nice to rely on more pythonish stuff when it's about doing mv, cp, chown/chmod (and as Bram's pointing out, we're supposed to have small helpers in the moulinette framework to do those).

Still that's quite a lot of work and there can be weird regressions like when there are symlinks or folders in some edgecases, which would be handled differently between bash and python functions

**Comment by Psycojoker** [comment]
Also `os.system` doesn't crash when the command fails and thing like that and that could hide errors making things hard to debug :/

**Comment by alexAubin** [comment]
Closing because pretty much #wontfix, it's not a big deal
