### ISSUE TITLE
Provide a way for app to be hidden from portal

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#50]
###### Original Redmine Issue: [50](https://dev.yunohost.org/issues/50)

Author Name: **julienmalik**

---

Some apps do not fit in the portal :
- baikal has an admin web ui, but is not easily accessible, and not so useful since it comes preconfigured.
- firefox sync does not have any web ui
- mumble ?
- opendkim ?
- piratebox ?
- proftpd ?
- radicale ?
- tor stuff ?
- z-push

We shall find a way for apps to declare they don't want to show up in the portal.

**Comment by alexAubin** [comment]
The no_sso thing has been integrated in 3.1 as far as i remember

Feel free to complain . reopen
