### ISSUE TITLE
Prévenir la saturation de l'espace disque à cause de /var/lib/mysql/ibdata1

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#523]
###### Original Redmine Issue: [523](https://dev.yunohost.org/issues/523)

Author Name: **maniack_crudelis**

---

Pour le contexte, suite à la mise à jour de Owncloud, il a scanné l'ensemble des disques dur et constitué une table sql de 9.3Go...
Cette table se répercute dans le fichier ibdata1 qui stocke les meta-infos sql.

Le problème est que ce fichier n'est jamais purgé, même en cas de suppression de la bdd problématique. Il ne fait que grossir avec le temps et deviendra tôt ou tard un problème selon la taille du disque dur système.

Pour owncloud, la solution est assez simple, `sudo yunohost app remove owncloud`, ça évite beaucoup de problème à venir...

Pour le fichier ibdata1, si l'espace est saturé, c'est trop tard, il faut supprimer les tables, supprimer le fichier et recharger un dump.

Pour éviter d'en arriver là, une bonne pratique est de séparer les fichiers de stockages de meta-infos pour chaque tables. Cela permet de supprimer ces fichiers avec les tables sans risque de toucher à l'intégrité des autres tables. Et ça évite également un embonpoint d'un seul fichier avec des tables obsolètes.

Pour obtenir ce comportement, il faut ajouter l'option `innodb_file_per_table=1` au fichier /etc/mysql/my.cnf. Le comportement sera pris en compte pour les nouvelles tables créés. Je pense donc que ce devrait être le réglage par défaut pour une nouvelle installation.

**Comment by alexAubin** [comment]
It's been a while, not sure this is still an issue ...

**Comment by alexAubin** [comment]
Closing, the issue seems to have disappeared by itself, maybe because mysql behavior is more sensible these days
