### ISSUE TITLE
Simplify install command

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#525]
###### Original Redmine Issue: [525](https://dev.yunohost.org/issues/525)

Author Name: **moul**

---

Currently, YunoHost [manual install script execution](https://yunohost.org/#/install_manually_en) is done in three steps. (Point 3. is not counted).

What do you think about doing it in one step?:

```bash
wget -qO- https://raw.githubusercontent.com/YunoHost/install_script/master/install_yunohost | sudo bash
```
or with:

```bash
curl https://raw.githubusercontent.com/YunoHost/install_script/master/install_yunohost | sudo bash
```

The problem is that I don't how to add options.

We may only update user documentation and not the one on the repository.

---

If we are agree, I will have to update [french and english documentation](https://yunohost.org/#/install_manually_en) and [repository doc](https://github.com/YunoHost/install_script).

**Comment by alexAubin** [comment]
So we already use a simplified install command for the alpha and beta of Stretch.

I plan to propose an update of https://yunohost.org/#/install_manually once we release it as stable

**Comment by alexAubin** [comment]
Will be fixed in https://github.com/YunoHost/doc/pull/740
