### ISSUE TITLE
Gracefully handle running install script or postinstall twice

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#54]
###### Original Redmine Issue: [54](https://dev.yunohost.org/issues/54)

Author Name: **julienmalik**

---

Install script without postinstall should support being launched several times (since its only aim is to install deb packages).
What should postinstall do when we are already post-installed correctly ?

**Comment by alexAubin** [comment]
Closing because it's not clear why running postinstall would be desirable nor what it would do
