### ISSUE TITLE
Handle "apt-get remove --purge yunohost"

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#55]
###### Original Redmine Issue: [55](https://dev.yunohost.org/issues/55)

Author Name: **julienmalik**

---

Currently not implemented correctly.

First step : before a postinstall, it should be possible to apt-get remove yunohost, and get the server back in its previous state.
Some dependent packages had problems in their pre/postrm scripts. Maybe just needs a test now.

Second step : after we are post-installed, can we remove yunohost ? can we purge ? Need specs about expected behavior.

**Comment by alexAubin** [comment]
Wontfix ...
