### ISSUE TITLE
Block stupid scanner and other by default?

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#550]
###### Original Redmine Issue: [550](https://dev.yunohost.org/issues/550)

Author Name: **Anonymous**

---

Script kiddies spend their time analyzing the internet to find vulnerable target, most of them are easily identifiable. Should we kickban them by default using fail2ban or nginx rules?

Example:

    185.49.14.190 - - [05/Sep/2016:08:49:18 +0200] "GET http://testp3.pospr.waw.pl/testproxy.php HTTP/1.1" 302 154 "-" "Mozilla/5.0 (Windows NT5.1; rv:32.0) Gecko/20100101 Firefox/31.0"
    5.28.163.84 - - [04/Sep/2016:13:34:25 +0200] "GET / HTTP/1.0" 302 154 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)"

On the downside that could make yunohost box obvious on the Internet and could block legitimate usages (scientific apparently enjoy scanning the whole internet right now).

I'm also not sure that this could produce any benefit at all but that kind of requests seems to scare some users (legitimately).

**Comment by alexAubin** [comment]
Imho it looks like a complicated thing to do (you dont want to introduce false positives doing this) with pretty low benefits ... Fail2ban already does the job, and (at least in stretch) recidive jail is enabled which discourages a lot of them.
