### ISSUE TITLE
Upgrade packages during initialization of ynh-dev environment

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#551]
###### Original Redmine Issue: [551](https://dev.yunohost.org/issues/551)

Author Name: **julienmalik**

---

Just after the creation of the environment (ither stable or unstable), I would expect all packages to be up-to-date.
Currently I guess we have packages at the state of "the last time the box was generated", which is not particularly well-defined.

**Comment by alexAubin** [comment]
Meh this is an old issue about a minor issue in our internal tool ... closing to clean things
