### ISSUE TITLE
Remove unsafe-eval and unsafe-inline from Content-Security-Policy

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#555]
###### Original Redmine Issue: [555](https://dev.yunohost.org/issues/555)

Author Name: **ljf**

---

Here is a post about the issue https://forum.yunohost.org/t/content-security-policy/1915

It seams webadmin libs (at least sammy.json.js, jquery.cloudkit.js) use eval() js function. It is not very safe, that exaplain why unsafe-eval is activated.

For unsafe-inline, I don't understand exactly the risk, I let you evaluate/explain it if you know.

**Comment by Psycojoker** [comment]
@zamentur stil relevant?

**Comment by frju365** [comment]
Moi, je dirais que c'est toujours d'actualité, sachant qu'il y a toujours unsafe-eval dans la conf d'admin. Je suis en train de travailler pour l'améliorer ;)

**Comment by alexAubin** [comment]
c.f. https://github.com/YunoHost/yunohost/pull/1290
