### ISSUE TITLE
Current email regex is probably too restrictive.

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#556]
###### Original Redmine Issue: [556](https://dev.yunohost.org/issues/556)

Author Name: **Bram**

---

It's `^([\w.-]+(\+[\w.-]+)*@([^\W_A-Z]+([-]*[^\W_A-Z]+)*\.)+([^\W\d_]{2,}),?)+$`.

Basically the current consensus is "check that there is an @ in the string".

**Comment by zamentur** [comment]
some wlork has been already done about that
