### ISSUE TITLE
[possibility] use mattermost + matterbridge to interconnect irc/xmpp/mattermost for #dev and #support

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#568]
###### Original Redmine Issue: [568](https://dev.yunohost.org/issues/568)

Author Name: **Bram**

---

There is a plugin for mattermost that allows to do bridge between irc and xmpp and mattermost, that could be an interesting way to connect #dev and #support on all the 3 of those networks and allows everyone to use their favorite chan.

https://github.com/42wim/matterbridge

**Comment by alexAubin** [comment]
This is now done !
