### ISSUE TITLE
Pb fonctionnalités d'administration Pirabox depuis Firefox sous Android

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#577]
###### Original Redmine Issue: [577](https://dev.yunohost.org/issues/577)

Author Name: **Anonymous**

---

Bonjour,

Aucune réaction du curseur "Espace maximum" ni du menu déroulant "Point d'accès associé" depuis Firefox 49 avec tablette Android.
Seuls les switch fonctionnent.

--
Bien Librement
SVNET - Libre

**Comment by Psycojoker** [comment]
A bit too oudated :/

I'm closing this because it's more related to partagebox_ynh of laqueinternet.
