### ISSUE TITLE
[bus factor] Move forum POP server to yunohost infrastructure

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#584]
###### Original Redmine Issue: [584](https://dev.yunohost.org/issues/584)

Author Name: **julienmalik**

---

Discourse needs a POP account to retrieve replies to post sent via email to reply+stgh@forum.yunohost.org
Those are retrieved from kload.fr POP server (user "info", as indicated in the discourse settings, section Email).

Also this speaks for itself :

    $ dig MX  forum.yunohost.org +short
    5 kload.fr.

so the SMTP server used to send mails to forum user is also kload.fr

Moving this is not immediate... We need to setup a dovecot instance for forum.yunohost.org

**Comment by alexAubin** [comment]
It's done now that we migrated the forum to a new server
