### ISSUE TITLE
Update debian repository instruction

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#594]
###### Original Redmine Issue: [594](https://dev.yunohost.org/issues/594)

Author Name: **moul**

---

[Debian repository instructions](http://repo.yunohost.org) is for version(YunoHost) < 2.3.

This documentation need to be update to version ≥ 2.4.

**Comment by alexAubin** [comment]
That looks okay to me now ? Anyway I don't think many people look at this page ...
