### ISSUE TITLE
Allow dynamic extensions to dns-conf

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#596]
###### Original Redmine Issue: [596](https://dev.yunohost.org/issues/596)

Author Name: **Anonymous**

---

Applications should be able to declare new stuff to be announced by 'yunohost service dns-conf'.

The first use case I see is the implementation of RFC 6764, which describes how CalDAV and CardDAV services should be announced via DNS. It is already nice that we have the .well-known URL, but to be perfectly compliant with RFC 6764, we should add two distincts DNS records :

A SRV record for announcing the subdomain where the calendar/carddav server is deployed (think of it as 'the MX but for caldav'): 

    _caldavs._tcp     SRV 0 1 443 calendar.example.com.

And a TXT record for announcing the path where the service is accessible on that subdomain, typically for owncloud :

    _caldavs._tcp    TXT path=/owncloud/remote.php/dav

As per RFC 6764, the well-known URIs implemented by owncloud/nextcloud/baikal is a fallback scenario when the DNS lookup has failed. I just checked in DAVDroid source code that it is indeed implemented [like this](https://gitlab.com/bitfireAT/davdroid/blob/master/app/src/main/java/at/bitfire/davdroid/ui/setup/DavResourceFinder.java#L282)

**Comment by alexAubin** [comment]
Related : https://github.com/YunoHost/yunohost/pull/517

**Comment by alexAubin** [comment]
Fixed by the PR mentioned earlier
