### ISSUE TITLE
Implement RFC-6186 : announce smtp/submission/imap/pop via DNS in dns-conf

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#597]
###### Original Redmine Issue: [597](https://dev.yunohost.org/issues/597)

Author Name: **julienmalik**

---

This can help mail client to autoconfigure accounts easily.

**Comment by Psycojoker** [comment]
Apparently this is pretty easy to do https://www.lowendtalk.com/discussion/36969/auto-configure-email-with-srv-records

**Comment by zamentur** [comment]
duplicate of https://github.com/YunoHost/issues/issues/1548
