### ISSUE TITLE
Allow skipped/unprotected_urls setting for ssowat not only uris

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#60]
###### Original Redmine Issue: [60](https://dev.yunohost.org/issues/60)

Author Name: **mbugeia**

---

When doing something like this:
sudo yunohost app setting appname unprotected_uris -v "somepath"
The function ssowatconf transformed the unprotected_uris setting to unprotected_urls which is domain + app_path + unprotected_uris
Most of the time it's what we want but some app required to unprotect a path which is not in the app path.

For example, in Seafile, we have to unprotect domain.tld/seafhttp for the syncing to work (it's hardcoded in seafile so no way to change it). With the actual behaviour it's not possible to do this with yunohost app setting since the moulinette will not take unprotected_urls as a ssowat parameter. So the only way to do it is to edit /etc/ssowat/conf.json.persistent, which is kind of a dirty hack.

My guess is this was introduced to avoid conflict between app especially with the yunohost app checkurl function but I think for the very specific cases where unprotected_urls this will not be a issue.

Relevant code here: https://github.com/YunoHost/yunohost/blob/unstable/src/yunohost/app.py#L982-L1007

**Comment by alexAubin** [comment]
Following discussions on the permission system, this whole (un)protected_urls/regex paradigm is to be reworked someday, so I think this issue is not relevant anymore.
