### ISSUE TITLE
Add a file browser to the admin internface

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#601]
###### Original Redmine Issue: [601](https://dev.yunohost.org/issues/601)

Author Name: **Bram**

---

Hello,

Currently, there is no mean for the user to access his filesystem other than using ssh. This is a big limitation of usability since one something goes wrong, he is simply screw up and needs to seeks help of someone that knows how to do ssh to get him out of this situation.

On of the solutions to solve this issue is to add, like on any desktop, a file browser interface that also allows to run files and edits them.

Having a home made solution fully integrated into YunoHost seems to have a lot of advantages but this will also cost us time so we might want to seeks an existing solution.

**Comment by alexAubin** [comment]
Meh I don't know what we want to do with this ... I feel like this is really a pandora box to go this way, but there are also legit argument for this ... Or we could just settle on "use an SFTP browser", though we should also address the whole situation of `admin`/`admins` don't have proper permissions on files so you have to connect with root

**Comment by alexAubin** [comment]
Closing because feels out of scope and is a pandora box
