### ISSUE TITLE
Can't write a response by email to discourse forum

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#604]
###### Original Redmine Issue: [604](https://dev.yunohost.org/issues/604)

Author Name: **ljf**

---

Hi,

When I try to answer to a mail from discourse, my answer is not published on discourse.

I send my email from Free/proxad ADSL, so it could be a trend micro RBL issue. But it's more probably an infra bug.

Thanks,

**Comment by decentral1se** [comment]
I don't think this is a bug anymore?

**Comment by decentral1se** [comment]
Assuming this refers to the https://forum.yunohost.org/? 

If not, we've also got this solved in the application as well https://github.com/YunoHost-Apps/discourse_ynh/pull/32.

**Comment by alexAubin** [comment]
I dunno, I think it's still the case ... as far as I remember we don't have any pop stuff configured correctly on the infrastructure, but maybe I forgot about it
