### ISSUE TITLE
Auto-diagnostic of DNS conf

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#605]
###### Original Redmine Issue: [605](https://dev.yunohost.org/issues/605)

Author Name: **Bram**

---

On domain add in web UI, check with dig if a domain is correctly configured, if not, point to the dns configuration.

This would be great in a notifications systems.

This might also be needed in a cron or something like that.

**Comment by alexAubin** [comment]
Implemented in https://github.com/YunoHost/yunohost/pull/534

**Comment by alexAubin** [comment]
Fixed by diagnosis system
