### ISSUE TITLE
add .nohost.me and .noho.st to public suffix list

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#610]
###### Original Redmine Issue: [610](https://dev.yunohost.org/issues/610)

Author Name: **Bram**

---

LE rate limits the number of requests per subdomain https://letsencrypt.org/docs/rate-limits/  this will breaks things on .nohost.me and .noho.st

To fix that we need to add ourselves to the public suffix list https://publicsuffix.org/

A PR had already been opened but has been closed, we can start back from there https://github.com/publicsuffix/list/pull/250

This is mandatory if we want LE to works on the prefixes we provide.

**Comment by Psycojoker** [comment]
Done, finally
