### ISSUE TITLE
Use an bot chat room for GitBot notifications

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#613]
###### Original Redmine Issue: [613](https://dev.yunohost.org/issues/613)

Author Name: **moul**

---

We are now using many XMPP notifications from many services:

- GitHub repositories activities:
 - YunoHost main repositories
 - YunoHost-Apps official apps
- Redmine: ticket modification
- Weblate: translation updates.

I found that annoying as it notify YunoHost project activity.
It oftenly cut discussions on dev chat room.
I propose to move all notification on [`bot` chat room](https://im.yunohost.org/logs/bots/).
That way, people who want this notification have to go on this chat room. And people who don't wan't to be disturbed don't need to go on.
Furtheremore, if someone do many tickets modifications, it's very annoying to be notified by all them.

----

I consider this one as a [medium vote](https://github.com/YunoHost/yunohost-project-organization/pull/5/files#diff-8bd196a3f9ba5b6a82563d735d7276afR146):

- 2 weeks: till 17th November
- 4 votes minimum (mine is included and positive)
- Let's say 80 or 100% positives opinions. (not decided upstream)
- As it's in Infra private project, only Infra members can vote.

(Do not hesitate to ask for vote modification)

----

If it pass, it will be needed to migrate all notifications to new chat room.
On dev chat room title, we must inform about bot chat room.

**Comment by Psycojoker** [comment]
I guess this is not relevant anymore, reopen if needed.
