### ISSUE TITLE
Sauvegarde / poids en MB

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#616]
###### Original Redmine Issue: [616](https://dev.yunohost.org/issues/616)

Author Name: **Anonymous**

---

Bonjour,

ce n'est pas vraiment un bug, mais je ne savais pas où dire ceci, à savoir que lorsqu'on fait une sauvegarde depuis l'interface web, la taille est affichée en MB plutôt qu'en Mo, ce qui pour nous francophile est moins parlant...

Cordialement

**Comment by alexAubin** [comment]
Meh
