### ISSUE TITLE
Allow to add a post-reload hook on firewall_reload

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#620]
###### Original Redmine Issue: [620](https://dev.yunohost.org/issues/620)

Author Name: **austinjh**

---

I needed to add custom iptables rules in order to work with my dedicated ip vpn provider.

Instead of modifying the /usr/lib/moulinette/yunohost/firewall.py

I was hoping there could be some code to add custom rules.

I can understand code but I don't know that much about iptables or checking if a custom iptables rule is acceptable.

**Comment by sy6sy2** [comment]
I also need to manually run a custom iptables command each time YunoHost does a firewall reload.

Maybe can we add one line in `firewall.py` that call a specific bash file (if this file exists) each time there is a firewall reload. Then anybody can put what he needs in this hook file?

**Comment by alexAubin** [comment]
Well I did not realize when passing by this issue the other day, but there is a post-reload hook on firewall_reload ... https://github.com/YunoHost/yunohost/blob/testing/src/yunohost/firewall.py#L273

(It's called `post_iptable_rules` though)

It's even used by the vpnclient and hotspot apps from the internet cube to add custom ip tables rules

You should be able to create a file like `/etc/yunohost/hooks.d/post_iptable_rules/123-yourhook` and put raw commands like in here:

https://github.com/labriqueinternet/vpnclient_ynh/blob/master/conf/hook_post-iptable-rules

**Comment by sy6sy2** [comment]
My bad, I checked `firewall.py` code but I did not notice this line! Thank you.

I will try it soon by manually creating the `post_iptable_rules` folder and my custom iptables file ;-)

**Comment by alexAubin** [comment]
Closing because c.f. the previous comment, this hook exists and is used by vpnclient
