### ISSUE TITLE
Tickets from Infra project are readable from RSS flow

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#623]
###### Original Redmine Issue: [623](https://dev.yunohost.org/issues/623)

Author Name: **moul**

---

Tickets from Infrastruture project, which are private, are accessible and readable with RSS and Atom flow without HTTP authentication.
If someone found the flow address could read all the content.

**Comment by alexAubin** [comment]
Weeeeell we aint on redmine anymore, though we still need to find a solution for private issues ¯\\\_(ツ)\_/¯
