### ISSUE TITLE
Disable email functionality for domain?

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#625]
###### Original Redmine Issue: [625](https://dev.yunohost.org/issues/625)

Author Name: **Anonymous**

---

I have two domains A and B setup. While for domain A I'm still using and external email provider, I'm self hosting email for domain B.

When I want to sent an email from domain B to domain A I the following error message:

~~~
An error occurred while sending mail. The mail server responded:  
5.1.1 <mail@domainA.org>: Recipient address rejected: User unknown in virtual mailbox table.
 Please check the message recipient "mail@domainA.com" and try again.
~~~

It seems the problem is the box tries to deliver the email to domain A locally, which is not working.

So I'm wondering, if and how it would be possible to disable the email functionality for a single domain.

Thank you kindly.

**Comment by alexAubin** [comment]
Maybe stuff from this : https://www.sysnove.fr/blog/2019/07/decouverte-multi-instances-postfix.html

could be used to implement and clarify this

(Though first we would need per-domain settings I guess)

**Comment by Josue-T** [comment]
In the https://github.com/YunoHost/yunohost/pull/585 there are some idea of permission also for email. We still need to merge this...

**Comment by alexAubin** [comment]
Closing, c.f. https://github.com/YunoHost/issues/issues/1028 which is a more general issue
