### ISSUE TITLE
Return-Path email header value is "default" domain

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#626]
###### Original Redmine Issue: [626](https://dev.yunohost.org/issues/626)

Author Name: **Anonymous**

---

I setup email for non-default domain B. 

I could send and receive email. 

When I check the email header I see value of "default" domain A in Return-Path value.

This is a problem when I don't want to reveal that domain A and B have anything to do with each other.

Is there a way to fix this?

**Comment by Psycojoker** [comment]
It's a duplicate of this one, right? https://github.com/YunoHost/issues/issues/269

**Comment by alexAubin** [comment]
That looks different, #269 is about `MAIL FROM:`

**Comment by HugoPoi** [comment]
I confirm the issue, when you send email with domain B when your main domain is A, the `envelope-from` will be email@domainA, this is very annoying because bounced email will be sent to email@domainA which doesn't exists.
