### ISSUE TITLE
Problem when deleting account and user deleted is connected

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#631]
###### Original Redmine Issue: [631](https://dev.yunohost.org/issues/631)

Author Name: **Anonymous**

---

**Story :**

* Create User A
* Connect with User A
* Delete User A
* Reload page : Error 500 (or nginx default index.html page)

**Problem :**

The cookie is still in the browser. To fix it I have to manually delete the cookies from my browser.

**Expected Behavior :**

I should be redirected on the connection page.

**Comment by Psycojoker** [comment]
This one is fixed iirc.
