### ISSUE TITLE
yunohost service module doesn't support systemd

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#635]
###### Original Redmine Issue: [635](https://dev.yunohost.org/issues/635)

Author Name: **Anonymous**

---

It's only based on sysinit for now, we need to move to systemd.

**Comment by alexAubin** [comment]
I think https://github.com/YunoHost/yunohost/pull/389 and https://github.com/YunoHost/yunohost/pull/469 solve this issue
