### ISSUE TITLE
Official Debian packages and make Yunohost a Debian Pure-Blend

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#637]
###### Original Redmine Issue: [637](https://dev.yunohost.org/issues/637)

Author Name: **Anonymous**

---

Hi!

Please, consider packaging yunohost-related software officially in Debian. That would make it possible to have Yunohost as a Debian Pure Blend [0], get support from Debian, make use of its infrastructure, follow stable and fixed releases, among other advantages :-)

[0] https://wiki.debian.org/DebianPureBlends

Thanks for you great project,

Santiago

**Comment by alexAubin** [comment]
Closing because it's very unlikely to ever happen ...
