### ISSUE TITLE
Provide "arm64" YunoHost packages

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#642]
###### Original Redmine Issue: [642](https://dev.yunohost.org/issues/642)

Author Name: **Anonymous**

---

Salut Moul !

Hardware : Odroid C2 Rev 0.2
OS : Armbian_5.21_Odroidc2_Debian_jessie_3.14.79 (clean install)

Cause probable :
W: Failed to fetch http://repo.yunohost.org/debian/dists/jessie/InRelease  Unable to find expected entry 'stable/binary-arm64/Packages' in Release file (Wrong sources.list entry or malformed file)

**Comment by alexAubin** [comment]
See https://github.com/YunoHost/issues/issues/438 (duplicate)
