### ISSUE TITLE
certificats wildcards et nouveaux sous-domaines

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#648]
###### Original Redmine Issue: [648](https://dev.yunohost.org/issues/648)

Author Name: **Anonymous**

---

Bonjour, merci pour votre lecture.

Mon fils ne sert à rien pour ceux qui utilisent Let'sencrypt (que j'aime pas). Mais pour moi qui utilise un wildcard, j'en serais heureux.

Parce que j'utilise CAcert, et [sa possibilité de faire des wildcards gratuitement](https://forum.yunohost.org/t/cacert-certificat-principal-et-wildcard-gratuits/2101).
Or, quand on a notre certificat puis que l'on crée un nouveau sous-domaine depuis l'interface d'administration, le certificat wildcard ne se copie pas, tandis que yunohost certifie lui même (après vérification) le nouveau sous-domaine.
Et ce n'est pas reconnu par les navigateurs, obligeant à retourner en ssl pour copier soi même le bon certificat.

Une case à cocher lors de la sélections du "j'ai déjà un nom de domaine" avec en plus, la possibilité de sélectionner ou pas un domaine déjà existant comme dans la création d'un sous domaine, pourrait permettre cette automatisation de copie de certificat wildcard et éviter de repasser par ssh.

Merci encore pour votre lecture. :)

[FugazziPL](https://forum.yunohost.org/users/FugazziPL)

**Comment by alexAubin** [comment]
Closing because wontfix, cf https://github.com/YunoHost/issues/issues/2089 for the general issue about supporting Lets Encrypt certs
