### ISSUE TITLE
XMPP VoIP doesn't works

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#65]
###### Original Redmine Issue: [65](https://dev.yunohost.org/issues/65)

Author Name: **moul**

---

VoIP and visioconference over XMPP doesn't works. I've only try it with two contacts on my server.
File transfert sometimes doesn't works.
If my memory is good, it was working in YunoHost version 2.0 but it doesn't not works on versions 2.2 and 2.4.
It could come from the configuration or from Metronome it self.

**Comment by alexAubin** [comment]
Closing because probably duplicate of https://github.com/YunoHost/issues/issues/1607 where there's more discussion
