### ISSUE TITLE
L10N - improve application translation - admin and descriptions

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#650]
###### Original Redmine Issue: [650](https://dev.yunohost.org/issues/650)

Author Name: **jibec**

---

I would like to be able to translate every field from admin/#/apps/install/ there is a few gaps at the moment.

* where is translation of application description handled?
  * I assume I'm lucky to be french to have translated version, but I tried in 'de' and 'nl', no translation.

* where is translation of install form handled?
  * In Dokuwiki: I have "Example:" which is English, and also yes/no for public website.
  * In Shell In A Box: two questions out of three are in English.
  * etc.

about install form: Debian has a debconf file that contains every questions that may be asked to end user and it is translated globally.
about application description: Fedora, Debian, and many others use a standard file named ".appdata"

* here is an example of a non translated appdata file from josm: https://jibecfed.fedorapeople.org/l10n/appdata-fr/xml/josm.desktop.xml
* here is an example of a well translated appdata file from gnome-maps: https://jibecfed.fedorapeople.org/l10n/appdata-fr/xml/org.gnome.Maps.desktop.xml

It's gettext who produce the translated content, here is the gnome-maps source file: https://git.gnome.org/browse/gnome-maps/tree/data/org.gnome.Maps.appdata.xml.in

Of course, there is documentation and tools: https://www.freedesktop.org/wiki/Distributions/AppStream/

thanks for your help

**Comment by alexAubin** [comment]
Closing assuming Bram's work fixed the issue
