### ISSUE TITLE
Display certificat type in a badge on domain list page

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#665]
###### Original Redmine Issue: [665](https://dev.yunohost.org/issues/665)

Author Name: **Bram**

---

It would be nice to be able to see which kind of certificat is linked to a domain on the domain list page.

**Comment by alexAubin** [comment]
Closing because meh, ultimately everybody clicks on install a Lets Encrypt cert and that's it

Also the new domain info page in 11.1 will display this more clearly
