### ISSUE TITLE
Migrate from Metronome to Prosody

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#67]
###### Original Redmine Issue: [67](https://dev.yunohost.org/issues/67)

Author Name: **stevenroose**

---

Metronome is no longer maintained and the missing features from Prosody that made us decide for Metronome are no longer missing from Prosody.

Besides, even though my issue concerning MAM has been closed (twice :p), MAM is not working currently in Metronome (Conversations for Android indicates MAM is unavailable).

Prosody is actively maintained these days and the most popular server alongside ejabberd, but because Metronome and Prosody are so alike, installation- and configuration-wise, migrating to Prosody should be easy.

Both MAM and Client State Indication are important XEPs for Mobile users and are not supported by Metronome (or not working currently and hard to get working since documentation is non-existent), but are by Prosody.

**Comment by rscmbbng** [comment]
Hello, I am one of the authors of https://homebrewserver.club/configuring-a-modern-xmpp-server.html which is based on debian stable and currently one of the most up to date and featureful configs. I believe it is a good basis to replace metronome with. Let know if you need help!

**Comment by Neustradamus** [comment]
@rscmbbng: Have you tested Metronome IM, the Prosody IM fork?

**Comment by rscmbbng** [comment]
I haven't tried it, but having looked into it now, it seems that it should be possible to have full [compliance](https://compliance.conversations.im/) with Metronome.  If you need advice on prosody community modules, hmu!

**Comment by decentral1se** [comment]
This should probably be closed based on the discussion and commentary in https://github.com/YunoHost/yunohost/pull/240#issuecomment-518135983, no?

**Comment by Psycojoker** [comment]
Indeed, let's close that for now (could be reopened if we ever need to do this migration later)
