### ISSUE TITLE
Add OSCP stapling for domain with LE certs ?

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#679]
###### Original Redmine Issue: [679](https://dev.yunohost.org/issues/679)

Author Name: **Anonymous**

---

To help Let's Encrypt servers with load, we should look into implementing OSCP stapling :

From [Wikipedia](https://en.wikipedia.org/wiki/OCSP_stapling) :
OCSP stapling [...] is an approach for checking the revocation status of X.509 digital certificates. It allows the presenter of a certificate to bear the resource cost involved in providing OCSP responses by appending ("stapling") a time-stamped OCSP response signed by the CA to the initial TLS handshake, eliminating the need for clients to contact the CA.

Apparently it only requires a few additional lines in the nginx conf :
https://www.digitalocean.com/community/tutorials/how-to-configure-ocsp-stapling-on-apache-and-nginx#configuring-ocsp-stapling-on-nginx

**Comment by alexAubin** [comment]
c.f. https://github.com/YunoHost/yunohost/pull/533

**Comment by alexAubin** [comment]
Fixed by YunoHost/yunohost#533
