### ISSUE TITLE
Implements auto-configuration files for email clients, aka .well-known

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#68]
###### Original Redmine Issue: [68](https://dev.yunohost.org/issues/68)

Author Name: **Anonymous**

---

See https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration

I guess that the /.well-known/ path should be reserved for each domain, and un-protected by SSOWat

**Comment by Psycojoker** [comment]
Also linked to https://github.com/YunoHost/issues/issues/597

**Comment by alexAubin** [comment]
Related : https://github.com/tuxmouraille/well-known_ynh

**Comment by alexAubin** [comment]
Solved by https://github.com/YunoHost/yunohost/pull/495 in 3.1
