### ISSUE TITLE
Support armel architecture

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#680]
###### Original Redmine Issue: [680](https://dev.yunohost.org/issues/680)

Author Name: **Bram**

---

Hello,

A request on #support to support this kind of architecture. Apparently we only support armhf and armel is another architecture that we could support.

I tried to gave a quicklook at our build pipepline but couldn't find where to had this architecture simply :/

**Comment by alexAubin** [comment]
This is now done for YunoHost 3.0+
