### ISSUE TITLE
Allows app to declare that they need to handle .well-know/foobar

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#684]
###### Original Redmine Issue: [684](https://dev.yunohost.org/issues/684)

Author Name: **Bram**

---

As reported here https://github.com/YunoHost-Apps/baikal_ynh/issues/17 we got a conflict where 2 apps needed to handle a unique resource on a domain (a path in `.well-known` for caldav/carddav).

It would be great to have a mechanism in which an app can say "I want to handle this unique resource, is it available?" and fails if no and display an understandable error message to the user pointing to the other app that handle this resource.

This would greatly improve usability in those situations for most of our users.

Luckily, for now, this seems to be a very rare situation and that would also requires a migration of those apps.

**Comment by alexAubin** [comment]
Was about to say "manifest v2 kind of fix this", but the .well-known situation is more complex than that ... I don't know exactly what we want to do with this but meh
