### ISSUE TITLE
Provide a mechanism/documentation on how to configure dnsmasq for certain situations

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#685]
###### Original Redmine Issue: [685](https://dev.yunohost.org/issues/685)

Author Name: **maniack_crudelis**

---

Par défaut le port 53 est ouvert en upnp sur le routeur en amont.
Cela a pour effet de rendre dnsmasq accessible de l'extérieur, ce qui l'expose à de très nombreuses requêtes extérieures.

Cela peut être surveillé en activant log-queries.

Par défaut, dnsmasq traite 150 requêtes simultanées, au delà les requêtes sont mises en attente.
Mais lorsque le port 53 est ouvert, les 150 requêtes simultanées sont très vite atteintes et dnsmasq ne répond plus aux requêtes locales. Et d'expérience, il fini par crasher sous la pression...

Le problème semble se poser uniquement si on utilise dnsmasq en tant que resolveur dns principal.
Dans mon cas, c'est lui qui se charge des résolutions dns et les requêtes proviennent directement du routeur.

La fermeture du port 53 sur le routeur à permis de régler ce problème.

**Comment by alexAubin** [comment]
Closing because meh
