### ISSUE TITLE
Installation stuck when no dialog is installed

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#692]
###### Original Redmine Issue: [692](https://dev.yunohost.org/issues/692)

Author Name: **Anonymous**

---

While on a minimal installation of Debian Jessie the installation is stuck at "..100%" and doesn't seem to continue when there's no dialog application installed. Installing one manually e.g. Debian's default (?) *whiptail* will fix this.

~~~
node# cd /tmp/install_script && sudo ./install_yunohost
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Installing packages
-------------------

..100%
~~~

**Comment by Psycojoker** [comment]
That looks to be handled by the installation script, let's close this one for now and reopen if needed.
