### ISSUE TITLE
Filtrer les applications en fonction de l'architecture supportée.

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#696]
###### Original Redmine Issue: [696](https://dev.yunohost.org/issues/696)

Author Name: **maniack_crudelis**

---

Les tests d'intégrations multi-architecture étant en cours de travail, nous devrions sous peu être capable de déterminer pour chaque app sa capacité à être installé sur différentes architectures processeur.

Ce faisant, il semble intéressant de filtrer les applications dans l'interface admin afin de ne pas afficher des apps non supportées par le système.

En parallèle à ce filtre, les applications ne doivent pas pouvoir être installés sur un système incompatible, même si l'installation se fait directement depuis le dépôt git ou en local.

**Comment by alexAubin** [comment]
Related to https://github.com/YunoHost/issues/issues/1614

**Comment by alexAubin** [comment]
Closing because addressed by packaging v2

**Comment by tituspijean** [comment]
Allow me to reopen this: even though the filter might be implicit in the webadmin, the current apps catalog website does not offer to filter per architecture.
