### ISSUE TITLE
Afficher les niveaux des apps

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#697]
###### Original Redmine Issue: [697](https://dev.yunohost.org/issues/697)

Author Name: **maniack_crudelis**

---

Pour faire suite à cette discussion:
https://forum.yunohost.org/t/redaction-de-regles-pour-passer-une-app-en-officielle/2256/26

Il serait intéressant d'afficher le niveau de chaque application dans les listes official et community.
Ainsi chaque utilisateur pourrait connaître le niveau d'une application avant de décider de l'installer.

**Comment by Psycojoker** [comment]
For reference https://github.com/YunoHost/issues/issues/711

**Comment by alexAubin** [comment]
c.f. https://github.com/YunoHost/yunohost-admin/pull/205

**Comment by alexAubin** [comment]
Let's say this is fixed by https://github.com/YunoHost/yunohost-admin/pull/205, at least for the webadmin, though there still are a few things which should be done about this (what about CLI, and we might want to have a prompt to confirm installation of bad-quality apps)
