### ISSUE TITLE
Add YunoHost compatibility to SSOwat

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#700]
###### Original Redmine Issue: [700](https://dev.yunohost.org/issues/700)

Author Name: **a1ex**

---

I'm opening this issue to discuss the limitation to the YunoHost development that is implied by the wish to make SSOwat independent of YunoHost.  

Right now SSOwat is extremely limited when interfacing with YunoHost, there is no way the two can communicate and actually make changes on eachother. I believe an improvement to the YunoHost sso would be that you could make changes to your YunoHost configuration, directly from the sso. I have several ideas for improving the portal (and so the user experience of YunoHost) but I'm very limited by the fact that changes made to SSOwat must be independent of YunoHost.

So I propose to add compatibility to SSOwat for YunoHost. This can have several forms, either:

* "Fork" SSOwat into a new package that will be shipped during YunoHost installation, with all that is required for the portal to interface with YunoHost configuration

* Patch SSOwat during installation and apply YunoHost compatibility files, this would be as simple as overriding js/html/ms files with added functions

I think that all that is needed to get rid of this limitation is being able to call the YunoHost API from the sso, and that would be as simple as adding javascript code to allow that.

If nobody is against it I'll try to propose something that addresses this compatibility issue.

**Comment by ketsapiwiq** [comment]
Related: https://github.com/YunoHost/issues/issues/2028 and https://github.com/YunoHost/yunohost/pull/1387)

**Comment by alexAubin** [comment]
Closing because cf follow-up issues / PR mentioned in previous comment
