### ISSUE TITLE
Don't expose the Yunohost version to unlogged users for security reasons ?

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#703]
###### Original Redmine Issue: [703](https://dev.yunohost.org/issues/703)

Author Name: **alexAubin**

---

Follow-up of https://dev.yunohost.org/issues/316

Bram
>for boring security reason it would be better not to display it to unloged users.

Moul
>Agreed.

opi
>we need to patch this API route too : https://example.com/yunohost/api/version, because it's more verbose, and available to everyone !

**Comment by Psycojoker** [comment]
Still relevant, sadly.

**Comment by alexAubin** [comment]
c.f. https://github.com/YunoHost/yunohost/pull/291

**Comment by alexAubin** [comment]
PR got merged
