### ISSUE TITLE
Be more flexible about user info ?

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#704]
###### Original Redmine Issue: [704](https://dev.yunohost.org/issues/704)

Author Name: **alexAubin**

---

When creating a new user, it feels sometimes a bit frustrating to absolutely have to provide a first and last name for the user.
- first name could be the username by default. Or it should be ok if first name is empty.
- It should be ok if last name is left empty
- The email address could be, by default, username@main.domain.tld. Not sure that's the case atm ?

**Comment by Psycojoker** [comment]
Yes, also first/last name only work in European country, if you look at the whole world https://www.w3.org/International/questions/qa-personal-names the conclusion is basically "you are fucked up, use a free field".

Also people don't especially want to uses their real identity.

**Comment by Psycojoker** [comment]
Close this as duplicate of https://github.com/YunoHost/issues/issues/704

**Comment by alexAubin** [comment]
Uuuuuh, this is #704 ? :P

**Comment by Psycojoker** [comment]
Feuk, this one https://github.com/YunoHost/issues/issues/296
