### ISSUE TITLE
Increase mysql thread_stack value to avoid error on restart

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#707]
###### Original Redmine Issue: [707](https://dev.yunohost.org/issues/707)

Author Name: **mbugeia**

---

When the mysql db start to grow the value of the parameter thread_stack is not high enough, and we can encounter this issue during mysql start:

Jan 10 14:05:12 max /etc/mysql/debian-start[3081]: ERROR 1436 (HY000) at line 1151: Thread stack overrun:  6800 bytes used of a 131072 byte stack, and 128000 bytes needed.  Use 'mysqld --thread_stack=#' to specify a bigger stack.
Jan 10 14:05:12 max /etc/mysql/debian-start[3081]: FATAL ERROR: Upgrade failed

The solution was simple for me: increase the value of thread_stack from 128k to 256k in /etc/mysql/my.cnf

Relevant code: https://github.com/YunoHost/yunohost/blob/unstable/data/templates/mysql/my.cnf#L37

**Comment by Psycojoker** [comment]
Shouldn't we do that? That looks simple.

Also : MySQL -_-

**Comment by alexAubin** [comment]
Closing because the mysql conf evolved since then and havent heard of that specific issue ever
