### ISSUE TITLE
Investissement dans un raspberry 3 à placer en housing

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#708]
###### Original Redmine Issue: [708](https://dev.yunohost.org/issues/708)

Author Name: **maniack_crudelis**

---

Durant la réunion du 10 janvier 2016, nous avons évoqués l'idée de financer à plusieurs l'achat d'un raspberry 3 pour divers tests autour de YunoHost.

Dans l'idée, le raspberry serait placé en housing chez ARN (ou quelque autre hébergeur bienveillant et nous le proposant).
Dans l'idéal, le raspberry tournerais sur raspbian minimal avec lxc pour proposer autant de conteneur que d'activités différentes que nous souhaitons y héberger.
Au moins pour le moment:
    - Une instance de CI_package_check pour tester les applications sous arm.
    - Une instance de Bicyclette (en cours de réflexion) pour tester YunoHost sur arm.
    - Un conteneur avec uniquement jessie pour tester l'installation de YunoHost.
    - D'autres conteneurs si on a d'autres besoins.

L'idée de passer par les conteneurs est bien évidemment de garder le PI dans un état stable, tandis que l'on martyrisera à loisir des instances virtualisées pour tout les tests qu'on voudrait faire et de pouvoir travailler ensemble sur une même machine physique.

Ainsi nous ne pourrons plus dire: "Je testerais bien, mais j'ai pas de pi sous la main"

---

D'un point du vue pratique,
   - Connaissez-vous un site de financement participatif du genre de Leetchi, en plus respectueux?
   - J'ai du temps (pour le moment) pour préparer la bête avant de l'envoyer dans sa future maison. Donc je peux me charger de cette partie.
   - Il y a une boutique ldlc à 100m de chez moi (ça me coûte très cher... c'est terrible !), donc je peux également me charger de la commande.
      - Il faut compter (chez ldlc) 50€ pour la carte mère, 17€ pour l'alimentation, 17€ pour le boitier et environ 12€/20€ pour une microSD class 10 de 16/32Go.
         - Soit un total de 96/104€ pour l'ensemble.
         - Sachant qu'il existe un starter kit à 90€ avec une microSD de 16Go avec NOOBS préinstallé. Ce dernier permettant l'installation d'une raspbian jessie minimalist.
            - La question de l'espace disque doit toutefois être bien réfléchie, car il faut envisager 1.5Go par instance YunoHost en conteneur, autant pour son conteneur et 700Mo pour un tarball du backup. Soit 3.7Go par conteneur LXC.

**Comment by alexAubin** [comment]
I think it's now solved .. at least using some weird magic we have tests for ARM (distributed over several hardware owned by several people afaik ?)
