### ISSUE TITLE
Non-web email clients doesn't work if SSO username and user in user@domain.tld have different values

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#71]
###### Original Redmine Issue: [71](https://dev.yunohost.org/issues/71)

Author Name: **Anonymous**

---

# * Problem *

I created a Yunohost user with pseudonym as username for SSO/LDAP and some other name for email : name@domain.tld
It works perfectly in RoundCube (after some troubles because of missing username homedir in /var/mail), but not in desktop/non-web email clients such as clients IceDove (Thunderbird)

IceDove asks for both **user** in **user@domain.tld** and the logging **username**
The logging **username** is the **SSO username**
Just to make things clear, even thought RainLoop does not have an SSO/LDAP-based auth but uses plain IMAP(S)/SMTP(S), it accepts **username** as login, but not **user** value from the email address, as manually filled in email field, in Yunohost user creation interface

After user RainLoop for debugging, I just used user@domain.tld for email address field, and **username** in outgoing/incoming username fields
**NB** : before knowing about RainLoop, I tried many combinations with and without the SSO username (**user** from user@domain.tld as incoming/outgoing username), if not all the logical ones

So let's suppose I created **user1** with **user2@domain.tld** as email address
My IceDove configuration looks like this

~~~
**Email address** : user2@domain.tld
**Password** : The same as the SSO passwords, works with Rainloop, Roundcube and XMPP clients

### IMAP
**Domain** : domain.tld (full, with a subdomain, the same as defined in Yunohost and my zone DNS file)
**Protocol** : SSL/TLS
**Port** : 993
**Incoming username** : user1

### SMTP
**Domain** : domain.tld (full, with a subdomain, the same as defined in Yunohost and my zone DNS file)
**Protocol** : SSL/TLS
**Port** : 465
**Incoming username** : user1
~~~

But it still doesn't work, IceDove fails to verify the configuration, and can't connect
For some reasons, it looks like IceDove (and probably other email clients) doesn't work properly when username is different from user in user@domain.tld

1. **Workaround**

I decide to make things simpler and more consistent
I edit my user's profile, changing it's address from **user2** to **user1**, so **user** from email address has the same value as **SSO username** 
I deleted **user1** homedir from /var/mail, then reacted it

~~~
1. sudo rm -r /var/mail/user1
1. sudo mkdir -p /var/mail/user1
1. sudo chown -hR vmail:mail /var/mail/user1
1. sudo /sbin/mkhomedir_helper /var/mail/user1
~~~

I restarted dovecot and postfix

~~~
1. sudo systemctl restart dovecot
1. sudo systemctl restart postfix
~~~

Then I edited IceDove account configuration accordingly, I kept the previous conf but changed the email address, now it works properly

1. **Suggestion**

Until a better solution could be found
Either make it clear it the documentation, that's it's recommended to have the same value for both **user** in the email address and **username** for SSO auth, for users who wish to use a non-web email client
Or automate the process by enforcing the same value between both, and not allowing users to modify one value independently from the other

You can for example do it in an conditional manner, by asking the Yunohost admins if they wish to use a non-web/remote client, when they create users
If yes, then enforce the same value for both SSO **username** and **user** in user@domain.tld, if not then they could use different values
(Even  if different values might be confusing for configuring remote clients)

**Comment by julienmalik** [comment]
Strange...

That's how my own account is set up (my sso id is different from the mail address) and I never had any problem with it. I do use Thunderbird on multiple machines.

**Comment by alexAubin** [comment]
Hmwell if we can't reproduce the issue, we can close it ... Dates back from 2015 and we havent had any other people reporting this

**Comment by julienmalik** [comment]
closing then. please reopen if you encounter the issue again
