### ISSUE TITLE
Intégration des niveaux des applications

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#711]
###### Original Redmine Issue: [711](https://dev.yunohost.org/issues/711)

Author Name: **maniack_crudelis**

---

Suite à la décision sur les apps officielles et les niveaux des apps (qui sera validée demain si tout va bien), je propose un affichage des niveaux dans YunoHost.
Car l'idée étant de stimuler le packaging d'app par l'intermédiaire des niveaux et d'un accès (enfin) possible aux apps officielles, il est nécessaire pour accompagner ce changement que les niveaux des applications soient visibles.
Sinon, le niveau n'a pas le moindre intérêt.

J'ai d'ores et déjà écrit une documentation sur les niveaux:
https://github.com/YunoHost/doc/pull/432

La première chose est déjà d'intégrer les niveaux d'applications aux listes d'app
https://github.com/YunoHost/apps/pull/118

Le script list_builder.py ignore simplement le level dans le json, c'est donc sans conséquence tant que le script n'est pas modifié.
Cette PR permet donc à list_builder.py d'intégrer le level dans le -build.json
https://github.com/YunoHost/apps/pull/119

Toutefois, en l'état le fichier -build.json contient l'information sur le niveau de chaque app. Mais cette information n'est pas affichée.
Dans un premier temps, une proposition d'intégration du niveau de chaque app dans la liste affichée dans la documentation. (Je n'ai pas testé ça, car ça m'aurait obligé à merger)
https://github.com/YunoHost/doc/pull/433

Et pour terminer, modification de la liste des apps à installer dans l'admin pour afficher le niveau de chaque app.
J'ai testé ça avec succès sur une VM.
https://github.com/YunoHost/yunohost-admin/pull/143

Voilà avec tout ça, on devrait pouvoir afficher le niveau de chaque app, dans la liste de la doc et dans la liste des apps à installer. Ce qui permettra à chaque utilisateur de connaître le niveau d'une application avant de choisir de l'installer. Et à chaque packageur de mettre en avant la qualité de son package.

Si cela vous convient (et si n'est pas une forme d'ingérence inacceptable), je propose de passer ça en décision standard avec clôture au 26 janvier. Et plutôt à soumettre à l'approbation du groupe core-dev.

**Comment by Psycojoker** [comment]
I'm closing this one since we have this other one here https://github.com/YunoHost/issues/issues/697
