### ISSUE TITLE
Be able to change user password in CLI without writing it in clear

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#714]
###### Original Redmine Issue: [714](https://dev.yunohost.org/issues/714)

Author Name: **alexAubin**

---

Currently, to change a user password in CLI, we use "yunohost user update username -p new_password"

This is bad practice as the password ends up in clear in some logs.

**Comment by cricriiiiii** [comment]
Maybe the easiest way to fix this is to create a new command "yunohost user changepassword username [-p new_password]" and reusing how it is done when creating a new user.
Is there a reason for not wanting to add this as a new command (and insisting on tweaking user_update to be able to detect if the password is not given and then asking for it) ?

**Comment by cyxae** [comment]
Fixed, can be closed !

**Comment by tituspijean** [comment]
Indeed!
