### ISSUE TITLE
Package Framindmap

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#724]
###### Original Redmine Issue: [724](https://dev.yunohost.org/issues/724)

Author Name: **maniack_crudelis**

---

[Framindmap](https://framindmap.org/), cartes heuristiques
Basé sur [wisemapping](http://wisemapping.com/)

Non packagé.

**Comment by alexAubin** [comment]
Package started here : https://github.com/YunoHost-Apps/wisemapping_ynh

**Comment by alexAubin** [comment]
(c.f. also : https://github.com/framasoft/wisemapping_ynh which has more commits )

**Comment by alexAubin** [comment]
And now there's : https://github.com/YunoHost-Apps/mindmaps_ynh

**Comment by andretheolauret** [comment]
Should be closed
