### ISSUE TITLE
Enable IPv6 support in OpenVPN Server

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#733]
###### Original Redmine Issue: [733](https://dev.yunohost.org/issues/733)

Author Name: **jdbean**

---

I make fairly frequent use of my OpenVPN server and would really like to see IPv6 tunnel support be added to the package to, in part, avoid IPv6 leaks from my VPN connection.

**Comment by alexAubin** [comment]
Old app issue, see openvpn_ynh i think...
