### ISSUE TITLE
Package Framacarte

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#734]
###### Original Redmine Issue: [734](https://dev.yunohost.org/issues/734)

Author Name: **maniack_crudelis**

---

[Framacarte](https://framacarte.org/), création de cartes personnalisées
Basé sur [uMap](https://github.com/umap-project/umap/)

Non packagé.

**Comment by alexAubin** [comment]
Closing because it seems well-packaged and working (according to the README ?) even tho it's not in community.json ...
