### ISSUE TITLE
Package Framanotes

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#736]
###### Original Redmine Issue: [736](https://dev.yunohost.org/issues/736)

Author Name: **maniack_crudelis**

---

[Framanotes](https://framanotes.org/), prise de notes
Basé sur [turtl](https://turtlapp.com/)

Non packagé.

**Comment by alexAubin** [comment]
Closing because Gogs has good level an is actively maintained

**Comment by alexAubin** [comment]
Woopsies, wrong issue
