### ISSUE TITLE
Package Framaforms

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#737]
###### Original Redmine Issue: [737](https://dev.yunohost.org/issues/737)

Author Name: **maniack_crudelis**

---

[Framaforms](https://framaforms.org), création de formulaires en ligne
Basé sur [drupal](https://www.drupal.org/) et ses modules [webform](https://www.drupal.org/project/webform) et [form builder](https://www.drupal.org/project/form_builder)

Non packagé.

**Comment by alexAubin** [comment]
Ongoing work by Jibec : https://github.com/YunoHost-Apps/Framaforms_ynh

**Comment by alexAubin** [comment]
Package is now level 7
