### ISSUE TITLE
Searx: InsecurePlatformWarning

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#74]
###### Original Redmine Issue: [74](https://dev.yunohost.org/issues/74)

Author Name: **Anonymous**

---

SOLUTION ::

Try this first.

sudo apt-get install build-essential python-dev libffi-dev libssl-dev
sudo /opt/yunohost/searx/bin/pip install urllib3[secure]

If it works great. If not try this also,

sudo /opt/yunohost/searx/bin/pip install pyopenssl ndg-httpsclient pyasn1
sudo /opt/yunohost/searx/bin/pip install requests[security]

STEPS I USED TO SOLUTION::

sudo cat /var/log/uwsgi/app/searx.log
https://www.newbserve.xyz/zerobin/?e1e8a858e9644934#v1XcgXhI2urhU2F/3nlSK7QSAKxSP0z2BoDvuispn/Q=
Insecure platform Warning ssl_.py
Researching...
http://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent
sudo /opt/yunohost/searx/bin/pip install requests[security]
sudo cat /var/log/uwsgi/app/searx.log
"Same ERROR"
sudo apt-get install libffi-dev libssl-dev
sudo /opt/yunohost/searx/bin/pip install pyopenssl ndg-httpsclient pyasn1
sudo cat /var/log/uwsgi/app/searx.log
"Same ERROR"
Help @ yunohost.org jappix chat to notice link in zerobin
https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
sudo /opt/yunohost/searx/bin/pip install urllib3[secure]
Testing engines and searches...
sudo cat /var/log/uwsgi/app/searx.log
"No such file or directory"
No ERRORS! SUCCESS

**Comment by alexAubin** [comment]
Moved to the corresponding app issue tracker
