### ISSUE TITLE
Package Framasphère

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#747]
###### Original Redmine Issue: [747](https://dev.yunohost.org/issues/747)

Author Name: **maniack_crudelis**

---

[Framasphère](https://framasphere.org/), réseau social libre
Basé sur [diaspora](https://github.com/diaspora/diaspora/)

Diaspora dispose d'un [package communautaire cassé](https://github.com/aymhce/diaspora_ynh)

**Comment by alexAubin** [comment]
Closing this because there's a mastodon app which imho is more relevant than diaspora nowadays

**Comment by isAAAc** [comment]
Mastodon is more near a twitter-like , not diaspora, there aren't same softs at all, not the same use ...

**Comment by frju365** [comment]
I agree with @isAAAc. Diaspora is not like Mastodon and has not the same goal. De plus, je ne savais pas que Yunohost pratiquait une discrimination au niveau des applications. ;-) Je rajouterai que fermer cette issue manque en quelque sorte autant de respect aux packageurs qui on tenté d'intégrer Diaspora, qu'aux développeurs nombreux ayant contribué au core de Diaspora. :-/

**Comment by frju365** [comment]
Je demanderais donc bien la réouverture de cette issue... sachant que c'est le groupe application qui gère la RoadMap 'dégooglisons-internet' ;-)

**Comment by alexAubin** [comment]
Sorry about that ¯\\\_(ツ)\_/¯ To me those look quite similar but if you have a strong opinion about that, let's reopen the issue :yum:

**Comment by frju365** [comment]
I opened an Issue on redmine for framapiaf (mastodon -- I thought it will open one in Issue here on github, but no). I marked it as resolved
