### ISSUE TITLE
Package Framabookin

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#752]
###### Original Redmine Issue: [752](https://dev.yunohost.org/issues/752)

Author Name: **maniack_crudelis**

---

[Framabookin](https://framabookin.org/), serveur OPDS pour ebooks
Basé sur [BicBucStriim](http://projekte.textmulch.de/bicbucstriim/)

BicBucStriim dispose d'un [package communautaire non terminé](https://github.com/YunoHost-Apps/BicBucStriim_ynh)

**Comment by alexAubin** [comment]
There's also https://github.com/YunoHost-Apps/cops_ynh

**Comment by alexAubin** [comment]
https://github.com/YunoHost-Apps/bicbucstriim_ynh is level 7
