### ISSUE TITLE
Package MyFrama

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#757]
###### Original Redmine Issue: [757](https://dev.yunohost.org/issues/757)

Author Name: **maniack_crudelis**

---

[MyFrama](https://my.framasoft.org/), partage de liens
Basé sur [Shaarli](https://github.com/shaarli/Shaarli/)

Shaarli dispose d'un [package communautaire non terminé](https://github.com/julienmalik/shaarli_ynh)

**Comment by alexAubin** [comment]
Closing because it's actively maintained and flagged as working in community.json :+1:
