### ISSUE TITLE
OpenVPN Connect (Android)

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#76]
###### Original Redmine Issue: [76](https://dev.yunohost.org/issues/76)

Author Name: **Anonymous**

---

https://play.google.com/store/apps/details?id=net.openvpn.openvpn

Download your .opvn

Edit the line '--auth-user-pass' to 'auth-user-pass' without quotes and OpenVPN Connect will ask for your username and password.

The OpenVPN desktop client works, but I am having the same problem as here https://dev.yunohost.org/issues/14 with the Android OpenVPN .

**Comment by alexAubin** [comment]
Closing because this is an old app-related issue ... see work on openvpn_ynh
