### ISSUE TITLE
Let's Encrypt certificate installations on IPv6-only instances

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#769]
###### Original Redmine Issue: [769](https://dev.yunohost.org/issues/769)

Author Name: **moul**

---

Let's Encrypt certificate can't be generated on YunoHost instance IPv6-only as you could see on following logs:

```bash
Erreur : Certificate installation for brique.<domain.tld> failed !
Exception: [Errno 22] Aucun enregistrement DNS « A » n’a été trouvé pour brique.<domain.tld>. De devez faire pointer votre nom de domaine vers votre machine pour être capable d’installer un certificat Let’s Encrypt ! (Si vous savez ce que vous faites, utilisez --no-checks pour désactiver ces contrôles)
```

[More details on discussion about LE integration PR](https://github.com/YunoHost/yunohost/pull/180#pullrequestreview-7769868).

**Comment by alexAubin** [comment]
Relates to https://github.com/YunoHost/issues/issues/959

**Comment by alexAubin** [comment]
Related to https://github.com/YunoHost/issues/issues/229

**Comment by khimaros** [comment]
for what it's worth, i was able to generate Let's Encrypt certs for a host with only an `AAAA` record and an unfiltered ipv6 address (and no `A` record) by running `yunohost domain cert-install --no-checks <domain>`.

caveat, this host did have a (rfc1918) ipv4 address bound and could reach other ipv4 internet addresses via NAT.

**Comment by martinkoutecky** [comment]
Hi - this directly concerns me. I have a home server, my ISP gives IPv6 addresses and I have no intention of buying a public IPv4. It seems that I need a valid ssl cert for my nextcloud to play nice with other nextclouds. But the Let's Encrypt installation does not work because this install is public IPv6 only.

On the other hand I confirm that `yunohost domain cert-install --no-checks <domain>` works as suggested by @khimaros .

**Comment by martinkoutecky** [comment]
OK, I was too quick to say it works :( @khimaros see log here: https://paste.yunohost.org/raw/buruyeberi it fails with "Certificate installation for ... failed". But the certificate was created successfully.

**Comment by khimaros** [comment]
@martinkoutecky -- my guess is that your failure is unrelated to ipv6 or at least unrelated to ipv6 limitations in yunohost. however, the log is not very clear.

you have probably already done this, but just in case, it is necessary to create the domain before installing the cert, either via the web interface or by running `yunohost domain add <domain>`

**Comment by khimaros** [comment]
this issue is related https://github.com/YunoHost/issues/issues/1813

and should be improved when https://github.com/YunoHost/yunohost/pull/1238 is merged.

**Comment by alexAubin** [comment]
Should be fixed by previously mentioned PR
