### ISSUE TITLE
UPnP doesn't works on some routers

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#77]
###### Original Redmine Issue: [77](https://dev.yunohost.org/issues/77)

Author Name: **moul**

---

In my case, with a cubieboard and Freebox ISP, YunoHost is not able to open ports using UPnP. My desktop computer can open ports using UPnP.
This issue also happend to people using Raspberry Pi.
May be this issue is solved with [this](https://github.com/YunoHost/yunohost/commit/349f392c4e538119adcc5852ad3d81367825362e).
I need to try it.

**Comment by alexAubin** [comment]
Closing because of lack of feedback / I don't remind having a lot of people complaining about this :/
