### ISSUE TITLE
"500 Internal Server Error" on user interface after changing user password

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#770]
###### Original Redmine Issue: [770](https://dev.yunohost.org/issues/770)

Author Name: **moul**

---

When logged in, I can't access the user interface.
I changed the password of the user. This might be the cause.
I reproduce it on many web browser.

I couldn't reproduce on a dev env, changing password from SSO. I couldn't change password via CLI or web admin.
I have to retry to see If I reproduce it.

**Comment by alexAubin** [comment]
Should be fixed by https://github.com/YunoHost/SSOwat/pull/114
