### ISSUE TITLE
Display version of the upstream app which will be installed

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#775]
###### Original Redmine Issue: [775](https://dev.yunohost.org/issues/775)

Author Name: **nicofrand**

---

It would be nice if the version of the applications available were displayed.

For example I'd like to install wallabag, but I only want the version 2.2+, not inferior.

On the web administration interface I can't know which one I will install.

**Comment by alexAubin** [comment]
Done in https://github.com/YunoHost/yunohost-admin/pull/235
