### ISSUE TITLE
integrate the "detected blocked ports" inside YunoHost

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#776]
###### Original Redmine Issue: [776](https://dev.yunohost.org/issues/776)

Author Name: **Bram**

---

We have a tool to detect blocked ports, it should be integrate inside YunoHost, for diagnosis and later for automatic notification.

**Comment by alexAubin** [comment]
Related : https://github.com/YunoHost/yunohost/pull/534

**Comment by alexAubin** [comment]
Fixed by the diagnosis system
