### ISSUE TITLE
Allow to modify the name of an installed application

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#782]
###### Original Redmine Issue: [782](https://dev.yunohost.org/issues/782)

Author Name: **nicofrand**

---

It would be great if we could change the name of an application that we installed, through the web interface and through something like 'yunohost app setting [app] name -v "New name"'.

I installed the Redirect app without renaming it, in order to proxy the requests to my CozyCloud instance on port 9104. But now I would like to rename it "Cozy" to make it more clear.

**Comment by alexAubin** [comment]
Solved by https://github.com/YunoHost/yunohost/pull/417 \o/
