### ISSUE TITLE
App access not cleaned after a user has been deleted

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#783]
###### Original Redmine Issue: [783](https://dev.yunohost.org/issues/783)

Author Name: **maxime**

---

App access not cleaned after a user has been deleted

I had a user, which I gave access to a certain app.
Then I deleted this user
And then I noticed the access on the app was really strange looking. See picture attached.

**Comment by alexAubin** [comment]
Should be solved by the new permission system : https://github.com/YunoHost/yunohost/pull/585#pullrequestreview-239169476
