### ISSUE TITLE
Move to gettext

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#788]
###### Original Redmine Issue: [788](https://dev.yunohost.org/issues/788)

Author Name: **Bram**

---

Currently, to add a new message that will be translated in YunoHost you need to :

* invent a key
* call m18n.n(key, **kwargs)
* put this key in another file (en.json)
* there put the string of the actual message

In addition this make code less readable since you only have key and can't see what string is behind that and force you to look at the good key in another file. The more you have to keep context in mind and the more you have indirection, the harder is it to concentrate and program.

In contrast, using gettext would only make you to do:

* write: `_("the string that will be translated %s" % stuff)`

Gettext is also the more or less universal standard to do translation, it's not perfect but has prove its worth since a long time and using it will also avoid the NIH syndrome.

We want to encourage having more useful output, therefor making it easier to write message is a way in that direction in addition of making programming easier (and thus contributions).

**Comment by alexAubin** [comment]
Closing because I doubt it's gonna happen ... our current system is a bit odd and unpractical in some ways, but it works and it's not super worth it to change it i guess ...
