### ISSUE TITLE
Issue with modal window when you click outside of it ...? 

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#789]
###### Original Redmine Issue: [789](https://dev.yunohost.org/issues/789)

Author Name: **jibec**

---

aller dans la page des mises à jour
appuyer sur "Mettre à jour"
un fenêtre contextuelle apparaît
cliquer à côté
la fenêtre disparaît
Rappuyer sur "Mettre à jour" => il ne se passe plus rien.
Actualiser la page envoie une fenêtre contextuelle indiquant : "confirm_update_type"

**Comment by alexAubin** [comment]
My understanding is that it's more related to modal window handling ? (I think I saw this in another issue)

**Comment by alexAubin** [comment]
Related to https://github.com/YunoHost/issues/issues/1287

**Comment by alexAubin** [comment]
Should be fixed by https://github.com/YunoHost/yunohost-admin/commit/c2810a1dcb1a46a65413a83ac244dbb91684f36c
