### ISSUE TITLE
Display a specific error page if someone try to use SSO without any referer instead of a 500

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#79]
###### Original Redmine Issue: [79](https://dev.yunohost.org/issues/79)

Author Name: **moul**

---

When logging to `https:/domain.tld/yunohost/sso` without HTTP referer, I can't be looged to user interface and I get redirected to a white page containing:
```
500 Internal Server Error
nginx/1.6.2
```

You can perform that issue with Firefox in `about:config` by setting `network.http.sendRefererHeader` to `0`. It works with `1` and `2`. [More information about the meaning of this numbers](http://kb.mozillazine.org/Network.http.sendRefererHeader).

If the web browser does not send any HTTP Referer, log-in does not works because of a [CSRF protection](https://en.wikipedia.org/wiki/Cross-Site_Request_Forgery).
However, [using HTTP referer for CSRF protection](https://github.com/Kloadut/SSOwat/blob/unstable/access.lua#L131-L145) could be useless, as it can be spoofed.

I'm using [Random Agent Spoofer](https://github.com/dillbyrne/random-agent-spoofer/) Firefox extension which spoof the referer. Some people could encounter this issue if they changed they Firefox config without knowing it come from that conf.

**Comment by Psycojoker** [comment]
We still periodically get reports from users having this because they have changed shitload on things in their firefox and installed dozens of security plugins.

**Comment by SilverViper** [comment]
I'm unable to reproduce the 500 error in Firefox with network.http.sendRefererHeader set to 0.

**Comment by eauchat** [comment]
I believe this issue is the same as #1495, no?

**Comment by alexAubin** [comment]
Closing because it looks like it was fixed somehow
