### ISSUE TITLE
Manual install on Raspberry Pi fails if user pi doesn't exists

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#791]
###### Original Redmine Issue: [791](https://dev.yunohost.org/issues/791)

Author Name: **alexAubin**

---

As reported here https://forum.yunohost.org/t/installation-sur-un-raspberry-et-user-pi/2482

Relevant piece of code : https://github.com/YunoHost/install_script/blob/31c5dc41fc73206fb30b4dbb8dccb9e349c45325/install_yunohost#L300

**Comment by alexAubin** [comment]
This is fixed in the stretch install script
