### ISSUE TITLE
Display Readme.md of an app in between new app installation page and parameters request

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#792]
###### Original Redmine Issue: [792](https://dev.yunohost.org/issues/792)

Author Name: **maxime**

---

Hi,

It would be really good, in my view, to add an extra step for app installatiosn (officials or community, but especially community).

Would it be possible to display the readme.md (or any other file) of the app, as an extra step, with a dedicated page, in between the admin clicking on "I want to install this app, show me the parameters" and "the page of the parameters".

With two buttons in the bottom : "No, go back" and "Yes, proceed with app parameters"

I don't think it would be a big work, and it would make the admin more aware of the app limitations, potential bugs, extra requirements (for example z-push requiring baikal to have carddav and caldav support), etc, etc. 
For the web interface we could even consider to integrate pictures such as screen-shots of the app (like nextcloud Readme.md)

The same could be done in cli, without the pictures. Not sure about the formatting, but maybe we could impose to have another file than Readme.md and have a specific typo to respect ?

**Comment by Psycojoker** [comment]
I don't think displaying the README would be the best idea, but displaying something is indeed interesting.

**Comment by alexAubin** [comment]
+1

**Comment by alexAubin** [comment]
Related to : https://github.com/YunoHost/issues/issues/1369

**Comment by alexAubin** [comment]
To be adressed by https://github.com/YunoHost/yunohost-admin/pull/486
