### ISSUE TITLE
Exchange in the languages of warning box 

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#795]
###### Original Redmine Issue: [795](https://dev.yunohost.org/issues/795)

Author Name: **kanhu**

---

Hi 

I found a bug which is very minor in nature. Hope I can explain it. 

If **1st** user is logged in which speaks English and simultaneously while the 1st user is still logged in, a **2nd** user who speaks Spanish (or any other language) try a failed attempt to login (incorrect username and password). The warning box languages of both users changes. When the **1st** user logout he see the Spanish warning box and the **2nd** user see the English warning box on refresh.

1. Spanish on English speaker page.
![Logout by 1st user after 2nd user (with other lang) try a fail attempt.
](045.png)
**Logout by 1st user after the 2nd user (with other lang) try a fail attempt.**

2. English on Spanish speaker page.
![Refresh by 2nd user after the 1st user have logged out.
](046.png)
**Refresh by 2nd user after the 1st user have logged out.**

**Comment by alexAubin** [comment]
Meh... this really seems to be a super edge case and we don't have the screenshot anymore and not sure to understand what happened...
