### ISSUE TITLE
Categories apps with tags

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#797]
###### Original Redmine Issue: [797](https://dev.yunohost.org/issues/797)

Author Name: **moul**

---

On https://github.com/YunoHost/Apps, we could create a list of of framasoft apps.
What do you think?
Or, may we simply add them to official and community lists?

**Comment by alexAubin** [comment]
Follow up in https://github.com/YunoHost/issues/issues/1322 ... I have some stuff pending on my machine to start the implementation, and a first piece is https://github.com/YunoHost/yunohost/pull/778
