### ISSUE TITLE
_backup_current_cert crashes if current cert is a broken symlink

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#798]
###### Original Redmine Issue: [798](https://dev.yunohost.org/issues/798)

Author Name: **alexAubin**

---

As reported here : https://forum.yunohost.org/t/installation-le-manuelle-puis-maj-2-5-probleme-de-certificat/2509/3

Not entirely sure that it's because of a broken symlink, but it looks like it given the context.

We probably need to test what's the file type before calling shutil.copytree ?

**Comment by Psycojoker** [comment]
@alexAubin still relevant? It's been more than one year and it's in 2.5

**Comment by alexAubin** [comment]
Hmyep I guess we can close, that might have been caused by some old legacy stuff in the way certificates were managed before.
