### ISSUE TITLE
YunoHost shouldn't consider an app as removed if the remove script fails

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#799]
###### Original Redmine Issue: [799](https://dev.yunohost.org/issues/799)

Author Name: **Bram**

---

Right now, if the remove script for an application fails, YunoHost consider it to be still installed.

This is very problematic because:

* the promote bad practice for the "remove" script where the app packager simply doesn't care about taking possible errors into account
* this can let a partially removed app in the system

This is a very bad design and ends up with broken installations hard to fix for non-technical users. This is a major issue (we recently had a `rm -rf /var/www` because of that).

The "don't consider an app to be uninstall if the remove script failed" part is easy to do, but afterward we need to:

* create a "broken" status for app
* spread this new status everywhere
* allow app to be still updated to received the new `remove` script while not running the `upgrade` script

**Comment by alexAubin** [comment]
(Nowadays we seem to have much less issues about failed remove scripts though)

**Comment by Psycojoker** [comment]
(that tasks should probably be switch to adding a global statut to app like "working" "can_be_updated" "update_failed" "remove_failed" but yes, we have way more robust remove scripts)

**Comment by alexAubin** [comment]
Closing because it's not really an issue nowadays, I can't think of any recent situation where the app left a whole mess after being removed
