### ISSUE TITLE
Modify the way we make the changelog

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#801]
###### Original Redmine Issue: [801](https://dev.yunohost.org/issues/801)

Author Name: **Bram**

---

Right now, the changelog for a new release is built from the git commit history. This tend to be quite a burden since there is a lot of commits and it's not easy to extract what exactly has happen and needs to be written in the changelog.

We want to change this to make release easier and of better quality.

The current discussion around this question make this solution emerge:

* copy the debian/changelog at the root of the project
* for each new PR, update the changelog
* once the release needs to be done, instead of listing the git commit history, simply copy this changelog file
* add the date of the release/finish the changelog
* release

Reference : http://keepachangelog.com/en/0.3.0/

**Comment by alexAubin** [comment]
Closing because nowadays we use a small `make_changelog.sh` script to parse the git log and only keep merge request + lone commits and it's good enough
