### ISSUE TITLE
Create Scaleway ImageHub image

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#804]
###### Original Redmine Issue: [804](https://dev.yunohost.org/issues/804)

Author Name: **opi**

---

https://www.scaleway.com/imagehub/

Scaleway ImageHub seems to be based on docker, but only for disk creation. See https://github.com/scaleway-community/scaleway-cozy and other images on https://github.com/scaleway-community

**Comment by pierreboissinot** [comment]
Hi there ! I'm using yunohost on scaleway for 1 year, if no one is working on this image, I can take a look. It's a good idea to have a click to deploy on scaleway like heroku does.

**Comment by alexAubin** [comment]
Yes absolutely, please have a look !

I dunno how that works exactly, like, if the image is made available, would it appears on Scaleway's interface when people create a server or something ? Or do they need to browse some external website ?

**Comment by pierreboissinot** [comment]
@alexAubin Yes it appears on Scaleway interface as a "community image". You can also fork a community image and do your stuff, then publish your modified image to you scaleway account if you want.
The images choice depends on the server range.
![capture](https://user-images.githubusercontent.com/6716686/50549201-16768700-0c59-11e9-87bf-776c4c8d7346.PNG)

Scaleway community uses [Docker as a tool](https://github.com/scaleway/image-builder) to create a server with custom install instructions, that's is, it does not mean you will run a yunohost instance inside a docker container after installtion.
The scaleway ImageHub is similar with DockerHub if you're familiar with Docker tools.
I'll work on it next week.

**Comment by alexAubin** [comment]
Thanks ! That's looks pretty nice ! I think that would definitely be a high-impact feature in terms of boosting the adoption of YunoHost - especially considering that running the install script if one of the only remaining things for which you absolutely need to use ssh/command line.

**Comment by alexAubin** [comment]
Bump,

by any chance, did you find time to work on this ? :stuck_out_tongue:

**Comment by pierreboissinot** [comment]
@alexAubin Hi, I started something, I just came back from holidays, I'll spend some time on that this week end.

**Comment by pierreboissinot** [comment]
Here's the repo I'm working on : https://github.com/pierreboissinot/scaleway-yunohost .

**Comment by HugoPoi** [comment]
I'm currently digging in this here https://github.com/HugoPoi/scaleway-yunohost
But I'm pretty sure I hit some rocks at the bottom.
## Good news
* my image can be build and deploy on scaleway
## Bad news
* the install script crash but doesn't return exit code > 0 BAD
* /etc/resolv.conf is read only inside a Docker build and Yunohost depends on `resolvconf` package

**Comment by alexAubin** [comment]
Hey there @HugoPoi ! Thanks for the epic work !

Could you share the exact error message ? I believe you might be running into a similar issue that Niels encountered during the brique camp while trying to deploy Yunohost inside podman (some sort of Docker fork from Red Hat)

He used to trick as found in this docker file and docker repo which somebody wrote to be able to install Yunohost inside a docker : https://github.com/domainelibre/YunohostDockerImage/blob/master/preinstall.sh#L19-L22 . There might be some other weird stuff and trickeries to perform.

Though do you know if that mean that the final system will be dockerized ? Our understanding so far is that docker really isn't a good environment to run yunohost inside because of all the constrains, and also because docker is meant to contain a single app and not a "general system manager" like yunohost

**Comment by HugoPoi** [comment]
@alexAubin It seems very promising so I think it will fix it ! I will try this evening I'm at work, I doesn't have the correct setup with me for testing.

**Comment by HugoPoi** [comment]
Seems working like a charm !
I have sent a email to Scaleway for qualifying the image for official InstantApps.

**Comment by alexAubin** [comment]
Wooouw that sounds awesome thank you so much !

**Comment by alexAubin** [comment]
Bump @HugoPoi : did you receive any feedback from Scaleway ? :D 

Edit: ah sorry just saw your tweet ;P

**Comment by HugoPoi** [comment]
Yes I relaunch them yesterday and they give me feedback.

## Bad translation by me
> Thank you for contacting us and taking time to test our services. However, for now, we don't wish to add more images to the Scaleway official list. There is plan in our roadmap, but this is not our priority for now. I advise you to keep your work  on Github and promote it because this is good stuff. Unfortunately Scaleway can't take engagement to maintain this or publish this yet.

## Original
> Merci de nous avoir contacté et d'avoir pris le temps de tester nos instances. Cependant, pour le moment, nous ne souhaitons pas ajouter plus d'images à la liste d'images proposées par Scaleway. Ceci est prévu dans notre roadmap, mais à court terme ce n'est pas notre priorité. Je te conseille de garder ton image sur ton compte GitHub et d'en faire la publicité car c'est du bon travail. Malheureusement Scaleway ne peut pas s'engager pas à la maintenir où à en faire la publier sur le site.

## My thoughts
* I don't now if there is a way of sharing my image without need to rebuilt it across Scaleway accounts.
* Scaleway send signals in 2 different ways, they promote Yunohost and their products on Twitter with manual installation. But doesn't have time to include a image to simplify that.
* Bad timing maybe, but I have faced similar issues with them when I ask if they can tell me about future available hardware and tell me nothing, and few weeks later the general purpose instance were out.

**Comment by alexAubin** [comment]
Hmmmokay,

do you know if there's any way that we could use this image in the meantime ? I thought that when creating a new server, one could use a custom instant app but apparently not now that I recheck the interface ... Or am I missing something ?

**Comment by HugoPoi** [comment]
@alexAubin I have some news
* Yes we can [make a image public](https://developers.scaleway.com/en/products/instance/api/#public-2594ea)
* But the button run on Scaleway is broken, or I can't find the way to make it work

You can now in theory pop a instance with this command `scw run --name=yunohost-test d4b73383-4f82-4e35-8dfd-477cd2d79062`

> https://twitter.com/Scaleway_fr/status/1171379698137477120

**Comment by alexAubin** [comment]
Related to https://github.com/YunoHost/issues/issues/2178

**Comment by alexAubin** [comment]
Closing because the links are pretty much broken, superseded by https://github.com/YunoHost/issues/issues/2178
