### ISSUE TITLE
Disable / remove old rspam.socket and rmilter.socket systemd services 

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#806]
###### Original Redmine Issue: [806](https://dev.yunohost.org/issues/806)

Author Name: **alexAubin**

---

As reported here 

https://forum.yunohost.org/t/etc-yunohost-services-yml-rmilter-socket-et-rspamd-socket-not-active/2505/5

and here

https://forum.yunohost.org/t/dkim-rmilter-error/2526/7

some setups have residual rspam.socket / rmilter.socket which causes some errors/warning in logs. We should find a way to remove them properly (or at least disable them)

**Comment by alexAubin** [comment]
nvm I think it was something like people who edited their postfix conf manually and therefore it didnt get updated by the regenconf ...
