### ISSUE TITLE
On RPi, sometimes rpi-update needs a "yes" during the install_script

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#808]
###### Original Redmine Issue: [808](https://dev.yunohost.org/issues/808)

Author Name: **alexAubin**

---

As reported here https://forum.yunohost.org/t/rpi-installation-problem-unable-to-update-the-system/2544

(also experienced in trotinette)

A simple fix is to add "<<< 'y'" to the line calling raspi-update

**Comment by alexAubin** [comment]
Hm let's close it, that sounds like a minor issue and maybe the behavior changed since then (apparently it was about a particular version upgrade of the kernel etc..)
