### ISSUE TITLE
Add bandwidth details to app infos

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#814]
###### Original Redmine Issue: [814](https://dev.yunohost.org/issues/814)

Author Name: **Thatoo**

---

Hello,

I think it would be great that in each app description here https://yunohost.org/#/apps_fr , it would be said if an app is using a little/moderately/a lot of bandwidth and if that usage is constant (Transmission/searx) or by request (Baikal/Zerobin)...

Thank you,

Thatoo

**Comment by alexAubin** [comment]
Closing because meh
