### ISSUE TITLE
Environment variables in Hooks

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#818]
###### Original Redmine Issue: [818](https://dev.yunohost.org/issues/818)

Author Name: **Scith**

---

Hello,
Would it be possible to have environmental variables in the hooks?
See https://github.com/YunoHost-Apps/rainloop_ynh/blob/master/hooks/post_domain_add#L3
We have app='rainloop', which cannot work in multi-instances
We need to have access to $YNH_APP_INSTANCE_NAME ideally

Thanks

**Comment by alexAubin** [comment]
I'm not sure how this works, but naively that sounds odd that the hook would be fed with an app-related info whereas it's just a general hook about adding a domain ?

Imho if you want to trigger specific stuff related to an app every time a domain is added, you should just have the app id inside the code of the hook ? (so use some template when installing the hook maybe)

**Comment by alexAubin** [comment]
Closing because to me there's no issue ... the hook mentionned by scith could perfectly be added multiple times (using $app in the file name and $app as the value at the beginning of the hook, defined/replaced during the installation of the script just like in other templates)
