### ISSUE TITLE
Raspberry Pi Image SSH Host Keys

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#821]
###### Original Redmine Issue: [821](https://dev.yunohost.org/issues/821)

Author Name: **Kamaluk**

---

I flashed the image multible times - and the SSH Host key didn't change - basically because it might not change on first boot - Could you add the instructions for that at least in the config document? :)

**Comment by alexAubin** [comment]
I think this should be solved for Stretch since we now rely on the build system of raspbian (custom image build) which should handle this appropriately ... nevertheless it should be double-checked
