### ISSUE TITLE
rmilter/rspamd segmentation fault on raspberry pi zero

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#823]
###### Original Redmine Issue: [823](https://dev.yunohost.org/issues/823)

Author Name: **banquise**

---

rmilter and rspamd seem to not work on raspberry pi zero (as well as probably raspberry pi 1).
The issue was firstly reported on this post (in addition with other configuration problems) : https://forum.yunohost.org/t/solved-dkim-rmilter-error/2526
The OP "solved" it by using a respberry pi 3 so we suppose it's caused by differences between armv6/armv7.

**Comment by alexAubin** [comment]
Closing because that's an old issue and we now run Rspamd 1.7 so a lot of things might have changed since then ...

(Feel free to reopen / comment on this issue if you experience this again)
