### ISSUE TITLE
New app helper to handle new variable on upgrade script

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#826]
###### Original Redmine Issue: [826](https://dev.yunohost.org/issues/826)

Author Name: **moul**

---

A package could evolve and use new variables.
To handle upgrade of the app and for futures operations (remove, upgrade, restore), this variable needs to be set otherwise the script fail as the variable is not set.

A helper could be great. This helper could try to retrieve this variable. If it doesn't exist, give it a value set on the script.

**Comment by alexAubin** [comment]
I don't understand this :|

**Comment by alexAubin** [comment]
Ah rereading this it seems pretty clear, could be like a `--default` option of `ynh_setting_get` that would set the default value when the value does not exist ... i dunno if that's worth it or not :|

**Comment by alexAubin** [comment]
Related to the story of config panel and "how to properly declare what settings exist" https://github.com/YunoHost/issues/issues/1973

**Comment by alexAubin** [comment]
cf the new `ynh_app_setting_set_default`
