### ISSUE TITLE
Stupid location for mysql logs

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#845]
###### Original Redmine Issue: [845](https://dev.yunohost.org/issues/845)

Author Name: **alexAubin**

---

Right now mysql logs are set as /var/log/mysql.log and .err, but mysql logs are truly in /var/lib/mysql/$hostname.err (because #MySQLYOLOMACNUGGETS).

c.f. : https://github.com/YunoHost/yunohost/blob/dcdf85260216c682aaf547356635b6b44c0e3ad2/data/templates/yunohost/services.yml#L27

Imho we should either make services.yml point to the actual file (but it depends on hostname é_è) or create a symlink (maybe in regen-conf?) to be put in /var/log/mysql/ ?

Edit: or we should be able to define the log location directly in the conf of mysql

**Comment by alexAubin** [comment]
Nowadays on Stretch it's in /var/log/mysql
