### ISSUE TITLE
Be able to restore mariadb from a complete backup archive even if mariadb is broken

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#847]
###### Original Redmine Issue: [847](https://dev.yunohost.org/issues/847)

Author Name: **ljf**

---

Here is a case where an innodb database was broken and cleaning mysql was needed.

https://forum.yunohost.org/t/resolu-mysql-service-lsb-start-and-stop-the-mysql-database-server-daemon/2648

May be we should put a script or a tool to repair a broken mariadb ?

**Comment by alexAubin** [comment]
Closing because that's not a real issue imho :/ .. If any critical is broken (be it nginx, php or mysql) then yes, some apps can't be installed ... If the purpose is to discuss the inclusion of an autorepair (sigh) for mariadb, feel free to reopen+rename the issue

**Comment by zamentur** [comment]
In some situation, mariadb is broken due to electrical cut.

So when we make a complete restore, we should consider to regenerate mariadb to be able to restore sql dump.

I change the label from bug to enh.

**Comment by alexAubin** [comment]
It's been 5 years and this still feels out of scope, mysql self-corruption have pretty much diappeared, and in the current paradigm we don't really backup the entire mysql setup so this feels like this ticket is going nowhere and should be closed...

**Comment by alexAubin** [comment]
cf previous comment ...
