### ISSUE TITLE
Allow apps to have several functions / part / tiles in ssowat

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#854]
###### Original Redmine Issue: [854](https://dev.yunohost.org/issues/854)

Author Name: **Thatoo**

---

Some apps have several functions. In the case I have in mind, Duniter, it has two functions, one for admin (Duniter) and one public (Cesium).
It would be nice at install to create two tiles then, one in each user panel that open the public function of the app (in my case Cesium), and one in the admin panel of this app that open the admin function of the app (in my case Duniter).

**Comment by alexAubin** [comment]
Will be fixed by the permission system and the integration in ssowat discussed in https://github.com/YunoHost/yunohost/pull/797
