### ISSUE TITLE
Add pagination for apps list and users list in web interface

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#858]
###### Original Redmine Issue: [858](https://dev.yunohost.org/issues/858)

Author Name: **alexAubin**

---

Migrated from https://github.com/YunoHost/yunohost-admin/issues/51

This is also somewhat related to the idea of app market...

**Comment by alexAubin** [comment]
Closing because those pagination things seem really overkill and led to technical mess in the past because  #YANGNI
