### ISSUE TITLE
Help blocks in admin interface

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#860]
###### Original Redmine Issue: [860](https://dev.yunohost.org/issues/860)

Author Name: **alexAubin**

---

Follow-up of https://github.com/YunoHost/yunohost-admin/issues/65

It was kind of started in https://github.com/YunoHost/yunohost-admin/pull/111 but then the PR died :s

**Comment by alexAubin** [comment]
Closing, duplicate of https://github.com/YunoHost/issues/issues/46
