### ISSUE TITLE
Proper port management

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#862]
###### Original Redmine Issue: [862](https://dev.yunohost.org/issues/862)

Author Name: **alexAubin**

---

Follow-up of https://github.com/YunoHost/yunohost-admin/issues/77

also discussed here https://github.com/YunoHost/yunohost/pull/266#issuecomment-285995129

We should have some proper way to manage/list which ports are used by which services/apps, even if they are disabled at the moment.

**Comment by alexAubin** [comment]
Let's close this, the Diagnosis does list ports with corresponding service
