### ISSUE TITLE
Be able to manage user groups

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#864]
###### Original Redmine Issue: [864](https://dev.yunohost.org/issues/864)

Author Name: **alexAubin**

---

Follow-up of https://github.com/YunoHost/yunohost-admin/issues/107

>add user groups in order to ease the access rights for large amounts of users

**Comment by alexAubin** [comment]
WIP : https://github.com/YunoHost/yunohost/pull/585

**Comment by arthurzenika** [comment]
https://github.com/YunoHost/yunohost/pull/585 was merged !

**Comment by alexAubin** [comment]
Indeed !

**Comment by alexAubin** [comment]
(Still to be heavility tested though)
