### ISSUE TITLE
After generating a certificate metronome doesn't works and needs to be restarted again

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#868]
###### Original Redmine Issue: [868](https://dev.yunohost.org/issues/868)

Author Name: **moul**

---

None

**Comment by alexAubin** [comment]
Is it still the case ? It's weird because this line should do the job : https://github.com/YunoHost/yunohost/blob/unstable/src/yunohost/certificate.py#L798 and dates back from Nov. 2016

**Comment by alexAubin** [comment]
Closing because lack of feedback + never seen anybody complain about this :/
