### ISSUE TITLE
Small UI improvements on 'install with yunohost' badge

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#877]
###### Original Redmine Issue: [877](https://dev.yunohost.org/issues/877)

Author Name: **alexAubin**

---

Follow-up of https://dev.yunohost.org/issues/646#note-10
about https://install-app.yunohost.org/
(repo : https://github.com/YunoHost/install-app)

>We were discussing with ju a few minor details :
>- the "power" button before the field "Link to your yunohost server" is a bit weird, maybe we could find something more appropriate
>- the visibility of the "Discover Yunohost" link could be improved
>- maybe handle the case were "app" is empty (i.e. if somebody goes directly to https://install-app.yunohost.org/)

**Comment by alexAubin** [comment]
Those were either solved or not so relevant
