### ISSUE TITLE
Be able to upload a user avatar on the SSO

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#879]
###### Original Redmine Issue: [879](https://dev.yunohost.org/issues/879)

Author Name: **alexAubin**

---

Continuation of https://github.com/YunoHost/SSOwat/issues/12

>Add upload field for user avatar 
>Using the "jpegphoto" ldap field.

**Comment by eauchat** [comment]
I'm interested in working on this issue.  

So I guess what should be implemented is the following:
  - the SSO interface to upload the image - to a temporary location (are there helpers existing already to achieve such kind of uploading tasks, or should they be created?),
  - use the command ldapadd/ldapmodify to add uploaded image to the user's profile,
  - implement the fetching of the avatar in SSO display.

Or is there maybe a more direct or better way to implement that?

**Comment by alexAubin** [comment]
Kinda duplicate of https://github.com/YunoHost/issues/issues/1381

**Comment by alexAubin** [comment]
cf https://github.com/YunoHost/issues/issues/1381#issuecomment-1913277275
