### ISSUE TITLE
Cookie conflicts between different yunohost instances

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#880]
###### Original Redmine Issue: [880](https://dev.yunohost.org/issues/880)

Author Name: **alexAubin**

---

Continuation of https://github.com/YunoHost/SSOwat/issues/22

>i have one ynh instance on mydomain.tld
>i have installed another ynh instance on other.mydomain.tld
>
>the cookies for mydomain.tld interfere with the cookies for other.mydomain.tld
>i cannot connect to other.mydomain.tld without deleting cookies first.
>i cannot be loggued in both sso.

opi seems to have pinpointed the issue : 

>From http://en.wikipedia.org/wiki/HTTP_cookie#Domain_and_Path
>
>    When no "Domain=foo.com" is specified in the cookie, then the cookie will be sent by default for requests to foo.com
>    When setting "Domain=foo.com" is sepecified, the cookie will be sent for requests to foo.com AND every subdomain.
>
>My opinion is that we should remove the "Domain=" from cookie string, in https://github.com/Kloadut/SSOwat/blob/unstable/helpers.lua#L104

**Comment by alexAubin** [comment]
Hmyeah whatever that's a super specific edgecase
