### ISSUE TITLE
Rework app list in the web admin to have an 'app market' / 'app store'

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#881]
###### Original Redmine Issue: [881](https://dev.yunohost.org/issues/881)

Author Name: **alexAubin**

---

Related posts on the forum : 
- https://forum.yunohost.org/t/point-sur-le-projet-et-ameliorations-possibles/1717
- https://forum.yunohost.org/t/developpement-de-lapp-market/2421
- https://forum.yunohost.org/t/app-categories/2235

Also a continuation of https://github.com/YunoHost/SSOwat/issues/23

**Comment by alexAubin** [comment]
Related : https://github.com/YunoHost/yunohost-admin/pull/205

**Comment by alexAubin** [comment]
Idk i'm gonna close this as being fixed by https://github.com/YunoHost/yunohost-admin/pull/205 though still specific improvements are still possible, but the scope of this issue is too large.
