### ISSUE TITLE
Handle extra debian repositories with regen-conf system

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#885]
###### Original Redmine Issue: [885](https://dev.yunohost.org/issues/885)

Author Name: **moul**

---

It would be great to handle a list of extra debian repositories with current regen-conf tool.

It could be used for Prosody, Rspamd, Node.js.

**Comment by alexAubin** [comment]
Closing, nowadays we have the ynh_install_extra_dependencies helper etc.
