### ISSUE TITLE
Manifest file with two "en" keys

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#887]
###### Original Redmine Issue: [887](https://dev.yunohost.org/issues/887)

Author Name: **jibec**

---

hi,

Weblate told me I had same English and French content, but in fact, there is two "en" keys for the same string: https://translate.yunohost.org/translate/yunohost/apps/fr/?sid=b751298a-186a-11e7-8ecd-00224da69287

I created this ticket so the package maintainer can fix his application [1], but can we do/have something to prevent this?

[1] https://github.com/chtixof/chtickynotes_ynh/issues/4

**Comment by Jibec** [comment]
@alexAubin what do you think about moving this issue to https://github.com/YunoHost/package_linter ?

**Comment by alexAubin** [comment]
Eh yes I guess though unfortunately it's not trivial to have a clean check but yea we can look into it

**Comment by Jibec** [comment]
please close this issue (by the way, I don't understand why we can't close issues, like any other github project)

**Comment by alexAubin** [comment]
Because you're not the author of the issue anymore I think ... (it got imported from redmine)
