### ISSUE TITLE
Manifest with empty string

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#888]
###### Original Redmine Issue: [888](https://dev.yunohost.org/issues/888)

Author Name: **jibec**

---

hi, it should not be possible to have empty strings: https://translate.yunohost.org/translate/yunohost/apps/en/?checksum=d58917cc9bea10e3

I created this ticket so the package maintainer can fix his application [1], but can we do/have something to prevent this?

[1] https://github.com/abeudin/proftpd_ynh/issues/1

**Comment by Jibec** [comment]
@alexAubin what do you think about moving this issue to https://github.com/YunoHost/package_linter ?

**Comment by alexAubin** [comment]
Yup

**Comment by Jibec** [comment]
please close this issue (by the way, I don't understand why we can't close issues, like any other github project)

**Comment by alexAubin** [comment]
Because you're not the author of the issue anymore I think ... (it got imported from redmine)
