### ISSUE TITLE
Mail sender address should only have registered domains 

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#891]
###### Original Redmine Issue: [891](https://dev.yunohost.org/issues/891)

Author Name: **kanhu**

---

Hi

Currently only illegitimate emails like user@192.168.3.3 are restricted by postfix. A registered user can send email from any non registered domain too . So if the domain Yunohost.org or gmail.com is not registered with my server, I still can send email from sender address from these domains. eg user@yunohost.org and user@gmail.com. (By using identities in email clients like roundcube,outlook etc)
![Adding  identity under setting in roundcube](Selection_057.png) 

![Sending mail form the new created identity](Selection_058.png)

There should be sender envelop restriction to registered domains only.
Future there should be username and alias check with the From address of the email, so that the spaming from the server can be checked and stopped.

**Comment by alexAubin** [comment]
>A registered user can send email from any non registered domain too

Closing because i don't understand this ... To me the current postfix config only allows to send emails using either your main email address, or an alias, and the users' alias can only correspond to a registered domain ... Closing because this is 7 years old
