### ISSUE TITLE
Always make app install verbose via CLI

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#894]
###### Original Redmine Issue: [894](https://dev.yunohost.org/issues/894)

Author Name: **moul**

---

- Remove `--verbose` option.

- Add `-q` and/or `--quiet` options to quiet logs.

**Comment by Psycojoker** [comment]
related https://github.com/YunoHost/issues/issues/971

**Comment by alexAubin** [comment]
Closing this following recent changes ... now apps have a mechanism to display custom info messages to tell what they're doing.
