### ISSUE TITLE
Reduce the amount of string to translate for application // standardize strings

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#896]
###### Original Redmine Issue: [896](https://dev.yunohost.org/issues/896)

Author Name: **jibec**

---

Hi,

We have 788 strings to translate for application manifests: https://translate.yunohost.org/projects/yunohost/apps/#information
No big deal, but there is a huge amount of 

127 strings: "Choose a domain for %%%", where %%% is the app name.
20 strings: "Choose a domain name for %%%"
136 phrases "Choose a path %%%"
22 strings to select admin
74 strings to tell if the application should be publicly accessible or private

Translate a lot is ok, but it makes the translator feel like a robot...

Can we suggest maintainers not to use the application name in questions?
Can we provide maintainers standard question to ask to user so we only have one string to translate?
Any other ideas?

**Comment by alexAubin** [comment]
Done
