### ISSUE TITLE
Force delete backups that cannot be retrieved anymore

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#899]
###### Original Redmine Issue: [899](https://dev.yunohost.org/issues/899)

Author Name: **Scith**

---

Hello,
I did a backup on a distant folder, unmounted the distant folder. The backup still appears in 'yunohost backup list', but cannot be accessed anymore so I cannot delete it.
Similar issue: I did a backup, then moved it to a different location. The backup still appears in 'yunohost backup list' as well, and cannot be deleted it.

So perhaps 'yunohost backup delete' could remove the backup entry from the database if the backup cannot be located anymore?
Or more complicated, another command or flag to purge backups that cannot be located?

Thanks

**Comment by Psycojoker** [comment]
@zamentur still relevant?

**Comment by alexAubin** [comment]
Closing because maybe fixed when we merged the .info.json into the archive itself
