### ISSUE TITLE
Add a notification system for the applications

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#9]
###### Original Redmine Issue: [9](https://dev.yunohost.org/issues/9)

Author Name: **Anonymous**

---

First proposal here: [#62 (comment)](https://github.com/YunoHost/yunohost/issues/62#issuecomment-119847121)

The idea is to implement a notification system for the applications in order to inform users while installing/upgrading/removing an app. We can implement it in mainly two ways:

messages are specified in the manifest for several defined moment - e.g. pre-install, post-remove
a command allows - directly from the scripts - to display a message
Feel free to give your opinion, purpose better implementations, ... Thanks!

**Comment by SilverViper** [comment]
Solved with ynh_script_progression?

**Comment by alexAubin** [comment]
Closing, superseded by https://github.com/YunoHost/issues/issues/1957
