### ISSUE TITLE
Implements human readable date for `yunohost app listlists` command. 

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#901]
###### Original Redmine Issue: [901](https://dev.yunohost.org/issues/901)

Author Name: **opi**

---

Sample output by now:

```bash
root@yunohost:~# yunohost app listlists
labriqueinternet: 
  lastUpdate: 1492064710
  url: https://labriqueinter.net/apps/labriqueinternet.json
yunohost: 
  lastUpdate: 1492064710
  url: https://app.yunohost.org/official.json
```

I would like to have a `-H` option to output lastUpdate date in a human readable format.

**Comment by alexAubin** [comment]
Burn the applist management :fire: :fire: :fire:

**Comment by cyxae** [comment]
This command doesn’t exist anymore…

**Comment by alexAubin** [comment]
Indeed, let's close this
