### ISSUE TITLE
Properly manage app status

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#902]
###### Original Redmine Issue: [902](https://dev.yunohost.org/issues/902)

Author Name: **alexAubin**

---

Follow-up of https://dev.yunohost.org/issues/764

Right now the way the app status if manage is really ambiguous in many places. Right now an app is either "installed" or "not installed", and is defined by checking if the app settings file exists. However it would greatly help to have a least : 
- a status "ongoing installation" (c.f. some app helpers that are called during installation with weird behavior regarding the app currently being installeD)
- a status "broken" (c.f. the discussion about failure during remove script execution)

One idea could be to have an app setting set to "installed", "installing" or "broken".

**Comment by alexAubin** [comment]
Closing because not a big deal anymore
