### ISSUE TITLE
Handle remove script that fails (and/or mitigate possible bad effects)

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#904]
###### Original Redmine Issue: [904](https://dev.yunohost.org/issues/904)

Author Name: **alexAubin**

---

Follow-up of https://dev.yunohost.org/issues/419 : 

>for the remove script, as we have discussed with Bram, we have 2 antinomic problems.
>
>    One hand, set -u will prevent destructive delete
>    Other hand, in this case, the remove script was abort. So the app is in a middle state, not really removed, but not installed anymore. So, you can't remove it, because the app is not installed. But also you can't reinstall because the install script can fail on some residual files.

the issue of "how to handle remove scripts that fails" was discussed during the meeting of the 4th April : https://pad.lqdn.fr/p/yunohost-04-04-2017

From what I remember, the main points and conclusion were :

- ynh_secure_remove + the app CI will avoid a good 90% of the issues related to remove script that fails (typically removing /var/www)
- However, this does not provide full coverage of all possible and imaginable issues (e.g. we don't have a strategy for remove scripts which would inadvertendly drop all mysql db's). This is related to the fact that we cannot test every possible configuration and that we don't have a mechanism to know which files an app is legitim to remove.
- We definetely need a "broken" status for apps, because it'll always be possible that the remove script crashes in the middle of the removing, and there's no way to automatically fix stuff from that point. This require human intervention or downloading a new, more up-to-date remove script

We defined the following action items :

* Generalize the use of ynh_secure_remove :
   * Search rm -Rf in all apps and replace by ynh_secure_remove : "sed s/rm -Rf/ynh_secure_remove/g"
   * Add some checks to the linter : rm shouldnt be used directly in the remove script. Also, wildcards (*) shouldn't be used with ynh_secure_remove (e.g. refuse to have stuff like ynh_secure_remove /etc/toto/*.conf).
* In ynh_secure_remove itself : refuse to do anything if there's more than one argument given (to avoid accidental wildcard ('*') usage)
* Add set -eu automatically (in core) before execution of remove script
* Add a test in CI to check we don't delete some file in some part of the system /var/www/foo /etc/nginx/conf.d/$domain.d/foo.conf
* Define a 'broken' status for apps for when remove script crashes. The user should be able to upgrade the app scripts (in particular the remove script) and re-run the remove script even if the app is flagged as broken, to fix the issue. The user should also be able to declare the app as 'manually removed' for when a newer remove script is not available (being understood that he takes the responsability to have correctly fixed stuff). In any case, provided that the previous points are implemented, encountering the 'broken' status situation should be rare.

**Comment by alexAubin** [comment]
Dunno if we still need this issue to be opened ... a lot of progress was made since then on app quality and I don't think I heard about catastrophic "remove" failures in a long time.

Nowadays shit like the whole PHP 7.x dependency story, or docker-ce breaking dpkg, or fail2ban failures during failed upgrade are the biggest issues
