### ISSUE TITLE
API KEY for applications with mobile client

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#905]
###### Original Redmine Issue: [905](https://dev.yunohost.org/issues/905)

Author Name: **maniack_crudelis**

---

As discussed on the "apps" xmpp room, we encounter some issues with apps when we try to use a mobile client (or any distant client).

So, the problem is pretty simple.
Either your app is public, and all is ok, or it's private, and your client doesn't access to your app. And the client has no way to access to your app, because, it can't pass through the sso.

So scith and I have an idea, use a "key", like an api key.
Just a random key that you can add to your url to pass through the sso.

The idea behind this concept is:

- If you try to access to `domain.tld/myapp`, the sso will block you.
- But if you try to access to `domain.tld/myapp/mykey`, the sso allow you to access.
But, after that, your app can't respond to mykey, so you need to rewrite this url to remove the key.

I use this rewrite rule, into my location directive:
`rewrite "^/myapp/mykey/(.*)$" "/myapp/$1" last;`

It works fine with nginx. But not with the sso...
In fact, it seems that nginx rewrite the url, then the sso match the url and doesn't allow to continue...

To be continued...

**Comment by alexAubin** [comment]
Closing because meh, that sounds like the issue of "the SSO should support SAML stuff", cf all the tickets about 2FA / advanced SSO technics
