### ISSUE TITLE
Allow hook execution of non-bash scripts ?

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#911]
###### Original Redmine Issue: [911](https://dev.yunohost.org/issues/911)

Author Name: **alexAubin**

---

Right now hooks are systematically runned with /bin/bash (or sh ?) which makes it really complicated to have pure-python or whichever language.

Not sure how we could easily run other languages (for instance an option of hook_exec is specifically to enable the xtrace (?) on a bash script but there's no equivalent in python afaik)

**Comment by alexAubin** [comment]
Fixed via https://github.com/YunoHost/yunohost/pull/747
