### ISSUE TITLE
Log users out of apps when they logout of YunoHost

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#913]
###### Original Redmine Issue: [913](https://dev.yunohost.org/issues/913)

Author Name: **Scith**

---

Hello,
It would be nice to have a mechanism to log users out of apps when they log out of YunoHost.

Perhaps:
1. Cookie based? Apps define the auth cookie in settings or manifest. When users logout, all the corresponding cookies are destroyed.
2. Or with a post_user_logout hook? Apps can define in their hooks how to logout, for instance by CURLing the logout URL on behalf of the user?

Thanks

**Comment by Psycojoker** [comment]
Close as duplicate of https://github.com/YunoHost/issues/issues/501
