### ISSUE TITLE
open firewall port 80 on renew of certs

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#917]
###### Original Redmine Issue: [917](https://dev.yunohost.org/issues/917)

Author Name: **ZeHiro**

---

On renewing the LE certs, yunohost should first check if port 80 is opened, if not open it. Renew the certs and close the port if it was before.
Could be extented to cert first generation

**Comment by Psycojoker** [comment]
In which situation does that ever happen :| ?

That really looks like an edgecase from users doing custom stuff.

**Comment by freechelmi** [comment]
I think this is needed for cert creation but does not seem needed for renew

**Comment by alexAubin** [comment]
Closing because meh
