### ISSUE TITLE
Add self-signed certificate warning in doc for newbies (post-install)

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#922]
###### Original Redmine Issue: [922](https://dev.yunohost.org/issues/922)

Author Name: **Zykino**

---

Maybe the warning page of self signed certificate (with screenshot for Firefox and Chrome) could be added to the tutorial.
The first time you see it you would not think of "ok self signed certificate, everything is normal".

And in the post install tutorial: "your server is ready to go, now the next recommended task is to set up let's encrypt for your server like so...". Have a redirect to example.com/yunohost/admin/#/domains/example.com at the end of the post-install is also a solution (after the first log in for peoples who did the post-install on cli.

As a best practice tell the user to not save the exception permanently for the first log-in (since the certificate will be switched to a let's encrypt one).

(The other solution I see is to have already set up the let's encrypt certificate by the time an user log in there for the first time. Maybe not expected by experienced user and I heard it's not possible.)

**Comment by decentral1se** [comment]
Unsure if there is more to do on this. I find the documentation quite nice now:

* https://yunohost.org/#/postinstall
* https://yunohost.org/#/certificate

**Comment by alexAubin** [comment]
Meh idk let's close this then
