### ISSUE TITLE
Cannot import wallabag v1 articles into wallabag v2

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#923]
###### Original Redmine Issue: [923](https://dev.yunohost.org/issues/923)

Author Name: **Gofannon**

---

Hello,

1. Issue detail

When importing my "wallabag 1 export file" to "wallabag 2.3.3" (see pic 1), yunohost shows the error **413 Request entity too large** (pic 2)

1. Debug process

After checking the [wallabag nginx documentation](https://doc.wallabag.org/en/admin/installation/virtualhosts.html#configuration-on-nginx) and the [web](https://github.com/wallabag/wallabag/issues/1849), I added the following to my nginx :

  ~~~ python
  vim /etc/nginx/conf.d/myDomain.d/wallabag2.conf

  location / {
  [...]
    client_max_body_size 10M;
  [...]
  ~~~

After a nginx reload and a new import, I got the php error **500: Internal Error** (pic 3) and a clue about **"upload_max_filesize"**

I had to add the following to the php configuration and `reload php5-fpm`

~~~ python

vim /etc/php5/fpm/pool.d/wallabag2.conf

[...]
php_value[upload_max_filesize] = 50M
php_value[post_max_size] = 50M
~~~

See [yunohost example package](https://github.com/YunoHost/example_ynh/blob/master/conf/php-fpm.conf) or other php config :

~~~
root@yunohost:# grep -R upload_max /etc/php5/fpm
./pool.d/sonerezh.conf:;php_value[upload_max_filesize] = 50M
./pool.d/kanboard.conf:php_value[upload_max_filesize] = 10G
./pool.d/nextcloud.conf:php_value[upload_max_filesize] = 10G
./pool.d/roundcube.conf:php_value[upload_max_filesize] = 10G
./php.ini:upload_max_filesize = 2M
~~~

Now, I get a **504 Gateway Time-out** in my browser (pic 4).

I will try with the **cli import** to see if it runs better : https://doc.wallabag.org/en/user/import/#import-via-command-line-interface-cli

**Comment by alexAubin** [comment]
Old app issue, probably not relevant anymore...
