### ISSUE TITLE
problème de header dans nextcloud —> lien SSOwat

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#924]
###### Original Redmine Issue: [924](https://dev.yunohost.org/issues/924)

Author Name: **valerian**

---

Je crois avoir trouvé une manière de résoudre  (violemment) le problème qui fait qu'il est nécessaire de recharger la page de nextcloud après connexion via SSOwat (que d'aucuns proposent de résoudre en supprimant purement et simplement les CSP https://github.com/YunoHost-Apps/nextcloud_ynh/pull/28). 

On a déjà identifié que c'était les headers qui posaient problème. Je crois que ça semble venir du connexion: keep-alive qui est renvoyé par défaut par le serveur. 

Quand je rajoute ngx.header["Connection"] = "close" là (https://github.com/YunoHost/SSOwat/blob/fc52f05459c8db8b6fbf72d1255f51cf07ae442a/access.lua#L27), tout fonctionne et j'ai plus le problème, mais 

1. je sais pas ce que je fais 
2. je pense que ça ralentit le chargement parce qu'il va réétablir la connexion pour chaque script (?) 

et donc je voudrais savoir s'il est possible de fermer la connexion une fois après l'authentification puis la réouvrir en keep-alive ensuite ?

**Comment by alexAubin** [comment]
I guess this is solved now ...
