### ISSUE TITLE
Consistent ciphersuite between programs

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#94]
###### Original Redmine Issue: [93](https://dev.yunohost.org/issues/93)

Author Name: **Bouska**

---

[Ciphersuite](https://en.wikipedia.org/wiki/Cipher_suite) determine the security parameters of an TLS connection, and as the result the security level and compatibility. Currently, each program has a custom list of ciphersuites allowed. I propose to use an unique list of ciphersuites shared by all the programs to assure a consistent level of security. 

Mozilla provides a [ciphersuite list](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28default.29) (you can also read this [stack exchange topic](http://security.stackexchange.com/questions/76993/now-that-it-is-2015-what-ssl-tls-cipher-suites-should-be-used-in-a-high-securit))which provides a good balance between security  and compatibility. This list is mainly provided for HTTPS connections, so it would be wise to analyze its compatibility with SSH/SMTPS/IMAPS/POP3S/XMPP/etc. clients. By default, this concerns (at least) OpenSSH, Postfix, Dovecot, metronome and ngnix.

Blocks issue #91

**Comment by alexAubin** [comment]
Thinking about this, I don't know how this goal really is realistic to have "consistent ciphersuites between programs". To me it sounds like different protocols have different constrains (so e.g. web vs. ssh vs. mail vs ...) related to compatibility (web browsers, other mail servers, ...) such that this can't realistically happen...

**Comment by alexAubin** [comment]
Closing because the issue is much more complex than having consistent cipher suites between programs, there's a lot of consideration depending on what the program does, and what is supported by the program and what's relevant to do.
