### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#96]
###### Original Redmine Issue: [95](https://dev.yunohost.org/issues/95)

Author Name: **Bouska**

---

[HTTP/2](https://en.wikipedia.org/wiki/HTTP/2) is the second major version of the HTTP network protocol and provides some improvements over HTTP/1.1. Enabling HTTP/2 requires nginx 1.9.5 and OpenSSL 1.0.2 (ALPN support). Those version are only available on Debian Stretch, which will become stable at the end of 2016.

**Comment by alexAubin** [comment]
Reopening because we had to disable it due to a few issue (for instance the CI reporting weird errors with wordpress)

**Comment by alexAubin** [comment]
This was discussed recently in this thread : https://forum.yunohost.org/t/yunohost-3-http2/5590

According to Josue, the issue we encountered with Wordpress should be easy to fix with a simple sleep before calling ynh_local_curl right away

(cc @Josue-T @frju365 )

**Comment by frju365** [comment]
Can we close this Issue ?
